OpenMAMA Java API: com.wombat.mama.MamaSourceManager Class Reference
com.wombat.mama.MamaSourceManager Class Reference
A Mama source manager maintains information about a set of data sources, including the quality of the data coming from sources.
Inherited by com.wombat.mama.MamaSource.
Public Member Functions
MamaSourceManager ()
Constructor - creates a new MamaSourceManager object.
MamaSource findOrCreateSource (final String sourceName)
Locates an existing mamaSource for a given name, if none exists a new one is created and added to the source manager.
MamaSource findSource (final String sourceName)
locates an existing source for a given name, if none is found null is returned, The caller has to validate null value on return.
void addSource (MamaSource mamaSource)
Add an existing mama Source to the source manager.
void addSource (MamaSource mamaSource, final String sourceName)
Add an existing mama Source to the source manager.
int getSize ()
Return the size of the contents of source manager.
Iterator sourceIterator ()
void destroy ()
Detailed Description
A Mama source manager maintains information about a set of data sources, including the quality of the data coming from sources.
Constructor & Destructor Documentation
MamaSourceManager()
com.wombat.mama.MamaSourceManager.MamaSourceManager ()
Constructor - creates a new MamaSourceManager object.
thread safe hashmap
References com.wombat.mama.MamaSource.setId().
Member Function Documentation
findOrCreateSource()
MamaSource com.wombat.mama.MamaSourceManager.findOrCreateSource (final String sourceName)
Locates an existing mamaSource for a given name, if none exists a new one is created and added to the source manager.
Parameters
sourceName The string identifier for the mamaSource
Returns
MamaSource
findSource()
MamaSource com.wombat.mama.MamaSourceManager.findSource (final String sourceName)
locates an existing source for a given name, if none is found null is returned, The caller has to validate null value on return.
Parameters
sourceName The string identifier for the MamaSource
Returns
MamaSource
Referenced by com.wombat.mama.MamaSourceDerivative.findSourceDerivative().
addSource() [1/2]
void com.wombat.mama.MamaSourceManager.addSource (MamaSource mamaSource)
Add an existing mama Source to the source manager.
The id of the source will be used instead of the name to identify the source within the source manager.
Parameters
mamaSource an existing mama source
References com.wombat.mama.MamaSource.getId().
Referenced by com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative().
addSource() [2/2]
void com.wombat.mama.MamaSourceManager.addSource (MamaSource mamaSource, final String sourceName)
Add an existing mama Source to the source manager.
The name will used to uniquely identify the source within the source manager.
Parameters
mamaSource an existing mama source
sourceName The string identifier for the MamaSource
References com.wombat.mama.MamaSource.setMappedId().
getSize()
int com.wombat.mama.MamaSourceManager.getSize ()
Return the size of the contents of source manager.
sourceIterator()
Iterator com.wombat.mama.MamaSourceManager.sourceIterator ()
Referenced by com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative().
destroy()
void com.wombat.mama.MamaSourceManager.destroy ()