OpenMAMA Java API: com.wombat.mama.MamaReservedFields Class Reference
com.wombat.mama.MamaReservedFields Class Reference
Public Member Functions
MamaReservedFields (String name, int id)
String getName ()
Return the name of the reserved field.
int getId ()
Return the id of the reserved field.
Static Public Attributes
static final MamaReservedFields MsgType
Field for the message type.
static final MamaReservedFields MsgStatus
Field for the message status.
static final MamaReservedFields FieldIndex
Field containing the index in the data dictionary.
static final MamaReservedFields MsgFields
Field containing the fields in the data dictionary.
static final MamaReservedFields SubscMsgTypeOld
Used internally for subscription management (deprecated).
static final MamaReservedFields SubscMsgSubjectOld
Used internally for subscription management (deprecated).
static final MamaReservedFields MsgNum
Field containing the current message number in a multi-part initial message.
static final MamaReservedFields MsgTotal
The total number of messages comprising an initial message.
static final MamaReservedFields TibrvResult
The RV result code.
static final MamaReservedFields SeqNum
The sequence number.
static final MamaReservedFields FeedName
The dictionary source feed name.
static final MamaReservedFields FeedHost
The dictionary source feed host.
static final MamaReservedFields SyncPattern
That pattern that subjects of a sync request should match.
static final MamaReservedFields ItemSeqNum
The item sequence number.
static final MamaReservedFields SendTime
The Message send time.
static final MamaReservedFields AppDataType
The application data type.
static final MamaReservedFields AppMsgType
The application message type.
static final MamaReservedFields SenderId
The sender id.
static final MamaReservedFields MsgQualifier
The message qualifier.
static final MamaReservedFields ElvinSource
static final MamaReservedFields ElvinSourceOld
static MamaReservedFields SubscriptionType
static final MamaReservedFields SubscMsgType
static final MamaReservedFields SubscSourceHost
static MamaReservedFields SubscSourceApp
static final MamaReservedFields SubscSourceUser
static final MamaReservedFields SubscSymbol
static final MamaReservedFields SymbolList
static final MamaReservedFields EntitleCode
static final short MAX_RESERVED_FID = 100
Constructor & Destructor Documentation
MamaReservedFields()
com.wombat.mama.MamaReservedFields.MamaReservedFields (String name, int id)
Member Function Documentation
getName()
String com.wombat.mama.MamaReservedFields.getName ()
Return the name of the reserved field.
Returns
The name.
Referenced by com.wombat.mama.MamaMsgStatus.statusForMsg(), com.wombat.mama.MamaMsgType.typeForMsg(), and com.wombat.mama.MamaMdMsgType.typeForMsg().
getId()
int com.wombat.mama.MamaReservedFields.getId ()
Return the id of the reserved field.
Returns
The id.
Referenced by com.wombat.mama.MamaMsgStatus.statusForMsg(), com.wombat.mama.MamaMsgType.typeForMsg(), and com.wombat.mama.MamaMdMsgType.typeForMsg().
Member Data Documentation
MsgType
final MamaReservedFields com.wombat.mama.MamaReservedFields.MsgType static
Initial value:
=
         new MamaReservedFields( "MdMsgType", 1)
Field for the message type.
See also
com.wombat.mama.MamaMsgType
Referenced by com.wombat.mama.MamaMsgType.typeForMsg().
MsgStatus
final MamaReservedFields com.wombat.mama.MamaReservedFields.MsgStatus static
Initial value:
=
         new MamaReservedFields( "MdMsgStatus", 2 )
Field for the message status.
See also
com.wombat.mama.MamaMsgStatus
Referenced by com.wombat.mama.MamaMsgStatus.statusForMsg().
FieldIndex
final MamaReservedFields com.wombat.mama.MamaReservedFields.FieldIndex static
Initial value:
=
         new MamaReservedFields( "MdFieldIndex", 3 )
Field containing the index in the data dictionary.
MsgFields
final MamaReservedFields com.wombat.mama.MamaReservedFields.MsgFields static
Initial value:
=
       new MamaReservedFields( "MdMsgFields", 4 )
Field containing the fields in the data dictionary.
This is an array.
SubscMsgTypeOld
final MamaReservedFields com.wombat.mama.MamaReservedFields.SubscMsgTypeOld static
Initial value:
=
        new MamaReservedFields( "MdSubscType", 5 )
Used internally for subscription management (deprecated).
SubscMsgSubjectOld
final MamaReservedFields com.wombat.mama.MamaReservedFields.SubscMsgSubjectOld static
Initial value:
=
         new MamaReservedFields( "MdSubscSubject", 6 )
Used internally for subscription management (deprecated).
MsgNum
final MamaReservedFields com.wombat.mama.MamaReservedFields.MsgNum static
Initial value:
=
         new MamaReservedFields( "MdMsgNum", 7 )
Field containing the current message number in a multi-part initial message.
See also
com.wombat.mama.MamaReservedFields::MsgTotal
MsgTotal
final MamaReservedFields com.wombat.mama.MamaReservedFields.MsgTotal static
Initial value:
=
         new MamaReservedFields( "MdMsgTotal", 8 )
The total number of messages comprising an initial message.
TibrvResult
final MamaReservedFields com.wombat.mama.MamaReservedFields.TibrvResult static
Initial value:
=
        new MamaReservedFields( "MdTibrvResult", 9 )
The RV result code.
SeqNum
final MamaReservedFields com.wombat.mama.MamaReservedFields.SeqNum static
Initial value:
=
        new MamaReservedFields( "MdSeqNum", 10)
The sequence number.
FeedName
final MamaReservedFields com.wombat.mama.MamaReservedFields.FeedName static
Initial value:
=
        new MamaReservedFields( "MdFeedName", 11)
The dictionary source feed name.
FeedHost
final MamaReservedFields com.wombat.mama.MamaReservedFields.FeedHost static
Initial value:
=
        new MamaReservedFields( "MdFeedHost", 12)
The dictionary source feed host.
SyncPattern
final MamaReservedFields com.wombat.mama.MamaReservedFields.SyncPattern static
Initial value:
=
        new MamaReservedFields( "MdSyncPattern", 14 )
That pattern that subjects of a sync request should match.
ItemSeqNum
final MamaReservedFields com.wombat.mama.MamaReservedFields.ItemSeqNum static
Initial value:
=
        new MamaReservedFields ("MdItemSeq", 15)
The item sequence number.
SendTime
final MamaReservedFields com.wombat.mama.MamaReservedFields.SendTime static
Initial value:
=
        new MamaReservedFields ("MamaSendTime", 16)
The Message send time.
AppDataType
final MamaReservedFields com.wombat.mama.MamaReservedFields.AppDataType static
Initial value:
=
        new MamaReservedFields ("MamaAppDataType", 17)
The application data type.
AppMsgType
final MamaReservedFields com.wombat.mama.MamaReservedFields.AppMsgType static
Initial value:
=
        new MamaReservedFields ("MamaAppMsgType", 18)
The application message type.
Referenced by com.wombat.mama.MamaMdMsgType.typeForMsg().
SenderId
final MamaReservedFields com.wombat.mama.MamaReservedFields.SenderId static
Initial value:
=
        new MamaReservedFields ("MamaSenderId", 20)
The sender id.
This identifies the feed handler sending the message. This may change in the event of a fault tolerant take over. Mama handles this situation internally.
MsgQualifier
final MamaReservedFields com.wombat.mama.MamaReservedFields.MsgQualifier static
Initial value:
=
        new MamaReservedFields ("wMsgQual", 21)
The message qualifier.
See also
MamaMsg for details.
ElvinSource
final MamaReservedFields com.wombat.mama.MamaReservedFields.ElvinSource static
Initial value:
=
        new MamaReservedFields( "MdElvinSource", 55 )
ElvinSourceOld
final MamaReservedFields com.wombat.mama.MamaReservedFields.ElvinSourceOld static
Initial value:
=
        new MamaReservedFields( "MdSubscSource", 64 )
SubscriptionType
MamaReservedFields com.wombat.mama.MamaReservedFields.SubscriptionType static
Initial value:
=
        new MamaReservedFields( "MdSubscriptionType", 60)
SubscMsgType
final MamaReservedFields com.wombat.mama.MamaReservedFields.SubscMsgType static
Initial value:
=
        new MamaReservedFields( "MdSubscMsgType", 61 )
SubscSourceHost
final MamaReservedFields com.wombat.mama.MamaReservedFields.SubscSourceHost static
Initial value:
=
        new MamaReservedFields( "MdSubscSourceHost", 63 )
SubscSourceApp
MamaReservedFields com.wombat.mama.MamaReservedFields.SubscSourceApp static
Initial value:
=
        new MamaReservedFields( "MdSubscSourceApp", 64)
SubscSourceUser
final MamaReservedFields com.wombat.mama.MamaReservedFields.SubscSourceUser static
Initial value:
=
        new MamaReservedFields( "MdSubscSourceUser", 65 )
SubscSymbol
final MamaReservedFields com.wombat.mama.MamaReservedFields.SubscSymbol static
Initial value:
=
        new MamaReservedFields( "MdSubscSymbol", 71 )
SymbolList
final MamaReservedFields com.wombat.mama.MamaReservedFields.SymbolList static
Initial value:
=
        new MamaReservedFields( "MamaSymbolList", 81 )
EntitleCode
final MamaReservedFields com.wombat.mama.MamaReservedFields.EntitleCode static
Initial value:
=
        new MamaReservedFields ( "wEntitleCode", 496)
MAX_RESERVED_FID
final short com.wombat.mama.MamaReservedFields.MAX_RESERVED_FID = 100 static