OpenMAMA Java API: com.wombat.mama.MamaDispatcher Class Reference
com.wombat.mama.MamaDispatcher Class Reference
Public Member Functions
long getPointerVal ()
native void create (MamaQueue queue)
native boolean isDispatching ()
native void destroy ()
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaDispatcher.getPointerVal ()
References com.wombat.mama.MamaDispatcher.create(), com.wombat.mama.MamaDispatcher.destroy(), and com.wombat.mama.MamaDispatcher.isDispatching().
create()
native void com.wombat.mama.MamaDispatcher.create (MamaQueue queue)
Referenced by com.wombat.mama.MamaDispatcher.getPointerVal(), com.wombat.mama.MamaQueueGroup.MamaQueueGroup(), and com.wombat.mama.MamaQueueGroup.startDispatch().
isDispatching()
native boolean com.wombat.mama.MamaDispatcher.isDispatching ()
Referenced by com.wombat.mama.MamaDispatcher.getPointerVal().
destroy()
native void com.wombat.mama.MamaDispatcher.destroy ()
Referenced by com.wombat.mama.MamaDispatcher.getPointerVal(), and com.wombat.mama.MamaQueueGroup.stopDispatch().