OpenMAMA Java API: com.wombat.mama.MamaLogFilePolicy Class Reference
com.wombat.mama.MamaLogFilePolicy Class Reference
Public Member Functions
int getValue ()
Static Public Member Functions
static MamaLogFilePolicy tryStringToLogPolicy (String policy)
Static Public Attributes
static final MamaLogFilePolicy UNBOUNDED = new MamaLogFilePolicy(1)
static final MamaLogFilePolicy ROLL = new MamaLogFilePolicy(2)
static final MamaLogFilePolicy OVERWRITE = new MamaLogFilePolicy(3)
static final MamaLogFilePolicy USER = new MamaLogFilePolicy(4)
Member Function Documentation
getValue()
int com.wombat.mama.MamaLogFilePolicy.getValue ()
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
tryStringToLogPolicy()
static MamaLogFilePolicy com.wombat.mama.MamaLogFilePolicy.tryStringToLogPolicy (String policy) static
References com.wombat.mama.MamaLogFilePolicy.OVERWRITE, com.wombat.mama.MamaLogFilePolicy.ROLL, com.wombat.mama.MamaLogFilePolicy.UNBOUNDED, and com.wombat.mama.MamaLogFilePolicy.USER.
Member Data Documentation
UNBOUNDED
final MamaLogFilePolicy com.wombat.mama.MamaLogFilePolicy.UNBOUNDED = new MamaLogFilePolicy(1) static
Referenced by com.wombat.mama.MamaLogFilePolicy.tryStringToLogPolicy().
ROLL
final MamaLogFilePolicy com.wombat.mama.MamaLogFilePolicy.ROLL = new MamaLogFilePolicy(2) static
Referenced by com.wombat.mama.MamaLogFilePolicy.tryStringToLogPolicy().
OVERWRITE
final MamaLogFilePolicy com.wombat.mama.MamaLogFilePolicy.OVERWRITE = new MamaLogFilePolicy(3) static
Referenced by com.wombat.mama.MamaLogFilePolicy.tryStringToLogPolicy().
USER
final MamaLogFilePolicy com.wombat.mama.MamaLogFilePolicy.USER = new MamaLogFilePolicy(4) static
Referenced by com.wombat.mama.MamaLogFilePolicy.tryStringToLogPolicy().