OpenMAMA Java API: com.wombat.mama.Mama Class Reference
com.wombat.mama.Mama Class Reference
Static Public Member Functions
static native MamaBridge loadBridge (String middleware, String path)
static MamaBridge loadBridge (String middleware)
static native MamaPayloadBridge loadPayloadBridge (String name)
static native MamaQueue getDefaultQueue (MamaBridge bridge)
static native void open ()
Initialize MAMA.
static native void open (String path, String filename)
Initialize MAMA.
static native void start (MamaBridge bridge)
Start processing messages on the internal queue.
static native void startBackground (MamaBridge bridge, MamaStartBackgroundCallback callback)
Start processing MAMA internal events in the background.
static native void stop (MamaBridge bridge)
Stop dispatching on the default event queue for the specified bridge.
static native void close ()
Close MAMA and free all associated resource.
static void enableLogging (Level level)
static void setLogCallback (MamaLogFileCallback2 callback) throws IllegalArgumentException
static void log (MamaLogLevel level, String message)
static void enableLogging (Level level, String file) throws FileNotFoundException
static void logToFile (String file, Level level) throws FileNotFoundException
static void disableLogging ()
static Level getLogLevel ()
static void setLogLevel (Level level)
static void setLogFilePolicy (MamaLogFilePolicy policy)
static native String getProperty (String name)
static native void setProperty (String name, String value)
static native void setLogSize (long size)
static native void setNumLogFiles (int numFiles)
static native void setAppendToLogFile (boolean append)
static native boolean loggingToFile ()
static native void setLogSizeCb (MamaLogFileCallback callback)
static MamaLogLevel getMamaLogLevelForLevel (Level level)
static int getMamaLevelForLevel (Level level)
static native void setApplicationName (String applicationName)
static native void setApplicationClassName (String applicationClassName)
static native String getApplicationName ()
static native String getApplicationClassName ()
static native String getCUserName ()
static native String getCHostName ()
static String getUserName ()
getUserName get the user name for the application
static String getHostName ()
getHostName get the host name of the machine
static String getIpAddress ()
getIpAddress get the ip address of the machine
static String getVersion (MamaBridge bridge)
static native int getLastErrorCode ()
static String getLastErrorText ()
Member Function Documentation
loadBridge() [1/2]
static native MamaBridge com.wombat.mama.Mama.loadBridge (String middleware, String path) static
Referenced by com.wombat.mama.Mama.loadBridge().
loadBridge() [2/2]
static MamaBridge com.wombat.mama.Mama.loadBridge (String middleware) static
References com.wombat.mama.Mama.close(), com.wombat.mama.Mama.getDefaultQueue(), com.wombat.mama.Mama.loadBridge(), com.wombat.mama.Mama.loadPayloadBridge(), com.wombat.mama.Mama.open(), com.wombat.mama.Mama.start(), com.wombat.mama.Mama.startBackground(), and com.wombat.mama.Mama.stop().
loadPayloadBridge()
static native MamaPayloadBridge com.wombat.mama.Mama.loadPayloadBridge (String name) static
Referenced by com.wombat.mama.Mama.loadBridge().
getDefaultQueue()
static native MamaQueue com.wombat.mama.Mama.getDefaultQueue (MamaBridge bridge) static
Referenced by com.wombat.mama.MamaQueueGroup.getNextQueue(), and com.wombat.mama.Mama.loadBridge().
open() [1/2]
static native void com.wombat.mama.Mama.open () static
Initialize MAMA.
MAMA employs a reference count to track multiple calls to Mama.open() and Mama.close(). The count is incremented every time Mama.open() is called and decremented when Mama.close() is called. The resources are not actually released until the count reaches zero.
If entitlements are enabled for the library, the available entitlement server names are read from the entitlement.servers property in the mama.properties file located in the $WOMBAT_PATH directory.
This function is thread safe.
Referenced by com.wombat.mama.Mama.loadBridge().
open() [2/2]
static native void com.wombat.mama.Mama.open (String path, String filename) static
Initialize MAMA.
Allows users of the API to override the default behavior of Mama.open() where a file mama.properties is required to be located in the directory specified by $WOMBAT_PATH.
The properties file must have the same structure as a standard mama.properties file.
If null is passed as the path the API will look for the properties file on the $WOMBAT_PATH.
If null is passed as the filename the API will look for the default filename of mama.properties.
Parameters
path Fully qualified path to the directory containing the properties file
filename The name of the file containing MAMA properties.
start()
static native void com.wombat.mama.Mama.start (MamaBridge bridge) static
Start processing messages on the internal queue.
This starts Mama's internal throttle, refresh logic, and other internal Mama processes as well as dispatching messages from the internal queue.
Mama.start() blocks until an invocation of Mama.stop() occurs.
MAMA employs a reference count to track multiple calls to Mama.start() and Mama.stop(). The count is incremented every time Mama.start() is called and decremented when Mama.stop() is called. The first Mama.start() call does not unblock until the count reaches zero.
This function is thread safe.
Parameters
bridge The bridge specific structure.
Referenced by com.wombat.mama.Mama.loadBridge().
startBackground()
static native void com.wombat.mama.Mama.startBackground (MamaBridge bridge, MamaStartBackgroundCallback callback) static
Start processing MAMA internal events in the background.
This method invokes Mama::start () in a separate thread.
Parameters
bridge The middleware-specific bridge structure
callback The callback for asynchronous status.
Referenced by com.wombat.mama.Mama.loadBridge().
stop()
static native void com.wombat.mama.Mama.stop (MamaBridge bridge) static
Stop dispatching on the default event queue for the specified bridge.
MAMA employs a reference count to track multiple calls to Mama.start() and Mama.stop(). The count is incremented every time Mama.start() is called and decremented when Mama.stop() is called. The first Mama.start() call does not unblock until the count reaches zero.
This function is thread safe.
Parameters
bridge The bridge specific structure.
Referenced by com.wombat.mama.Mama.loadBridge().
close()
static native void com.wombat.mama.Mama.close () static
Close MAMA and free all associated resource.
MAMA employs a reference count to track multiple calls to Mama.open() and Mama.close(). The count is incremented every time Mama.open() is called and decremented when Mama.close() is called. The resources are not actually released until the count reaches zero.
This function is thread safe.
Referenced by com.wombat.mama.Mama.loadBridge().
enableLogging() [1/2]
static void com.wombat.mama.Mama.enableLogging (Level level) static
References com.wombat.mama.MamaLogLevel.getMamaLogLevel(), com.wombat.mama.MamaLogFileCallback2.onLog(), and com.wombat.mama.Mama.setLogCallback().
Referenced by com.wombat.mama.Mama.logToFile().
setLogCallback()
static void com.wombat.mama.Mama.setLogCallback (MamaLogFileCallback2 callback) throws IllegalArgumentException static
Referenced by com.wombat.mama.Mama.enableLogging().
log()
static void com.wombat.mama.Mama.log (MamaLogLevel level, String message) static
References com.wombat.mama.MamaLogLevel.getValue().
enableLogging() [2/2]
static void com.wombat.mama.Mama.enableLogging (Level level, String file) throws FileNotFoundException static
References com.wombat.mama.Mama.logToFile().
logToFile()
static void com.wombat.mama.Mama.logToFile (String file, Level level) throws FileNotFoundException static
References com.wombat.mama.Mama.enableLogging(), and com.wombat.mama.Mama.getMamaLogLevelForLevel().
Referenced by com.wombat.mama.Mama.enableLogging(), and com.wombat.mama.Mama.setLogFilePolicy().
disableLogging()
static void com.wombat.mama.Mama.disableLogging () static
getLogLevel()
static Level com.wombat.mama.Mama.getLogLevel () static
References com.wombat.mama.MamaLogLevel.getLevel(), and com.wombat.mama.MamaLogLevel.getMamaLogLevel().
setLogLevel()
static void com.wombat.mama.Mama.setLogLevel (Level level) static
References com.wombat.mama.Mama.getMamaLogLevelForLevel().
setLogFilePolicy()
static void com.wombat.mama.Mama.setLogFilePolicy (MamaLogFilePolicy policy) static
References com.wombat.mama.Mama.getProperty(), com.wombat.mama.MamaLogFilePolicy.getValue(), com.wombat.mama.Mama.loggingToFile(), com.wombat.mama.Mama.logToFile(), com.wombat.mama.Mama.setAppendToLogFile(), com.wombat.mama.Mama.setLogSize(), com.wombat.mama.Mama.setLogSizeCb(), com.wombat.mama.Mama.setNumLogFiles(), and com.wombat.mama.Mama.setProperty().
getProperty()
static native String com.wombat.mama.Mama.getProperty (String name) static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
setProperty()
static native void com.wombat.mama.Mama.setProperty (String name, String value) static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
setLogSize()
static native void com.wombat.mama.Mama.setLogSize (long size) static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
setNumLogFiles()
static native void com.wombat.mama.Mama.setNumLogFiles (int numFiles) static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
setAppendToLogFile()
static native void com.wombat.mama.Mama.setAppendToLogFile (boolean append) static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
loggingToFile()
static native boolean com.wombat.mama.Mama.loggingToFile () static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
setLogSizeCb()
static native void com.wombat.mama.Mama.setLogSizeCb (MamaLogFileCallback callback) static
Referenced by com.wombat.mama.Mama.setLogFilePolicy().
getMamaLogLevelForLevel()
static MamaLogLevel com.wombat.mama.Mama.getMamaLogLevelForLevel (Level level) static
References com.wombat.mama.MamaLogLevel.getMamaLogLevel().
Referenced by com.wombat.mama.Mama.logToFile(), and com.wombat.mama.Mama.setLogLevel().
getMamaLevelForLevel()
static int com.wombat.mama.Mama.getMamaLevelForLevel (Level level) static
References com.wombat.mama.Mama.getApplicationClassName(), com.wombat.mama.Mama.getApplicationName(), com.wombat.mama.Mama.getCHostName(), com.wombat.mama.Mama.getCUserName(), com.wombat.mama.Mama.setApplicationClassName(), and com.wombat.mama.Mama.setApplicationName().
Referenced by com.wombat.mama.MamaLogHandler.publish().
setApplicationName()
static native void com.wombat.mama.Mama.setApplicationName (String applicationName) static
Referenced by com.wombat.mama.Mama.getMamaLevelForLevel().
setApplicationClassName()
static native void com.wombat.mama.Mama.setApplicationClassName (String applicationClassName) static
Referenced by com.wombat.mama.Mama.getMamaLevelForLevel().
getApplicationName()
static native String com.wombat.mama.Mama.getApplicationName () static
Referenced by com.wombat.mama.Mama.getMamaLevelForLevel().
getApplicationClassName()
static native String com.wombat.mama.Mama.getApplicationClassName () static
Referenced by com.wombat.mama.Mama.getMamaLevelForLevel().
getCUserName()
static native String com.wombat.mama.Mama.getCUserName () static
Referenced by com.wombat.mama.Mama.getMamaLevelForLevel(), and com.wombat.mama.Mama.getUserName().
getCHostName()
static native String com.wombat.mama.Mama.getCHostName () static
Referenced by com.wombat.mama.Mama.getHostName(), and com.wombat.mama.Mama.getMamaLevelForLevel().
getUserName()
static String com.wombat.mama.Mama.getUserName () static
getUserName get the user name for the application
Returns
String the user name
References com.wombat.mama.Mama.getCUserName().
getHostName()
static String com.wombat.mama.Mama.getHostName () static
getHostName get the host name of the machine
Returns
String the hostname
References com.wombat.mama.Mama.getCHostName().
getIpAddress()
static String com.wombat.mama.Mama.getIpAddress () static
getIpAddress get the ip address of the machine
Returns
String the IP address
getVersion()
static String com.wombat.mama.Mama.getVersion (MamaBridge bridge) static
References com.wombat.mama.Mama.getLastErrorCode().
getLastErrorCode()
static native int com.wombat.mama.Mama.getLastErrorCode () static
Referenced by com.wombat.mama.Mama.getLastErrorText(), and com.wombat.mama.Mama.getVersion().
getLastErrorText()
static String com.wombat.mama.Mama.getLastErrorText () static
References com.wombat.mama.Mama.getLastErrorCode(), and com.wombat.mama.MamaError.toString().