OpenMAMA Java API: com.wombat.mama.MamaSubscriptionState Class Reference
com.wombat.mama.MamaSubscriptionState Class Reference
This class is the java equivalent of the C subscription state enumeration.
Public Member Functions
int getValue ()
Returns the integer representation of the subscription state.
String toString ()
This function returns the string representation of the member state.
Static Public Member Functions
static MamaSubscriptionState getSubscriptionState (int state)
This function converts the integer state value to a corresponding MamaSubscriptionState object.
static MamaSubscriptionState parseSubscriptionState (String state)
This function will return the subscription state corresponding to the supplied string.
static String toString (int state)
This function returns the string representation of the state.
static String toString (MamaSubscriptionState state)
This function returns the string representation of the state.
Static Public Attributes
static final MamaSubscriptionState MAMA_SUBSCRIPTION_UNKNOWN = new MamaSubscriptionState(0)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_ALLOCATED = new MamaSubscriptionState(1)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_SETUP = new MamaSubscriptionState(2)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_ACTIVATING = new MamaSubscriptionState(3)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_ACTIVATED = new MamaSubscriptionState(4)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_DEACTIVATING = new MamaSubscriptionState(5)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_DEACTIVATED = new MamaSubscriptionState(6)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_DESTROYING = new MamaSubscriptionState(7)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_DESTROYED = new MamaSubscriptionState(8)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_DEALLOCATING = new MamaSubscriptionState(9)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_DEALLOCATED = new MamaSubscriptionState(10)
static final MamaSubscriptionState MAMA_SUBSCRIPTION_REACTIVATING = new MamaSubscriptionState(11)
Detailed Description
This class is the java equivalent of the C subscription state enumeration.
Member Function Documentation
getValue()
int com.wombat.mama.MamaSubscriptionState.getValue ()
Returns the integer representation of the subscription state.
Returns
The state as an integer.
getSubscriptionState()
static MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.getSubscriptionState (int state) static
This function converts the integer state value to a corresponding MamaSubscriptionState object.
Parameters
state The state.
Returns
To return the MamaSusbscriptionState instance.
References com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ACTIVATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ACTIVATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ALLOCATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEACTIVATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEACTIVATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEALLOCATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEALLOCATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DESTROYED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DESTROYING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_REACTIVATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_SETUP, and com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_UNKNOWN.
Referenced by com.wombat.mama.MamaBasicSubscription.getState(), and com.wombat.mama.MamaSubscription.getState().
parseSubscriptionState()
static MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.parseSubscriptionState (String state) static
This function will return the subscription state corresponding to the supplied string.
Note that if the string is not recognised then MAMA_SUBSCRIPTION_UNKNOWN will be returned.
Parameters
state
Returns
The corresponding state object or MAMA_SUBSCRIPTION_UNKNOWN if the string isn't recognised.
References com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ACTIVATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ACTIVATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ALLOCATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEACTIVATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEACTIVATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEALLOCATED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEALLOCATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DESTROYED, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DESTROYING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_REACTIVATING, com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_SETUP, and com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_UNKNOWN.
toString() [1/3]
static String com.wombat.mama.MamaSubscriptionState.toString (int state) static
This function returns the string representation of the state.
Parameters
state The state.
Returns
The string representation.
toString() [2/3]
static String com.wombat.mama.MamaSubscriptionState.toString (MamaSubscriptionState state) static
This function returns the string representation of the state.
Parameters
state The state.
Returns
The string representation.
References com.wombat.mama.MamaSubscriptionState.toString().
toString() [3/3]
String com.wombat.mama.MamaSubscriptionState.toString ()
This function returns the string representation of the member state.
Returns
The string representation.
Referenced by com.wombat.mama.MamaSubscriptionState.toString().
Member Data Documentation
MAMA_SUBSCRIPTION_UNKNOWN
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_UNKNOWN = new MamaSubscriptionState(0) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_ALLOCATED
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ALLOCATED = new MamaSubscriptionState(1) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_SETUP
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_SETUP = new MamaSubscriptionState(2) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_ACTIVATING
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ACTIVATING = new MamaSubscriptionState(3) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_ACTIVATED
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_ACTIVATED = new MamaSubscriptionState(4) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_DEACTIVATING
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEACTIVATING = new MamaSubscriptionState(5) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_DEACTIVATED
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEACTIVATED = new MamaSubscriptionState(6) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_DESTROYING
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DESTROYING = new MamaSubscriptionState(7) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_DESTROYED
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DESTROYED = new MamaSubscriptionState(8) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_DEALLOCATING
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEALLOCATING = new MamaSubscriptionState(9) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_DEALLOCATED
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_DEALLOCATED = new MamaSubscriptionState(10) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().
MAMA_SUBSCRIPTION_REACTIVATING
final MamaSubscriptionState com.wombat.mama.MamaSubscriptionState.MAMA_SUBSCRIPTION_REACTIVATING = new MamaSubscriptionState(11) static
Referenced by com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaSubscriptionState.parseSubscriptionState().