OpenMAMA Java API: com.wombat.mama.MamaConnection Class Reference
com.wombat.mama.MamaConnection Class Reference
Public Member Functions
MamaConnection (MamaTransport transport, String ipAddress, int port, int maxQueueSize, int curQueueSize, int msgCount, int bytesSent, String userName, String appName)
native void destroy ()
native MamaTransport getTransport ()
native String getIpAddress ()
native int getPort ()
native String getUserName ()
native String getAppName ()
native int getMaxQueueSize ()
native int getQueueSize ()
native int getMsgCount ()
native int getBytesSent ()
native String toString ()
native boolean isIntercepted ()
Constructor & Destructor Documentation
MamaConnection()
com.wombat.mama.MamaConnection.MamaConnection (MamaTransport transport, String ipAddress, int port, int maxQueueSize, int curQueueSize, int msgCount, int bytesSent, String userName, String appName)
References com.wombat.mama.MamaConnection.destroy(), com.wombat.mama.MamaConnection.getAppName(), com.wombat.mama.MamaConnection.getBytesSent(), com.wombat.mama.MamaConnection.getIpAddress(), com.wombat.mama.MamaConnection.getMaxQueueSize(), com.wombat.mama.MamaConnection.getMsgCount(), com.wombat.mama.MamaConnection.getPort(), com.wombat.mama.MamaConnection.getQueueSize(), com.wombat.mama.MamaConnection.getTransport(), com.wombat.mama.MamaConnection.getUserName(), com.wombat.mama.MamaConnection.isIntercepted(), and com.wombat.mama.MamaConnection.toString().
Member Function Documentation
destroy()
native void com.wombat.mama.MamaConnection.destroy ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getTransport()
native MamaTransport com.wombat.mama.MamaConnection.getTransport ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getIpAddress()
native String com.wombat.mama.MamaConnection.getIpAddress ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getPort()
native int com.wombat.mama.MamaConnection.getPort ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getUserName()
native String com.wombat.mama.MamaConnection.getUserName ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getAppName()
native String com.wombat.mama.MamaConnection.getAppName ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getMaxQueueSize()
native int com.wombat.mama.MamaConnection.getMaxQueueSize ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getQueueSize()
native int com.wombat.mama.MamaConnection.getQueueSize ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getMsgCount()
native int com.wombat.mama.MamaConnection.getMsgCount ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
getBytesSent()
native int com.wombat.mama.MamaConnection.getBytesSent ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
toString()
native String com.wombat.mama.MamaConnection.toString ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().
isIntercepted()
native boolean com.wombat.mama.MamaConnection.isIntercepted ()
Referenced by com.wombat.mama.MamaConnection.MamaConnection().