OpenMAMA Java API: com.wombat.mama.MamaBasicSubscription Class Reference
com.wombat.mama.MamaBasicSubscription Class Reference
Public Member Functions
MamaBasicSubscription ()
The constructor allocates the underlying C subscription.
void createBasicSubscription (final MamaBasicSubscriptionCallback callback, final MamaTransport transport, final MamaQueue queue, final String topic, final Object closure)
Create a basic subscription without marketdata semantics.
void createBasicWildCardSubscription (final MamaBasicWildCardSubscriptionCallback callback, final MamaTransport transport, final MamaQueue queue, final String source, final String topic, final Object closure)
Object getClosure ()
This function returns the closure supplied to the createSubscription function.
long getPointerVal ()
This function returns the pointer to the underlying C subscription.
MamaSubscriptionState getState ()
This function returns the current state of the subscription as one of the MamaSubscriptionState instances, see this class for more information.
native void deallocate ()
De-allocates the underlying C subscription.
native void destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
native void destroyEx ()
This function will destroy the subscription and can be called from any thread.
native String getSymbol ()
This function returns the symbol subscribed to.
Protected Member Functions
void finalize () throws Throwable
The finalizer deallocates the underlying C subscritpion.
Constructor & Destructor Documentation
MamaBasicSubscription()
com.wombat.mama.MamaBasicSubscription.MamaBasicSubscription ()
The constructor allocates the underlying C subscription.
Member Function Documentation
finalize()
void com.wombat.mama.MamaBasicSubscription.finalize () throws Throwable protected
The finalizer deallocates the underlying C subscritpion.
Exceptions
Throwable A MamaException will be thrown if the underlying subscription could not be de-allocated.
References com.wombat.mama.MamaBasicSubscription.deallocate().
createBasicSubscription()
void com.wombat.mama.MamaBasicSubscription.createBasicSubscription (final MamaBasicSubscriptionCallback callback, final MamaTransport transport, final MamaQueue queue, final String topic, final Object closure)
Create a basic subscription without marketdata semantics.
Parameters
callback The object implementing the callback functions.
transport The MamaTransport.
queue The MamaQueue.
topic The symbol name.
closure The closure will be passed to subsequent callback invocations for this subscription.
createBasicWildCardSubscription()
void com.wombat.mama.MamaBasicSubscription.createBasicWildCardSubscription (final MamaBasicWildCardSubscriptionCallback callback, final MamaTransport transport, final MamaQueue queue, final String source, final String topic, final Object closure)
getClosure()
Object com.wombat.mama.MamaBasicSubscription.getClosure ()
This function returns the closure supplied to the createSubscription function.
Returns
The closure object.
getPointerVal()
long com.wombat.mama.MamaBasicSubscription.getPointerVal ()
This function returns the pointer to the underlying C subscription.
Returns
The pointer.
getState()
MamaSubscriptionState com.wombat.mama.MamaBasicSubscription.getState ()
This function returns the current state of the subscription as one of the MamaSubscriptionState instances, see this class for more information.
Returns
The MamaSubscriptionState that represents the current state of the subscription.
References com.wombat.mama.MamaBasicSubscription.deallocate(), com.wombat.mama.MamaBasicSubscription.destroy(), com.wombat.mama.MamaBasicSubscription.destroyEx(), com.wombat.mama.MamaSubscriptionState.getSubscriptionState(), and com.wombat.mama.MamaBasicSubscription.getSymbol().
deallocate()
native void com.wombat.mama.MamaBasicSubscription.deallocate ()
De-allocates the underlying C subscription.
This can be used to reduce time during finalization.
Referenced by com.wombat.mama.MamaBasicSubscription.finalize(), and com.wombat.mama.MamaBasicSubscription.getState().
destroy()
native void com.wombat.mama.MamaBasicSubscription.destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
Use destroyEx to destroy the subscription from any thread. Note that the subscription will not be fully destroyed until the onDestroy callback is received.
Referenced by com.wombat.mama.MamaBasicSubscription.getState().
destroyEx()
native void com.wombat.mama.MamaBasicSubscription.destroyEx ()
This function will destroy the subscription and can be called from any thread.
Note that the subscription will not be fully destroyed until the onDestroy callback is received. To destroy from the dispatching thread the destroy function should be used in preference.
Referenced by com.wombat.mama.MamaBasicSubscription.getState().
getSymbol()
native String com.wombat.mama.MamaBasicSubscription.getSymbol ()
This function returns the symbol subscribed to.
Returns
The symbol.
Referenced by com.wombat.mama.MamaBasicSubscription.getState().