OpenMAMA Java API: com.wombat.mama.MamaFtMember Class Reference
com.wombat.mama.MamaFtMember Class Reference
Public Member Functions
MamaFtMember ()
native void destroy ()
native void activate ()
native void deactivate ()
native boolean isActive ()
native String getGroupName ()
native int getWeight ()
native double getHeartbeatInterval ()
native double getTimeoutInterval ()
native void setWeight (int weight)
native void setInstanceId (String id)
native void setupFtMember (short ftType, MamaQueue queue, MamaFtCallback callback, MamaTransport transport, String groupName, int weight, double heartbeatInterval, double timeoutInterval)
Protected Member Functions
void finalize ()
Constructor & Destructor Documentation
MamaFtMember()
com.wombat.mama.MamaFtMember.MamaFtMember ()
References com.wombat.mama.MamaFtMember.activate(), com.wombat.mama.MamaFtMember.deactivate(), com.wombat.mama.MamaFtMember.destroy(), com.wombat.mama.MamaFtMember.getGroupName(), com.wombat.mama.MamaFtMember.getHeartbeatInterval(), com.wombat.mama.MamaFtMember.getTimeoutInterval(), com.wombat.mama.MamaFtMember.getWeight(), com.wombat.mama.MamaFtMember.isActive(), com.wombat.mama.MamaFtMember.setInstanceId(), com.wombat.mama.MamaFtMember.setupFtMember(), and com.wombat.mama.MamaFtMember.setWeight().
Member Function Documentation
destroy()
native void com.wombat.mama.MamaFtMember.destroy ()
Referenced by com.wombat.mama.MamaFtMember.finalize(), and com.wombat.mama.MamaFtMember.MamaFtMember().
activate()
native void com.wombat.mama.MamaFtMember.activate ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
deactivate()
native void com.wombat.mama.MamaFtMember.deactivate ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
isActive()
native boolean com.wombat.mama.MamaFtMember.isActive ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
getGroupName()
native String com.wombat.mama.MamaFtMember.getGroupName ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
getWeight()
native int com.wombat.mama.MamaFtMember.getWeight ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
getHeartbeatInterval()
native double com.wombat.mama.MamaFtMember.getHeartbeatInterval ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
getTimeoutInterval()
native double com.wombat.mama.MamaFtMember.getTimeoutInterval ()
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
setWeight()
native void com.wombat.mama.MamaFtMember.setWeight (int weight)
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
setInstanceId()
native void com.wombat.mama.MamaFtMember.setInstanceId (String id)
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
setupFtMember()
native void com.wombat.mama.MamaFtMember.setupFtMember (short ftType, MamaQueue queue, MamaFtCallback callback, MamaTransport transport, String groupName, int weight, double heartbeatInterval, double timeoutInterval)
Referenced by com.wombat.mama.MamaFtMember.MamaFtMember().
finalize()
void com.wombat.mama.MamaFtMember.finalize () protected
References com.wombat.mama.MamaFtMember.destroy().