OpenMAMA Java API: com.wombat.mama.MamaPrice Class Reference
com.wombat.mama.MamaPrice Class Reference
Inherits Comparable.
Public Member Functions
MamaPrice ()
MamaPrice (double value)
MamaPrice (double value, MamaPricePrecision precision)
MamaPrice (MamaPrice src)
int hashCode ()
boolean equals (Object obj)
int compareTo (Object obj)
void add (MamaPrice value)
void add (double value)
void subtract (MamaPrice value)
void subtract (double value)
native void clear ()
void set (double priceValue, MamaPriceHints hints)
native void setValue (double value)
void setPrecision (MamaPricePrecision precision)
void setHints (MamaPriceHints hints)
native double getValue ()
double getRoundedValue ()
This function obtains the double value of the price rounded to zero precision.
double getRoundedValue (MamaPricePrecision precision)
This function obtains the double value of the price rounded to the supplied precision.
MamaPricePrecision getPrecision ()
MamaPriceHints getHints ()
native String toString ()
void negate ()
boolean isZero ()
native void setIsValidPrice (boolean valid)
native boolean getIsValidPrice ()
native void copy (MamaPrice price)
native void destroy ()
Static Public Attributes
static final double EPSILON = 0.00000000001
MAMA_PRICE_EPSILON a value that is considered equivalent to zero.
Protected Member Functions
long getPointerVal ()
Object clone () throws CloneNotSupportedException
void finalize ()
Constructor & Destructor Documentation
MamaPrice() [1/4]
com.wombat.mama.MamaPrice.MamaPrice ()
Referenced by com.wombat.mama.MamaPrice.clone(), and com.wombat.mama.MamaPrice.compareTo().
MamaPrice() [2/4]
com.wombat.mama.MamaPrice.MamaPrice (double value)
References com.wombat.mama.MamaPricePrecision.PRECISION_100, and com.wombat.mama.MamaPrice.setValue().
MamaPrice() [3/4]
com.wombat.mama.MamaPrice.MamaPrice (double value, MamaPricePrecision precision)
References com.wombat.mama.MamaPrice.setPrecision(), and com.wombat.mama.MamaPrice.setValue().
MamaPrice() [4/4]
com.wombat.mama.MamaPrice.MamaPrice (MamaPrice src)
References com.wombat.mama.MamaPrice.copy().
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaPrice.getPointerVal () protected
Referenced by com.wombat.mama.MamaMsgField.getPrice(), and com.wombat.mama.MamaMsg.getPrice().
hashCode()
int com.wombat.mama.MamaPrice.hashCode ()
References com.wombat.mama.MamaPrice.getValue().
clone()
Object com.wombat.mama.MamaPrice.clone () throws CloneNotSupportedException protected
References com.wombat.mama.MamaPrice.MamaPrice().
equals()
boolean com.wombat.mama.MamaPrice.equals (Object obj)
References com.wombat.mama.MamaPrice.getValue().
compareTo()
int com.wombat.mama.MamaPrice.compareTo (Object obj)
References com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.MamaPrice().
add() [1/2]
void com.wombat.mama.MamaPrice.add (MamaPrice value)
References com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.setValue().
add() [2/2]
void com.wombat.mama.MamaPrice.add (double value)
References com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.setValue().
subtract() [1/2]
void com.wombat.mama.MamaPrice.subtract (MamaPrice value)
References com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.setValue().
subtract() [2/2]
void com.wombat.mama.MamaPrice.subtract (double value)
References com.wombat.mama.MamaPrice.clear(), com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.setValue().
clear()
native void com.wombat.mama.MamaPrice.clear ()
Referenced by com.wombat.mama.MamaPrice.subtract().
set()
void com.wombat.mama.MamaPrice.set (double priceValue, MamaPriceHints hints)
References com.wombat.mama.MamaPrice.setValue().
setValue()
native void com.wombat.mama.MamaPrice.setValue (double value)
Referenced by com.wombat.mama.MamaPrice.add(), com.wombat.mama.MamaPrice.MamaPrice(), com.wombat.mama.MamaPrice.negate(), com.wombat.mama.MamaPrice.set(), and com.wombat.mama.MamaPrice.subtract().
setPrecision()
void com.wombat.mama.MamaPrice.setPrecision (MamaPricePrecision precision)
Referenced by com.wombat.mama.MamaPrice.MamaPrice().
setHints()
void com.wombat.mama.MamaPrice.setHints (MamaPriceHints hints)
References com.wombat.mama.MamaPrice.getValue().
getValue()
native double com.wombat.mama.MamaPrice.getValue ()
Referenced by com.wombat.mama.MamaPrice.add(), com.wombat.mama.MamaPrice.compareTo(), com.wombat.mama.MamaPrice.equals(), com.wombat.mama.MamaPrice.hashCode(), com.wombat.mama.MamaPrice.isZero(), com.wombat.mama.MamaPrice.negate(), com.wombat.mama.MamaPrice.setHints(), and com.wombat.mama.MamaPrice.subtract().
getRoundedValue() [1/2]
double com.wombat.mama.MamaPrice.getRoundedValue ()
This function obtains the double value of the price rounded to zero precision.
Returns
The rounded value.
Exceptions
com.wombat.mama MamaException thrown if the underlying JNI object has been destroyed.
com.wombat.common.WombatException for other general MAMA errors.
getRoundedValue() [2/2]
double com.wombat.mama.MamaPrice.getRoundedValue (MamaPricePrecision precision)
This function obtains the double value of the price rounded to the supplied precision.
Parameters
precision The precision to use for rounding.
Returns
The rounded value.
Exceptions
com.wombat.mama MamaException thrown if the underlying JNI object has been destroyed.
com.wombat.common.WombatException for other general MAMA errors.
getPrecision()
MamaPricePrecision com.wombat.mama.MamaPrice.getPrecision ()
getHints()
MamaPriceHints com.wombat.mama.MamaPrice.getHints ()
References com.wombat.mama.MamaPrice.toString().
toString()
native String com.wombat.mama.MamaPrice.toString ()
Referenced by com.wombat.mama.MamaPrice.getHints().
negate()
void com.wombat.mama.MamaPrice.negate ()
References com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.setValue().
isZero()
boolean com.wombat.mama.MamaPrice.isZero ()
References com.wombat.mama.MamaPrice.copy(), com.wombat.mama.MamaPrice.destroy(), com.wombat.mama.MamaPrice.getIsValidPrice(), com.wombat.mama.MamaPrice.getValue(), and com.wombat.mama.MamaPrice.setIsValidPrice().
setIsValidPrice()
native void com.wombat.mama.MamaPrice.setIsValidPrice (boolean valid)
Referenced by com.wombat.mama.MamaPrice.isZero().
getIsValidPrice()
native boolean com.wombat.mama.MamaPrice.getIsValidPrice ()
Referenced by com.wombat.mama.MamaPrice.isZero().
copy()
native void com.wombat.mama.MamaPrice.copy (MamaPrice price)
Referenced by com.wombat.mama.MamaPrice.isZero(), and com.wombat.mama.MamaPrice.MamaPrice().
destroy()
native void com.wombat.mama.MamaPrice.destroy ()
Referenced by com.wombat.mama.MamaPrice.finalize(), and com.wombat.mama.MamaPrice.isZero().
finalize()
void com.wombat.mama.MamaPrice.finalize () protected
References com.wombat.mama.MamaPrice.destroy().
Member Data Documentation
EPSILON
final double com.wombat.mama.MamaPrice.EPSILON = 0.00000000001 static
MAMA_PRICE_EPSILON a value that is considered equivalent to zero.