OpenMAMA Java API: com.wombat.mama.MamaMsgIterator Class Reference
com.wombat.mama.MamaMsgIterator Class Reference
Inherits Iterator.
Public Member Functions
native void iteratorCreate (MamaMsg msg, MamaDictionary dictionary)
native void iteratorAssociate (MamaMsg msg, MamaDictionary dictionary)
native void iteratorNext ()
native boolean iteratorHasNext ()
MamaMsgIterator (MamaMsg parent, MamaDictionary dictionary)
void reset (MamaMsg parent, MamaDictionary dictionary)
Object next ()
boolean hasNext ()
void remove ()
Constructor & Destructor Documentation
MamaMsgIterator()
com.wombat.mama.MamaMsgIterator.MamaMsgIterator (MamaMsg parent, MamaDictionary dictionary)
References com.wombat.mama.MamaMsgIterator.iteratorCreate().
Member Function Documentation
iteratorCreate()
native void com.wombat.mama.MamaMsgIterator.iteratorCreate (MamaMsg msg, MamaDictionary dictionary)
Referenced by com.wombat.mama.MamaMsgIterator.MamaMsgIterator().
iteratorAssociate()
native void com.wombat.mama.MamaMsgIterator.iteratorAssociate (MamaMsg msg, MamaDictionary dictionary)
Referenced by com.wombat.mama.MamaMsgIterator.reset().
iteratorNext()
native void com.wombat.mama.MamaMsgIterator.iteratorNext ()
Referenced by com.wombat.mama.MamaMsgIterator.next().
iteratorHasNext()
native boolean com.wombat.mama.MamaMsgIterator.iteratorHasNext ()
reset()
void com.wombat.mama.MamaMsgIterator.reset (MamaMsg parent, MamaDictionary dictionary)
References com.wombat.mama.MamaMsgIterator.iteratorAssociate().
Referenced by com.wombat.mama.MamaMsg.iterator().
next()
Object com.wombat.mama.MamaMsgIterator.next ()
References com.wombat.mama.MamaMsgIterator.iteratorNext().
hasNext()
boolean com.wombat.mama.MamaMsgIterator.hasNext ()
remove()
void com.wombat.mama.MamaMsgIterator.remove ()
References com.wombat.mama.MamaMsgField.destroy().