OpenMAMA Java API: com.wombat.mama.MamaQueue Class Reference
com.wombat.mama.MamaQueue Class Reference
Public Member Functions
long getPointerVal ()
MamaQueue ()
native void create (MamaBridge bridge)
native void createUsingNative (MamaBridge bridge, Object nativeQueue)
native void destroy ()
Destroy the queue, this function should only be called if there are no open objects against the queue.
native void destroyWait ()
Destroy a queue.
native void destroyTimedWait (long timeout)
Destroy a queue.
native void dispatch ()
native void stopDispatch ()
native void enqueueEvent (MamaQueueEventCallback callback, Object closure)
native void setQueueMonitorCallback (MamaQueueMonitorCallback callback)
native void setHighWatermark (long highWatermark)
native long getHighwatermark ()
native void setLowWatermark (long lowWatermark)
native long getLowWatermark ()
native void setQueueName (String queueName)
native String getQueueName ()
native String getQueueBridgeName ()
native long getEventCount ()
Public Attributes
MamaMsg reuseableMsg = null
Constructor & Destructor Documentation
MamaQueue()
com.wombat.mama.MamaQueue.MamaQueue ()
References com.wombat.mama.MamaQueue.create(), com.wombat.mama.MamaQueue.createUsingNative(), com.wombat.mama.MamaQueue.destroy(), com.wombat.mama.MamaQueue.destroyTimedWait(), com.wombat.mama.MamaQueue.destroyWait(), com.wombat.mama.MamaQueue.dispatch(), com.wombat.mama.MamaQueue.enqueueEvent(), com.wombat.mama.MamaQueue.getEventCount(), com.wombat.mama.MamaQueue.getHighwatermark(), com.wombat.mama.MamaQueue.getLowWatermark(), com.wombat.mama.MamaQueue.getQueueBridgeName(), com.wombat.mama.MamaQueue.getQueueName(), com.wombat.mama.MamaQueue.setHighWatermark(), com.wombat.mama.MamaQueue.setLowWatermark(), com.wombat.mama.MamaQueue.setQueueMonitorCallback(), com.wombat.mama.MamaQueue.setQueueName(), and com.wombat.mama.MamaQueue.stopDispatch().
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaQueue.getPointerVal ()
create()
native void com.wombat.mama.MamaQueue.create (MamaBridge bridge)
Referenced by com.wombat.mama.MamaQueue.MamaQueue(), and com.wombat.mama.MamaQueueGroup.MamaQueueGroup().
createUsingNative()
native void com.wombat.mama.MamaQueue.createUsingNative (MamaBridge bridge, Object nativeQueue)
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
destroy()
native void com.wombat.mama.MamaQueue.destroy ()
Destroy the queue, this function should only be called if there are no open objects against the queue.
Use one of the other destroy functions to block until all objects have been cleaned up.
Exceptions
MamaException will be thrown if there are open objects.
Referenced by com.wombat.mama.MamaQueueGroup.destroy(), and com.wombat.mama.MamaQueue.MamaQueue().
destroyWait()
native void com.wombat.mama.MamaQueue.destroyWait ()
Destroy a queue.
Note that the queue can only be destroyed if all of the objects created on it, (timers, subscriptions etc), have been destroyed. This function will block until all of the objects have been destroyed and will then destroy the queue.
Referenced by com.wombat.mama.MamaQueueGroup.destroyWait(), and com.wombat.mama.MamaQueue.MamaQueue().
destroyTimedWait()
native void com.wombat.mama.MamaQueue.destroyTimedWait (long timeout)
Destroy a queue.
Note that the queue can only be destroyed if all of the objects created on it, (timers, subscriptions etc), have been destroyed. This function will block until all of the objects have been destroyed and will then destroy the queue.
Parameters
timeout The time to block for in milliseconds.
Exceptions
MamaException will be thrown if the timeout elapses.
Referenced by com.wombat.mama.MamaQueueGroup.destroyTimedWait(), and com.wombat.mama.MamaQueue.MamaQueue().
dispatch()
native void com.wombat.mama.MamaQueue.dispatch ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
stopDispatch()
native void com.wombat.mama.MamaQueue.stopDispatch ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
enqueueEvent()
native void com.wombat.mama.MamaQueue.enqueueEvent (MamaQueueEventCallback callback, Object closure)
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
setQueueMonitorCallback()
native void com.wombat.mama.MamaQueue.setQueueMonitorCallback (MamaQueueMonitorCallback callback)
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
setHighWatermark()
native void com.wombat.mama.MamaQueue.setHighWatermark (long highWatermark)
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
getHighwatermark()
native long com.wombat.mama.MamaQueue.getHighwatermark ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
setLowWatermark()
native void com.wombat.mama.MamaQueue.setLowWatermark (long lowWatermark)
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
getLowWatermark()
native long com.wombat.mama.MamaQueue.getLowWatermark ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
setQueueName()
native void com.wombat.mama.MamaQueue.setQueueName (String queueName)
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
getQueueName()
native String com.wombat.mama.MamaQueue.getQueueName ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
getQueueBridgeName()
native String com.wombat.mama.MamaQueue.getQueueBridgeName ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
getEventCount()
native long com.wombat.mama.MamaQueue.getEventCount ()
Referenced by com.wombat.mama.MamaQueue.MamaQueue().
Member Data Documentation
reuseableMsg
MamaMsg com.wombat.mama.MamaQueue.reuseableMsg = null