OpenMAMA Java API: com.wombat.mama.MamaQueueGroup Class Reference
com.wombat.mama.MamaQueueGroup Class Reference
A simple class for distributing events across multiple queues in a round robin.
Public Member Functions
MamaQueueGroup (int numberOfQueues, MamaBridge bridge)
Create a MamaQueueGroup with the specified number of MamaQueues.
int getNumberOfQueues ()
Return number of queues in the array.
void destroy ()
Destroy the queue, this function should only be called if there are no open objects against the queue.
void destroyWait ()
Destroy a queue.
void destroyTimedWait (long timeout)
Destroy a queue.
MamaQueue getNextQueue ()
Return the next queue.
void stopDispatch ()
void startDispatch ()
Detailed Description
A simple class for distributing events across multiple queues in a round robin.
Constructor & Destructor Documentation
MamaQueueGroup()
com.wombat.mama.MamaQueueGroup.MamaQueueGroup (int numberOfQueues, MamaBridge bridge)
Create a MamaQueueGroup with the specified number of MamaQueues.
If the number of queues is 0, getNextQueue() returns the default queue for the bridge.
Parameters
numberOfQueues The number of queues to create.
References com.wombat.mama.MamaDispatcher.create(), and com.wombat.mama.MamaQueue.create().
Member Function Documentation
getNumberOfQueues()
int com.wombat.mama.MamaQueueGroup.getNumberOfQueues ()
Return number of queues in the array.
C++ returns 0 if the array is empty and the default queue is being used.
destroy()
void com.wombat.mama.MamaQueueGroup.destroy ()
Destroy the queue, this function should only be called if there are no open objects against the queue.
Use one of the other destroy functions to block until all objects have been cleaned up.
Exceptions
MamaException will be thrown if there are open objects.
References com.wombat.mama.MamaQueue.destroy().
destroyWait()
void com.wombat.mama.MamaQueueGroup.destroyWait ()
Destroy a queue.
Note that the queue can only be destroyed if all of the objects created on it, (timers, subscriptions etc), have been destroyed. This function will block until all of the objects have been destroyed and will then destroy the queue.
References com.wombat.mama.MamaQueue.destroyWait().
destroyTimedWait()
void com.wombat.mama.MamaQueueGroup.destroyTimedWait (long timeout)
Destroy a queue.
Note that the queue can only be destroyed if all of the objects created on it, (timers, subscriptions etc), have been destroyed. This function will block until all of the objects have been destroyed and will then destroy the queue.
Parameters
timeout The time to block for in milliseconds.
Exceptions
MamaException will be thrown if the timeout elapses.
References com.wombat.mama.MamaQueue.destroyTimedWait().
getNextQueue()
MamaQueue com.wombat.mama.MamaQueueGroup.getNextQueue ()
Return the next queue.
The queues are returned in a round robin.
Returns
The next queue.
References com.wombat.mama.Mama.getDefaultQueue().
stopDispatch()
void com.wombat.mama.MamaQueueGroup.stopDispatch ()
References com.wombat.mama.MamaDispatcher.destroy().
startDispatch()
void com.wombat.mama.MamaQueueGroup.startDispatch ()
References com.wombat.mama.MamaDispatcher.create().