OpenMAMA Java API: com.wombat.mama.MamaSourceState Class Reference
com.wombat.mama.MamaSourceState Class Reference
MamaSource state class implemented with typesafe enumeration.
Public Member Functions
String toString ()
Static Public Attributes
static final MamaSourceState OFF = new MamaSourceState("OFF")
static final MamaSourceState OK = new MamaSourceState("OK")
static final MamaSourceState UKNOWN = new MamaSourceState ("UKNOWN")
Detailed Description
MamaSource state class implemented with typesafe enumeration.
Member Function Documentation
toString()
String com.wombat.mama.MamaSourceState.toString ()
Referenced by com.wombat.mama.MamaSource.getStateAsString().
Member Data Documentation
OFF
final MamaSourceState com.wombat.mama.MamaSourceState.OFF = new MamaSourceState("OFF") static
Referenced by com.wombat.mama.MamaSourceGroup.reevaluate().
OK
final MamaSourceState com.wombat.mama.MamaSourceState.OK = new MamaSourceState("OK") static
Referenced by com.wombat.mama.MamaSourceGroup.reevaluate().
UKNOWN
final MamaSourceState com.wombat.mama.MamaSourceState.UKNOWN = new MamaSourceState ("UKNOWN") static
Referenced by com.wombat.mama.MamaSourceDerivative.getState(), and com.wombat.mama.MamaSource.getStateAsString().