OpenMAMA Java API: com.wombat.mama.MamaDQPublisherManager Class Reference
com.wombat.mama.MamaDQPublisherManager Class Reference
The MamaDQPublisherManager interface represents a collection of subscriptions.
Classes
class MamaPublishTopic
This class is used to contain information on each publisher within the MamaDQPublisherManager.
Public Member Functions
void create (MamaTransport transport, MamaQueue queue, MamaDQPublisherManagerCallback callback, String source)
Create in instance of the MamaDQPublisherManager.
void create (MamaTransport transport, MamaQueue queue, MamaDQPublisherManagerCallback callback, String source, String root)
Create in instance of the MamaDQPublisherManager.
void destroy ()
Destroy the instance of the MamaDQPublisherManager.
void addPublisher (String symbol, MamaDQPublisher publisher, MamaSubscriptionCallback cache)
Add a new Publisher to the MamaDQPublisherManager.
MamaDQPublisher removePublisher (String symbol)
Remove a Publisher from the MamaDQPublisherManager.
void destroyPublisher (String symbol)
Remove a Publisher from the MamaDQPublisherManager.
MamaDQPublisher createPublisher (String symbol, Object cache)
Create a new Publisher and associate it with the MamaDQPublisherManager.
void setStatus (int status)
Set the status for the MamaDQPublisherManager.
void setSeqNum (long seqNum)
Set the message sequence number for the MamaDQPublisherManager.
void setSenderId (long id)
Set the sender ID for the MamaDQPublisherManager.
void sendSyncRequest (int numMsg, double delay, double duration)
Send out a synchronization request from the MamaDQPublisherManager.
void sendNoSubscribers (String symbol)
Publish a NO_SUBSCRIBERS message for the given symbol.
Static Public Member Functions
static Object getCache (String symbol)
Accessor for the internal ArrayList that contains all the current publishers.
static MamaDQPublisher getPublisher (String symbol)
Accessor for the internal ArrayList that contains all the current publishers.
Detailed Description
The MamaDQPublisherManager interface represents a collection of subscriptions.
It has the ability to provide all the aspects of a Mama Publisher including initials, recaps, and data quality.
See also
Mama
Member Function Documentation
create() [1/2]
void com.wombat.mama.MamaDQPublisherManager.create (MamaTransport transport, MamaQueue queue, MamaDQPublisherManagerCallback callback, String source)
Create in instance of the MamaDQPublisherManager.
Parameters
transport The transport to create the publishermanager on
queue The queue to create the publisher manager on
callback The associated callback to use
source The source namepaceto create the publisher manager with
create() [2/2]
void com.wombat.mama.MamaDQPublisherManager.create (MamaTransport transport, MamaQueue queue, MamaDQPublisherManagerCallback callback, String source, String root)
Create in instance of the MamaDQPublisherManager.
Parameters
transport The transport to create the publishermanager on
queue The queue to create the publisher manager on
callback The associated callback to use
source The source name to create the publisher manager with
root The root of the source namespace
destroy()
void com.wombat.mama.MamaDQPublisherManager.destroy ()
Destroy the instance of the MamaDQPublisherManager.
addPublisher()
void com.wombat.mama.MamaDQPublisherManager.addPublisher (String symbol, MamaDQPublisher publisher, MamaSubscriptionCallback cache)
Add a new Publisher to the MamaDQPublisherManager.
Parameters
symbol The symbol associated with the new publisher
publisher The new publisher instance
cache The callback associated with the new publisher
removePublisher()
MamaDQPublisher com.wombat.mama.MamaDQPublisherManager.removePublisher (String symbol)
Remove a Publisher from the MamaDQPublisherManager.
Parameters
symbol The symbol for which the associated publisher will be removed
destroyPublisher()
void com.wombat.mama.MamaDQPublisherManager.destroyPublisher (String symbol)
Remove a Publisher from the MamaDQPublisherManager.
Parameters
symbol The symbol for which the associated publisher will be destroyed and free'd
createPublisher()
MamaDQPublisher com.wombat.mama.MamaDQPublisherManager.createPublisher (String symbol, Object cache)
Create a new Publisher and associate it with the MamaDQPublisherManager.
Parameters
symbol The symbol for which the new publisher will be created
cache The callback that will be associated with the new publisher
Returns
MamaDQPublisher The newly created MamaDQPublisher
References com.wombat.mama.MamaDQPublisher.setCache().
setStatus()
void com.wombat.mama.MamaDQPublisherManager.setStatus (int status)
Set the status for the MamaDQPublisherManager.
Parameters
status The mamaMsgStatus to set for the publisher manager
setSeqNum()
void com.wombat.mama.MamaDQPublisherManager.setSeqNum (long seqNum)
Set the message sequence number for the MamaDQPublisherManager.
Parameters
seqNum The sequence number to set for the publisher manager
setSenderId()
void com.wombat.mama.MamaDQPublisherManager.setSenderId (long id)
Set the sender ID for the MamaDQPublisherManager.
Parameters
id The publisher sender id to set for the publisher manager
sendSyncRequest()
void com.wombat.mama.MamaDQPublisherManager.sendSyncRequest (int numMsg, double delay, double duration)
Send out a synchronization request from the MamaDQPublisherManager.
Parameters
numMsg The number of topics to include per sync response message
delay The Interval (in seconds) for the responder to wait before sending the first response
duration The Interval (in seconds) over which to send the responses
sendNoSubscribers()
void com.wombat.mama.MamaDQPublisherManager.sendNoSubscribers (String symbol)
Publish a NO_SUBSCRIBERS message for the given symbol.
Parameters
symbol The symbol to publish a NO_SUBSCRIBERS message against
References com.wombat.mama.MamaDQPublisherManager.getCache(), and com.wombat.mama.MamaDQPublisherManager.getPublisher().
getCache()
static Object com.wombat.mama.MamaDQPublisherManager.getCache (String symbol) static
Accessor for the internal ArrayList that contains all the current publishers.
Parameters
symbol The symbol for the which you want to get the cache
Returns
The cache associated with the symbol/publisher
Referenced by com.wombat.mama.MamaDQPublisherManager.sendNoSubscribers().
getPublisher()
static MamaDQPublisher com.wombat.mama.MamaDQPublisherManager.getPublisher (String symbol) static
Accessor for the internal ArrayList that contains all the current publishers.
Parameters
symbol The symbol for the which you want to get the publisher
Returns
The MamaDQPublisher associated with the given symbol
Referenced by com.wombat.mama.MamaDQPublisherManager.sendNoSubscribers().