OpenMAMA Java API: com.wombat.mama.MamaTimeZone Class Reference
com.wombat.mama.MamaTimeZone Class Reference
A time zone representation to make conversion of timestamps to and from particular time zones more convenient.
Public Member Functions
MamaTimeZone ()
Constructor.
MamaTimeZone (String tz)
Constructor.
MamaTimeZone (MamaTimeZone copy)
Copy constructor.
boolean equals (Object obj)
Equals override.
int hashCode ()
Hashcode override.
void set (String tz)
Assign new timezones to this object.
String tz ()
Return the time zone string.
int offset ()
Return the offset from UTC (in seconds).
TimeZone getJavaTimzone ()
Return a java.util.TimeZone object for this MamaTimeZone.
Static Public Member Functions
static MamaTimeZone local ()
Return a reference to a MamaTimeZone corresponding to the local time zone.
static MamaTimeZone utc ()
Return a reference to a MamaTimeZone corresponding to UTC time zone.
static MamaTimeZone usEastern ()
Return a reference to a MamaTimeZone corresponding to the US Eastern time zone.
Detailed Description
A time zone representation to make conversion of timestamps to and from particular time zones more convenient.
Note: The addition of instance monitoring to the MamaTimeZone implementation has resulted in the following limitation in its usage. Do not create short lived objects of this type on the method stack or delete long lived objects before program termination. Pointers to all instances are maintained in a global vector. At the moment there is no mechanism by which we can detect deleted objects or those which are popped off the method stack. An internal thread will always iterate over all objects ever created. A call to an object removed from the stack will result in nondeterminable behaviour. Pointers could be stored in a map against a unique object id; however, addition and removal from the map would have to be synchronized which would impact on performance.
Constructor & Destructor Documentation
MamaTimeZone() [1/3]
com.wombat.mama.MamaTimeZone.MamaTimeZone ()
Constructor.
The default for C/C++ sets TZ="TZ" which appears to be no timezone (date in bash reports the correct local time with no timezone. For now, we will just use the local timezone. I am not sure if this is correct.
MamaTimeZone() [2/3]
com.wombat.mama.MamaTimeZone.MamaTimeZone (String tz)
Constructor.
NULL argument is equivalent to local timezone.
MamaTimeZone() [3/3]
com.wombat.mama.MamaTimeZone.MamaTimeZone (MamaTimeZone copy)
Copy constructor.
Member Function Documentation
local()
static MamaTimeZone com.wombat.mama.MamaTimeZone.local () static
Return a reference to a MamaTimeZone corresponding to the local time zone.
utc()
static MamaTimeZone com.wombat.mama.MamaTimeZone.utc () static
Return a reference to a MamaTimeZone corresponding to UTC time zone.
usEastern()
static MamaTimeZone com.wombat.mama.MamaTimeZone.usEastern () static
Return a reference to a MamaTimeZone corresponding to the US Eastern time zone.
equals()
boolean com.wombat.mama.MamaTimeZone.equals (Object obj)
Equals override.
Two timezones are equal if they represent the same timezone
References com.wombat.mama.MamaTimeZone.tz().
hashCode()
int com.wombat.mama.MamaTimeZone.hashCode ()
Hashcode override.
References com.wombat.mama.MamaTimeZone.tz().
set()
void com.wombat.mama.MamaTimeZone.set (String tz)
Assign new timezones to this object.
References com.wombat.mama.MamaTimeZone.tz().
tz()
String com.wombat.mama.MamaTimeZone.tz ()
Return the time zone string.
Referenced by com.wombat.mama.MamaTimeZone.equals(), com.wombat.mama.MamaDateTime.formatString(), com.wombat.mama.MamaDateTime.getEpochTimeMicroseconds(), com.wombat.mama.MamaDateTime.getEpochTimeMilliseconds(), com.wombat.mama.MamaDateTime.getEpochTimeSeconds(), com.wombat.mama.MamaTimeZone.hashCode(), com.wombat.mama.MamaDateTime.MamaDateTime(), com.wombat.mama.MamaTimeZone.set(), com.wombat.mama.MamaDateTime.setTime(), com.wombat.mama.MamaDateTime.setToMidnightToday(), and com.wombat.mama.MamaDateTime.setWithHints().
offset()
int com.wombat.mama.MamaTimeZone.offset ()
Return the offset from UTC (in seconds).
Can be positive or negative, depending upon the direction.
This might be inefficient if this method gets called alot. In the C/C++ implementation, the offset is cached and a spearate thread updates them at regular intervals. We may not need this for Java clients.
getJavaTimzone()
TimeZone com.wombat.mama.MamaTimeZone.getJavaTimzone ()
Return a java.util.TimeZone object for this MamaTimeZone.