OpenMAMA Java API: com.wombat.mama.MamaMdMsgType Class Reference
com.wombat.mama.MamaMdMsgType Class Reference
This class provides an enumeration of types and methods for MAMA types related to market data applications.
Public Member Functions
String toString ()
Returns the stringified name for the enumerated type.
int getValue ()
Returns the integer value for the type.
boolean equals (MamaMdMsgType appDataType)
Compare the two types for equality.
Static Public Member Functions
static MamaMdMsgType typeForMsg (final MamaMsg msg)
Get the md msg type from the specified MamaMsg.
static String stringForMsg (final MamaMsg msg)
The stringified name of the type based on the int value for the type in the specified message.
static short compatMsgType (MamaMdMsgType mdMsgType)
Return the corresponding MamaMsgType for the specified MamaMdMsgType.
static String valueToString (int value)
Utility method for mapping type integer values to corresponding string values.
static MamaMdMsgType enumObjectForValue (int value)
Return an instance of a MamaMdMsgType corresponding to the specified integer value.
Static Public Attributes
static final int CANCEL_VALUE = 2
Trade Cancellation.
static final MamaMdMsgType CANCEL
static final int ERROR_VALUE = 3
Trade Error.
static final MamaMdMsgType ERROR
static final int CORRECTION_VALUE = 4
Trade correction.
static final MamaMdMsgType CORRECTION
static final int CLOSING_VALUE = 5
Closing summary.
static final MamaMdMsgType CLOSING
static final int SYMBOL_ACTION_VALUE = 8
Action related to this symbol, such as a name change or symbol deletion due to option/future expiration, etc.
static final MamaMdMsgType SYMBOL_ACTION
static final int PREOPENING_VALUE = 12
Pre-opening summary (e.g.
static final MamaMdMsgType PREOPENING
static final int QUOTE_VALUE = 13
Quote update.
static final MamaMdMsgType QUOTE
static final int TRADE_VALUE = 14
Trade Update.
static final MamaMdMsgType TRADE
static final int BOOK_INITIAL_VALUE = 16
Order book initial value.
static final MamaMdMsgType BOOK_INITIAL
static final int IMBALANCE_VALUE = 17
Order imbalance or noimbalance update.
static final MamaMdMsgType IMBALANCE
static final int SECURITY_STATUS_VALUE = 18
Security status update.
static final MamaMdMsgType SECURITY_STATUS
static final int MISC_VALUE = 100
Miscellaneous.
static final MamaMdMsgType MISC
Detailed Description
This class provides an enumeration of types and methods for MAMA types related to market data applications.
It is intended that the types in this class will ultimately replace the MamaMsgType as an indicator of the type of market data message received by a subscribing application.
Member Function Documentation
toString()
String com.wombat.mama.MamaMdMsgType.toString ()
Returns the stringified name for the enumerated type.
Returns
Name for the type.
Referenced by com.wombat.mama.MamaMdMsgType.stringForMsg().
getValue()
int com.wombat.mama.MamaMdMsgType.getValue ()
Returns the integer value for the type.
This value can be used in switch statements against the public XXX_VALUE static members of the class.
Returns
The integer type.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
equals()
boolean com.wombat.mama.MamaMdMsgType.equals (MamaMdMsgType appDataType)
Compare the two types for equality.
Returns true if the integer value of both types is equal. Otherwise returns false.
Parameters
appDataType The object to check equality against.
Returns
Whether the two objects are equal.
typeForMsg()
static MamaMdMsgType com.wombat.mama.MamaMdMsgType.typeForMsg (final MamaMsg msg) static
Get the md msg type from the specified MamaMsg.
Returns null if no type was found in the message.
Parameters
msg The MamaMsg from which the msg type will be extracted.
Returns
An instance of a MamaMdMsgType
References com.wombat.mama.MamaReservedFields.AppMsgType, com.wombat.mama.MamaMdMsgType.enumObjectForValue(), com.wombat.mama.MamaReservedFields.getId(), com.wombat.mama.MamaReservedFields.getName(), and com.wombat.mama.MamaMsg.getU8().
Referenced by com.wombat.mama.MamaMdMsgType.stringForMsg().
stringForMsg()
static String com.wombat.mama.MamaMdMsgType.stringForMsg (final MamaMsg msg) static
The stringified name of the type based on the int value for the type in the specified message.
Parameters
msg The MamaMsg from which the type is to be extracted.
Returns
The string name for the type.
References com.wombat.mama.MamaMdMsgType.toString(), and com.wombat.mama.MamaMdMsgType.typeForMsg().
compatMsgType()
static short com.wombat.mama.MamaMdMsgType.compatMsgType (MamaMdMsgType mdMsgType) static
Return the corresponding MamaMsgType for the specified MamaMdMsgType.
Mainly for backwards compatibility.
Parameters
mdMsgType The MamaMdMsgType for which a mapping is required.
Returns
The MamaMsgType corresponding to the specified MamaMdMsgType.
References com.wombat.mama.MamaMdMsgType.getValue(), com.wombat.mama.MamaMsgType.TYPE_BOOK_INITIAL, com.wombat.mama.MamaMsgType.TYPE_CLOSING, com.wombat.mama.MamaMsgType.TYPE_CORRECTION, com.wombat.mama.MamaMsgType.TYPE_ERROR, com.wombat.mama.MamaMsgType.TYPE_MISC, com.wombat.mama.MamaMsgType.TYPE_PREOPENING, com.wombat.mama.MamaMsgType.TYPE_QUOTE, com.wombat.mama.MamaMsgType.TYPE_TRADE, and com.wombat.mama.MamaMsgType.TYPE_UPDATE.
valueToString()
static String com.wombat.mama.MamaMdMsgType.valueToString (int value) static
Utility method for mapping type integer values to corresponding string values.
Returns "UNKNOWN" is the int type value is not recognised.
Parameters
value The int value for a MamaMdMsgType.
Returns
The string name value of the specified MamaMdMsgType integer value.
enumObjectForValue()
static MamaMdMsgType com.wombat.mama.MamaMdMsgType.enumObjectForValue (int value) static
Return an instance of a MamaMdMsgType corresponding to the specified integer value.
Returns null if the integer value is not recognised.
Parameters
value Int value for a MamaMdMsgType.
Returns
Instance of a MamaMdMsgType if a mapping exists.
References com.wombat.mama.MamaMdMsgType.BOOK_INITIAL, com.wombat.mama.MamaMdMsgType.CANCEL, com.wombat.mama.MamaMdMsgType.CLOSING, com.wombat.mama.MamaMdMsgType.CORRECTION, com.wombat.mama.MamaMdMsgType.ERROR, com.wombat.mama.MamaMdMsgType.IMBALANCE, com.wombat.mama.MamaMdMsgType.MISC, com.wombat.mama.MamaMdMsgType.PREOPENING, com.wombat.mama.MamaMdMsgType.QUOTE, com.wombat.mama.MamaMdMsgType.SECURITY_STATUS, com.wombat.mama.MamaMdMsgType.SYMBOL_ACTION, and com.wombat.mama.MamaMdMsgType.TRADE.
Referenced by com.wombat.mama.MamaMdMsgType.typeForMsg().
Member Data Documentation
CANCEL_VALUE
final int com.wombat.mama.MamaMdMsgType.CANCEL_VALUE = 2 static
Trade Cancellation.
CANCEL
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.CANCEL static
Initial value:
= new MamaMdMsgType
                         (valueToString (CANCEL_VALUE),
                          CANCEL_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
ERROR_VALUE
final int com.wombat.mama.MamaMdMsgType.ERROR_VALUE = 3 static
Trade Error.
ERROR
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.ERROR static
Initial value:
= new MamaMdMsgType
                         (valueToString (ERROR_VALUE),
                          ERROR_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
CORRECTION_VALUE
final int com.wombat.mama.MamaMdMsgType.CORRECTION_VALUE = 4 static
Trade correction.
CORRECTION
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.CORRECTION static
Initial value:
= new MamaMdMsgType
                         (valueToString (CORRECTION_VALUE),
                          CORRECTION_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
CLOSING_VALUE
final int com.wombat.mama.MamaMdMsgType.CLOSING_VALUE = 5 static
Closing summary.
CLOSING
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.CLOSING static
Initial value:
= new MamaMdMsgType
                         (valueToString (CLOSING_VALUE),
                          CLOSING_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
SYMBOL_ACTION_VALUE
final int com.wombat.mama.MamaMdMsgType.SYMBOL_ACTION_VALUE = 8 static
Action related to this symbol, such as a name change or symbol deletion due to option/future expiration, etc.
SYMBOL_ACTION
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.SYMBOL_ACTION static
Initial value:
= new MamaMdMsgType
                         (valueToString (SYMBOL_ACTION_VALUE),
                          SYMBOL_ACTION_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
PREOPENING_VALUE
final int com.wombat.mama.MamaMdMsgType.PREOPENING_VALUE = 12 static
Pre-opening summary (e.g.
morning roll)
PREOPENING
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.PREOPENING static
Initial value:
= new MamaMdMsgType
                         (valueToString (PREOPENING_VALUE),
                          PREOPENING_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
QUOTE_VALUE
final int com.wombat.mama.MamaMdMsgType.QUOTE_VALUE = 13 static
Quote update.
QUOTE
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.QUOTE static
Initial value:
= new MamaMdMsgType
                         (valueToString (QUOTE_VALUE),
                          QUOTE_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
TRADE_VALUE
final int com.wombat.mama.MamaMdMsgType.TRADE_VALUE = 14 static
Trade Update.
TRADE
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.TRADE static
Initial value:
= new MamaMdMsgType
                         (valueToString (TRADE_VALUE),
                          TRADE_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
BOOK_INITIAL_VALUE
final int com.wombat.mama.MamaMdMsgType.BOOK_INITIAL_VALUE = 16 static
Order book initial value.
BOOK_INITIAL
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.BOOK_INITIAL static
Initial value:
= new MamaMdMsgType
                         (valueToString (BOOK_INITIAL_VALUE),
                          BOOK_INITIAL_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
IMBALANCE_VALUE
final int com.wombat.mama.MamaMdMsgType.IMBALANCE_VALUE = 17 static
Order imbalance or noimbalance update.
IMBALANCE
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.IMBALANCE static
Initial value:
= new MamaMdMsgType
                         (valueToString (IMBALANCE_VALUE),
                          IMBALANCE_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
SECURITY_STATUS_VALUE
final int com.wombat.mama.MamaMdMsgType.SECURITY_STATUS_VALUE = 18 static
Security status update.
SECURITY_STATUS
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.SECURITY_STATUS static
Initial value:
= new MamaMdMsgType
                         (valueToString (SECURITY_STATUS_VALUE),
                          SECURITY_STATUS_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().
MISC_VALUE
final int com.wombat.mama.MamaMdMsgType.MISC_VALUE = 100 static
Miscellaneous.
MISC
final MamaMdMsgType com.wombat.mama.MamaMdMsgType.MISC static
Initial value:
= new MamaMdMsgType
                         (valueToString (MISC_VALUE),
                          MISC_VALUE)
Referenced by com.wombat.mama.MamaMdMsgType.enumObjectForValue().