OpenMAMA Java API: com.wombat.mama.MamaSourceGroup Class Reference
com.wombat.mama.MamaSourceGroup Class Reference
Inherits com.wombat.mama.MamaSourceGroupListener.
Public Member Functions
MamaSourceGroup (String name)
Create a mamaSourceGroup object.
void enableLogging (Level level)
void disableLogging ()
String getName ()
Return the name string identifier for the specified source group.
MamaSource findSource (final String sourceName)
Find a source with the given name in the group.
void addSource (MamaSource source, long weight)
Add a mamaSource to the specified group with the specified weighting.
void addSourceWithName (MamaSource source, String sourceName, long weight)
Add a mamaSource to the specified group with the specified weighting and string name identifier.
void setSourceWeight (String sourceName, long weight)
Set the weight for an existing mamaSource in the specified group.
boolean reevaluate ()
Re-evaluate the group by checking all of the relative weights and changing the state of each MamaSource in the group as appropriate.
MamaSource getTopWeightSource ()
Return the top weighted source for this source group.
void registerStateChangeListener (MamaSourceStateChangeListener event)
Applications interested in event notifications can register for events.
void unregisterStateChangeListener (MamaSourceStateChangeListener event)
Applications interested in event notifications can unregister for events.
Iterator sourceIterator ()
Constructor & Destructor Documentation
MamaSourceGroup()
com.wombat.mama.MamaSourceGroup.MamaSourceGroup (String name)
Create a mamaSourceGroup object.
Member Function Documentation
enableLogging()
void com.wombat.mama.MamaSourceGroup.enableLogging (Level level)
disableLogging()
void com.wombat.mama.MamaSourceGroup.disableLogging ()
getName()
String com.wombat.mama.MamaSourceGroup.getName ()
Return the name string identifier for the specified source group.
Returns
The group name
Referenced by com.wombat.mama.MamaSourceGroupManager.addSourceGroup(), com.wombat.mama.MamaSourceGroup.addSourceWithName(), and com.wombat.mama.MamaSourceGroup.reevaluate().
findSource()
MamaSource com.wombat.mama.MamaSourceGroup.findSource (final String sourceName)
Find a source with the given name in the group.
Parameters
sourceName The name identifier for the source being located.
Returns
MamaSource
Referenced by com.wombat.mama.MamaSourceGroup.addSourceWithName().
addSource()
void com.wombat.mama.MamaSourceGroup.addSource (MamaSource source, long weight)
Add a mamaSource to the specified group with the specified weighting.
The source id will be used by the group to uniquely identify the source.
Parameters
source The mamaSource being added to the mamaSourceGroup.
weight The weighing to apply to the source being added.
References com.wombat.mama.MamaSourceGroup.addSourceWithName(), and com.wombat.mama.MamaSource.getId().
addSourceWithName()
void com.wombat.mama.MamaSourceGroup.addSourceWithName (MamaSource source, String sourceName, long weight)
Add a mamaSource to the specified group with the specified weighting and string name identifier.
Parameters
source The mamaSource being added to the mamaSourceGroup.
sourceName The unique identifier for this source in this group.
weight The weighing to apply to the source being added.
References com.wombat.mama.MamaSourceGroup.findSource(), com.wombat.mama.MamaSource.getId(), and com.wombat.mama.MamaSourceGroup.getName().
Referenced by com.wombat.mama.MamaSourceGroup.addSource().
setSourceWeight()
void com.wombat.mama.MamaSourceGroup.setSourceWeight (String sourceName, long weight)
Set the weight for an existing mamaSource in the specified group.
Parameters
sourceName The name of the source whose weight is being updated.
weight The new weight value for the specified source.
reevaluate()
boolean com.wombat.mama.MamaSourceGroup.reevaluate ()
Re-evaluate the group by checking all of the relative weights and changing the state of each MamaSource in the group as appropriate.
Returns true if any states were changed; otherwise false.
Returns
boolean Whether any states were changed as a result of the call. false indicates none were changed. true indicates that the state of one or more sources has changed.
References com.wombat.mama.MamaSourceGroup.getName(), com.wombat.mama.MamaSourceState.OFF, and com.wombat.mama.MamaSourceState.OK.
getTopWeightSource()
MamaSource com.wombat.mama.MamaSourceGroup.getTopWeightSource ()
Return the top weighted source for this source group.
registerStateChangeListener()
void com.wombat.mama.MamaSourceGroup.registerStateChangeListener (MamaSourceStateChangeListener event)
Applications interested in event notifications can register for events.
Parameters
event to register
Implements com.wombat.mama.MamaSourceGroupListener.
unregisterStateChangeListener()
void com.wombat.mama.MamaSourceGroup.unregisterStateChangeListener (MamaSourceStateChangeListener event)
Applications interested in event notifications can unregister for events.
Parameters
event to unregister
Implements com.wombat.mama.MamaSourceGroupListener.
References com.wombat.mama.MamaSourceStateChangeListener.onStateChanged().
sourceIterator()
Iterator com.wombat.mama.MamaSourceGroup.sourceIterator ()