OpenMAMA Java API: com.wombat.mama.MamaSubscription Class Reference
com.wombat.mama.MamaSubscription Class Reference
Public Member Functions
MamaSubscription ()
The constructor allocates the underlying C subscription.
void createSubscription (MamaSubscriptionCallback callback, MamaQueue queue, MamaSource source, String symbol, Object closure)
Create and activate subscription.
MamaDictionary createDictionarySubscription (MamaDictionaryCallback callback, MamaQueue queue, MamaSource source)
Create a dictionary subscription using default values for the timeout and number of retries.
MamaDictionary createDictionarySubscription (MamaDictionaryCallback callback, MamaQueue queue, MamaSource source, double timeout, int retries)
Create a dictionary subscription using default values for the timeout and number of retries.
void createSnapshotSubscription (MamaSubscriptionCallback callback, MamaQueue queue, MamaSource source, String symbol, Object closure)
Create a snapshot subscription for initial value only (no updates).
Object getClosure ()
This function returns the closure supplied to the createSubscription function.
long getPointerVal ()
This function returns the pointer to the underlying C subscription.
MamaSource getSource ()
Return the source associated with the subscription.
MamaSubscriptionState getState ()
This function returns the current state of the subscription as one of the MamaSubscriptionState instances, see this class for more information.
void setupSubscription (MamaSubscriptionCallback callback, MamaQueue queue, MamaSource source, String symbol, Object closure)
Setup a basic subscription without marketdata semantics.
void setAppDataType (MamaMdDataType type)
MamaMdDataType getAppDataType ()
void setDebugLevel (Level level)
void setMessageQualifierFilter (MamaMsgQualifier qualifier)
MamaMsgQualifier getMessageQualifierFilter ()
void setSubscriptionType (MamaSubscriptionType type)
MamaSubscriptionType getSubscriptionType ()
MamaTransport getTransport ()
native void activate ()
Activate a subscription that has been set up by calling MamaSubscription.setup.
native void deactivate ()
Deactivate a subscription.
native void deallocate ()
De-allocates the underlying C subscription.
native void destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
native void destroyEx ()
This function will destroy the subscription and can be called from any thread.
native boolean getReceivedInitial ()
Get whether we have received an Initial.
native String getSubscSource ()
Return the source for this subscription.
native String getSymbol ()
Return the symbol for this subscription.
native double getTimeout ()
To return the subscription timeout.
native boolean isActive ()
Returns whether the subscription is valid, note that this function has been deprecated, use mamaSubscription_getState instead.
native boolean isValid ()
Returns whether the subscription is valid, note that this function has been deprecated, use mamaSubscription_getState instead.
native void setRequiresInitial (boolean value)
Set whether subscriptoin requires initial value.
native void setTimeout (double timeout)
Set the timeout for this subscription.
native Object getItemClosure ()
native int getPreInitialCacheSize ()
native boolean getRecoverGaps ()
native boolean getRequiresInitital ()
native int getRetries ()
native short getServiceLevel ()
native long getServiceLevelOptions ()
native void setPreInitialCacheSize (int size)
native void setItemClosure (Object closure)
native void setRecoverGaps (boolean recover)
native void setServiceLevel (short level, long options)
native void setRetries (int retries)
Static Public Attributes
static final int DEFAULT_RETRIES = 2
static final double DEFAULT_TIMEOUT = 10.0
Protected Member Functions
void finalize () throws Throwable
The finalizer deallocates the underlying C subscription.
Constructor & Destructor Documentation
MamaSubscription()
com.wombat.mama.MamaSubscription.MamaSubscription ()
The constructor allocates the underlying C subscription.
Member Function Documentation
finalize()
void com.wombat.mama.MamaSubscription.finalize () throws Throwable protected
The finalizer deallocates the underlying C subscription.
Exceptions
Throwable A MamaException will be thrown if the underlying subscription could not be de-allocated.
References com.wombat.mama.MamaSubscription.deallocate().
createSubscription()
void com.wombat.mama.MamaSubscription.createSubscription (MamaSubscriptionCallback callback, MamaQueue queue, MamaSource source, String symbol, Object closure)
Create and activate subscription.
This is effectively a pair of calls to mamaSubscription_setup() and mamaSubscription_activate().
Parameters
callback The object implementing the callback functions.
queue The MamaQueue.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol name.
closure The closure will be passed to subsequent callback invocations for this subscription.
createDictionarySubscription() [1/2]
MamaDictionary com.wombat.mama.MamaSubscription.createDictionarySubscription (MamaDictionaryCallback callback, MamaQueue queue, MamaSource source)
Create a dictionary subscription using default values for the timeout and number of retries.
Parameters
callback The object implementing the callback functions, this can also be an instance of MamaSubscriptionCallbackEx to be notified when the subscription has been destroyed.
queue The MamaQueue.
source The MamaSource identifying the publisher for this symbol.
createDictionarySubscription() [2/2]
MamaDictionary com.wombat.mama.MamaSubscription.createDictionarySubscription (MamaDictionaryCallback callback, MamaQueue queue, MamaSource source, double timeout, int retries)
Create a dictionary subscription using default values for the timeout and number of retries.
Parameters
callback The object implementing the callback functions.
queue The MamaQueue.
source The MamaSource identifying the publisher for this symbol.
timeout The timeout value in seconds.
retries The number of retries.
createSnapshotSubscription()
void com.wombat.mama.MamaSubscription.createSnapshotSubscription (MamaSubscriptionCallback callback, MamaQueue queue, MamaSource source, String symbol, Object closure)
Create a snapshot subscription for initial value only (no updates).
This function is equivalent to mamaSubscription_create () with svcLevel set to MAMA_SERVICE_LEVEL_SNAPSHOT and default arguments for type, svcLevelOpt, requiresInitial, retries, timeout.
Parameters
callback The object implementing the callback functions.
queue The MamaQueue.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol name.
closure The closure will be passed to subsequent callback invocations for this subscription.
References com.wombat.mama.MamaSubscriptionType.NORMAL, com.wombat.mama.MamaSubscription.setRequiresInitial(), com.wombat.mama.MamaSubscription.setServiceLevel(), com.wombat.mama.MamaSubscription.setSubscriptionType(), and com.wombat.mama.MamaServiceLevel.SNAPSHOT.
getClosure()
Object com.wombat.mama.MamaSubscription.getClosure ()
This function returns the closure supplied to the createSubscription function.
Returns
The closure object.
getPointerVal()
long com.wombat.mama.MamaSubscription.getPointerVal ()
This function returns the pointer to the underlying C subscription.
Returns
The pointer.
getSource()
MamaSource com.wombat.mama.MamaSubscription.getSource ()
Return the source associated with the subscription.
Returns
The MamaSource object.
getState()
MamaSubscriptionState com.wombat.mama.MamaSubscription.getState ()
This function returns the current state of the subscription as one of the MamaSubscriptionState instances, see this class for more information.
Returns
The MamaSubscriptionState that represents the current state of the subscription.
References com.wombat.mama.MamaSubscriptionState.getSubscriptionState().
setupSubscription()
void com.wombat.mama.MamaSubscription.setupSubscription (MamaSubscriptionCallback callback, MamaQueue queue, MamaSource source, String symbol, Object closure)
Setup a basic subscription without marketdata semantics.
Note that activate must still be called.
Parameters
callback The object implementing the callback functions.
queue The MamaQueue.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol name.
closure The closure will be passed to subsequent callback invocations for this subscription.
setAppDataType()
void com.wombat.mama.MamaSubscription.setAppDataType (MamaMdDataType type)
References com.wombat.mama.MamaMdDataType.getValue().
getAppDataType()
MamaMdDataType com.wombat.mama.MamaSubscription.getAppDataType ()
References com.wombat.mama.MamaMdDataType.enumObjectForValue().
setDebugLevel()
void com.wombat.mama.MamaSubscription.setDebugLevel (Level level)
setMessageQualifierFilter()
void com.wombat.mama.MamaSubscription.setMessageQualifierFilter (MamaMsgQualifier qualifier)
getMessageQualifierFilter()
MamaMsgQualifier com.wombat.mama.MamaSubscription.getMessageQualifierFilter ()
setSubscriptionType()
void com.wombat.mama.MamaSubscription.setSubscriptionType (MamaSubscriptionType type)
References com.wombat.mama.MamaSubscriptionType.getValue().
Referenced by com.wombat.mama.MamaSubscription.createSnapshotSubscription().
getSubscriptionType()
MamaSubscriptionType com.wombat.mama.MamaSubscription.getSubscriptionType ()
getTransport()
MamaTransport com.wombat.mama.MamaSubscription.getTransport ()
References com.wombat.mama.MamaSubscription.activate(), com.wombat.mama.MamaSubscription.deactivate(), com.wombat.mama.MamaSubscription.deallocate(), com.wombat.mama.MamaSubscription.destroy(), com.wombat.mama.MamaSubscription.destroyEx(), com.wombat.mama.MamaSubscription.getItemClosure(), com.wombat.mama.MamaSubscription.getPreInitialCacheSize(), com.wombat.mama.MamaSubscription.getReceivedInitial(), com.wombat.mama.MamaSubscription.getRecoverGaps(), com.wombat.mama.MamaSubscription.getRequiresInitital(), com.wombat.mama.MamaSubscription.getRetries(), com.wombat.mama.MamaSubscription.getServiceLevel(), com.wombat.mama.MamaSubscription.getServiceLevelOptions(), com.wombat.mama.MamaSubscription.getSubscSource(), com.wombat.mama.MamaSubscription.getSymbol(), com.wombat.mama.MamaSubscription.getTimeout(), com.wombat.mama.MamaSource.getTransport(), com.wombat.mama.MamaSubscription.isActive(), com.wombat.mama.MamaSubscription.isValid(), com.wombat.mama.MamaSubscription.setItemClosure(), com.wombat.mama.MamaSubscription.setPreInitialCacheSize(), com.wombat.mama.MamaSubscription.setRecoverGaps(), com.wombat.mama.MamaSubscription.setRequiresInitial(), com.wombat.mama.MamaSubscription.setRetries(), com.wombat.mama.MamaSubscription.setServiceLevel(), and com.wombat.mama.MamaSubscription.setTimeout().
activate()
native void com.wombat.mama.MamaSubscription.activate ()
Activate a subscription that has been set up by calling MamaSubscription.setup.
Subscription creation actually occurs on the throttle queue. An individual subscription cannot be assumed to be fully created until its onCreate() callback has been successfully invoked. The subscription rate can be governed via the MamaTransport.setOutboundThrottle () function. Any subscription properties should be set prior to calling this function.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
deactivate()
native void com.wombat.mama.MamaSubscription.deactivate ()
Deactivate a subscription.
The subscription can be reactivated if desired using MamaSubscription.activate(). Note that the subscription will not be fully deactivated until the onDestroy callback is received.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
deallocate()
native void com.wombat.mama.MamaSubscription.deallocate ()
De-allocates the underlying C subscription.
This can be used to reduce time during finalization.
Referenced by com.wombat.mama.MamaSubscription.finalize(), and com.wombat.mama.MamaSubscription.getTransport().
destroy()
native void com.wombat.mama.MamaSubscription.destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
Use destroyEx to destroy the subscription from any thread. Note that the subscription will not be fully destroyed until the onDestroy callback is received.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
destroyEx()
native void com.wombat.mama.MamaSubscription.destroyEx ()
This function will destroy the subscription and can be called from any thread.
Note that the subscription will not be fully destroyed until the onDestroy callback is received. To destroy from the dispatching thread the destroy function should be used in preference.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getReceivedInitial()
native boolean com.wombat.mama.MamaSubscription.getReceivedInitial ()
Get whether we have received an Initial.
Returns
True if an initial has been received.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getSubscSource()
native String com.wombat.mama.MamaSubscription.getSubscSource ()
Return the source for this subscription.
Returns
The source string.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getSymbol()
native String com.wombat.mama.MamaSubscription.getSymbol ()
Return the symbol for this subscription.
Returns
The symbol string.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getTimeout()
native double com.wombat.mama.MamaSubscription.getTimeout ()
To return the subscription timeout.
Returns
The timeout in seconds.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
isActive()
native boolean com.wombat.mama.MamaSubscription.isActive ()
Returns whether the subscription is valid, note that this function has been deprecated, use mamaSubscription_getState instead.
Returns
whether the subscription is valid.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
isValid()
native boolean com.wombat.mama.MamaSubscription.isValid ()
Returns whether the subscription is valid, note that this function has been deprecated, use mamaSubscription_getState instead.
Returns
whether the subscription is valid.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
setRequiresInitial()
native void com.wombat.mama.MamaSubscription.setRequiresInitial (boolean value)
Set whether subscriptoin requires initial value.
Parameters
value True if the subscription needs an initial.
Referenced by com.wombat.mama.MamaSubscription.createSnapshotSubscription(), and com.wombat.mama.MamaSubscription.getTransport().
setTimeout()
native void com.wombat.mama.MamaSubscription.setTimeout (double timeout)
Set the timeout for this subscription.
Parameters
timeout The timeout in seconds.
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getItemClosure()
native Object com.wombat.mama.MamaSubscription.getItemClosure ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getPreInitialCacheSize()
native int com.wombat.mama.MamaSubscription.getPreInitialCacheSize ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getRecoverGaps()
native boolean com.wombat.mama.MamaSubscription.getRecoverGaps ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getRequiresInitital()
native boolean com.wombat.mama.MamaSubscription.getRequiresInitital ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getRetries()
native int com.wombat.mama.MamaSubscription.getRetries ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getServiceLevel()
native short com.wombat.mama.MamaSubscription.getServiceLevel ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
getServiceLevelOptions()
native long com.wombat.mama.MamaSubscription.getServiceLevelOptions ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
setPreInitialCacheSize()
native void com.wombat.mama.MamaSubscription.setPreInitialCacheSize (int size)
Referenced by com.wombat.mama.MamaSubscription.getTransport().
setItemClosure()
native void com.wombat.mama.MamaSubscription.setItemClosure (Object closure)
Referenced by com.wombat.mama.MamaSubscription.getTransport().
setRecoverGaps()
native void com.wombat.mama.MamaSubscription.setRecoverGaps (boolean recover)
Referenced by com.wombat.mama.MamaSubscription.getTransport().
setServiceLevel()
native void com.wombat.mama.MamaSubscription.setServiceLevel (short level, long options)
Referenced by com.wombat.mama.MamaSubscription.createSnapshotSubscription(), and com.wombat.mama.MamaSubscription.getTransport().
setRetries()
native void com.wombat.mama.MamaSubscription.setRetries (int retries)
Referenced by com.wombat.mama.MamaSubscription.getTransport().
Member Data Documentation
DEFAULT_RETRIES
final int com.wombat.mama.MamaSubscription.DEFAULT_RETRIES = 2 static
DEFAULT_TIMEOUT
final double com.wombat.mama.MamaSubscription.DEFAULT_TIMEOUT = 10.0 static