OpenMAMA Java API: com.wombat.mama.MamaDictionary Class Reference
com.wombat.mama.MamaDictionary Class Reference
Public Member Functions
long getPointerVal ()
native MamaFieldDescriptor createFieldDescriptor (int fid, String name, short type)
native void buildDictionaryFromMessage (MamaMsg msg)
native MamaMsg getDictionaryMessage ()
native MamaFieldDescriptor getFeedName ()
native MamaFieldDescriptor getFeedHost ()
native MamaFieldDescriptor getFieldByFid (int fid)
native MamaFieldDescriptor getFieldByIndex (int index)
native MamaFieldDescriptor getFieldByName (String name)
native Collection getFieldByNameAll (String name)
native int getMaxFid ()
native int getSize ()
native boolean hasDuplicates ()
void finalize ()
native void writeToFile (String file)
void populateFromFile (String file)
native void _populateFromFile (String file)
native void create ()
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaDictionary.getPointerVal ()
References com.wombat.mama.MamaDictionary.buildDictionaryFromMessage(), com.wombat.mama.MamaDictionary.createFieldDescriptor(), com.wombat.mama.MamaDictionary.getDictionaryMessage(), com.wombat.mama.MamaDictionary.getFeedHost(), com.wombat.mama.MamaDictionary.getFeedName(), com.wombat.mama.MamaDictionary.getFieldByFid(), com.wombat.mama.MamaDictionary.getFieldByIndex(), com.wombat.mama.MamaDictionary.getFieldByName(), com.wombat.mama.MamaDictionary.getFieldByNameAll(), com.wombat.mama.MamaDictionary.getMaxFid(), com.wombat.mama.MamaDictionary.getSize(), and com.wombat.mama.MamaDictionary.hasDuplicates().
createFieldDescriptor()
native MamaFieldDescriptor com.wombat.mama.MamaDictionary.createFieldDescriptor (int fid, String name, short type)
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
buildDictionaryFromMessage()
native void com.wombat.mama.MamaDictionary.buildDictionaryFromMessage (MamaMsg msg)
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getDictionaryMessage()
native MamaMsg com.wombat.mama.MamaDictionary.getDictionaryMessage ()
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getFeedName()
native MamaFieldDescriptor com.wombat.mama.MamaDictionary.getFeedName ()
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getFeedHost()
native MamaFieldDescriptor com.wombat.mama.MamaDictionary.getFeedHost ()
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getFieldByFid()
native MamaFieldDescriptor com.wombat.mama.MamaDictionary.getFieldByFid (int fid)
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getFieldByIndex()
native MamaFieldDescriptor com.wombat.mama.MamaDictionary.getFieldByIndex (int index)
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getFieldByName()
native MamaFieldDescriptor com.wombat.mama.MamaDictionary.getFieldByName (String name)
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getFieldByNameAll()
native Collection com.wombat.mama.MamaDictionary.getFieldByNameAll (String name)
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getMaxFid()
native int com.wombat.mama.MamaDictionary.getMaxFid ()
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
getSize()
native int com.wombat.mama.MamaDictionary.getSize ()
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
hasDuplicates()
native boolean com.wombat.mama.MamaDictionary.hasDuplicates ()
Referenced by com.wombat.mama.MamaDictionary.getPointerVal().
finalize()
void com.wombat.mama.MamaDictionary.finalize ()
References com.wombat.mama.MamaDictionary.writeToFile().
writeToFile()
native void com.wombat.mama.MamaDictionary.writeToFile (String file)
Referenced by com.wombat.mama.MamaDictionary.finalize().
populateFromFile()
void com.wombat.mama.MamaDictionary.populateFromFile (String file)
References com.wombat.mama.MamaDictionary._populateFromFile(), and com.wombat.mama.MamaDictionary.create().
_populateFromFile()
native void com.wombat.mama.MamaDictionary._populateFromFile (String file)
Referenced by com.wombat.mama.MamaDictionary.populateFromFile().
create()
native void com.wombat.mama.MamaDictionary.create ()
Referenced by com.wombat.mama.MamaDictionary.populateFromFile().