OpenMAMA Java API: com.wombat.mama.MamaMsg Class Reference
com.wombat.mama.MamaMsg Class Reference
Wrapper class for the native C mama msg structure.
Public Member Functions
MamaMsg ()
The default construction behaviour is to create the underlying C message structure.
MamaMsg (char payloadId)
Create a MamaMsg.
MamaMsg (MamaPayloadBridge payloadBridge)
Create a MamaMsg.
MamaBuffer getStringAsBuffer (MamaFieldDescriptor fieldDesc)
This function will obtain a string from the mama message and return it inside a MamaBuffer object without performing any memory allocation that would cause future garbage collection.
MamaBuffer getStringAsBuffer (String name, int fid)
This function will obtain a string from the mama message and return it inside a MamaBuffer object without performing any memory allocation that would cause future garbage collection.
boolean tryStringAsBuffer (String name, int fid, MamaBuffer mamaBuffer)
This function will obtain a string from the mama message and return it inside a MamaBuffer object without performing any memory allocation that would cause future garbage collection.
long getPointerVal ()
Return the native message pointer.
Iterator iterator (MamaDictionary dictionary)
Return a iterator for use with this MamaMsg.
Iterator iterator ()
Return an iterator for use with this MamaMsg.
native int getNumFields ()
Returns the total number of fields in the message.
native boolean getBoolean (String name, int fid)
Returns a Boolean value from the underlying message.
boolean getBoolean (MamaFieldDescriptor fieldDesc)
Returns a Boolean value from the underlying message.
native char getChar (String name, int fid)
Returns a Char value from the underlying message.
char getChar (MamaFieldDescriptor fieldDesc)
Returns a Char value from the underlying message.
native byte getI8 (String name, int fid)
Returns an I8 value from the underlying message.
byte getI8 (MamaFieldDescriptor fieldDesc)
Returns a Integer (I8) value from the underlying message.
native short getU8 (String name, int fid)
Returns a U8 value from the underlying message.
short getU8 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U8) value from the underlying message.
native short getI16 (String name, int fid)
Returns an I16 value from the underlying message.
short getI16 (MamaFieldDescriptor fieldDesc)
Returns a Integer (U16) value from the underlying message.
native int getU16 (String name, int fid)
Returns a U16 value from the underlying message.
int getU16 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U16) value from the underlying message.
native int getI32 (String name, int fid)
Returns an I32 value from the underlying message.
int getI32 (MamaFieldDescriptor fieldDesc)
Returns a Integer (I32) value from the underlying message.
native long getU32 (String name, int fid)
Returns a U32 value from the underlying message.
long getU32 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U32) value from the underlying message.
native long getI64 (String name, int fid)
Returns an I64 value from the underlying message.
long getI64 (MamaFieldDescriptor fieldDesc)
Returns a Integer (I64) value from the underlying message.
native long getU64 (String name, int fid)
Returns a U64 value from the underlying message.
long getU64 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U64) value from the underlying message.
native float getF32 (String name, int fid)
Returns an F32 value from the underlying message.
float getF32 (MamaFieldDescriptor fieldDesc)
Returns a Float (F32) value from the underlying message.
native double getF64 (String name, int fid)
Returns an F64 value from the underlying message.
double getF64 (MamaFieldDescriptor fieldDesc)
Returns a Double (F64) value from the underlying message.
native String getString (String name, int fid)
Returns a String value from the underlying message.
String getString (MamaFieldDescriptor fieldDesc)
Returns a String value from the underlying message.
native MamaMsg getMsg (String name, int fid)
Returns a MamaMsg value from the underlying message.
MamaMsg getMsg (MamaFieldDescriptor fieldDesc)
Returns a MamaMsg value from the underlying message.
native byte [] getByteBuffer ()
Return the internal message buffer as an array of bytes which is suitable for writing to a file.
void createFromByteBuffer (byte[] byteArray)
Create a mamaMsg from the provided byte buffer.
void setNewBuffer (byte[] byteArray)
Set a new buffer for an existing mamaMsg.
native byte [] getOpaque (String name, int fid)
Returns a Opaque value from the underlying message.
byte [] getOpaque (MamaFieldDescriptor fieldDesc)
Returns a Opaque (byte[]) value from the underlying message.
MamaDateTime getDateTime (String name, int fid)
Returns a MamaDateTime value from the underlying message.
MamaDateTime getDateTime (MamaFieldDescriptor fieldDesc)
Returns a MamaDateTime value from the underlying message.
MamaPrice getPrice (String name, int fid)
Returns a MamaPrice value from the underlying message.
MamaPrice getPrice (MamaFieldDescriptor fieldDesc)
Returns a MamaPrice value from the underlying message.
native MamaMsg [] getArrayMsg (String name, int fid)
Returns a Message Array value from the underlying message.
MamaMsg [] getArrayMsg (MamaFieldDescriptor fieldDesc)
Returns a MamaMsg Array (MamaMsg[]) value from the underlying message.
native byte [] getArrayI8 (String name, int fid)
Returns an I8 Array value from the underlying message.
byte [] getArrayI8 (MamaFieldDescriptor fieldDesc)
Returns an I8 Array (byte[]) value from the underlying message.
native short [] getArrayU8 (String name, int fid)
Returns a U8 Array value from the underlying message.
short [] getArrayU8 (MamaFieldDescriptor fieldDesc)
Returns a U8 Array (short[]) value from the underlying message.
native short [] getArrayI16 (String name, int fid)
Returns an I16 Array value from the underlying message.
short [] getArrayI16 (MamaFieldDescriptor fieldDesc)
Returns a I16 Array (short[]) value from the underlying message.
native int [] getArrayU16 (String name, int fid)
Returns a U16 Array value from the underlying message.
int [] getArrayU16 (MamaFieldDescriptor fieldDesc)
Returns a U16 Array (int[]) value from the underlying message.
native int [] getArrayI32 (String name, int fid)
Returns an I32 Array value from the underlying message.
int [] getArrayI32 (MamaFieldDescriptor fieldDesc)
Returns a I32 Array (int[]) value from the underlying message.
native long [] getArrayU32 (String name, int fid)
Returns a U32 Array value from the underlying message.
long [] getArrayU32 (MamaFieldDescriptor fieldDesc)
Returns a U32 Array (long[]) value from the underlying message.
native long [] getArrayI64 (String name, int fid)
Returns an I64 Array value from the underlying message.
long [] getArrayI64 (MamaFieldDescriptor fieldDesc)
Returns a I64 Array (long[]) value from the underlying message.
native long [] getArrayU64 (String name, int fid)
Returns an U64 Array value from the underlying message.
long [] getArrayU64 (MamaFieldDescriptor fieldDesc)
Returns a U64 Array (long[]) value from the underlying message.
native float [] getArrayF32 (String name, int fid)
Returns an F32 Array value from the underlying message.
float [] getArrayF32 (MamaFieldDescriptor fieldDesc)
Returns a F32 Array (float[]) value from the underlying message.
native double [] getArrayF64 (String name, int fid)
Returns an F64 Array value from the underlying message.
double [] getArrayF64 (MamaFieldDescriptor fieldDesc)
Returns a F32 Array (double[]) value from the underlying message.
native String [] getArrayString (String name, int fid)
Returns an String Array value from the underlying message.
String [] getArrayString (MamaFieldDescriptor fieldDesc)
Returns a String Array (string[]) value from the underlying message.
native boolean getIsDefinitelyDuplicate ()
Returns Boolean indiciating whether the underlying message is definitely duplicate.
native boolean getIsPossiblyDuplicate ()
Returns Boolean indiciating whether the underlying message is possibly duplicate.
native boolean getIsPossiblyDelayed ()
Returns Boolean indiciating whether the underlying message is possibly delayed.
native boolean getIsDefinitelyDelayed ()
Returns Boolean indiciating whether the underlying message is definitely delayed.
native boolean getIsOutOfSequence ()
Returns Boolean indiciating whether the underlying message is out of sequence.
native long getSeqNum ()
Returns the Sequence Number from the underlying message.
void addBool (String name, int fid, boolean value)
Add a Boolean value to the underlying message.
native void addBoolean (String name, int fid, boolean value)
Add a Boolean value to the underlying message.
native void addChar (String name, int fid, char value)
Add a Char value to the underlying message.
native void addI8 (String name, int fid, byte value)
Add an I8 (byte) value to the underlying message.
native void addU8 (String name, int fid, short value)
Add an U8 (byte) value to the underlying message.
native void addI16 (String name, int fid, short value)
Add an I16 (short) value to the underlying message.
native void addU16 (String name, int fid, int value)
Add an U16 (short) value to the underlying message.
native void addI32 (String name, int fid, int value)
Add an I32 (int) value to the underlying message.
native void addU32 (String name, int fid, long value)
Add an U32 (int) value to the underlying message.
native void addI64 (String name, int fid, long value)
Add an I64 (long) value to the underlying message.
native void addU64 (String name, int fid, long value)
Add an U64 (long) value to the underlying message.
native void addF32 (String name, int fid, float value)
Add an F32 (float) value to the underlying message.
native void addF64 (String name, int fid, double value)
Add an F64 (double) value to the underlying message.
native void addString (String name, int fid, String value)
Add an String (Java String) value to the underlying message.
native void addDateTime (String name, int fid, MamaDateTime value)
Add an MamaDateTime value to the underlying message.
native void addPrice (String name, int fid, MamaPrice value)
Add an MamaPrice value to the underlying message.
native void addMsg (String name, int fid, MamaMsg value)
Add an MamaMsg value to the underlying message.
native void addOpaque (String name, int fid, byte[] value)
Add an Opaque (byte[]) value to the underlying message.
native void addArrayI8 (String name, int fid, byte[] value)
Add an I8 Array (byte[]) value to the underlying message.
native void addArrayU8 (String name, int fid, short[] value)
Add a U8 Array (short[]) value to the underlying message.
native void addArrayI16 (String name, int fid, short[] value)
Add an I16 Array (short[]) value to the underlying message.
native void addArrayU16 (String name, int fid, int[] value)
Add a U16 Array (int[]) value to the underlying message.
native void addArrayI32 (String name, int fid, int[] value)
Add an I32 Array (int[]) value to the underlying message.
native void addArrayU32 (String name, int fid, long[] value)
Add a U32 Array (long[]) value to the underlying message.
native void addArrayI64 (String name, int fid, long[] value)
Add an I64 Array (long[]) value to the underlying message.
native void addArrayU64 (String name, int fid, long[] value)
Add a U64 Array (long[]) value to the underlying message.
native void addArrayF32 (String name, int fid, float[] value)
Add a F32 Array (float[]) value to the underlying message.
native void addArrayF64 (String name, int fid, double[] value)
Add a F64 Array (double[]) value to the underlying message.
native void addArrayMsg (String name, int fid, MamaMsg[] value)
Add a MamaMsg Array (MamaMsg[]) value to the underlying message.
native void addArrayMsgWithLength (String name, int fid, MamaMsg[] value, int length)
This function will add a new field containing an array of messages.
native void addArrayString (String name, int fid, String[] value, int length)
Add a String Array (String[]) value to the underlying message.
void addArrayString (String name, int fid, String[] value)
Add a String Array (String[]) value to the underlying message.
native void updateI8 (String name, int fid, byte value)
Update the value of an I8 (byte) value in the underlying message.
native void updateU8 (String name, int fid, short value)
Update the value of a U8 (byte) value in the underlying message.
native void updateI16 (String name, int fid, short value)
Update the value of an I16 (short) value in the underlying message.
native void updateU16 (String name, int fid, int value)
Update the value of a U16 (short) value in the underlying message.
native void updateI32 (String name, int fid, int value)
Update the value of an I32 (int) value in the underlying message.
native void updateU32 (String name, int fid, long value)
Update the value of a U32 (int) value in the underlying message.
native void updateI64 (String name, int fid, long value)
Update the value of an I64 (long) value in the underlying message.
native void updateU64 (String name, int fid, long value)
Update the value of a U64 (long) value in the underlying message.
native void updateF32 (String name, int fid, float value)
Update the value of an F32 (float) value in the underlying message.
native void updateF64 (String name, int fid, double value)
Update the value of an F64 (double) value in the underlying message.
native void updateString (String name, int fid, String value)
Update the value of an String (Java String) value in the underlying message.
native void updatePrice (String name, int fid, MamaPrice value)
Update the value of a MamaPrice value in the underlying message.
native void updateBoolean (String name, int fid, boolean value)
Update the value of a Boolean value in the underlying message.
native void updateChar (String name, int fid, char value)
Update the value of an Char value in the underlying message.
native void updateDateTime (String name, int fid, MamaDateTime value)
Update the value of an MamaDateTime value in the underlying message.
native void updateArrayI8 (String name, int fid, byte[] value)
Update the value of an I8 (byte[]) value in the underlying message.
native void updateArrayU8 (String name, int fid, short[] value)
Update the value of a U8 (short[]) value in the underlying message.
native void updateArrayI16 (String name, int fid, short[] value)
Update the value of an I16 (short[]) value in the underlying message.
native void updateArrayU16 (String name, int fid, int[] value)
Update the value of a U16 (int[]) value in the underlying message.
native void updateArrayI32 (String name, int fid, int[] value)
Update the value of an I32 (int[]) value in the underlying message.
native void updateArrayU32 (String name, int fid, long[] value)
Update the value of a U32 (long[]) value in the underlying message.
native void updateArrayI64 (String name, int fid, long[] value)
Update the value of an I64 (long[]) value in the underlying message.
native void updateArrayU64 (String name, int fid, long[] value)
Update the value of a U64 (long[]) value in the underlying message.
native void updateArrayF32 (String name, int fid, float[] value)
Update the value of an F32 (float[]) value in the underlying message.
native void updateArrayF64 (String name, int fid, double[] value)
Update the value of an F64 (double[]) value in the underlying message.
char getChar (String name, int fid, char defaultValue)
Return the value of a Char field from the underlying message.
char getChar (MamaFieldDescriptor fieldDesc, char defaultValue)
Return the value of a Char field from the underlying message.
byte getI8 (String name, int fid, byte defaultValue)
Return the value of an I8 field from the underlying message.
byte getI8 (MamaFieldDescriptor fieldDesc, byte defaultValue)
Return the value of an I8 field from the underlying message.
short getU8 (String name, int fid, short defaultValue)
Return the value of a U8 field from the underlying message.
short getU8 (MamaFieldDescriptor fieldDesc, short defaultValue)
Return the value of a U8 field from the underlying message.
short getI16 (String name, int fid, short defaultValue)
Return the value of an I16 field from the underlying message.
short getI16 (MamaFieldDescriptor fieldDesc, short defaultValue)
Return the value of an I16 field from the underlying message.
int getU16 (String name, int fid, int defaultValue)
Return the value of a U16 field from the underlying message.
int getU16 (MamaFieldDescriptor fieldDesc, int defaultValue)
Return the value of a U16 field from the underlying message.
int getI32 (String name, int fid, int defaultValue)
Return the value of an I32 field from the underlying message.
int getI32 (MamaFieldDescriptor fieldDesc, int defaultValue)
Return the value of an I32 field from the underlying message.
long getU32 (String name, int fid, long defaultValue)
Return the value of a U32 field from the underlying message.
long getU32 (MamaFieldDescriptor fieldDesc, long defaultValue)
Return the value of a U32 field from the underlying message.
long getI64 (String name, int fid, long defaultValue)
Return the value of an I64 field from the underlying message.
long getI64 (MamaFieldDescriptor fieldDesc, long defaultValue)
Return the value of an I64 field from the underlying message.
long getU64 (String name, int fid, long defaultValue)
Return the value of a U64 field from the underlying message.
long getU64 (MamaFieldDescriptor fieldDesc, long defaultValue)
Return the value of a U64 field from the underlying message.
float getF32 (String name, int fid, float defaultValue)
Return the value of an F32 field from the underlying message.
float getF32 (MamaFieldDescriptor fieldDesc, float defaultValue)
Return the value of an F32 field from the underlying message.
double getF64 (String name, int fid, double defaultValue)
Return the value of an F64 field from the underlying message.
double getF64 (MamaFieldDescriptor fieldDesc, double defaultValue)
Return the value of an F64 field from the underlying message.
String getString (String name, int fid, String defaultValue)
Return the value of a String field from the underlying message.
String getString (MamaFieldDescriptor fieldDesc, String defaultValue)
Return the value of a String field from the underlying message.
MamaPrice getPrice (String name, int fid, MamaPrice defaultValue)
Return the value of a MamaPrice field from the underlying message.
MamaPrice getPrice (MamaFieldDescriptor fieldDesc, MamaPrice defaultValue)
Return the value of a MamaPrice field from the underlying message.
MamaMsg getMsg (MamaFieldDescriptor fieldDesc, MamaMsg defaultValue)
Return the value of a MamaMsg field from the underlying message.
int [] getArrayI32 (MamaFieldDescriptor fieldDesc, int[] defaultValue)
Return the value of an I32 Array field from the underlying message.
MamaMsg [] getArrayMsg (MamaFieldDescriptor fieldDesc, MamaMsg[] defaultValue)
Return the value of a MamaMsg Array field from the underlying message.
native boolean tryBoolean (String name, int fid, MamaBoolean result)
Try to get the value of a Boolean field from the underlying message.
boolean tryBoolean (MamaFieldDescriptor field, MamaBoolean result)
Return the value of a MamaBoolean field from the underlying message.
native boolean tryChar (String name, int fid, MamaChar result)
Try to get the value of a MamaChar field from the underlying message.
boolean tryChar (MamaFieldDescriptor field, MamaChar result)
Return the value of a MamaChar field from the underlying message.
native boolean tryI8 (String name, int fid, MamaByte result)
Try to get the value of a MamaByte field from the underlying message.
boolean tryI8 (MamaFieldDescriptor field, MamaByte result)
Return the value of a MamaByte field from the underlying message.
native boolean tryU8 (String name, int fid, MamaShort result)
Try to get the value of a MamaShort field from the underlying message.
boolean tryU8 (MamaFieldDescriptor field, MamaShort result)
Return the value of a MamaShort field from the underlying message.
native boolean tryI16 (String name, int fid, MamaShort result)
Try to get the value of a MamaShort field from the underlying message.
boolean tryI16 (MamaFieldDescriptor field, MamaShort result)
Return the value of a MamaShort field from the underlying message.
native boolean tryU16 (String name, int fid, MamaInteger result)
Try to get the value of a MamaInteger field from the underlying message.
boolean tryU16 (MamaFieldDescriptor field, MamaInteger result)
Return the value of a MamaInteger field from the underlying message.
native boolean tryI32 (String name, int fid, MamaInteger result)
Try to get the value of a MamaInteger field from the underlying message.
boolean tryI32 (MamaFieldDescriptor field, MamaInteger result)
Return the value of a MamaInteger field from the underlying message.
native boolean tryU32 (String name, int fid, MamaLong result)
Try to get the value of a MamaLong field from the underlying message.
boolean tryU32 (MamaFieldDescriptor field, MamaLong result)
Return the value of a MamaLong field from the underlying message.
native boolean tryI64 (String name, int fid, MamaLong result)
Try to get the value of a MamaLong field from the underlying message.
boolean tryI64 (MamaFieldDescriptor field, MamaLong result)
Return the value of a MamaLong field from the underlying message.
native boolean tryU64 (String name, int fid, MamaLong result)
Try to get the value of a MamaLong field from the underlying message.
boolean tryU64 (MamaFieldDescriptor field, MamaLong result)
Return the value of a MamaLong field from the underlying message.
native boolean tryF32 (String name, int fid, MamaFloat result)
Try to get the value of a MamaFloat field from the underlying message.
boolean tryF32 (MamaFieldDescriptor field, MamaFloat result)
Return the value of a MamaFloat field from the underlying message.
native boolean tryF64 (String name, int fid, MamaDouble result)
Try to get the value of a MamaDouble field from the underlying message.
boolean tryF64 (MamaFieldDescriptor field, MamaDouble result)
Return the value of a MamaDouble field from the underlying message.
boolean tryDateTime (MamaFieldDescriptor field, MamaDateTime result)
Return the value of a MamaDateTime field from the underlying message.
native boolean tryDateTime (String name, int fid, MamaDateTime result)
Try to get the value of a MamaDateTime field from the underlying message.
boolean tryPrice (MamaFieldDescriptor field, MamaPrice result)
Return the value of a MamaPrice field from the underlying message.
native boolean tryPrice (String name, int fid, MamaPrice result)
Try to get the value of a MamaPrice field from the underlying message.
native boolean tryString (String name, int fid, MamaString result)
Try to get the value of a MamaString field from the underlying message.
boolean tryString (MamaFieldDescriptor field, MamaString result)
Return the value of a MamaString field from the underlying message.
boolean tryOpaque (String name, int fid, MamaOpaque result)
Try to get the value of a MamaOpaque field from the underlying message.
boolean tryOpaque (MamaFieldDescriptor field, MamaOpaque result)
Return the value of a MamaOpaque field from the underlying message.
boolean tryMsg (String name, int fid, MamaMessage result)
Try to get the value of a MamaMessage field from the underlying message.
boolean tryMsg (MamaFieldDescriptor field, MamaMessage result)
Return the value of a MamaMessage field from the underlying message.
boolean tryArrayI32 (String name, int fid, MamaArrayInt result)
Try to get the value of a MamaArrayInt field from the underlying message.
boolean tryArrayI32 (MamaFieldDescriptor field, MamaArrayInt result)
Return the value of a MamaArrayInt field from the underlying message.
boolean tryArrayU16 (String name, int fid, MamaArrayInt result)
Try to get the value of a MamaArrayInt field from the underlying message.
boolean tryArrayU16 (MamaFieldDescriptor field, MamaArrayInt result)
Return the value of a MamaArrayInt field from the underlying message.
boolean tryArrayMsg (String name, int fid, MamaArrayMsg result)
Try to get the value of a MamaArrayMsg field from the underlying message.
boolean tryArrayMsg (MamaFieldDescriptor field, MamaArrayMsg result)
Return the value of a MamaArrayMsg field from the underlying message.
boolean tryArrayString (String name, int fid, MamaArrayString result)
Try to get the value of a MamaArrayString field from the underlying message.
boolean tryArrayString (MamaFieldDescriptor field, MamaArrayString result)
Return the value of a MamaArrayMsg field from the underlying message.
void iterateFields (MamaMsgFieldIterator iterator, MamaDictionary dictionary, Object closure)
Iterate over all of the fields within the message.
native String getFieldAsString (int fid, MamaDictionary dictionary)
Return a String representation of the entire message.
native boolean isFromInbox ()
Return a String representation of the entire message.
native String toString ()
Return a String representation of the entire message.
native char getPayloadType ()
Return as a character representation of the payload type used in the message.
void destroy ()
Destroy the internal state of the MamaMsg object.
native void clear ()
Clear the message.
native void copy (MamaMsg rhs)
Create a deep copy of the message.
native MamaMsg detach ()
Detach the message.
native void apply (MamaMsg rhs)
Update the MamaMsg with the fields of another MamaMsg.
MamaMsgField getField (MamaFieldDescriptor field, MamaDictionary dict)
Get a specified field from a message, or null if not found.
MamaMsgField getField (String fieldName, int fid, MamaDictionary dict)
Get a specified field from a message, or null if not found.
Protected Member Functions
void finalize ()
Detailed Description
Wrapper class for the native C mama msg structure.
Field identifiers must be >=0. A field identifier of 0 indicates that there is no unique FID and multiple fields with the same name may have FID == 0.
Field lookup proceeds in the following manner.
If the fid supplied is non-zero, search for a field with the specified fid and return the field if it exists (the name is not validated). Otherwise return null.
If the fid supplied is 0, return the first field encountered with the supplied name or null if no such field exists.
Get methods for numeric values may result in loss of information through either rounding or truncation when a larger data type is accessed as a smaller one. The result may be the same as the result of casting the larger value to the smaller. For example calling getShort for an integer field with a value greater than Short.MAX_VALUE might return Short.MIN_VALUE. It is also valid to throw a ClassCastException or other appropriate RuntimeException.
Since some message implementations may not natively support all data types, the behaviour may vary substantially. In creating and accessing messages the Wombat APIs assume that the underlying values are stored in the smallest possible fields, and accesses them accordingly. For this reason the minimal requirement is that the methods for accessing and creating fields support the full range of values appropriate for their type. How they deal with larger values should be irrelevant.
Constructor & Destructor Documentation
MamaMsg() [1/3]
com.wombat.mama.MamaMsg.MamaMsg ()
The default construction behaviour is to create the underlying C message structure.
We need this when users are creating their own messages when using the publishing API.
Referenced by com.wombat.mama.MamaMsg.MamaMsg().
MamaMsg() [2/3]
com.wombat.mama.MamaMsg.MamaMsg (char payloadId)
Create a MamaMsg.
Parameters
payloadId The identifier of the payload to be used.
MamaMsg() [3/3]
com.wombat.mama.MamaMsg.MamaMsg (MamaPayloadBridge payloadBridge)
Create a MamaMsg.
Parameters
payloadBridge The MamaPayloadBridge to be used
References com.wombat.mama.MamaMsg.MamaMsg().
Member Function Documentation
getStringAsBuffer() [1/2]
MamaBuffer com.wombat.mama.MamaMsg.getStringAsBuffer (MamaFieldDescriptor fieldDesc)
This function will obtain a string from the mama message and return it inside a MamaBuffer object without performing any memory allocation that would cause future garbage collection.
Parameters
fieldDesc The field descriptor.
Returns
A MamaBuffer containing single byte ASCII characters, to obtain a unicode string call MamaBuffer.asCharBuffer.
Exceptions
WombatException Thrown if the field descriptor is null.
References com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
Referenced by com.wombat.mama.MamaMsg.getStringAsBuffer().
getStringAsBuffer() [2/2]
MamaBuffer com.wombat.mama.MamaMsg.getStringAsBuffer (String name, int fid)
This function will obtain a string from the mama message and return it inside a MamaBuffer object without performing any memory allocation that would cause future garbage collection.
Parameters
name The field name.
fid The field Id.
Returns
A MamaBuffer containing single byte ASCII characters, to obtain a unicode string call MamaBuffer.asCharBuffer.
References com.wombat.mama.MamaBuffer.array(), com.wombat.mama.MamaMsg.getStringAsBuffer(), com.wombat.mama.MamaBuffer.grow(), and com.wombat.mama.MamaBuffer.limit().
tryStringAsBuffer()
boolean com.wombat.mama.MamaMsg.tryStringAsBuffer (String name, int fid, MamaBuffer mamaBuffer)
This function will obtain a string from the mama message and return it inside a MamaBuffer object without performing any memory allocation that would cause future garbage collection.
If the field is not in the message the function will return FALSE.
Parameters
name The field name.
fid The field Id.
mamaBuffer A MamaBuffer that will contain the string if it is present in the message.
Returns
Boolean indicating of the field was present in the message or not.
References com.wombat.mama.MamaBuffer.array(), com.wombat.mama.MamaBuffer.grow(), and com.wombat.mama.MamaBuffer.limit().
getPointerVal()
long com.wombat.mama.MamaMsg.getPointerVal ()
Return the native message pointer.
Returns
The message pointer (Long)
iterator() [1/2]
Iterator com.wombat.mama.MamaMsg.iterator (MamaDictionary dictionary)
Return a iterator for use with this MamaMsg.
Parameters
dictionary The dictionary to use for iterating over the message
Returns
The message iterator (Iterator)
References com.wombat.mama.MamaMsgIterator.reset().
iterator() [2/2]
Iterator com.wombat.mama.MamaMsg.iterator ()
Return an iterator for use with this MamaMsg.
Returns
A message iterator (Iterator)
References com.wombat.mama.MamaMsg.getBoolean(), and com.wombat.mama.MamaMsg.getNumFields().
Referenced by com.wombat.mama.MamaMsg.iterateFields().
getNumFields()
native int com.wombat.mama.MamaMsg.getNumFields ()
Returns the total number of fields in the message.
Returns
Number of fields in the message as in int
Referenced by com.wombat.mama.MamaMsg.iterator().
getBoolean() [1/2]
native boolean com.wombat.mama.MamaMsg.getBoolean (String name, int fid)
Returns a Boolean value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a boolean
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getBoolean(), and com.wombat.mama.MamaMsg.iterator().
getBoolean() [2/2]
boolean com.wombat.mama.MamaMsg.getBoolean (MamaFieldDescriptor fieldDesc)
Returns a Boolean value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a boolean
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getBoolean(), com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getChar() [1/4]
native char com.wombat.mama.MamaMsg.getChar (String name, int fid)
Returns a Char value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a char
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getBoolean(), and com.wombat.mama.MamaMsg.getChar().
getChar() [2/4]
char com.wombat.mama.MamaMsg.getChar (MamaFieldDescriptor fieldDesc)
Returns a Char value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a boolean
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI8(), and com.wombat.mama.MamaFieldDescriptor.getName().
getI8() [1/4]
native byte com.wombat.mama.MamaMsg.getI8 (String name, int fid)
Returns an I8 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a byte
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaMsg.getI8(), and com.wombat.mama.MamaMsg.getU8().
getI8() [2/4]
byte com.wombat.mama.MamaMsg.getI8 (MamaFieldDescriptor fieldDesc)
Returns a Integer (I8) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a byte
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI8(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU8().
getU8() [1/4]
native short com.wombat.mama.MamaMsg.getU8 (String name, int fid)
Returns a U8 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a short
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI8(), com.wombat.mama.MamaMsg.getU8(), and com.wombat.mama.MamaMdMsgType.typeForMsg().
getU8() [2/4]
short com.wombat.mama.MamaMsg.getU8 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U8) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a short
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaMsg.getI8(), and com.wombat.mama.MamaFieldDescriptor.getName().
getI16() [1/4]
native short com.wombat.mama.MamaMsg.getI16 (String name, int fid)
Returns an I16 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a short
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaMsg.getU8(), and com.wombat.mama.MamaMsgType.typeForMsg().
getI16() [2/4]
short com.wombat.mama.MamaMsg.getI16 (MamaFieldDescriptor fieldDesc)
Returns a Integer (U16) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a short
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU16().
getU16() [1/4]
native int com.wombat.mama.MamaMsg.getU16 (String name, int fid)
Returns a U16 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a int
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI16(), and com.wombat.mama.MamaMsg.getU16().
getU16() [2/4]
int com.wombat.mama.MamaMsg.getU16 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U16) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a int
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU16().
getI32() [1/4]
native int com.wombat.mama.MamaMsg.getI32 (String name, int fid)
Returns an I32 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a int
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaMsg.getU16(), and com.wombat.mama.MamaMsgStatus.statusForMsg().
getI32() [2/4]
int com.wombat.mama.MamaMsg.getI32 (MamaFieldDescriptor fieldDesc)
Returns a Integer (I32) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a int
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU32().
getU32() [1/4]
native long com.wombat.mama.MamaMsg.getU32 (String name, int fid)
Returns a U32 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a long
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI32(), and com.wombat.mama.MamaMsg.getU32().
getU32() [2/4]
long com.wombat.mama.MamaMsg.getU32 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U32) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a long
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI64(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU32().
getI64() [1/4]
native long com.wombat.mama.MamaMsg.getI64 (String name, int fid)
Returns an I64 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a long
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI64(), and com.wombat.mama.MamaMsg.getU32().
getI64() [2/4]
long com.wombat.mama.MamaMsg.getI64 (MamaFieldDescriptor fieldDesc)
Returns a Integer (I64) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a long
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI64(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU64().
getU64() [1/4]
native long com.wombat.mama.MamaMsg.getU64 (String name, int fid)
Returns a U64 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a long
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getI64(), and com.wombat.mama.MamaMsg.getU64().
getU64() [2/4]
long com.wombat.mama.MamaMsg.getU64 (MamaFieldDescriptor fieldDesc)
Returns a Unsigned Integer (U64) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a long
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getF32(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU64().
getF32() [1/4]
native float com.wombat.mama.MamaMsg.getF32 (String name, int fid)
Returns an F32 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a float
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getF32(), and com.wombat.mama.MamaMsg.getU64().
getF32() [2/4]
float com.wombat.mama.MamaMsg.getF32 (MamaFieldDescriptor fieldDesc)
Returns a Float (F32) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a float
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getF32(), com.wombat.mama.MamaMsg.getF64(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getF64() [1/4]
native double com.wombat.mama.MamaMsg.getF64 (String name, int fid)
Returns an F64 value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a double
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getF32(), and com.wombat.mama.MamaMsg.getF64().
getF64() [2/4]
double com.wombat.mama.MamaMsg.getF64 (MamaFieldDescriptor fieldDesc)
Returns a Double (F64) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a double
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getF64(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getString().
getString() [1/4]
native String com.wombat.mama.MamaMsg.getString (String name, int fid)
Returns a String value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a String
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getF64(), and com.wombat.mama.MamaMsg.getString().
getString() [2/4]
String com.wombat.mama.MamaMsg.getString (MamaFieldDescriptor fieldDesc)
Returns a String value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a string
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getMsg(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getString().
getMsg() [1/3]
native MamaMsg com.wombat.mama.MamaMsg.getMsg (String name, int fid)
Returns a MamaMsg value from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
Returns
The field value as a MamaMsg
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getMsg(), and com.wombat.mama.MamaMsg.getString().
getMsg() [2/3]
MamaMsg com.wombat.mama.MamaMsg.getMsg (MamaFieldDescriptor fieldDesc)
Returns a MamaMsg value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a MamaMsg
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getByteBuffer(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getMsg(), and com.wombat.mama.MamaFieldDescriptor.getName().
getByteBuffer()
native byte [] com.wombat.mama.MamaMsg.getByteBuffer ()
Return the internal message buffer as an array of bytes which is suitable for writing to a file.
Note that this is a copy of the bytes in the current buffer.
Returns
The byte array containing the message wire format
Referenced by com.wombat.mama.MamaMsg.getMsg().
createFromByteBuffer()
void com.wombat.mama.MamaMsg.createFromByteBuffer (byte [] byteArray)
Create a mamaMsg from the provided byte buffer.
This function causes a memory buffer to be allocated that is persisted for the lifetime of the message. Therefore calling this function a second time will cause an error. Instead destroy the message and then re-created it using this function.
Parameters
byteArray The byte array containing the wire format of the message
setNewBuffer()
void com.wombat.mama.MamaMsg.setNewBuffer (byte [] byteArray)
Set a new buffer for an existing mamaMsg.
This approach is faster than creating a new message for buffers as the message can reuse memory allocated during previous use.
Parameters
byteArray The byte array containing the wire format of the message
Exceptions
WombatException will be thrown if the byteArray is null
References com.wombat.mama.MamaMsg.getOpaque().
getOpaque() [1/2]
native byte [] com.wombat.mama.MamaMsg.getOpaque (String name, int fid)
Returns a Opaque value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a byte[]
Referenced by com.wombat.mama.MamaMsg.getOpaque(), and com.wombat.mama.MamaMsg.setNewBuffer().
getOpaque() [2/2]
byte [] com.wombat.mama.MamaMsg.getOpaque (MamaFieldDescriptor fieldDesc)
Returns a Opaque (byte[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a byte[]
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getOpaque().
getDateTime() [1/2]
MamaDateTime com.wombat.mama.MamaMsg.getDateTime (String name, int fid)
Returns a MamaDateTime value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a MamaDateTime
References com.wombat.mama.MamaDateTime.getPointerVal().
Referenced by com.wombat.mama.MamaMsg.getDateTime().
getDateTime() [2/2]
MamaDateTime com.wombat.mama.MamaMsg.getDateTime (MamaFieldDescriptor fieldDesc)
Returns a MamaDateTime value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a MamaDateTime
References com.wombat.mama.MamaMsg.getDateTime(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getPrice() [1/4]
MamaPrice com.wombat.mama.MamaMsg.getPrice (String name, int fid)
Returns a MamaPrice value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a MamaPrice
References com.wombat.mama.MamaPrice.getPointerVal().
Referenced by com.wombat.mama.MamaMsg.getPrice().
getPrice() [2/4]
MamaPrice com.wombat.mama.MamaMsg.getPrice (MamaFieldDescriptor fieldDesc)
Returns a MamaPrice value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a MamaPrice
References com.wombat.mama.MamaMsg.getArrayMsg(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getPrice().
getArrayMsg() [1/3]
native MamaMsg [] com.wombat.mama.MamaMsg.getArrayMsg (String name, int fid)
Returns a Message Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a MamaMsg[]
Referenced by com.wombat.mama.MamaMsg.getArrayMsg(), and com.wombat.mama.MamaMsg.getPrice().
getArrayMsg() [2/3]
MamaMsg [] com.wombat.mama.MamaMsg.getArrayMsg (MamaFieldDescriptor fieldDesc)
Returns a MamaMsg Array (MamaMsg[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a MamaMsg[]
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getArrayI8(), com.wombat.mama.MamaMsg.getArrayMsg(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayI8() [1/2]
native byte [] com.wombat.mama.MamaMsg.getArrayI8 (String name, int fid)
Returns an I8 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a byte[]
Referenced by com.wombat.mama.MamaMsg.getArrayI8(), and com.wombat.mama.MamaMsg.getArrayMsg().
getArrayI8() [2/2]
byte [] com.wombat.mama.MamaMsg.getArrayI8 (MamaFieldDescriptor fieldDesc)
Returns an I8 Array (byte[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a byte[]
References com.wombat.mama.MamaMsg.getArrayI8(), com.wombat.mama.MamaMsg.getArrayU8(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayU8() [1/2]
native short [] com.wombat.mama.MamaMsg.getArrayU8 (String name, int fid)
Returns a U8 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a short[]
Referenced by com.wombat.mama.MamaMsg.getArrayI8(), and com.wombat.mama.MamaMsg.getArrayU8().
getArrayU8() [2/2]
short [] com.wombat.mama.MamaMsg.getArrayU8 (MamaFieldDescriptor fieldDesc)
Returns a U8 Array (short[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a short[]
References com.wombat.mama.MamaMsg.getArrayI16(), com.wombat.mama.MamaMsg.getArrayU8(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayI16() [1/2]
native short [] com.wombat.mama.MamaMsg.getArrayI16 (String name, int fid)
Returns an I16 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a short[]
Referenced by com.wombat.mama.MamaMsg.getArrayI16(), and com.wombat.mama.MamaMsg.getArrayU8().
getArrayI16() [2/2]
short [] com.wombat.mama.MamaMsg.getArrayI16 (MamaFieldDescriptor fieldDesc)
Returns a I16 Array (short[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a short[]
References com.wombat.mama.MamaMsg.getArrayI16(), com.wombat.mama.MamaMsg.getArrayU16(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayU16() [1/2]
native int [] com.wombat.mama.MamaMsg.getArrayU16 (String name, int fid)
Returns a U16 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a int[]
Referenced by com.wombat.mama.MamaMsg.getArrayI16(), and com.wombat.mama.MamaMsg.getArrayU16().
getArrayU16() [2/2]
int [] com.wombat.mama.MamaMsg.getArrayU16 (MamaFieldDescriptor fieldDesc)
Returns a U16 Array (int[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a int[]
References com.wombat.mama.MamaMsg.getArrayI32(), com.wombat.mama.MamaMsg.getArrayU16(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayI32() [1/3]
native int [] com.wombat.mama.MamaMsg.getArrayI32 (String name, int fid)
Returns an I32 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a int[]
Referenced by com.wombat.mama.MamaMsg.getArrayI32(), and com.wombat.mama.MamaMsg.getArrayU16().
getArrayI32() [2/3]
int [] com.wombat.mama.MamaMsg.getArrayI32 (MamaFieldDescriptor fieldDesc)
Returns a I32 Array (int[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a int[]
References com.wombat.mama.MamaMsg.getArrayI32(), com.wombat.mama.MamaMsg.getArrayU32(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayU32() [1/2]
native long [] com.wombat.mama.MamaMsg.getArrayU32 (String name, int fid)
Returns a U32 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a long[]
Referenced by com.wombat.mama.MamaMsg.getArrayI32(), and com.wombat.mama.MamaMsg.getArrayU32().
getArrayU32() [2/2]
long [] com.wombat.mama.MamaMsg.getArrayU32 (MamaFieldDescriptor fieldDesc)
Returns a U32 Array (long[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a long[]
References com.wombat.mama.MamaMsg.getArrayI64(), com.wombat.mama.MamaMsg.getArrayU32(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayI64() [1/2]
native long [] com.wombat.mama.MamaMsg.getArrayI64 (String name, int fid)
Returns an I64 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a long[]
Referenced by com.wombat.mama.MamaMsg.getArrayI64(), and com.wombat.mama.MamaMsg.getArrayU32().
getArrayI64() [2/2]
long [] com.wombat.mama.MamaMsg.getArrayI64 (MamaFieldDescriptor fieldDesc)
Returns a I64 Array (long[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a long[]
References com.wombat.mama.MamaMsg.getArrayI64(), com.wombat.mama.MamaMsg.getArrayU64(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayU64() [1/2]
native long [] com.wombat.mama.MamaMsg.getArrayU64 (String name, int fid)
Returns an U64 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a long[]
Referenced by com.wombat.mama.MamaMsg.getArrayI64(), and com.wombat.mama.MamaMsg.getArrayU64().
getArrayU64() [2/2]
long [] com.wombat.mama.MamaMsg.getArrayU64 (MamaFieldDescriptor fieldDesc)
Returns a U64 Array (long[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a long[]
References com.wombat.mama.MamaMsg.getArrayF32(), com.wombat.mama.MamaMsg.getArrayU64(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayF32() [1/2]
native float [] com.wombat.mama.MamaMsg.getArrayF32 (String name, int fid)
Returns an F32 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a float[]
Referenced by com.wombat.mama.MamaMsg.getArrayF32(), and com.wombat.mama.MamaMsg.getArrayU64().
getArrayF32() [2/2]
float [] com.wombat.mama.MamaMsg.getArrayF32 (MamaFieldDescriptor fieldDesc)
Returns a F32 Array (float[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a float[]
References com.wombat.mama.MamaMsg.getArrayF32(), com.wombat.mama.MamaMsg.getArrayF64(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayF64() [1/2]
native double [] com.wombat.mama.MamaMsg.getArrayF64 (String name, int fid)
Returns an F64 Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a double[]
Referenced by com.wombat.mama.MamaMsg.getArrayF32(), and com.wombat.mama.MamaMsg.getArrayF64().
getArrayF64() [2/2]
double [] com.wombat.mama.MamaMsg.getArrayF64 (MamaFieldDescriptor fieldDesc)
Returns a F32 Array (double[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a double[]
References com.wombat.mama.MamaMsg.getArrayF64(), com.wombat.mama.MamaMsg.getArrayString(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayString() [1/2]
native String [] com.wombat.mama.MamaMsg.getArrayString (String name, int fid)
Returns an String Array value from the underlying message.
Parameters
name The name of the field
fid The FID of the field
Returns
The field value as a string[]
Referenced by com.wombat.mama.MamaMsg.getArrayF64(), and com.wombat.mama.MamaMsg.getArrayString().
getArrayString() [2/2]
String [] com.wombat.mama.MamaMsg.getArrayString (MamaFieldDescriptor fieldDesc)
Returns a String Array (string[]) value from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor of the message field that you wich to retrieve
Returns
The field value as a string[]
Exceptions
WombatException will be thrown if the fieldDesc is null
References com.wombat.mama.MamaMsg.getArrayString(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getIsDefinitelyDelayed(), com.wombat.mama.MamaMsg.getIsDefinitelyDuplicate(), com.wombat.mama.MamaMsg.getIsOutOfSequence(), com.wombat.mama.MamaMsg.getIsPossiblyDelayed(), com.wombat.mama.MamaMsg.getIsPossiblyDuplicate(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getSeqNum().
getIsDefinitelyDuplicate()
native boolean com.wombat.mama.MamaMsg.getIsDefinitelyDuplicate ()
Returns Boolean indiciating whether the underlying message is definitely duplicate.
Returns
Boolean indiciating whether the message is a duplicate
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getArrayString().
getIsPossiblyDuplicate()
native boolean com.wombat.mama.MamaMsg.getIsPossiblyDuplicate ()
Returns Boolean indiciating whether the underlying message is possibly duplicate.
Returns
Boolean indiciating whether the message is a possibly a duplicate
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getArrayString().
getIsPossiblyDelayed()
native boolean com.wombat.mama.MamaMsg.getIsPossiblyDelayed ()
Returns Boolean indiciating whether the underlying message is possibly delayed.
Returns
Boolean indiciating whether the message is a possibly delayed
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getArrayString().
getIsDefinitelyDelayed()
native boolean com.wombat.mama.MamaMsg.getIsDefinitelyDelayed ()
Returns Boolean indiciating whether the underlying message is definitely delayed.
Returns
Boolean indiciating whether the message is a definitely delayed
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getArrayString().
getIsOutOfSequence()
native boolean com.wombat.mama.MamaMsg.getIsOutOfSequence ()
Returns Boolean indiciating whether the underlying message is out of sequence.
Returns
Boolean indiciating whether the message is out of sequence
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.getArrayString().
getSeqNum()
native long com.wombat.mama.MamaMsg.getSeqNum ()
Returns the Sequence Number from the underlying message.
Returns
The field value as a long
Referenced by com.wombat.mama.MamaMsg.getArrayString().
addBool()
void com.wombat.mama.MamaMsg.addBool (String name, int fid, boolean value)
Add a Boolean value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
References com.wombat.mama.MamaMsg.addArrayF32(), com.wombat.mama.MamaMsg.addArrayF64(), com.wombat.mama.MamaMsg.addArrayI16(), com.wombat.mama.MamaMsg.addArrayI32(), com.wombat.mama.MamaMsg.addArrayI64(), com.wombat.mama.MamaMsg.addArrayI8(), com.wombat.mama.MamaMsg.addArrayMsg(), com.wombat.mama.MamaMsg.addArrayMsgWithLength(), com.wombat.mama.MamaMsg.addArrayString(), com.wombat.mama.MamaMsg.addArrayU16(), com.wombat.mama.MamaMsg.addArrayU32(), com.wombat.mama.MamaMsg.addArrayU64(), com.wombat.mama.MamaMsg.addArrayU8(), com.wombat.mama.MamaMsg.addBoolean(), com.wombat.mama.MamaMsg.addChar(), com.wombat.mama.MamaMsg.addDateTime(), com.wombat.mama.MamaMsg.addF32(), com.wombat.mama.MamaMsg.addF64(), com.wombat.mama.MamaMsg.addI16(), com.wombat.mama.MamaMsg.addI32(), com.wombat.mama.MamaMsg.addI64(), com.wombat.mama.MamaMsg.addI8(), com.wombat.mama.MamaMsg.addMsg(), com.wombat.mama.MamaMsg.addOpaque(), com.wombat.mama.MamaMsg.addPrice(), com.wombat.mama.MamaMsg.addString(), com.wombat.mama.MamaMsg.addU16(), com.wombat.mama.MamaMsg.addU32(), com.wombat.mama.MamaMsg.addU64(), and com.wombat.mama.MamaMsg.addU8().
addBoolean()
native void com.wombat.mama.MamaMsg.addBoolean (String name, int fid, boolean value)
Add a Boolean value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addChar()
native void com.wombat.mama.MamaMsg.addChar (String name, int fid, char value)
Add a Char value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addI8()
native void com.wombat.mama.MamaMsg.addI8 (String name, int fid, byte value)
Add an I8 (byte) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addU8()
native void com.wombat.mama.MamaMsg.addU8 (String name, int fid, short value)
Add an U8 (byte) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addI16()
native void com.wombat.mama.MamaMsg.addI16 (String name, int fid, short value)
Add an I16 (short) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addU16()
native void com.wombat.mama.MamaMsg.addU16 (String name, int fid, int value)
Add an U16 (short) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addI32()
native void com.wombat.mama.MamaMsg.addI32 (String name, int fid, int value)
Add an I32 (int) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addU32()
native void com.wombat.mama.MamaMsg.addU32 (String name, int fid, long value)
Add an U32 (int) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addI64()
native void com.wombat.mama.MamaMsg.addI64 (String name, int fid, long value)
Add an I64 (long) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addU64()
native void com.wombat.mama.MamaMsg.addU64 (String name, int fid, long value)
Add an U64 (long) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addF32()
native void com.wombat.mama.MamaMsg.addF32 (String name, int fid, float value)
Add an F32 (float) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addF64()
native void com.wombat.mama.MamaMsg.addF64 (String name, int fid, double value)
Add an F64 (double) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addString()
native void com.wombat.mama.MamaMsg.addString (String name, int fid, String value)
Add an String (Java String) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addDateTime()
native void com.wombat.mama.MamaMsg.addDateTime (String name, int fid, MamaDateTime value)
Add an MamaDateTime value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addPrice()
native void com.wombat.mama.MamaMsg.addPrice (String name, int fid, MamaPrice value)
Add an MamaPrice value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addMsg()
native void com.wombat.mama.MamaMsg.addMsg (String name, int fid, MamaMsg value)
Add an MamaMsg value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addOpaque()
native void com.wombat.mama.MamaMsg.addOpaque (String name, int fid, byte [] value)
Add an Opaque (byte[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayI8()
native void com.wombat.mama.MamaMsg.addArrayI8 (String name, int fid, byte [] value)
Add an I8 Array (byte[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayU8()
native void com.wombat.mama.MamaMsg.addArrayU8 (String name, int fid, short [] value)
Add a U8 Array (short[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayI16()
native void com.wombat.mama.MamaMsg.addArrayI16 (String name, int fid, short [] value)
Add an I16 Array (short[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayU16()
native void com.wombat.mama.MamaMsg.addArrayU16 (String name, int fid, int [] value)
Add a U16 Array (int[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayI32()
native void com.wombat.mama.MamaMsg.addArrayI32 (String name, int fid, int [] value)
Add an I32 Array (int[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayU32()
native void com.wombat.mama.MamaMsg.addArrayU32 (String name, int fid, long [] value)
Add a U32 Array (long[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayI64()
native void com.wombat.mama.MamaMsg.addArrayI64 (String name, int fid, long [] value)
Add an I64 Array (long[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayU64()
native void com.wombat.mama.MamaMsg.addArrayU64 (String name, int fid, long [] value)
Add a U64 Array (long[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayF32()
native void com.wombat.mama.MamaMsg.addArrayF32 (String name, int fid, float [] value)
Add a F32 Array (float[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayF64()
native void com.wombat.mama.MamaMsg.addArrayF64 (String name, int fid, double [] value)
Add a F64 Array (double[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayMsg()
native void com.wombat.mama.MamaMsg.addArrayMsg (String name, int fid, MamaMsg [] value)
Add a MamaMsg Array (MamaMsg[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The value to be added to the message
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayMsgWithLength()
native void com.wombat.mama.MamaMsg.addArrayMsgWithLength (String name, int fid, MamaMsg [] value, int length)
This function will add a new field containing an array of messages.
Unlinke addArrayMsg it will not add the entire array but only the number of messages supplied in the length parameter.
Parameters
name The field name.
fid The field id.
value The array of messages.
length The number of messages to add from the array, if this parameter is outside the array bounds then an exception will be thrown.
Exceptions
com.wombat.mama.MamaException
Referenced by com.wombat.mama.MamaMsg.addBool().
addArrayString() [1/2]
native void com.wombat.mama.MamaMsg.addArrayString (String name, int fid, String [] value, int length)
Add a String Array (String[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The array of strings
length The number of strings to add from the string array, if this parameter is outside the array bounds then an exception will be thrown.
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString(), and com.wombat.mama.MamaMsg.addBool().
addArrayString() [2/2]
void com.wombat.mama.MamaMsg.addArrayString (String name, int fid, String [] value)
Add a String Array (String[]) value to the underlying message.
Parameters
name The name of the field to be added to the message
fid The FID of the field to be added to the message
value The array of strings
Exceptions
MamaException will be thrown if the message pointer does not exist
References com.wombat.mama.MamaMsg.addArrayString(), com.wombat.mama.MamaMsg.updateArrayF32(), com.wombat.mama.MamaMsg.updateArrayF64(), com.wombat.mama.MamaMsg.updateArrayI16(), com.wombat.mama.MamaMsg.updateArrayI32(), com.wombat.mama.MamaMsg.updateArrayI64(), com.wombat.mama.MamaMsg.updateArrayI8(), com.wombat.mama.MamaMsg.updateArrayU16(), com.wombat.mama.MamaMsg.updateArrayU32(), com.wombat.mama.MamaMsg.updateArrayU64(), com.wombat.mama.MamaMsg.updateArrayU8(), com.wombat.mama.MamaMsg.updateBoolean(), com.wombat.mama.MamaMsg.updateChar(), com.wombat.mama.MamaMsg.updateDateTime(), com.wombat.mama.MamaMsg.updateF32(), com.wombat.mama.MamaMsg.updateF64(), com.wombat.mama.MamaMsg.updateI16(), com.wombat.mama.MamaMsg.updateI32(), com.wombat.mama.MamaMsg.updateI64(), com.wombat.mama.MamaMsg.updateI8(), com.wombat.mama.MamaMsg.updatePrice(), com.wombat.mama.MamaMsg.updateString(), com.wombat.mama.MamaMsg.updateU16(), com.wombat.mama.MamaMsg.updateU32(), com.wombat.mama.MamaMsg.updateU64(), and com.wombat.mama.MamaMsg.updateU8().
updateI8()
native void com.wombat.mama.MamaMsg.updateI8 (String name, int fid, byte value)
Update the value of an I8 (byte) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateU8()
native void com.wombat.mama.MamaMsg.updateU8 (String name, int fid, short value)
Update the value of a U8 (byte) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateI16()
native void com.wombat.mama.MamaMsg.updateI16 (String name, int fid, short value)
Update the value of an I16 (short) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateU16()
native void com.wombat.mama.MamaMsg.updateU16 (String name, int fid, int value)
Update the value of a U16 (short) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateI32()
native void com.wombat.mama.MamaMsg.updateI32 (String name, int fid, int value)
Update the value of an I32 (int) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateU32()
native void com.wombat.mama.MamaMsg.updateU32 (String name, int fid, long value)
Update the value of a U32 (int) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateI64()
native void com.wombat.mama.MamaMsg.updateI64 (String name, int fid, long value)
Update the value of an I64 (long) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateU64()
native void com.wombat.mama.MamaMsg.updateU64 (String name, int fid, long value)
Update the value of a U64 (long) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateF32()
native void com.wombat.mama.MamaMsg.updateF32 (String name, int fid, float value)
Update the value of an F32 (float) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateF64()
native void com.wombat.mama.MamaMsg.updateF64 (String name, int fid, double value)
Update the value of an F64 (double) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateString()
native void com.wombat.mama.MamaMsg.updateString (String name, int fid, String value)
Update the value of an String (Java String) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updatePrice()
native void com.wombat.mama.MamaMsg.updatePrice (String name, int fid, MamaPrice value)
Update the value of a MamaPrice value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateBoolean()
native void com.wombat.mama.MamaMsg.updateBoolean (String name, int fid, boolean value)
Update the value of a Boolean value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateChar()
native void com.wombat.mama.MamaMsg.updateChar (String name, int fid, char value)
Update the value of an Char value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateDateTime()
native void com.wombat.mama.MamaMsg.updateDateTime (String name, int fid, MamaDateTime value)
Update the value of an MamaDateTime value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayI8()
native void com.wombat.mama.MamaMsg.updateArrayI8 (String name, int fid, byte [] value)
Update the value of an I8 (byte[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayU8()
native void com.wombat.mama.MamaMsg.updateArrayU8 (String name, int fid, short [] value)
Update the value of a U8 (short[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayI16()
native void com.wombat.mama.MamaMsg.updateArrayI16 (String name, int fid, short [] value)
Update the value of an I16 (short[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayU16()
native void com.wombat.mama.MamaMsg.updateArrayU16 (String name, int fid, int [] value)
Update the value of a U16 (int[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayI32()
native void com.wombat.mama.MamaMsg.updateArrayI32 (String name, int fid, int [] value)
Update the value of an I32 (int[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayU32()
native void com.wombat.mama.MamaMsg.updateArrayU32 (String name, int fid, long [] value)
Update the value of a U32 (long[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayI64()
native void com.wombat.mama.MamaMsg.updateArrayI64 (String name, int fid, long [] value)
Update the value of an I64 (long[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayU64()
native void com.wombat.mama.MamaMsg.updateArrayU64 (String name, int fid, long [] value)
Update the value of a U64 (long[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayF32()
native void com.wombat.mama.MamaMsg.updateArrayF32 (String name, int fid, float [] value)
Update the value of an F32 (float[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
updateArrayF64()
native void com.wombat.mama.MamaMsg.updateArrayF64 (String name, int fid, double [] value)
Update the value of an F64 (double[]) value in the underlying message.
Parameters
name The name of the field to be updated within the message
fid The FID of the field to be updated within the message
value The new value
Exceptions
MamaException will be thrown if the message pointer does not exist
Referenced by com.wombat.mama.MamaMsg.addArrayString().
getChar() [3/4]
char com.wombat.mama.MamaMsg.getChar (String name, int fid, char defaultValue)
Return the value of a Char field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a char
References com.wombat.mama.MamaMsgField.getChar(), and com.wombat.mama.MamaMsg.getField().
getChar() [4/4]
char com.wombat.mama.MamaMsg.getChar (MamaFieldDescriptor fieldDesc, char defaultValue)
Return the value of a Char field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a char
References com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getI8() [3/4]
byte com.wombat.mama.MamaMsg.getI8 (String name, int fid, byte defaultValue)
Return the value of an I8 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a byte
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getI8().
getI8() [4/4]
byte com.wombat.mama.MamaMsg.getI8 (MamaFieldDescriptor fieldDesc, byte defaultValue)
Return the value of an I8 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a byte
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI8(), and com.wombat.mama.MamaFieldDescriptor.getName().
getU8() [3/4]
short com.wombat.mama.MamaMsg.getU8 (String name, int fid, short defaultValue)
Return the value of a U8 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a short
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getU8().
getU8() [4/4]
short com.wombat.mama.MamaMsg.getU8 (MamaFieldDescriptor fieldDesc, short defaultValue)
Return the value of a U8 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a short
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU8().
getI16() [3/4]
short com.wombat.mama.MamaMsg.getI16 (String name, int fid, short defaultValue)
Return the value of an I16 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a short
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getI16().
getI16() [4/4]
short com.wombat.mama.MamaMsg.getI16 (MamaFieldDescriptor fieldDesc, short defaultValue)
Return the value of an I16 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a short
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI16(), and com.wombat.mama.MamaFieldDescriptor.getName().
getU16() [3/4]
int com.wombat.mama.MamaMsg.getU16 (String name, int fid, int defaultValue)
Return the value of a U16 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a int
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getU16().
getU16() [4/4]
int com.wombat.mama.MamaMsg.getU16 (MamaFieldDescriptor fieldDesc, int defaultValue)
Return the value of a U16 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a int
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU16().
getI32() [3/4]
int com.wombat.mama.MamaMsg.getI32 (String name, int fid, int defaultValue)
Return the value of an I32 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a int
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getI32().
getI32() [4/4]
int com.wombat.mama.MamaMsg.getI32 (MamaFieldDescriptor fieldDesc, int defaultValue)
Return the value of an I32 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a int
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI32(), and com.wombat.mama.MamaFieldDescriptor.getName().
getU32() [3/4]
long com.wombat.mama.MamaMsg.getU32 (String name, int fid, long defaultValue)
Return the value of a U32 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a long
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getU32().
getU32() [4/4]
long com.wombat.mama.MamaMsg.getU32 (MamaFieldDescriptor fieldDesc, long defaultValue)
Return the value of a U32 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a long
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU32().
getI64() [3/4]
long com.wombat.mama.MamaMsg.getI64 (String name, int fid, long defaultValue)
Return the value of an I64 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a long
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getI64().
getI64() [4/4]
long com.wombat.mama.MamaMsg.getI64 (MamaFieldDescriptor fieldDesc, long defaultValue)
Return the value of an I64 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a long
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getI64(), and com.wombat.mama.MamaFieldDescriptor.getName().
getU64() [3/4]
long com.wombat.mama.MamaMsg.getU64 (String name, int fid, long defaultValue)
Return the value of a U64 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a long
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getU64().
getU64() [4/4]
long com.wombat.mama.MamaMsg.getU64 (MamaFieldDescriptor fieldDesc, long defaultValue)
Return the value of a U64 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a long
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getU64().
getF32() [3/4]
float com.wombat.mama.MamaMsg.getF32 (String name, int fid, float defaultValue)
Return the value of an F32 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a float
References com.wombat.mama.MamaMsgField.getF32(), and com.wombat.mama.MamaMsg.getField().
getF32() [4/4]
float com.wombat.mama.MamaMsg.getF32 (MamaFieldDescriptor fieldDesc, float defaultValue)
Return the value of an F32 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a float
References com.wombat.mama.MamaMsg.getF32(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getF64() [3/4]
double com.wombat.mama.MamaMsg.getF64 (String name, int fid, double defaultValue)
Return the value of an F64 field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a double
References com.wombat.mama.MamaMsgField.getF64(), and com.wombat.mama.MamaMsg.getField().
getF64() [4/4]
double com.wombat.mama.MamaMsg.getF64 (MamaFieldDescriptor fieldDesc, double defaultValue)
Return the value of an F64 field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a double
References com.wombat.mama.MamaMsg.getF64(), com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
getString() [3/4]
String com.wombat.mama.MamaMsg.getString (String name, int fid, String defaultValue)
Return the value of a String field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a String
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getString().
getString() [4/4]
String com.wombat.mama.MamaMsg.getString (MamaFieldDescriptor fieldDesc, String defaultValue)
Return the value of a String field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a String
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getString().
getPrice() [3/4]
MamaPrice com.wombat.mama.MamaMsg.getPrice (String name, int fid, MamaPrice defaultValue)
Return the value of a MamaPrice field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a MamaPrice
References com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaMsgField.getPrice().
getPrice() [4/4]
MamaPrice com.wombat.mama.MamaMsg.getPrice (MamaFieldDescriptor fieldDesc, MamaPrice defaultValue)
Return the value of a MamaPrice field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a MamaPrice
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.getPrice().
getMsg() [3/3]
MamaMsg com.wombat.mama.MamaMsg.getMsg (MamaFieldDescriptor fieldDesc, MamaMsg defaultValue)
Return the value of a MamaMsg field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a MamaMsg
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getField(), com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayI32() [3/3]
int [] com.wombat.mama.MamaMsg.getArrayI32 (MamaFieldDescriptor fieldDesc, int [] defaultValue)
Return the value of an I32 Array field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a int[]
References com.wombat.mama.MamaMsgField.getArrayI32(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaFieldDescriptor.getName().
getArrayMsg() [3/3]
MamaMsg [] com.wombat.mama.MamaMsg.getArrayMsg (MamaFieldDescriptor fieldDesc, MamaMsg [] defaultValue)
Return the value of a MamaMsg Array field from the underlying message.
Parameters
fieldDesc The MamaFieldDescriptor for the field within the message
defaultValue The default value to use of no value is present
Returns
The value as a MamaMsg[]
References com.wombat.mama.MamaMsgField.getArrayMsg(), com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaMsg.getField(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryBoolean().
tryBoolean() [1/2]
native boolean com.wombat.mama.MamaMsg.tryBoolean (String name, int fid, MamaBoolean result)
Try to get the value of a Boolean field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.getArrayMsg(), and com.wombat.mama.MamaMsg.tryBoolean().
tryBoolean() [2/2]
boolean com.wombat.mama.MamaMsg.tryBoolean (MamaFieldDescriptor field, MamaBoolean result)
Return the value of a MamaBoolean field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryBoolean(), and com.wombat.mama.MamaMsg.tryChar().
tryChar() [1/2]
native boolean com.wombat.mama.MamaMsg.tryChar (String name, int fid, MamaChar result)
Try to get the value of a MamaChar field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryBoolean(), and com.wombat.mama.MamaMsg.tryChar().
tryChar() [2/2]
boolean com.wombat.mama.MamaMsg.tryChar (MamaFieldDescriptor field, MamaChar result)
Return the value of a MamaChar field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryChar(), and com.wombat.mama.MamaMsg.tryI8().
tryI8() [1/2]
native boolean com.wombat.mama.MamaMsg.tryI8 (String name, int fid, MamaByte result)
Try to get the value of a MamaByte field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryChar(), and com.wombat.mama.MamaMsg.tryI8().
tryI8() [2/2]
boolean com.wombat.mama.MamaMsg.tryI8 (MamaFieldDescriptor field, MamaByte result)
Return the value of a MamaByte field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI8(), and com.wombat.mama.MamaMsg.tryU8().
tryU8() [1/2]
native boolean com.wombat.mama.MamaMsg.tryU8 (String name, int fid, MamaShort result)
Try to get the value of a MamaShort field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI8(), and com.wombat.mama.MamaMsg.tryU8().
tryU8() [2/2]
boolean com.wombat.mama.MamaMsg.tryU8 (MamaFieldDescriptor field, MamaShort result)
Return the value of a MamaShort field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI16(), and com.wombat.mama.MamaMsg.tryU8().
tryI16() [1/2]
native boolean com.wombat.mama.MamaMsg.tryI16 (String name, int fid, MamaShort result)
Try to get the value of a MamaShort field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI16(), and com.wombat.mama.MamaMsg.tryU8().
tryI16() [2/2]
boolean com.wombat.mama.MamaMsg.tryI16 (MamaFieldDescriptor field, MamaShort result)
Return the value of a MamaShort field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI16(), and com.wombat.mama.MamaMsg.tryU16().
tryU16() [1/2]
native boolean com.wombat.mama.MamaMsg.tryU16 (String name, int fid, MamaInteger result)
Try to get the value of a MamaInteger field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI16(), and com.wombat.mama.MamaMsg.tryU16().
tryU16() [2/2]
boolean com.wombat.mama.MamaMsg.tryU16 (MamaFieldDescriptor field, MamaInteger result)
Return the value of a MamaInteger field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI32(), and com.wombat.mama.MamaMsg.tryU16().
tryI32() [1/2]
native boolean com.wombat.mama.MamaMsg.tryI32 (String name, int fid, MamaInteger result)
Try to get the value of a MamaInteger field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI32(), and com.wombat.mama.MamaMsg.tryU16().
tryI32() [2/2]
boolean com.wombat.mama.MamaMsg.tryI32 (MamaFieldDescriptor field, MamaInteger result)
Return the value of a MamaInteger field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI32(), and com.wombat.mama.MamaMsg.tryU32().
tryU32() [1/2]
native boolean com.wombat.mama.MamaMsg.tryU32 (String name, int fid, MamaLong result)
Try to get the value of a MamaLong field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI32(), and com.wombat.mama.MamaMsg.tryU32().
tryU32() [2/2]
boolean com.wombat.mama.MamaMsg.tryU32 (MamaFieldDescriptor field, MamaLong result)
Return the value of a MamaLong field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI64(), and com.wombat.mama.MamaMsg.tryU32().
tryI64() [1/2]
native boolean com.wombat.mama.MamaMsg.tryI64 (String name, int fid, MamaLong result)
Try to get the value of a MamaLong field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI64(), and com.wombat.mama.MamaMsg.tryU32().
tryI64() [2/2]
boolean com.wombat.mama.MamaMsg.tryI64 (MamaFieldDescriptor field, MamaLong result)
Return the value of a MamaLong field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryI64(), and com.wombat.mama.MamaMsg.tryU64().
tryU64() [1/2]
native boolean com.wombat.mama.MamaMsg.tryU64 (String name, int fid, MamaLong result)
Try to get the value of a MamaLong field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryI64(), and com.wombat.mama.MamaMsg.tryU64().
tryU64() [2/2]
boolean com.wombat.mama.MamaMsg.tryU64 (MamaFieldDescriptor field, MamaLong result)
Return the value of a MamaLong field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryF32(), and com.wombat.mama.MamaMsg.tryU64().
tryF32() [1/2]
native boolean com.wombat.mama.MamaMsg.tryF32 (String name, int fid, MamaFloat result)
Try to get the value of a MamaFloat field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryF32(), and com.wombat.mama.MamaMsg.tryU64().
tryF32() [2/2]
boolean com.wombat.mama.MamaMsg.tryF32 (MamaFieldDescriptor field, MamaFloat result)
Return the value of a MamaFloat field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), com.wombat.mama.MamaMsg.tryF32(), and com.wombat.mama.MamaMsg.tryF64().
tryF64() [1/2]
native boolean com.wombat.mama.MamaMsg.tryF64 (String name, int fid, MamaDouble result)
Try to get the value of a MamaDouble field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryF32(), and com.wombat.mama.MamaMsg.tryF64().
tryF64() [2/2]
boolean com.wombat.mama.MamaMsg.tryF64 (MamaFieldDescriptor field, MamaDouble result)
Return the value of a MamaDouble field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryF64().
tryDateTime() [1/2]
boolean com.wombat.mama.MamaMsg.tryDateTime (MamaFieldDescriptor field, MamaDateTime result)
Return the value of a MamaDateTime field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
tryDateTime() [2/2]
native boolean com.wombat.mama.MamaMsg.tryDateTime (String name, int fid, MamaDateTime result)
Try to get the value of a MamaDateTime field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
tryPrice() [1/2]
boolean com.wombat.mama.MamaMsg.tryPrice (MamaFieldDescriptor field, MamaPrice result)
Return the value of a MamaPrice field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryString().
tryPrice() [2/2]
native boolean com.wombat.mama.MamaMsg.tryPrice (String name, int fid, MamaPrice result)
Try to get the value of a MamaPrice field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
tryString() [1/2]
native boolean com.wombat.mama.MamaMsg.tryString (String name, int fid, MamaString result)
Try to get the value of a MamaString field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
Referenced by com.wombat.mama.MamaMsg.tryPrice(), and com.wombat.mama.MamaMsg.tryString().
tryString() [2/2]
boolean com.wombat.mama.MamaMsg.tryString (MamaFieldDescriptor field, MamaString result)
Return the value of a MamaString field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryString().
tryOpaque() [1/2]
boolean com.wombat.mama.MamaMsg.tryOpaque (String name, int fid, MamaOpaque result)
Try to get the value of a MamaOpaque field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaMsg.getField(), com.wombat.mama.MamaMsgField.getOpaque(), and com.wombat.mama.MamaOpaque.setValue().
Referenced by com.wombat.mama.MamaMsg.tryOpaque().
tryOpaque() [2/2]
boolean com.wombat.mama.MamaMsg.tryOpaque (MamaFieldDescriptor field, MamaOpaque result)
Return the value of a MamaOpaque field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryOpaque().
tryMsg() [1/2]
boolean com.wombat.mama.MamaMsg.tryMsg (String name, int fid, MamaMessage result)
Try to get the value of a MamaMessage field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaMsg.getField(), com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMessage.setValue().
Referenced by com.wombat.mama.MamaMsg.tryMsg().
tryMsg() [2/2]
boolean com.wombat.mama.MamaMsg.tryMsg (MamaFieldDescriptor field, MamaMessage result)
Return the value of a MamaMessage field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryMsg().
tryArrayI32() [1/2]
boolean com.wombat.mama.MamaMsg.tryArrayI32 (String name, int fid, MamaArrayInt result)
Try to get the value of a MamaArrayInt field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaMsgField.getArrayI32(), com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaArrayInt.setValue().
Referenced by com.wombat.mama.MamaMsg.tryArrayI32().
tryArrayI32() [2/2]
boolean com.wombat.mama.MamaMsg.tryArrayI32 (MamaFieldDescriptor field, MamaArrayInt result)
Return the value of a MamaArrayInt field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryArrayI32().
tryArrayU16() [1/2]
boolean com.wombat.mama.MamaMsg.tryArrayU16 (String name, int fid, MamaArrayInt result)
Try to get the value of a MamaArrayInt field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaMsgField.getArrayU16(), com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaArrayInt.setValue().
Referenced by com.wombat.mama.MamaMsg.tryArrayU16().
tryArrayU16() [2/2]
boolean com.wombat.mama.MamaMsg.tryArrayU16 (MamaFieldDescriptor field, MamaArrayInt result)
Return the value of a MamaArrayInt field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryArrayU16().
tryArrayMsg() [1/2]
boolean com.wombat.mama.MamaMsg.tryArrayMsg (String name, int fid, MamaArrayMsg result)
Try to get the value of a MamaArrayMsg field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaMsgField.getArrayMsg(), com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaArrayMsg.setValue().
Referenced by com.wombat.mama.MamaMsg.tryArrayMsg().
tryArrayMsg() [2/2]
boolean com.wombat.mama.MamaMsg.tryArrayMsg (MamaFieldDescriptor field, MamaArrayMsg result)
Return the value of a MamaArrayMsg field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryArrayMsg().
tryArrayString() [1/2]
boolean com.wombat.mama.MamaMsg.tryArrayString (String name, int fid, MamaArrayString result)
Try to get the value of a MamaArrayString field from the underlying message.
Parameters
name The name of the field within the message
fid The FID of the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaMsgField.getArrayString(), com.wombat.mama.MamaMsg.getField(), and com.wombat.mama.MamaArrayString.setValue().
Referenced by com.wombat.mama.MamaMsg.tryArrayString().
tryArrayString() [2/2]
boolean com.wombat.mama.MamaMsg.tryArrayString (MamaFieldDescriptor field, MamaArrayString result)
Return the value of a MamaArrayMsg field from the underlying message.
Parameters
field The MamaFieldDescriptor for the field within the message
result The result (not modified if field not present)
Returns
Boolean representing whether the field was present or not
References com.wombat.mama.MamaFieldDescriptor.getFid(), com.wombat.mama.MamaFieldDescriptor.getName(), and com.wombat.mama.MamaMsg.tryArrayString().
iterateFields()
void com.wombat.mama.MamaMsg.iterateFields (MamaMsgFieldIterator iterator, MamaDictionary dictionary, Object closure)
Iterate over all of the fields within the message.
The onField() method of the MamaMsgFieldIterator instance will be invoked for each field in the underlying message.
Parameters
iterator Callback object implementing the MamaMsgFieldIterator interface
dictionary Optional MamaDictionary object
closure Optional user supplied arbitrary closure data which will be passed back in onField()
References com.wombat.mama.MamaMsg.getFieldAsString(), com.wombat.mama.MamaMsg.getPayloadType(), com.wombat.mama.MamaMsg.isFromInbox(), com.wombat.mama.MamaMsg.iterator(), and com.wombat.mama.MamaMsg.toString().
getFieldAsString()
native String com.wombat.mama.MamaMsg.getFieldAsString (int fid, MamaDictionary dictionary)
Return a String representation of the entire message.
Parameters
fid The FID of the field
dictionary Optional MamaDictionary object
Returns
Return a String representation the field with the given fid
Referenced by com.wombat.mama.MamaMsg.iterateFields().
isFromInbox()
native boolean com.wombat.mama.MamaMsg.isFromInbox ()
Return a String representation of the entire message.
Returns
Boolean indicating whether this message is a p2p request
Referenced by com.wombat.mama.MamaMsg.iterateFields().
toString()
native String com.wombat.mama.MamaMsg.toString ()
Return a String representation of the entire message.
Returns
the String representation of the entire message.
Referenced by com.wombat.mama.MamaMsg.iterateFields(), and com.wombat.mama.MamaMessage.toString().
getPayloadType()
native char com.wombat.mama.MamaMsg.getPayloadType ()
Return as a character representation of the payload type used in the message.
Returns
A MamaPayloadType indicating which message payload is used in the message.
Referenced by com.wombat.mama.MamaMsg.iterateFields().
destroy()
void com.wombat.mama.MamaMsg.destroy ()
Destroy the internal state of the MamaMsg object.
Needed for JNI so we know when to free the underlying C strucure. Should only be called if the client app has created the message. i.e. do not call on messages passed in the callbacks as these are managed internal to the MAMA API
References com.wombat.mama.MamaMsg.apply(), com.wombat.mama.MamaMsg.clear(), com.wombat.mama.MamaMsg.copy(), and com.wombat.mama.MamaMsg.detach().
Referenced by com.wombat.mama.MamaMsg.finalize().
clear()
native void com.wombat.mama.MamaMsg.clear ()
Clear the message.
All fields are removed
Referenced by com.wombat.mama.MamaMsg.destroy().
copy()
native void com.wombat.mama.MamaMsg.copy (MamaMsg rhs)
Create a deep copy of the message.
Parameters
rhs The MamaMsg to be copied
Referenced by com.wombat.mama.MamaMsg.destroy().
detach()
native MamaMsg com.wombat.mama.MamaMsg.detach ()
Detach the message.
This will take a deep copy of the MamaMsg and transfer the ownership to the application and it will be the responsibility of the user to destroy.
Referenced by com.wombat.mama.MamaMsg.destroy().
apply()
native void com.wombat.mama.MamaMsg.apply (MamaMsg rhs)
Update the MamaMsg with the fields of another MamaMsg.
Parameters
rhs The MamaMsg to be used to update the current message
Referenced by com.wombat.mama.MamaMsg.destroy().
getField() [1/2]
MamaMsgField com.wombat.mama.MamaMsg.getField (MamaFieldDescriptor field, MamaDictionary dict)
Get a specified field from a message, or null if not found.
Parameters
field The MamaFieldDescriptor for the field within the message
dict Optional MamaDictionary object
Returns
The MamaMsgField or null
References com.wombat.mama.MamaFieldDescriptor.getFid(), and com.wombat.mama.MamaFieldDescriptor.getName().
Referenced by com.wombat.mama.MamaMsg.getArrayI32(), com.wombat.mama.MamaMsg.getArrayMsg(), com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaMsg.getF32(), com.wombat.mama.MamaMsg.getF64(), com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaMsg.getI64(), com.wombat.mama.MamaMsg.getI8(), com.wombat.mama.MamaMsg.getMsg(), com.wombat.mama.MamaMsg.getPrice(), com.wombat.mama.MamaMsg.getString(), com.wombat.mama.MamaMsg.getU16(), com.wombat.mama.MamaMsg.getU32(), com.wombat.mama.MamaMsg.getU64(), com.wombat.mama.MamaMsg.getU8(), com.wombat.mama.MamaMsg.tryArrayI32(), com.wombat.mama.MamaMsg.tryArrayMsg(), com.wombat.mama.MamaMsg.tryArrayString(), com.wombat.mama.MamaMsg.tryArrayU16(), com.wombat.mama.MamaMsg.tryMsg(), and com.wombat.mama.MamaMsg.tryOpaque().
getField() [2/2]
MamaMsgField com.wombat.mama.MamaMsg.getField (String fieldName, int fid, MamaDictionary dict)
Get a specified field from a message, or null if not found.
Parameters
fieldName The name of the field within the message
fid The FID of the field within the message
dict Optional MamaDictionary object
Returns
The MamaMsgField or null
References com.wombat.mama.MamaMsgField.getPointerVal(), and com.wombat.mama.MamaMsgField.setPointerVal().
finalize()
void com.wombat.mama.MamaMsg.finalize () protected
References com.wombat.mama.MamaMsg.destroy().