OpenMAMA Java API: com.wombat.mama.MamaFieldDescriptor Class Reference
com.wombat.mama.MamaFieldDescriptor Class Reference
The MamaFieldDescriptor class represents a field in a MamaMsg
Public Member Functions
MamaFieldDescriptor (int fid, short type, String name, Object data)
Create a MamaFieldDescriptor
int getFid ()
Return the field identifier.
short getType ()
Return the data type.
String getName ()
Return the human readable name of the field.
String toString ()
Returns a string suitable for output to a terminal containing the type, id, and name.
void setClosure (Object closure)
Set user specified data to associate with the field descriptor.
Object getClosure ()
Return the user specified data associated with the field descriptor.
void setTrackModState (boolean on)
boolean getTrackModState ()
Static Public Member Functions
static String getTypeName (short type)
Static Public Attributes
static final short MSG = 1
static final short DATETIME = 3
static final short OPAQUE = 7
static final short STRING = 8
static final short BOOL = 9
static final short CHAR = 10
static final short I8 = 14
static final short U8 = 15
static final short I16 = 16
static final short U16 = 17
static final short I32 = 18
static final short U32 = 19
static final short I64 = 20
static final short U64 = 21
static final short F32 = 24
static final short F64 = 25
static final short TIME = 26
static final short PRICE = 27
static final short I8ARRAY = 34
static final short U8ARRAY = 35
static final short I16ARRAY = 36
static final short U16ARRAY = 37
static final short I32ARRAY = 38
static final short U32ARRAY = 39
static final short I64ARRAY = 40
static final short U64ARRAY = 41
static final short F32ARRAY = 44
static final short F64ARRAY = 45
static final short VECTOR_STRING = 46
static final short VECTOR_MSG = 47
static final short VECTOR_TIME = 48
static final short VECTOR_PRICE = 49
static final short QUANTITY = 50
static final short VECTOR = 98
static final short COLLECTION = 99
static final short UNKNOWN = 100
Detailed Description
The MamaFieldDescriptor class represents a field in a MamaMsg
See also
MamaDictionary
MamaMsg
Constructor & Destructor Documentation
MamaFieldDescriptor()
com.wombat.mama.MamaFieldDescriptor.MamaFieldDescriptor (int fid, short type, String name, Object data)
Create a MamaFieldDescriptor
Parameters
fid The field identifier.
type The type.
name The field name.
Member Function Documentation
getFid()
int com.wombat.mama.MamaFieldDescriptor.getFid ()
Return the field identifier.
Returns
The fid.
Referenced by com.wombat.mama.MamaMsg.getArrayF32(), com.wombat.mama.MamaMsg.getArrayF64(), com.wombat.mama.MamaMsg.getArrayI16(), com.wombat.mama.MamaMsg.getArrayI32(), com.wombat.mama.MamaMsg.getArrayI64(), com.wombat.mama.MamaMsg.getArrayI8(), com.wombat.mama.MamaMsg.getArrayMsg(), com.wombat.mama.MamaMsg.getArrayString(), com.wombat.mama.MamaMsg.getArrayU16(), com.wombat.mama.MamaMsg.getArrayU32(), com.wombat.mama.MamaMsg.getArrayU64(), com.wombat.mama.MamaMsg.getArrayU8(), com.wombat.mama.MamaMsg.getBoolean(), com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaMsg.getDateTime(), com.wombat.mama.MamaMsg.getF32(), com.wombat.mama.MamaMsg.getF64(), com.wombat.mama.MamaMsg.getField(), com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaMsg.getI64(), com.wombat.mama.MamaMsg.getI8(), com.wombat.mama.MamaMsg.getMsg(), com.wombat.mama.MamaMsg.getOpaque(), com.wombat.mama.MamaMsg.getPrice(), com.wombat.mama.MamaMsg.getString(), com.wombat.mama.MamaMsg.getStringAsBuffer(), com.wombat.mama.MamaMsg.getU16(), com.wombat.mama.MamaMsg.getU32(), com.wombat.mama.MamaMsg.getU64(), com.wombat.mama.MamaMsg.getU8(), com.wombat.mama.MamaMsg.tryArrayI32(), com.wombat.mama.MamaMsg.tryArrayMsg(), com.wombat.mama.MamaMsg.tryArrayString(), com.wombat.mama.MamaMsg.tryArrayU16(), com.wombat.mama.MamaMsg.tryBoolean(), com.wombat.mama.MamaMsg.tryChar(), com.wombat.mama.MamaMsg.tryDateTime(), com.wombat.mama.MamaMsg.tryF32(), com.wombat.mama.MamaMsg.tryF64(), com.wombat.mama.MamaMsg.tryI16(), com.wombat.mama.MamaMsg.tryI32(), com.wombat.mama.MamaMsg.tryI64(), com.wombat.mama.MamaMsg.tryI8(), com.wombat.mama.MamaMsg.tryMsg(), com.wombat.mama.MamaMsg.tryOpaque(), com.wombat.mama.MamaMsg.tryPrice(), com.wombat.mama.MamaMsg.tryString(), com.wombat.mama.MamaMsg.tryU16(), com.wombat.mama.MamaMsg.tryU32(), com.wombat.mama.MamaMsg.tryU64(), and com.wombat.mama.MamaMsg.tryU8().
getType()
short com.wombat.mama.MamaFieldDescriptor.getType ()
Return the data type.
Returns
The type.
getName()
String com.wombat.mama.MamaFieldDescriptor.getName ()
Return the human readable name of the field.
Returns
The name.
Referenced by com.wombat.mama.MamaMsg.getArrayF32(), com.wombat.mama.MamaMsg.getArrayF64(), com.wombat.mama.MamaMsg.getArrayI16(), com.wombat.mama.MamaMsg.getArrayI32(), com.wombat.mama.MamaMsg.getArrayI64(), com.wombat.mama.MamaMsg.getArrayI8(), com.wombat.mama.MamaMsg.getArrayMsg(), com.wombat.mama.MamaMsg.getArrayString(), com.wombat.mama.MamaMsg.getArrayU16(), com.wombat.mama.MamaMsg.getArrayU32(), com.wombat.mama.MamaMsg.getArrayU64(), com.wombat.mama.MamaMsg.getArrayU8(), com.wombat.mama.MamaMsg.getBoolean(), com.wombat.mama.MamaMsg.getChar(), com.wombat.mama.MamaMsg.getDateTime(), com.wombat.mama.MamaMsg.getF32(), com.wombat.mama.MamaMsg.getF64(), com.wombat.mama.MamaMsg.getField(), com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaMsg.getI64(), com.wombat.mama.MamaMsg.getI8(), com.wombat.mama.MamaMsg.getMsg(), com.wombat.mama.MamaMsg.getOpaque(), com.wombat.mama.MamaMsg.getPrice(), com.wombat.mama.MamaMsg.getString(), com.wombat.mama.MamaMsg.getStringAsBuffer(), com.wombat.mama.MamaMsg.getU16(), com.wombat.mama.MamaMsg.getU32(), com.wombat.mama.MamaMsg.getU64(), com.wombat.mama.MamaMsg.getU8(), com.wombat.mama.MamaMsg.tryArrayI32(), com.wombat.mama.MamaMsg.tryArrayMsg(), com.wombat.mama.MamaMsg.tryArrayString(), com.wombat.mama.MamaMsg.tryArrayU16(), com.wombat.mama.MamaMsg.tryBoolean(), com.wombat.mama.MamaMsg.tryChar(), com.wombat.mama.MamaMsg.tryDateTime(), com.wombat.mama.MamaMsg.tryF32(), com.wombat.mama.MamaMsg.tryF64(), com.wombat.mama.MamaMsg.tryI16(), com.wombat.mama.MamaMsg.tryI32(), com.wombat.mama.MamaMsg.tryI64(), com.wombat.mama.MamaMsg.tryI8(), com.wombat.mama.MamaMsg.tryMsg(), com.wombat.mama.MamaMsg.tryOpaque(), com.wombat.mama.MamaMsg.tryPrice(), com.wombat.mama.MamaMsg.tryString(), com.wombat.mama.MamaMsg.tryU16(), com.wombat.mama.MamaMsg.tryU32(), com.wombat.mama.MamaMsg.tryU64(), and com.wombat.mama.MamaMsg.tryU8().
toString()
String com.wombat.mama.MamaFieldDescriptor.toString ()
Returns a string suitable for output to a terminal containing the type, id, and name.
Returns
A human readable string for the field.
References com.wombat.mama.MamaFieldDescriptor.getTypeName().
setClosure()
void com.wombat.mama.MamaFieldDescriptor.setClosure (Object closure)
Set user specified data to associate with the field descriptor.
Parameters
closure The data to associate with the descriptor.
getClosure()
Object com.wombat.mama.MamaFieldDescriptor.getClosure ()
Return the user specified data associated with the field descriptor.
The closure data has a default value of null
Returns
The user specified data associated with the field descriptor.
getTypeName()
static String com.wombat.mama.MamaFieldDescriptor.getTypeName (short type) static
Referenced by com.wombat.mama.MamaFieldDescriptor.toString().
setTrackModState()
void com.wombat.mama.MamaFieldDescriptor.setTrackModState (boolean on)
getTrackModState()
boolean com.wombat.mama.MamaFieldDescriptor.getTrackModState ()
Member Data Documentation
MSG
final short com.wombat.mama.MamaFieldDescriptor.MSG = 1 static
DATETIME
final short com.wombat.mama.MamaFieldDescriptor.DATETIME = 3 static
OPAQUE
final short com.wombat.mama.MamaFieldDescriptor.OPAQUE = 7 static
STRING
final short com.wombat.mama.MamaFieldDescriptor.STRING = 8 static
BOOL
final short com.wombat.mama.MamaFieldDescriptor.BOOL = 9 static
CHAR
final short com.wombat.mama.MamaFieldDescriptor.CHAR = 10 static
I8
final short com.wombat.mama.MamaFieldDescriptor.I8 = 14 static
U8
final short com.wombat.mama.MamaFieldDescriptor.U8 = 15 static
I16
final short com.wombat.mama.MamaFieldDescriptor.I16 = 16 static
U16
final short com.wombat.mama.MamaFieldDescriptor.U16 = 17 static
I32
final short com.wombat.mama.MamaFieldDescriptor.I32 = 18 static
U32
final short com.wombat.mama.MamaFieldDescriptor.U32 = 19 static
I64
final short com.wombat.mama.MamaFieldDescriptor.I64 = 20 static
U64
final short com.wombat.mama.MamaFieldDescriptor.U64 = 21 static
F32
final short com.wombat.mama.MamaFieldDescriptor.F32 = 24 static
F64
final short com.wombat.mama.MamaFieldDescriptor.F64 = 25 static
TIME
final short com.wombat.mama.MamaFieldDescriptor.TIME = 26 static
PRICE
final short com.wombat.mama.MamaFieldDescriptor.PRICE = 27 static
I8ARRAY
final short com.wombat.mama.MamaFieldDescriptor.I8ARRAY = 34 static
U8ARRAY
final short com.wombat.mama.MamaFieldDescriptor.U8ARRAY = 35 static
I16ARRAY
final short com.wombat.mama.MamaFieldDescriptor.I16ARRAY = 36 static
U16ARRAY
final short com.wombat.mama.MamaFieldDescriptor.U16ARRAY = 37 static
I32ARRAY
final short com.wombat.mama.MamaFieldDescriptor.I32ARRAY = 38 static
U32ARRAY
final short com.wombat.mama.MamaFieldDescriptor.U32ARRAY = 39 static
I64ARRAY
final short com.wombat.mama.MamaFieldDescriptor.I64ARRAY = 40 static
U64ARRAY
final short com.wombat.mama.MamaFieldDescriptor.U64ARRAY = 41 static
F32ARRAY
final short com.wombat.mama.MamaFieldDescriptor.F32ARRAY = 44 static
F64ARRAY
final short com.wombat.mama.MamaFieldDescriptor.F64ARRAY = 45 static
VECTOR_STRING
final short com.wombat.mama.MamaFieldDescriptor.VECTOR_STRING = 46 static
VECTOR_MSG
final short com.wombat.mama.MamaFieldDescriptor.VECTOR_MSG = 47 static
VECTOR_TIME
final short com.wombat.mama.MamaFieldDescriptor.VECTOR_TIME = 48 static
VECTOR_PRICE
final short com.wombat.mama.MamaFieldDescriptor.VECTOR_PRICE = 49 static
QUANTITY
final short com.wombat.mama.MamaFieldDescriptor.QUANTITY = 50 static
VECTOR
final short com.wombat.mama.MamaFieldDescriptor.VECTOR = 98 static
COLLECTION
final short com.wombat.mama.MamaFieldDescriptor.COLLECTION = 99 static
UNKNOWN
final short com.wombat.mama.MamaFieldDescriptor.UNKNOWN = 100 static