OpenMAMA Java API: com.wombat.mama.MamaSource Class Reference
com.wombat.mama.MamaSource Class Reference
A MAMA source maintains information about a data source, including the quality of the data coming from that source.
Inherits com.wombat.mama.MamaSourceManager.
Inherited by com.wombat.mama.MamaSourceDerivative.
Public Member Functions
MamaSource ()
Creates a new mama source with default parameters.
MamaSource (final String sourceId, MamaTransport transport, final String symbolNamespace)
native void setId (final String sourceId)
native void setMappedId (final String mappedId)
native void setDisplayId (final String displayId)
native void setQuality (short quality)
void setState (MamaSourceState state)
void setParent (MamaSource parent)
native void setSymbolNamespace (final String symbolNamespace)
void setTransportName (final String transportName)
void setTransport (MamaTransport transport)
native final String getId ()
native final String getMappedId ()
native final String getDisplayId ()
native short getQuality ()
MamaSourceState getState ()
Get the state of a mama source object.
String getStateAsString ()
Get the stringified state name of a mama source object.
MamaSource getParent ()
Get the parent source of the mama source object.
native final String getSymbolNamespace ()
MamaTransport getTransport ()
void addSubscription (final String key, MamaSubscription subscription)
Add a subscriptions to the mamaSource.
MamaSubscription findSubscription (final String key)
find a MamaSubscription, null will be returned if not found
boolean isPartOf (MamaSource source)
void destroy ()
Public Member Functions inherited from com.wombat.mama.MamaSourceManager
MamaSourceManager ()
Constructor - creates a new MamaSourceManager object.
MamaSource findOrCreateSource (final String sourceName)
Locates an existing mamaSource for a given name, if none exists a new one is created and added to the source manager.
MamaSource findSource (final String sourceName)
locates an existing source for a given name, if none is found null is returned, The caller has to validate null value on return.
void addSource (MamaSource mamaSource)
Add an existing mama Source to the source manager.
void addSource (MamaSource mamaSource, final String sourceName)
Add an existing mama Source to the source manager.
int getSize ()
Return the size of the contents of source manager.
Iterator sourceIterator ()
void destroy ()
Detailed Description
A MAMA source maintains information about a data source, including the quality of the data coming from that source.
It inherits MamaSourceManager because a source can have sub-sources.
Constructor & Destructor Documentation
MamaSource() [1/2]
com.wombat.mama.MamaSource.MamaSource ()
Creates a new mama source with default parameters.
Referenced by com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative().
MamaSource() [2/2]
com.wombat.mama.MamaSource.MamaSource (final String sourceId, MamaTransport transport, final String symbolNamespace)
References com.wombat.mama.MamaSource.setDisplayId(), com.wombat.mama.MamaSource.setId(), com.wombat.mama.MamaSource.setMappedId(), com.wombat.mama.MamaSource.setQuality(), com.wombat.mama.MamaSource.setSymbolNamespace(), and com.wombat.mama.MamaSource.setTransport().
Member Function Documentation
setId()
native void com.wombat.mama.MamaSource.setId (final String sourceId)
Referenced by com.wombat.mama.MamaSource.MamaSource(), com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative(), and com.wombat.mama.MamaSourceManager.MamaSourceManager().
setMappedId()
native void com.wombat.mama.MamaSource.setMappedId (final String mappedId)
Referenced by com.wombat.mama.MamaSourceManager.addSource(), and com.wombat.mama.MamaSource.MamaSource().
setDisplayId()
native void com.wombat.mama.MamaSource.setDisplayId (final String displayId)
Referenced by com.wombat.mama.MamaSource.MamaSource(), and com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative().
setQuality()
native void com.wombat.mama.MamaSource.setQuality (short quality)
Referenced by com.wombat.mama.MamaSource.MamaSource().
setState()
void com.wombat.mama.MamaSource.setState (MamaSourceState state)
setParent()
void com.wombat.mama.MamaSource.setParent (MamaSource parent)
References com.wombat.mama.MamaSource.setSymbolNamespace().
Referenced by com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative().
setSymbolNamespace()
native void com.wombat.mama.MamaSource.setSymbolNamespace (final String symbolNamespace)
Referenced by com.wombat.mama.MamaSource.MamaSource(), and com.wombat.mama.MamaSource.setParent().
setTransportName()
void com.wombat.mama.MamaSource.setTransportName (final String transportName)
References com.wombat.mama.MamaTransport.setName().
setTransport()
void com.wombat.mama.MamaSource.setTransport (MamaTransport transport)
References com.wombat.mama.MamaSource.getDisplayId(), com.wombat.mama.MamaSource.getId(), com.wombat.mama.MamaSource.getMappedId(), and com.wombat.mama.MamaSource.getQuality().
Referenced by com.wombat.mama.MamaSource.MamaSource().
getId()
native final String com.wombat.mama.MamaSource.getId ()
Referenced by com.wombat.mama.MamaSourceManager.addSource(), com.wombat.mama.MamaSourceGroup.addSource(), com.wombat.mama.MamaSourceGroup.addSourceWithName(), com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative(), and com.wombat.mama.MamaSource.setTransport().
getMappedId()
native final String com.wombat.mama.MamaSource.getMappedId ()
Referenced by com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative(), and com.wombat.mama.MamaSource.setTransport().
getDisplayId()
native final String com.wombat.mama.MamaSource.getDisplayId ()
Referenced by com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative(), and com.wombat.mama.MamaSource.setTransport().
getQuality()
native short com.wombat.mama.MamaSource.getQuality ()
Referenced by com.wombat.mama.MamaSourceDerivative.getQuality(), and com.wombat.mama.MamaSource.setTransport().
getState()
MamaSourceState com.wombat.mama.MamaSource.getState ()
Get the state of a mama source object.
Returns
The state of the source object
Referenced by com.wombat.mama.MamaSourceDerivative.getState().
getStateAsString()
String com.wombat.mama.MamaSource.getStateAsString ()
Get the stringified state name of a mama source object.
Returns
The stringified state of the source object
References com.wombat.mama.MamaSourceState.toString(), and com.wombat.mama.MamaSourceState.UKNOWN.
getParent()
MamaSource com.wombat.mama.MamaSource.getParent ()
Get the parent source of the mama source object.
Returns
MamaSource parent object
References com.wombat.mama.MamaSource.getSymbolNamespace().
getSymbolNamespace()
native final String com.wombat.mama.MamaSource.getSymbolNamespace ()
Referenced by com.wombat.mama.MamaSource.getParent().
getTransport()
MamaTransport com.wombat.mama.MamaSource.getTransport ()
Referenced by com.wombat.mama.MamaSubscription.getTransport().
addSubscription()
void com.wombat.mama.MamaSource.addSubscription (final String key, MamaSubscription subscription)
Add a subscriptions to the mamaSource.
Parameters
key Key value to use to insert Subscription into a Subscription Map
subscription MamaSubscription object
Exceptions
MamaException will be thrown is the key value already exists in the Map
findSubscription()
MamaSubscription com.wombat.mama.MamaSource.findSubscription (final String key)
find a MamaSubscription, null will be returned if not found
Parameters
key The String identifier key for the subscription
Returns
The mama subscription object
References com.wombat.mama.MamaSource.findSubscription().
Referenced by com.wombat.mama.MamaSource.findSubscription().
isPartOf()
boolean com.wombat.mama.MamaSource.isPartOf (MamaSource source)
References com.wombat.mama.MamaSource.isPartOf().
Referenced by com.wombat.mama.MamaSource.isPartOf().
destroy()
void com.wombat.mama.MamaSource.destroy ()