OpenMAMA Java API: com.wombat.mama.MamaTimer Class Reference
com.wombat.mama.MamaTimer Class Reference
Public Member Functions
long getPointerVal ()
native void create (MamaQueue queue, MamaTimerCallback callback, double interval)
Create a timer.
void create (MamaQueue queue, MamaTimerCallback callback, double interval, Object closure)
Create a timer.
native void destroy ()
native void resetInterval (double interval)
native double getInterval ()
native void reset ()
Object getClosure ()
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaTimer.getPointerVal ()
References com.wombat.mama.MamaTimer.create().
create() [1/2]
native void com.wombat.mama.MamaTimer.create (MamaQueue queue, MamaTimerCallback callback, double interval)
Create a timer.
Parameters
queue The MamaQueue.
callback The object implementing the callback functions.
interval The timer interval in seconds.
Referenced by com.wombat.mama.MamaTimer.create(), and com.wombat.mama.MamaTimer.getPointerVal().
create() [2/2]
void com.wombat.mama.MamaTimer.create (MamaQueue queue, MamaTimerCallback callback, double interval, Object closure)
Create a timer.
Parameters
queue The MamaQueue.
callback The object implementing the callback functions.
interval The timer interval in seconds.
closure The closure will be passed to subsequent callback invocations for this subscription.
References com.wombat.mama.MamaTimer.create(), com.wombat.mama.MamaTimer.destroy(), com.wombat.mama.MamaTimer.getInterval(), com.wombat.mama.MamaTimer.reset(), and com.wombat.mama.MamaTimer.resetInterval().
destroy()
native void com.wombat.mama.MamaTimer.destroy ()
Referenced by com.wombat.mama.MamaTimer.create().
resetInterval()
native void com.wombat.mama.MamaTimer.resetInterval (double interval)
Referenced by com.wombat.mama.MamaTimer.create().
getInterval()
native double com.wombat.mama.MamaTimer.getInterval ()
Referenced by com.wombat.mama.MamaTimer.create().
reset()
native void com.wombat.mama.MamaTimer.reset ()
Referenced by com.wombat.mama.MamaTimer.create().
getClosure()
Object com.wombat.mama.MamaTimer.getClosure ()