OpenMAMA Java API: com.wombat.mama.MamaBuffer Class Reference
com.wombat.mama.MamaBuffer Class Reference
Mama Assignable Buffer.
Public Member Functions
MamaBuffer ()
void grow (int length)
byte [] array ()
int limit ()
void limit (int length)
CharBuffer asCharBuffer ()
ByteBuffer asByteBuffer ()
Detailed Description
Mama Assignable Buffer.
The default is a ByteBuffer but can also returned as a CharBuffer.
Constructor & Destructor Documentation
MamaBuffer()
com.wombat.mama.MamaBuffer.MamaBuffer ()
Member Function Documentation
grow()
void com.wombat.mama.MamaBuffer.grow (int length)
Referenced by com.wombat.mama.MamaMsg.getStringAsBuffer(), and com.wombat.mama.MamaMsg.tryStringAsBuffer().
array()
byte [] com.wombat.mama.MamaBuffer.array ()
Referenced by com.wombat.mama.MamaMsg.getStringAsBuffer(), and com.wombat.mama.MamaMsg.tryStringAsBuffer().
limit() [1/2]
int com.wombat.mama.MamaBuffer.limit ()
Referenced by com.wombat.mama.MamaMsg.getStringAsBuffer(), and com.wombat.mama.MamaMsg.tryStringAsBuffer().
limit() [2/2]
void com.wombat.mama.MamaBuffer.limit (int length)
asCharBuffer()
CharBuffer com.wombat.mama.MamaBuffer.asCharBuffer ()
asByteBuffer()
ByteBuffer com.wombat.mama.MamaBuffer.asByteBuffer ()