OpenMAMA Java API: com.wombat.mama.MamaPublisher Class Reference
com.wombat.mama.MamaPublisher Class Reference
Public Member Functions
void create (MamaTransport transport, String topic)
void create (MamaTransport transport, String topic, String source)
void create (MamaTransport transport, MamaQueue queue, String topic, MamaPublisherCallback cb, Object closure)
void create (MamaTransport transport, MamaQueue queue, String topic, String source, MamaPublisherCallback cb, Object closure)
Object getClosure ()
native void destroy ()
native void destroyEx ()
void send (MamaMsg msg)
void sendWithThrottle (MamaMsg msg)
void sendWithThrottle (MamaMsg msg, MamaThrottleCallback callback)
void sendReplyToInbox (MamaMsg request, MamaMsg reply)
void sendReplyToInboxWithThrottle (MamaMsg request, MamaMsg reply)
void sendFromInbox (MamaInbox inbox, MamaMsg msg)
MamaTransport getTransport ()
native String getRoot ()
native String getSource ()
native String getSymbol ()
native short getState ()
native String stringForState (short state)
Member Function Documentation
create() [1/4]
void com.wombat.mama.MamaPublisher.create (MamaTransport transport, String topic)
create() [2/4]
void com.wombat.mama.MamaPublisher.create (MamaTransport transport, String topic, String source)
create() [3/4]
void com.wombat.mama.MamaPublisher.create (MamaTransport transport, MamaQueue queue, String topic, MamaPublisherCallback cb, Object closure)
create() [4/4]
void com.wombat.mama.MamaPublisher.create (MamaTransport transport, MamaQueue queue, String topic, String source, MamaPublisherCallback cb, Object closure)
getClosure()
Object com.wombat.mama.MamaPublisher.getClosure ()
References com.wombat.mama.MamaPublisher.destroy(), and com.wombat.mama.MamaPublisher.destroyEx().
destroy()
native void com.wombat.mama.MamaPublisher.destroy ()
Referenced by com.wombat.mama.MamaPublisher.getClosure().
destroyEx()
native void com.wombat.mama.MamaPublisher.destroyEx ()
Referenced by com.wombat.mama.MamaPublisher.getClosure().
send()
void com.wombat.mama.MamaPublisher.send (MamaMsg msg)
sendWithThrottle() [1/2]
void com.wombat.mama.MamaPublisher.sendWithThrottle (MamaMsg msg)
sendWithThrottle() [2/2]
void com.wombat.mama.MamaPublisher.sendWithThrottle (MamaMsg msg, MamaThrottleCallback callback)
sendReplyToInbox()
void com.wombat.mama.MamaPublisher.sendReplyToInbox (MamaMsg request, MamaMsg reply)
sendReplyToInboxWithThrottle()
void com.wombat.mama.MamaPublisher.sendReplyToInboxWithThrottle (MamaMsg request, MamaMsg reply)
sendFromInbox()
void com.wombat.mama.MamaPublisher.sendFromInbox (MamaInbox inbox, MamaMsg msg)
getTransport()
MamaTransport com.wombat.mama.MamaPublisher.getTransport ()
References com.wombat.mama.MamaTransport.getPointerVal(), com.wombat.mama.MamaPublisher.getRoot(), com.wombat.mama.MamaPublisher.getSource(), com.wombat.mama.MamaPublisher.getState(), com.wombat.mama.MamaPublisher.getSymbol(), com.wombat.mama.MamaTransport.setPointerVal(), and com.wombat.mama.MamaPublisher.stringForState().
getRoot()
native String com.wombat.mama.MamaPublisher.getRoot ()
Referenced by com.wombat.mama.MamaPublisher.getTransport().
getSource()
native String com.wombat.mama.MamaPublisher.getSource ()
Referenced by com.wombat.mama.MamaPublisher.getTransport().
getSymbol()
native String com.wombat.mama.MamaPublisher.getSymbol ()
Referenced by com.wombat.mama.MamaPublisher.getTransport().
getState()
native short com.wombat.mama.MamaPublisher.getState ()
Referenced by com.wombat.mama.MamaPublisher.getTransport().
stringForState()
native String com.wombat.mama.MamaPublisher.stringForState (short state)
Referenced by com.wombat.mama.MamaPublisher.getTransport().