OpenMAMA Java API: com.wombat.mama.MamaSourceDerivative Class Reference
com.wombat.mama.MamaSourceDerivative Class Reference
Inherits com.wombat.mama.MamaSource.
Public Member Functions
MamaSourceDerivative (MamaSource baseSource)
MamaSource getBaseSource ()
Return the base source.
MamaSourceState getState ()
short getQuality ()
MamaSourceDerivative findSourceDerivative (final String sourceName)
Public Member Functions inherited from com.wombat.mama.MamaSource
MamaSource ()
Creates a new mama source with default parameters.
MamaSource (final String sourceId, MamaTransport transport, final String symbolNamespace)
native void setId (final String sourceId)
native void setMappedId (final String mappedId)
native void setDisplayId (final String displayId)
native void setQuality (short quality)
void setState (MamaSourceState state)
void setParent (MamaSource parent)
native void setSymbolNamespace (final String symbolNamespace)
void setTransportName (final String transportName)
void setTransport (MamaTransport transport)
native final String getId ()
native final String getMappedId ()
native final String getDisplayId ()
native short getQuality ()
MamaSourceState getState ()
Get the state of a mama source object.
String getStateAsString ()
Get the stringified state name of a mama source object.
MamaSource getParent ()
Get the parent source of the mama source object.
native final String getSymbolNamespace ()
MamaTransport getTransport ()
void addSubscription (final String key, MamaSubscription subscription)
Add a subscriptions to the mamaSource.
MamaSubscription findSubscription (final String key)
find a MamaSubscription, null will be returned if not found
boolean isPartOf (MamaSource source)
void destroy ()
Public Member Functions inherited from com.wombat.mama.MamaSourceManager
MamaSourceManager ()
Constructor - creates a new MamaSourceManager object.
MamaSource findOrCreateSource (final String sourceName)
Locates an existing mamaSource for a given name, if none exists a new one is created and added to the source manager.
MamaSource findSource (final String sourceName)
locates an existing source for a given name, if none is found null is returned, The caller has to validate null value on return.
void addSource (MamaSource mamaSource)
Add an existing mama Source to the source manager.
void addSource (MamaSource mamaSource, final String sourceName)
Add an existing mama Source to the source manager.
int getSize ()
Return the size of the contents of source manager.
Iterator sourceIterator ()
void destroy ()
Constructor & Destructor Documentation
MamaSourceDerivative()
com.wombat.mama.MamaSourceDerivative.MamaSourceDerivative (MamaSource baseSource)
References com.wombat.mama.MamaSourceManager.addSource(), com.wombat.mama.MamaSource.getDisplayId(), com.wombat.mama.MamaSource.getId(), com.wombat.mama.MamaSource.getMappedId(), com.wombat.mama.MamaSource.MamaSource(), com.wombat.mama.MamaSource.setDisplayId(), com.wombat.mama.MamaSource.setId(), com.wombat.mama.MamaSource.setParent(), and com.wombat.mama.MamaSourceManager.sourceIterator().
Member Function Documentation
getBaseSource()
MamaSource com.wombat.mama.MamaSourceDerivative.getBaseSource ()
Return the base source.
Returns
the base source.
getState()
MamaSourceState com.wombat.mama.MamaSourceDerivative.getState ()
References com.wombat.mama.MamaSource.getState(), and com.wombat.mama.MamaSourceState.UKNOWN.
getQuality()
short com.wombat.mama.MamaSourceDerivative.getQuality ()
References com.wombat.mama.MamaSource.getQuality(), and com.wombat.mama.MamaQuality.QUALITY_UNKNOWN.
findSourceDerivative()
MamaSourceDerivative com.wombat.mama.MamaSourceDerivative.findSourceDerivative (final String sourceName)
References com.wombat.mama.MamaSourceManager.findSource().