OpenMAMA Java API: com.wombat.mama.MamaTransport Class Reference
com.wombat.mama.MamaTransport Class Reference
Public Member Functions
MamaTransport ()
The constructor initialises all member variables and creates the re-usable objects including the transport listeners.
void setTransportCallbackQueue (MamaQueue queue)
Set the callback queue.
void addTransportListener (MamaTransportListener transportListener)
This function will set the client listener, note that only one listener or extended listener is supported at any one time.
void addTransportTopicListener (MamaTransportTopicListener transportTopicListener)
This function will set the client topic listener, note that only one topic listener is supported at any one time.
void removeTransportListener (MamaTransportListener transportListener)
This function will remove the current transport listener.
void removeTransportTopicListener ()
This function will remove the current topic listener.
long getPointerVal ()
void create (MamaBridge bridge)
native void _create (MamaBridge bridge)
void create (String name, MamaBridge bridge)
native void _create (String name, MamaBridge bridge)
native void destroy ()
double getOutboundThrottle (MamaThrottleInstance throttleInstance)
double getOutboundThrottle ()
void setOutboundThrottle (MamaThrottleInstance throttleInstance, double outboundThrottle)
void setOutboundThrottle (double outboundThrottle)
native void setDescription (String description)
native String getDescription ()
native void setInvokeQualityForAllSubscs (boolean invokeQualityForAllSubscs)
native boolean getInvokeQualityForAllSubscs ()
native short getQuality ()
MamaBridge getBridge ()
native void requestConflation ()
native void requestEndConflation ()
native String getName ()
native void setName (String name)
Protected Member Functions
void setPointerVal (long pointerVal)
Constructor & Destructor Documentation
MamaTransport()
com.wombat.mama.MamaTransport.MamaTransport ()
The constructor initialises all member variables and creates the re-usable objects including the transport listeners.
Member Function Documentation
setTransportCallbackQueue()
void com.wombat.mama.MamaTransport.setTransportCallbackQueue (MamaQueue queue)
Set the callback queue.
addTransportListener()
void com.wombat.mama.MamaTransport.addTransportListener (MamaTransportListener transportListener)
This function will set the client listener, note that only one listener or extended listener is supported at any one time.
Parameters
transportListener The new listener, null can be passed to remove the current listener.
addTransportTopicListener()
void com.wombat.mama.MamaTransport.addTransportTopicListener (MamaTransportTopicListener transportTopicListener)
This function will set the client topic listener, note that only one topic listener is supported at any one time.
Parameters
transportTopicListener The new listener, null can be passed to remove the current listener.
removeTransportListener()
void com.wombat.mama.MamaTransport.removeTransportListener (MamaTransportListener transportListener)
This function will remove the current transport listener.
It will actually remove both the basic and extended listeners.
Parameters
transportListener The transport listener. Note that this parameter is currently redundant.
removeTransportTopicListener()
void com.wombat.mama.MamaTransport.removeTransportTopicListener ()
This function will remove the current topic listener.
getPointerVal()
long com.wombat.mama.MamaTransport.getPointerVal ()
Referenced by com.wombat.mama.MamaPublisher.getTransport().
setPointerVal()
void com.wombat.mama.MamaTransport.setPointerVal (long pointerVal) protected
Referenced by com.wombat.mama.MamaPublisher.getTransport().
create() [1/2]
void com.wombat.mama.MamaTransport.create (MamaBridge bridge)
References com.wombat.mama.MamaTransport._create().
_create() [1/2]
native void com.wombat.mama.MamaTransport._create (MamaBridge bridge)
Referenced by com.wombat.mama.MamaTransport.create().
create() [2/2]
void com.wombat.mama.MamaTransport.create (String name, MamaBridge bridge)
References com.wombat.mama.MamaTransport._create(), com.wombat.mama.MamaTransport.destroy(), and com.wombat.mama.MamaTransport.getOutboundThrottle().
_create() [2/2]
native void com.wombat.mama.MamaTransport._create (String name, MamaBridge bridge)
destroy()
native void com.wombat.mama.MamaTransport.destroy ()
Referenced by com.wombat.mama.MamaTransport.create().
getOutboundThrottle() [1/2]
double com.wombat.mama.MamaTransport.getOutboundThrottle (MamaThrottleInstance throttleInstance)
References com.wombat.mama.MamaTransport.getOutboundThrottle(), and com.wombat.mama.MamaThrottleInstance.getValue().
getOutboundThrottle() [2/2]
double com.wombat.mama.MamaTransport.getOutboundThrottle ()
References com.wombat.mama.MamaThrottleInstance.INITIAL_THROTTLE.
Referenced by com.wombat.mama.MamaTransport.create(), and com.wombat.mama.MamaTransport.getOutboundThrottle().
setOutboundThrottle() [1/2]
void com.wombat.mama.MamaTransport.setOutboundThrottle (MamaThrottleInstance throttleInstance, double outboundThrottle)
References com.wombat.mama.MamaThrottleInstance.getValue().
setOutboundThrottle() [2/2]
void com.wombat.mama.MamaTransport.setOutboundThrottle (double outboundThrottle)
References com.wombat.mama.MamaTransport.getDescription(), com.wombat.mama.MamaTransport.getInvokeQualityForAllSubscs(), com.wombat.mama.MamaTransport.getQuality(), com.wombat.mama.MamaThrottleInstance.INITIAL_THROTTLE, com.wombat.mama.MamaTransport.setDescription(), and com.wombat.mama.MamaTransport.setInvokeQualityForAllSubscs().
setDescription()
native void com.wombat.mama.MamaTransport.setDescription (String description)
Referenced by com.wombat.mama.MamaTransport.setOutboundThrottle().
getDescription()
native String com.wombat.mama.MamaTransport.getDescription ()
Referenced by com.wombat.mama.MamaTransport.setOutboundThrottle().
setInvokeQualityForAllSubscs()
native void com.wombat.mama.MamaTransport.setInvokeQualityForAllSubscs (boolean invokeQualityForAllSubscs)
Referenced by com.wombat.mama.MamaTransport.setOutboundThrottle().
getInvokeQualityForAllSubscs()
native boolean com.wombat.mama.MamaTransport.getInvokeQualityForAllSubscs ()
Referenced by com.wombat.mama.MamaTransport.setOutboundThrottle().
getQuality()
native short com.wombat.mama.MamaTransport.getQuality ()
Referenced by com.wombat.mama.MamaTransport.setOutboundThrottle().
getBridge()
MamaBridge com.wombat.mama.MamaTransport.getBridge ()
References com.wombat.mama.MamaTransport.getName(), com.wombat.mama.MamaTransport.requestConflation(), com.wombat.mama.MamaTransport.requestEndConflation(), and com.wombat.mama.MamaTransport.setName().
requestConflation()
native void com.wombat.mama.MamaTransport.requestConflation ()
Referenced by com.wombat.mama.MamaTransport.getBridge().
requestEndConflation()
native void com.wombat.mama.MamaTransport.requestEndConflation ()
Referenced by com.wombat.mama.MamaTransport.getBridge().
getName()
native String com.wombat.mama.MamaTransport.getName ()
Referenced by com.wombat.mama.MamaTransport.getBridge().
setName()
native void com.wombat.mama.MamaTransport.setName (String name)
Referenced by com.wombat.mama.MamaTransport.getBridge(), and com.wombat.mama.MamaSource.setTransportName().