OpenMAMA Java API: com.wombat.mama.MamaMsgStatus Class Reference
com.wombat.mama.MamaMsgStatus Class Reference
Utility class for interpreting Mama message status.
Static Public Member Functions
static int statusForMsg (final MamaMsg msg)
Extract the status from the supplied message.
static String stringForStatus (final MamaMsg msg)
Return the status as a string given an MamaMsg message.
static String stringForStatus (final int type)
Return a text description of the message's status.
Static Public Attributes
static final short STATUS_OK = 0
OK.
static final short STATUS_LINE_DOWN = 1
The feed handler has detected a Line Down.
static final short STATUS_NO_SUBSCRIBERS = 2
The feed handler does not have any subscribers to the subject.
static final short STATUS_BAD_SYMBOL = 3
The symbol does not exist.
static final short STATUS_EXPIRED = 4
Expired.
static final short STATUS_TIMEOUT = 5
A time out occurred.
static final short STATUS_MISC = 6
Miscellaneous status.
static final short STATUS_STALE = 7
The subject is stale.
static final short STATUS_TIBRV_STATUS = 8
static final short STATUS_PLATFORM_STATUS = 8
Error in the underlying messaging API.
static final short STATUS_NOT_ENTITLED = 9
Not entitled to a subject.
static final short STATUS_NOT_FOUND = 10
Not found.
static final short STATUS_POSSIBLY_STALE = 11
Messages may have been dropped.
static final short STATUS_NOT_PERMISSIONED = 12
Not permissioned for the subject.
static final short STATUS_TOPIC_CHANGE = 13
Topic renamed.
static final short STATUS_BANDWIDTH_EXCEEDED = 14
Bandwidth exceeded.
static final short STATUS_DUPLICATE = 15
Message with duplicate sequence number.
static final short STATUS_DELETE = 17
Message with the type of DELETE.
static final short STATUS_EXCEPTION = 999
Detailed Description
Utility class for interpreting Mama message status.
Member Function Documentation
statusForMsg()
static int com.wombat.mama.MamaMsgStatus.statusForMsg (final MamaMsg msg) static
Extract the status from the supplied message.
Parameters
msg
References com.wombat.mama.MamaMsg.getI32(), com.wombat.mama.MamaReservedFields.getId(), com.wombat.mama.MamaReservedFields.getName(), com.wombat.mama.MamaReservedFields.MsgStatus, and com.wombat.mama.MamaMsgStatus.STATUS_NOT_FOUND.
Referenced by com.wombat.mama.MamaMsgStatus.stringForStatus().
stringForStatus() [1/2]
static String com.wombat.mama.MamaMsgStatus.stringForStatus (final MamaMsg msg) static
Return the status as a string given an MamaMsg message.
Returns
The string.
References com.wombat.mama.MamaMsgStatus.statusForMsg().
stringForStatus() [2/2]
static String com.wombat.mama.MamaMsgStatus.stringForStatus (final int type) static
Return a text description of the message's status.
Returns
The description.
Member Data Documentation
STATUS_OK
final short com.wombat.mama.MamaMsgStatus.STATUS_OK = 0 static
OK.
STATUS_LINE_DOWN
final short com.wombat.mama.MamaMsgStatus.STATUS_LINE_DOWN = 1 static
The feed handler has detected a Line Down.
STATUS_NO_SUBSCRIBERS
final short com.wombat.mama.MamaMsgStatus.STATUS_NO_SUBSCRIBERS = 2 static
The feed handler does not have any subscribers to the subject.
STATUS_BAD_SYMBOL
final short com.wombat.mama.MamaMsgStatus.STATUS_BAD_SYMBOL = 3 static
The symbol does not exist.
STATUS_EXPIRED
final short com.wombat.mama.MamaMsgStatus.STATUS_EXPIRED = 4 static
Expired.
STATUS_TIMEOUT
final short com.wombat.mama.MamaMsgStatus.STATUS_TIMEOUT = 5 static
A time out occurred.
STATUS_MISC
final short com.wombat.mama.MamaMsgStatus.STATUS_MISC = 6 static
Miscellaneous status.
Not an error
STATUS_STALE
final short com.wombat.mama.MamaMsgStatus.STATUS_STALE = 7 static
The subject is stale.
Messages may have been dropped
STATUS_TIBRV_STATUS
final short com.wombat.mama.MamaMsgStatus.STATUS_TIBRV_STATUS = 8 static
STATUS_PLATFORM_STATUS
final short com.wombat.mama.MamaMsgStatus.STATUS_PLATFORM_STATUS = 8 static
Error in the underlying messaging API.
STATUS_NOT_ENTITLED
final short com.wombat.mama.MamaMsgStatus.STATUS_NOT_ENTITLED = 9 static
Not entitled to a subject.
STATUS_NOT_FOUND
final short com.wombat.mama.MamaMsgStatus.STATUS_NOT_FOUND = 10 static
Not found.
Referenced by com.wombat.mama.MamaMsgStatus.statusForMsg().
STATUS_POSSIBLY_STALE
final short com.wombat.mama.MamaMsgStatus.STATUS_POSSIBLY_STALE = 11 static
Messages may have been dropped.
STATUS_NOT_PERMISSIONED
final short com.wombat.mama.MamaMsgStatus.STATUS_NOT_PERMISSIONED = 12 static
Not permissioned for the subject.
STATUS_TOPIC_CHANGE
final short com.wombat.mama.MamaMsgStatus.STATUS_TOPIC_CHANGE = 13 static
Topic renamed.
STATUS_BANDWIDTH_EXCEEDED
final short com.wombat.mama.MamaMsgStatus.STATUS_BANDWIDTH_EXCEEDED = 14 static
Bandwidth exceeded.
STATUS_DUPLICATE
final short com.wombat.mama.MamaMsgStatus.STATUS_DUPLICATE = 15 static
Message with duplicate sequence number.
STATUS_DELETE
final short com.wombat.mama.MamaMsgStatus.STATUS_DELETE = 17 static
Message with the type of DELETE.
STATUS_EXCEPTION
final short com.wombat.mama.MamaMsgStatus.STATUS_EXCEPTION = 999 static