OpenMAMA Java API: com.wombat.mama.MamaDateTime Class Reference
com.wombat.mama.MamaDateTime Class Reference
MamaDataTime.
Inherits Comparable.
Public Member Functions
MamaDateTime ()
MamaDateTime (MamaDateTime copy)
MamaDateTime (MamaDateTime time, MamaDateTime date)
MamaDateTime (Calendar calendar)
MamaDateTime (String str)
MamaDateTime (String str, MamaTimeZone tz)
String toString ()
String formatString (String str, MamaTimeZone tz)
int compareTo (Object obj)
boolean equals (Object obj)
int hashCode ()
native boolean isEmpty ()
void setEpochTime (long secondsSinceEpoch, long microseconds, MamaDateTimePrecision precision)
void setEpochTime (long secondsSinceEpoch, long microseconds)
native void setEpochTimeF64 (double secondsSinceEpoch)
native void setEpochTimeMilliseconds (long millisecondsSinceEpoch)
native void setEpochTimeMicroseconds (long microsecondsSinceEpoch)
void setWithHints (long secondsSinceEpoch, long microseconds, MamaDateTimePrecision precision, MamaDateTimeHints hints)
native void setToNow ()
void setToMidnightToday (MamaTimeZone tz)
void set (int year, int month, int day, int hour, int minute, int second, long microsecond, MamaDateTimePrecision precision, MamaTimeZone tz)
void setTime (int hour, int minute, int second, long microsecond, MamaDateTimePrecision precision, MamaTimeZone tz)
native void setDate (int year, int month, int day)
native void copyTime (MamaDateTime src)
native void copyDate (MamaDateTime src)
native void clear ()
native void clearTime ()
native void clearDate ()
native boolean hasDate ()
native boolean hasTime ()
native void addSeconds (double seconds)
native void addSeconds (long seconds)
native void addMicroSeconds (long microSeconds)
long getEpochTimeMicroseconds ()
Get the date and time as microseconds since the Epoch, (using the UTC timezone).
long getEpochTimeMicroseconds (MamaTimeZone tz)
long getEpochTimeMilliseconds ()
long getEpochTimeMilliseconds (MamaTimeZone tz)
double getEpochTimeSeconds ()
double getEpochTimeSeconds (MamaTimeZone tz)
native double getEpochTimeSecondsWithCheck ()
Get the date and time as seconds since the Epoch, (using the UTC timezone).
native String getAsString ()
native String getTimeAsString ()
native String getDateAsString ()
native long getYear ()
native long getMonth ()
native long getDay ()
native long getHour ()
native long getMinute ()
native long getSecond ()
native long getMicrosecond ()
MamaDayOfWeek getDayOfWeek ()
Calendar getCalendar ()
native void destroy ()
native void copy (MamaDateTime copy)
Static Public Member Functions
static native double diffSeconds (MamaDateTime t1, MamaDateTime t0)
static native double diffSecondsSameDay (MamaDateTime t1, MamaDateTime t0)
static native long diffMicroseconds (MamaDateTime t1, MamaDateTime t0)
Protected Member Functions
long getPointerVal ()
void setPointerVal (long pointerVal)
void finalize ()
Detailed Description
MamaDataTime.
Posix date/time representation.
Constructor & Destructor Documentation
MamaDateTime() [1/6]
com.wombat.mama.MamaDateTime.MamaDateTime ()
Referenced by com.wombat.mama.MamaDateTime.compareTo(), and com.wombat.mama.MamaDateTime.equals().
MamaDateTime() [2/6]
com.wombat.mama.MamaDateTime.MamaDateTime (MamaDateTime copy)
References com.wombat.mama.MamaDateTime.copy().
MamaDateTime() [3/6]
com.wombat.mama.MamaDateTime.MamaDateTime (MamaDateTime time, MamaDateTime date)
References com.wombat.mama.MamaDateTime.copyDate(), com.wombat.mama.MamaDateTime.getEpochTimeMilliseconds(), com.wombat.mama.MamaDateTimePrecision.PREC_MILLISECONDS, and com.wombat.mama.MamaDateTime.setEpochTimeMilliseconds().
MamaDateTime() [4/6]
com.wombat.mama.MamaDateTime.MamaDateTime (Calendar calendar)
References com.wombat.mama.MamaDateTimePrecision.PREC_MILLISECONDS, and com.wombat.mama.MamaDateTime.setEpochTimeMilliseconds().
MamaDateTime() [5/6]
com.wombat.mama.MamaDateTime.MamaDateTime (String str)
MamaDateTime() [6/6]
com.wombat.mama.MamaDateTime.MamaDateTime (String str, MamaTimeZone tz)
References com.wombat.mama.MamaTimeZone.tz().
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaDateTime.getPointerVal () protected
Referenced by com.wombat.mama.MamaMsgField.getDateTime(), and com.wombat.mama.MamaMsg.getDateTime().
setPointerVal()
void com.wombat.mama.MamaDateTime.setPointerVal (long pointerVal) protected
toString()
String com.wombat.mama.MamaDateTime.toString ()
References com.wombat.mama.MamaDateTime.getAsString().
formatString()
String com.wombat.mama.MamaDateTime.formatString (String str, MamaTimeZone tz)
References com.wombat.mama.MamaTimeZone.tz().
compareTo()
int com.wombat.mama.MamaDateTime.compareTo (Object obj)
References com.wombat.mama.MamaDateTime.getEpochTimeMicroseconds(), and com.wombat.mama.MamaDateTime.MamaDateTime().
equals()
boolean com.wombat.mama.MamaDateTime.equals (Object obj)
References com.wombat.mama.MamaDateTime.getEpochTimeMicroseconds(), and com.wombat.mama.MamaDateTime.MamaDateTime().
hashCode()
int com.wombat.mama.MamaDateTime.hashCode ()
References com.wombat.mama.MamaDateTime.getEpochTimeMicroseconds(), and com.wombat.mama.MamaDateTime.isEmpty().
isEmpty()
native boolean com.wombat.mama.MamaDateTime.isEmpty ()
Referenced by com.wombat.mama.MamaDateTime.hashCode().
setEpochTime() [1/2]
void com.wombat.mama.MamaDateTime.setEpochTime (long secondsSinceEpoch, long microseconds, MamaDateTimePrecision precision)
References com.wombat.mama.MamaDateTimePrecision.getShortValue().
setEpochTime() [2/2]
void com.wombat.mama.MamaDateTime.setEpochTime (long secondsSinceEpoch, long microseconds)
References com.wombat.mama.MamaDateTimePrecision.getShortValue(), com.wombat.mama.MamaDateTimePrecision.PREC_UNKNOWN, com.wombat.mama.MamaDateTime.setEpochTimeF64(), com.wombat.mama.MamaDateTime.setEpochTimeMicroseconds(), and com.wombat.mama.MamaDateTime.setEpochTimeMilliseconds().
setEpochTimeF64()
native void com.wombat.mama.MamaDateTime.setEpochTimeF64 (double secondsSinceEpoch)
Referenced by com.wombat.mama.MamaDateTime.setEpochTime().
setEpochTimeMilliseconds()
native void com.wombat.mama.MamaDateTime.setEpochTimeMilliseconds (long millisecondsSinceEpoch)
Referenced by com.wombat.mama.MamaDateTime.MamaDateTime(), and com.wombat.mama.MamaDateTime.setEpochTime().
setEpochTimeMicroseconds()
native void com.wombat.mama.MamaDateTime.setEpochTimeMicroseconds (long microsecondsSinceEpoch)
Referenced by com.wombat.mama.MamaDateTime.setEpochTime().
setWithHints()
void com.wombat.mama.MamaDateTime.setWithHints (long secondsSinceEpoch, long microseconds, MamaDateTimePrecision precision, MamaDateTimeHints hints)
This is not actually implemented in C/C++. The hints field is ignored.
References com.wombat.mama.MamaDateTimePrecision.getShortValue(), com.wombat.mama.MamaDateTime.setToNow(), and com.wombat.mama.MamaTimeZone.tz().
setToNow()
native void com.wombat.mama.MamaDateTime.setToNow ()
Referenced by com.wombat.mama.MamaDateTime.setWithHints().
setToMidnightToday()
void com.wombat.mama.MamaDateTime.setToMidnightToday (MamaTimeZone tz)
References com.wombat.mama.MamaTimeZone.tz().
set()
void com.wombat.mama.MamaDateTime.set (int year, int month, int day, int hour, int minute, int second, long microsecond, MamaDateTimePrecision precision, MamaTimeZone tz)
References com.wombat.mama.MamaDateTime.clear(), com.wombat.mama.MamaDateTime.setDate(), and com.wombat.mama.MamaDateTime.setTime().
setTime()
void com.wombat.mama.MamaDateTime.setTime (int hour, int minute, int second, long microsecond, MamaDateTimePrecision precision, MamaTimeZone tz)
References com.wombat.mama.MamaDateTime.addMicroSeconds(), com.wombat.mama.MamaDateTime.addSeconds(), com.wombat.mama.MamaDateTime.clear(), com.wombat.mama.MamaDateTime.clearDate(), com.wombat.mama.MamaDateTime.clearTime(), com.wombat.mama.MamaDateTime.copyDate(), com.wombat.mama.MamaDateTime.copyTime(), com.wombat.mama.MamaDateTimePrecision.getShortValue(), com.wombat.mama.MamaDateTime.hasDate(), com.wombat.mama.MamaDateTime.hasTime(), com.wombat.mama.MamaDateTime.setDate(), and com.wombat.mama.MamaTimeZone.tz().
Referenced by com.wombat.mama.MamaDateTime.set().
setDate()
native void com.wombat.mama.MamaDateTime.setDate (int year, int month, int day)
Referenced by com.wombat.mama.MamaDateTime.set(), and com.wombat.mama.MamaDateTime.setTime().
copyTime()
native void com.wombat.mama.MamaDateTime.copyTime (MamaDateTime src)
Referenced by com.wombat.mama.MamaDateTime.setTime().
copyDate()
native void com.wombat.mama.MamaDateTime.copyDate (MamaDateTime src)
Referenced by com.wombat.mama.MamaDateTime.MamaDateTime(), and com.wombat.mama.MamaDateTime.setTime().
clear()
native void com.wombat.mama.MamaDateTime.clear ()
Referenced by com.wombat.mama.MamaDateTime.set(), and com.wombat.mama.MamaDateTime.setTime().
clearTime()
native void com.wombat.mama.MamaDateTime.clearTime ()
Referenced by com.wombat.mama.MamaDateTime.setTime().
clearDate()
native void com.wombat.mama.MamaDateTime.clearDate ()
Referenced by com.wombat.mama.MamaDateTime.setTime().
hasDate()
native boolean com.wombat.mama.MamaDateTime.hasDate ()
Referenced by com.wombat.mama.MamaDateTime.setTime().
hasTime()
native boolean com.wombat.mama.MamaDateTime.hasTime ()
Referenced by com.wombat.mama.MamaDateTime.setTime().
addSeconds() [1/2]
native void com.wombat.mama.MamaDateTime.addSeconds (double seconds)
Referenced by com.wombat.mama.MamaDateTime.setTime().
addSeconds() [2/2]
native void com.wombat.mama.MamaDateTime.addSeconds (long seconds)
addMicroSeconds()
native void com.wombat.mama.MamaDateTime.addMicroSeconds (long microSeconds)
Referenced by com.wombat.mama.MamaDateTime.setTime().
getEpochTimeMicroseconds() [1/2]
long com.wombat.mama.MamaDateTime.getEpochTimeMicroseconds ()
Get the date and time as microseconds since the Epoch, (using the UTC timezone).
Returns
The number of microseconds since the Epoch.
Exceptions
com.wombat.mama MamaException thrown if the underlying JNI object has been destroyed.
com.wombat.common.WombatException for other general MAMA errors.
Referenced by com.wombat.mama.MamaDateTime.compareTo(), com.wombat.mama.MamaDateTime.equals(), and com.wombat.mama.MamaDateTime.hashCode().
getEpochTimeMicroseconds() [2/2]
long com.wombat.mama.MamaDateTime.getEpochTimeMicroseconds (MamaTimeZone tz)
References com.wombat.mama.MamaTimeZone.tz().
getEpochTimeMilliseconds() [1/2]
long com.wombat.mama.MamaDateTime.getEpochTimeMilliseconds ()
Referenced by com.wombat.mama.MamaDateTime.MamaDateTime().
getEpochTimeMilliseconds() [2/2]
long com.wombat.mama.MamaDateTime.getEpochTimeMilliseconds (MamaTimeZone tz)
References com.wombat.mama.MamaTimeZone.tz().
getEpochTimeSeconds() [1/2]
double com.wombat.mama.MamaDateTime.getEpochTimeSeconds ()
getEpochTimeSeconds() [2/2]
double com.wombat.mama.MamaDateTime.getEpochTimeSeconds (MamaTimeZone tz)
References com.wombat.mama.MamaDateTime.getAsString(), com.wombat.mama.MamaDateTime.getDateAsString(), com.wombat.mama.MamaDateTime.getDay(), com.wombat.mama.MamaDateTime.getEpochTimeSecondsWithCheck(), com.wombat.mama.MamaDateTime.getHour(), com.wombat.mama.MamaDateTime.getMicrosecond(), com.wombat.mama.MamaDateTime.getMinute(), com.wombat.mama.MamaDateTime.getMonth(), com.wombat.mama.MamaDateTime.getSecond(), com.wombat.mama.MamaDateTime.getTimeAsString(), com.wombat.mama.MamaDateTime.getYear(), and com.wombat.mama.MamaTimeZone.tz().
getEpochTimeSecondsWithCheck()
native double com.wombat.mama.MamaDateTime.getEpochTimeSecondsWithCheck ()
Get the date and time as seconds since the Epoch, (using the UTC timezone).
If no date value is contained in the dateTime then it will be set to today's date and the calculation made.
The timezone must to set to UTC if calling this from multiple threads concurrently to avoid contention in strftime.
Returns
The number of seconds, (including partial seconds), since the Epoch.
Exceptions
com.wombat.mama MamaException thrown if the underlying JNI object has been destroyed.
com.wombat.common.WombatException for other general MAMA errors.
Referenced by com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getAsString()
native String com.wombat.mama.MamaDateTime.getAsString ()
Referenced by com.wombat.mama.MamaDateTime.getEpochTimeSeconds(), and com.wombat.mama.MamaDateTime.toString().
getTimeAsString()
native String com.wombat.mama.MamaDateTime.getTimeAsString ()
Referenced by com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getDateAsString()
native String com.wombat.mama.MamaDateTime.getDateAsString ()
Referenced by com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getYear()
native long com.wombat.mama.MamaDateTime.getYear ()
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getMonth()
native long com.wombat.mama.MamaDateTime.getMonth ()
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getDay()
native long com.wombat.mama.MamaDateTime.getDay ()
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getHour()
native long com.wombat.mama.MamaDateTime.getHour ()
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getMinute()
native long com.wombat.mama.MamaDateTime.getMinute ()
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getSecond()
native long com.wombat.mama.MamaDateTime.getSecond ()
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getMicrosecond()
native long com.wombat.mama.MamaDateTime.getMicrosecond ()
Referenced by com.wombat.mama.MamaDateTime.getEpochTimeSeconds().
getDayOfWeek()
MamaDayOfWeek com.wombat.mama.MamaDateTime.getDayOfWeek ()
References com.wombat.mama.MamaDateTime.diffMicroseconds(), com.wombat.mama.MamaDateTime.diffSeconds(), com.wombat.mama.MamaDateTime.diffSecondsSameDay(), and com.wombat.mama.MamaDayOfWeek.getDayForValue().
diffSeconds()
static native double com.wombat.mama.MamaDateTime.diffSeconds (MamaDateTime t1, MamaDateTime t0) static
Referenced by com.wombat.mama.MamaDateTime.getDayOfWeek().
diffSecondsSameDay()
static native double com.wombat.mama.MamaDateTime.diffSecondsSameDay (MamaDateTime t1, MamaDateTime t0) static
Referenced by com.wombat.mama.MamaDateTime.getDayOfWeek().
diffMicroseconds()
static native long com.wombat.mama.MamaDateTime.diffMicroseconds (MamaDateTime t1, MamaDateTime t0) static
Referenced by com.wombat.mama.MamaDateTime.getDayOfWeek().
getCalendar()
Calendar com.wombat.mama.MamaDateTime.getCalendar ()
References com.wombat.mama.MamaDateTime.copy(), com.wombat.mama.MamaDateTime.destroy(), com.wombat.mama.MamaDateTime.getDay(), com.wombat.mama.MamaDateTime.getHour(), com.wombat.mama.MamaDateTime.getMinute(), com.wombat.mama.MamaDateTime.getMonth(), com.wombat.mama.MamaDateTime.getSecond(), and com.wombat.mama.MamaDateTime.getYear().
destroy()
native void com.wombat.mama.MamaDateTime.destroy ()
Referenced by com.wombat.mama.MamaDateTime.finalize(), and com.wombat.mama.MamaDateTime.getCalendar().
copy()
native void com.wombat.mama.MamaDateTime.copy (MamaDateTime copy)
Referenced by com.wombat.mama.MamaDateTime.getCalendar(), and com.wombat.mama.MamaDateTime.MamaDateTime().
finalize()
void com.wombat.mama.MamaDateTime.finalize () protected
References com.wombat.mama.MamaDateTime.destroy().