OpenMAMA Java API: com.wombat.mama.MamaLogLevel Class Reference
com.wombat.mama.MamaLogLevel Class Reference
Public Member Functions
int getValue ()
Static Public Member Functions
static MamaLogLevel tryStringToLogLevel (String level)
static MamaLogLevel getMamaLogLevel (int level)
static MamaLogLevel getMamaLogLevel (Level level)
static Level getLevel (MamaLogLevel mamalevel)
Static Public Attributes
static final MamaLogLevel OFF = new MamaLogLevel(0)
static final MamaLogLevel SEVERE = new MamaLogLevel(1)
static final MamaLogLevel ERROR = new MamaLogLevel(2)
static final MamaLogLevel WARN = new MamaLogLevel(3)
static final MamaLogLevel NORMAL = new MamaLogLevel(4)
static final MamaLogLevel FINE = new MamaLogLevel(5)
static final MamaLogLevel FINER = new MamaLogLevel(6)
static final MamaLogLevel FINEST = new MamaLogLevel(7)
Member Function Documentation
getValue()
int com.wombat.mama.MamaLogLevel.getValue ()
Referenced by com.wombat.mama.Mama.log().
tryStringToLogLevel()
static MamaLogLevel com.wombat.mama.MamaLogLevel.tryStringToLogLevel (String level) static
References com.wombat.mama.MamaLogLevel.ERROR, com.wombat.mama.MamaLogLevel.FINE, com.wombat.mama.MamaLogLevel.FINER, com.wombat.mama.MamaLogLevel.FINEST, com.wombat.mama.MamaLogLevel.NORMAL, com.wombat.mama.MamaLogLevel.OFF, com.wombat.mama.MamaLogLevel.SEVERE, and com.wombat.mama.MamaLogLevel.WARN.
getMamaLogLevel() [1/2]
static MamaLogLevel com.wombat.mama.MamaLogLevel.getMamaLogLevel (int level) static
References com.wombat.mama.MamaLogLevel.ERROR, com.wombat.mama.MamaLogLevel.FINE, com.wombat.mama.MamaLogLevel.FINER, com.wombat.mama.MamaLogLevel.FINEST, com.wombat.mama.MamaLogLevel.NORMAL, com.wombat.mama.MamaLogLevel.OFF, com.wombat.mama.MamaLogLevel.SEVERE, and com.wombat.mama.MamaLogLevel.WARN.
Referenced by com.wombat.mama.Mama.enableLogging(), com.wombat.mama.Mama.getLogLevel(), and com.wombat.mama.Mama.getMamaLogLevelForLevel().
getMamaLogLevel() [2/2]
static MamaLogLevel com.wombat.mama.MamaLogLevel.getMamaLogLevel (Level level) static
References com.wombat.mama.MamaLogLevel.FINE, com.wombat.mama.MamaLogLevel.FINER, com.wombat.mama.MamaLogLevel.FINEST, com.wombat.mama.MamaLogLevel.NORMAL, com.wombat.mama.MamaLogLevel.OFF, com.wombat.mama.MamaLogLevel.SEVERE, and com.wombat.mama.MamaLogLevel.WARN.
getLevel()
static Level com.wombat.mama.MamaLogLevel.getLevel (MamaLogLevel mamalevel) static
References com.wombat.mama.MamaLogLevel.FINE, com.wombat.mama.MamaLogLevel.FINER, com.wombat.mama.MamaLogLevel.FINEST, com.wombat.mama.MamaLogLevel.NORMAL, com.wombat.mama.MamaLogLevel.OFF, com.wombat.mama.MamaLogLevel.SEVERE, and com.wombat.mama.MamaLogLevel.WARN.
Referenced by com.wombat.mama.Mama.getLogLevel().
Member Data Documentation
OFF
final MamaLogLevel com.wombat.mama.MamaLogLevel.OFF = new MamaLogLevel(0) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
SEVERE
final MamaLogLevel com.wombat.mama.MamaLogLevel.SEVERE = new MamaLogLevel(1) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
ERROR
final MamaLogLevel com.wombat.mama.MamaLogLevel.ERROR = new MamaLogLevel(2) static
Referenced by com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
WARN
final MamaLogLevel com.wombat.mama.MamaLogLevel.WARN = new MamaLogLevel(3) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
NORMAL
final MamaLogLevel com.wombat.mama.MamaLogLevel.NORMAL = new MamaLogLevel(4) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
FINE
final MamaLogLevel com.wombat.mama.MamaLogLevel.FINE = new MamaLogLevel(5) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
FINER
final MamaLogLevel com.wombat.mama.MamaLogLevel.FINER = new MamaLogLevel(6) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().
FINEST
final MamaLogLevel com.wombat.mama.MamaLogLevel.FINEST = new MamaLogLevel(7) static
Referenced by com.wombat.mama.MamaLogLevel.getLevel(), com.wombat.mama.MamaLogLevel.getMamaLogLevel(), and com.wombat.mama.MamaLogLevel.tryStringToLogLevel().