OpenMAMA Java API: com.wombat.mama.MamaMsgType Class Reference
com.wombat.mama.MamaMsgType Class Reference
A utility class for retrieving and interpreting type information from Mama Messages.
Static Public Member Functions
static short typeForMsg (final MamaMsg msg)
Extract the type from the supplied message.
static String stringForType (final MamaMsg msg)
Return the type name.
static String stringForType (final short type)
Return the type name.
Static Public Attributes
static final short TYPE_UPDATE = 0
general update (indices, funds).
static final short TYPE_INITIAL = 1
initial value.
static final short TYPE_CANCEL = 2
trade cancel.
static final short TYPE_ERROR = 3
trade error.
static final short TYPE_CORRECTION = 4
trade correction.
static final short TYPE_CLOSING = 5
closing summary.
static final short TYPE_RECAP = 6
refresh/recap of some/all fields.
static final short TYPE_DELETE = 7
symbol deleted.
static final short TYPE_EXPIRE = 8
expired.
static final short TYPE_SNAPSHOT = 9
full-record snapshot (no updates).
static final short TYPE_PREOPENING = 12
pre-opening summary.
static final short TYPE_QUOTE = 13
quote updates.
static final short TYPE_TRADE = 14
trade updates.
static final short TYPE_ORDER = 15
order updates.
static final short TYPE_BOOK_INITIAL = 16
order book initial.
static final short TYPE_BOOK_UPDATE = 17
order book update.
static final short TYPE_BOOK_CLEAR = 18
order book clear.
static final short TYPE_BOOK_RECAP = 19
order book recap.
static final short TYPE_BOOK_SNAPSHOT = 20
order book snapshot.
static final short TYPE_NOT_PERMISSIONED = 21
not permissioned (on feed).
static final short TYPE_NOT_FOUND = 22
not found (but may show up later).
static final short TYPE_END_OF_INITIALS = 23
end of group of initial values.
static final short TYPE_WOMBAT_REQUEST = 24
service request.
static final short TYPE_WOMBAT_CALC = 25
calculated result.
static final short TYPE_SEC_STATUS = 26
security status update
static final short TYPE_DDICT_SNAPSHOT = 50
data dictionary.
static final short TYPE_MISC = 100
miscellaneous.
static final short TYPE_PLATFORM = 101
static final short TYPE_FEATURE_SET = 150
static final short TYPE_FEATURE_SET_REQ = 151
static final short TYPE_SYNC_REQUEST = 170
static final short TYPE_REFRESH = 171
static final short TYPE_NULL = 175
static final short WV_REQUEST_SYMBOLOGIES = 180
static final short WV_REPLY_SYMBOLOGIES = 181
static final short WV_UPDATE_SYMBOLOGIES = 182
static final short WV_REQUEST_SOURCES = 183
static final short WV_REPLY_SOURCES = 184
static final short WV_UPDATE_SOURCES = 185
static final short WV_REQUEST_SOURCES_GROUPS = 186
static final short WV_REPLY_SOURCES_GROUPS = 187
static final short WV_UPDATE_SOURCES_GROUPS = 188
static final short WV_REQUEST_SYMBOL_RESOLUTION = 189
static final short WV_REPLY_SYMBOL_RESOLUTION = 190
Detailed Description
A utility class for retrieving and interpreting type information from Mama Messages.
Member Function Documentation
typeForMsg()
static short com.wombat.mama.MamaMsgType.typeForMsg (final MamaMsg msg) static
Extract the type from the supplied message.
Parameters
msg
Returns
The type.
References com.wombat.mama.MamaMsg.getI16(), com.wombat.mama.MamaReservedFields.getId(), com.wombat.mama.MamaReservedFields.getName(), and com.wombat.mama.MamaReservedFields.MsgType.
Referenced by com.wombat.mama.MamaMsgType.stringForType().
stringForType() [1/2]
static String com.wombat.mama.MamaMsgType.stringForType (final MamaMsg msg) static
Return the type name.
Returns
The type name.
References com.wombat.mama.MamaMsgType.typeForMsg().
stringForType() [2/2]
static String com.wombat.mama.MamaMsgType.stringForType (final short type) static
Return the type name.
Returns
The type name.
Member Data Documentation
TYPE_UPDATE
final short com.wombat.mama.MamaMsgType.TYPE_UPDATE = 0 static
general update (indices, funds).
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_INITIAL
final short com.wombat.mama.MamaMsgType.TYPE_INITIAL = 1 static
initial value.
TYPE_CANCEL
final short com.wombat.mama.MamaMsgType.TYPE_CANCEL = 2 static
trade cancel.
TYPE_ERROR
final short com.wombat.mama.MamaMsgType.TYPE_ERROR = 3 static
trade error.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_CORRECTION
final short com.wombat.mama.MamaMsgType.TYPE_CORRECTION = 4 static
trade correction.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_CLOSING
final short com.wombat.mama.MamaMsgType.TYPE_CLOSING = 5 static
closing summary.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_RECAP
final short com.wombat.mama.MamaMsgType.TYPE_RECAP = 6 static
refresh/recap of some/all fields.
TYPE_DELETE
final short com.wombat.mama.MamaMsgType.TYPE_DELETE = 7 static
symbol deleted.
TYPE_EXPIRE
final short com.wombat.mama.MamaMsgType.TYPE_EXPIRE = 8 static
expired.
(e.g. option, future).
TYPE_SNAPSHOT
final short com.wombat.mama.MamaMsgType.TYPE_SNAPSHOT = 9 static
full-record snapshot (no updates).
TYPE_PREOPENING
final short com.wombat.mama.MamaMsgType.TYPE_PREOPENING = 12 static
pre-opening summary.
(e.g. morning "roll").
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_QUOTE
final short com.wombat.mama.MamaMsgType.TYPE_QUOTE = 13 static
quote updates.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_TRADE
final short com.wombat.mama.MamaMsgType.TYPE_TRADE = 14 static
trade updates.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_ORDER
final short com.wombat.mama.MamaMsgType.TYPE_ORDER = 15 static
order updates.
TYPE_BOOK_INITIAL
final short com.wombat.mama.MamaMsgType.TYPE_BOOK_INITIAL = 16 static
order book initial.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_BOOK_UPDATE
final short com.wombat.mama.MamaMsgType.TYPE_BOOK_UPDATE = 17 static
order book update.
TYPE_BOOK_CLEAR
final short com.wombat.mama.MamaMsgType.TYPE_BOOK_CLEAR = 18 static
order book clear.
TYPE_BOOK_RECAP
final short com.wombat.mama.MamaMsgType.TYPE_BOOK_RECAP = 19 static
order book recap.
TYPE_BOOK_SNAPSHOT
final short com.wombat.mama.MamaMsgType.TYPE_BOOK_SNAPSHOT = 20 static
order book snapshot.
TYPE_NOT_PERMISSIONED
final short com.wombat.mama.MamaMsgType.TYPE_NOT_PERMISSIONED = 21 static
not permissioned (on feed).
TYPE_NOT_FOUND
final short com.wombat.mama.MamaMsgType.TYPE_NOT_FOUND = 22 static
not found (but may show up later).
TYPE_END_OF_INITIALS
final short com.wombat.mama.MamaMsgType.TYPE_END_OF_INITIALS = 23 static
end of group of initial values.
TYPE_WOMBAT_REQUEST
final short com.wombat.mama.MamaMsgType.TYPE_WOMBAT_REQUEST = 24 static
service request.
TYPE_WOMBAT_CALC
final short com.wombat.mama.MamaMsgType.TYPE_WOMBAT_CALC = 25 static
calculated result.
TYPE_SEC_STATUS
final short com.wombat.mama.MamaMsgType.TYPE_SEC_STATUS = 26 static
security status update
TYPE_DDICT_SNAPSHOT
final short com.wombat.mama.MamaMsgType.TYPE_DDICT_SNAPSHOT = 50 static
data dictionary.
TYPE_MISC
final short com.wombat.mama.MamaMsgType.TYPE_MISC = 100 static
miscellaneous.
Referenced by com.wombat.mama.MamaMdMsgType.compatMsgType().
TYPE_PLATFORM
final short com.wombat.mama.MamaMsgType.TYPE_PLATFORM = 101 static
TYPE_FEATURE_SET
final short com.wombat.mama.MamaMsgType.TYPE_FEATURE_SET = 150 static
TYPE_FEATURE_SET_REQ
final short com.wombat.mama.MamaMsgType.TYPE_FEATURE_SET_REQ = 151 static
TYPE_SYNC_REQUEST
final short com.wombat.mama.MamaMsgType.TYPE_SYNC_REQUEST = 170 static
TYPE_REFRESH
final short com.wombat.mama.MamaMsgType.TYPE_REFRESH = 171 static
TYPE_NULL
final short com.wombat.mama.MamaMsgType.TYPE_NULL = 175 static
WV_REQUEST_SYMBOLOGIES
final short com.wombat.mama.MamaMsgType.WV_REQUEST_SYMBOLOGIES = 180 static
WV_REPLY_SYMBOLOGIES
final short com.wombat.mama.MamaMsgType.WV_REPLY_SYMBOLOGIES = 181 static
WV_UPDATE_SYMBOLOGIES
final short com.wombat.mama.MamaMsgType.WV_UPDATE_SYMBOLOGIES = 182 static
WV_REQUEST_SOURCES
final short com.wombat.mama.MamaMsgType.WV_REQUEST_SOURCES = 183 static
WV_REPLY_SOURCES
final short com.wombat.mama.MamaMsgType.WV_REPLY_SOURCES = 184 static
WV_UPDATE_SOURCES
final short com.wombat.mama.MamaMsgType.WV_UPDATE_SOURCES = 185 static
WV_REQUEST_SOURCES_GROUPS
final short com.wombat.mama.MamaMsgType.WV_REQUEST_SOURCES_GROUPS = 186 static
WV_REPLY_SOURCES_GROUPS
final short com.wombat.mama.MamaMsgType.WV_REPLY_SOURCES_GROUPS = 187 static
WV_UPDATE_SOURCES_GROUPS
final short com.wombat.mama.MamaMsgType.WV_UPDATE_SOURCES_GROUPS = 188 static
WV_REQUEST_SYMBOL_RESOLUTION
final short com.wombat.mama.MamaMsgType.WV_REQUEST_SYMBOL_RESOLUTION = 189 static
WV_REPLY_SYMBOL_RESOLUTION
final short com.wombat.mama.MamaMsgType.WV_REPLY_SYMBOL_RESOLUTION = 190 static