OpenMAMA Java API: com.wombat.mama.MamaMsgField Class Reference
com.wombat.mama.MamaMsgField Class Reference
Wrapper class for the underlying mamaMsgField C structure.
Public Member Functions
long getPointerVal ()
native int getFid ()
native String getName ()
native short getType ()
native String getTypeName ()
native boolean getBoolean ()
native byte getI8 ()
native short getU8 ()
native char getChar ()
native short getI16 ()
native int getU16 ()
native int getI32 ()
native long getU32 ()
native long getI64 ()
native long getU64 ()
native float getF32 ()
native double getF64 ()
MamaDateTime getDateTime ()
MamaPrice getPrice ()
MamaMsg getMsg ()
native MamaFieldDescriptor getDescriptor ()
native String getString ()
native byte [] getOpaque ()
native byte [] getArrayI8 ()
native short [] getArrayU8 ()
native short [] getArrayI16 ()
native int [] getArrayU16 ()
native int [] getArrayI32 ()
native long [] getArrayU32 ()
native long [] getArrayI64 ()
native long [] getArrayU64 ()
native float [] getArrayF32 ()
native double [] getArrayF64 ()
native String [] getArrayString ()
native MamaMsg [] getArrayMsg ()
native String toString ()
native void destroy ()
Protected Member Functions
void setPointerVal (long pointerVal)
void finalize ()
Detailed Description
Wrapper class for the underlying mamaMsgField C structure.
Member Function Documentation
getPointerVal()
long com.wombat.mama.MamaMsgField.getPointerVal ()
Referenced by com.wombat.mama.MamaMsg.getField().
setPointerVal()
void com.wombat.mama.MamaMsgField.setPointerVal (long pointerVal) protected
References com.wombat.mama.MamaMsgField.getBoolean(), com.wombat.mama.MamaMsgField.getChar(), com.wombat.mama.MamaMsgField.getF32(), com.wombat.mama.MamaMsgField.getF64(), com.wombat.mama.MamaMsgField.getFid(), com.wombat.mama.MamaMsgField.getI16(), com.wombat.mama.MamaMsgField.getI32(), com.wombat.mama.MamaMsgField.getI64(), com.wombat.mama.MamaMsgField.getI8(), com.wombat.mama.MamaMsgField.getName(), com.wombat.mama.MamaMsgField.getType(), com.wombat.mama.MamaMsgField.getTypeName(), com.wombat.mama.MamaMsgField.getU16(), com.wombat.mama.MamaMsgField.getU32(), com.wombat.mama.MamaMsgField.getU64(), and com.wombat.mama.MamaMsgField.getU8().
Referenced by com.wombat.mama.MamaMsg.getField().
getFid()
native int com.wombat.mama.MamaMsgField.getFid ()
Referenced by com.wombat.mama.MamaMsgField.setPointerVal().
getName()
native String com.wombat.mama.MamaMsgField.getName ()
Referenced by com.wombat.mama.MamaMsgField.setPointerVal().
getType()
native short com.wombat.mama.MamaMsgField.getType ()
Referenced by com.wombat.mama.MamaMsgField.setPointerVal().
getTypeName()
native String com.wombat.mama.MamaMsgField.getTypeName ()
Referenced by com.wombat.mama.MamaMsgField.setPointerVal().
getBoolean()
native boolean com.wombat.mama.MamaMsgField.getBoolean ()
Referenced by com.wombat.mama.MamaMsgField.setPointerVal().
getI8()
native byte com.wombat.mama.MamaMsgField.getI8 ()
Referenced by com.wombat.mama.MamaMsg.getI8(), and com.wombat.mama.MamaMsgField.setPointerVal().
getU8()
native short com.wombat.mama.MamaMsgField.getU8 ()
Referenced by com.wombat.mama.MamaMsg.getU8(), and com.wombat.mama.MamaMsgField.setPointerVal().
getChar()
native char com.wombat.mama.MamaMsgField.getChar ()
Referenced by com.wombat.mama.MamaMsg.getChar(), and com.wombat.mama.MamaMsgField.setPointerVal().
getI16()
native short com.wombat.mama.MamaMsgField.getI16 ()
Referenced by com.wombat.mama.MamaMsg.getI16(), and com.wombat.mama.MamaMsgField.setPointerVal().
getU16()
native int com.wombat.mama.MamaMsgField.getU16 ()
Referenced by com.wombat.mama.MamaMsg.getU16(), and com.wombat.mama.MamaMsgField.setPointerVal().
getI32()
native int com.wombat.mama.MamaMsgField.getI32 ()
Referenced by com.wombat.mama.MamaMsg.getI32(), and com.wombat.mama.MamaMsgField.setPointerVal().
getU32()
native long com.wombat.mama.MamaMsgField.getU32 ()
Referenced by com.wombat.mama.MamaMsg.getU32(), and com.wombat.mama.MamaMsgField.setPointerVal().
getI64()
native long com.wombat.mama.MamaMsgField.getI64 ()
Referenced by com.wombat.mama.MamaMsg.getI64(), and com.wombat.mama.MamaMsgField.setPointerVal().
getU64()
native long com.wombat.mama.MamaMsgField.getU64 ()
Referenced by com.wombat.mama.MamaMsg.getU64(), and com.wombat.mama.MamaMsgField.setPointerVal().
getF32()
native float com.wombat.mama.MamaMsgField.getF32 ()
Referenced by com.wombat.mama.MamaMsg.getF32(), and com.wombat.mama.MamaMsgField.setPointerVal().
getF64()
native double com.wombat.mama.MamaMsgField.getF64 ()
Referenced by com.wombat.mama.MamaMsg.getF64(), and com.wombat.mama.MamaMsgField.setPointerVal().
getDateTime()
MamaDateTime com.wombat.mama.MamaMsgField.getDateTime ()
References com.wombat.mama.MamaDateTime.getPointerVal().
getPrice()
MamaPrice com.wombat.mama.MamaMsgField.getPrice ()
References com.wombat.mama.MamaPrice.getPointerVal().
Referenced by com.wombat.mama.MamaMsg.getPrice().
getMsg()
MamaMsg com.wombat.mama.MamaMsgField.getMsg ()
References com.wombat.mama.MamaMsgField.destroy(), com.wombat.mama.MamaMsgField.getArrayF32(), com.wombat.mama.MamaMsgField.getArrayF64(), com.wombat.mama.MamaMsgField.getArrayI16(), com.wombat.mama.MamaMsgField.getArrayI32(), com.wombat.mama.MamaMsgField.getArrayI64(), com.wombat.mama.MamaMsgField.getArrayI8(), com.wombat.mama.MamaMsgField.getArrayMsg(), com.wombat.mama.MamaMsgField.getArrayString(), com.wombat.mama.MamaMsgField.getArrayU16(), com.wombat.mama.MamaMsgField.getArrayU32(), com.wombat.mama.MamaMsgField.getArrayU64(), com.wombat.mama.MamaMsgField.getArrayU8(), com.wombat.mama.MamaMsgField.getDescriptor(), com.wombat.mama.MamaMsgField.getOpaque(), com.wombat.mama.MamaMsgField.getString(), and com.wombat.mama.MamaMsgField.toString().
Referenced by com.wombat.mama.MamaMsg.getMsg(), and com.wombat.mama.MamaMsg.tryMsg().
getDescriptor()
native MamaFieldDescriptor com.wombat.mama.MamaMsgField.getDescriptor ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getString()
native String com.wombat.mama.MamaMsgField.getString ()
Referenced by com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsg.getString().
getOpaque()
native byte [] com.wombat.mama.MamaMsgField.getOpaque ()
Referenced by com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsg.tryOpaque().
getArrayI8()
native byte [] com.wombat.mama.MamaMsgField.getArrayI8 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayU8()
native short [] com.wombat.mama.MamaMsgField.getArrayU8 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayI16()
native short [] com.wombat.mama.MamaMsgField.getArrayI16 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayU16()
native int [] com.wombat.mama.MamaMsgField.getArrayU16 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsg.tryArrayU16().
getArrayI32()
native int [] com.wombat.mama.MamaMsgField.getArrayI32 ()
Referenced by com.wombat.mama.MamaMsg.getArrayI32(), com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsg.tryArrayI32().
getArrayU32()
native long [] com.wombat.mama.MamaMsgField.getArrayU32 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayI64()
native long [] com.wombat.mama.MamaMsgField.getArrayI64 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayU64()
native long [] com.wombat.mama.MamaMsgField.getArrayU64 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayF32()
native float [] com.wombat.mama.MamaMsgField.getArrayF32 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayF64()
native double [] com.wombat.mama.MamaMsgField.getArrayF64 ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
getArrayString()
native String [] com.wombat.mama.MamaMsgField.getArrayString ()
Referenced by com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsg.tryArrayString().
getArrayMsg()
native MamaMsg [] com.wombat.mama.MamaMsgField.getArrayMsg ()
Referenced by com.wombat.mama.MamaMsg.getArrayMsg(), com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsg.tryArrayMsg().
toString()
native String com.wombat.mama.MamaMsgField.toString ()
Referenced by com.wombat.mama.MamaMsgField.getMsg().
destroy()
native void com.wombat.mama.MamaMsgField.destroy ()
Referenced by com.wombat.mama.MamaMsgField.finalize(), com.wombat.mama.MamaMsgField.getMsg(), and com.wombat.mama.MamaMsgIterator.remove().
finalize()
void com.wombat.mama.MamaMsgField.finalize () protected
References com.wombat.mama.MamaMsgField.destroy().