OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookEntryManager Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookEntryManager Class Reference
Public Member Functions
MamdaOrderBookEntryManager (int approxCount)
Default constructor.
void clear ()
Clear all entries from the manager.
void clear (String symbol)
Clear all entries for a particular symbol from the manager.
void addEntry (MamdaOrderBookEntry entry)
Add an entry to the manager.
void addEntry (MamdaOrderBookEntry entry, String entryId)
Add an entry to the manager using a specific entry ID, which may be different from the entry's entry ID.
MamdaOrderBookEntry findEntry (String entryId, boolean mustExist)
Find an entry in the manager.
void removeEntry (String entryId)
Remove an entry from the manager.
Constructor & Destructor Documentation
MamdaOrderBookEntryManager()
com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.MamdaOrderBookEntryManager (int approxCount)
Default constructor.
Create an empty order book entry manager.
Parameters
approxCount Approximate number of entries.
Member Function Documentation
clear() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.clear ()
Clear all entries from the manager.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
clear() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.clear (String symbol)
Clear all entries for a particular symbol from the manager.
Parameters
symbol the symbol.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSymbol().
addEntry() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.addEntry (MamdaOrderBookEntry entry)
Add an entry to the manager.
This method may throw a MamdaOrderBookDuplicateEntry exception.
Parameters
entry the entry to add.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
addEntry() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.addEntry (MamdaOrderBookEntry entry, String entryId)
Add an entry to the manager using a specific entry ID, which may be different from the entry's entry ID.
This method may throw a MamdaOrderBookDuplicateEntry exception.
Parameters
entry the entry to add.
entryId the entry id to use.
findEntry()
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.findEntry (String entryId, boolean mustExist)
Find an entry in the manager.
If no entry matches the unique entry ID and "mustExist" is true then a MamdaOrderBookMissingEntryException exception is thrown, otherwise it returns NULL.
Returns
the entry if found.
Parameters
entryId The entry id to search for.
mustExist true if the entry must exist.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
removeEntry()
void com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry (String entryId)
Remove an entry from the manager.
This method does not actually delete the MamdaOrderBookEntry object itself.
Parameters
entryId the id for the entry to be removed.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPrice(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSymbol().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().