OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionExpirationDateSet Class Reference
com.wombat.mamda.options.MamdaOptionExpirationDateSet Class Reference
A class that represents a set of expiration dates, each of which contains a set of strike prices (MamdaOptionStrikeSet), each of which contains a set of option contracts (MamdaOptionContractSet), each of which contains exchange-specific contracts.
Inherits TreeMap.
Public Member Functions
MamdaOptionExpirationDateSet ()
MamdaOptionExpirationDateSet (MamdaOptionExpirationDateSet copy)
MamdaOptionExpirationDateSet getExpirationsBefore (Date date)
MamdaOptionExpirationDateSet getExpirations (int numExpirations)
String toString ()
Protected Member Functions
MamdaOptionExpirationDateSet (SortedMap map)
Detailed Description
A class that represents a set of expiration dates, each of which contains a set of strike prices (MamdaOptionStrikeSet), each of which contains a set of option contracts (MamdaOptionContractSet), each of which contains exchange-specific contracts.
To access a set of strike prices for a given expiration date, use the get method (inherited from TreeMap).
Constructor & Destructor Documentation
MamdaOptionExpirationDateSet() [1/3]
com.wombat.mamda.options.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet ()
Referenced by com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirations(), and com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirationsBefore().
MamdaOptionExpirationDateSet() [2/3]
com.wombat.mamda.options.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet (MamdaOptionExpirationDateSet copy)
MamdaOptionExpirationDateSet() [3/3]
com.wombat.mamda.options.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet (SortedMap map) protected
Member Function Documentation
getExpirationsBefore()
MamdaOptionExpirationDateSet com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirationsBefore (Date date)
References com.wombat.mamda.options.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet().
Referenced by com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirations(), and com.wombat.mamda.options.MamdaOptionChainView.onOptionSeriesUpdate().
getExpirations()
MamdaOptionExpirationDateSet com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirations (int numExpirations)
References com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirationsBefore(), and com.wombat.mamda.options.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet().
Referenced by com.wombat.mamda.options.MamdaOptionChainView.onOptionSeriesUpdate().
toString()
String com.wombat.mamda.options.MamdaOptionExpirationDateSet.toString ()