OpenMAMDA Java API: com.wombat.mamda.MamdaFieldState Class Reference
com.wombat.mamda.MamdaFieldState Class Reference
An enumeration representing field state.
Public Member Functions
void setState (short state)
short getState ()
Static Public Member Functions
static String toString (short fieldState)
Convert a MamdaFieldState to an appropriate, displayable string.
Static Public Attributes
static final short NOT_INITIALISED = 0
static final short NOT_MODIFIED = 1
static final short MODIFIED = 2
Detailed Description
An enumeration representing field state.
MODIFIED (0) value indicates the field was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (2) value indicates that the field has never been updated
Member Function Documentation
toString()
static String com.wombat.mamda.MamdaFieldState.toString (short fieldState) static
Convert a MamdaFieldState to an appropriate, displayable string.
Parameters
fieldState The Field State as a short.
setState()
void com.wombat.mamda.MamdaFieldState.setState (short state)
Referenced by com.wombat.mamda.MamdaAuctionListener.clearCache(), com.wombat.mamda.MamdaTradeListener.clearCache(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.MamdaAuctionListener.onMsg(), com.wombat.mamda.MamdaFundamentalListener.onMsg(), com.wombat.mamda.MamdaQuoteListener.onMsg(), and com.wombat.mamda.MamdaTradeListener.onMsg().
getState()
short com.wombat.mamda.MamdaFieldState.getState ()
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getActivityTimeFieldState(), com.wombat.mamda.MamdaAuctionListener.getActivityTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getActivityTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getActivityTimeFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getActivityTimeFieldState(), com.wombat.mamda.MamdaQuoteListener.getBeginGapSeqNumFieldState(), com.wombat.mamda.MamdaTradeListener.getBeginGapSeqNumFieldState(), com.wombat.mamda.MamdaFundamentalListener.getCorporateActionTypeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getDividendCurrencyFieldState(), com.wombat.mamda.MamdaFundamentalListener.getDividendExDateFieldState(), com.wombat.mamda.MamdaFundamentalListener.getDividendFrequencyFieldState(), com.wombat.mamda.MamdaFundamentalListener.getDividendPayDateFieldState(), com.wombat.mamda.MamdaFundamentalListener.getDividendPriceFieldState(), com.wombat.mamda.MamdaFundamentalListener.getDividendRecordDateFieldState(), com.wombat.mamda.MamdaFundamentalListener.getEarningsPerShareFieldState(), com.wombat.mamda.MamdaQuoteListener.getEndGapSeqNumFieldState(), com.wombat.mamda.MamdaTradeListener.getEndGapSeqNumFieldState(), com.wombat.mamda.options.MamdaOptionChainListener.getEventSeqNumFieldState(), com.wombat.mamda.MamdaAuctionListener.getEventSeqNumFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNumFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEventSeqNumFieldState(), com.wombat.mamda.options.MamdaOptionChainListener.getEventTimeFieldState(), com.wombat.mamda.MamdaAuctionListener.getEventTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventTimeFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEventTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getHistoricalVolatilityFieldState(), com.wombat.mamda.MamdaTradeListener.getIsIndicativeFieldState(), com.wombat.mamda.MamdaAuctionListener.getIssueSymbolFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getLineTimeFieldState(), com.wombat.mamda.MamdaAuctionListener.getLineTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getLineTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getLineTimeFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getLineTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getMarketSectorFieldState(), com.wombat.mamda.MamdaFundamentalListener.getMarketSectorNativeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getMarketSegmentFieldState(), com.wombat.mamda.MamdaFundamentalListener.getMarketSegmentNativeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getPartIdFieldState(), com.wombat.mamda.MamdaFundamentalListener.getPartIdFieldState(), com.wombat.mamda.MamdaAuctionListener.getPartIdFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getPartIdFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPartIdFieldState(), com.wombat.mamda.MamdaFundamentalListener.getPriceEarningsRatioFieldState(), com.wombat.mamda.MamdaFundamentalListener.getRiskFreeRateFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getSendTimeFieldState(), com.wombat.mamda.MamdaAuctionListener.getSendTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getSendTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getSendTimeFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSendTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getSharesAuthorizedFieldState(), com.wombat.mamda.MamdaFundamentalListener.getSharesFloatFieldState(), com.wombat.mamda.MamdaFundamentalListener.getSharesOutFieldState(), com.wombat.mamda.options.MamdaOptionChainListener.getSrcTimeFieldState(), com.wombat.mamda.MamdaAuctionListener.getSrcTimeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getSrcTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getSrcTimeFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSrcTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getSymbolFieldState(), com.wombat.mamda.MamdaFundamentalListener.getSymbolFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getSymbolFieldState(), com.wombat.mamda.MamdaAuctionListener.getSymbolFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSymbolFieldState(), com.wombat.mamda.MamdaAuctionListener.getUncrossPriceFieldState(), com.wombat.mamda.MamdaAuctionListener.getUncrossPriceIndFieldState(), com.wombat.mamda.MamdaAuctionListener.getUncrossVolumeFieldState(), com.wombat.mamda.MamdaFundamentalListener.getVolatilityFieldState(), com.wombat.mamda.MamdaFundamentalListener.getYieldFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.MamdaAuctionListener.onMsg(), com.wombat.mamda.MamdaFundamentalListener.onMsg(), com.wombat.mamda.MamdaQuoteListener.onMsg(), and com.wombat.mamda.MamdaTradeListener.onMsg().
Member Data Documentation
NOT_INITIALISED
final short com.wombat.mamda.MamdaFieldState.NOT_INITIALISED = 0 static
Referenced by com.wombat.mamda.MamdaAuctionListener.clearCache(), com.wombat.mamda.MamdaOrderImbalanceListener.clearCache(), com.wombat.mamda.MamdaSecurityStatusListener.clearCache(), com.wombat.mamda.MamdaQuoteListener.clearCache(), com.wombat.mamda.MamdaTradeListener.clearCache(), com.wombat.mamda.MamdaSecurityStatusListener.getFieldAsString(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.MamdaQuoteListener.onMsg().
NOT_MODIFIED
final short com.wombat.mamda.MamdaFieldState.NOT_MODIFIED = 1 static
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg(), com.wombat.mamda.MamdaFundamentalListener.onMsg(), com.wombat.mamda.MamdaSecurityStatusListener.onMsg(), com.wombat.mamda.MamdaOrderImbalanceListener.onMsg(), com.wombat.mamda.MamdaQuoteListener.onMsg(), and com.wombat.mamda.MamdaTradeListener.onMsg().
MODIFIED
final short com.wombat.mamda.MamdaFieldState.MODIFIED = 2 static
Referenced by com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTimeFieldState(), com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNumFieldState(), com.wombat.mamda.MamdaConcreteBasicEvent.getEventTimeFieldState(), com.wombat.mamda.MamdaSecurityStatusListener.getFieldAsString(), com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTimeFieldState(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.MamdaAuctionListener.onMsg(), com.wombat.mamda.MamdaFundamentalListener.onMsg(), com.wombat.mamda.MamdaSecurityStatusListener.onMsg(), com.wombat.mamda.MamdaOrderImbalanceListener.onMsg(), com.wombat.mamda.MamdaQuoteListener.onMsg(), and com.wombat.mamda.MamdaTradeListener.onMsg().