OpenMAMDA Java API: com.wombat.mamda.MamdaUncrossPriceInd Class Reference
com.wombat.mamda.MamdaUncrossPriceInd Class Reference
Public Member Functions
void set (short ind)
short get ()
Static Public Member Functions
static String toString (short ind)
Convert a MamdaUncrossPriceInd to an appropriate, displayable string.
static short mamdaUncrossPriceIndFromString (String uncrossPriceInd)
Static Public Attributes
static final short UNCROSS_NONE = 0
static final short UNCROSS_INDICATIVE = 1
static final short UNCROSS_FIRM = 2
static final short UNCROSS_INSUFFICIENT_VOL = 3
Member Function Documentation
toString()
static String com.wombat.mamda.MamdaUncrossPriceInd.toString (short ind) static
Convert a MamdaUncrossPriceInd to an appropriate, displayable string.
Parameters
ind The price Ind as a short.
set()
void com.wombat.mamda.MamdaUncrossPriceInd.set (short ind)
Referenced by com.wombat.mamda.MamdaAuctionListener.clearCache(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
get()
short com.wombat.mamda.MamdaUncrossPriceInd.get ()
Referenced by com.wombat.mamda.MamdaAuctionListener.getUncrossPriceInd().
mamdaUncrossPriceIndFromString()
static short com.wombat.mamda.MamdaUncrossPriceInd.mamdaUncrossPriceIndFromString (String uncrossPriceInd) static
References com.wombat.mamda.MamdaUncrossPriceInd.UNCROSS_NONE.
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
Member Data Documentation
UNCROSS_NONE
final short com.wombat.mamda.MamdaUncrossPriceInd.UNCROSS_NONE = 0 static
Referenced by com.wombat.mamda.MamdaAuctionListener.clearCache(), and com.wombat.mamda.MamdaUncrossPriceInd.mamdaUncrossPriceIndFromString().
UNCROSS_INDICATIVE
final short com.wombat.mamda.MamdaUncrossPriceInd.UNCROSS_INDICATIVE = 1 static
UNCROSS_FIRM
final short com.wombat.mamda.MamdaUncrossPriceInd.UNCROSS_FIRM = 2 static
UNCROSS_INSUFFICIENT_VOL
final short com.wombat.mamda.MamdaUncrossPriceInd.UNCROSS_INSUFFICIENT_VOL = 3 static