OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta Class Reference
MamdaOrderBookConcreteSimpleDelta is a class that saves information about a simple order book delta.
Inherits com.wombat.mamda.orderbook.MamdaOrderBookSimpleDelta.
Public Member Functions
MamaDateTime getSrcTime ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setSrcTime (MamaDateTime srcTime)
MamaDateTime getActivityTime ()
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setActivityTime (MamaDateTime activityTime)
MamaDateTime getEventTime ()
short getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setEventTime (MamaDateTime eventTime)
long getEventSeqNum ()
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setEventSeqNum (long eventSeqNum)
Public Member Functions inherited from com.wombat.mamda.orderbook.MamdaOrderBookSimpleDelta
MamdaOrderBookSimpleDelta ()
MamdaOrderBookSimpleDelta (MamdaOrderBookSimpleDelta copy)
Public Member Functions inherited from com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta
MamdaOrderBookBasicDelta ()
MamdaOrderBookBasicDelta (MamdaOrderBookBasicDelta source)
void clear ()
Clear the delta.
void set (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
Set the delta info.
void setPriceLevel (MamdaOrderBookPriceLevel level)
Set the MamdaOrderBookPriceLevel object to which this entry belongs.
void setPlDeltaAction (char action)
Set the delta action with respect to the price level.
MamdaOrderBookPriceLevel getPriceLevel ()
Get the MamdaOrderBookPriceLevel object related to this basic delta.
MamdaOrderBookEntry getEntry ()
Get the MamdaOrderBookEntry object related to this basic delta.
double getPlDeltaSize ()
Get the difference in size for the price level.
char getPlDeltaAction ()
Get the delta action with respect to the price level.
char getEntryDeltaAction ()
Get the delta action with respect to the entry.
MamdaOrderBook getOrderBook ()
Get the MamdaOrderBook object to which this delta belongs.
void dump (OutputStream output)
Dump the simple update to the output stream.
void dump ()
Dump the simple update to the output stream.
Detailed Description
MamdaOrderBookConcreteSimpleDelta is a class that saves information about a simple order book delta.
A simple delta is one that affects a single order book entry.
Member Function Documentation
getSrcTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTime().
getSrcTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTimeFieldState().
setSrcTime()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setSrcTime (MamaDateTime srcTime)
References com.wombat.mamda.MamdaConcreteBasicEvent.setSrcTime().
getActivityTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTime().
getActivityTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTimeFieldState().
setActivityTime()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setActivityTime (MamaDateTime activityTime)
References com.wombat.mamda.MamdaConcreteBasicEvent.setActivityTime().
getEventTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventTime().
getEventTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventTimeFieldState().
setEventTime()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setEventTime (MamaDateTime eventTime)
References com.wombat.mamda.MamdaConcreteBasicEvent.setEventTime().
getEventSeqNum()
long com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNum().
getEventSeqNumFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNumFieldState().
setEventSeqNum()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setEventSeqNum (long eventSeqNum)
References com.wombat.mamda.MamdaConcreteBasicEvent.setEventSeqNum().