OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionChainView Class Reference
com.wombat.mamda.options.MamdaOptionChainView Class Reference
A class that represents a "view" of a subset of an option chain.
Inherits com.wombat.mamda.options.MamdaOptionChainHandler.
Public Member Functions
MamdaOptionChainView (MamdaOptionChain chain)
Create a view on the given option chain.
String getSymbol ()
Return the symbol for the option chain.
void setAtTheMoneyType (short atTheMoneyType)
Set how the underlying price ("at the money") is determined (.
void setStrikeRangePercent (double percentMargin)
Set the range of strike prices to be included in the view by percentage variation from the underlying price.
void setStrikeRangeNumber (int number)
Set the number of strike prices to be included in the view.
void setExpirationRangeDays (int expirationDays)
Set the range of expiration dates to be included in the view by the maximum number of days until expiration.
void setNumberOfExpirations (int numExpirations)
Set the number of expiration dates to be included in the view.
void setJitterMargin (double percentMargin)
Set a "jitter margin" to avoid having the range jump between different strike prices when the underlying price hovers right on the edge of a range boundary.
boolean isVisible (MamdaOptionContract contract)
Return whether an option contract falls within this view's parameters.
Iterator expirationIterator ()
Return an Iterator over the set of expiration dates within the view.
void onOptionChainRecap (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionChain chain)
Handler option chain recaps and initial values.
void onOptionContractCreate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionContract contract, MamdaOptionChain chain)
Handler for option chain structural updates.
void onOptionSeriesUpdate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionSeriesUpdate event, MamdaOptionChain chain)
Handler for option chain structural updates.
Detailed Description
A class that represents a "view" of a subset of an option chain.
The view can be restricted to a percentage or number of strike prices around "the money" as well as to a maximum number of days into the future. The view will be adjusted to include strike prices within the range as the underlying price moves. This means that the range of strike prices will change over time. In order to avoid a "jitter" in the range of strike prices when the underlying price hovers right on the edge of a range boundary, the class also provides a "jitter margin" as some percentage of the underlying price (default is 0.5%).
Constructor & Destructor Documentation
MamdaOptionChainView()
com.wombat.mamda.options.MamdaOptionChainView.MamdaOptionChainView (MamdaOptionChain chain)
Create a view on the given option chain.
Multiple views are supported on any given option chain.
Member Function Documentation
getSymbol()
String com.wombat.mamda.options.MamdaOptionChainView.getSymbol ()
Return the symbol for the option chain.
References com.wombat.mamda.options.MamdaOptionChain.getSymbol().
setAtTheMoneyType()
void com.wombat.mamda.options.MamdaOptionChainView.setAtTheMoneyType (short atTheMoneyType)
Set how the underlying price ("at the money") is determined (.
See also
MamdaOptionAtTheMoneyCompareType).
setStrikeRangePercent()
void com.wombat.mamda.options.MamdaOptionChainView.setStrikeRangePercent (double percentMargin)
Set the range of strike prices to be included in the view by percentage variation from the underlying price.
The range of strike prices in the view will vary as the underlying varies. The "jitter margin" avoids switching between ranges too often.
setStrikeRangeNumber()
void com.wombat.mamda.options.MamdaOptionChainView.setStrikeRangeNumber (int number)
Set the number of strike prices to be included in the view.
The "jitter margin" avoids switching between ranges too often.
setExpirationRangeDays()
void com.wombat.mamda.options.MamdaOptionChainView.setExpirationRangeDays (int expirationDays)
Set the range of expiration dates to be included in the view by the maximum number of days until expiration.
Note: a non-zero range overrides a specific number of expirations set by setNumberOfExpirations().
setNumberOfExpirations()
void com.wombat.mamda.options.MamdaOptionChainView.setNumberOfExpirations (int numExpirations)
Set the number of expiration dates to be included in the view.
Note: a non-zero range (set by setExpirationRangeDays()) overrides a specific number of expirations.
setJitterMargin()
void com.wombat.mamda.options.MamdaOptionChainView.setJitterMargin (double percentMargin)
Set a "jitter margin" to avoid having the range jump between different strike prices when the underlying price hovers right on the edge of a range boundary.
The underlying is allowed to fluctuate within the jitter margin without the range being reset. When the underlying moves beyond the jitter margin, the range is reset.
isVisible()
boolean com.wombat.mamda.options.MamdaOptionChainView.isVisible (MamdaOptionContract contract)
Return whether an option contract falls within this view's parameters.
References com.wombat.mamda.options.MamdaOptionContract.getExpireDate(), and com.wombat.mamda.options.MamdaOptionContract.getStrikePrice().
expirationIterator()
Iterator com.wombat.mamda.options.MamdaOptionChainView.expirationIterator ()
Return an Iterator over the set of expiration dates within the view.
Each Iterator represents a MamdaOptionExpirationStrikes object.
onOptionChainRecap()
void com.wombat.mamda.options.MamdaOptionChainView.onOptionChainRecap (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionChain chain)
Handler option chain recaps and initial values.
Implements com.wombat.mamda.options.MamdaOptionChainHandler.
onOptionContractCreate()
void com.wombat.mamda.options.MamdaOptionChainView.onOptionContractCreate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionContract contract, MamdaOptionChain chain)
Handler for option chain structural updates.
Implements com.wombat.mamda.options.MamdaOptionChainHandler.
onOptionSeriesUpdate()
void com.wombat.mamda.options.MamdaOptionChainView.onOptionSeriesUpdate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionSeriesUpdate event, MamdaOptionChain chain)
Handler for option chain structural updates.
Implements com.wombat.mamda.options.MamdaOptionChainHandler.
References com.wombat.mamda.options.MamdaOptionChain.getAllExpirations(), com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirations(), com.wombat.mamda.options.MamdaOptionExpirationDateSet.getExpirationsBefore(), com.wombat.mamda.options.MamdaOptionChain.getStrikesWithinPercent(), com.wombat.mamda.options.MamdaOptionChain.getStrikesWithinRangeSize(), and com.wombat.mamda.options.MamdaOptionExpirationStrikes.trimStrikes().