OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookListener Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookListener Class Reference
MamdaOrderBookListener is a class that specializes in handling order book updates.
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.orderbook.MamdaOrderBookClear, com.wombat.mamda.orderbook.MamdaOrderBookRecap, and com.wombat.mamda.orderbook.MamdaOrderBookGap.
Public Member Functions
MamdaOrderBookListener ()
Create an order book listener using internally created data structures for the full and delta order books.
MamdaOrderBookListener (MamdaOrderBook fullBook)
Create an order book listener using an optional user-provided object for the full order book.
void addHandler (MamdaOrderBookHandler handler)
Add a specialized order book handler.
void addIgnoreEntryId (String id)
Add an entry ID to ignore.
void removeIgnoreEntryId (String id)
Remove an entry ID to ignore.
void clear ()
Clear all cached data fields.
String getSymbol ()
Get the string symbol for the instrument.
String getPartId ()
Get the participant identifier.
MamaDateTime getSrcTime ()
MamaDateTime getActivityTime ()
long getEventSeqNum ()
MamaDateTime getEventTime ()
MamaDateTime getLineTime ()
Get the line time of the update.
MamaDateTime getSendTime ()
Get the send time of the update.
short getMsgQual ()
MamdaOrderBook getOrderBook ()
Returns the full orderbook related to this clear event.
long getBeginGapSeqNum ()
Beginning sequence number in a detected gap event.
long getEndGapSeqNum ()
Ending sequence number in a detected gap event.
void setProcessMarketOrders (boolean process)
boolean getProcessMarketOrders ()
short getSymbolFieldState ()
short getPartIdFieldState ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getLineTimeFieldState ()
short getSendTimeFieldState ()
short getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setProcessEntries (boolean process)
Set whether we are interested in "entry level" information at all.
MamdaOrderBook getBookSnapshot ()
Returns a deep, writeable copy of the underlying order book.
MamdaOrderBook getReadOnlyBookSnapshot ()
Returns a deep, read only, copy of the underlying order book.
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Static Public Member Functions
static MamdaOrderBook getBookSnapShot (String symbol)
Detailed Description
MamdaOrderBookListener is a class that specializes in handling order book updates.
Developers provide their own implementation of the MamdaOrderBookHandler interface and will be delivered notifications for order book recaps and deltas. Notifications for order book deltas include the delta itself as well as the full order book with deltas applied. An obvious application for this MAMDA class is any kind of program trading application that looks at depth of book.
Note: The MamdaOrderBookListener class caches the order book. Among other reasons, caching of these fields makes it possible to provide complete trade-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaOrderBookListener() [1/2]
com.wombat.mamda.orderbook.MamdaOrderBookListener.MamdaOrderBookListener ()
Create an order book listener using internally created data structures for the full and delta order books.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapShot().
MamdaOrderBookListener() [2/2]
com.wombat.mamda.orderbook.MamdaOrderBookListener.MamdaOrderBookListener (MamdaOrderBook fullBook)
Create an order book listener using an optional user-provided object for the full order book.
If "fullBook" is NULL, an object will be allocated internally. If this listener is destroyed then the full order book object will only be destroyed if it was created by the listener (i.e., if fullBook was passed as NULL in this constructor).
Parameters
fullBook The MamdaOrderBook used to maintain the full book.
Member Function Documentation
addHandler()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.addHandler (MamdaOrderBookHandler handler)
Add a specialized order book handler.
Currently, only one handler can (and must) be registered.
Parameters
handler The hadler registered to receive order book update callbacks.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.getFailureCount().
addIgnoreEntryId()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.addIgnoreEntryId (String id)
Add an entry ID to ignore.
This only makes sense when the entry type is participant ID (as opposed to order ID). All order book updates for this entry ID will be ignored.
Parameters
id The id of the participant to ignore when process book updates.
removeIgnoreEntryId()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.removeIgnoreEntryId (String id)
Remove an entry ID to ignore.
Parameters
id The id of the participant whose update will be subsequently processed as part of the book.
See also
addIgnoreEntryId(String)
clear()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.clear ()
Clear all cached data fields.
References com.wombat.mamda.locks.MamdaLock.acquireWriteLock(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.clear(), com.wombat.mamda.orderbook.MamdaOrderBook.clear(), and com.wombat.mamda.locks.MamdaLock.releaseWriteLock().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNumFieldState(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getSymbol()
String com.wombat.mamda.orderbook.MamdaOrderBookListener.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.orderbook.MamdaOrderBook.getSymbol().
getPartId()
String com.wombat.mamda.orderbook.MamdaOrderBookListener.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getSrcTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookListener.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getActivityTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getEventSeqNum()
long com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getEventTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getLineTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookListener.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookListener.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getMsgQual()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getMsgQual ()
getOrderBook()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookListener.getOrderBook ()
Returns the full orderbook related to this clear event.
Returns
The full order book.
Implements com.wombat.mamda.orderbook.MamdaOrderBookClear.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getBeginGapSeqNum()
long com.wombat.mamda.orderbook.MamdaOrderBookListener.getBeginGapSeqNum ()
Beginning sequence number in a detected gap event.
Implements com.wombat.mamda.orderbook.MamdaOrderBookGap.
getEndGapSeqNum()
long com.wombat.mamda.orderbook.MamdaOrderBookListener.getEndGapSeqNum ()
Ending sequence number in a detected gap event.
Implements com.wombat.mamda.orderbook.MamdaOrderBookGap.
setProcessMarketOrders()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.setProcessMarketOrders (boolean process)
getProcessMarketOrders()
boolean com.wombat.mamda.orderbook.MamdaOrderBookListener.getProcessMarketOrders ()
getSymbolFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getPartIdFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSrcTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getActivityTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getLineTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSendTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getEventTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getEventSeqNumFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), com.wombat.mamda.orderbook.MamdaOrderBook.getQuality(), com.wombat.mamda.MamdaFieldState.getState(), and com.wombat.mamda.orderbook.MamdaOrderBook.setQuality().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setProcessEntries()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.setProcessEntries (boolean process)
Set whether we are interested in "entry level" information at all.
Many applications only care about price level information. (Default is to process entry level information.)
Parameters
process Whether to process entries in books.
getBookSnapshot()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapshot ()
Returns a deep, writeable copy of the underlying order book.
Returns
A snapshot of the current Order Book
References com.wombat.mamda.locks.MamdaLock.acquireWriteLock(), com.wombat.mamda.orderbook.MamdaOrderBook.copy(), and com.wombat.mamda.locks.MamdaLock.releaseWriteLock().
getBookSnapShot()
static MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapShot (String symbol) static
References com.wombat.mamda.locks.MamdaLock.acquireWriteLock(), com.wombat.mamda.orderbook.MamdaOrderBookListener.MamdaOrderBookListener(), and com.wombat.mamda.locks.MamdaLock.releaseWriteLock().
getReadOnlyBookSnapshot()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookListener.getReadOnlyBookSnapshot ()
Returns a deep, read only, copy of the underlying order book.
This method is faster than the writeable getBookSnapshot.
Returns
A deep snapshot of the current Order Book
References com.wombat.mamda.locks.MamdaLock.acquireWriteLock(), com.wombat.mamda.orderbook.MamdaOrderBook.copyReadOnly(), and com.wombat.mamda.locks.MamdaLock.releaseWriteLock().
onMsg()
void com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.locks.MamdaLock.acquireWriteLock(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UNKNOWN, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UPDATE, com.wombat.mamda.MamdaCommonFields.ACTIVITY_TIME, com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.add(), com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookFields.ASK_MARKET_ORDERS, com.wombat.mamda.orderbook.MamdaOrderBookFields.BID_MARKET_ORDERS, com.wombat.mamda.orderbook.MamdaOrderBookFields.BOOK_PROP_MSG_TYPE, com.wombat.mamda.orderbook.MamdaOrderBookFields.BOOK_PROPERTIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.BOOK_TIME, com.wombat.mamda.orderbook.MamdaOrderBookFields.BOOK_TYPE, com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.clear(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.clear(), com.wombat.mamda.orderbook.MamdaOrderBook.clear(), com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), com.wombat.mamda.orderbook.MamdaOrderBook.detach(), com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_ACTION, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_ID, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_PROP_MSG_TYPE, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_PROPERTIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_REASON, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_SIZE, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_STATUS, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_TIME, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.entryIterator(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.findEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.findLevel(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.findOrCreateLevel(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getActivityTime(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getActivityTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNum(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNumFieldState(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventTime(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBook.getIsConsistent(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntriesTotal(), com.wombat.mamda.orderbook.MamdaOrderBookFields.getNumEntryFields(), com.wombat.mamda.orderbook.MamdaOrderBookFields.getNumLevelFields(), com.wombat.mamda.orderbook.MamdaOrderBook.getOrCreateMarketOrdersSide(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getOrderBook(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice(), com.wombat.mamda.orderbook.MamdaOrderBook.getQuality(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), com.wombat.mamda.orderbook.MamdaOrderBook.getSourceDerivative(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getSrcTime(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getSrcTimeFieldState(), com.wombat.mamda.orderbook.MamdaOrderBook.getSymbol(), com.wombat.mamda.MamdaSubscription.getSymbol(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getTime(), com.wombat.mamda.orderbook.MamdaOrderBookFields.isSet(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_LIMIT, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_MARKET, com.wombat.mamda.MamdaCommonFields.LINE_TIME, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_REASON_UNKNOWN, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_PROP_MSG_TYPE_UPDATE, com.wombat.mamda.MamdaCommonFields.MSG_NUM, com.wombat.mamda.MamdaCommonFields.MSG_SEQ_NUM, com.wombat.mamda.MamdaCommonFields.MSG_TOTAL, com.wombat.mamda.orderbook.MamdaOrderBookFields.NUM_LEVELS, com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookClear(), com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookComplexDelta(), com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookDelta(), com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookGap(), com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookRecap(), com.wombat.mamda.MamdaCommonFields.PART_ID, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_ACTION, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_ENTRIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_ENTRY, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_NUM_ATTACH, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_NUM_ENTRIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_PRICE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_PROP_MSG_TYPE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_PROPERTIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_SIDE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_SIZE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_SIZE_CHANGE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_TIME, com.wombat.mamda.orderbook.MamdaOrderBookFields.PRICE_LEVEL, com.wombat.mamda.orderbook.MamdaOrderBookFields.PRICE_LEVELS, com.wombat.mamda.locks.MamdaLock.releaseWriteLock(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.MamdaCommonFields.SEND_TIME, com.wombat.mamda.MamdaCommonFields.SENDER_ID, com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.set(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction(), com.wombat.mamda.orderbook.MamdaOrderBook.setBookTime(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setId(), com.wombat.mamda.orderbook.MamdaOrderBook.setIsConsistent(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setManager(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setOrderType(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setPrice(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setReason(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSize(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setSourceDerivative(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setStatus(), com.wombat.mamda.orderbook.MamdaOrderBook.setSymbol(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setTime(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setTime(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setUniqueId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID, com.wombat.mamda.MamdaCommonFields.SRC_TIME, and com.wombat.mamda.MamdaCommonFields.SYMBOL.