OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBook Class Reference
com.wombat.mamda.orderbook.MamdaOrderBook Class Reference
MamdaOrderBook is a class that provides order book functionality, including iterators over price levels and entries within price levels.
Public Member Functions
MamdaOrderBook ()
Construct a new order book object.
MamdaOrderBook (MamdaOrderBook copy)
Construct a copy of the supplied orderbook.
MamdaOrderBook (MamdaOrderBook copy, boolean writeable)
Construct a copy of the supplied orderbook.
boolean isReadOnly ()
If this book is read only.
void clear ()
Clear all levels from the order book.
void setSymbol (String symbol)
The order book subscription symbol.
String getSymbol ()
The order book subscription symbol.
void setPartId (String PartId)
String getPartId ()
boolean hasPartId ()
MamdaOrderBookPriceLevel findOrCreateLevel (double price, char side)
Create a price level in the orderbook for the given price/size.
MamdaOrderBookPriceLevel findLevel (double price, char side)
MamdaOrderBookPriceLevel getMarketOrdersSide (char side)
MamdaOrderBookPriceLevel getOrCreateMarketOrdersSide (char side)
void apply (MamdaOrderBook deltaBook)
Apply a delta to this (presumably) full book.
void apply (MamdaOrderBookBasicDelta delta)
Apply a MamdaOrderBookBasicDelta to this book.
void apply (MamdaBookAtomicLevel level)
void apply (MamdaBookAtomicLevelEntry levelEntry)
void apply (MamdaOrderBookBasicDeltaList deltaList)
Apply a MamdaOrderBookBasicDeltaList to this book.
void copy (MamdaOrderBook book)
Make a writeable deep copy of a book.
void copyReadOnly (MamdaOrderBook book)
Make a read only deep copy of a book.
void setAsDeltaDeleted (MamdaOrderBook bookToDelete)
Set this order book to be a delta that would, when applied, delete all of the fields in the bookToDelete.
void setAsDeltaDifference (MamdaOrderBook lhs, MamdaOrderBook rhs)
Set this order book to be a delta that would, when applied, be the difference between to other books.
long getTotalNumLevels ()
Get the total number of price levels (both sides of order book).
int getNumBidLevels ()
Get the number of bid levels.
int getNumAskLevels ()
Get the number of ask levels.
MamdaOrderBookPriceLevel getBidMarketOrders ()
MamdaOrderBookPriceLevel getAskMarketOrders ()
MamaDateTime getBookTime ()
Return the book time.
void setBookTime (MamaDateTime value)
Set The SourceDerivative for this book.
void setSourceDerivative (MamaSourceDerivative value)
Set The SourceDerivative for this book.
MamaSourceDerivative getSourceDerivative ()
Return the SourceDerivative for this book.
MamaSource getSource ()
Get the MamaSource for this order book.
void setQuality (short quality)
Set the mamaQuality for this order book.
short getQuality ()
Get the mamaQuality for this order book.
void setClosure (Object closure)
Set the order book closure handle.
Object getClosure ()
Get the order book closure handle.
int hashCode ()
boolean equals (Object obj)
void addEntry (MamdaOrderBookEntry entry, double price, char side, MamaDateTime eventTime, MamdaOrderBookBasicDelta delta)
Add an entry to the order book and (if "delta" is not NULL) record information about the delta related to this action.
MamdaOrderBookEntry addEntry (String entryId, long entrySize, double price, char side, MamaDateTime eventTime, MamaSourceDerivative source, MamdaOrderBookBasicDelta delta)
Add an entry to the order book and (if "delta" is not NULL) record information about the delta related to this action.
void addLevel (MamdaOrderBookPriceLevel level)
Add a price level to the orderbook.
void updateLevel (MamdaOrderBookPriceLevel level)
Update an existing level in the orderbook.
boolean populateDelta (MamaMsg msg)
Populate a MamaMsg of the changes to this order book.
void populateRecap (MamaMsg msg)
Populate a MamaMsg with the current state of this order book.
void deleteLevel (MamdaOrderBookPriceLevel level)
Delete a price level from the orderbook.
boolean reevaluate ()
Re-evaluate the order book.
void setNeedsReevaluation (boolean need)
Set whether this book needs a re-evaluation.
boolean getNeedsReevaluation ()
Get whether this book needs a re-evaluation.
void setCheckSourceState (boolean check)
Set whether to check the MamaSourceState when adding/deleting/re-evaluating entries in the book.
boolean getCheckSourceState ()
Get whether to check the MamaSourceState when adding/deleting/re-evaluating entries in the book.
MamdaOrderBookPriceLevel getLevelAtPrice (double price, char side)
Return the order book price level at "price" on "side" of the order book.
MamdaOrderBookPriceLevel getLevelAtPosition (long pos, char side)
Return the order book price level at position "pos" in the order book.
MamdaOrderBookEntry getEntryAtPosition (long pos, char side)
Return the order book entry at position "pos" in the order book.
void assertEqual (MamdaOrderBook rhs)
Order book equality verification.
void assertEqual (MamdaOrderBookPriceLevel lhsLevel, MamdaOrderBookPriceLevel rhsLevel)
Order book level equality verification.
void setIsConsistent (boolean isConsistent)
Set whether the order book is in a consistent or an an inconsistent state.
boolean getIsConsistent ()
Get whether the order book is in a consistent or an an inconsistent state.
void dump ()
Dump the order book to standard out.
void dump (OutputStream outputStream)
Dump the order book to an OutputStream.
void updateEntry (MamdaOrderBookEntry entry, double size, MamaDateTime eventTime, MamdaOrderBookBasicDelta delta)
Update an entry in the order book and (if "delta" is not NULL) record information about the delta related to this action.
void deleteEntry (MamdaOrderBookEntry entry, MamaDateTime eventTime, MamdaOrderBookBasicDelta delta)
Delete an entry in the order book and (if "delta" is not NULL) record information about the delta related to this action.
void addEntriesFromBook (MamdaOrderBook book, MamdaOrderBookEntryFilter filter, MamdaOrderBookBasicDeltaList delta)
Add all entries from another book into this book.
void addPriceLevelsFromBookAsEntries (MamdaOrderBook book, String source, MamdaOrderBookBasicDeltaList delta)
Add all price levels from another book as entries (one per price level) into this book using "source" as the entryId for each entry.
void deleteEntriesFromSource (MamaSource source, MamdaOrderBookBasicDeltaList delta)
Delete all entries in this book that have "source" as its MamaSource.
void generateDeltaMsgs (boolean publish)
Enable the generation of book deltas for this book.
boolean getGenerateDeltaMsgs ()
Get whether book delta generation is enabled.
void clearDeltaList ()
clear the delta list using for storing generated deltas
void addDelta (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
For book delta generation.
void detach (MamdaOrderBookEntry entry)
NOOP FOR JAVA Adds the entry to the list of entries to be detached.
void detach (MamdaOrderBookPriceLevel level)
Detach a price level.
Iterator bidEntryIterator ()
Iterator for all the bid side entries in the book.
Iterator bidIterator ()
Allows an application to iterate over all the bid side price levels in the order book.
Iterator askIterator ()
Allows an application to iterate over all ask side price levels in the order book.
Iterator askEntryIterator ()
Iterator for all the ask side entries in the book.
void cleanupDetached ()
Static Public Member Functions
static void setStrictChecking (boolean strict)
Enforce strict checking of order book modifications (at the expense of some performance).
Detailed Description
MamdaOrderBook is a class that provides order book functionality, including iterators over price levels and entries within price levels.
An order book may be read only or writeable. Copying into a read only book is faster than creating a writeable book. Calling methods that attempt to edit the book structure on a read only book will throw a MamdaOrderBookException.
Constructor & Destructor Documentation
MamdaOrderBook() [1/3]
com.wombat.mamda.orderbook.MamdaOrderBook.MamdaOrderBook ()
Construct a new order book object.
Contains no price levels upon construction. This book will be writeable.
MamdaOrderBook() [2/3]
com.wombat.mamda.orderbook.MamdaOrderBook.MamdaOrderBook (MamdaOrderBook copy)
Construct a copy of the supplied orderbook.
Parameters
copy The book to copy.
MamdaOrderBook() [3/3]
com.wombat.mamda.orderbook.MamdaOrderBook.MamdaOrderBook (MamdaOrderBook copy, boolean writeable)
Construct a copy of the supplied orderbook.
Parameters
copy The book to copy.
writeable is this copy writable. false creates a read only copy
Member Function Documentation
isReadOnly()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.isReadOnly ()
If this book is read only.
Returns
true if this book is read only.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
clear()
void com.wombat.mamda.orderbook.MamdaOrderBook.clear ()
Clear all levels from the order book.
Clears both the bid and ask side levels from the order book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setSymbol()
void com.wombat.mamda.orderbook.MamdaOrderBook.setSymbol (String symbol)
The order book subscription symbol.
Parameters
symbol the symbol.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getSymbol()
String com.wombat.mamda.orderbook.MamdaOrderBook.getSymbol ()
The order book subscription symbol.
Returns
the symbol.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getSymbol(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSymbol(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setPartId()
void com.wombat.mamda.orderbook.MamdaOrderBook.setPartId (String PartId)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPartId()
String com.wombat.mamda.orderbook.MamdaOrderBook.getPartId ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
hasPartId()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.hasPartId ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
findOrCreateLevel()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.findOrCreateLevel (double price, char side)
Create a price level in the orderbook for the given price/size.
The price level is initially empty and marked as "not used". The "not used" status changes automatically when entries are added to the price level.
Parameters
price The price of the price level to find/create.
side The side of the book of the price level to find/create.
Returns
The found or newly create price level.
Exceptions
MamdaOrderBookException When an error is encountered during book processing.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
findLevel()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.findLevel (double price, char side)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getMarketOrdersSide()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.getMarketOrdersSide (char side)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getOrCreateMarketOrdersSide()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.getOrCreateMarketOrdersSide (char side)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
apply() [1/5]
void com.wombat.mamda.orderbook.MamdaOrderBook.apply (MamdaOrderBook deltaBook)
Apply a delta to this (presumably) full book.
Parameters
deltaBook The delta to apply to the order book.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
apply() [2/5]
void com.wombat.mamda.orderbook.MamdaOrderBook.apply (MamdaOrderBookBasicDelta delta)
Apply a MamdaOrderBookBasicDelta to this book.
Parameters
delta The delta to apply.
Exceptions
MamdaOrderBookException if called on a read only order book
apply() [3/5]
void com.wombat.mamda.orderbook.MamdaOrderBook.apply (MamdaBookAtomicLevel level)
apply() [4/5]
void com.wombat.mamda.orderbook.MamdaOrderBook.apply (MamdaBookAtomicLevelEntry levelEntry)
apply() [5/5]
void com.wombat.mamda.orderbook.MamdaOrderBook.apply (MamdaOrderBookBasicDeltaList deltaList)
Apply a MamdaOrderBookBasicDeltaList to this book.
Parameters
deltaList The deltas to apply.
Exceptions
MamdaOrderBookException if called on a read only order book
References com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator().
copy()
void com.wombat.mamda.orderbook.MamdaOrderBook.copy (MamdaOrderBook book)
Make a writeable deep copy of a book.
Parameters
book The order book to copy.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapshot().
copyReadOnly()
void com.wombat.mamda.orderbook.MamdaOrderBook.copyReadOnly (MamdaOrderBook book)
Make a read only deep copy of a book.
This method is faster than the copy (MamdaOrderBook book) method.
Parameters
book The order book to copy.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.getReadOnlyBookSnapshot().
setAsDeltaDeleted()
void com.wombat.mamda.orderbook.MamdaOrderBook.setAsDeltaDeleted (MamdaOrderBook bookToDelete)
Set this order book to be a delta that would, when applied, delete all of the fields in the bookToDelete.
Parameters
bookToDelete The book to be deleted.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setAsDeltaDifference()
void com.wombat.mamda.orderbook.MamdaOrderBook.setAsDeltaDifference (MamdaOrderBook lhs, MamdaOrderBook rhs)
Set this order book to be a delta that would, when applied, be the difference between to other books.
Parameters
lhs An order book.
rhs An order book.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getTotalNumLevels()
long com.wombat.mamda.orderbook.MamdaOrderBook.getTotalNumLevels ()
Get the total number of price levels (both sides of order book).
Returns
The total number of level in the order book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
getNumBidLevels()
int com.wombat.mamda.orderbook.MamdaOrderBook.getNumBidLevels ()
Get the number of bid levels.
Returns
the number of bid levels.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getNumAskLevels()
int com.wombat.mamda.orderbook.MamdaOrderBook.getNumAskLevels ()
Get the number of ask levels.
Returns
the number of ask levels.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getBidMarketOrders()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.getBidMarketOrders ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getAskMarketOrders()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.getAskMarketOrders ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getBookTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBook.getBookTime ()
Return the book time.
Returns
return the book time.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setBookTime()
void com.wombat.mamda.orderbook.MamdaOrderBook.setBookTime (MamaDateTime value)
Set The SourceDerivative for this book.
Parameters
value The SourceDerivative.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setSourceDerivative()
void com.wombat.mamda.orderbook.MamdaOrderBook.setSourceDerivative (MamaSourceDerivative value)
Set The SourceDerivative for this book.
Parameters
value The SourceDerivative.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getSourceDerivative()
MamaSourceDerivative com.wombat.mamda.orderbook.MamdaOrderBook.getSourceDerivative ()
Return the SourceDerivative for this book.
Returns
the SourceDerivative.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getSource()
MamaSource com.wombat.mamda.orderbook.MamdaOrderBook.getSource ()
Get the MamaSource for this order book.
Returns
The source.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setQuality()
void com.wombat.mamda.orderbook.MamdaOrderBook.setQuality (short quality)
Set the mamaQuality for this order book.
Parameters
quality The new quality.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNumFieldState().
getQuality()
short com.wombat.mamda.orderbook.MamdaOrderBook.getQuality ()
Get the mamaQuality for this order book.
Returns
The quality.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNumFieldState(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setClosure()
void com.wombat.mamda.orderbook.MamdaOrderBook.setClosure (Object closure)
Set the order book closure handle.
Parameters
closure The closure.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getClosure()
Object com.wombat.mamda.orderbook.MamdaOrderBook.getClosure ()
Get the order book closure handle.
Returns
The orderbook closure.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
hashCode()
int com.wombat.mamda.orderbook.MamdaOrderBook.hashCode ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
equals()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.equals (Object obj)
References com.wombat.mamda.orderbook.MamdaOrderBook.equals().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBook.equals().
addEntry() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.addEntry (MamdaOrderBookEntry entry, double price, char side, MamaDateTime eventTime, MamdaOrderBookBasicDelta delta)
Add an entry to the order book and (if "delta" is not NULL) record information about the delta related to this action.
Parameters
entry the entry
price the price
side the side (bid or ask)
eventTime the event time.
delta the delta.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
addEntry() [2/2]
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBook.addEntry (String entryId, long entrySize, double price, char side, MamaDateTime eventTime, MamaSourceDerivative source, MamdaOrderBookBasicDelta delta)
Add an entry to the order book and (if "delta" is not NULL) record information about the delta related to this action.
The new entry is returned.
Parameters
price the price
side the side (bid or ask)
eventTime the event time.
delta the delta.
entryId The id.
entrySize the size
source the MamaSourceDerivative.
Returns
the new entry.
Exceptions
MamdaOrderBookException if called on a read only order book
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, and com.wombat.mamda.orderbook.MamdaOrderBook.addEntry().
addLevel()
void com.wombat.mamda.orderbook.MamdaOrderBook.addLevel (MamdaOrderBookPriceLevel level)
Add a price level to the orderbook.
Parameters
level The price level to add to the orderbook.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
updateLevel()
void com.wombat.mamda.orderbook.MamdaOrderBook.updateLevel (MamdaOrderBookPriceLevel level)
Update an existing level in the orderbook.
Parameters
level The details of the price level to update.
Exceptions
MamdaOrderBookException When an error is encountered during book processing.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
populateDelta()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.populateDelta (MamaMsg msg)
Populate a MamaMsg of the changes to this order book.
This will include the changes from the last time this function was called or all changes from the initial state.
Parameters
msg A MamaMsg ref containing all changes to the current book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
populateRecap()
void com.wombat.mamda.orderbook.MamdaOrderBook.populateRecap (MamaMsg msg)
Populate a MamaMsg with the current state of this order book.
Parameters
msg A MamaMsg containing all book, price and entry (if applicable) details of the current book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
deleteLevel()
void com.wombat.mamda.orderbook.MamdaOrderBook.deleteLevel (MamdaOrderBookPriceLevel level)
Delete a price level from the orderbook.
Parameters
level The price level to delete from the orderbook.
Exceptions
MamdaOrderBookException When an error is encountered during book processing.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
reevaluate()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.reevaluate ()
Re-evaluate the order book.
This would be performed after the status of sources and/or subsources of an "aggregated order book" (i.e., a book built from multiple sources) have changed.
Returns
Whether the book info changed based on the re-evaluation.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setNeedsReevaluation()
void com.wombat.mamda.orderbook.MamdaOrderBook.setNeedsReevaluation (boolean need)
Set whether this book needs a re-evaluation.
Parameters
need true if books requires re-evaluation.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getNeedsReevaluation()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.getNeedsReevaluation ()
Get whether this book needs a re-evaluation.
Returns
true if the book needs re-evaluation.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setCheckSourceState()
void com.wombat.mamda.orderbook.MamdaOrderBook.setCheckSourceState (boolean check)
Set whether to check the MamaSourceState when adding/deleting/re-evaluating entries in the book.
Parameters
check true to check the MamaSourceState.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getCheckSourceState()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState ()
Get whether to check the MamaSourceState when adding/deleting/re-evaluating entries in the book.
Returns
true if checking the MamaSourceState
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.deleteEntriesFromSource(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getEntryAtPosition(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.reevaluate(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById().
getLevelAtPrice()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.getLevelAtPrice (double price, char side)
Return the order book price level at "price" on "side" of the order book.
Parameters
price The price of the order book price level.
side The side of the order book to search.
Returns
The order book price level or NULL if not found.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getLevelAtPosition()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBook.getLevelAtPosition (long pos, char side)
Return the order book price level at position "pos" in the order book.
Parameters
pos The position of the order book price level.
side The side of the order book to search.
Returns
The order book price level or NULL if not found.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getEntryAtPosition()
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBook.getEntryAtPosition (long pos, char side)
Return the order book entry at position "pos" in the order book.
Parameters
pos The position of the order book entry.
side The side of the order book to search.
Returns
The order book entry or NULL if not found.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
assertEqual() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.assertEqual (MamdaOrderBook rhs)
Order book equality verification.
A MamdaOrderBookException is thrown if the books are not equal, along with the reason for the inequality.
Parameters
rhs The order book to compare to the current book.
Exceptions
MamdaOrderBookException The two books are not equal.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
assertEqual() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.assertEqual (MamdaOrderBookPriceLevel lhsLevel, MamdaOrderBookPriceLevel rhsLevel)
Order book level equality verification.
A MamdaOrderBookException is thrown if the books are not equal, along with the reason for the inequality.
Parameters
rhs The order book to compare to the current book.
Exceptions
MamdaOrderBookException The two books are not equal.
setIsConsistent()
void com.wombat.mamda.orderbook.MamdaOrderBook.setIsConsistent (boolean isConsistent)
Set whether the order book is in a consistent or an an inconsistent state.
Parameters
isConsistent Whether the book is consistent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getIsConsistent()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.getIsConsistent ()
Get whether the order book is in a consistent or an an inconsistent state.
The orderbook will be marked as inconsistent if a gap is detected by the Listener. The book will be marked consistent again once a full recap for the book has been obtained from the feed.
Returns
boolean Whether the book is in a consistent state.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
dump() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.dump ()
Dump the order book to standard out.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
dump() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.dump (OutputStream outputStream)
Dump the order book to an OutputStream.
Parameters
outputStream the OutputStream
updateEntry()
void com.wombat.mamda.orderbook.MamdaOrderBook.updateEntry (MamdaOrderBookEntry entry, double size, MamaDateTime eventTime, MamdaOrderBookBasicDelta delta)
Update an entry in the order book and (if "delta" is not NULL) record information about the delta related to this action.
If the entry is not internally "wired" to the order book, a MamdaOrderBookInvalidEntry exception is thrown.
Parameters
entry the entry
size the size
eventTime the event time
delta the delta.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
deleteEntry()
void com.wombat.mamda.orderbook.MamdaOrderBook.deleteEntry (MamdaOrderBookEntry entry, MamaDateTime eventTime, MamdaOrderBookBasicDelta delta)
Delete an entry in the order book and (if "delta" is not NULL) record information about the delta related to this action.
If the entry is not internally "wired" to the order book, a MamdaOrderBookInvalidEntry exception is thrown.
Parameters
entry the entry to detete.
eventTime the event time.
delta the delta
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
addEntriesFromBook()
void com.wombat.mamda.orderbook.MamdaOrderBook.addEntriesFromBook (MamdaOrderBook book, MamdaOrderBookEntryFilter filter, MamdaOrderBookBasicDeltaList delta)
Add all entries from another book into this book.
Parameters
book The source book to add.
filter If not NULL, a filter to apply to each entry.
delta An optional delta to collect the added entries.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
addPriceLevelsFromBookAsEntries()
void com.wombat.mamda.orderbook.MamdaOrderBook.addPriceLevelsFromBookAsEntries (MamdaOrderBook book, String source, MamdaOrderBookBasicDeltaList delta)
Add all price levels from another book as entries (one per price level) into this book using "source" as the entryId for each entry.
Parameters
book The source book to add.
source The name to use as the entry ID.
delta An optional delta to collect the added entries.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
deleteEntriesFromSource()
void com.wombat.mamda.orderbook.MamdaOrderBook.deleteEntriesFromSource (MamaSource source, MamdaOrderBookBasicDeltaList delta)
Delete all entries in this book that have "source" as its MamaSource.
Parameters
source The source to match.
delta An optional delta to collect the deleted entries.
Exceptions
MamdaOrderBookException if called on a read only order book
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
generateDeltaMsgs()
void com.wombat.mamda.orderbook.MamdaOrderBook.generateDeltaMsgs (boolean publish)
Enable the generation of book deltas for this book.
When delta generation is enabled changes to the book are saved and can be popultaed to MamaMsgs.
Parameters
publish Whether book delta generation is enabled.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getGenerateDeltaMsgs()
boolean com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs ()
Get whether book delta generation is enabled.
Returns
Whether book delta generation is enabled.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
clearDeltaList()
void com.wombat.mamda.orderbook.MamdaOrderBook.clearDeltaList ()
clear the delta list using for storing generated deltas
addDelta()
void com.wombat.mamda.orderbook.MamdaOrderBook.addDelta (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
For book delta generation.
Add a delta to the order book delta list for the publishing of order book data
Parameters
entry MamdaOrderBookEntry where change occurred.
level MamdaOrderBookPriceLevel where change occurred.
plDeltaSize Pricelevel size change.
plAction Pricelevel action.
entAction Entry action.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
detach() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.detach (MamdaOrderBookEntry entry)
NOOP FOR JAVA Adds the entry to the list of entries to be detached.
Parameters
entry the entry to detach.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.deleteEntriesFromSource(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
detach() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBook.detach (MamdaOrderBookPriceLevel level)
Detach a price level.
Parameters
level the level to detach.
Exceptions
MamdaOrderBookException if called on a read only order book
bidEntryIterator()
Iterator com.wombat.mamda.orderbook.MamdaOrderBook.bidEntryIterator ()
Iterator for all the bid side entries in the book.
Returns
the iterator.
References com.wombat.mamda.orderbook.MamdaOrderBook.bidIterator().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
bidIterator()
Iterator com.wombat.mamda.orderbook.MamdaOrderBook.bidIterator ()
Allows an application to iterate over all the bid side price levels in the order book.
Returns
Iterator java.util.Iterator for the bid side price levels in the order book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.bidEntryIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
askIterator()
Iterator com.wombat.mamda.orderbook.MamdaOrderBook.askIterator ()
Allows an application to iterate over all ask side price levels in the order book.
Returns
Iterator java.util.Iterator for the ask side price levels in the order book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.askEntryIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
askEntryIterator()
Iterator com.wombat.mamda.orderbook.MamdaOrderBook.askEntryIterator ()
Iterator for all the ask side entries in the book.
Returns
the iterator.
References com.wombat.mamda.orderbook.MamdaOrderBook.askIterator().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setStrictChecking()
static void com.wombat.mamda.orderbook.MamdaOrderBook.setStrictChecking (boolean strict) static
Enforce strict checking of order book modifications (at the expense of some performance).
This setting is passed on to the MamdaOrderBookPriceLevel and MamdaOrderBookEntry classes.
Parameters
strict the value for strict checking.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.setStrictChecking(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setStrictChecking().
cleanupDetached()
void com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached ()
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UNKNOWN, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UNKNOWN, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.add(), com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBook.addEntriesFromBook(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntriesFromLevel(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.addLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.addPriceLevelsFromBookAsEntries(), com.wombat.mamda.orderbook.MamdaOrderBook.apply(), com.wombat.mamda.orderbook.MamdaOrderBook.askEntryIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.askIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.assertEqual(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.assertEqual(), com.wombat.mamda.orderbook.MamdaOrderBook.bidEntryIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.bidIterator(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.clear(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.clear(), com.wombat.mamda.orderbook.MamdaOrderBook.clear(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.clear(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy(), com.wombat.mamda.orderbook.MamdaOrderBook.copy(), com.wombat.mamda.orderbook.MamdaOrderBook.deleteEntriesFromSource(), com.wombat.mamda.orderbook.MamdaOrderBook.deleteEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.deleteLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.detach(), com.wombat.mamda.orderbook.MamdaOrderBook.dump(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.empty(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.entryIterator(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.entryIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.equals(), com.wombat.mamda.orderbook.MamdaOrderBook.findLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.findOrCreateLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.generateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getAction(), com.wombat.mamda.orderbook.MamdaOrderBook.getAskMarketOrders(), com.wombat.mamda.orderbook.MamdaOrderBook.getBidMarketOrders(), com.wombat.mamda.orderbook.MamdaOrderBook.getBookTime(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBook.getClosure(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.getEntryAtPosition(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getEntryAtPosition(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getEntryDeltaAction(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBook.getIsConsistent(), com.wombat.mamda.orderbook.MamdaOrderBook.getLevelAtPosition(), com.wombat.mamda.orderbook.MamdaOrderBook.getLevelAtPrice(), com.wombat.mamda.orderbook.MamdaOrderBook.getMarketOrdersSide(), com.wombat.mamda.orderbook.MamdaOrderBook.getNeedsReevaluation(), com.wombat.mamda.orderbook.MamdaOrderBook.getNumAskLevels(), com.wombat.mamda.orderbook.MamdaOrderBook.getNumBidLevels(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBook.getOrCreateMarketOrdersSide(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getOrderBook(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getOrderType(), com.wombat.mamda.orderbook.MamdaOrderBook.getPartId(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPlDeltaAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPriceLevel(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelAction(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryAction(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryId(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryReason(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntrySize(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryTime(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelMamaPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelMamaPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelNumEntries(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelSide(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSide(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSize(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSizeChange(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelTime(), com.wombat.mamda.orderbook.MamdaOrderBook.getQuality(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), com.wombat.mamda.orderbook.MamdaOrderBook.getSource(), com.wombat.mamda.orderbook.MamdaOrderBook.getSourceDerivative(), com.wombat.mamda.orderbook.MamdaOrderBook.getSymbol(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getTime(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getTime(), com.wombat.mamda.orderbook.MamdaOrderBook.getTotalNumLevels(), com.wombat.mamda.orderbook.MamdaOrderBook.hashCode(), com.wombat.mamda.orderbook.MamdaOrderBook.hasPartId(), com.wombat.mamda.orderbook.MamdaOrderBook.isReadOnly(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.isVisible(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_MARKET, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_ACTION_UNKNOWN, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_SIDE_ASK, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_SIDE_BID, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaOrderBook.populateDelta(), com.wombat.mamda.orderbook.MamdaOrderBook.populateRecap(), com.wombat.mamda.orderbook.MamdaOrderBook.reevaluate(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.reevaluate(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.set(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAction(), com.wombat.mamda.orderbook.MamdaOrderBook.setAsDeltaDeleted(), com.wombat.mamda.orderbook.MamdaOrderBook.setAsDeltaDifference(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference(), com.wombat.mamda.orderbook.MamdaOrderBook.setBookTime(), com.wombat.mamda.orderbook.MamdaOrderBook.setCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBook.setClosure(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setId(), com.wombat.mamda.orderbook.MamdaOrderBook.setIsConsistent(), com.wombat.mamda.orderbook.MamdaOrderBook.setNeedsReevaluation(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setOrderBook(), com.wombat.mamda.orderbook.MamdaOrderBook.setPartId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setPrice(), com.wombat.mamda.orderbook.MamdaOrderBook.setQuality(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setReason(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSizeChange(), com.wombat.mamda.orderbook.MamdaOrderBook.setSourceDerivative(), com.wombat.mamda.orderbook.MamdaOrderBook.setSymbol(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setTime(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setTime(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_ASK, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_UNKNOWN, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.updateEntry(), and com.wombat.mamda.orderbook.MamdaOrderBook.updateLevel().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().