OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionContract Class Reference
com.wombat.mamda.options.MamdaOptionContract Class Reference
A class that represents a single option contract.
Public Member Functions
MamdaOptionContract (String symbol, String exchange, Date expireDate, double strikePrice, char putCall)
Constructor from expiration date, strike price, and put/call indicator.
void setOpenInterest (long openInterest)
Set the open interest size.
void setExerciseStyle (char exerciseStyle)
Set the exercise style.
String getSymbol ()
Return the OPRA contract symbol.
String getExchange ()
Return the exchange.
Date getExpireDate ()
Return the expiration date.
String getExpireDateStr ()
Return the expiration date as a commonly formatted string (MMMyy).
double getStrikePrice ()
Return the strike price.
char getPutCall ()
Return the put/call indicator.
long getOpenInterest ()
Return the open interest.
char getExerciseStyle ()
Return the exercise style.
void addTradeHandler (MamdaTradeHandler handler)
Add a MamdaTradeHandler for handling trade updates to this option contract.
void addQuoteHandler (MamdaQuoteHandler handler)
Add a MamdaQuoteHandler for handling quote updates to this option contract.
void addFundamentalHandler (MamdaFundamentalHandler handler)
Add a MamdaFundamentalHandler for handling fundamental updates to this option contract.
void setCustomObject (Object object)
Add a custom object to this option contract.
MamdaTradeRecap getTradeInfo ()
Return the current trade fields.
MamdaQuoteRecap getQuoteInfo ()
Return the current quote fields.
MamdaFundamentals getFundamentalsInfo ()
Return the current fundamental fields.
Object getCustomObject ()
Return the custom object.
MamdaTradeListener getTradeListener ()
Return the trade listener.
MamdaQuoteListener getQuoteListener ()
Return the current quote listener.
MamdaFundamentalListener getFundamentalListener ()
Return the current fundamental listener.
void setInView (boolean inView)
Set whether this contract is in the "view" within the option chain.
boolean getInView ()
Return whether this contract is in the "view" within the option chain.
Static Public Attributes
static final char PC_UNKNOWN = ' '
static final char PC_CALL = 'C'
static final char PC_PUT = 'P'
static final char EXERCISE_STYLE_AMERICAN = 'A'
static final char EXERCISE_STYLE_EUROPEAN = 'E'
static final char EXERCISE_STYLE_CAPPED = 'C'
static final char EXERCISE_STYLE_UNKNOWN = 'Z'
Detailed Description
A class that represents a single option contract.
Instances of this object are typically created by the MamdaOptionChainListener. Applications may attach a custom object to each instance of MamdaOptionContract.
Note: User applications can be notified of creation of MamdaOptionContract instances via the MamdaOptionChainListener.onOptionContractCreate() method.
Note: It is possible to provide individual MamdaTradeHandler and MamdaQuoteHandler handlers for trades and quotes, even though the MamdaOptionChainHandler also provides a general callback interface for updates to individual contracts.
Constructor & Destructor Documentation
MamdaOptionContract()
com.wombat.mamda.options.MamdaOptionContract.MamdaOptionContract (String symbol, String exchange, Date expireDate, double strikePrice, char putCall)
Constructor from expiration date, strike price, and put/call indicator.
Member Function Documentation
setOpenInterest()
void com.wombat.mamda.options.MamdaOptionContract.setOpenInterest (long openInterest)
Set the open interest size.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
setExerciseStyle()
void com.wombat.mamda.options.MamdaOptionContract.setExerciseStyle (char exerciseStyle)
Set the exercise style.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
getSymbol()
String com.wombat.mamda.options.MamdaOptionContract.getSymbol ()
Return the OPRA contract symbol.
Referenced by com.wombat.mamda.options.MamdaOptionChain.dump().
getExchange()
String com.wombat.mamda.options.MamdaOptionContract.getExchange ()
Return the exchange.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract(), and com.wombat.mamda.options.MamdaOptionChain.dump().
getExpireDate()
Date com.wombat.mamda.options.MamdaOptionContract.getExpireDate ()
Return the expiration date.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract(), com.wombat.mamda.options.MamdaOptionChain.dump(), and com.wombat.mamda.options.MamdaOptionChainView.isVisible().
getExpireDateStr()
String com.wombat.mamda.options.MamdaOptionContract.getExpireDateStr ()
Return the expiration date as a commonly formatted string (MMMyy).
getStrikePrice()
double com.wombat.mamda.options.MamdaOptionContract.getStrikePrice ()
Return the strike price.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract(), com.wombat.mamda.options.MamdaOptionChain.dump(), and com.wombat.mamda.options.MamdaOptionChainView.isVisible().
getPutCall()
char com.wombat.mamda.options.MamdaOptionContract.getPutCall ()
Return the put/call indicator.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract().
getOpenInterest()
long com.wombat.mamda.options.MamdaOptionContract.getOpenInterest ()
Return the open interest.
getExerciseStyle()
char com.wombat.mamda.options.MamdaOptionContract.getExerciseStyle ()
Return the exercise style.
addTradeHandler()
void com.wombat.mamda.options.MamdaOptionContract.addTradeHandler (MamdaTradeHandler handler)
Add a MamdaTradeHandler for handling trade updates to this option contract.
References com.wombat.mamda.MamdaTradeListener.addHandler().
addQuoteHandler()
void com.wombat.mamda.options.MamdaOptionContract.addQuoteHandler (MamdaQuoteHandler handler)
Add a MamdaQuoteHandler for handling quote updates to this option contract.
References com.wombat.mamda.MamdaQuoteListener.addHandler().
addFundamentalHandler()
void com.wombat.mamda.options.MamdaOptionContract.addFundamentalHandler (MamdaFundamentalHandler handler)
Add a MamdaFundamentalHandler for handling fundamental updates to this option contract.
References com.wombat.mamda.MamdaFundamentalListener.addHandler().
setCustomObject()
void com.wombat.mamda.options.MamdaOptionContract.setCustomObject (Object object)
Add a custom object to this option contract.
Such an object might contain customer per-contract data.
getTradeInfo()
MamdaTradeRecap com.wombat.mamda.options.MamdaOptionContract.getTradeInfo ()
Return the current trade fields.
getQuoteInfo()
MamdaQuoteRecap com.wombat.mamda.options.MamdaOptionContract.getQuoteInfo ()
Return the current quote fields.
getFundamentalsInfo()
MamdaFundamentals com.wombat.mamda.options.MamdaOptionContract.getFundamentalsInfo ()
Return the current fundamental fields.
getCustomObject()
Object com.wombat.mamda.options.MamdaOptionContract.getCustomObject ()
Return the custom object.
getTradeListener()
MamdaTradeListener com.wombat.mamda.options.MamdaOptionContract.getTradeListener ()
Return the trade listener.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
getQuoteListener()
MamdaQuoteListener com.wombat.mamda.options.MamdaOptionContract.getQuoteListener ()
Return the current quote listener.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
getFundamentalListener()
MamdaFundamentalListener com.wombat.mamda.options.MamdaOptionContract.getFundamentalListener ()
Return the current fundamental listener.
setInView()
void com.wombat.mamda.options.MamdaOptionContract.setInView (boolean inView)
Set whether this contract is in the "view" within the option chain.
See also
MamdaOptionChain
getInView()
boolean com.wombat.mamda.options.MamdaOptionContract.getInView ()
Return whether this contract is in the "view" within the option chain.
See also
MamdaOptionChain
Member Data Documentation
PC_UNKNOWN
final char com.wombat.mamda.options.MamdaOptionContract.PC_UNKNOWN = ' ' static
PC_CALL
final char com.wombat.mamda.options.MamdaOptionContract.PC_CALL = 'C' static
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract().
PC_PUT
final char com.wombat.mamda.options.MamdaOptionContract.PC_PUT = 'P' static
EXERCISE_STYLE_AMERICAN
final char com.wombat.mamda.options.MamdaOptionContract.EXERCISE_STYLE_AMERICAN = 'A' static
EXERCISE_STYLE_EUROPEAN
final char com.wombat.mamda.options.MamdaOptionContract.EXERCISE_STYLE_EUROPEAN = 'E' static
EXERCISE_STYLE_CAPPED
final char com.wombat.mamda.options.MamdaOptionContract.EXERCISE_STYLE_CAPPED = 'C' static
EXERCISE_STYLE_UNKNOWN
final char com.wombat.mamda.options.MamdaOptionContract.EXERCISE_STYLE_UNKNOWN = 'Z' static