OpenMAMDA Java API: com.wombat.mamda.MamdaConcreteBasicEvent Class Reference
com.wombat.mamda.MamdaConcreteBasicEvent Class Reference
MamdaConcreteBasicEvent is intended to be used to help implement concrete versions of various classes derived from MamdaBasicEvent.
Inherits com.wombat.mamda.MamdaBasicEvent.
Inherited by com.wombat.mamda.orderbook.MamdaOrderBookConcreteClear, and com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.
Public Member Functions
MamaDateTime getSrcTime ()
short getSrcTimeFieldState ()
void setSrcTime (MamaDateTime srcTime)
MamaDateTime getActivityTime ()
short getActivityTimeFieldState ()
void setActivityTime (MamaDateTime activityTime)
MamaDateTime getEventTime ()
short getEventTimeFieldState ()
void setEventTime (MamaDateTime eventTime)
long getEventSeqNum ()
short getEventSeqNumFieldState ()
void setEventSeqNum (long eventSeqNum)
Detailed Description
MamdaConcreteBasicEvent is intended to be used to help implement concrete versions of various classes derived from MamdaBasicEvent.
Member Function Documentation
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTime ()
Returns
Returns mSrcTime.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getSrcTime(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getSrcTime().
getSrcTimeFieldState()
short com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTimeFieldState ()
Returns
Returns mSrcTime.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.MODIFIED.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getSrcTimeFieldState(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getSrcTimeFieldState().
setSrcTime()
void com.wombat.mamda.MamdaConcreteBasicEvent.setSrcTime (MamaDateTime srcTime)
Parameters
mSrcTime The mSrcTime to set.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setSrcTime(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setSrcTime().
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTime ()
Returns
Returns mActivityTime.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getActivityTime(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getActivityTime().
getActivityTimeFieldState()
short com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTimeFieldState ()
Returns
Returns mActivityTime Field State.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.MODIFIED.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getActivityTimeFieldState(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getActivityTimeFieldState().
setActivityTime()
void com.wombat.mamda.MamdaConcreteBasicEvent.setActivityTime (MamaDateTime activityTime)
Parameters
mActivityTime The mActivityTime to set.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setActivityTime(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setActivityTime().
getEventTime()
MamaDateTime com.wombat.mamda.MamdaConcreteBasicEvent.getEventTime ()
Returns
Returns mEventTime.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventTime(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventTime().
getEventTimeFieldState()
short com.wombat.mamda.MamdaConcreteBasicEvent.getEventTimeFieldState ()
Returns
Returns mEventTime Field State.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.MODIFIED.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventTimeFieldState(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventTimeFieldState().
setEventTime()
void com.wombat.mamda.MamdaConcreteBasicEvent.setEventTime (MamaDateTime eventTime)
Parameters
mEventTime The mEventTime to set.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setEventTime(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setEventTime().
getEventSeqNum()
long com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNum ()
Returns
Returns mEventSeqNum.
Implements com.wombat.mamda.MamdaBasicEvent.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventSeqNum(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventSeqNum().
getEventSeqNumFieldState()
short com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNumFieldState ()
Returns
Returns mEventSeqNum Field State.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.MODIFIED.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.getEventSeqNumFieldState(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventSeqNumFieldState().
setEventSeqNum()
void com.wombat.mamda.MamdaConcreteBasicEvent.setEventSeqNum (long eventSeqNum)
Parameters
mEventSeqNum The mEventSeqNum to set.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookConcreteSimpleDelta.setEventSeqNum(), and com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setEventSeqNum().