OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookEntry Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookEntry Class Reference
MamdaOrderBookEntry is a class that provides implements order book functionality.
Public Member Functions
MamdaOrderBookEntry ()
MamdaOrderBookEntry (MamdaOrderBookEntry copy)
Copy an order book entry object which is a shallow copy of the original.
MamdaOrderBookEntry (String entryId, double entrySize, char action, MamaDateTime eventTime, MamaSourceDerivative source)
void copy (MamdaOrderBookEntry copy)
Copy an order book entry object which is an exact and deep copy of the original.
void setId (String id)
void setSize (double size)
void setAction (char action)
void setReason (char reason)
void setTime (MamaDateTime time)
void setDetails (MamdaOrderBookEntry copy)
void setDetails (MamdaBookAtomicLevelEntry copy)
String getId ()
If supported, Order book entry ID (order ID, participant ID, etc.)
String getUniqueId ()
If supported, Order book entry unique ID (order ID, participant ID, etc.).
double getSize ()
The size of the order entry.
char getAction ()
Whether to ADD, UPDATE or DELETE the entry.
char getReason ()
The reason for the order entry.
MamaDateTime getTime ()
Time of order book entry update.
void setStatus (int value)
Set the status for the entry.
int getStatus ()
Return the status for the entry.
double getPrice ()
Get the price for this entry.
char getSide ()
Get the price for this entry.
int getPosition (int maxPos)
Get the position in the order book for this entry.
int hashCode ()
boolean equals (Object obj)
void setPriceLevel (MamdaOrderBookPriceLevel priceLevel)
Set the MamdaOrderBookPriceLevel object to which this entry belongs.
MamdaOrderBookPriceLevel getPriceLevel ()
Get the MamdaOrderBookPriceLevel object to which this entry belongs.
MamdaOrderBook getOrderBook ()
Get the order book for this entry, if possible.
void setManager (MamdaOrderBookEntryManager manager)
Set the MamdaOrderBookEntryManager object to which this entry belongs.
MamdaOrderBookEntryManager getManager ()
Get the MamdaOrderBookEntryManager object to which this entry belongs.
String getSymbol ()
Get the symbol for this entry, if possible.
void setSourceDerivative (MamaSourceDerivative source)
Set the MamaSourceDerivative for this book entry.
MamaSourceDerivative getSourceDerivative ()
Return the MamaSourceDerivative for this book entry.
MamaSource getSource ()
Return the MamaSource for this book entry.
boolean getCheckSourceState ()
Get whether this order book wants to check the source state.
void setQuality (short quality)
Set the entry-level quality factor.
short getQuality ()
Get the entry-level quality factor.
boolean isVisible ()
void setClosure (Object closure)
Set the order book entry closure handle.
Object getClosure ()
Get the order book entry closure handle.
void assertEqual (MamdaOrderBookEntry rhs)
Order book entry equality verification.
boolean equalId (String id)
Whether the id of the entry is equal to the id passed to the method.
void setUniqueId (String uniqueId)
Static Public Member Functions
static void setStrictChecking (boolean strict)
Enforce strict checking of order book modifications (at the expense of some performance).
Static Public Attributes
static final char ACTION_ADD = 'A'
An enumeration for book entry actions.
static final char ACTION_UPDATE = 'U'
An updated entry.
static final char ACTION_DELETE = 'D'
A deleted entry.
static final char ACTION_UNKNOWN = 'Z'
Unknown action (error).
Detailed Description
MamdaOrderBookEntry is a class that provides implements order book functionality.
Constructor & Destructor Documentation
MamdaOrderBookEntry() [1/3]
com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntry.equals().
MamdaOrderBookEntry() [2/3]
com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry (MamdaOrderBookEntry copy)
Copy an order book entry object which is a shallow copy of the original.
Parameters
copy The MamdaOrderBookEntry to copy.
MamdaOrderBookEntry() [3/3]
com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry (String entryId, double entrySize, char action, MamaDateTime eventTime, MamaSourceDerivative source)
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookEntry.getUniqueId(), com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_REASON_UNKNOWN, and com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry().
Member Function Documentation
copy()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.copy (MamdaOrderBookEntry copy)
Copy an order book entry object which is an exact and deep copy of the original.
Parameters
copy The MamdaOrderBookEntry to copy.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
setId()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setId (String id)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setSize()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setSize (double size)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setAction()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction (char action)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntriesFromLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
setReason()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setReason (char reason)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setTime()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setTime (MamaDateTime time)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails().
setDetails() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails (MamdaOrderBookEntry copy)
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.setTime().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
setDetails() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails (MamdaBookAtomicLevelEntry copy)
References com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntrySize(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryTime(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setTime().
getId()
String com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId ()
If supported, Order book entry ID (order ID, participant ID, etc.)
Returns
the id.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.assertEqual(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.checkNotExist(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.dump(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
getUniqueId()
String com.wombat.mamda.orderbook.MamdaOrderBookEntry.getUniqueId ()
If supported, Order book entry unique ID (order ID, participant ID, etc.).
The unique ID should be unique throughout the order book. If no explicit unique ID has been set, then it assumed that the basic ID is unique and that is returned.
Returns
The unique entry id
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry().
getSize()
double com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize ()
The size of the order entry.
Returns
the size.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.deleteEntriesFromSource(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.reevaluate(), com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
getAction()
char com.wombat.mamda.orderbook.MamdaOrderBookEntry.getAction ()
Whether to ADD, UPDATE or DELETE the entry.
Returns
char The action.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
getReason()
char com.wombat.mamda.orderbook.MamdaOrderBookEntry.getReason ()
The reason for the order entry.
Returns
the reason
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
getTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookEntry.getTime ()
Time of order book entry update.
Returns
the time.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
setStatus()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setStatus (int value)
Set the status for the entry.
the new status value.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getStatus()
int com.wombat.mamda.orderbook.MamdaOrderBookEntry.getStatus ()
Return the status for the entry.
Returns
the status.
getPrice()
double com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPrice ()
Get the price for this entry.
This method will throw a MamdaOrderBookInvalidEntry if no MamdaPriceLevel is associated with it because order book price information is only stored in MamdaOrderBookPriceLevel objects.
Returns
The price for this entry.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry().
getSide()
char com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSide ()
Get the price for this entry.
This method will throw a MamdaOrderBookInvalidEntry if no MamdaPriceLevel is associated with it because order book price information is only stored in MamdaOrderBookPriceLevel objects.
Returns
The side for this entry.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry().
getPosition()
int com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition (int maxPos)
Get the position in the order book for this entry.
If maxPos is not zero, then the method will return a result no greater than maxPos. This is to prevent searching the entire book when only a limited search is necessary. Note: the logic used in the positional search is to use the number of entries that MamdaOrderBookPriceLevel::getNumEntries() returns for price levels above the entry's price level. -1 is return if the entry is in the book but not currently "visible" (i.e., it is being omitted because the MAMA source is turned off). A MamdaOrderBookInvalidEntry is thrown if the entry is not found in the book.
Parameters
maxPos The maximum position to return;
Returns
The position of this entry in the order book.
References com.wombat.mamda.orderbook.MamdaOrderBook.askIterator(), com.wombat.mamda.orderbook.MamdaOrderBook.bidIterator(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.entryIterator(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getOrderBook(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID.
hashCode()
int com.wombat.mamda.orderbook.MamdaOrderBookEntry.hashCode ()
equals()
boolean com.wombat.mamda.orderbook.MamdaOrderBookEntry.equals (Object obj)
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry().
setPriceLevel()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setPriceLevel (MamdaOrderBookPriceLevel priceLevel)
Set the MamdaOrderBookPriceLevel object to which this entry belongs.
This method is invoked automatically internally, by the MAMDA API, when an entry is added to a price level.
Parameters
priceLevel The price level to be associated with.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry().
getPriceLevel()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel ()
Get the MamdaOrderBookPriceLevel object to which this entry belongs.
Returns
The price level currently associated with this entry.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
getOrderBook()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookEntry.getOrderBook ()
Get the order book for this entry, if possible.
This can only be done if the entry is part of a price level and the price level is part of an order book. null is returned if no order book can be found.
Returns
The order book or null.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getOrderBook().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntry.getCheckSourceState(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition().
setManager()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setManager (MamdaOrderBookEntryManager manager)
Set the MamdaOrderBookEntryManager object to which this entry belongs.
This method is invoked automatically internally, by the MAMDA API, when an entry is added to an entry manager.
Parameters
manager The manager.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getManager()
MamdaOrderBookEntryManager com.wombat.mamda.orderbook.MamdaOrderBookEntry.getManager ()
Get the MamdaOrderBookEntryManager object to which this entry belongs.
Returns
The manager currently associated with this entry.
getSymbol()
String com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSymbol ()
Get the symbol for this entry, if possible.
This can only be done if the entry is part of a price level and the price level is part of an order book. NULL is returned if no symbol can be found.
Returns
The symbol or NULL.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSymbol().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.clear(), and com.wombat.mamda.orderbook.MamdaOrderBookEntryManager.removeEntry().
setSourceDerivative()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setSourceDerivative (MamaSourceDerivative source)
Set the MamaSourceDerivative for this book entry.
The source derivative is used to help determine what the quality of order book entry is and to efficiently identify all of the entries for a given source (e.g., for aggregated order books).
Parameters
source The MAMA source derivative.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getSourceDerivative()
MamaSourceDerivative com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSourceDerivative ()
Return the MamaSourceDerivative for this book entry.
Returns
the MamaSourceDerivative
getSource()
MamaSource com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSource ()
Return the MamaSource for this book entry.
Returns
the source.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.deleteEntriesFromSource().
getCheckSourceState()
boolean com.wombat.mamda.orderbook.MamdaOrderBookEntry.getCheckSourceState ()
Get whether this order book wants to check the source state.
Returns
Whether to check source state.
References com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.getOrderBook().
setQuality()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setQuality (short quality)
Set the entry-level quality factor.
This level, if not MAMA_QUALITY_OK, overrides the source-level level.
Parameters
quality The new entry-level MAMA quality level.
getQuality()
short com.wombat.mamda.orderbook.MamdaOrderBookEntry.getQuality ()
Get the entry-level quality factor.
If the entry-level quality is MAMA_QUALITY_OK, then this method returns the source-level quality.
Returns
The current MAMA quality level.
isVisible()
boolean com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.deleteEntriesFromSource(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getEntryAtPosition(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.reevaluate(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById().
setClosure()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setClosure (Object closure)
Set the order book entry closure handle.
Parameters
closure The closure.
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
getClosure()
Object com.wombat.mamda.orderbook.MamdaOrderBookEntry.getClosure ()
Get the order book entry closure handle.
Returns
The entry closure.
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
assertEqual()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.assertEqual (MamdaOrderBookEntry rhs)
Order book entry equality verification.
A MamdaOrderBookException is thrown if the entries within a price level are not equal, along with the reason for the inequality.
Exceptions
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.assertEqual().
equalId()
boolean com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId (String id)
Whether the id of the entry is equal to the id passed to the method.
Parameters
id The id to compare to the order entry id.
Returns
boolean Whether the id is the same as the order id.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.checkNotExist(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.equals(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
setStrictChecking()
static void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setStrictChecking (boolean strict) static
Enforce strict checking of order book modifications (at the expense of some performance).
This setting is automatically updated by MamdaOrderBook::setStrictChecking().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.setStrictChecking().
setUniqueId()
void com.wombat.mamda.orderbook.MamdaOrderBookEntry.setUniqueId (String uniqueId)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
Member Data Documentation
ACTION_ADD
final char com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD = 'A' static
An enumeration for book entry actions.
Price level actions differ from entry actions because, for example, a price level message with ACTION_UPDATE may consist of entries with ACTION_ADD, ACTION_UPDATE or ACTION_DELETE.A new entry.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntriesFromLevel(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.MamdaOrderBookEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
ACTION_UPDATE
final char com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UPDATE = 'U' static
An updated entry.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
ACTION_DELETE
final char com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE = 'D' static
A deleted entry.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById().
ACTION_UNKNOWN
final char com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UNKNOWN = 'Z' static
Unknown action (error).
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.clear(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().