OpenMAMDA Java API: com.wombat.mamda.MamdaQuoteListener Class Reference
com.wombat.mamda.MamdaQuoteListener Class Reference
MamdaQuoteListener is a class that specializes in handling quote updates.
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.MamdaQuoteRecap, com.wombat.mamda.MamdaQuoteUpdate, com.wombat.mamda.MamdaQuoteGap, and com.wombat.mamda.MamdaQuoteClosing.
Public Member Functions
MamdaQuoteListener ()
Create a specialized quote listener.
void clearCache (MamdaQuoteCache cache)
void addHandler (MamdaQuoteHandler handler)
Add a specialized quote handler.
String getSymbol ()
Get the string symbol for the instrument.
String getPartId ()
Get the participant identifier.
MamaDateTime getSrcTime ()
MamaDateTime getActivityTime ()
MamaDateTime getLineTime ()
Get the line time of the update.
MamaDateTime getSendTime ()
Get the send time of the update.
String getPubId ()
MamaPrice getBidPrice ()
Get the closing bid price.
double getBidSize ()
Get the closing bid size.
String getBidPartId ()
Get the closing bid participant identifier.
MamaPrice getBidClosePrice ()
MamaDateTime getBidCloseDate ()
MamaPrice getBidPrevClosePrice ()
MamaDateTime getBidPrevCloseDate ()
MamaPrice getBidHigh ()
MamaPrice getBidLow ()
MamaPrice getAskPrice ()
Get the closing ask price.
double getAskSize ()
Get the closing ask size.
String getAskPartId ()
Get the closing ask participant identifier.
double getAskDepth ()
double getBidDepth ()
MamaPrice getAskClosePrice ()
MamaDateTime getAskCloseDate ()
MamaPrice getAskPrevClosePrice ()
MamaDateTime getAskPrevCloseDate ()
MamaPrice getAskHigh ()
MamaPrice getAskLow ()
MamaPrice getQuoteMidPrice ()
Get the quote mid price.
String getQuoteQual ()
Get the normalized quote qualifier.
String getQuoteQualNative ()
char getShortSaleBidTick ()
char getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
MamaDateTime getAskTime ()
MamaDateTime getBidTime ()
String getAskIndicator ()
String getBidIndicator ()
long getAskUpdateCount ()
long getBidUpdateCount ()
double getAskYield ()
double getBidYield ()
long getQuoteCount ()
Get the quote count.
long getEventSeqNum ()
MamaDateTime getEventDate ()
Date corresponding to the last quote, as reported by the feed.
MamaDateTime getEventTime ()
Time corresponding to the last quote, as reported by the feed.
String getAskSizesList ()
String getBidSizesList ()
MamaDateTime getEventDateTime ()
MamaDateTime getQuoteDate ()
long getBeginGapSeqNum ()
The starting sequence number of detected missing quotes based on the quote count.
long getEndGapSeqNum ()
The end sequence number of detected missing quotes based on the quote count.
short getSymbolFieldState ()
short getPartIdFieldState ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getLineTimeFieldState ()
short getSendTimeFieldState ()
short getPubIdFieldState ()
short getBidPriceFieldState ()
short getBidSizeFieldState ()
short getBidPartIdFieldState ()
short getBidClosePriceFieldState ()
short getBidCloseDateFieldState ()
short getBidPrevClosePriceFieldState ()
short getBidPrevCloseDateFieldState ()
short getBidHighFieldState ()
short getBidLowFieldState ()
short getAskPriceFieldState ()
short getAskSizeFieldState ()
short getAskPartIdFieldState ()
short getAskClosePriceFieldState ()
short getAskCloseDateFieldState ()
short getAskPrevClosePriceFieldState ()
short getAskPrevCloseDateFieldState ()
short getAskHighFieldState ()
short getAskLowFieldState ()
short getAskDepthFieldState ()
short getBidDepthFieldState ()
short getQuoteMidPriceFieldState ()
short getQuoteQualFieldState ()
short getQuoteQualNativeFieldState ()
short getShortSaleBidTickFieldState ()
short getShortSaleCircuitBreakerFieldState ()
short getAskTimeFieldState ()
short getBidTimeFieldState ()
short getAskIndicatorFieldState ()
short getBidIndicatorFieldState ()
short getAskUpdateCountFieldState ()
short getBidUpdateCountFieldState ()
short getAskYieldFieldState ()
short getBidYieldFieldState ()
short getQuoteCountFieldState ()
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getEventDateFieldState ()
short getEventTimeFieldState ()
short getAskSizesListFieldState ()
short getBidSizesListFieldState ()
short getBeginGapSeqNumFieldState ()
short getEndGapSeqNumFieldState ()
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Public Attributes
MamdaFieldState mGapBeginFieldState = new MamdaFieldState()
MamdaFieldState mGapEndFieldState = new MamdaFieldState()
Protected Attributes
final MamdaQuoteCache mQuoteCache
Detailed Description
MamdaQuoteListener is a class that specializes in handling quote updates.
Developers provide their own implementation of the MamdaQuoteHandler interface and will be delivered notifications for quotes and quote closing prices. An obvious application for this MAMDA class is any kind of quote tick capture application.
Note: The MamdaQuoteListener class caches quote-related field values. Among other reasons, caching of these fields makes it possible to provide complete quote-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaQuoteListener()
com.wombat.mamda.MamdaQuoteListener.MamdaQuoteListener ()
Create a specialized quote listener.
This listener handles quote updates, quote recaps, and quote gap notifications.
References com.wombat.mamda.MamdaQuoteListener.clearCache().
Member Function Documentation
clearCache()
void com.wombat.mamda.MamdaQuoteListener.clearCache (MamdaQuoteCache cache)
References com.wombat.mamda.MamdaFieldState.NOT_INITIALISED.
Referenced by com.wombat.mamda.MamdaQuoteListener.MamdaQuoteListener().
addHandler()
void com.wombat.mamda.MamdaQuoteListener.addHandler (MamdaQuoteHandler handler)
Add a specialized quote handler.
Currently, only one handler can (and must) be registered.
Referenced by com.wombat.mamda.options.MamdaOptionUnderlying.addQuoteHandler(), and com.wombat.mamda.options.MamdaOptionContract.addQuoteHandler().
getSymbol()
String com.wombat.mamda.MamdaQuoteListener.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
getPartId()
String com.wombat.mamda.MamdaQuoteListener.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
getLineTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getPubId()
String com.wombat.mamda.MamdaQuoteListener.getPubId ()
getBidPrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getBidPrice ()
Get the closing bid price.
Returns
Today's closing bid price, after the market has closed and the stock has traded today.
Implements com.wombat.mamda.MamdaQuoteClosing.
Referenced by com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney().
getBidSize()
double com.wombat.mamda.MamdaQuoteListener.getBidSize ()
Get the closing bid size.
Returns
Today's closing bid size, after the market has closed and the stock has traded today.
Implements com.wombat.mamda.MamdaQuoteClosing.
getBidPartId()
String com.wombat.mamda.MamdaQuoteListener.getBidPartId ()
Get the closing bid participant identifier.
Returns
Today's closing bid participant identifier, after the market has closed and the stock has traded today.
Implements com.wombat.mamda.MamdaQuoteClosing.
getBidClosePrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getBidClosePrice ()
getBidCloseDate()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getBidCloseDate ()
getBidPrevClosePrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getBidPrevClosePrice ()
getBidPrevCloseDate()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getBidPrevCloseDate ()
getBidHigh()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getBidHigh ()
getBidLow()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getBidLow ()
getAskPrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getAskPrice ()
Get the closing ask price.
Returns
Today's closing ask price, after the market has closed and the stock has traded today.
Implements com.wombat.mamda.MamdaQuoteClosing.
Referenced by com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney().
getAskSize()
double com.wombat.mamda.MamdaQuoteListener.getAskSize ()
Get the closing ask size.
Returns
Today's closing ask size, after the market has closed and the stock has traded today.
Implements com.wombat.mamda.MamdaQuoteClosing.
getAskPartId()
String com.wombat.mamda.MamdaQuoteListener.getAskPartId ()
Get the closing ask participant identifier.
Returns
Today's closing ask participant identifier, after the market has closed and the stock has traded today.
Implements com.wombat.mamda.MamdaQuoteClosing.
getAskDepth()
double com.wombat.mamda.MamdaQuoteListener.getAskDepth ()
Returns
the quote bid depth
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidDepth()
double com.wombat.mamda.MamdaQuoteListener.getBidDepth ()
Returns
the quote bid depth
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskClosePrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getAskClosePrice ()
getAskCloseDate()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getAskCloseDate ()
getAskPrevClosePrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getAskPrevClosePrice ()
getAskPrevCloseDate()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getAskPrevCloseDate ()
getAskHigh()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getAskHigh ()
getAskLow()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getAskLow ()
getQuoteMidPrice()
MamaPrice com.wombat.mamda.MamdaQuoteListener.getQuoteMidPrice ()
Get the quote mid price.
Returns
The mid price of the current quote. Usually, this is the average of the bid and ask prices, but some exchanges provide this field explicitly (e.g. LSE).
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteQual()
String com.wombat.mamda.MamdaQuoteListener.getQuoteQual ()
Get the normalized quote qualifier.
Returns
A normalized set of qualifiers for the last quote for the security. This field may contain multiple string values, separated by the colon(:) character.
See also
MamdaQuoteUpdate::getQuoteQual
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteQualNative()
String com.wombat.mamda.MamdaQuoteListener.getQuoteQualNative ()
See also
MamdaQuoteUpdate::getQuoteQualNative()
Implements com.wombat.mamda.MamdaQuoteRecap.
getShortSaleBidTick()
char com.wombat.mamda.MamdaQuoteListener.getShortSaleBidTick ()
See also
MamdaQuoteUpdate::getShortSaleBidTick()
Implements com.wombat.mamda.MamdaQuoteRecap.
getShortSaleCircuitBreaker()
char com.wombat.mamda.MamdaQuoteListener.getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
Returns
ShortSaleCircuitBreaker
See also
MamdaQuoteUpdate::getShortSaleCircuitBreaker()
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getAskTime ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getBidTime ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskIndicator()
String com.wombat.mamda.MamdaQuoteListener.getAskIndicator ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidIndicator()
String com.wombat.mamda.MamdaQuoteListener.getBidIndicator ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskUpdateCount()
long com.wombat.mamda.MamdaQuoteListener.getAskUpdateCount ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidUpdateCount()
long com.wombat.mamda.MamdaQuoteListener.getBidUpdateCount ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskYield()
double com.wombat.mamda.MamdaQuoteListener.getAskYield ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidYield()
double com.wombat.mamda.MamdaQuoteListener.getBidYield ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteCount()
long com.wombat.mamda.MamdaQuoteListener.getQuoteCount ()
Get the quote count.
Returns
The number of quotes generated for this security during the current trading session.
Implements com.wombat.mamda.MamdaQuoteRecap.
getEventSeqNum()
long com.wombat.mamda.MamdaQuoteListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
getEventDate()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getEventDate ()
Date corresponding to the last quote, as reported by the feed.
Implements com.wombat.mamda.MamdaQuoteRecap.
getEventTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getEventTime ()
Time corresponding to the last quote, as reported by the feed.
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskSizesList()
String com.wombat.mamda.MamdaQuoteListener.getAskSizesList ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidSizesList()
String com.wombat.mamda.MamdaQuoteListener.getBidSizesList ()
Implements com.wombat.mamda.MamdaQuoteRecap.
getEventDateTime()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getEventDateTime ()
getQuoteDate()
MamaDateTime com.wombat.mamda.MamdaQuoteListener.getQuoteDate ()
getBeginGapSeqNum()
long com.wombat.mamda.MamdaQuoteListener.getBeginGapSeqNum ()
The starting sequence number of detected missing quotes based on the quote count.
Implements com.wombat.mamda.MamdaQuoteGap.
getEndGapSeqNum()
long com.wombat.mamda.MamdaQuoteListener.getEndGapSeqNum ()
The end sequence number of detected missing quotes based on the quote count.
Implements com.wombat.mamda.MamdaQuoteGap.
getSymbolFieldState()
short com.wombat.mamda.MamdaQuoteListener.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getPartIdFieldState()
short com.wombat.mamda.MamdaQuoteListener.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getSrcTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getLineTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getPubIdFieldState()
short com.wombat.mamda.MamdaQuoteListener.getPubIdFieldState ()
getBidPriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidPriceFieldState ()
Returns
the bid price Field State
Implements com.wombat.mamda.MamdaQuoteClosing.
getBidSizeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidSizeFieldState ()
Returns
the bid size Field State
Implements com.wombat.mamda.MamdaQuoteClosing.
getBidPartIdFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidPartIdFieldState ()
Returns
the bid part ID Field State
Implements com.wombat.mamda.MamdaQuoteClosing.
getBidClosePriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidClosePriceFieldState ()
getBidCloseDateFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidCloseDateFieldState ()
getBidPrevClosePriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidPrevClosePriceFieldState ()
getBidPrevCloseDateFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidPrevCloseDateFieldState ()
getBidHighFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidHighFieldState ()
getBidLowFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidLowFieldState ()
getAskPriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskPriceFieldState ()
Returns
the ask price Field State
Implements com.wombat.mamda.MamdaQuoteClosing.
getAskSizeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskSizeFieldState ()
Returns
the ask size Field State
Implements com.wombat.mamda.MamdaQuoteClosing.
getAskPartIdFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskPartIdFieldState ()
Returns
the ask part ID Field State
Implements com.wombat.mamda.MamdaQuoteClosing.
getAskClosePriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskClosePriceFieldState ()
getAskCloseDateFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskCloseDateFieldState ()
getAskPrevClosePriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskPrevClosePriceFieldState ()
getAskPrevCloseDateFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskPrevCloseDateFieldState ()
getAskHighFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskHighFieldState ()
getAskLowFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskLowFieldState ()
getAskDepthFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskDepthFieldState ()
Returns
the ask depth Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidDepthFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidDepthFieldState ()
Returns
the bid depth Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteMidPriceFieldState()
short com.wombat.mamda.MamdaQuoteListener.getQuoteMidPriceFieldState ()
Returns
the quote mid price Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteQualFieldState()
short com.wombat.mamda.MamdaQuoteListener.getQuoteQualFieldState ()
Returns
the quote qual Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteQualNativeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getQuoteQualNativeFieldState ()
Returns
the quote qual native Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getShortSaleBidTickFieldState()
short com.wombat.mamda.MamdaQuoteListener.getShortSaleBidTickFieldState ()
Returns
the short sale bid tick Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getShortSaleCircuitBreakerFieldState()
short com.wombat.mamda.MamdaQuoteListener.getShortSaleCircuitBreakerFieldState ()
Returns
Returns the FieldState, always MODIFIED.
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskTimeFieldState ()
Returns
the ask time Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidTimeFieldState ()
Returns
the bid time Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskIndicatorFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskIndicatorFieldState ()
Returns
the ask indicator Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidIndicatorFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidIndicatorFieldState ()
Returns
the bid indicator Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskUpdateCountFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskUpdateCountFieldState ()
Returns
the ask update count Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidUpdateCountFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidUpdateCountFieldState ()
Returns
the bid update count Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskYieldFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskYieldFieldState ()
Returns
the ask yield Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidYieldFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidYieldFieldState ()
Returns
the bid yield Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getQuoteCountFieldState()
short com.wombat.mamda.MamdaQuoteListener.getQuoteCountFieldState ()
Returns
the quote count Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getEventSeqNumFieldState()
short com.wombat.mamda.MamdaQuoteListener.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getEventDateFieldState()
short com.wombat.mamda.MamdaQuoteListener.getEventDateFieldState ()
Returns
event date Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getEventTimeFieldState()
short com.wombat.mamda.MamdaQuoteListener.getEventTimeFieldState ()
Returns
the event time Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getAskSizesListFieldState()
short com.wombat.mamda.MamdaQuoteListener.getAskSizesListFieldState ()
Returns
the ask sizes list Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBidSizesListFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBidSizesListFieldState ()
Returns
the bid sizes list Field State
Implements com.wombat.mamda.MamdaQuoteRecap.
getBeginGapSeqNumFieldState()
short com.wombat.mamda.MamdaQuoteListener.getBeginGapSeqNumFieldState ()
Returns
the begin gap seq num Field State
Implements com.wombat.mamda.MamdaQuoteGap.
References com.wombat.mamda.MamdaFieldState.getState().
getEndGapSeqNumFieldState()
short com.wombat.mamda.MamdaQuoteListener.getEndGapSeqNumFieldState ()
Returns
the end gap seq num Field State
Implements com.wombat.mamda.MamdaQuoteGap.
References com.wombat.mamda.MamdaFieldState.getState().
onMsg()
void com.wombat.mamda.MamdaQuoteListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
NB! For internal use only.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaCommonFields.ACTIVITY_TIME, com.wombat.mamda.MamdaQuoteFields.ASK_CLOSE_DATE, com.wombat.mamda.MamdaQuoteFields.ASK_CLOSE_PRICE, com.wombat.mamda.MamdaQuoteFields.ASK_DEPTH, com.wombat.mamda.MamdaQuoteFields.ASK_HIGH, com.wombat.mamda.MamdaQuoteFields.ASK_INDICATOR, com.wombat.mamda.MamdaQuoteFields.ASK_LOW, com.wombat.mamda.MamdaQuoteFields.ASK_PART_ID, com.wombat.mamda.MamdaQuoteFields.ASK_PREV_CLOSE_DATE, com.wombat.mamda.MamdaQuoteFields.ASK_PREV_CLOSE_PRICE, com.wombat.mamda.MamdaQuoteFields.ASK_PRICE, com.wombat.mamda.MamdaQuoteFields.ASK_SIZE, com.wombat.mamda.MamdaQuoteFields.ASK_SIZES_LIST, com.wombat.mamda.MamdaQuoteFields.ASK_TIME, com.wombat.mamda.MamdaQuoteFields.ASK_UPDATE_COUNT, com.wombat.mamda.MamdaQuoteFields.ASK_YIELD, com.wombat.mamda.MamdaQuoteFields.BID_CLOSE_DATE, com.wombat.mamda.MamdaQuoteFields.BID_CLOSE_PRICE, com.wombat.mamda.MamdaQuoteFields.BID_DEPTH, com.wombat.mamda.MamdaQuoteFields.BID_HIGH, com.wombat.mamda.MamdaQuoteFields.BID_INDICATOR, com.wombat.mamda.MamdaQuoteFields.BID_LOW, com.wombat.mamda.MamdaQuoteFields.BID_PART_ID, com.wombat.mamda.MamdaQuoteFields.BID_PREV_CLOSE_DATE, com.wombat.mamda.MamdaQuoteFields.BID_PREV_CLOSE_PRICE, com.wombat.mamda.MamdaQuoteFields.BID_PRICE, com.wombat.mamda.MamdaQuoteFields.BID_SIZE, com.wombat.mamda.MamdaQuoteFields.BID_SIZES_LIST, com.wombat.mamda.MamdaQuoteFields.BID_TICK, com.wombat.mamda.MamdaQuoteFields.BID_TIME, com.wombat.mamda.MamdaQuoteFields.BID_UPDATE_COUNT, com.wombat.mamda.MamdaQuoteFields.BID_YIELD, com.wombat.mamda.MamdaQuoteFields.getMaxFid(), com.wombat.mamda.MamdaFieldState.getState(), com.wombat.mamda.MamdaQuoteFields.isSet(), com.wombat.mamda.MamdaCommonFields.ISSUE_SYMBOL, com.wombat.mamda.MamdaCommonFields.LINE_TIME, com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaQuoteListener.mQuoteCache, com.wombat.mamda.MamdaFieldState.NOT_INITIALISED, com.wombat.mamda.MamdaFieldState.NOT_MODIFIED, com.wombat.mamda.MamdaQuoteHandler.onQuoteGap(), com.wombat.mamda.MamdaQuoteHandler.onQuoteRecap(), com.wombat.mamda.MamdaQuoteHandler.onQuoteUpdate(), com.wombat.mamda.MamdaCommonFields.PART_ID, com.wombat.mamda.MamdaCommonFields.PUB_ID, com.wombat.mamda.MamdaQuoteFields.QUOTE_COUNT, com.wombat.mamda.MamdaQuoteFields.QUOTE_DATE, com.wombat.mamda.MamdaQuoteFields.QUOTE_QUAL, com.wombat.mamda.MamdaQuoteFields.QUOTE_QUAL_NATIVE, com.wombat.mamda.MamdaQuoteFields.QUOTE_SEQ_NUM, com.wombat.mamda.MamdaQuoteFields.QUOTE_TIME, com.wombat.mamda.MamdaCommonFields.SEND_TIME, com.wombat.mamda.MamdaFieldState.setState(), com.wombat.mamda.MamdaQuoteFields.SHORT_SALE_BID_TICK, com.wombat.mamda.MamdaQuoteFields.SHORT_SALE_CIRCUIT_BREAKER, com.wombat.mamda.MamdaCommonFields.SRC_TIME, and com.wombat.mamda.MamdaCommonFields.SYMBOL.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
Member Data Documentation
mQuoteCache
final MamdaQuoteCache com.wombat.mamda.MamdaQuoteListener.mQuoteCache protected
Initial value:
=
                            new MamdaQuoteCache ()
Referenced by com.wombat.mamda.MamdaQuoteListener.onMsg().
mGapBeginFieldState
MamdaFieldState com.wombat.mamda.MamdaQuoteListener.mGapBeginFieldState = new MamdaFieldState()
mGapEndFieldState
MamdaFieldState com.wombat.mamda.MamdaQuoteListener.mGapEndFieldState = new MamdaFieldState()