OpenMAMDA Java API: com.wombat.mamda.MamdaTradeListener Class Reference
com.wombat.mamda.MamdaTradeListener Class Reference
MamdaTradeListener is a class that specializes in handling trade updates.
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.MamdaTradeRecap, com.wombat.mamda.MamdaTradeReport, com.wombat.mamda.MamdaTradeGap, com.wombat.mamda.MamdaTradeCancelOrError, com.wombat.mamda.MamdaTradeCorrection, and com.wombat.mamda.MamdaTradeClosing.
Classes
class TradeLineTime
class TradeSendTime
Public Member Functions
MamdaTradeListener ()
Create a specialized trade listener.
void printCache (MamdaTradeCache cache)
void clearCache (MamdaTradeCache cache)
void addHandler (MamdaTradeHandler handler)
Add a specialized trade handler.
String getSymbol ()
Get the string symbol for the instrument.
String getPartId ()
Get the participant identifier.
MamaDateTime getSrcTime ()
MamaDateTime getActivityTime ()
MamaDateTime getLineTime ()
Get the line time of the update.
MamaDateTime getSendTime ()
Get the send time of the update.
String getPubId ()
long getEventSeqNum ()
MamaDateTime getEventTime ()
MamaPrice getLastPrice ()
double getLastVolume ()
char getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
char getOrigShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
char getCorrShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
String getLastPartId ()
MamaDateTime getLastDate ()
MamaDateTime getLastTime ()
MamaDateTime getLastDateTime ()
MamaPrice getIrregPrice ()
double getIrregVolume ()
String getIrregPartId ()
MamaDateTime getIrregTime ()
MamaDateTime getTradeDate ()
double getAccVolume ()
double getOffExAccVolume ()
double getOnExAccVolume ()
MamaPrice getNetChange ()
double getPctChange ()
String getTradeDirection ()
String getSide ()
MamaPrice getOpenPrice ()
MamaPrice getHighPrice ()
MamaPrice getLowPrice ()
MamaPrice getClosePrice ()
MamaPrice getPrevClosePrice ()
MamaDateTime getPrevCloseDate ()
MamaPrice getAdjPrevClose ()
long getBlockCount ()
double getBlockVolume ()
double getVwap ()
double getOffExVwap ()
double getOnExVwap ()
double getTotalValue ()
double getOffExTotalValue ()
double getOnExTotalValue ()
double getStdDev ()
double getStdDevSum ()
double getStdDevSumSquares ()
long getOrderId ()
MamaPrice getSettlePrice ()
MamaDateTime getSettleDate ()
MamaPrice getTradePrice ()
double getTradeVolume ()
String getTradePartId ()
String getTradeId ()
String getOrigTradeId ()
String getCorrTradeId ()
String getTradeQual ()
String getTradeQualNativeStr ()
String getTradeCondition ()
long getTradeSellersSaleDays ()
char getTradeStopStock ()
String getTradeExecVenue ()
MamaPrice getOffExchangeTradePrice ()
MamaPrice getOnExchangeTradePrice ()
long getTradeCount ()
String getTradeUnits ()
long getLastSeqNum ()
long getHighSeqNum ()
long getLowSeqNum ()
long getTotalVolumeSeqNum ()
String getCurrencyCode ()
boolean getIsIrregular ()
long getBeginGapSeqNum ()
long getEndGapSeqNum ()
boolean getIsCancel ()
long getOrigSeqNum ()
double getOrigPrice ()
double getOrigVolume ()
String getOrigPartId ()
String getOrigQual ()
String getOrigQualNative ()
String getOrigCondition ()
long getOrigSellersSaleDays ()
char getOrigStopStock ()
double getCorrPrice ()
double getCorrVolume ()
String getCorrPartId ()
String getCorrQual ()
String getCorrQualNative ()
String getCorrCondition ()
long getCorrSellersSaleDays ()
char getCorrStopStock ()
boolean getIsIndicative ()
boolean IsIrregular ()
IsIrregular Checks the explicit and implicit irregular fields.
short getSymbolFieldState ()
short getPartIdFieldState ()
short getSrcTimeFieldState ()
short getActivityTimeFieldState ()
short getLineTimeFieldState ()
short getSendTimeFieldState ()
short getShortSaleCircuitBreakerFieldState ()
short getOrigShortSaleCircuitBreakerFieldState ()
short getCorrShortSaleCircuitBreakerFieldState ()
short getPubIdFieldState ()
short getEventSeqNumFieldState ()
short getEventTimeFieldState ()
short getLastPriceFieldState ()
short getLastVolumeFieldState ()
short getLastPartIdFieldState ()
short getLastDateFieldState ()
short getLastTimeFieldState ()
short getIrregPriceFieldState ()
short getIrregVolumeFieldState ()
short getIrregPartIdFieldState ()
short getIrregTimeFieldState ()
short getAccVolumeFieldState ()
short getOffExAccVolumeFieldState ()
short getOnExAccVolumeFieldState ()
short getNetChangeFieldState ()
short getPctChangeFieldState ()
short getTradeDirectionFieldState ()
short getSideFieldState ()
short getOpenPriceFieldState ()
short getHighPriceFieldState ()
short getLowPriceFieldState ()
short getClosePriceFieldState ()
short getPrevClosePriceFieldState ()
short getPrevCloseDateFieldState ()
short getAdjPrevCloseFieldState ()
short getBlockCountFieldState ()
short getBlockVolumeFieldState ()
short getVwapFieldState ()
short getOffExVwapFieldState ()
short getOnExVwapFieldState ()
short getTotalValueFieldState ()
short getOffExTotalValueFieldState ()
short getOnExTotalValueFieldState ()
short getStdDevFieldState ()
short getStdDevSumFieldState ()
short getStdDevSumSquaresFieldState ()
short getOrderIdFieldState ()
short getSettlePriceFieldState ()
short getSettleDateFieldState ()
short getTradePriceFieldState ()
short getTradeVolumeFieldState ()
short getTradePartIdFieldState ()
short getTradeIdFieldState ()
short getOrigTradeIdFieldState ()
short getCorrTradeIdFieldState ()
short getTradeQualFieldState ()
short getTradeQualNativeStrFieldState ()
short getTradeConditionFieldState ()
short getTradeSellersSaleDaysFieldState ()
short getTradeStopStockFieldState ()
short getTradeExecVenueFieldState ()
short getOffExchangeTradePriceFieldState ()
short getOnExchangeTradePriceFieldState ()
short getTradeCountFieldState ()
short getTradeUnitsFieldState ()
short getLastSeqNumFieldState ()
short getHighSeqNumFieldState ()
short getLowSeqNumFieldState ()
short getTotalVolumeSeqNumFieldState ()
short getCurrencyCodeFieldState ()
short getIsIrregularFieldState ()
short getBeginGapSeqNumFieldState ()
short getEndGapSeqNumFieldState ()
short getIsCancelFieldState ()
short getOrigSeqNumFieldState ()
short getOrigPriceFieldState ()
short getOrigVolumeFieldState ()
short getOrigPartIdFieldState ()
short getOrigQualFieldState ()
short getOrigQualNativeFieldState ()
short getOrigConditionFieldState ()
short getOrigSellersSaleDaysFieldState ()
short getOrigStopStockFieldState ()
short getCorrPriceFieldState ()
short getCorrVolumeFieldState ()
short getCorrPartIdFieldState ()
short getCorrQualFieldState ()
short getCorrQualNativeFieldState ()
short getCorrConditionFieldState ()
short getCorrSellersSaleDaysFieldState ()
short getCorrStopStockFieldState ()
short getIsIndicativeFieldState ()
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Protected Attributes
final MamdaTradeCache mTradeCache
Detailed Description
MamdaTradeListener is a class that specializes in handling trade updates.
Developers provide their own implementation of the MamdaTradeHandler interface and will be delivered notifications for trades, trade cancels/error/corrections, and trade closing prices. An obvious application for this MAMDA class is any kind of trade tick capture application.
Note: The MamdaTradeListener class caches trade-related field values. Among other reasons, caching of these fields makes it possible to provide complete trade-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaTradeListener()
com.wombat.mamda.MamdaTradeListener.MamdaTradeListener ()
Create a specialized trade listener.
This listener handles trade reports, trade recaps, trade errors/cancels, trade corrections, and trade gap notifications.
References com.wombat.mamda.MamdaTradeListener.clearCache().
Member Function Documentation
printCache()
void com.wombat.mamda.MamdaTradeListener.printCache (MamdaTradeCache cache)
clearCache()
void com.wombat.mamda.MamdaTradeListener.clearCache (MamdaTradeCache cache)
References com.wombat.mamda.MamdaFieldState.NOT_INITIALISED, com.wombat.mamda.MamdaFieldState.setState(), and com.wombat.mamda.MamdaTradeSide.TRADE_SIDE_UNKNOWN.
Referenced by com.wombat.mamda.MamdaTradeListener.MamdaTradeListener().
addHandler()
void com.wombat.mamda.MamdaTradeListener.addHandler (MamdaTradeHandler handler)
Add a specialized trade handler.
Currently, only one handler can (and must) be registered.
Referenced by com.wombat.mamda.options.MamdaOptionUnderlying.addTradeHandler(), and com.wombat.mamda.options.MamdaOptionContract.addTradeHandler().
getSymbol()
String com.wombat.mamda.MamdaTradeListener.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
getPartId()
String com.wombat.mamda.MamdaTradeListener.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getSrcTime ()
See also
MamdaBasicEvent::getSrcTime()
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getActivityTime ()
See also
MamdaBasicEvent::getActivityTime()
Implements com.wombat.mamda.MamdaBasicEvent.
getLineTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getPubId()
String com.wombat.mamda.MamdaTradeListener.getPubId ()
getEventSeqNum()
long com.wombat.mamda.MamdaTradeListener.getEventSeqNum ()
See also
MamdaBasicEvent::getEventSeqNum()
Implements com.wombat.mamda.MamdaTradeRecap.
getEventTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getEventTime ()
See also
MamdaBasicEvent::getEventTime()
Implements com.wombat.mamda.MamdaBasicEvent.
getLastPrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getLastPrice ()
See also
MamdaTradeRecap::getLastPrice()
Implements com.wombat.mamda.MamdaTradeRecap.
Referenced by com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney().
getLastVolume()
double com.wombat.mamda.MamdaTradeListener.getLastVolume ()
See also
MamdaTradeRecap::getLastVolume()
Implements com.wombat.mamda.MamdaTradeRecap.
getShortSaleCircuitBreaker()
char com.wombat.mamda.MamdaTradeListener.getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
Returns
ShortSaleCircuitBreaker
See also
MamdaTradeReport::getShortSaleCircuitBreaker()
Implements com.wombat.mamda.MamdaTradeRecap.
getOrigShortSaleCircuitBreaker()
char com.wombat.mamda.MamdaTradeListener.getOrigShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
Returns
ShortSaleCircuitBreaker
See also
MamdaTradeReport::getOrigShortSaleCircuitBreaker()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getCorrShortSaleCircuitBreaker()
char com.wombat.mamda.MamdaTradeListener.getCorrShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
Returns
ShortSaleCircuitBreaker
See also
MamdaTradeReport::getCorrShortSaleCircuitBreaker()
Implements com.wombat.mamda.MamdaTradeCorrection.
getLastPartId()
String com.wombat.mamda.MamdaTradeListener.getLastPartId ()
See also
MamdaTradeRecap::getLastPartId()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastDate()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getLastDate ()
See also
MamdaTradeRecap::getLastDate()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getLastTime ()
See also
MamdaTradeRecap::getLastTime()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastDateTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getLastDateTime ()
See also
MamdaTradeRecap::getLastTime()
getIrregPrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getIrregPrice ()
See also
MamdaTradeRecap::getIrregPrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregVolume()
double com.wombat.mamda.MamdaTradeListener.getIrregVolume ()
See also
MamdaTradeRecap::getIrregVolume()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregPartId()
String com.wombat.mamda.MamdaTradeListener.getIrregPartId ()
See also
MamdaTradeRecap::getIrregPartId()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregTime()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getIrregTime ()
See also
MamdaTradeRecap::getLastTime()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeDate()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getTradeDate ()
getAccVolume()
double com.wombat.mamda.MamdaTradeListener.getAccVolume ()
See also
MamdaTradeRecap::getAccVolume()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExAccVolume()
double com.wombat.mamda.MamdaTradeListener.getOffExAccVolume ()
See also
MamdaTradeRecap::getOffExAccVolume()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExAccVolume()
double com.wombat.mamda.MamdaTradeListener.getOnExAccVolume ()
See also
MamdaTradeRecap::getOnExAccVolume()
Implements com.wombat.mamda.MamdaTradeRecap.
getNetChange()
MamaPrice com.wombat.mamda.MamdaTradeListener.getNetChange ()
See also
MamdaTradeRecap::getNetChange()
Implements com.wombat.mamda.MamdaTradeRecap.
getPctChange()
double com.wombat.mamda.MamdaTradeListener.getPctChange ()
See also
MamdaTradeRecap::getPctChange()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeDirection()
String com.wombat.mamda.MamdaTradeListener.getTradeDirection ()
See also
MamdaTradeRecap::getTradeDirection()
Implements com.wombat.mamda.MamdaTradeRecap.
getSide()
String com.wombat.mamda.MamdaTradeListener.getSide ()
See also
MamdaTradeRecap::getSide()
Implements com.wombat.mamda.MamdaTradeRecap.
getOpenPrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getOpenPrice ()
See also
MamdaTradeRecap::getOpenPrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getHighPrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getHighPrice ()
See also
MamdaTradeRecap::getHighPrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getLowPrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getLowPrice ()
See also
MamdaTradeRecap::getLowPrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getClosePrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getClosePrice ()
See also
MamdaTradeRecap::getClosePrice()
Implements com.wombat.mamda.MamdaTradeClosing.
getPrevClosePrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getPrevClosePrice ()
See also
MamdaTradeRecap::getPrevClosePrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getPrevCloseDate()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getPrevCloseDate ()
See also
MamdaTradeRecap::getPrevCloseDate()
Implements com.wombat.mamda.MamdaTradeRecap.
getAdjPrevClose()
MamaPrice com.wombat.mamda.MamdaTradeListener.getAdjPrevClose ()
See also
MamdaTradeRecap::getAdjPrevClose()
Implements com.wombat.mamda.MamdaTradeRecap.
getBlockCount()
long com.wombat.mamda.MamdaTradeListener.getBlockCount ()
See also
MamdaTradeRecap::getBlockCount()
Implements com.wombat.mamda.MamdaTradeRecap.
getBlockVolume()
double com.wombat.mamda.MamdaTradeListener.getBlockVolume ()
See also
MamdaTradeRecap::getBlockVolume()
Implements com.wombat.mamda.MamdaTradeRecap.
getVwap()
double com.wombat.mamda.MamdaTradeListener.getVwap ()
See also
MamdaTradeRecap::getVwap()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExVwap()
double com.wombat.mamda.MamdaTradeListener.getOffExVwap ()
See also
MamdaTradeRecap::getOffExVwap()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExVwap()
double com.wombat.mamda.MamdaTradeListener.getOnExVwap ()
See also
MamdaTradeRecap::getOnExVwap()
Implements com.wombat.mamda.MamdaTradeRecap.
getTotalValue()
double com.wombat.mamda.MamdaTradeListener.getTotalValue ()
See also
MamdaTradeRecap::getTotalValue()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExTotalValue()
double com.wombat.mamda.MamdaTradeListener.getOffExTotalValue ()
See also
MamdaTradeRecap::getOffExTotalValue()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExTotalValue()
double com.wombat.mamda.MamdaTradeListener.getOnExTotalValue ()
See also
MamdaTradeRecap::getOnExTotalValue()
Implements com.wombat.mamda.MamdaTradeRecap.
getStdDev()
double com.wombat.mamda.MamdaTradeListener.getStdDev ()
See also
MamdaTradeRecap::getStdDev()
Implements com.wombat.mamda.MamdaTradeRecap.
getStdDevSum()
double com.wombat.mamda.MamdaTradeListener.getStdDevSum ()
See also
MamdaTradeRecap::getStdDevSum()
Implements com.wombat.mamda.MamdaTradeRecap.
getStdDevSumSquares()
double com.wombat.mamda.MamdaTradeListener.getStdDevSumSquares ()
See also
MamdaTradeRecap::getStdDevSumSquares()
Implements com.wombat.mamda.MamdaTradeRecap.
getOrderId()
long com.wombat.mamda.MamdaTradeListener.getOrderId ()
See also
MamdaTradeRecap::getOrderId
Implements com.wombat.mamda.MamdaTradeRecap.
getSettlePrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getSettlePrice ()
See also
MamdaTradeRecap::getSettlePrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getSettleDate()
MamaDateTime com.wombat.mamda.MamdaTradeListener.getSettleDate ()
See also
MamdaTradeRecap::getSettleDate()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradePrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getTradePrice ()
See also
MamdaTradeReport::getTradePrice()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeVolume()
double com.wombat.mamda.MamdaTradeListener.getTradeVolume ()
See also
MamdaTradeReport::getTradeVolume()
Implements com.wombat.mamda.MamdaTradeReport.
getTradePartId()
String com.wombat.mamda.MamdaTradeListener.getTradePartId ()
See also
MamdaTradeReport::getTradePartId()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeId()
String com.wombat.mamda.MamdaTradeListener.getTradeId ()
See also
MamdaTradeReport::getTradeId()
Implements com.wombat.mamda.MamdaTradeReport.
getOrigTradeId()
String com.wombat.mamda.MamdaTradeListener.getOrigTradeId ()
See also
MamdaTradeCancelOrError::getOrigTradeId()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getCorrTradeId()
String com.wombat.mamda.MamdaTradeListener.getCorrTradeId ()
See also
MamdaTradeCorrection::getCorrTradeId()
Implements com.wombat.mamda.MamdaTradeCorrection.
getTradeQual()
String com.wombat.mamda.MamdaTradeListener.getTradeQual ()
See also
MamdaTradeReport::getTradeQual()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeQualNativeStr()
String com.wombat.mamda.MamdaTradeListener.getTradeQualNativeStr ()
See also
MamdaTradeReport::getTradeQualNativeStr()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeCondition()
String com.wombat.mamda.MamdaTradeListener.getTradeCondition ()
See also
MamdaTradeReport::getTradeCondition()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeSellersSaleDays()
long com.wombat.mamda.MamdaTradeListener.getTradeSellersSaleDays ()
See also
MamdaTradeReport::getTradeSellersSaleDays()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeStopStock()
char com.wombat.mamda.MamdaTradeListener.getTradeStopStock ()
See also
MamdaTradeReport::getTradeStopStock()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeExecVenue()
String com.wombat.mamda.MamdaTradeListener.getTradeExecVenue ()
See also
MamdaTradeReport::gettradeExecVenue()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExchangeTradePrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getOffExchangeTradePrice ()
See also
MamdaTradeReport::geOffExchangetTradePrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExchangeTradePrice()
MamaPrice com.wombat.mamda.MamdaTradeListener.getOnExchangeTradePrice ()
See also
MamdaTradeReport::getOnExchangeTradePrice()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeCount()
long com.wombat.mamda.MamdaTradeListener.getTradeCount ()
See also
MamdaTradeRecap::getTradeCount()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeUnits()
String com.wombat.mamda.MamdaTradeListener.getTradeUnits ()
See also
MamdaTradeRecap::getTradeUnits()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastSeqNum()
long com.wombat.mamda.MamdaTradeListener.getLastSeqNum ()
See also
MamdaTradeRecap::getLastSeqNum()
Implements com.wombat.mamda.MamdaTradeRecap.
getHighSeqNum()
long com.wombat.mamda.MamdaTradeListener.getHighSeqNum ()
See also
MamdaTradeRecap::getHighSeqNum()
Implements com.wombat.mamda.MamdaTradeRecap.
getLowSeqNum()
long com.wombat.mamda.MamdaTradeListener.getLowSeqNum ()
See also
MamdaTradeRecap::getLowSeqNum()
Implements com.wombat.mamda.MamdaTradeRecap.
getTotalVolumeSeqNum()
long com.wombat.mamda.MamdaTradeListener.getTotalVolumeSeqNum ()
See also
MamdaTradeRecap::getTotalVolumeSeqNum()
Implements com.wombat.mamda.MamdaTradeRecap.
getCurrencyCode()
String com.wombat.mamda.MamdaTradeListener.getCurrencyCode ()
See also
MamdaTradeRecap::getCurrencyCode()
Implements com.wombat.mamda.MamdaTradeRecap.
getIsIrregular()
boolean com.wombat.mamda.MamdaTradeListener.getIsIrregular ()
See also
MamdaTradeReport::getIsIrregular()
Implements com.wombat.mamda.MamdaTradeReport.
getBeginGapSeqNum()
long com.wombat.mamda.MamdaTradeListener.getBeginGapSeqNum ()
See also
MamdaTradeGap::getBeginGapSeqNum()
Implements com.wombat.mamda.MamdaTradeGap.
getEndGapSeqNum()
long com.wombat.mamda.MamdaTradeListener.getEndGapSeqNum ()
See also
MamdaTradeGap::getEndGapSeqNum()
Implements com.wombat.mamda.MamdaTradeGap.
getIsCancel()
boolean com.wombat.mamda.MamdaTradeListener.getIsCancel ()
See also
MamdaTradeCancelOrError::getIsCancel()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigSeqNum()
long com.wombat.mamda.MamdaTradeListener.getOrigSeqNum ()
See also
MamdaTradeCancelOrError::getOrigSeqNum()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigPrice()
double com.wombat.mamda.MamdaTradeListener.getOrigPrice ()
See also
MamdaTradeCancelOrError::getOrigPrice()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigVolume()
double com.wombat.mamda.MamdaTradeListener.getOrigVolume ()
See also
MamdaTradeCancelOrError::getOrigVolume()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigPartId()
String com.wombat.mamda.MamdaTradeListener.getOrigPartId ()
See also
MamdaTradeCancelOrError::getOrigPartId()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigQual()
String com.wombat.mamda.MamdaTradeListener.getOrigQual ()
See also
MamdaTradeCancelOrError::getOrigQual()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigQualNative()
String com.wombat.mamda.MamdaTradeListener.getOrigQualNative ()
See also
MamdaTradeCancelOrError::getOrigQualNative()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigCondition()
String com.wombat.mamda.MamdaTradeListener.getOrigCondition ()
See also
MamdaTradeCancelOrError::getOrigCondition()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigSellersSaleDays()
long com.wombat.mamda.MamdaTradeListener.getOrigSellersSaleDays ()
See also
MamdaTradeCancelOrError::getOrigSellersSaleDays()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigStopStock()
char com.wombat.mamda.MamdaTradeListener.getOrigStopStock ()
See also
MamdaTradeCancelOrError::getOrigStopStock()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getCorrPrice()
double com.wombat.mamda.MamdaTradeListener.getCorrPrice ()
See also
MamdaTradeCorrection::getCorrPrice()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrVolume()
double com.wombat.mamda.MamdaTradeListener.getCorrVolume ()
See also
MamdaTradeCorrection::getCorrVolume()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrPartId()
String com.wombat.mamda.MamdaTradeListener.getCorrPartId ()
See also
MamdaTradeCorrection::getCorrPartId()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrQual()
String com.wombat.mamda.MamdaTradeListener.getCorrQual ()
See also
MamdaTradeCorrection::getCorrQual()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrQualNative()
String com.wombat.mamda.MamdaTradeListener.getCorrQualNative ()
See also
MamdaTradeCorrection::getCorrQualNative()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrCondition()
String com.wombat.mamda.MamdaTradeListener.getCorrCondition ()
See also
MamdaTradeCorrection::getCorrCondition()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrSellersSaleDays()
long com.wombat.mamda.MamdaTradeListener.getCorrSellersSaleDays ()
See also
MamdaTradeCorrection::getCorrSellersSaleDays()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrStopStock()
char com.wombat.mamda.MamdaTradeListener.getCorrStopStock ()
See also
MamdaTradeCorrection::getCorrStopStock()
Implements com.wombat.mamda.MamdaTradeCorrection.
getIsIndicative()
boolean com.wombat.mamda.MamdaTradeListener.getIsIndicative ()
See also
MamdaTradeClosing::getIsIndicative()
Implements com.wombat.mamda.MamdaTradeClosing.
IsIrregular()
boolean com.wombat.mamda.MamdaTradeListener.IsIrregular ()
IsIrregular Checks the explicit and implicit irregular fields.
Returns
true if the Trade is irregular.
getSymbolFieldState()
short com.wombat.mamda.MamdaTradeListener.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getPartIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getSrcTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getSrcTimeFieldState ()
See also
MamdaBasicEvent::getSrcTimeFieldState()
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getActivityTimeFieldState ()
See also
MamdaBasicEvent::getActivityTimeFieldState()
Implements com.wombat.mamda.MamdaBasicEvent.
getLineTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getShortSaleCircuitBreakerFieldState()
short com.wombat.mamda.MamdaTradeListener.getShortSaleCircuitBreakerFieldState ()
Returns
Returns the FieldState, always MODIFIED.
Implements com.wombat.mamda.MamdaTradeRecap.
getOrigShortSaleCircuitBreakerFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigShortSaleCircuitBreakerFieldState ()
Returns
Returns the FieldState, always MODIFIED.
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getCorrShortSaleCircuitBreakerFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrShortSaleCircuitBreakerFieldState ()
Returns
Returns the FieldState, always MODIFIED.
Implements com.wombat.mamda.MamdaTradeCorrection.
getPubIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getPubIdFieldState ()
getEventSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getEventSeqNumFieldState ()
See also
MamdaBasicEvent::getEventSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getEventTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getEventTimeFieldState ()
See also
MamdaBasicEvent::getEventTimeFieldState()
Implements com.wombat.mamda.MamdaBasicEvent.
getLastPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getLastPriceFieldState ()
See also
MamdaTradeRecap::getLastPriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getLastVolumeFieldState ()
See also
MamdaTradeRecap::getLastVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastPartIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getLastPartIdFieldState ()
See also
MamdaTradeRecap::getLastPartIdFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastDateFieldState()
short com.wombat.mamda.MamdaTradeListener.getLastDateFieldState ()
See also
MamdaTradeRecap::getLastDateFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getLastTimeFieldState ()
See also
MamdaTradeRecap::getLastTimeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getIrregPriceFieldState ()
See also
MamdaTradeRecap::getIrregPriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getIrregVolumeFieldState ()
See also
MamdaTradeRecap::getIrregVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregPartIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getIrregPartIdFieldState ()
See also
MamdaTradeRecap::getIrregPartIdFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getIrregTimeFieldState()
short com.wombat.mamda.MamdaTradeListener.getIrregTimeFieldState ()
See also
MamdaTradeRecap::getLastTimeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getAccVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getAccVolumeFieldState ()
See also
MamdaTradeRecap::getAccVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExAccVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getOffExAccVolumeFieldState ()
See also
MamdaTradeRecap::getOffExAccVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExAccVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getOnExAccVolumeFieldState ()
See also
MamdaTradeRecap::getOnExAccVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getNetChangeFieldState()
short com.wombat.mamda.MamdaTradeListener.getNetChangeFieldState ()
See also
MamdaTradeRecap::getNetChangeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getPctChangeFieldState()
short com.wombat.mamda.MamdaTradeListener.getPctChangeFieldState ()
See also
MamdaTradeRecap::getPctChangeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeDirectionFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeDirectionFieldState ()
See also
MamdaTradeRecap::getTradeDirectionFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getSideFieldState()
short com.wombat.mamda.MamdaTradeListener.getSideFieldState ()
See also
MamdaTradeRecap::getSideFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOpenPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getOpenPriceFieldState ()
See also
MamdaTradeRecap::getOpenPriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getHighPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getHighPriceFieldState ()
See also
MamdaTradeRecap::getHighPriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLowPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getLowPriceFieldState ()
See also
MamdaTradeRecap::getLowPriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getClosePriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getClosePriceFieldState ()
See also
MamdaTradeRecap::getClosePriceFieldState()
Implements com.wombat.mamda.MamdaTradeClosing.
getPrevClosePriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getPrevClosePriceFieldState ()
See also
MamdaTradeRecap::getPrevClosePriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getPrevCloseDateFieldState()
short com.wombat.mamda.MamdaTradeListener.getPrevCloseDateFieldState ()
See also
MamdaTradeRecap::getPrevCloseDateFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getAdjPrevCloseFieldState()
short com.wombat.mamda.MamdaTradeListener.getAdjPrevCloseFieldState ()
See also
MamdaTradeRecap::getAdjPrevCloseFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getBlockCountFieldState()
short com.wombat.mamda.MamdaTradeListener.getBlockCountFieldState ()
See also
MamdaTradeRecap::getBlockCountFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getBlockVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getBlockVolumeFieldState ()
See also
MamdaTradeRecap::getBlockVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getVwapFieldState()
short com.wombat.mamda.MamdaTradeListener.getVwapFieldState ()
See also
MamdaTradeRecap::getVwapFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExVwapFieldState()
short com.wombat.mamda.MamdaTradeListener.getOffExVwapFieldState ()
See also
MamdaTradeRecap::getOffExVwapFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExVwapFieldState()
short com.wombat.mamda.MamdaTradeListener.getOnExVwapFieldState ()
See also
MamdaTradeRecap::getOnExVwapFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getTotalValueFieldState()
short com.wombat.mamda.MamdaTradeListener.getTotalValueFieldState ()
See also
MamdaTradeRecap::getTotalValueFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExTotalValueFieldState()
short com.wombat.mamda.MamdaTradeListener.getOffExTotalValueFieldState ()
See also
MamdaTradeRecap::getOffExTotalValueFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExTotalValueFieldState()
short com.wombat.mamda.MamdaTradeListener.getOnExTotalValueFieldState ()
See also
MamdaTradeRecap::getOnExTotalValueFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getStdDevFieldState()
short com.wombat.mamda.MamdaTradeListener.getStdDevFieldState ()
See also
MamdaTradeRecap::getStdDevFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getStdDevSumFieldState()
short com.wombat.mamda.MamdaTradeListener.getStdDevSumFieldState ()
See also
MamdaTradeRecap::getStdDevSumFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getStdDevSumSquaresFieldState()
short com.wombat.mamda.MamdaTradeListener.getStdDevSumSquaresFieldState ()
See also
MamdaTradeRecap::getStdDevSumSquaresFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOrderIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrderIdFieldState ()
See also
MamdaTradeRecap::getOrderId
Implements com.wombat.mamda.MamdaTradeRecap.
getSettlePriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getSettlePriceFieldState ()
See also
MamdaTradeRecap::getSettlePriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getSettleDateFieldState()
short com.wombat.mamda.MamdaTradeListener.getSettleDateFieldState ()
See also
MamdaTradeRecap::getSettleDateFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradePriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradePriceFieldState ()
See also
MamdaTradeReport::getTradePriceFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeVolumeFieldState ()
See also
MamdaTradeReport::getTradeVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradePartIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradePartIdFieldState ()
See also
MamdaTradeReport::getTradePartIdFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeIdFieldState ()
See also
MamdaTradeReport::getTradeIdFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getOrigTradeIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigTradeIdFieldState ()
See also
MamdaTradeCancelOrError::getOrigTradeIdFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getCorrTradeIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrTradeIdFieldState ()
See also
MamdaTradeCorrection::getCorrTradeIdFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getTradeQualFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeQualFieldState ()
See also
MamdaTradeReport::getTradeQualFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeQualNativeStrFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeQualNativeStrFieldState ()
See also
MamdaTradeReport::getTradeQualNativeStrFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeConditionFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeConditionFieldState ()
See also
MamdaTradeReport::getTradeConditionFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeSellersSaleDaysFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeSellersSaleDaysFieldState ()
See also
MamdaTradeReport::getTradeSellersSaleDaysFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeStopStockFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeStopStockFieldState ()
See also
MamdaTradeReport::getTradeStopStockFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getTradeExecVenueFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeExecVenueFieldState ()
See also
MamdaTradeReport::gettradeExecVenueFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOffExchangeTradePriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getOffExchangeTradePriceFieldState ()
See also
MamdaTradeReport::geOffExchangetTradePriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getOnExchangeTradePriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getOnExchangeTradePriceFieldState ()
See also
MamdaTradeReport::getOnExchangeTradePriceFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeCountFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeCountFieldState ()
See also
MamdaTradeRecap::getTradeCountFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getTradeUnitsFieldState()
short com.wombat.mamda.MamdaTradeListener.getTradeUnitsFieldState ()
See also
MamdaTradeRecap::getTradeUnitsFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLastSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getLastSeqNumFieldState ()
See also
MamdaTradeRecap::getLastSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getHighSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getHighSeqNumFieldState ()
See also
MamdaTradeRecap::getHighSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getLowSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getLowSeqNumFieldState ()
See also
MamdaTradeRecap::getLowSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getTotalVolumeSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getTotalVolumeSeqNumFieldState ()
See also
MamdaTradeRecap::getTotalVolumeSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getCurrencyCodeFieldState()
short com.wombat.mamda.MamdaTradeListener.getCurrencyCodeFieldState ()
See also
MamdaTradeRecap::getCurrencyCodeFieldState()
Implements com.wombat.mamda.MamdaTradeRecap.
getIsIrregularFieldState()
short com.wombat.mamda.MamdaTradeListener.getIsIrregularFieldState ()
See also
MamdaTradeReport::getIsIrregularFieldState()
Implements com.wombat.mamda.MamdaTradeReport.
getBeginGapSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getBeginGapSeqNumFieldState ()
See also
MamdaTradeGap::getBeginGapSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeGap.
References com.wombat.mamda.MamdaFieldState.getState().
getEndGapSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getEndGapSeqNumFieldState ()
See also
MamdaTradeGap::getEndGapSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeGap.
References com.wombat.mamda.MamdaFieldState.getState().
getIsCancelFieldState()
short com.wombat.mamda.MamdaTradeListener.getIsCancelFieldState ()
See also
MamdaTradeCancelOrError::getIsCancelFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigSeqNumFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigSeqNumFieldState ()
See also
MamdaTradeCancelOrError::getOrigSeqNumFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigPriceFieldState ()
See also
MamdaTradeCancelOrError::getOrigPriceFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigVolumeFieldState ()
See also
MamdaTradeCancelOrError::getOrigVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigPartIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigPartIdFieldState ()
See also
MamdaTradeCancelOrError::getOrigPartIdFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigQualFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigQualFieldState ()
See also
MamdaTradeCancelOrError::getOrigQualFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigQualNativeFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigQualNativeFieldState ()
See also
MamdaTradeCancelOrError::getOrigQualNativeFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigConditionFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigConditionFieldState ()
See also
MamdaTradeCancelOrError::getOrigConditionFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigSellersSaleDaysFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigSellersSaleDaysFieldState ()
See also
MamdaTradeCancelOrError::getOrigSellersSaleDaysFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getOrigStopStockFieldState()
short com.wombat.mamda.MamdaTradeListener.getOrigStopStockFieldState ()
See also
MamdaTradeCancelOrError::getOrigStopStockFieldState()
Implements com.wombat.mamda.MamdaTradeCancelOrError.
getCorrPriceFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrPriceFieldState ()
See also
MamdaTradeCorrection::getCorrPriceFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrVolumeFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrVolumeFieldState ()
See also
MamdaTradeCorrection::getCorrVolumeFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrPartIdFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrPartIdFieldState ()
See also
MamdaTradeCorrection::getCorrPartIdFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrQualFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrQualFieldState ()
See also
MamdaTradeCorrection::getCorrQualFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrQualNativeFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrQualNativeFieldState ()
See also
MamdaTradeCorrection::getCorrQualNativeFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrConditionFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrConditionFieldState ()
See also
MamdaTradeCorrection::getCorrConditionFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrSellersSaleDaysFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrSellersSaleDaysFieldState ()
See also
MamdaTradeCorrection::getCorrSellersSaleDaysFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getCorrStopStockFieldState()
short com.wombat.mamda.MamdaTradeListener.getCorrStopStockFieldState ()
See also
MamdaTradeCorrection::getCorrStopStockFieldState()
Implements com.wombat.mamda.MamdaTradeCorrection.
getIsIndicativeFieldState()
short com.wombat.mamda.MamdaTradeListener.getIsIndicativeFieldState ()
See also
MamdaTradeClosing::getIsIndicativeFieldState()
Implements com.wombat.mamda.MamdaTradeClosing.
References com.wombat.mamda.MamdaFieldState.getState().
onMsg()
void com.wombat.mamda.MamdaTradeListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaCommonFields.ACTIVITY_TIME, com.wombat.mamda.MamdaTradeFields.ADJ_PREV_CLOSE, com.wombat.mamda.MamdaTradeFields.AGGRESSOR_SIDE, com.wombat.mamda.MamdaTradeFields.BLOCK_COUNT, com.wombat.mamda.MamdaTradeFields.BLOCK_VOLUME, com.wombat.mamda.MamdaTradeFields.CANCEL_TIME, com.wombat.mamda.MamdaTradeFields.CLOSE_PRICE, com.wombat.mamda.MamdaTradeFields.CORR_PART_ID, com.wombat.mamda.MamdaTradeFields.CORR_PRICE, com.wombat.mamda.MamdaTradeFields.CORR_SALE_CONDITION, com.wombat.mamda.MamdaTradeFields.CORR_SELLERS_SALE_DAYS, com.wombat.mamda.MamdaTradeFields.CORR_SHORT_SALE_CIRCUIT_BREAKER, com.wombat.mamda.MamdaTradeFields.CORR_SIZE, com.wombat.mamda.MamdaTradeFields.CORR_STOP_STOCK_IND, com.wombat.mamda.MamdaTradeFields.CORR_TRADE_ID, com.wombat.mamda.MamdaTradeFields.CORR_TRADE_QUALIFIER, com.wombat.mamda.MamdaTradeFields.CURRENCY_CODE, com.wombat.mamda.MamdaTradeFields.getMaxFid(), com.wombat.mamda.MamdaFieldState.getState(), com.wombat.mamda.MamdaTradeFields.HIGH_PRICE, com.wombat.mamda.MamdaTradeFields.HIGH_SEQNUM, com.wombat.mamda.MamdaTradeFields.IRREG_PART_ID, com.wombat.mamda.MamdaTradeFields.IRREG_PRICE, com.wombat.mamda.MamdaTradeFields.IRREG_SIZE, com.wombat.mamda.MamdaTradeFields.IRREG_TIME, com.wombat.mamda.MamdaTradeFields.IS_IRREGULAR, com.wombat.mamda.MamdaTradeFields.isSet(), com.wombat.mamda.MamdaCommonFields.ISSUE_SYMBOL, com.wombat.mamda.MamdaTradeFields.LAST_SEQNUM, com.wombat.mamda.MamdaCommonFields.LINE_TIME, com.wombat.mamda.MamdaTradeFields.LOW_PRICE, com.wombat.mamda.MamdaTradeFields.LOW_SEQNUM, com.wombat.mamda.MamdaTradeSide.mamdaTradeSideFromString(), com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaTradeListener.mTradeCache, com.wombat.mamda.MamdaTradeFields.NET_CHANGE, com.wombat.mamda.MamdaFieldState.NOT_MODIFIED, com.wombat.mamda.MamdaTradeFields.OFF_EXCHANGE_TOTAL_VALUE, com.wombat.mamda.MamdaTradeFields.OFF_EXCHANGE_TOTAL_VOLUME, com.wombat.mamda.MamdaTradeFields.OFF_EXCHANGE_TRADE_PRICE, com.wombat.mamda.MamdaTradeFields.OFF_EXCHANGE_VWAP, com.wombat.mamda.MamdaTradeFields.ON_EXCHANGE_TOTAL_VALUE, com.wombat.mamda.MamdaTradeFields.ON_EXCHANGE_TOTAL_VOLUME, com.wombat.mamda.MamdaTradeFields.ON_EXCHANGE_TRADE_PRICE, com.wombat.mamda.MamdaTradeFields.ON_EXCHANGE_VWAP, com.wombat.mamda.MamdaTradeHandler.onTradeCancelOrError(), com.wombat.mamda.MamdaTradeHandler.onTradeClosing(), com.wombat.mamda.MamdaTradeHandler.onTradeCorrection(), com.wombat.mamda.MamdaTradeHandler.onTradeGap(), com.wombat.mamda.MamdaTradeHandler.onTradeRecap(), com.wombat.mamda.MamdaTradeHandler.onTradeReport(), com.wombat.mamda.MamdaTradeFields.OPEN_PRICE, com.wombat.mamda.MamdaTradeFields.ORDER_ID, com.wombat.mamda.MamdaTradeFields.ORIG_PART_ID, com.wombat.mamda.MamdaTradeFields.ORIG_PRICE, com.wombat.mamda.MamdaTradeFields.ORIG_SALE_CONDITION, com.wombat.mamda.MamdaTradeFields.ORIG_SELLERS_SALE_DAYS, com.wombat.mamda.MamdaTradeFields.ORIG_SEQNUM, com.wombat.mamda.MamdaTradeFields.ORIG_SHORT_SALE_CIRCUIT_BREAKER, com.wombat.mamda.MamdaTradeFields.ORIG_SIZE, com.wombat.mamda.MamdaTradeFields.ORIG_STOP_STOCK_IND, com.wombat.mamda.MamdaTradeFields.ORIG_TRADE_ID, com.wombat.mamda.MamdaTradeFields.ORIG_TRADE_QUALIFIER, com.wombat.mamda.MamdaCommonFields.PART_ID, com.wombat.mamda.MamdaTradeFields.PCT_CHANGE, com.wombat.mamda.MamdaTradeFields.PREV_CLOSE_DATE, com.wombat.mamda.MamdaTradeFields.PREV_CLOSE_PRICE, com.wombat.mamda.MamdaCommonFields.PUB_ID, com.wombat.mamda.MamdaTradeFields.SALE_CONDITION, com.wombat.mamda.MamdaTradeFields.SELLERS_SALE_DAYS, com.wombat.mamda.MamdaCommonFields.SEND_TIME, com.wombat.mamda.MamdaFieldState.setState(), com.wombat.mamda.MamdaTradeFields.SETTLE_DATE, com.wombat.mamda.MamdaTradeFields.SETTLE_PRICE, com.wombat.mamda.MamdaTradeFields.SHORT_SALE_CIRCUIT_BREAKER, com.wombat.mamda.MamdaCommonFields.SRC_TIME, com.wombat.mamda.MamdaTradeFields.STD_DEV, com.wombat.mamda.MamdaTradeFields.STD_DEV_SUM, com.wombat.mamda.MamdaTradeFields.STD_DEV_SUM_SQUARES, com.wombat.mamda.MamdaTradeFields.STOP_STOCK_IND, com.wombat.mamda.MamdaCommonFields.SYMBOL, com.wombat.mamda.MamdaTradeSide.toString(), com.wombat.mamda.MamdaTradeFields.TOTAL_VALUE, com.wombat.mamda.MamdaTradeFields.TOTAL_VOLUME, com.wombat.mamda.MamdaTradeFields.TOTAL_VOLUME_SEQNUM, com.wombat.mamda.MamdaTradeFields.TRADE_COUNT, com.wombat.mamda.MamdaTradeFields.TRADE_DATE, com.wombat.mamda.MamdaTradeFields.TRADE_DIRECTION, com.wombat.mamda.MamdaTradeFields.TRADE_EXEC_VENUE, com.wombat.mamda.MamdaTradeFields.TRADE_ID, com.wombat.mamda.MamdaTradeFields.TRADE_PART_ID, com.wombat.mamda.MamdaTradeFields.TRADE_PRICE, com.wombat.mamda.MamdaTradeFields.TRADE_QUALIFIER, com.wombat.mamda.MamdaTradeFields.TRADE_SEQNUM, com.wombat.mamda.MamdaTradeFields.TRADE_SIDE, com.wombat.mamda.MamdaTradeFields.TRADE_SIZE, com.wombat.mamda.MamdaTradeFields.TRADE_TIME, com.wombat.mamda.MamdaTradeFields.TRADE_UNITS, com.wombat.mamda.MamdaTradeFields.UPDATE_AS_TRADE, and com.wombat.mamda.MamdaTradeFields.VWAP.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
Member Data Documentation
mTradeCache
final MamdaTradeCache com.wombat.mamda.MamdaTradeListener.mTradeCache protected
Initial value:
=
                new MamdaTradeCache ()
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().