OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionChain Class Reference
com.wombat.mamda.options.MamdaOptionChain Class Reference
MamdaOptionChain is a specialized class to represent market data option chains.
Public Member Functions
MamdaOptionChain (String symbol)
MamdaOptionChain Constructor.
void setSymbol (String symbol)
Set the underlying symbol for the option chain.
String getSymbol ()
Get the underlying symbol for the option chain.
void setUnderlyingQuoteListener (MamdaQuoteListener quoteListener)
Set the underlying quote listener information.
void setUnderlyingTradeListener (MamdaTradeListener tradeListener)
Set the underlying trade listener information.
MamdaQuoteListener getUnderlyingQuoteListener ()
Make the underlying quote listener available externally.
MamdaTradeListener getUnderlyingTradeListener ()
Make the underlying trade listener available externally.
MamdaOptionContract getContract (String contractSymbol)
Find an option contract by OPRA symbol.
SortedSet getExchanges ()
Return the superset of regional exchange identifiers for any option in this chain.
SortedSet getStrikePrices ()
Return the superset of strike prices for this chain.
void addContract (String contractSymbol, MamdaOptionContract contract)
Add an option contract.
void removeContract (String contractSymbol)
Remove an option contract.
double getAtTheMoney (short compareType)
Get the price of the option underlying.
boolean getIsPriceWithinPercentOfMoney (double price, double percentage, short compareType)
Return whether the price within a % of the money.
SortedSet getStrikesWithinPercent (double percentage, short compareType)
Determine the set of strike prices that are included in a given percentage range of the underlying price.
SortedSet getStrikesWithinRangeSize (int rangeLength, short compareType)
Determine the set of strike prices that are included in a given fixed size range of strikes surrounding the underlying price.
Iterator callIterator ()
Return an iterator over all call option contracts.
Iterator putIterator ()
Return an iterator over all put option contracts.
MamdaOptionExpirationDateSet getAllExpirations ()
Return a set of MamdaOptionExpirationDateSet.
void dump ()
Print the contents of the chain to standard out.
Detailed Description
MamdaOptionChain is a specialized class to represent market data option chains.
The class has capabilities to store the current state of an entire option chain, or a subset of the chain.
Constructor & Destructor Documentation
MamdaOptionChain()
com.wombat.mamda.options.MamdaOptionChain.MamdaOptionChain (String symbol)
MamdaOptionChain Constructor.
Parameters
symbol The underlying symbol.
References com.wombat.mamda.options.MamdaOptionChain.setSymbol().
Member Function Documentation
setSymbol()
void com.wombat.mamda.options.MamdaOptionChain.setSymbol (String symbol)
Set the underlying symbol for the option chain.
Parameters
symbol The underlying symbol.
Referenced by com.wombat.mamda.options.MamdaOptionChain.MamdaOptionChain().
getSymbol()
String com.wombat.mamda.options.MamdaOptionChain.getSymbol ()
Get the underlying symbol for the option chain.
Returns
String The underlying symbol for the option chain.
Referenced by com.wombat.mamda.options.MamdaOptionChainView.getSymbol(), and com.wombat.mamda.options.MamdaOptionChainListener.MamdaOptionChainListener().
setUnderlyingQuoteListener()
void com.wombat.mamda.options.MamdaOptionChain.setUnderlyingQuoteListener (MamdaQuoteListener quoteListener)
Set the underlying quote listener information.
MamdaOptionChain does not use this class itself, but related classes might (e.g., MamdaOptionChainView).
Parameters
quoteListener The quote listener for the chain.
setUnderlyingTradeListener()
void com.wombat.mamda.options.MamdaOptionChain.setUnderlyingTradeListener (MamdaTradeListener tradeListener)
Set the underlying trade listener information.
MamdaOptionChain uses this class to implement the atTheMoney() method. Related classes might (e.g., MamdaOptionChainView) use it for other reasons.
Parameters
tradeListener The trade listener for the chain.
getUnderlyingQuoteListener()
MamdaQuoteListener com.wombat.mamda.options.MamdaOptionChain.getUnderlyingQuoteListener ()
Make the underlying quote listener available externally.
Returns
MamdaQuoteListener The quote listener for the chain.
getUnderlyingTradeListener()
MamdaTradeListener com.wombat.mamda.options.MamdaOptionChain.getUnderlyingTradeListener ()
Make the underlying trade listener available externally.
Returns
MamdaTradeListener The trade listener for the chain.
getContract()
MamdaOptionContract com.wombat.mamda.options.MamdaOptionChain.getContract (String contractSymbol)
Find an option contract by OPRA symbol.
Parameters
contractSymbol The option symbol.
Returns
MamdaOptionContract The contract object representing the option.
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
getExchanges()
SortedSet com.wombat.mamda.options.MamdaOptionChain.getExchanges ()
Return the superset of regional exchange identifiers for any option in this chain.
Each element in the set is a String object.
Returns
SortedSet Set of regional exchange identifiers.
getStrikePrices()
SortedSet com.wombat.mamda.options.MamdaOptionChain.getStrikePrices ()
Return the superset of strike prices for this chain.
Each element in the set is a Double object.
Returns
SortedSet Set of strike prices for the chain.
addContract()
void com.wombat.mamda.options.MamdaOptionChain.addContract (String contractSymbol, MamdaOptionContract contract)
Add an option contract.
This method would not normally be invoked by a user application. Rather, MamdaOptionChainListener would be most likely to call this method.
Parameters
contractSymbol The option instrument symbol.
contract The Mamda option contract representation.
References com.wombat.mamda.options.MamdaOptionStrikeSet.getCallSet(), com.wombat.mamda.options.MamdaOptionContract.getExchange(), com.wombat.mamda.options.MamdaOptionContract.getExpireDate(), com.wombat.mamda.options.MamdaOptionContract.getPutCall(), com.wombat.mamda.options.MamdaOptionStrikeSet.getPutSet(), com.wombat.mamda.options.MamdaOptionContract.getStrikePrice(), com.wombat.mamda.options.MamdaOptionExchangeUtils.isBbo(), com.wombat.mamda.options.MamdaOptionExchangeUtils.isWombatBbo(), com.wombat.mamda.options.MamdaOptionContract.PC_CALL, com.wombat.mamda.options.MamdaOptionContractSet.setBboContract(), com.wombat.mamda.options.MamdaOptionContractSet.setExchangeContract(), and com.wombat.mamda.options.MamdaOptionContractSet.setWombatBboContract().
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
removeContract()
void com.wombat.mamda.options.MamdaOptionChain.removeContract (String contractSymbol)
Remove an option contract.
This method would not normally be invoked by a user application. Rather, MamdaOptionChainListener would be most likely to call this method.
getAtTheMoney()
double com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney (short compareType)
Get the price of the option underlying.
Determine the underlying price ("at the money"), based on the mode of calculation.
Parameters
compareType The mode of calculation (MamdaOptionAtTheMoneyCompareType)
Returns
double The price of the underlying.
See also
MamdaOptionAtTheMoneyCompareType
References com.wombat.mamda.options.MamdaOptionAtTheMoneyCompareType.ASK, com.wombat.mamda.options.MamdaOptionAtTheMoneyCompareType.BID, com.wombat.mamda.MamdaQuoteListener.getAskPrice(), com.wombat.mamda.MamdaQuoteListener.getBidPrice(), com.wombat.mamda.MamdaTradeListener.getLastPrice(), com.wombat.mamda.options.MamdaOptionAtTheMoneyCompareType.LAST_TRADE, and com.wombat.mamda.options.MamdaOptionAtTheMoneyCompareType.MID_QUOTE.
Referenced by com.wombat.mamda.options.MamdaOptionChain.getIsPriceWithinPercentOfMoney(), com.wombat.mamda.options.MamdaOptionChain.getStrikesWithinPercent(), and com.wombat.mamda.options.MamdaOptionChain.getStrikesWithinRangeSize().
getIsPriceWithinPercentOfMoney()
boolean com.wombat.mamda.options.MamdaOptionChain.getIsPriceWithinPercentOfMoney (double price, double percentage, short compareType)
Return whether the price within a % of the money.
Determine whether some price (e.g. a strike price) is within a given percentage range of the underlying (at the money) price.
Parameters
price The strike price to check.
percentage What % to check the strike price against.
compareType What price we are checking against (see MamdaOptionAtTheMoneyCompareType)
Returns
boolean Whether the proce is within % of the money.
See also
MamdaOptionAtTheMoneyCompareType
References com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney().
getStrikesWithinPercent()
SortedSet com.wombat.mamda.options.MamdaOptionChain.getStrikesWithinPercent (double percentage, short compareType)
Determine the set of strike prices that are included in a given percentage range of the underlying price.
If there are no strikes within the percentage range, then both strike prices are set to zero.
Parameters
percentage The percentage range of the underlying price.
compareType Which underlying price to compare to.
Returns
SortedSet Set of strike prices.
See also
MamdaOptionAtTheMoneyCompareType
References com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney().
Referenced by com.wombat.mamda.options.MamdaOptionChainView.onOptionSeriesUpdate().
getStrikesWithinRangeSize()
SortedSet com.wombat.mamda.options.MamdaOptionChain.getStrikesWithinRangeSize (int rangeLength, short compareType)
Determine the set of strike prices that are included in a given fixed size range of strikes surrounding the underlying price.
If rangeLen is odd, then the strike price nearest to the underlying price is treated as a higher strike price. If rangeLen is even and the underlying price is exactly equal to a strike price, then that strike price is treated as a higher strike price.
Parameters
rangeLength Number of strike prices to include in result.
compareType What underlying price to use as a comparator.
Returns
SortedSet Resulting set of strike prices.
See also
MamdaOptionAtTheMoneyCompareType
References com.wombat.mamda.options.MamdaOptionChain.getAtTheMoney().
Referenced by com.wombat.mamda.options.MamdaOptionChainView.onOptionSeriesUpdate().
callIterator()
Iterator com.wombat.mamda.options.MamdaOptionChain.callIterator ()
Return an iterator over all call option contracts.
The type of object that Iterator.next() returns is MamdaOptionContract.
Returns
Iterator The iterator of call options.
putIterator()
Iterator com.wombat.mamda.options.MamdaOptionChain.putIterator ()
Return an iterator over all put option contracts.
The type of object that Iterator.next() returns is MamdaOptionContract.
Returns
Iterator The iterator of put options.
getAllExpirations()
MamdaOptionExpirationDateSet com.wombat.mamda.options.MamdaOptionChain.getAllExpirations ()
Return a set of MamdaOptionExpirationDateSet.
Returns
MamdaOptionExpirationDateSet Set of expiration dates.
Referenced by com.wombat.mamda.options.MamdaOptionChainView.onOptionSeriesUpdate().
dump()
void com.wombat.mamda.options.MamdaOptionChain.dump ()
Print the contents of the chain to standard out.
References com.wombat.mamda.options.MamdaOptionContract.getExchange(), com.wombat.mamda.options.MamdaOptionContract.getExpireDate(), com.wombat.mamda.options.MamdaOptionContract.getStrikePrice(), and com.wombat.mamda.options.MamdaOptionContract.getSymbol().