OpenMAMDA Java API: com.wombat.mamda.MamdaFields Class Reference
com.wombat.mamda.MamdaFields Class Reference
Common base class for all the MamdaXXXFields classes.
Inherited by com.wombat.mamda.MamdaAuctionFields, com.wombat.mamda.MamdaCommonFields, com.wombat.mamda.MamdaFundamentalFields, com.wombat.mamda.MamdaOrderImbalanceFields, com.wombat.mamda.MamdaQuoteFields, com.wombat.mamda.MamdaSecurityStatusFields, com.wombat.mamda.MamdaTradeFields, com.wombat.mamda.options.MamdaOptionFields, and com.wombat.mamda.orderbook.MamdaOrderBookFields.
Static Protected Member Functions
static String lookupFieldName (Properties properties, String defaultFieldName)
Look up a given field name mapping from the Properties object.
Detailed Description
Common base class for all the MamdaXXXFields classes.
Each of the subclasses maintains a cache of relevant MamaFieldDescriptors obtained from the MamaDictionary using the fields standard name. If the dictionary is being published with non standard field name mappings users can pass a Properties object to the corresponding setDictionary() method which contains field mappings.
Each mapping should have the following format:
mamda.field.<common field="" name>="">=<mapped field="" name>=""> e.g.
mamda.field.wTradePrice=myMappedTradePrice where myMappedTradePrice is the name of the field under which the trade price is being published by the feedhandlers and which is being published by the dictionary to describe the trade price field.
Member Function Documentation
lookupFieldName()
static String com.wombat.mamda.MamdaFields.lookupFieldName (Properties properties, String defaultFieldName) static protected
Look up a given field name mapping from the Properties object.
If no map exists, then the default field name is return.
Referenced by com.wombat.mamda.MamdaAuctionFields.setDictionary(), com.wombat.mamda.options.MamdaOptionFields.setDictionary(), com.wombat.mamda.MamdaCommonFields.setDictionary(), com.wombat.mamda.MamdaSecurityStatusFields.setDictionary(), com.wombat.mamda.MamdaOrderImbalanceFields.setDictionary(), com.wombat.mamda.MamdaFundamentalFields.setDictionary(), com.wombat.mamda.orderbook.MamdaOrderBookFields.setDictionary(), com.wombat.mamda.MamdaQuoteFields.setDictionary(), and com.wombat.mamda.MamdaTradeFields.setDictionary().