OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel Class Reference
Public Member Functions
MamdaOrderBookPriceLevel ()
Default constructor.
MamdaOrderBookPriceLevel (MamdaOrderBookPriceLevel copy)
Construct a price level object which is a shallow copy of the original.
MamdaOrderBookPriceLevel (double price, char side)
void clear ()
Clear the pricelevel.
void copy (MamdaOrderBookPriceLevel copy)
Copy a price level object which is an exact and deep copy of the original.
void copy (MamdaBookAtomicLevel copy)
Copy an atomic price level object which is an exact and deep copy of the original.
void copy (MamdaBookAtomicLevelEntry copy)
Copy a price level object which is an exact and deep copy of the original.
void setPrice (MamaPrice price)
void setPrice (double price)
void setSize (double size)
void setSizeChange (double size)
void setNumEntries (double numEntries)
void setSide (char side)
void setAction (char action)
void setTime (MamaDateTime time)
void setOrderType (char orderType)
char getOrderType ()
boolean empty ()
Return whether there are no entries for this level.
void setDetails (MamdaOrderBookPriceLevel level)
Take the details from level and apply them to this level.
void setDetails (MamdaBookAtomicLevel level)
Take the details from atomic level and apply them to this level.
void setDetails (MamdaBookAtomicLevelEntry levelEntry)
Take the details from atomic levelEntry and apply them to this levelEntry.
void addEntry (MamdaOrderBookEntry entry)
Add a new order book entry to the price level.
void updateEntry (MamdaOrderBookEntry entry)
Update the details of an existing entry in the level.
void updateEntry (MamdaBookAtomicLevelEntry levelEntry)
Update the details of an existing entry in the level, where the update details are provied by an atomic levelEntry.
void removeEntry (MamdaOrderBookEntry entry)
Remove an order book entry from the price level.
void removeEntry (MamdaBookAtomicLevelEntry levelEntry)
Remove an order book entry from the price level, where the delete details are provied by an atomic levelEntry.
Iterator entryIterator ()
Returns a java.util.Iterator for all entries within this level.
void checkNotExist (MamdaOrderBookEntry entry)
If the provided order book entry exists in the price level a MamdaOrderBookException exception is thrown.
void checkNotExist (MamdaBookAtomicLevelEntry levelEntry)
If the provided levelEntry entry exists in the price level, as a OrderBookEntry, a MamdaOrderBookException exception is thrown.
void markAllDeleted ()
Mark everything in this price level as deleted, including entries.
void setAsDifference (MamdaOrderBookPriceLevel lhs, MamdaOrderBookPriceLevel rhs)
MamaPrice getPrice ()
Return the price for this level.
double getSize ()
Return the total size (across all entries) for this level.
double getSizeChange ()
Return the size change for this (presumably delta) level.
double getNumEntries ()
Return the actual number of entries for this level.
int getNumEntriesTotal ()
char getSide ()
Return the side (bid/ask) of the book for this level.
char getAction ()
Return the action for this price level.
MamaDateTime getTime ()
Return the time stamp for when the price level was last updated.
void assertEqual (MamdaOrderBookPriceLevel rhs)
Order book price level equality verification.
String getSymbol ()
void removeEntryById (MamdaOrderBookEntry entry)
void removeEntryById (MamdaBookAtomicLevelEntry levelEntry)
void addEntriesFromLevel (MamdaOrderBookPriceLevel bookLevel, MamdaOrderBookEntryFilter filter, MamdaOrderBookBasicDeltaList delta)
void deleteEntriesFromSource (MamaSource source, MamdaOrderBookBasicDeltaList delta)
boolean reevaluate ()
Re-evaluate the price level.
MamdaOrderBookEntry getEntryAtPosition (long pos)
Return the order book entry at position "pos" in the price level.
MamdaOrderBookEntry findOrCreateEntry (String id)
MamdaOrderBookEntry findEntry (String id)
Static Public Member Functions
static void setStrictChecking (boolean strict)
Enforce strict checking of order book modifications (at the expense of some performance).
Static Public Attributes
static final char ACTION_ADD = 'A'
static final char ACTION_UPDATE = 'U'
A new price level.
static final char ACTION_DELETE = 'D'
Updated price level.
static final char ACTION_UNKNOWN = 'Z'
Deleted price level.
static final char SIDE_BID = 'B'
Unknown action (error).
static final char SIDE_ASK = 'A'
Bid (buy) side.
static final char SIDE_UNKNOWN = 'Z'
Ask (sell) side.
static final char LEVEL_LIMIT = 'L'
Unknown side (error).
static final char LEVEL_MARKET = 'M'
LIMIT order.
static final char LEVEL_UNKNOWN = 'U'
MARKET order.
Protected Member Functions
MamdaOrderBook getOrderBook ()
void setOrderBook (MamdaOrderBook book)
Constructor & Destructor Documentation
MamdaOrderBookPriceLevel() [1/3]
com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.MamdaOrderBookPriceLevel ()
Default constructor.
MamdaOrderBookPriceLevel() [2/3]
com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.MamdaOrderBookPriceLevel (MamdaOrderBookPriceLevel copy)
Construct a price level object which is a shallow copy of the original.
Parameters
copy The MamdaOrderBookPriceLevel to copy.
MamdaOrderBookPriceLevel() [3/3]
com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.MamdaOrderBookPriceLevel (double price, char side)
Member Function Documentation
clear()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.clear ()
Clear the pricelevel.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.empty(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_LIMIT, and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
copy() [1/3]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy (MamdaOrderBookPriceLevel copy)
Copy a price level object which is an exact and deep copy of the original.
Parameters
copy The MamdaOrderBookPriceLevel to copy.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.copy().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
copy() [2/3]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy (MamdaBookAtomicLevel copy)
Copy an atomic price level object which is an exact and deep copy of the original.
Parameters
copy The MamdaOrderBookPriceLevel to copy.
References com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelAction(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelMamaPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelNumEntries(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSide(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSize(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSizeChange(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelTime().
copy() [3/3]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy (MamdaBookAtomicLevelEntry copy)
Copy a price level object which is an exact and deep copy of the original.
Parameters
copy The MamdaOrderBookPriceLevel to copy.
References com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelAction(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryTime(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelMamaPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelNumEntries(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelSide(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelSize().
setPrice() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setPrice (MamaPrice price)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setPrice() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setPrice (double price)
setSize()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSize (double size)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
setSizeChange()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSizeChange (double size)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
setNumEntries()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setNumEntries (double numEntries)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
setSide()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSide (char side)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
setAction()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAction (char action)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
setTime()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setTime (MamaDateTime time)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setOrderType()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setOrderType (char orderType)
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getOrderType()
char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getOrderType ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
empty()
boolean com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.empty ()
Return whether there are no entries for this level.
Returns
Whether there are no entries for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.clear().
setDetails() [1/3]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails (MamdaOrderBookPriceLevel level)
Take the details from level and apply them to this level.
This does not update entries within the level, only information pertaining to the level itself. It is intended that this method should not be used externally to the API.
Parameters
level The price level object from which the details are being obtained.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setDetails() [2/3]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails (MamdaBookAtomicLevel level)
Take the details from atomic level and apply them to this level.
This does not update entries within the level, only information pertaining to the level itself. It is intended that this method should not be used externally to the API.
Parameters
level The atomic price level object from which the details are being obtained.
References com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelNumEntries(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSize(), com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSizeChange(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelTime().
setDetails() [3/3]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails (MamdaBookAtomicLevelEntry levelEntry)
Take the details from atomic levelEntry and apply them to this levelEntry.
This update entries within the level. It is intended that this method should not be used externally to the API.
Parameters
levelEntry The atomic price levelEntry object from which the details are being obtained.
References com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntrySize(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryTime().
addEntry()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry (MamdaOrderBookEntry entry)
Add a new order book entry to the price level.
Parameters
entry The new entry to be added to the level.
See also
MamdaOrderBookEntry
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.checkNotExist(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setPriceLevel().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntriesFromLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
updateEntry() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry (MamdaOrderBookEntry entry)
Update the details of an existing entry in the level.
Parameters
entry An instance of MamdaOrderBookEntry with the new details for the entry in the level.
See also
MamdaOrderBookEntry
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
updateEntry() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry (MamdaBookAtomicLevelEntry levelEntry)
Update the details of an existing entry in the level, where the update details are provied by an atomic levelEntry.
Parameters
levelEntry An instance of MamdaBookAtomicLevelEntry with the new details for the entry in the level.
See also
MamdaOrderBookEntry
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryId(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails().
removeEntry() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry (MamdaOrderBookEntry entry)
Remove an order book entry from the price level.
Parameters
entry The entry which is to be removed from the price level.
See also
MamdaOrderBookEntry
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntriesTotal(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
removeEntry() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry (MamdaBookAtomicLevelEntry levelEntry)
Remove an order book entry from the price level, where the delete details are provied by an atomic levelEntry.
Parameters
levelEntry The entry which is to be removed from the price level.
See also
MamdaOrderBookEntry
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryId(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntrySize(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.isVisible().
entryIterator()
Iterator com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.entryIterator ()
Returns a java.util.Iterator for all entries within this level.
Price Level entries are represented by the MamdaOrderBookEntry class.
Returns
Iterator The iterator for the price level entries
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
checkNotExist() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.checkNotExist (MamdaOrderBookEntry entry)
If the provided order book entry exists in the price level a MamdaOrderBookException exception is thrown.
Otherwise the method simply returns.
Parameters
entry The entry whose presence in the level is being determined.
Exceptions
MamdaOrderBookException If the entry is found in the price level.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry().
checkNotExist() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.checkNotExist (MamdaBookAtomicLevelEntry levelEntry)
If the provided levelEntry entry exists in the price level, as a OrderBookEntry, a MamdaOrderBookException exception is thrown.
Otherwise the method simply returns.
Parameters
entry The entry whose presence in the level is being determined.
Exceptions
MamdaOrderBookException If the entry is found in the price level.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryId().
markAllDeleted()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted ()
Mark everything in this price level as deleted, including entries.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSize(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSizeChange().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setAsDifference()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference (MamdaOrderBookPriceLevel lhs, MamdaOrderBookPriceLevel rhs)
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getTime(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSide(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setSizeChange(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPrice()
MamaPrice com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice ()
Return the price for this level.
Returns
The price for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.dump(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPrice(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
getSize()
double com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSize ()
Return the total size (across all entries) for this level.
Returns
The total size for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
getSizeChange()
double com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange ()
Return the size change for this (presumably delta) level.
This attribute is only of interest for delta order books. For full order books, this field will be equal to the size of the price level.
Returns
The changed size for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
getNumEntries()
double com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntries ()
Return the actual number of entries for this level.
The actual number of entries may not equate to the number of entries that can be iterated over if: (a) the feed does not provide the actual entries, or (b) the price level is just a delta.
Returns
The actual number of entries for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
getNumEntriesTotal()
int com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntriesTotal ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById().
getSide()
char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide ()
Return the side (bid/ask) of the book for this level.
Returns
The side of the book for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.dump(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
getAction()
char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getAction ()
Return the action for this price level.
All price levels for a full book are marked with ACTION_ADD.
Returns
The action for this level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
getTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getTime ()
Return the time stamp for when the price level was last updated.
Returns
The time stamp for when the price level was last updated.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference().
assertEqual()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.assertEqual (MamdaOrderBookPriceLevel rhs)
Order book price level equality verification.
A MamdaOrderBookException is thrown if the price levels are not equal, along with the reason for the inequality.
Exceptions
MamdaOrderBookException
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.assertEqual(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
setStrictChecking()
static void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setStrictChecking (boolean strict) static
Enforce strict checking of order book modifications (at the expense of some performance).
This setting is automatically updated by MamdaOrderBook::setStrictChecking().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.setStrictChecking().
getOrderBook()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getOrderBook () protected
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getOrderBook(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.getOrderBook().
setOrderBook()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setOrderBook (MamdaOrderBook book) protected
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getSymbol()
String com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSymbol ()
References com.wombat.mamda.orderbook.MamdaOrderBook.getSymbol().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSymbol().
removeEntryById() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById (MamdaOrderBookEntry entry)
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntriesTotal(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
removeEntryById() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById (MamdaBookAtomicLevelEntry levelEntry)
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.equalId(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryId(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntrySize(), and com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.isVisible().
addEntriesFromLevel()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntriesFromLevel (MamdaOrderBookPriceLevel bookLevel, MamdaOrderBookEntryFilter filter, MamdaOrderBookBasicDeltaList delta)
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookEntryFilter.checkEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
deleteEntriesFromSource()
void com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.deleteEntriesFromSource (MamaSource source, MamdaOrderBookBasicDeltaList delta)
References com.wombat.mamda.orderbook.MamdaOrderBook.detach(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSource(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible().
reevaluate()
boolean com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.reevaluate ()
Re-evaluate the price level.
This would be performed after the status of sources and/or subsources of an "aggregated order book" (i.e., a book built from multiple sources) have changed.
Returns
Whether the book info changed based on the re-evaluation.
References com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getEntryAtPosition()
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getEntryAtPosition (long pos)
Return the order book entry at position "pos" in the price level.
Parameters
pos The position of the order book entry.
Returns
The order book entry or NULL if not found.
References com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
findOrCreateEntry()
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry (String id)
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE, com.wombat.mamda.orderbook.MamdaOrderBook.addDelta(), com.wombat.mamda.orderbook.MamdaOrderBook.getCheckSourceState(), com.wombat.mamda.orderbook.MamdaOrderBook.getGenerateDeltaMsgs(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPriceLevel(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSizeChange(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.isVisible(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setAction(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setId(), and com.wombat.mamda.orderbook.MamdaOrderBookEntry.setPriceLevel().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
findEntry()
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findEntry (String id)
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
Member Data Documentation
ACTION_ADD
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD = 'A' static
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.clear(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getSize(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
ACTION_UPDATE
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UPDATE = 'U' static
A new price level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.findOrCreateEntry(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setAsDifference(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
ACTION_DELETE
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE = 'D' static
Updated price level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.markAllDeleted(), com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById().
ACTION_UNKNOWN
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UNKNOWN = 'Z' static
Deleted price level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
SIDE_BID
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID = 'B' static
Unknown action (error).
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.clear(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getPosition(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator(), com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
SIDE_ASK
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_ASK = 'A' static
Bid (buy) side.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
SIDE_UNKNOWN
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_UNKNOWN = 'Z' static
Ask (sell) side.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
LEVEL_LIMIT
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_LIMIT = 'L' static
Unknown side (error).
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.clear(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
LEVEL_MARKET
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_MARKET = 'M' static
LIMIT order.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
LEVEL_UNKNOWN
final char com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.LEVEL_UNKNOWN = 'U' static
MARKET order.