OpenMAMDA Java API: com.wombat.mamda.MamdaOrderImbalanceListener Class Reference
com.wombat.mamda.MamdaOrderImbalanceListener Class Reference
A MamdaOrderImbalanceListener is class that specializes in handling imbalance order updates.
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.MamdaBasicEvent, com.wombat.mamda.MamdaBasicRecap, com.wombat.mamda.MamdaOrderImbalanceRecap, and com.wombat.mamda.MamdaOrderImbalanceUpdate.
Public Member Functions
void clearCache (MamdaOrderImbalanceCache cache)
clearCache - clears all cached data by resetting to default values.
MamdaOrderImbalanceListener ()
constructor
void addHandler (MamdaOrderImbalanceHandler handler)
addHandler - Registers handler interested in receiving update update and recap events.
MamaPrice getHighIndicationPrice ()
getHighIndicationPrice - Returns the high indication price of the imbalance order.
MamaPrice getLowIndicationPrice ()
getLowIndicationPrice - Returns the low indication price of the imbalance order.
MamaPrice getImbalancePrice ()
getImbalancePrice - Returns the indication price for the imbalance order.
long getBuyVolume ()
getBuyVolume - Returns the buy volume of the imbalance order
long getSellVolume ()
getSellVolume - Returns the sell volume of the imbalance order
long getMatchVolume ()
getMatchVolume - Returns the match volume of the imbalance order
String getImbalanceState ()
getImbalanceState - Returns the order imbalance state
MamaPrice getMatchPrice ()
getMatchPrice - Returns the match price for the imbalance order.
MamaPrice getFarClearingPrice ()
getFarClearingPrice - Returns the far clearing price for the imbalance order.
MamaPrice getNearClearingPrice ()
getNearClearingPrice - Returns the near clearing price for the imbalance order.
char getNoClearingPrice ()
getNoClearingPrice - Returns the no clearing price for the imbalance order.
char getPriceVarInd ()
getPriceVarInd -
char getCrossType ()
MamaDateTime getEventTime ()
getEventTime
long getEventSeqNum ()
getEventSeqNum
MamaDateTime getActivityTime ()
getActivityTime
MamaDateTime getSrcTime ()
getSrcTime
MamaDateTime getSendTime ()
getSendTime
MamaDateTime getLineTime ()
getLineTime
int getMsgType ()
getMsgType
String getIssueSymbol ()
getIssueSymbol
String getPartId ()
getPartId
String getSymbol ()
getSymbol
int getSeqNum ()
getSeqNum
String getSecurityStatusOrig ()
getSecurityStatusOrig
MamaDateTime getSecurityStatusTime ()
getSecurityStatusTime
MamaDateTime getAuctionTime ()
getAuctionTime
short getHighIndicationPriceFieldState ()
getHighIndicationPriceFieldState - Returns the high indication price of the imbalance order.
short getLowIndicationPriceFieldState ()
getLowIndicationPriceFieldState - Returns the low indication price of the imbalance order.
short getImbalancePriceFieldState ()
getImbalancePriceFieldState - Returns the indication price for the imbalance order.
short getBuyVolumeFieldState ()
getBuyVolumeFieldState - Returns the buy volume of the imbalance order
short getSellVolumeFieldState ()
getSellVolumeFieldState - Returns the sell volume of the imbalance order
short getMatchVolumeFieldState ()
getMatchVolumeFieldState - Returns the match volume of the imbalance order
short getImbalanceStateFieldState ()
getImbalanceStateFieldState - Returns the order imbalance state
short getMatchPriceFieldState ()
getMatchPriceFieldState - Returns the match price for the imbalance order.
short getFarClearingPriceFieldState ()
getFarClearingPriceFieldState - Returns the far clearing price for the imbalance order.
short getNearClearingPriceFieldState ()
getNearClearingPriceFieldState - Returns the near clearing price for the imbalance order.
short getNoClearingPriceFieldState ()
getNoClearingPriceFieldState - Returns the no clearing price for the imbalance order.
short getPriceVarIndFieldState ()
getPriceVarIndFieldState -
short getCrossTypeFieldState ()
getCrossType return the imbalance cross type
short getEventTimeFieldState ()
getEventTimeFieldState
short getEventSeqNumFieldState ()
getEventSeqNumFieldState
short getActivityTimeFieldState ()
getActivityTimeFieldState
short getSrcTimeFieldState ()
getSrcTimeFieldState
short getSendTimeFieldState ()
getSendTimeFieldState
short getLineTimeFieldState ()
getLineTimeFieldState
short getMsgTypeFieldState ()
getMsgTypeFieldState
short getIssueSymbolFieldState ()
getIssueSymbolFieldState
short getPartIdFieldState ()
getPartIdFieldState
short getSymbolFieldState ()
getSymbolFieldState
short getSeqNumFieldState ()
getSeqNumFieldState
short getSecurityStatusOrigFieldState ()
getSecurityStatusOrigFieldState
short getSecurityStatusTimeFieldState ()
getSecurityStatusTimeFieldState
short getAuctionTimeFieldState ()
getAuctionTimeFieldState
MamdaOrderImbalanceSide getImbalanceSide ()
getImbalanceSide- Returns the imbalance side of the imbalance order.
long getImbalanceVolume ()
getImbalanceVolume - Returns the imbalance volume, which is either the sell or buy volume
void onMsg (MamdaSubscription subscription, final MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Protected Attributes
final MamdaOrderImbalanceCache orderImbalanceCache
Detailed Description
A MamdaOrderImbalanceListener is class that specializes in handling imbalance order updates.
An imbalance order occurs when too many orders of a particular type - either buy, sell or limit - for listed securities and not enough of the other, matching orders are received by an exchange. Developers provide their own implementation of the MamdaOrderImbalanceHandler interface and will be delivered notifications for imbalance updates.
Constructor & Destructor Documentation
MamdaOrderImbalanceListener()
com.wombat.mamda.MamdaOrderImbalanceListener.MamdaOrderImbalanceListener ()
constructor
References com.wombat.mamda.MamdaOrderImbalanceListener.clearCache().
Member Function Documentation
clearCache()
void com.wombat.mamda.MamdaOrderImbalanceListener.clearCache (MamdaOrderImbalanceCache cache)
clearCache - clears all cached data by resetting to default values.
Parameters
cache The imbalance order cache to clear.
References com.wombat.mamda.MamdaFieldState.NOT_INITIALISED.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.MamdaOrderImbalanceListener().
addHandler()
void com.wombat.mamda.MamdaOrderImbalanceListener.addHandler (MamdaOrderImbalanceHandler handler)
addHandler - Registers handler interested in receiving update update and recap events.
Currently only one handler can and must be registered.
Parameters
handler - the handler to be registered.
getHighIndicationPrice()
MamaPrice com.wombat.mamda.MamdaOrderImbalanceListener.getHighIndicationPrice ()
getHighIndicationPrice - Returns the high indication price of the imbalance order.
Returns
mHighIndicationPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getLowIndicationPrice()
MamaPrice com.wombat.mamda.MamdaOrderImbalanceListener.getLowIndicationPrice ()
getLowIndicationPrice - Returns the low indication price of the imbalance order.
Returns
mLowIndicationPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getImbalancePrice()
MamaPrice com.wombat.mamda.MamdaOrderImbalanceListener.getImbalancePrice ()
getImbalancePrice - Returns the indication price for the imbalance order.
Returns
mIndicationPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getBuyVolume()
long com.wombat.mamda.MamdaOrderImbalanceListener.getBuyVolume ()
getBuyVolume - Returns the buy volume of the imbalance order
Returns
mBuyVolume
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceVolume().
getSellVolume()
long com.wombat.mamda.MamdaOrderImbalanceListener.getSellVolume ()
getSellVolume - Returns the sell volume of the imbalance order
Returns
mSellVolume
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceVolume().
getMatchVolume()
long com.wombat.mamda.MamdaOrderImbalanceListener.getMatchVolume ()
getMatchVolume - Returns the match volume of the imbalance order
Returns
mMatchVolume
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getImbalanceState()
String com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceState ()
getImbalanceState - Returns the order imbalance state
Returns
mSecurityStatusQual
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getMatchPrice()
MamaPrice com.wombat.mamda.MamdaOrderImbalanceListener.getMatchPrice ()
getMatchPrice - Returns the match price for the imbalance order.
Returns
mInsideMatchPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getFarClearingPrice()
MamaPrice com.wombat.mamda.MamdaOrderImbalanceListener.getFarClearingPrice ()
getFarClearingPrice - Returns the far clearing price for the imbalance order.
Returns
mFarClearingPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getNearClearingPrice()
MamaPrice com.wombat.mamda.MamdaOrderImbalanceListener.getNearClearingPrice ()
getNearClearingPrice - Returns the near clearing price for the imbalance order.
Returns
mNearClearingPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getNoClearingPrice()
char com.wombat.mamda.MamdaOrderImbalanceListener.getNoClearingPrice ()
getNoClearingPrice - Returns the no clearing price for the imbalance order.
Returns
mNoClearingPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getPriceVarInd()
char com.wombat.mamda.MamdaOrderImbalanceListener.getPriceVarInd ()
getPriceVarInd -
Returns
mPriceVarInd
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getCrossType()
char com.wombat.mamda.MamdaOrderImbalanceListener.getCrossType ()
Returns
Returns the CrossType.
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getEventTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getEventTime ()
getEventTime
Returns
mEventTime
See also
MamdaBasicEvent::getEventTime
Implements com.wombat.mamda.MamdaBasicEvent.
getEventSeqNum()
long com.wombat.mamda.MamdaOrderImbalanceListener.getEventSeqNum ()
getEventSeqNum
Returns
mEventSeqNum
See also
MamdaBasicEvent::getEventSeqNum
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getActivityTime ()
getActivityTime
Returns
mActTime
See also
MamdaBasicEvent::getActivityTime
Implements com.wombat.mamda.MamdaBasicEvent.
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getSrcTime ()
getSrcTime
Returns
mSrcTime
See also
MamdaBasicEvent::getSrcTime
Implements com.wombat.mamda.MamdaBasicEvent.
getSendTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getSendTime ()
getSendTime
Returns
mSendTime
See also
MamdaBasicEvent::getSendTime
Implements com.wombat.mamda.MamdaBasicRecap.
getLineTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getLineTime ()
getLineTime
Returns
mLineTime
See also
MamdaBasicEvent::getLineTime
Implements com.wombat.mamda.MamdaBasicRecap.
getMsgType()
int com.wombat.mamda.MamdaOrderImbalanceListener.getMsgType ()
getMsgType
Returns
mMsgType
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getIssueSymbol()
String com.wombat.mamda.MamdaOrderImbalanceListener.getIssueSymbol ()
getIssueSymbol
Returns
mIssueSymbol
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getPartId()
String com.wombat.mamda.MamdaOrderImbalanceListener.getPartId ()
getPartId
Returns
mPartId
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbol()
String com.wombat.mamda.MamdaOrderImbalanceListener.getSymbol ()
getSymbol
Returns
mSymbol
Implements com.wombat.mamda.MamdaBasicRecap.
getSeqNum()
int com.wombat.mamda.MamdaOrderImbalanceListener.getSeqNum ()
getSeqNum
Returns
mSeqNum
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getSecurityStatusOrig()
String com.wombat.mamda.MamdaOrderImbalanceListener.getSecurityStatusOrig ()
getSecurityStatusOrig
Returns
mSecurityStatusOrig
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getSecurityStatusTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getSecurityStatusTime ()
getSecurityStatusTime
Returns
mSecurityStatusTime
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getAuctionTime()
MamaDateTime com.wombat.mamda.MamdaOrderImbalanceListener.getAuctionTime ()
getAuctionTime
Returns
mAuctionTime
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getHighIndicationPriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getHighIndicationPriceFieldState ()
getHighIndicationPriceFieldState - Returns the high indication price of the imbalance order.
Returns
mHighIndicationPriceFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getLowIndicationPriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getLowIndicationPriceFieldState ()
getLowIndicationPriceFieldState - Returns the low indication price of the imbalance order.
Returns
mLowIndicationPriceFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getImbalancePriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getImbalancePriceFieldState ()
getImbalancePriceFieldState - Returns the indication price for the imbalance order.
Returns
mIndicationPriceFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getBuyVolumeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getBuyVolumeFieldState ()
getBuyVolumeFieldState - Returns the buy volume of the imbalance order
Returns
mBuyVolumeFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getSellVolumeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSellVolumeFieldState ()
getSellVolumeFieldState - Returns the sell volume of the imbalance order
Returns
mSellVolumeFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getMatchVolumeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getMatchVolumeFieldState ()
getMatchVolumeFieldState - Returns the match volume of the imbalance order
Returns
mMatchVolume
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getImbalanceStateFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceStateFieldState ()
getImbalanceStateFieldState - Returns the order imbalance state
Returns
mSecurityStatusQual
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getMatchPriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getMatchPriceFieldState ()
getMatchPriceFieldState - Returns the match price for the imbalance order.
Returns
mInsideMatchPrice
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getFarClearingPriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getFarClearingPriceFieldState ()
getFarClearingPriceFieldState - Returns the far clearing price for the imbalance order.
Returns
mFarClearingPriceFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getNearClearingPriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getNearClearingPriceFieldState ()
getNearClearingPriceFieldState - Returns the near clearing price for the imbalance order.
Returns
mNearClearingPriceFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getNoClearingPriceFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getNoClearingPriceFieldState ()
getNoClearingPriceFieldState - Returns the no clearing price for the imbalance order.
Returns
mNoClearingPriceFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getPriceVarIndFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getPriceVarIndFieldState ()
getPriceVarIndFieldState -
Returns
mPriceVarIndFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getCrossTypeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getCrossTypeFieldState ()
getCrossType return the imbalance cross type
Returns
mCrossType
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getEventTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getEventTimeFieldState ()
getEventTimeFieldState
Returns
mEventTimeFieldState
See also
MamdaBasicEvent::getEventTimeFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
getEventSeqNumFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getEventSeqNumFieldState ()
getEventSeqNumFieldState
Returns
mEventSeqNumFieldState
See also
MamdaBasicEvent::getEventSeqNumFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getActivityTimeFieldState ()
getActivityTimeFieldState
Returns
mActTimeFieldState
See also
MamdaBasicEvent::getActivityTimeFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
getSrcTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSrcTimeFieldState ()
getSrcTimeFieldState
Returns
mSrcTimeFieldState
See also
MamdaBasicEvent::getSrcTimeFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
getSendTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSendTimeFieldState ()
getSendTimeFieldState
Returns
mSendTimeFieldState
See also
MamdaBasicEvent::getSendTimeFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
getLineTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getLineTimeFieldState ()
getLineTimeFieldState
Returns
mLineTimeFieldState
See also
MamdaBasicEvent::getLineTimeFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
getMsgTypeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getMsgTypeFieldState ()
getMsgTypeFieldState
Returns
mMsgTypeFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getIssueSymbolFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getIssueSymbolFieldState ()
getIssueSymbolFieldState
Returns
mIssueSymbolFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getPartIdFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getPartIdFieldState ()
getPartIdFieldState
Returns
mPartIdFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbolFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSymbolFieldState ()
getSymbolFieldState
Returns
mSymbolFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
getSeqNumFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSeqNumFieldState ()
getSeqNumFieldState
Returns
mSeqNumFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getSecurityStatusOrigFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSecurityStatusOrigFieldState ()
getSecurityStatusOrigFieldState
Returns
mSecurityStatusOrigFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getSecurityStatusTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getSecurityStatusTimeFieldState ()
getSecurityStatusTimeFieldState
Returns
mSecurityStatusTimeFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getAuctionTimeFieldState()
short com.wombat.mamda.MamdaOrderImbalanceListener.getAuctionTimeFieldState ()
getAuctionTimeFieldState
Returns
mAuctionTimeFieldState
Implements com.wombat.mamda.MamdaOrderImbalanceRecap.
getImbalanceSide()
MamdaOrderImbalanceSide com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceSide ()
getImbalanceSide- Returns the imbalance side of the imbalance order.
This is determined by the Buy and Sell Volumes.
Returns
mSide
References com.wombat.mamda.MamdaOrderImbalanceSide.ASK_SIDE, and com.wombat.mamda.MamdaOrderImbalanceSide.BID_SIDE.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceVolume().
getImbalanceVolume()
long com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceVolume ()
getImbalanceVolume - Returns the imbalance volume, which is either the sell or buy volume
Returns
long
References com.wombat.mamda.MamdaOrderImbalanceSide.BID_SIDE, com.wombat.mamda.MamdaOrderImbalanceListener.getBuyVolume(), com.wombat.mamda.MamdaOrderImbalanceListener.getImbalanceSide(), and com.wombat.mamda.MamdaOrderImbalanceListener.getSellVolume().
onMsg()
void com.wombat.mamda.MamdaOrderImbalanceListener.onMsg (MamdaSubscription subscription, final MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaOrderImbalanceFields.ACTIVITY_TIME, com.wombat.mamda.MamdaOrderImbalanceFields.AUCTION_TIME, com.wombat.mamda.MamdaOrderImbalanceFields.BUY_VOLUME, com.wombat.mamda.MamdaOrderImbalanceFields.CROSS_TYPE, com.wombat.mamda.MamdaOrderImbalanceFields.FAR_CLEARING_PRICE, com.wombat.mamda.MamdaOrderImbalanceFields.getMaxFid(), com.wombat.mamda.MamdaOrderImbalanceFields.HIGH_INDICATION_PRICE, com.wombat.mamda.MamdaOrderImbalanceFields.INDICATION_PRICE, com.wombat.mamda.MamdaOrderImbalanceFields.INSIDE_MATCH_PRICE, com.wombat.mamda.MamdaOrderImbalanceType.isMamdaImbalanceOrder(), com.wombat.mamda.MamdaOrderImbalanceType.isMamdaOrderImbalanceType(), com.wombat.mamda.MamdaOrderImbalanceFields.isSet(), com.wombat.mamda.MamdaOrderImbalanceFields.ISSUE_SYMBOL, com.wombat.mamda.MamdaOrderImbalanceFields.LINE_TIME, com.wombat.mamda.MamdaOrderImbalanceFields.LOW_INDICATION_PRICE, com.wombat.mamda.MamdaOrderImbalanceFields.MATCH_VOLUME, com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaOrderImbalanceFields.MSG_TYPE, com.wombat.mamda.MamdaOrderImbalanceFields.NEAR_CLEARING_PRICE, com.wombat.mamda.MamdaOrderImbalanceFields.NO_CLEARING_PRICE, com.wombat.mamda.MamdaFieldState.NOT_MODIFIED, com.wombat.mamda.MamdaOrderImbalanceHandler.onNoOrderImbalance(), com.wombat.mamda.MamdaOrderImbalanceHandler.onOrderImbalance(), com.wombat.mamda.MamdaOrderImbalanceHandler.onOrderImbalanceRecap(), com.wombat.mamda.MamdaOrderImbalanceListener.orderImbalanceCache, com.wombat.mamda.MamdaOrderImbalanceFields.PART_ID, com.wombat.mamda.MamdaOrderImbalanceFields.PRICE_VAR_IND, com.wombat.mamda.MamdaOrderImbalanceFields.SECURITY_STATUS_ORIG, com.wombat.mamda.MamdaOrderImbalanceFields.SECURITY_STATUS_QUAL, com.wombat.mamda.MamdaOrderImbalanceFields.SECURITY_STATUS_TIME, com.wombat.mamda.MamdaOrderImbalanceFields.SELL_VOLUME, com.wombat.mamda.MamdaOrderImbalanceFields.SEND_TIME, com.wombat.mamda.MamdaOrderImbalanceFields.SEQ_NUM, com.wombat.mamda.MamdaOrderImbalanceFields.SRC_TIME, com.wombat.mamda.MamdaOrderImbalanceType.stringToValue(), com.wombat.mamda.MamdaOrderImbalanceFields.SYMBOL, and com.wombat.mamda.MamdaOrderImbalanceType.UNKNOWN.
Member Data Documentation
orderImbalanceCache
final MamdaOrderImbalanceCache com.wombat.mamda.MamdaOrderImbalanceListener.orderImbalanceCache protected
Initial value:
= new
                                             MamdaOrderImbalanceCache ()
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.onMsg().