OpenMAMDA Java API: com.wombat.mamda.locks.MamdaLock Class Reference
com.wombat.mamda.locks.MamdaLock Class Reference
Inherits ReentrantReadWriteLock.
Public Member Functions
final void acquireReadLock ()
final void acquireWriteLock ()
final void releaseWriteLock ()
final void releaseReadLock ()
final void acquireWriteLock ()
Acquires the lock.
final void acquireReadLock ()
final void releaseWriteLock ()
Releases the lock.
final void releaseReadLock ()
Member Function Documentation
acquireReadLock() [1/2]
final void com.wombat.mamda.locks.MamdaLock.acquireReadLock ()
acquireWriteLock() [1/2]
final void com.wombat.mamda.locks.MamdaLock.acquireWriteLock ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapshot(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapShot(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getReadOnlyBookSnapshot(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
releaseWriteLock() [1/2]
final void com.wombat.mamda.locks.MamdaLock.releaseWriteLock ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapshot(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getBookSnapShot(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getReadOnlyBookSnapshot(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
releaseReadLock() [1/2]
final void com.wombat.mamda.locks.MamdaLock.releaseReadLock ()
acquireWriteLock() [2/2]
final void com.wombat.mamda.locks.MamdaLock.acquireWriteLock ()
Acquires the lock.
acquireReadLock() [2/2]
final void com.wombat.mamda.locks.MamdaLock.acquireReadLock ()
releaseWriteLock() [2/2]
final void com.wombat.mamda.locks.MamdaLock.releaseWriteLock ()
Releases the lock.
releaseReadLock() [2/2]
final void com.wombat.mamda.locks.MamdaLock.releaseReadLock ()