OpenMAMDA Java API: com.wombat.mamda.MamdaAuctionListener Class Reference
com.wombat.mamda.MamdaAuctionListener Class Reference
A MamdaAuctionListener is class that specializes in handling Auction order updates.
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.MamdaBasicEvent, com.wombat.mamda.MamdaBasicRecap, com.wombat.mamda.MamdaAuctionRecap, and com.wombat.mamda.MamdaAuctionUpdate.
Public Member Functions
void clearCache ()
clearCache - clears all cached data by resetting to default values.
MamdaAuctionListener ()
constructor
void addHandler (MamdaAuctionHandler handler)
addHandler - Registers handler interested in receiving update update and recap events.
MamaDateTime getActivityTime ()
getActivityTime
MamaDateTime getSrcTime ()
getSrcTime
MamaDateTime getSendTime ()
getSendTime
MamaDateTime getLineTime ()
getLineTime
String getIssueSymbol ()
getIssueSymbol
String getPartId ()
getPartId
String getSymbol ()
getSymbol
MamaDateTime getEventTime ()
getEventTime
long getEventSeqNum ()
getEventSeqNum
MamaPrice getUncrossPrice ()
getUncrossPrice
MamaDouble getUncrossVolume ()
getUncrossVolume
short getUncrossPriceInd ()
getUncrossPriceInd
short getActivityTimeFieldState ()
getActivityTimeFieldState
short getSrcTimeFieldState ()
getSrcTimeFieldState
short getSendTimeFieldState ()
getSendTimeFieldState
short getLineTimeFieldState ()
getLineTimeFieldState
short getIssueSymbolFieldState ()
getIssueSymbolFieldState
short getPartIdFieldState ()
getPartIdFieldState
short getSymbolFieldState ()
getSymbolFieldState
short getEventTimeFieldState ()
getEventTimeFieldState
short getEventSeqNumFieldState ()
getEventSeqNumFieldState
short getUncrossPriceFieldState ()
getUncrossPriceFieldState
short getUncrossVolumeFieldState ()
getUncrossVolumeFieldState
short getUncrossPriceIndFieldState ()
getUncrossPriceIndFieldState
void onMsg (MamdaSubscription subscription, final MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Public Attributes
MamaDateTime mSrcTime = new MamaDateTime()
MamaDateTime mActTime = new MamaDateTime()
MamaDateTime mSendTime = new MamaDateTime()
MamaDateTime mLineTime = new MamaDateTime()
MamaDateTime mEventTime = new MamaDateTime()
MamaLong mEventSeqNum = new MamaLong()
MamaString mIssueSymbol = new MamaString()
MamaString mPartId = new MamaString()
MamaString mSymbol = new MamaString()
MamaPrice mUncrossPrice = new MamaPrice()
MamaDouble mUncrossVolume = new MamaDouble()
MamdaUncrossPriceInd mUncrossPriceInd = new MamdaUncrossPriceInd()
MamdaFieldState mSrcTimeFieldState = new MamdaFieldState()
MamdaFieldState mActTimeFieldState = new MamdaFieldState()
MamdaFieldState mSendTimeFieldState = new MamdaFieldState()
MamdaFieldState mLineTimeFieldState = new MamdaFieldState()
MamdaFieldState mEventTimeFieldState = new MamdaFieldState()
MamdaFieldState mIssueSymbolFieldState = new MamdaFieldState()
MamdaFieldState mPartIdFieldState = new MamdaFieldState()
MamdaFieldState mSymbolFieldState = new MamdaFieldState()
MamdaFieldState mEventSeqNumFieldState = new MamdaFieldState()
MamdaFieldState mUncrossPriceFieldState = new MamdaFieldState()
MamdaFieldState mUncrossVolumeFieldState = new MamdaFieldState()
MamdaFieldState mUncrossPriceIndFieldState = new MamdaFieldState()
Detailed Description
A MamdaAuctionListener is class that specializes in handling Auction order updates.
An Auction order occurs when too many orders of a particular type - either buy, sell or limit - for listed securities and not enough of the other, matching orders are received by an exchange. Developers provide their own implementation of the MamdaAuctionHandler interface and will be delivered notifications for Auction updates.
Constructor & Destructor Documentation
MamdaAuctionListener()
com.wombat.mamda.MamdaAuctionListener.MamdaAuctionListener ()
constructor
References com.wombat.mamda.MamdaAuctionListener.clearCache().
Member Function Documentation
clearCache()
void com.wombat.mamda.MamdaAuctionListener.clearCache ()
clearCache - clears all cached data by resetting to default values.
Parameters
cache The Auction order cache to clear.
References com.wombat.mamda.MamdaFieldState.NOT_INITIALISED, com.wombat.mamda.MamdaUncrossPriceInd.set(), com.wombat.mamda.MamdaFieldState.setState(), and com.wombat.mamda.MamdaUncrossPriceInd.UNCROSS_NONE.
Referenced by com.wombat.mamda.MamdaAuctionListener.MamdaAuctionListener().
addHandler()
void com.wombat.mamda.MamdaAuctionListener.addHandler (MamdaAuctionHandler handler)
addHandler - Registers handler interested in receiving update update and recap events.
Currently only one handler can and must be registered.
Parameters
handler - the handler to be registered.
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaAuctionListener.getActivityTime ()
getActivityTime
Returns
mActTime
See also
MamdaBasicEvent::getActivityTime
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaAuctionListener.mActTime.
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaAuctionListener.getSrcTime ()
getSrcTime
Returns
mSrcTime
See also
MamdaBasicEvent::getSrcTime
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaAuctionListener.mSrcTime.
getSendTime()
MamaDateTime com.wombat.mamda.MamdaAuctionListener.getSendTime ()
getSendTime
Returns
mSendTime
See also
MamdaBasicEvent::getSendTime
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaAuctionListener.mSendTime.
getLineTime()
MamaDateTime com.wombat.mamda.MamdaAuctionListener.getLineTime ()
getLineTime
Returns
mLineTime
See also
MamdaBasicEvent::getLineTime
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaAuctionListener.mLineTime.
getIssueSymbol()
String com.wombat.mamda.MamdaAuctionListener.getIssueSymbol ()
getIssueSymbol
Returns
mIssueSymbol
getPartId()
String com.wombat.mamda.MamdaAuctionListener.getPartId ()
getPartId
Returns
mPartId
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbol()
String com.wombat.mamda.MamdaAuctionListener.getSymbol ()
getSymbol
Returns
mSymbol
Implements com.wombat.mamda.MamdaBasicRecap.
getEventTime()
MamaDateTime com.wombat.mamda.MamdaAuctionListener.getEventTime ()
getEventTime
Returns
mEventTime
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaAuctionListener.mEventTime.
getEventSeqNum()
long com.wombat.mamda.MamdaAuctionListener.getEventSeqNum ()
getEventSeqNum
Returns
mEventSeqNum
Implements com.wombat.mamda.MamdaBasicEvent.
getUncrossPrice()
MamaPrice com.wombat.mamda.MamdaAuctionListener.getUncrossPrice ()
getUncrossPrice
Returns
mUncrossPrice
Implements com.wombat.mamda.MamdaAuctionRecap.
References com.wombat.mamda.MamdaAuctionListener.mUncrossPrice.
getUncrossVolume()
MamaDouble com.wombat.mamda.MamdaAuctionListener.getUncrossVolume ()
getUncrossVolume
Returns
mUncrossVolume
Implements com.wombat.mamda.MamdaAuctionRecap.
References com.wombat.mamda.MamdaAuctionListener.mUncrossVolume.
getUncrossPriceInd()
short com.wombat.mamda.MamdaAuctionListener.getUncrossPriceInd ()
getUncrossPriceInd
Returns
mUncrossPriceInd
Implements com.wombat.mamda.MamdaAuctionRecap.
References com.wombat.mamda.MamdaUncrossPriceInd.get().
getActivityTimeFieldState()
short com.wombat.mamda.MamdaAuctionListener.getActivityTimeFieldState ()
getActivityTimeFieldState
Returns
mActTimeFieldState
See also
MamdaBasicEvent::getActivityTimeFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getSrcTimeFieldState()
short com.wombat.mamda.MamdaAuctionListener.getSrcTimeFieldState ()
getSrcTimeFieldState
Returns
mSrcTimeFieldState
See also
MamdaBasicEvent::getSrcTimeFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getSendTimeFieldState()
short com.wombat.mamda.MamdaAuctionListener.getSendTimeFieldState ()
getSendTimeFieldState
Returns
mSendTimeFieldState
See also
MamdaBasicEvent::getSendTimeFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getLineTimeFieldState()
short com.wombat.mamda.MamdaAuctionListener.getLineTimeFieldState ()
getLineTimeFieldState
Returns
mLineTimeFieldState
See also
MamdaBasicEvent::getLineTimeFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getIssueSymbolFieldState()
short com.wombat.mamda.MamdaAuctionListener.getIssueSymbolFieldState ()
getIssueSymbolFieldState
Returns
mIssueSymbolFieldState
References com.wombat.mamda.MamdaFieldState.getState().
getPartIdFieldState()
short com.wombat.mamda.MamdaAuctionListener.getPartIdFieldState ()
getPartIdFieldState
Returns
mPartIdFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSymbolFieldState()
short com.wombat.mamda.MamdaAuctionListener.getSymbolFieldState ()
getSymbolFieldState
Returns
mSymbolFieldState
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getEventTimeFieldState()
short com.wombat.mamda.MamdaAuctionListener.getEventTimeFieldState ()
getEventTimeFieldState
Returns
mEventTimeFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getEventSeqNumFieldState()
short com.wombat.mamda.MamdaAuctionListener.getEventSeqNumFieldState ()
getEventSeqNumFieldState
Returns
mEventSeqNumFieldState
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getUncrossPriceFieldState()
short com.wombat.mamda.MamdaAuctionListener.getUncrossPriceFieldState ()
getUncrossPriceFieldState
Returns
mUncrossPriceFieldState
Implements com.wombat.mamda.MamdaAuctionRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getUncrossVolumeFieldState()
short com.wombat.mamda.MamdaAuctionListener.getUncrossVolumeFieldState ()
getUncrossVolumeFieldState
Returns
mUncrossVolumeFieldState
Implements com.wombat.mamda.MamdaAuctionRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getUncrossPriceIndFieldState()
short com.wombat.mamda.MamdaAuctionListener.getUncrossPriceIndFieldState ()
getUncrossPriceIndFieldState
Returns
mUncrossPriceIndFieldState
Implements com.wombat.mamda.MamdaAuctionRecap.
References com.wombat.mamda.MamdaFieldState.getState().
onMsg()
void com.wombat.mamda.MamdaAuctionListener.onMsg (MamdaSubscription subscription, final MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaCommonFields.ACTIVITY_TIME, com.wombat.mamda.MamdaAuctionFields.getMaxFid(), com.wombat.mamda.MamdaFieldState.getState(), com.wombat.mamda.MamdaAuctionFields.isSet(), com.wombat.mamda.MamdaCommonFields.ISSUE_SYMBOL, com.wombat.mamda.MamdaCommonFields.LINE_TIME, com.wombat.mamda.MamdaAuctionListener.mActTime, com.wombat.mamda.MamdaAuctionListener.mActTimeFieldState, com.wombat.mamda.MamdaUncrossPriceInd.mamdaUncrossPriceIndFromString(), com.wombat.mamda.MamdaAuctionListener.mIssueSymbol, com.wombat.mamda.MamdaAuctionListener.mIssueSymbolFieldState, com.wombat.mamda.MamdaAuctionListener.mLineTime, com.wombat.mamda.MamdaAuctionListener.mLineTimeFieldState, com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaAuctionListener.mPartId, com.wombat.mamda.MamdaAuctionListener.mPartIdFieldState, com.wombat.mamda.MamdaAuctionListener.mSendTime, com.wombat.mamda.MamdaAuctionListener.mSendTimeFieldState, com.wombat.mamda.MamdaAuctionListener.mSrcTime, com.wombat.mamda.MamdaAuctionListener.mSrcTimeFieldState, com.wombat.mamda.MamdaAuctionListener.mSymbol, com.wombat.mamda.MamdaAuctionListener.mSymbolFieldState, com.wombat.mamda.MamdaAuctionListener.mUncrossPrice, com.wombat.mamda.MamdaAuctionListener.mUncrossPriceFieldState, com.wombat.mamda.MamdaAuctionListener.mUncrossPriceInd, com.wombat.mamda.MamdaAuctionListener.mUncrossPriceIndFieldState, com.wombat.mamda.MamdaAuctionListener.mUncrossVolume, com.wombat.mamda.MamdaAuctionListener.mUncrossVolumeFieldState, com.wombat.mamda.MamdaFieldState.NOT_MODIFIED, com.wombat.mamda.MamdaAuctionHandler.onAuctionRecap(), com.wombat.mamda.MamdaAuctionHandler.onAuctionUpdate(), com.wombat.mamda.MamdaCommonFields.PART_ID, com.wombat.mamda.MamdaCommonFields.SEND_TIME, com.wombat.mamda.MamdaUncrossPriceInd.set(), com.wombat.mamda.MamdaFieldState.setState(), com.wombat.mamda.MamdaCommonFields.SRC_TIME, com.wombat.mamda.MamdaCommonFields.SYMBOL, com.wombat.mamda.MamdaAuctionFields.UNCROSS_PRICE, com.wombat.mamda.MamdaAuctionFields.UNCROSS_PRICE_IND, and com.wombat.mamda.MamdaAuctionFields.UNCROSS_VOLUME.
Member Data Documentation
mSrcTime
MamaDateTime com.wombat.mamda.MamdaAuctionListener.mSrcTime = new MamaDateTime()
Referenced by com.wombat.mamda.MamdaAuctionListener.getSrcTime(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
mActTime
MamaDateTime com.wombat.mamda.MamdaAuctionListener.mActTime = new MamaDateTime()
Referenced by com.wombat.mamda.MamdaAuctionListener.getActivityTime(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
mSendTime
MamaDateTime com.wombat.mamda.MamdaAuctionListener.mSendTime = new MamaDateTime()
Referenced by com.wombat.mamda.MamdaAuctionListener.getSendTime(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
mLineTime
MamaDateTime com.wombat.mamda.MamdaAuctionListener.mLineTime = new MamaDateTime()
Referenced by com.wombat.mamda.MamdaAuctionListener.getLineTime(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
mEventTime
MamaDateTime com.wombat.mamda.MamdaAuctionListener.mEventTime = new MamaDateTime()
Referenced by com.wombat.mamda.MamdaAuctionListener.getEventTime().
mEventSeqNum
MamaLong com.wombat.mamda.MamdaAuctionListener.mEventSeqNum = new MamaLong()
mIssueSymbol
MamaString com.wombat.mamda.MamdaAuctionListener.mIssueSymbol = new MamaString()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mPartId
MamaString com.wombat.mamda.MamdaAuctionListener.mPartId = new MamaString()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mSymbol
MamaString com.wombat.mamda.MamdaAuctionListener.mSymbol = new MamaString()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mUncrossPrice
MamaPrice com.wombat.mamda.MamdaAuctionListener.mUncrossPrice = new MamaPrice()
Referenced by com.wombat.mamda.MamdaAuctionListener.getUncrossPrice(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
mUncrossVolume
MamaDouble com.wombat.mamda.MamdaAuctionListener.mUncrossVolume = new MamaDouble()
Referenced by com.wombat.mamda.MamdaAuctionListener.getUncrossVolume(), and com.wombat.mamda.MamdaAuctionListener.onMsg().
mUncrossPriceInd
MamdaUncrossPriceInd com.wombat.mamda.MamdaAuctionListener.mUncrossPriceInd = new MamdaUncrossPriceInd()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mSrcTimeFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mSrcTimeFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mActTimeFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mActTimeFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mSendTimeFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mSendTimeFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mLineTimeFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mLineTimeFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mEventTimeFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mEventTimeFieldState = new MamdaFieldState()
mIssueSymbolFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mIssueSymbolFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mPartIdFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mPartIdFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mSymbolFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mSymbolFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mEventSeqNumFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mEventSeqNumFieldState = new MamdaFieldState()
mUncrossPriceFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mUncrossPriceFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mUncrossVolumeFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mUncrossVolumeFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
mUncrossPriceIndFieldState
MamdaFieldState com.wombat.mamda.MamdaAuctionListener.mUncrossPriceIndFieldState = new MamdaFieldState()
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().