OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaBookAtomicListener Class Reference
com.wombat.mamda.orderbook.MamdaBookAtomicListener Class Reference
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.orderbook.MamdaBookAtomicLevel, com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry, and com.wombat.mamda.orderbook.MamdaBookAtomicGap.
Public Member Functions
Iterator entryIterator ()
Returns a java.util.Iterator for all entries within this level.
void addBookHandler (MamdaBookAtomicBookHandler handler)
void addLevelHandler (MamdaBookAtomicLevelHandler handler)
void addLevelEntryHandler (MamdaBookAtomicLevelEntryHandler handler)
String getSymbol ()
Get the string symbol for the instrument.
String getPartId ()
Get the participant identifier.
MamaDateTime getSrcTime ()
MamaDateTime getActivityTime ()
MamaDateTime getLineTime ()
Get the line time of the update.
MamaDateTime getSendTime ()
Get the send time of the update.
short getMsgQual ()
long getEventSeqNum ()
MamaDateTime getEventTime ()
long getPriceLevelNumLevels ()
Return the number of price levels in the order book update.
long getPriceLevelNum ()
Return at which position this level is within an update containing a number of levels.
double getPriceLevelPrice ()
Return the price for this price level.
MamaPrice getPriceLevelMamaPrice ()
Return the MamaPrice for this price level.
double getPriceLevelSize ()
Return the number of order entries comprising this price level.
long getPriceLevelSizeChange ()
Aggregate size at current price level.
char getPriceLevelAction ()
The action to apply to the orderbook for this price level.
char getPriceLevelSide ()
Side of book at current price level.
MamaDateTime getPriceLevelTime ()
Time of order book price level.
double getPriceLevelNumEntries ()
Number of order book entries at current price level.
void setOrderType (char orderType)
char getOrderType ()
boolean getHasMarketOrders ()
void setProcessMarketOrders (boolean process)
long getPriceLevelActNumEntries ()
char getPriceLevelEntryAction ()
Order book entry action to apply to the full order book.
char getPriceLevelEntryReason ()
Reason for order book entry.
String getPriceLevelEntryId ()
Order book entry Id.
long getPriceLevelEntrySize ()
Return the order book entry size.
MamaDateTime getPriceLevelEntryTime ()
Return the time of order book entry update.
long getBeginGapSeqNum ()
Beginning sequence number in a detected gap event.
long getEndGapSeqNum ()
Ending sequence number in a detected gap event.
void setPriceLevel (long priceLevel)
boolean isVisible ()
short getSymbolFieldState ()
short getPartIdFieldState ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getLineTimeFieldState ()
short getSendTimeFieldState ()
short getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Member Function Documentation
entryIterator()
Iterator com.wombat.mamda.orderbook.MamdaBookAtomicListener.entryIterator ()
Returns a java.util.Iterator for all entries within this level.
Price Level entries are represented by the MamdaOrderBookEntry class.
Returns
Iterator The iterator for the price level entries
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
addBookHandler()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.addBookHandler (MamdaBookAtomicBookHandler handler)
addLevelHandler()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.addLevelHandler (MamdaBookAtomicLevelHandler handler)
addLevelEntryHandler()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.addLevelEntryHandler (MamdaBookAtomicLevelEntryHandler handler)
getSymbol()
String com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
getPartId()
String com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getSrcTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
getLineTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getMsgQual()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getMsgQual ()
getEventSeqNum()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
getEventTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getPriceLevelNumLevels()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelNumLevels ()
Return the number of price levels in the order book update.
Returns
The number of price levels.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelNum()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelNum ()
Return at which position this level is within an update containing a number of levels.
(i.e. level m of n levels in the update)
Returns
The position of this level in the update received.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelPrice()
double com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelPrice ()
Return the price for this price level.
Returns
The price level price.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelMamaPrice()
MamaPrice com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelMamaPrice ()
Return the MamaPrice for this price level.
Returns
The price level price.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelSize()
double com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelSize ()
Return the number of order entries comprising this price level.
Not supported for V5 entry book updates.
Returns
The number of entries in this price level.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelSizeChange()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelSizeChange ()
Aggregate size at current price level.
Not supported for V5 entry book updates.
Returns
The aggregate size at the current price level.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelAction()
char com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelAction ()
The action to apply to the orderbook for this price level.
Can have a value of:
A : Add a new price level
U : Update an existing price level
D : Delete an existing price level
C : Closing information for price level (often treat the same as Update).
Not supported for V5 entry book updates.
Returns
The price level action.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelSide()
char com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelSide ()
Side of book at current price level.
B : Bid side. Same as 'buy' side.
A : Ask side. Same as 'sell' side.
Returns
The price level side.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelTime ()
Time of order book price level.
Returns
The time of the orderbook price level.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
getPriceLevelNumEntries()
double com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelNumEntries ()
Number of order book entries at current price level.
Not supported for V5 entry book updates.
Returns
The number of entries at the current price level.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevel.
setOrderType()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.setOrderType (char orderType)
getOrderType()
char com.wombat.mamda.orderbook.MamdaBookAtomicListener.getOrderType ()
getHasMarketOrders()
boolean com.wombat.mamda.orderbook.MamdaBookAtomicListener.getHasMarketOrders ()
setProcessMarketOrders()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.setProcessMarketOrders (boolean process)
getPriceLevelActNumEntries()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelActNumEntries ()
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getPriceLevelEntryAction()
char com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelEntryAction ()
Order book entry action to apply to the full order book.
A : Add entry to the price level. U : Update existing entry in the price level. D : Delete existing entry from the price level.
Returns
The orderbook entry action.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getPriceLevelEntryReason()
char com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelEntryReason ()
Reason for order book entry.
Returns
The orderbook entry reason.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getPriceLevelEntryId()
String com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelEntryId ()
Order book entry Id.
(order ID, participant ID, etc.)
Returns
The entry id
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getPriceLevelEntrySize()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelEntrySize ()
Return the order book entry size.
Returns
Order book entry size
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getPriceLevelEntryTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPriceLevelEntryTime ()
Return the time of order book entry update.
Returns
Time of order book entry update.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getBeginGapSeqNum()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getBeginGapSeqNum ()
Beginning sequence number in a detected gap event.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicGap.
getEndGapSeqNum()
long com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEndGapSeqNum ()
Ending sequence number in a detected gap event.
Implements com.wombat.mamda.orderbook.MamdaBookAtomicGap.
setPriceLevel()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.setPriceLevel (long priceLevel)
isVisible()
boolean com.wombat.mamda.orderbook.MamdaBookAtomicListener.isVisible ()
Implements com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.
getSymbolFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getPartIdFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSrcTimeFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getActivityTimeFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getLineTimeFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSendTimeFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getEventTimeFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getEventSeqNumFieldState()
short com.wombat.mamda.orderbook.MamdaBookAtomicListener.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
onMsg()
void com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Parameters
subscription The MamdaSubscription to which this listener was registered.
msg The MamaMsg received by the underlying MAMA API and which resulted in this callback being invoked.
msgType The message type. e.g. INITIAL, RECAP, UPDATE etc.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_UNKNOWN, com.wombat.mamda.MamdaCommonFields.ACTIVITY_TIME, com.wombat.mamda.orderbook.MamdaOrderBook.addEntry(), com.wombat.mamda.orderbook.MamdaOrderBookFields.ASK_MARKET_ORDERS, com.wombat.mamda.orderbook.MamdaOrderBook.askIterator(), com.wombat.mamda.orderbook.MamdaOrderBookFields.BID_MARKET_ORDERS, com.wombat.mamda.orderbook.MamdaOrderBook.bidIterator(), com.wombat.mamda.orderbook.MamdaOrderBookFields.BOOK_TIME, com.wombat.mamda.orderbook.MamdaOrderBookFields.BOOK_TYPE, com.wombat.mamda.orderbook.MamdaOrderBook.clear(), com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_ACTION, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_ID, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_REASON, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_SIZE, com.wombat.mamda.orderbook.MamdaOrderBookFields.ENTRY_TIME, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.entryIterator(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getAction(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getAction(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getClosure(), com.wombat.mamda.orderbook.MamdaOrderBookFields.getHasVectorFields(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getNumEntries(), com.wombat.mamda.orderbook.MamdaOrderBookFields.getNumEntryFields(), com.wombat.mamda.orderbook.MamdaOrderBookFields.getNumLevelFields(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getReason(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getSize(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSize(), com.wombat.mamda.MamdaFieldState.getState(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.getTime(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getTime(), com.wombat.mamda.orderbook.MamdaOrderBook.getTotalNumLevels(), com.wombat.mamda.orderbook.MamdaOrderBookFields.isSet(), com.wombat.mamda.MamdaCommonFields.LINE_TIME, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_LEVEL_MARKET, com.wombat.mamda.orderbook.MamdaOrderBookTypes.MAMDA_BOOK_REASON_UNKNOWN, com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaCommonFields.MSG_QUAL, com.wombat.mamda.MamdaFieldState.NOT_INITIALISED, com.wombat.mamda.orderbook.MamdaOrderBookFields.NUM_LEVELS, com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicBeginBook(), com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicClear(), com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicEndBook(), com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicGap(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelHandler.onBookAtomicLevelDelta(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntryHandler.onBookAtomicLevelEntryDelta(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntryHandler.onBookAtomicLevelEntryRecap(), com.wombat.mamda.orderbook.MamdaBookAtomicLevelHandler.onBookAtomicLevelRecap(), com.wombat.mamda.MamdaCommonFields.PART_ID, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_ACTION, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_ENTRIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_ENTRY, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_NUM_ATTACH, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_NUM_ENTRIES, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_PRICE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_SIDE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_SIZE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_SIZE_CHANGE, com.wombat.mamda.orderbook.MamdaOrderBookFields.PL_TIME, com.wombat.mamda.orderbook.MamdaOrderBookFields.PRICE_LEVEL, com.wombat.mamda.orderbook.MamdaOrderBookFields.PRICE_LEVELS, com.wombat.mamda.MamdaCommonFields.SEND_TIME, com.wombat.mamda.orderbook.MamdaOrderBookEntry.setClosure(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setReason(), com.wombat.mamda.MamdaFieldState.setState(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID, com.wombat.mamda.MamdaCommonFields.SRC_TIME, and com.wombat.mamda.MamdaCommonFields.SYMBOL.