OpenMAMDA Java API: com.wombat.mamda.MamdaSubscription Class Reference
com.wombat.mamda.MamdaSubscription Class Reference
A MamdaSubscription is used to register interest in a particular symbol and source.
Public Member Functions
MamdaSubscription ()
Default constructor.
void create (MamaTransport transport, MamaQueue queue, String source, String symbol, Object closure)
Create and activate a subscription.
void setSource (String source)
Set the data source name.
void setSymbol (String symbol)
Set the symbol.
void setTransport (MamaTransport transport)
Set the MAMA transport.
void setQueue (MamaQueue queue)
Set the MAMA queue.
void setType (MamaSubscriptionType type)
Set the subscrption type.
void setServiceLevel (short serviceLevel, short serviceLevelOpt)
Set the MAMA service level.
void setRequireInitial (boolean require)
Set whether an initial value is required.
void setTimeout (double timeout)
Set the timeout (in seconds) for this subscription.
void setRetries (int retries)
Set the retries for this subscirption.
void setClosure (Object closure)
Set the closure.
void addMsgListener (MamdaMsgListener listener)
Add a listener for regular messages.
Vector getMsgListeners ()
void addStaleListener (MamdaStaleListener listener)
Add a listener for changes in stale status.
void addErrorListener (MamdaErrorListener listener)
Add a listener for error events.
synchronized void activate ()
Activate the subscription.
void deactivate ()
Deactivate the subscription.
MamaSubscriptionType getSubscriptionType ()
Returns the underlying MamaSubscriptionType for the specified Subscription.
short getServiceLevel ()
Get the service level for the specified Subscription.
long getServiceLevelOpt ()
Get the service level options for the specified subscription.
void setRequiresInitial (boolean requiresInitial)
Whether an initial value is required for the specified Subscription.
boolean getRequiresInitial ()
Returns a value of true or false indicating whether this Subscription is interested in initial values.
void setAppDataType (MamaMdDataType appDataType)
Set the application-specific data type.
MamaMdDataType getAppDataType ()
Retrieve the application-specific data type.
void setRecoverGaps (boolean doesRecover)
Whether a Subscription should attempt to recover from sequence number gaps.
boolean getRecoverGaps ()
Whether the specified subscription will attempt to recover from sequence number gaps.
void setPreInitialCacheSize (int cacheSize)
Set the number of messages to cache for each symbol before the initial value arrives.
int getPreInitialCacheSize ()
Return the initial value cache size.
MamaMsgQualifier getMsgQualifier ()
Return the MamaMsgQualifier.
void requestRecap ()
Force a recap request to be sent for this subscription.
int getRetries ()
double getTimeout ()
String getSource ()
String getSymbol ()
MamaQueue getQueue ()
MamaTransport getTransport ()
Object getClosure ()
Get the additional object passed as the closure to the create() method.
long getSeqNum ()
MamaSubscription getMamaSubscription ()
Detailed Description
A MamdaSubscription is used to register interest in a particular symbol and source.
A MamaTransport is required to actually activate the subscription.
Multiple listeners can be added to the MamdaSubscription. In this way, an application can make use of more than one of the specialized value added MAMDA listeners, such as MamdaTradeListener and MamdaQuoteListener.
Constructor & Destructor Documentation
MamdaSubscription()
com.wombat.mamda.MamdaSubscription.MamdaSubscription ()
Default constructor.
The subscription is not created until either create() or activate() is called.
Member Function Documentation
create()
void com.wombat.mamda.MamdaSubscription.create (MamaTransport transport, MamaQueue queue, String source, String symbol, Object closure)
Create and activate a subscription.
Any properties for the subscription should be set prior to calling this method.
References com.wombat.mamda.MamdaSubscription.activate(), com.wombat.mamda.MamdaSubscription.setClosure(), com.wombat.mamda.MamdaSubscription.setQueue(), com.wombat.mamda.MamdaSubscription.setSource(), com.wombat.mamda.MamdaSubscription.setSymbol(), and com.wombat.mamda.MamdaSubscription.setTransport().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBookChecker.MamdaOrderBookChecker().
setSource()
void com.wombat.mamda.MamdaSubscription.setSource (String source)
Set the data source name.
Do this before calling activate().
Referenced by com.wombat.mamda.MamdaSubscription.create().
setSymbol()
void com.wombat.mamda.MamdaSubscription.setSymbol (String symbol)
Set the symbol.
Do this before calling activate().
Referenced by com.wombat.mamda.MamdaSubscription.create().
setTransport()
void com.wombat.mamda.MamdaSubscription.setTransport (MamaTransport transport)
Set the MAMA transport.
Do this before calling activate().
Referenced by com.wombat.mamda.MamdaSubscription.create().
setQueue()
void com.wombat.mamda.MamdaSubscription.setQueue (MamaQueue queue)
Set the MAMA queue.
Do this before calling activate().
Referenced by com.wombat.mamda.MamdaSubscription.create().
setType()
void com.wombat.mamda.MamdaSubscription.setType (MamaSubscriptionType type)
Set the subscrption type.
Do this before calling activate(). Default is MamaSubscriptionType.NORMAL
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBookChecker.MamdaOrderBookChecker().
setServiceLevel()
void com.wombat.mamda.MamdaSubscription.setServiceLevel (short serviceLevel, short serviceLevelOpt)
Set the MAMA service level.
Do this before calling activate(). Default value is MamaServiceLevel.REAL_TIME and 0
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
setRequireInitial()
void com.wombat.mamda.MamdaSubscription.setRequireInitial (boolean require)
Set whether an initial value is required.
Do this before calling activate(). Default is true
setTimeout()
void com.wombat.mamda.MamdaSubscription.setTimeout (double timeout)
Set the timeout (in seconds) for this subscription.
Do this before calling activate(). Default is 10 seconds.
setRetries()
void com.wombat.mamda.MamdaSubscription.setRetries (int retries)
Set the retries for this subscirption.
Do this before calling activate. Default is 3
setClosure()
void com.wombat.mamda.MamdaSubscription.setClosure (Object closure)
Set the closure.
Do this before calling activate().
Referenced by com.wombat.mamda.MamdaSubscription.create().
addMsgListener()
void com.wombat.mamda.MamdaSubscription.addMsgListener (MamdaMsgListener listener)
Add a listener for regular messages.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.getFailureCount(), and com.wombat.mamda.orderbook.MamdaOrderBookChecker.MamdaOrderBookChecker().
getMsgListeners()
Vector com.wombat.mamda.MamdaSubscription.getMsgListeners ()
addStaleListener()
void com.wombat.mamda.MamdaSubscription.addStaleListener (MamdaStaleListener listener)
Add a listener for changes in stale status.
addErrorListener()
void com.wombat.mamda.MamdaSubscription.addErrorListener (MamdaErrorListener listener)
Add a listener for error events.
activate()
synchronized void com.wombat.mamda.MamdaSubscription.activate ()
Activate the subscription.
Until this method is invoked, no updates will be received.
Referenced by com.wombat.mamda.MamdaSubscription.create().
deactivate()
void com.wombat.mamda.MamdaSubscription.deactivate ()
Deactivate the subscription.
No more updates will be received for this subscription (unless activate() is invoked again).
This function must be called from the same thread dispatching on the associated event queue unless both the default queue and dispatch queue are not actively dispatching.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
getSubscriptionType()
MamaSubscriptionType com.wombat.mamda.MamdaSubscription.getSubscriptionType ()
Returns the underlying MamaSubscriptionType for the specified Subscription.
getServiceLevel()
short com.wombat.mamda.MamdaSubscription.getServiceLevel ()
Get the service level for the specified Subscription.
getServiceLevelOpt()
long com.wombat.mamda.MamdaSubscription.getServiceLevelOpt ()
Get the service level options for the specified subscription.
Returns
serviceLevel
setRequiresInitial()
void com.wombat.mamda.MamdaSubscription.setRequiresInitial (boolean requiresInitial)
Whether an initial value is required for the specified Subscription.
This only applies to market data subscriptions and not to basic subscriptions. Default value of true indicating that initial values are required.
Parameters
requiresInitial [true|false] Whether to request an initial value or not.
getRequiresInitial()
boolean com.wombat.mamda.MamdaSubscription.getRequiresInitial ()
Returns a value of true or false indicating whether this Subscription is interested in initial values.
Returns
boolean
setAppDataType()
void com.wombat.mamda.MamdaSubscription.setAppDataType (MamaMdDataType appDataType)
Set the application-specific data type.
Parameters
appDataType The application-specific data type.
getAppDataType()
MamaMdDataType com.wombat.mamda.MamdaSubscription.getAppDataType ()
Retrieve the application-specific data type.
Returns
appDataType .
setRecoverGaps()
void com.wombat.mamda.MamdaSubscription.setRecoverGaps (boolean doesRecover)
Whether a Subscription should attempt to recover from sequence number gaps.
Parameters
doesRecover indicates not to recover. true The Subscription will attempt to recover via a recap request.
getRecoverGaps()
boolean com.wombat.mamda.MamdaSubscription.getRecoverGaps ()
Whether the specified subscription will attempt to recover from sequence number gaps.
Returns
boolean - false does not recoever true - does attempt to recover
setPreInitialCacheSize()
void com.wombat.mamda.MamdaSubscription.setPreInitialCacheSize (int cacheSize)
Set the number of messages to cache for each symbol before the initial value arrives.
This allows the Subscription to recover when the initial value arrives late (after a subsequent trade or quote already arrived).
For group subscription, a separate cache is used for each group member.
The default is 10.
Parameters
cacheSize The size of the cache.
getPreInitialCacheSize()
int com.wombat.mamda.MamdaSubscription.getPreInitialCacheSize ()
Return the initial value cache size.
Returns
cacheSize
getMsgQualifier()
MamaMsgQualifier com.wombat.mamda.MamdaSubscription.getMsgQualifier ()
Return the MamaMsgQualifier.
Returns
MamaMsgQualifier
requestRecap()
void com.wombat.mamda.MamdaSubscription.requestRecap ()
Force a recap request to be sent for this subscription.
getRetries()
int com.wombat.mamda.MamdaSubscription.getRetries ()
getTimeout()
double com.wombat.mamda.MamdaSubscription.getTimeout ()
getSource()
String com.wombat.mamda.MamdaSubscription.getSource ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
getSymbol()
String com.wombat.mamda.MamdaSubscription.getSymbol ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), com.wombat.mamda.options.MamdaOptionChainListener.onMsg(), com.wombat.mamda.MamdaMultiParticipantManager.onMsg(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getQueue()
MamaQueue com.wombat.mamda.MamdaSubscription.getQueue ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow(), and com.wombat.mamda.orderbook.MamdaOrderBookChecker.getFailureCount().
getTransport()
MamaTransport com.wombat.mamda.MamdaSubscription.getTransport ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
getClosure()
Object com.wombat.mamda.MamdaSubscription.getClosure ()
Get the additional object passed as the closure to the create() method.
getSeqNum()
long com.wombat.mamda.MamdaSubscription.getSeqNum ()
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
getMamaSubscription()
MamaSubscription com.wombat.mamda.MamdaSubscription.getMamaSubscription ()
References com.wombat.mamda.MamdaErrorCode.codeForMamaStatus(), com.wombat.mamda.MamdaErrorListener.onError(), com.wombat.mamda.MamdaMsgListener.onMsg(), com.wombat.mamda.MamdaStaleListener.onStale(), com.wombat.mamda.MamdaErrorSeverity.severityForErrorCode(), and com.wombat.mamda.MamdaErrorCode.stringForMamdaError().