OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta Class Reference
com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta Class Reference
MamdaOrderBookConcreteComplexDelta is a class that saves information about a complex order book delta.
Inherits com.wombat.mamda.orderbook.MamdaOrderBookComplexDelta.
Public Member Functions
MamaDateTime getSrcTime ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setSrcTime (MamaDateTime srcTime)
MamaDateTime getActivityTime ()
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setActivityTime (MamaDateTime activityTime)
MamaDateTime getEventTime ()
short getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setEventTime (MamaDateTime eventTime)
long getEventSeqNum ()
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void setEventSeqNum (long eventSeqNum)
Public Member Functions inherited from com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList
MamdaOrderBookBasicDeltaList ()
void clear ()
Clear the delta.
void setKeepBasicDeltas (boolean keep)
Set whether to actually keep the basic deltas.
int getModifiedSides ()
Get which side(s) of the book have been modified by this complex update.
void add (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
Add a basic delta.
MamdaOrderBook getOrderBook ()
Get the MamdaOrderBook object to which this delta belongs.
long getSize ()
Return the number of simple deltas in this complex delta.
void dump (OutputStream output)
Dump the complex update to the output stream.
void dump ()
Dump the complex update to the output stream.
Iterator iterator ()
Additional Inherited Members
Static Public Attributes inherited from com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList
static final int MOD_SIDES_NONE = 0
static final int MOD_SIDES_BID = 1
static final int MOD_SIDES_ASK = 2
static final int MOD_SIDES_BID_AND_ASK = 3
Detailed Description
MamdaOrderBookConcreteComplexDelta is a class that saves information about a complex order book delta.
A complex delta involves multiple entries and/or price levels. For example, a modified order may involve a price change that means moving an entry from one price level to another. A complex delta is made up of several simple deltas, which can be iterated over by methods provided in the class.
Member Function Documentation
getSrcTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTime().
getSrcTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getSrcTimeFieldState().
setSrcTime()
void com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setSrcTime (MamaDateTime srcTime)
References com.wombat.mamda.MamdaConcreteBasicEvent.setSrcTime().
getActivityTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTime().
getActivityTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getActivityTimeFieldState().
setActivityTime()
void com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setActivityTime (MamaDateTime activityTime)
References com.wombat.mamda.MamdaConcreteBasicEvent.setActivityTime().
getEventTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventTime().
getEventTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventTimeFieldState().
setEventTime()
void com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setEventTime (MamaDateTime eventTime)
References com.wombat.mamda.MamdaConcreteBasicEvent.setEventTime().
getEventSeqNum()
long com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNum().
getEventSeqNumFieldState()
short com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaConcreteBasicEvent.getEventSeqNumFieldState().
setEventSeqNum()
void com.wombat.mamda.orderbook.MamdaOrderbookConcreteComplexDelta.setEventSeqNum (long eventSeqNum)
References com.wombat.mamda.MamdaConcreteBasicEvent.setEventSeqNum().