OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta Class Reference
MamdaOrderBookBasicDelta is a class that saves information about a basic order book delta.
Inherited by com.wombat.mamda.orderbook.MamdaOrderBookSimpleDelta.
Public Member Functions
MamdaOrderBookBasicDelta ()
MamdaOrderBookBasicDelta (MamdaOrderBookBasicDelta source)
void clear ()
Clear the delta.
void set (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
Set the delta info.
void setPriceLevel (MamdaOrderBookPriceLevel level)
Set the MamdaOrderBookPriceLevel object to which this entry belongs.
void setPlDeltaAction (char action)
Set the delta action with respect to the price level.
MamdaOrderBookPriceLevel getPriceLevel ()
Get the MamdaOrderBookPriceLevel object related to this basic delta.
MamdaOrderBookEntry getEntry ()
Get the MamdaOrderBookEntry object related to this basic delta.
double getPlDeltaSize ()
Get the difference in size for the price level.
char getPlDeltaAction ()
Get the delta action with respect to the price level.
char getEntryDeltaAction ()
Get the delta action with respect to the entry.
MamdaOrderBook getOrderBook ()
Get the MamdaOrderBook object to which this delta belongs.
void dump (OutputStream output)
Dump the simple update to the output stream.
void dump ()
Dump the simple update to the output stream.
Detailed Description
MamdaOrderBookBasicDelta is a class that saves information about a basic order book delta.
A basic delta is one that affects a single order book entry.
Constructor & Destructor Documentation
MamdaOrderBookBasicDelta() [1/2]
com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.MamdaOrderBookBasicDelta ()
References com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.clear().
MamdaOrderBookBasicDelta() [2/2]
com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.MamdaOrderBookBasicDelta (MamdaOrderBookBasicDelta source)
Member Function Documentation
clear()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.clear ()
Clear the delta.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.ACTION_UNKNOWN.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.MamdaOrderBookBasicDelta().
set()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.set (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
Set the delta info.
Parameters
entry The entry
level The level
plDeltaSize The delta size
plAction The price level action
entryAction The entry action
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.add(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setPriceLevel()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.setPriceLevel (MamdaOrderBookPriceLevel level)
Set the MamdaOrderBookPriceLevel object to which this entry belongs.
This method is invoked internally, by the MAMDA API, when an entry is added to a price level.
Parameters
level The price level to be associated with.
setPlDeltaAction()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.setPlDeltaAction (char action)
Set the delta action with respect to the price level.
Parameters
action The price level action.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getSize().
getPriceLevel()
MamdaOrderBookPriceLevel com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPriceLevel ()
Get the MamdaOrderBookPriceLevel object related to this basic delta.
Returns
The price level.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.add(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getSize().
getEntry()
MamdaOrderBookEntry com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getEntry ()
Get the MamdaOrderBookEntry object related to this basic delta.
Returns
The entry.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPlDeltaSize()
double com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPlDeltaSize ()
Get the difference in size for the price level.
Returns
The price level size delta.
getPlDeltaAction()
char com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPlDeltaAction ()
Get the delta action with respect to the price level.
Returns
The price level action.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getSize().
getEntryDeltaAction()
char com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getEntryDeltaAction ()
Get the delta action with respect to the entry.
Returns
The entry action.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getOrderBook()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getOrderBook ()
Get the MamdaOrderBook object to which this delta belongs.
Returns
The order book related to this delta.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getOrderBook().
dump() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.dump (OutputStream output)
Dump the simple update to the output stream.
Parameters
output The OutputStream to write the update to.
References com.wombat.mamda.orderbook.MamdaOrderBookEntry.getId(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getPrice(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.dump().
dump() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.dump ()
Dump the simple update to the output stream.