OpenMAMDA Java API: com.wombat.mamda.MamdaAuctionFields Class Reference
com.wombat.mamda.MamdaAuctionFields Class Reference
Maintains a cache of common update field descriptors.
Inherits com.wombat.mamda.MamdaFields.
Static Public Member Functions
static void setDictionary (MamaDictionary dictionary, Properties properties)
Set the dictionary for common update fields.
static boolean isSet ()
static void reset ()
static int getMaxFid ()
Static Public Attributes
static MamaFieldDescriptor UNCROSS_PRICE = null
static MamaFieldDescriptor UNCROSS_VOLUME = null
static MamaFieldDescriptor UNCROSS_PRICE_IND = null
static int MAX_FID = 0
Additional Inherited Members
Static Protected Member Functions inherited from com.wombat.mamda.MamdaFields
static String lookupFieldName (Properties properties, String defaultFieldName)
Look up a given field name mapping from the Properties object.
Detailed Description
Maintains a cache of common update field descriptors.
Member Function Documentation
setDictionary()
static void com.wombat.mamda.MamdaAuctionFields.setDictionary (MamaDictionary dictionary, Properties properties) static
Set the dictionary for common update fields.
Maintains a cache of MamaFieldDescriptors for common update related fields. The properties parameter allows users of the API to map the common dictionary names to something else if they are being published under different names.
Parameters
dictionary A reference to a valid MamaDictionary
properties A Properties object containing field mappings. (See MamdaFields for more information)
References com.wombat.mamda.MamdaFields.lookupFieldName(), and com.wombat.mamda.MamdaCommonFields.setDictionary().
isSet()
static boolean com.wombat.mamda.MamdaAuctionFields.isSet () static
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
reset()
static void com.wombat.mamda.MamdaAuctionFields.reset () static
References com.wombat.mamda.MamdaCommonFields.isSet(), and com.wombat.mamda.MamdaCommonFields.reset().
getMaxFid()
static int com.wombat.mamda.MamdaAuctionFields.getMaxFid () static
References com.wombat.mamda.MamdaAuctionFields.MAX_FID.
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
Member Data Documentation
UNCROSS_PRICE
MamaFieldDescriptor com.wombat.mamda.MamdaAuctionFields.UNCROSS_PRICE = null static
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
UNCROSS_VOLUME
MamaFieldDescriptor com.wombat.mamda.MamdaAuctionFields.UNCROSS_VOLUME = null static
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
UNCROSS_PRICE_IND
MamaFieldDescriptor com.wombat.mamda.MamdaAuctionFields.UNCROSS_PRICE_IND = null static
Referenced by com.wombat.mamda.MamdaAuctionListener.onMsg().
MAX_FID
int com.wombat.mamda.MamdaAuctionFields.MAX_FID = 0 static
Referenced by com.wombat.mamda.MamdaAuctionFields.getMaxFid().