OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap Class Reference
MamdaOrderBookConcreteRecap is a class that saves information about a full order book image.
Inherits com.wombat.mamda.MamdaConcreteBasicEvent, and com.wombat.mamda.orderbook.MamdaOrderBookRecap.
Public Member Functions
MamdaOrderBook getOrderBook ()
Returns a reference to the full orderbook if a full book is being maintained by the MamdaOrderBookListener.
void setBook (MamdaOrderBook book)
MamaDateTime getSendTime ()
Get the send time of the update.
short getSendTimeFieldState ()
void setSendTime (MamaDateTime sendTime)
MamaDateTime getLineTime ()
Get the line time of the update.
short getLineTimeFieldState ()
void setLineTime (MamaDateTime lineTime)
String getPartId ()
Get the participant identifier.
short getPartIdFieldState ()
void setPartId (String partId)
String getSymbol ()
Get the string symbol for the instrument.
short getSymbolFieldState ()
void setSymbol (String symbol)
Public Member Functions inherited from com.wombat.mamda.MamdaConcreteBasicEvent
MamaDateTime getSrcTime ()
short getSrcTimeFieldState ()
void setSrcTime (MamaDateTime srcTime)
MamaDateTime getActivityTime ()
short getActivityTimeFieldState ()
void setActivityTime (MamaDateTime activityTime)
MamaDateTime getEventTime ()
short getEventTimeFieldState ()
void setEventTime (MamaDateTime eventTime)
long getEventSeqNum ()
short getEventSeqNumFieldState ()
void setEventSeqNum (long eventSeqNum)
Public Member Functions inherited from com.wombat.mamda.MamdaBasicRecap
MamaDateTime getSrcTime ()
Source time.
short getSrcTimeFieldState ()
MamaDateTime getActivityTime ()
Activity time.
short getActivityTimeFieldState ()
Detailed Description
MamdaOrderBookConcreteRecap is a class that saves information about a full order book image.
Member Function Documentation
getOrderBook()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getOrderBook ()
Returns a reference to the full orderbook if a full book is being maintained by the MamdaOrderBookListener.
Implements com.wombat.mamda.orderbook.MamdaOrderBookRecap.
setBook()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.setBook (MamdaOrderBook book)
getSendTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
setSendTime()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.setSendTime (MamaDateTime sendTime)
getLineTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getLineTimeFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
setLineTime()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.setLineTime (MamaDateTime lineTime)
getPartId()
String com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getPartIdFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
setPartId()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.setPartId (String partId)
getSymbol()
String com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbolFieldState()
short com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
setSymbol()
void com.wombat.mamda.orderbook.MamdaOrderBookConcreteRecap.setSymbol (String symbol)