OpenMAMDA Java API: com.wombat.mamda.MamdaSecurityStatusListener Class Reference
com.wombat.mamda.MamdaSecurityStatusListener Class Reference
MamdaSecurityStatusListener is a class that specializes in handling security status updates.
Inherits com.wombat.mamda.MamdaMsgListener, com.wombat.mamda.MamdaSecurityStatusRecap, and com.wombat.mamda.MamdaSecurityStatusUpdate.
Public Member Functions
MamdaSecurityStatusListener ()
Create a specialized trade listener.
void addHandler (MamdaSecurityStatusHandler handler)
Add a specialized trade handler.
void clearCache (MamdaSecurityStatusCache cache)
MamaDateTime getSrcTime ()
MamaDateTime getActivityTime ()
MamaDateTime getSendTime ()
Get the send time of the update.
MamaDateTime getLineTime ()
Get the line time of the update.
long getEventSeqNum ()
MamaDateTime getEventTime ()
String getPartId ()
Get the participant identifier.
String getSymbol ()
Get the string symbol for the instrument.
long getSecurityStatus ()
long getSecurityStatusQualifier ()
char getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
short getSecurityStatusEnum ()
short getSecurityStatusQualifierEnum ()
String getSecurityStatusStr ()
String getSecurityStatusQualifierStr ()
String getSecurityStatusOrigStr ()
String getReason ()
MamaDateTime getLuldTime ()
char getLuldIndicator ()
MamaPrice getLuldHighLimit ()
MamaPrice getLuldLowLimit ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getSendTimeFieldState ()
short getLineTimeFieldState ()
short getShortSaleCircuitBreakerFieldState ()
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getPartIdFieldState ()
short getSymbolFieldState ()
short getSecurityStatusFieldState ()
short getSecurityStatusQualifierFieldState ()
short getSecurityStatusEnumFieldState ()
short getSecurityStatusQualifierEnumFieldState ()
short getSecurityStatusStrFieldState ()
short getSecurityStatusQualifierStrFieldState ()
short getSecurityStatusOrigStrFieldState ()
short getReasonFieldState ()
short getLuldIndicatorFieldState ()
return the Limit Up Limit Down Indicator Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getLuldTimeFieldState ()
return the Limit Up Limit Down Time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getLuldHighLimitFieldState ()
return the Limit Up Limit Down High Limit Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getLuldLowLimitFieldState ()
return the Limit Up Limit Down Low Limit Field State MODIFIED (2) value indicates the field was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
String getFieldAsString (MamaMsgField field)
Protected Attributes
final MamdaSecurityStatusCache securityStatusCache
Detailed Description
MamdaSecurityStatusListener is a class that specializes in handling security status updates.
Developers provide their own implementation of the MamdaSecurityStatusHandler interface and will be delivered notifications for security status updates.
Note: The MamdaSecurityStatusListener class caches some field values. Among other reasons, caching of these fields makes it possible to provide complete certain callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaSecurityStatusListener()
com.wombat.mamda.MamdaSecurityStatusListener.MamdaSecurityStatusListener ()
Create a specialized trade listener.
This listener handles trade reports, trade recaps, trade errors/cancels, trade corrections, and trade gap notifications.
References com.wombat.mamda.MamdaSecurityStatusListener.clearCache().
Member Function Documentation
addHandler()
void com.wombat.mamda.MamdaSecurityStatusListener.addHandler (MamdaSecurityStatusHandler handler)
Add a specialized trade handler.
Currently, only one handler can (and must) be registered.
clearCache()
void com.wombat.mamda.MamdaSecurityStatusListener.clearCache (MamdaSecurityStatusCache cache)
References com.wombat.mamda.MamdaFieldState.NOT_INITIALISED.
Referenced by com.wombat.mamda.MamdaSecurityStatusListener.MamdaSecurityStatusListener().
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaSecurityStatusListener.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaSecurityStatusListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
getSendTime()
MamaDateTime com.wombat.mamda.MamdaSecurityStatusListener.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getLineTime()
MamaDateTime com.wombat.mamda.MamdaSecurityStatusListener.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getEventSeqNum()
long com.wombat.mamda.MamdaSecurityStatusListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
getEventTime()
MamaDateTime com.wombat.mamda.MamdaSecurityStatusListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getPartId()
String com.wombat.mamda.MamdaSecurityStatusListener.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbol()
String com.wombat.mamda.MamdaSecurityStatusListener.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
getSecurityStatus()
long com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatus ()
See also
MamdaSecurityStatusUpdate::getSecurityStatus()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
References com.wombat.mamda.MamdaSecurityStatus.mamdaSecurityStatusFromString().
getSecurityStatusQualifier()
long com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusQualifier ()
See also
MamdaSecurityStatusUpdate::getSecurityStatusQualifier()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
References com.wombat.mamda.MamdaSecurityStatusQual.mamdaSecurityStatusQualFromString().
getShortSaleCircuitBreaker()
char com.wombat.mamda.MamdaSecurityStatusListener.getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
Returns
ShortSaleCircuitBreaker
See also
MamdaSecurityStatusUpdate::getShortSaleCircuitBreaker()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusEnum()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusEnum ()
See also
MamdaSecurityStatusUpdate::getSecurityStatusEnum()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
References com.wombat.mamda.MamdaSecurityStatus.mamdaSecurityStatusFromString().
getSecurityStatusQualifierEnum()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusQualifierEnum ()
See also
MamdaSecurityStatusUpdate::getSecurityStatusQualifierEnum()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
References com.wombat.mamda.MamdaSecurityStatusQual.mamdaSecurityStatusQualFromString().
getSecurityStatusStr()
String com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusStr ()
See also
MamdaSecurityStatusUpdate::getSecurityStatusStr()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusQualifierStr()
String com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusQualifierStr ()
See also
MamdaSecurityStatusUpdate::getSecurityStatusQualifierStr()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusOrigStr()
String com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusOrigStr ()
See also
MamdaSecurityStatusUpdate::getSecurityStatusOrigStr()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getReason()
String com.wombat.mamda.MamdaSecurityStatusListener.getReason ()
See also
MamdaSecurityStatusUpdate::getReason()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldTime()
MamaDateTime com.wombat.mamda.MamdaSecurityStatusListener.getLuldTime ()
See also
MamdaSecurityStatusUpdate::getLuldTime()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldIndicator()
char com.wombat.mamda.MamdaSecurityStatusListener.getLuldIndicator ()
See also
MamdaSecurityStatusUpdate::getLuldIndicator()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldHighLimit()
MamaPrice com.wombat.mamda.MamdaSecurityStatusListener.getLuldHighLimit ()
See also
MamdaSecurityStatusUpdate::getLuldHighLimit()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldLowLimit()
MamaPrice com.wombat.mamda.MamdaSecurityStatusListener.getLuldLowLimit ()
See also
MamdaSecurityStatusUpdate::getLuldLowLimit()
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSrcTimeFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTimeFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getSendTimeFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getLineTimeFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getShortSaleCircuitBreakerFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getShortSaleCircuitBreakerFieldState ()
Returns
Returns the FieldState, always MODIFIED.
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getEventSeqNumFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getEventTimeFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
getPartIdFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbolFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
getSecurityStatusFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusFieldState ()
Returns
the security status Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusQualifierFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusQualifierFieldState ()
Returns
the security status Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusEnumFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusEnumFieldState ()
Returns
the security status Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusQualifierEnumFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusQualifierEnumFieldState ()
Returns
the security status qualifier enum Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusStrFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusStrFieldState ()
Returns
the security status string Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusQualifierStrFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusQualifierStrFieldState ()
Returns
the security status qualifier string Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getSecurityStatusOrigStrFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getSecurityStatusOrigStrFieldState ()
Returns
the security status orig string Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getReasonFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getReasonFieldState ()
Returns
the reason Field State
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldIndicatorFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getLuldIndicatorFieldState ()
return the Limit Up Limit Down Indicator Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldTimeFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getLuldTimeFieldState ()
return the Limit Up Limit Down Time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldHighLimitFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getLuldHighLimitFieldState ()
return the Limit Up Limit Down High Limit Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
getLuldLowLimitFieldState()
short com.wombat.mamda.MamdaSecurityStatusListener.getLuldLowLimitFieldState ()
return the Limit Up Limit Down Low Limit Field State MODIFIED (2) value indicates the field was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaSecurityStatusRecap.
onMsg()
void com.wombat.mamda.MamdaSecurityStatusListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaSecurityStatusFields.ACTIVITY_TIME, com.wombat.mamda.MamdaSecurityStatusFields.getMaxFid(), com.wombat.mamda.MamdaSecurityStatusFields.isSet(), com.wombat.mamda.MamdaSecurityStatusFields.ISSUE_SYMBOL, com.wombat.mamda.MamdaSecurityStatusFields.LINE_TIME, com.wombat.mamda.MamdaSecurityStatusFields.LULDHIGHLIMIT, com.wombat.mamda.MamdaSecurityStatusFields.LULDINDICATOR, com.wombat.mamda.MamdaSecurityStatusFields.LULDLOWLIMIT, com.wombat.mamda.MamdaSecurityStatusFields.LULDTIME, com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaFieldState.NOT_MODIFIED, com.wombat.mamda.MamdaSecurityStatusHandler.onSecurityStatusRecap(), com.wombat.mamda.MamdaSecurityStatusHandler.onSecurityStatusUpdate(), com.wombat.mamda.MamdaSecurityStatusFields.PART_ID, com.wombat.mamda.MamdaSecurityStatusFields.REASON, com.wombat.mamda.MamdaSecurityStatusFields.SECURITY_STATUS, com.wombat.mamda.MamdaSecurityStatusFields.SECURITY_STATUS_ORIG, com.wombat.mamda.MamdaSecurityStatusFields.SECURITY_STATUS_QUAL, com.wombat.mamda.MamdaSecurityStatusFields.SECURITY_STATUS_TIME, com.wombat.mamda.MamdaSecurityStatusFields.SEND_TIME, com.wombat.mamda.MamdaSecurityStatusFields.SEQNUM, com.wombat.mamda.MamdaSecurityStatusFields.SHORT_SALE_CIRCUIT_BREAKER, com.wombat.mamda.MamdaSecurityStatusFields.SRC_TIME, and com.wombat.mamda.MamdaSecurityStatusFields.SYMBOL.
getFieldAsString()
String com.wombat.mamda.MamdaSecurityStatusListener.getFieldAsString (MamaMsgField field)
References com.wombat.mamda.MamdaSecurityStatusListener.getFieldAsString(), com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaFieldState.NOT_INITIALISED, and com.wombat.mamda.MamdaSecurityStatusListener.securityStatusCache.
Referenced by com.wombat.mamda.MamdaSecurityStatusListener.getFieldAsString().
Member Data Documentation
securityStatusCache
final MamdaSecurityStatusCache com.wombat.mamda.MamdaSecurityStatusListener.securityStatusCache protected
Initial value:
=
                                       new MamdaSecurityStatusCache ()
Referenced by com.wombat.mamda.MamdaSecurityStatusListener.getFieldAsString().