OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionContractSet Class Reference
com.wombat.mamda.options.MamdaOptionContractSet Class Reference
A class that represents a set of option contracts at a given strike price.
Public Member Functions
MamdaOptionContractSet ()
void setBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer.
void setWombatBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer, as calculated by NYSE Technologies.
void setExchangeContract (String exchange, MamdaOptionContract contract)
Set the contract for the particular exchange.
MamdaOptionContract getBboContract ()
Return the contract for the best bid and offer.
MamdaOptionContract getWombatBboContract ()
Return the contract for the best bid and offer, as calculated by NYSE Technologies.
MamdaOptionContract getExchangeContract (String exchange)
Return the contract for the particular exchange.
Collection getExchangeContracts ()
Return the set of individual regional exchange option contracts.
Set getExchanges ()
Return the set of individual regional exchange identifiers.
Detailed Description
A class that represents a set of option contracts at a given strike price.
Constructor & Destructor Documentation
MamdaOptionContractSet()
com.wombat.mamda.options.MamdaOptionContractSet.MamdaOptionContractSet ()
Member Function Documentation
setBboContract()
void com.wombat.mamda.options.MamdaOptionContractSet.setBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract().
setWombatBboContract()
void com.wombat.mamda.options.MamdaOptionContractSet.setWombatBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer, as calculated by NYSE Technologies.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract().
setExchangeContract()
void com.wombat.mamda.options.MamdaOptionContractSet.setExchangeContract (String exchange, MamdaOptionContract contract)
Set the contract for the particular exchange.
Referenced by com.wombat.mamda.options.MamdaOptionChain.addContract().
getBboContract()
MamdaOptionContract com.wombat.mamda.options.MamdaOptionContractSet.getBboContract ()
Return the contract for the best bid and offer.
getWombatBboContract()
MamdaOptionContract com.wombat.mamda.options.MamdaOptionContractSet.getWombatBboContract ()
Return the contract for the best bid and offer, as calculated by NYSE Technologies.
getExchangeContract()
MamdaOptionContract com.wombat.mamda.options.MamdaOptionContractSet.getExchangeContract (String exchange)
Return the contract for the particular exchange.
getExchangeContracts()
Collection com.wombat.mamda.options.MamdaOptionContractSet.getExchangeContracts ()
Return the set of individual regional exchange option contracts.
The type of object in the set is a instance of MamdaOptionContract.
getExchanges()
Set com.wombat.mamda.options.MamdaOptionContractSet.getExchanges ()
Return the set of individual regional exchange identifiers.
The type of object in the set is a instance of String.