OpenMAMDA Java API: com.wombat.mamda.MamdaMultiParticipantManager Class Reference
com.wombat.mamda.MamdaMultiParticipantManager Class Reference
MamdaMultiParticipantManager is a class that manages updates on a consolidated basis for securities that may be traded on multiple exchanges and which may have a national best bid and offer.
Inherits com.wombat.mamda.MamdaMsgListener.
Public Member Functions
MamdaMultiParticipantManager (String symbol)
Only constructor for the class.
void addHandler (MamdaMultiParticipantHandler handler)
Add a specialized handler for notifications about the multi-participant security.
void addConsolidatedListener (MamdaMsgListener listener)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for the consolidated data.
void addParticipantListener (MamdaMsgListener listener, String partId)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for a participant.
void onMsg (final MamdaSubscription subscription, final MamaMsg msg, final short msgType)
Implementation of the MamdaMsgListener Interface.
Detailed Description
MamdaMultiParticipantManager is a class that manages updates on a consolidated basis for securities that may be traded on multiple exchanges and which may have a national best bid and offer.
Developers are notified of each element available for the consolidated security, including the national best bid and offer, and each regional exchange (Market Maker). Developers can pick and choose which elements they wish to provide handling for (e.g., BBO-only, certain regional exchanges, etc.).
Specialized Listeners can be added to the MamdaMultiParticipantManager in response to the callbacks on the MamdaMultiParticipantHandler being invoked. Alternatively, the Listeners can be added up front if the participants are known in advance.
Note: the MamdaMultiParticipantManager can also be used for securities that are not traded on multiple exchanges.
Constructor & Destructor Documentation
MamdaMultiParticipantManager()
com.wombat.mamda.MamdaMultiParticipantManager.MamdaMultiParticipantManager (String symbol)
Only constructor for the class.
No default available.
Parameters
symbol The group symbol for which the corresponding subscription was created.
Member Function Documentation
addHandler()
void com.wombat.mamda.MamdaMultiParticipantManager.addHandler (MamdaMultiParticipantHandler handler)
Add a specialized handler for notifications about the multi-participant security.
Parameters
handler Concrete instance of the MamdaMultiParticipantHandler interface.
addConsolidatedListener()
void com.wombat.mamda.MamdaMultiParticipantManager.addConsolidatedListener (MamdaMsgListener listener)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for the consolidated data.
Multiple listeners can be added.
Parameters
listener Concrete instance of the MamdaMsgListener interface.
addParticipantListener()
void com.wombat.mamda.MamdaMultiParticipantManager.addParticipantListener (MamdaMsgListener listener, String partId)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for a participant.
Multiple listeners for each participant can be added.
Parameters
listener Concrete instance of the MamdaMsgListener interface.
partId The participant id for the instrument. This is suffix for the symbol in NYSE Technologies symbology.
onMsg()
void com.wombat.mamda.MamdaMultiParticipantManager.onMsg (final MamdaSubscription subscription, final MamaMsg msg, final short msgType)
Implementation of the MamdaMsgListener Interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaSubscription.getSymbol(), com.wombat.mamda.MamdaCommonFields.INDEX_SYMBOL, com.wombat.mamda.MamdaCommonFields.ISSUE_SYMBOL, com.wombat.mamda.MamdaMultiParticipantHandler.onConsolidatedCreate(), com.wombat.mamda.MamdaMsgListener.onMsg(), com.wombat.mamda.MamdaMultiParticipantHandler.onParticipantCreate(), com.wombat.mamda.MamdaCommonFields.PART_ID, and com.wombat.mamda.MamdaCommonFields.SYMBOL.