OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionFields Class Reference
com.wombat.mamda.options.MamdaOptionFields Class Reference
Maintains a cache of common options related field descriptors.
Inherits com.wombat.mamda.MamdaFields.
Static Public Member Functions
static void setDictionary (final MamaDictionary dictionary, final Properties properties)
Set the dictionary for common options fields.
static boolean isSet ()
static void reset ()
Static Public Attributes
static MamaFieldDescriptor CONTRACT_SYMBOL = null
static MamaFieldDescriptor UNDERLYING_SYMBOL = null
static MamaFieldDescriptor EXPIRATION_DATE = null
static MamaFieldDescriptor STRIKE_PRICE = null
static MamaFieldDescriptor PUT_CALL = null
static MamaFieldDescriptor OPEN_INTEREST = null
static MamaFieldDescriptor EXERCISE_STYLE = null
Additional Inherited Members
Static Protected Member Functions inherited from com.wombat.mamda.MamdaFields
static String lookupFieldName (Properties properties, String defaultFieldName)
Look up a given field name mapping from the Properties object.
Detailed Description
Maintains a cache of common options related field descriptors.
Member Function Documentation
setDictionary()
static void com.wombat.mamda.options.MamdaOptionFields.setDictionary (final MamaDictionary dictionary, final Properties properties) static
Set the dictionary for common options fields.
Maintains a cache of MamaFieldDescriptors for common options related fields. The properties parameter allows users of the API to map the common dictionary names to something else if they are being published under different names.
Parameters
dictionary A reference to a valid MamaDictionary
properties A Properties object containing field mappings. (See MamdaFields for more information)
References com.wombat.mamda.MamdaFields.lookupFieldName().
isSet()
static boolean com.wombat.mamda.options.MamdaOptionFields.isSet () static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.onMsg().
reset()
static void com.wombat.mamda.options.MamdaOptionFields.reset () static
References com.wombat.mamda.MamdaCommonFields.isSet(), and com.wombat.mamda.MamdaCommonFields.reset().
Member Data Documentation
CONTRACT_SYMBOL
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.CONTRACT_SYMBOL = null static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
UNDERLYING_SYMBOL
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.UNDERLYING_SYMBOL = null static
EXPIRATION_DATE
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.EXPIRATION_DATE = null static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
STRIKE_PRICE
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.STRIKE_PRICE = null static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
PUT_CALL
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.PUT_CALL = null static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
OPEN_INTEREST
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.OPEN_INTEREST = null static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
EXERCISE_STYLE
MamaFieldDescriptor com.wombat.mamda.options.MamdaOptionFields.EXERCISE_STYLE = null static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().