OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList Class Reference
MamdaOrderBookBasicDeltaList is a class that saves information about an order book delta that involves multiple entries and/or price levels.
Inherited by com.wombat.mamda.orderbook.MamdaOrderBookComplexDelta.
Public Member Functions
MamdaOrderBookBasicDeltaList ()
void clear ()
Clear the delta.
void setKeepBasicDeltas (boolean keep)
Set whether to actually keep the basic deltas.
int getModifiedSides ()
Get which side(s) of the book have been modified by this complex update.
void add (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
Add a basic delta.
MamdaOrderBook getOrderBook ()
Get the MamdaOrderBook object to which this delta belongs.
long getSize ()
Return the number of simple deltas in this complex delta.
void dump (OutputStream output)
Dump the complex update to the output stream.
void dump ()
Dump the complex update to the output stream.
Iterator iterator ()
Static Public Attributes
static final int MOD_SIDES_NONE = 0
static final int MOD_SIDES_BID = 1
static final int MOD_SIDES_ASK = 2
static final int MOD_SIDES_BID_AND_ASK = 3
Detailed Description
MamdaOrderBookBasicDeltaList is a class that saves information about an order book delta that involves multiple entries and/or price levels.
For example, a modified order may involve a price change that means moving an entry from one price level to another. A delta list is made up of several basic deltas, which can be iterated over by methods provided in the class.
Constructor & Destructor Documentation
MamdaOrderBookBasicDeltaList()
com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MamdaOrderBookBasicDeltaList ()
References com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_NONE.
Member Function Documentation
clear()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.clear ()
Clear the delta.
References com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_NONE.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
setKeepBasicDeltas()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.setKeepBasicDeltas (boolean keep)
Set whether to actually keep the basic deltas.
Many applications don't need the basic deltas and will iterate over part or all of the full book (with the deltas already applied). If this is set to true and an attempt is made to iterate over the basic deltas (by calling begin() or end()) then a MamdaOrderBookException will be thrown.
Parameters
keep true if to keep the basic deltas.
getModifiedSides()
int com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getModifiedSides ()
Get which side(s) of the book have been modified by this complex update.
This information may prevent the need for receivers of complex updates to iterate over one or other side of the book.
Returns
The modified side(s).
add()
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.add (MamdaOrderBookEntry entry, MamdaOrderBookPriceLevel level, double plDeltaSize, char plAction, char entryAction)
Add a basic delta.
This method adds a MamdaOrderBookBasicDelta to the list.
Parameters
entry the entry.
level the level.
plDeltaSize the delta size.
plAction the price level action.
entryAction the entry action.
References com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPriceLevel(), and com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.set().
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
getOrderBook()
MamdaOrderBook com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getOrderBook ()
Get the MamdaOrderBook object to which this delta belongs.
Returns
The order book related to this delta.
getSize()
long com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.getSize ()
Return the number of simple deltas in this complex delta.
Returns
the number of deltas.
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_ADD, com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.ACTION_DELETE, com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPlDeltaAction(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.getPriceLevel(), and com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.setPlDeltaAction().
dump() [1/2]
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.dump (OutputStream output)
Dump the complex update to the output stream.
Parameters
output The OutputStream to write the update to.
References com.wombat.mamda.orderbook.MamdaOrderBookBasicDelta.dump().
dump() [2/2]
void com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.dump ()
Dump the complex update to the output stream.
iterator()
Iterator com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator ()
References com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.getSide(), com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_ASK, com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_BID, com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_BID_AND_ASK, and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.SIDE_BID.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.apply().
Member Data Documentation
MOD_SIDES_NONE
final int com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_NONE = 0 static
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.clear(), and com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MamdaOrderBookBasicDeltaList().
MOD_SIDES_BID
final int com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_BID = 1 static
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator().
MOD_SIDES_ASK
final int com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_ASK = 2 static
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator().
MOD_SIDES_BID_AND_ASK
final int com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.MOD_SIDES_BID_AND_ASK = 3 static
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookBasicDeltaList.iterator().