OpenMAMDA Java API: com.wombat.mamda.MamdaFundamentalListener Class Reference
com.wombat.mamda.MamdaFundamentalListener Class Reference
MamdaFundamentalListener is a class that specializes in handling fundamental equity pricing/analysis attributes, indicators and ratios.
Inherits com.wombat.mamda.MamdaMsgListener, and com.wombat.mamda.MamdaFundamentals.
Public Member Functions
MamdaFundamentalListener ()
Create a specialized fundamental field listener.
void addHandler (MamdaFundamentalHandler handler)
Add a specialized fundamentals handler.
MamaDateTime getSrcTime ()
Source time.
MamaDateTime getActivityTime ()
Activity time.
MamaDateTime getSendTime ()
Get the send time of the update.
MamaDateTime getLineTime ()
Get the line time of the update.
String getPartId ()
Get the participant identifier.
String getSymbol ()
Get the string symbol for the instrument.
String getCorporateActionType ()
Corporate Action Type.
double getDividendPrice ()
Dividend price.
String getDividendFrequency ()
Frequency of the dividend payments.
String getDividendExDate ()
The date on or after which a security is traded without a previously declared dividend or distribution.
String getDividendPayDate ()
Date on which corporate action distribution will be paid or effective.
String getDividendRecordDate ()
This is the date on which all shareholders are considered a "holder of record" and ensured the right of a dividend or distribution.
String getDividendCurrency ()
Currency of dividend.
long getSharesOut ()
Shares outstanding.
long getSharesFloat ()
The number of shares of a security that are outstanding and available for trading by the public.
long getSharesAuthorized ()
Authorized shares.
double getEarningsPerShare ()
Earnings per share, including common stock, preferred stock, unexercised stock options, unexercised warrants, and some convertible debt.
double getVolatility ()
The relative rate at which the price of a security moves up and down.
double getPriceEarningsRatio ()
The most common measure of how expensive a stock is.
double getYield ()
Yield, for cash instruments where prices are published.
String getMarketSegmentNative ()
Feed-specific market segment code in native feed format.
String getMarketSectorNative ()
Feed-specific market sector code in native feed format.
String getMarketSegment ()
Market subgroup.
String getMarketSector ()
A distinct subset of a market, society, industry, or economy, whose components share similar characteristics.
double getHistoricalVolatility ()
Volatility estimated from historical data.
double getRiskFreeRate ()
Theoretical interest rate at which an investment may earn interest without incurring any risk.
short getSrcTimeFieldState ()
short getActivityTimeFieldState ()
short getSendTimeFieldState ()
short getLineTimeFieldState ()
short getPartIdFieldState ()
short getSymbolFieldState ()
short getCorporateActionTypeFieldState ()
short getDividendPriceFieldState ()
short getDividendFrequencyFieldState ()
short getDividendExDateFieldState ()
short getDividendPayDateFieldState ()
short getDividendRecordDateFieldState ()
short getDividendCurrencyFieldState ()
short getSharesOutFieldState ()
short getSharesFloatFieldState ()
short getSharesAuthorizedFieldState ()
short getEarningsPerShareFieldState ()
short getVolatilityFieldState ()
short getPriceEarningsRatioFieldState ()
short getYieldFieldState ()
short getMarketSegmentNativeFieldState ()
short getMarketSectorNativeFieldState ()
short getMarketSegmentFieldState ()
short getMarketSectorFieldState ()
short getHistoricalVolatilityFieldState ()
short getRiskFreeRateFieldState ()
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Detailed Description
MamdaFundamentalListener is a class that specializes in handling fundamental equity pricing/analysis attributes, indicators and ratios.
Developers provide their own implementation of the MamdaFundamentalHandler interface and will be delivered notifications for updates in the fundamental data. An obvious application for this MAMDA class is any kind of pricing analysis application.
Note: The MamdaFundamentalListener class caches equity pricing/analysis attributes, indicators and ratios. Among other reasons, caching of these fields makes it possible to provide complete fundamental callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaFundamentalListener()
com.wombat.mamda.MamdaFundamentalListener.MamdaFundamentalListener ()
Create a specialized fundamental field listener.
Member Function Documentation
addHandler()
void com.wombat.mamda.MamdaFundamentalListener.addHandler (MamdaFundamentalHandler handler)
Add a specialized fundamentals handler.
Referenced by com.wombat.mamda.options.MamdaOptionContract.addFundamentalHandler().
getSrcTime()
MamaDateTime com.wombat.mamda.MamdaFundamentalListener.getSrcTime ()
Source time.
Typically, the exchange generated feed
Implements com.wombat.mamda.MamdaBasicRecap.
getActivityTime()
MamaDateTime com.wombat.mamda.MamdaFundamentalListener.getActivityTime ()
Activity time.
A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicRecap.
getSendTime()
MamaDateTime com.wombat.mamda.MamdaFundamentalListener.getSendTime ()
Get the send time of the update.
Returns
Send time. A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware).
Implements com.wombat.mamda.MamdaBasicRecap.
getLineTime()
MamaDateTime com.wombat.mamda.MamdaFundamentalListener.getLineTime ()
Get the line time of the update.
Returns
Line time. A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements com.wombat.mamda.MamdaBasicRecap.
getPartId()
String com.wombat.mamda.MamdaFundamentalListener.getPartId ()
Get the participant identifier.
Returns
Participant ID. This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements com.wombat.mamda.MamdaBasicRecap.
getSymbol()
String com.wombat.mamda.MamdaFundamentalListener.getSymbol ()
Get the string symbol for the instrument.
Returns
Symbol. This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements com.wombat.mamda.MamdaBasicRecap.
getCorporateActionType()
String com.wombat.mamda.MamdaFundamentalListener.getCorporateActionType ()
Corporate Action Type.
Implements com.wombat.mamda.MamdaFundamentals.
getDividendPrice()
double com.wombat.mamda.MamdaFundamentalListener.getDividendPrice ()
Dividend price.
Implements com.wombat.mamda.MamdaFundamentals.
getDividendFrequency()
String com.wombat.mamda.MamdaFundamentalListener.getDividendFrequency ()
Frequency of the dividend payments.
: No dividend payments are made.
1M : Monthly
3M : Quarterly
6M : Semi-Annually
1Y : Annually
SP : Payment frequency is special.
NA : Irregular payment frequency.
ER : Invalid dividend frequency period.
Implements com.wombat.mamda.MamdaFundamentals.
getDividendExDate()
String com.wombat.mamda.MamdaFundamentalListener.getDividendExDate ()
The date on or after which a security is traded without a previously declared dividend or distribution.
Implements com.wombat.mamda.MamdaFundamentals.
getDividendPayDate()
String com.wombat.mamda.MamdaFundamentalListener.getDividendPayDate ()
Date on which corporate action distribution will be paid or effective.
Implements com.wombat.mamda.MamdaFundamentals.
getDividendRecordDate()
String com.wombat.mamda.MamdaFundamentalListener.getDividendRecordDate ()
This is the date on which all shareholders are considered a "holder of record" and ensured the right of a dividend or distribution.
Implements com.wombat.mamda.MamdaFundamentals.
getDividendCurrency()
String com.wombat.mamda.MamdaFundamentalListener.getDividendCurrency ()
Currency of dividend.
Implements com.wombat.mamda.MamdaFundamentals.
getSharesOut()
long com.wombat.mamda.MamdaFundamentalListener.getSharesOut ()
Shares outstanding.
The number of authorized shares in a company that are held by investors, including employees and executives of that company. (Un-issued shares and treasury shares are not included in this figure).
Implements com.wombat.mamda.MamdaFundamentals.
getSharesFloat()
long com.wombat.mamda.MamdaFundamentalListener.getSharesFloat ()
The number of shares of a security that are outstanding and available for trading by the public.
Implements com.wombat.mamda.MamdaFundamentals.
getSharesAuthorized()
long com.wombat.mamda.MamdaFundamentalListener.getSharesAuthorized ()
Authorized shares.
The number of shares that a corporation is permitted to issue.
Implements com.wombat.mamda.MamdaFundamentals.
getEarningsPerShare()
double com.wombat.mamda.MamdaFundamentalListener.getEarningsPerShare ()
Earnings per share, including common stock, preferred stock, unexercised stock options, unexercised warrants, and some convertible debt.
In companies with a large amount of convertibles, warrants and stock options, diluted earnings per share are usually a more accurate measure of the company's real earning power than earnings per share.
Implements com.wombat.mamda.MamdaFundamentals.
getVolatility()
double com.wombat.mamda.MamdaFundamentalListener.getVolatility ()
The relative rate at which the price of a security moves up and down.
Implements com.wombat.mamda.MamdaFundamentals.
getPriceEarningsRatio()
double com.wombat.mamda.MamdaFundamentalListener.getPriceEarningsRatio ()
The most common measure of how expensive a stock is.
The P/E ratio is equal to a stock's market capitalization divided by its after-tax earnings over a 12-month period, usually the trailing period but occasionally the current or forward period.
Implements com.wombat.mamda.MamdaFundamentals.
getYield()
double com.wombat.mamda.MamdaFundamentalListener.getYield ()
Yield, for cash instruments where prices are published.
Implements com.wombat.mamda.MamdaFundamentals.
getMarketSegmentNative()
String com.wombat.mamda.MamdaFundamentalListener.getMarketSegmentNative ()
Feed-specific market segment code in native feed format.
Implements com.wombat.mamda.MamdaFundamentals.
getMarketSectorNative()
String com.wombat.mamda.MamdaFundamentalListener.getMarketSectorNative ()
Feed-specific market sector code in native feed format.
Implements com.wombat.mamda.MamdaFundamentals.
getMarketSegment()
String com.wombat.mamda.MamdaFundamentalListener.getMarketSegment ()
Market subgroup.
Implements com.wombat.mamda.MamdaFundamentals.
getMarketSector()
String com.wombat.mamda.MamdaFundamentalListener.getMarketSector ()
A distinct subset of a market, society, industry, or economy, whose components share similar characteristics.
Implements com.wombat.mamda.MamdaFundamentals.
getHistoricalVolatility()
double com.wombat.mamda.MamdaFundamentalListener.getHistoricalVolatility ()
Volatility estimated from historical data.
Implements com.wombat.mamda.MamdaFundamentals.
getRiskFreeRate()
double com.wombat.mamda.MamdaFundamentalListener.getRiskFreeRate ()
Theoretical interest rate at which an investment may earn interest without incurring any risk.
Implements com.wombat.mamda.MamdaFundamentals.
getSrcTimeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getSrcTimeFieldState ()
Returns
source time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getActivityTimeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getActivityTimeFieldState ()
Returns
activity time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSendTimeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getSendTimeFieldState ()
Returns
send time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getLineTimeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getLineTimeFieldState ()
Returns
line time Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getPartIdFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getPartIdFieldState ()
Returns
participant ID Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getSymbolFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getSymbolFieldState ()
Returns
symbol Field State
Implements com.wombat.mamda.MamdaBasicRecap.
References com.wombat.mamda.MamdaFieldState.getState().
getCorporateActionTypeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getCorporateActionTypeFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getDividendPriceFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getDividendPriceFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getDividendFrequencyFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getDividendFrequencyFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getDividendExDateFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getDividendExDateFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getDividendPayDateFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getDividendPayDateFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getDividendRecordDateFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getDividendRecordDateFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getDividendCurrencyFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getDividendCurrencyFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getSharesOutFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getSharesOutFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getSharesFloatFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getSharesFloatFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getSharesAuthorizedFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getSharesAuthorizedFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getEarningsPerShareFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getEarningsPerShareFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getVolatilityFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getVolatilityFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getPriceEarningsRatioFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getPriceEarningsRatioFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getYieldFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getYieldFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getMarketSegmentNativeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getMarketSegmentNativeFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getMarketSectorNativeFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getMarketSectorNativeFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getMarketSegmentFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getMarketSegmentFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getMarketSectorFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getMarketSectorFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getHistoricalVolatilityFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getHistoricalVolatilityFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
getRiskFreeRateFieldState()
short com.wombat.mamda.MamdaFundamentalListener.getRiskFreeRateFieldState ()
Returns
Field State
Implements com.wombat.mamda.MamdaFundamentals.
References com.wombat.mamda.MamdaFieldState.getState().
onMsg()
void com.wombat.mamda.MamdaFundamentalListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaFundamentalFields.ACTIVITY_TIME, com.wombat.mamda.MamdaFundamentalFields.CORP_ACT_TYPE, com.wombat.mamda.MamdaFundamentalFields.DIVIDEND_CURRENCY, com.wombat.mamda.MamdaFundamentalFields.DIVIDEND_EX_DATE, com.wombat.mamda.MamdaFundamentalFields.DIVIDEND_FREQ, com.wombat.mamda.MamdaFundamentalFields.DIVIDEND_PAY_DATE, com.wombat.mamda.MamdaFundamentalFields.DIVIDEND_PRICE, com.wombat.mamda.MamdaFundamentalFields.DIVIDEND_REC_DATE, com.wombat.mamda.MamdaFundamentalFields.EARN_PER_SHARE, com.wombat.mamda.MamdaFieldState.getState(), com.wombat.mamda.MamdaFundamentalFields.HIST_VOLATILITY, com.wombat.mamda.MamdaFundamentalFields.isSet(), com.wombat.mamda.MamdaFundamentalFields.LINE_TIME, com.wombat.mamda.MamdaFieldState.MODIFIED, com.wombat.mamda.MamdaFundamentalFields.MRKT_SECT_NATIVE, com.wombat.mamda.MamdaFundamentalFields.MRKT_SECTOR, com.wombat.mamda.MamdaFundamentalFields.MRKT_SEGM_NATIVE, com.wombat.mamda.MamdaFundamentalFields.MRKT_SEGMENT, com.wombat.mamda.MamdaFieldState.NOT_MODIFIED, com.wombat.mamda.MamdaFundamentalHandler.onFundamentals(), com.wombat.mamda.MamdaFundamentalFields.PART_ID, com.wombat.mamda.MamdaFundamentalFields.PRICE_EARN_RATIO, com.wombat.mamda.MamdaFundamentalFields.RISK_FREE_RATE, com.wombat.mamda.MamdaFundamentalFields.SEND_TIME, com.wombat.mamda.MamdaFieldState.setState(), com.wombat.mamda.MamdaFundamentalFields.SHARES_AUTH, com.wombat.mamda.MamdaFundamentalFields.SHARES_FLOAT, com.wombat.mamda.MamdaFundamentalFields.SHARES_OUT, com.wombat.mamda.MamdaFundamentalFields.SRC_TIME, com.wombat.mamda.MamdaFundamentalFields.SYMBOL, com.wombat.mamda.MamdaFundamentalFields.VOLATILITY, and com.wombat.mamda.MamdaFundamentalFields.YIELD.