OpenMAMDA Java API: com.wombat.mamda.options.MamdaOptionChainListener Class Reference
com.wombat.mamda.options.MamdaOptionChainListener Class Reference
MamdaOptionChainListener is a class that specializes in handling and managing option chain updates.
Inherits com.wombat.mamda.MamdaMsgListener, and com.wombat.mamda.options.MamdaOptionSeriesUpdate.
Public Member Functions
MamdaOptionChainListener (String underlyingSymbol)
Create a specialized option chain listener.
MamdaOptionChainListener (MamdaOptionChain chain)
Create a specialized option chain listener.
void addHandler (MamdaOptionChainHandler handler)
Add a specialized option chain handler.
MamdaOptionChain getOptionChain ()
Return the option chain associated with this listener.
void onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
MamaDateTime getSrcTime ()
MamaDateTime getActivityTime ()
long getEventSeqNum ()
MamaDateTime getEventTime ()
short getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
short getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
MamdaOptionContract getOptionContract ()
Get the option contract to which the most recent event applies.
char getOptionAction ()
Get the most recent action.
Static Public Attributes
static final char ACTION_UNKNOWN = ' '
static final char ACTION_ADD = 'A'
static final char ACTION_DELETE = 'D'
Static Public Attributes inherited from com.wombat.mamda.options.MamdaOptionSeriesUpdate
static final char ACTION_UNKNOWN = ' '
static final char ACTION_ADD = 'A'
static final char ACTION_DELETE = 'D'
Detailed Description
MamdaOptionChainListener is a class that specializes in handling and managing option chain updates.
Developers provide their own implementation of the MamdaOptionChainHandler interface and will be delivered notifications for various types of options-related events.
Constructor & Destructor Documentation
MamdaOptionChainListener() [1/2]
com.wombat.mamda.options.MamdaOptionChainListener.MamdaOptionChainListener (String underlyingSymbol)
Create a specialized option chain listener.
This listener handles option chain updates.
MamdaOptionChainListener() [2/2]
com.wombat.mamda.options.MamdaOptionChainListener.MamdaOptionChainListener (MamdaOptionChain chain)
Create a specialized option chain listener.
This listener handles option chain updates.
References com.wombat.mamda.options.MamdaOptionChain.getSymbol().
Member Function Documentation
addHandler()
void com.wombat.mamda.options.MamdaOptionChainListener.addHandler (MamdaOptionChainHandler handler)
Add a specialized option chain handler.
Currently, only one handler can (and must) be registered.
getOptionChain()
MamdaOptionChain com.wombat.mamda.options.MamdaOptionChainListener.getOptionChain ()
Return the option chain associated with this listener.
onMsg()
void com.wombat.mamda.options.MamdaOptionChainListener.onMsg (MamdaSubscription subscription, MamaMsg msg, short msgType)
Implementation of MamdaListener interface.
Implements com.wombat.mamda.MamdaMsgListener.
References com.wombat.mamda.MamdaSubscription.getSymbol(), com.wombat.mamda.options.MamdaOptionFields.isSet(), and com.wombat.mamda.options.MamdaOptionChainHandler.onOptionChainRecap().
getSrcTime()
MamaDateTime com.wombat.mamda.options.MamdaOptionChainListener.getSrcTime ()
Returns
Source time. Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getActivityTime()
MamaDateTime com.wombat.mamda.options.MamdaOptionChainListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements com.wombat.mamda.MamdaBasicEvent.
getEventSeqNum()
long com.wombat.mamda.options.MamdaOptionChainListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements com.wombat.mamda.MamdaBasicEvent.
getEventTime()
MamaDateTime com.wombat.mamda.options.MamdaOptionChainListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements com.wombat.mamda.MamdaBasicEvent.
getSrcTimeFieldState()
short com.wombat.mamda.options.MamdaOptionChainListener.getSrcTimeFieldState ()
return Source time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getActivityTimeFieldState()
short com.wombat.mamda.options.MamdaOptionChainListener.getActivityTimeFieldState ()
return Activity time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getEventSeqNumFieldState()
short com.wombat.mamda.options.MamdaOptionChainListener.getEventSeqNumFieldState ()
return source sequence number Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getEventTimeFieldState()
short com.wombat.mamda.options.MamdaOptionChainListener.getEventTimeFieldState ()
return event time Field State MODIFIED (2) value indicates the fied was updated in last tick NOT MODIFIED (1) value indicate that there was no change in the last tick NOT_INITIALISED (0) value indicates that the field has never been updated
Implements com.wombat.mamda.MamdaBasicEvent.
References com.wombat.mamda.MamdaFieldState.getState().
getOptionContract()
MamdaOptionContract com.wombat.mamda.options.MamdaOptionChainListener.getOptionContract ()
Get the option contract to which the most recent event applies.
Returns
The option contract to which the most recent event applies. If the contract is new, it will have already been added to the chain. If it is being removed, it will have already been removed from the chain.
Implements com.wombat.mamda.options.MamdaOptionSeriesUpdate.
getOptionAction()
char com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction ()
Get the most recent action.
Returns
The action related to the last series update message.
Implements com.wombat.mamda.options.MamdaOptionSeriesUpdate.
References com.wombat.mamda.options.MamdaOptionChainListener.ACTION_ADD, com.wombat.mamda.options.MamdaOptionChain.addContract(), com.wombat.mamda.options.MamdaOptionFields.CONTRACT_SYMBOL, com.wombat.mamda.options.MamdaOptionFields.EXERCISE_STYLE, com.wombat.mamda.options.MamdaOptionFields.EXPIRATION_DATE, com.wombat.mamda.options.MamdaOptionChain.getContract(), com.wombat.mamda.options.MamdaOptionContract.getQuoteListener(), com.wombat.mamda.options.MamdaOptionContract.getTradeListener(), com.wombat.mamda.MamdaQuoteListener.onMsg(), com.wombat.mamda.MamdaTradeListener.onMsg(), com.wombat.mamda.options.MamdaOptionChainHandler.onOptionContractCreate(), com.wombat.mamda.options.MamdaOptionFields.OPEN_INTEREST, com.wombat.mamda.options.MamdaOptionFields.PUT_CALL, com.wombat.mamda.options.MamdaOptionContract.setExerciseStyle(), com.wombat.mamda.options.MamdaOptionContract.setOpenInterest(), and com.wombat.mamda.options.MamdaOptionFields.STRIKE_PRICE.
Member Data Documentation
ACTION_UNKNOWN
final char com.wombat.mamda.options.MamdaOptionChainListener.ACTION_UNKNOWN = ' ' static
ACTION_ADD
final char com.wombat.mamda.options.MamdaOptionChainListener.ACTION_ADD = 'A' static
Referenced by com.wombat.mamda.options.MamdaOptionChainListener.getOptionAction().
ACTION_DELETE
final char com.wombat.mamda.options.MamdaOptionChainListener.ACTION_DELETE = 'D' static