OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookChecker Class Reference
com.wombat.mamda.orderbook.MamdaOrderBookChecker Class Reference
Public Member Functions
MamdaOrderBookChecker (MamaTransport transport, MamaQueue queue, MamdaOrderBookCheckerHandler handler, final String source, final String symbol, double intervalSeconds)
MamdaOrderBookChecker (final MamdaSubscription realTimeSubsc, MamdaOrderBookListener realTimeListener, MamdaOrderBookCheckerHandler handler, double intervalSeconds)
long getSuccessCount ()
long getInconclusiveCount ()
long getFailureCount ()
void checkSnapShotNow ()
Constructor & Destructor Documentation
MamdaOrderBookChecker() [1/2]
com.wombat.mamda.orderbook.MamdaOrderBookChecker.MamdaOrderBookChecker (MamaTransport transport, MamaQueue queue, MamdaOrderBookCheckerHandler handler, final String source, final String symbol, double intervalSeconds)
References com.wombat.mamda.MamdaSubscription.addMsgListener(), com.wombat.mamda.MamdaSubscription.create(), and com.wombat.mamda.MamdaSubscription.setType().
MamdaOrderBookChecker() [2/2]
com.wombat.mamda.orderbook.MamdaOrderBookChecker.MamdaOrderBookChecker (final MamdaSubscription realTimeSubsc, MamdaOrderBookListener realTimeListener, MamdaOrderBookCheckerHandler handler, double intervalSeconds)
Member Function Documentation
getSuccessCount()
long com.wombat.mamda.orderbook.MamdaOrderBookChecker.getSuccessCount ()
getInconclusiveCount()
long com.wombat.mamda.orderbook.MamdaOrderBookChecker.getInconclusiveCount ()
getFailureCount()
long com.wombat.mamda.orderbook.MamdaOrderBookChecker.getFailureCount ()
References com.wombat.mamda.orderbook.MamdaOrderBookListener.addHandler(), com.wombat.mamda.MamdaSubscription.addMsgListener(), and com.wombat.mamda.MamdaSubscription.getQueue().
checkSnapShotNow()
void com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow ()
References com.wombat.mamda.orderbook.MamdaOrderBook.apply(), com.wombat.mamda.orderbook.MamdaOrderBookCheckType.APPLY_DELTA, com.wombat.mamda.orderbook.MamdaOrderBook.assertEqual(), com.wombat.mamda.orderbook.MamdaOrderBook.clear(), com.wombat.mamda.orderbook.MamdaOrderBookListener.clear(), com.wombat.mamda.orderbook.MamdaOrderBook.copy(), com.wombat.mamda.MamdaSubscription.create(), com.wombat.mamda.MamdaSubscription.deactivate(), com.wombat.mamda.orderbook.MamdaOrderBook.dump(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getEventSeqNum(), com.wombat.mamda.orderbook.MamdaOrderBookListener.getOrderBook(), com.wombat.mamda.MamdaSubscription.getQueue(), com.wombat.mamda.MamdaSubscription.getSeqNum(), com.wombat.mamda.MamdaSubscription.getSource(), com.wombat.mamda.orderbook.MamdaOrderBook.getSymbol(), com.wombat.mamda.MamdaSubscription.getSymbol(), com.wombat.mamda.MamdaSubscription.getTransport(), com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler.onFailure(), com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler.onInconclusive(), com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler.onSuccess(), com.wombat.mamda.MamdaSubscription.setServiceLevel(), com.wombat.mamda.orderbook.MamdaOrderBook.setSymbol(), com.wombat.mamda.MamdaSubscription.setType(), and com.wombat.mamda.orderbook.MamdaOrderBookCheckType.SNAPSHOT.