OpenMAMDA Java API: com.wombat.mamda.MamdaOrderImbalanceHandler Interface Reference
com.wombat.mamda.MamdaOrderImbalanceHandler Interface Reference
MamdaOrderImbalanceHandler is an interface for applications that want to have an easy way to handle order imbalance updates.
Public Member Functions
void onOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, final MamaMsg msg, MamdaOrderImbalanceRecap imbalance, MamdaOrderImbalanceUpdate update)
Method invoked when a order imbalance is reported.
void onNoOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, final MamaMsg msg, MamdaOrderImbalanceRecap imbalance, MamdaOrderImbalanceUpdate update)
Method invoked when a no order imbalance is reported.
void onOrderImbalanceRecap (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, final MamaMsg msg, MamdaOrderImbalanceRecap imbalance)
Method invoked when the current order imbalance information is available.
Detailed Description
MamdaOrderImbalanceHandler is an interface for applications that want to have an easy way to handle order imbalance updates.
The interface defines callback methods for different types of order-imbalance events:
Member Function Documentation
onOrderImbalance()
void com.wombat.mamda.MamdaOrderImbalanceHandler.onOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, final MamaMsg msg, MamdaOrderImbalanceRecap imbalance, MamdaOrderImbalanceUpdate update)
Method invoked when a order imbalance is reported.
Parameters
subscription The subscription which received this update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
imbalance Provides access to imbalance details.
update Provides access to update details.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.onMsg().
onNoOrderImbalance()
void com.wombat.mamda.MamdaOrderImbalanceHandler.onNoOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, final MamaMsg msg, MamdaOrderImbalanceRecap imbalance, MamdaOrderImbalanceUpdate update)
Method invoked when a no order imbalance is reported.
Parameters
subscription The subscription which received this update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
imbalance Provides access to imbalance details.
update Provides access to update details.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.onMsg().
onOrderImbalanceRecap()
void com.wombat.mamda.MamdaOrderImbalanceHandler.onOrderImbalanceRecap (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, final MamaMsg msg, MamdaOrderImbalanceRecap imbalance)
Method invoked when the current order imbalance information is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The subscription which received this update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
imbalance Provides access to imbalance details.
Referenced by com.wombat.mamda.MamdaOrderImbalanceListener.onMsg().