OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler Interface Reference
com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler Interface Reference
MamdaOrderBookCheckerHandler is an interface for applications that want to handle the results of the MamdaOrderBookChecker.
Public Member Functions
void onSuccess (MamdaOrderBookCheckType checkType, final MamdaOrderBook realTimeBook)
Method invoked when a successful check is completed.
void onInconclusive (MamdaOrderBookCheckType checkType, final String reason)
Method invoked when check is completed inconclusively.
void onFailure (MamdaOrderBookCheckType checkType, final String reason, final MamaMsg msg, final MamdaOrderBook realTimeBook, final MamdaOrderBook checkBook)
Method invoked when a failed check is completed.
Detailed Description
MamdaOrderBookCheckerHandler is an interface for applications that want to handle the results of the MamdaOrderBookChecker.
Callback interfaces are provided for correct and erroneous checks.
Member Function Documentation
onSuccess()
void com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler.onSuccess (MamdaOrderBookCheckType checkType, final MamdaOrderBook realTimeBook)
Method invoked when a successful check is completed.
Parameters
checkType Types of MamdaOrderBookChecks.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
onInconclusive()
void com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler.onInconclusive (MamdaOrderBookCheckType checkType, final String reason)
Method invoked when check is completed inconclusively.
An attempt to check the order book may be inconclusive if the order book sequence numbers do not match up.
Parameters
checkType Types of MamdaOrderBookChecks.
reason Reason for the sequence numbers mismatch.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().
onFailure()
void com.wombat.mamda.orderbook.MamdaOrderBookCheckerHandler.onFailure (MamdaOrderBookCheckType checkType, final String reason, final MamaMsg msg, final MamdaOrderBook realTimeBook, final MamdaOrderBook checkBook)
Method invoked when a failed check is completed.
The message provided, if non-NULL, is the one received for the snapshot or delta, depending upon the value of checkType.
Parameters
checkType Types of MamdaOrderBookChecks.
reason Reason for the failure.
msg The MamaMsg which caused failure.
realTimeBook The Real Time Order Book which is compared against.
checkBook The Aggregated Book which is compared.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookChecker.checkSnapShotNow().