OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaOrderBookHandler Interface Reference
com.wombat.mamda.orderbook.MamdaOrderBookHandler Interface Reference
Process updates on the order book.
Public Member Functions
void onBookRecap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookComplexDelta delta, MamdaOrderBookRecap event, MamdaOrderBook book)
Method invoked when an updated full order book image is available.
void onBookDelta (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookSimpleDelta event, MamdaOrderBook book)
Method invoked when a regular update for an order book is available.
void onBookComplexDelta (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookComplexDelta event, MamdaOrderBook book)
Method invoked when an order book delta is reported.
void onBookClear (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookClear event, MamdaOrderBook book)
Method invoked when an order book is cleared.
void onBookGap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookGap event, MamdaOrderBook fullBook)
Method invoked when a gap in order book updates is discovered.
Detailed Description
Process updates on the order book.
Concrete instances of this interface are passed to the MamdaOrderBookListener in order for an application to receive callbacks on order book update events.
Member Function Documentation
onBookRecap()
void com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookRecap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookComplexDelta delta, MamdaOrderBookRecap event, MamdaOrderBook book)
Method invoked when an updated full order book image is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
delta The order book delta generated from the update.
event The MamdaOrderBookRecap.
book The book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
onBookDelta()
void com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookDelta (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookSimpleDelta event, MamdaOrderBook book)
Method invoked when a regular update for an order book is available.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event The order book delta generated from the update.
book The full order book after the update is applied.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
onBookComplexDelta()
void com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookComplexDelta (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookComplexDelta event, MamdaOrderBook book)
Method invoked when an order book delta is reported.
A delta consists of one or more price levels (add/update/delete), each of which contains zero or more entries (add/update/delete). Some feeds do not provide order book entry information.
Parameters
subscription The MamdaSubscription handle.
listener The order book listener that received the update.
msg The MamaMsg that triggered this invocation.
event Details of the the delta.
book The current full book (after applying the delta).
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
onBookClear()
void com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookClear (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookClear event, MamdaOrderBook book)
Method invoked when an order book is cleared.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event The clear event.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().
onBookGap()
void com.wombat.mamda.orderbook.MamdaOrderBookHandler.onBookGap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookGap event, MamdaOrderBook fullBook)
Method invoked when a gap in order book updates is discovered.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event Access to details on the order book gap event.
fullBook The full order book.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookListener.onMsg().