OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry Interface Reference
com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry Interface Reference
MamdaBookAtomicLevel is an interface that provides access to Price Level and Price Level Entry fields.
Inherits com.wombat.mamda.MamdaBasicRecap.
Inherited by com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Public Member Functions
double getPriceLevelPrice ()
MamaPrice getPriceLevelMamaPrice ()
double getPriceLevelSize ()
char getPriceLevelAction ()
char getPriceLevelSide ()
MamaDateTime getPriceLevelTime ()
double getPriceLevelNumEntries ()
long getPriceLevelActNumEntries ()
char getPriceLevelEntryAction ()
Order book entry action to apply to the full order book.
char getPriceLevelEntryReason ()
Reason for order book entry.
String getPriceLevelEntryId ()
Order book entry Id.
long getPriceLevelEntrySize ()
Return the order book entry size.
MamaDateTime getPriceLevelEntryTime ()
Return the time of order book entry update.
Iterator entryIterator ()
boolean isVisible ()
Public Member Functions inherited from com.wombat.mamda.MamdaBasicRecap
String getSymbol ()
Get the string symbol for the instrument.
short getSymbolFieldState ()
String getPartId ()
Get the participant identifier.
short getPartIdFieldState ()
MamaDateTime getSrcTime ()
Source time.
short getSrcTimeFieldState ()
MamaDateTime getActivityTime ()
Activity time.
short getActivityTimeFieldState ()
MamaDateTime getLineTime ()
Get the line time of the update.
short getLineTimeFieldState ()
MamaDateTime getSendTime ()
Get the send time of the update.
short getSendTimeFieldState ()
Detailed Description
MamdaBookAtomicLevel is an interface that provides access to Price Level and Price Level Entry fields.
Member Function Documentation
getPriceLevelPrice()
double com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelPrice ()
See also
MamdaBookAtomicLevel::getPriceLevelPrice()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPriceLevelMamaPrice()
MamaPrice com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelMamaPrice ()
See also
MamdaBookAtomicLevel::getPriceLevelMamaPrice()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelSize()
double com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelSize ()
See also
MamdaBookAtomicLevel::getPriceLevelSize()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelAction()
char com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelAction ()
See also
MamdaBookAtomicLevel::getPriceLevelAction()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelSide()
char com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelSide ()
See also
MamdaBookAtomicLevel::getPriceLevelSide()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelTime ()
See also
MamdaBookAtomicLevel::getPriceLevelTime()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
getPriceLevelNumEntries()
double com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelNumEntries ()
See also
MamdaBookAtomicLevel::getPriceLevelNumEntries()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelActNumEntries()
long com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelActNumEntries ()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
getPriceLevelEntryAction()
char com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryAction ()
Order book entry action to apply to the full order book.
A : Add entry to the price level. U : Update existing entry in the price level. D : Delete existing entry from the price level.
Returns
The orderbook entry action.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPriceLevelEntryReason()
char com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryReason ()
Reason for order book entry.
Returns
The orderbook entry reason.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPriceLevelEntryId()
String com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryId ()
Order book entry Id.
(order ID, participant ID, etc.)
Returns
The entry id
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.checkNotExist(), com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.updateEntry().
getPriceLevelEntrySize()
long com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntrySize ()
Return the order book entry size.
Returns
Order book entry size
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails().
getPriceLevelEntryTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.getPriceLevelEntryTime ()
Return the time of order book entry update.
Returns
Time of order book entry update.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy(), com.wombat.mamda.orderbook.MamdaOrderBookEntry.setDetails(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails().
entryIterator()
Iterator com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.entryIterator ()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
isVisible()
boolean com.wombat.mamda.orderbook.MamdaBookAtomicLevelEntry.isVisible ()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntry(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.removeEntryById().