OpenMAMDA Java API: com.wombat.mamda.MamdaMsgListener Interface Reference
com.wombat.mamda.MamdaMsgListener Interface Reference
MamdaMsgListener defines an interface for handling normal messages for a MamdaSubscription.
Inherited by com.wombat.mamda.MamdaAuctionListener, com.wombat.mamda.MamdaFundamentalListener, com.wombat.mamda.MamdaMultiParticipantManager, com.wombat.mamda.MamdaMultiSecurityManager, com.wombat.mamda.MamdaOrderImbalanceListener, com.wombat.mamda.MamdaQuoteListener, com.wombat.mamda.MamdaSecurityStatusListener, com.wombat.mamda.MamdaTradeListener, com.wombat.mamda.options.MamdaOptionChainListener, com.wombat.mamda.orderbook.MamdaBookAtomicListener, and com.wombat.mamda.orderbook.MamdaOrderBookListener.
Public Member Functions
void onMsg (final MamdaSubscription subscription, final MamaMsg msg, final short msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Detailed Description
MamdaMsgListener defines an interface for handling normal messages for a MamdaSubscription.
Member Function Documentation
onMsg()
void com.wombat.mamda.MamdaMsgListener.onMsg (final MamdaSubscription subscription, final MamaMsg msg, final short msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Parameters
subscription The MamdaSubscription to which this listener was registered.
msg The MamaMsg received by the underlying MAMA API and which resulted in this callback being invoked.
msgType The message type. e.g. INITIAL, RECAP, UPDATE etc.
Implemented in com.wombat.mamda.MamdaTradeListener, com.wombat.mamda.MamdaQuoteListener, com.wombat.mamda.MamdaOrderImbalanceListener, com.wombat.mamda.orderbook.MamdaOrderBookListener, com.wombat.mamda.MamdaSecurityStatusListener, com.wombat.mamda.MamdaFundamentalListener, com.wombat.mamda.MamdaAuctionListener, com.wombat.mamda.orderbook.MamdaBookAtomicListener, com.wombat.mamda.MamdaMultiParticipantManager, com.wombat.mamda.options.MamdaOptionChainListener, and com.wombat.mamda.MamdaMultiSecurityManager.
Referenced by com.wombat.mamda.MamdaSubscription.getMamaSubscription(), com.wombat.mamda.MamdaMultiSecurityManager.onMsg(), and com.wombat.mamda.MamdaMultiParticipantManager.onMsg().