OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaBookAtomicLevel Interface Reference
com.wombat.mamda.orderbook.MamdaBookAtomicLevel Interface Reference
MamdaBookAtomicLevel is an interface that provides access to trade related fields.
Inherits com.wombat.mamda.MamdaBasicRecap.
Inherited by com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Public Member Functions
long getPriceLevelNumLevels ()
Return the number of price levels in the order book update.
long getPriceLevelNum ()
Return at which position this level is within an update containing a number of levels.
double getPriceLevelPrice ()
Return the price for this price level.
MamaPrice getPriceLevelMamaPrice ()
Return the MamaPrice for this price level.
double getPriceLevelSize ()
Return the number of order entries comprising this price level.
long getPriceLevelSizeChange ()
Aggregate size at current price level.
char getPriceLevelAction ()
The action to apply to the orderbook for this price level.
char getPriceLevelSide ()
Side of book at current price level.
MamaDateTime getPriceLevelTime ()
Time of order book price level.
double getPriceLevelNumEntries ()
Number of order book entries at current price level.
Iterator entryIterator ()
Public Member Functions inherited from com.wombat.mamda.MamdaBasicRecap
String getSymbol ()
Get the string symbol for the instrument.
short getSymbolFieldState ()
String getPartId ()
Get the participant identifier.
short getPartIdFieldState ()
MamaDateTime getSrcTime ()
Source time.
short getSrcTimeFieldState ()
MamaDateTime getActivityTime ()
Activity time.
short getActivityTimeFieldState ()
MamaDateTime getLineTime ()
Get the line time of the update.
short getLineTimeFieldState ()
MamaDateTime getSendTime ()
Get the send time of the update.
short getSendTimeFieldState ()
Detailed Description
MamdaBookAtomicLevel is an interface that provides access to trade related fields.
Member Function Documentation
getPriceLevelNumLevels()
long com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelNumLevels ()
Return the number of price levels in the order book update.
Returns
The number of price levels.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
getPriceLevelNum()
long com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelNum ()
Return at which position this level is within an update containing a number of levels.
(i.e. level m of n levels in the update)
Returns
The position of this level in the update received.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
getPriceLevelPrice()
double com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelPrice ()
Return the price for this price level.
Returns
The price level price.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().
getPriceLevelMamaPrice()
MamaPrice com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelMamaPrice ()
Return the MamaPrice for this price level.
Returns
The price level price.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelSize()
double com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSize ()
Return the number of order entries comprising this price level.
Not supported for V5 entry book updates.
Returns
The number of entries in this price level.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails().
getPriceLevelSizeChange()
long com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSizeChange ()
Aggregate size at current price level.
Not supported for V5 entry book updates.
Returns
The aggregate size at the current price level.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails().
getPriceLevelAction()
char com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelAction ()
The action to apply to the orderbook for this price level.
Can have a value of:
A : Add a new price level
U : Update an existing price level
D : Delete an existing price level
C : Closing information for price level (often treat the same as Update).
Not supported for V5 entry book updates.
Returns
The price level action.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelSide()
char com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelSide ()
Side of book at current price level.
B : Bid side. Same as 'buy' side.
A : Ask side. Same as 'sell' side.
Returns
The price level side.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy().
getPriceLevelTime()
MamaDateTime com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelTime ()
Time of order book price level.
Returns
The time of the orderbook price level.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails().
getPriceLevelNumEntries()
double com.wombat.mamda.orderbook.MamdaBookAtomicLevel.getPriceLevelNumEntries ()
Number of order book entries at current price level.
Not supported for V5 entry book updates.
Returns
The number of entries at the current price level.
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached(), com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.copy(), and com.wombat.mamda.orderbook.MamdaOrderBookPriceLevel.setDetails().
entryIterator()
Iterator com.wombat.mamda.orderbook.MamdaBookAtomicLevel.entryIterator ()
Implemented in com.wombat.mamda.orderbook.MamdaBookAtomicListener.
Referenced by com.wombat.mamda.orderbook.MamdaOrderBook.cleanupDetached().