OpenMAMDA Java API: com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler Interface Reference
com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler Interface Reference
MamdaBookAtomicBookHandler is an interface for applications that need to know when a MamdaBookAtomicListener finishes processing a single book update.
Public Member Functions
void onBookAtomicBeginBook (MamdaSubscription subscription, MamdaBookAtomicListener listener, boolean isRecap)
Method invoked before we start processing the first level in a message.
void onBookAtomicEndBook (MamdaSubscription subscription, MamdaBookAtomicListener listener)
Method invoked when we stop processing the last level in a message.
void onBookAtomicClear (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg)
Method invoked when an order book is cleared.
void onBookAtomicGap (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg, MamdaBookAtomicGap event)
Method invoked when a gap in orderBook reports is discovered.
Detailed Description
MamdaBookAtomicBookHandler is an interface for applications that need to know when a MamdaBookAtomicListener finishes processing a single book update.
This may be useful for applications that wish to destroy the subscription from a callback as the subscription can only be destroyed after the message processing is complete. Furthermore, it allows applications to determine when to clear the book when a recap arrives.
Member Function Documentation
onBookAtomicBeginBook()
void com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicBeginBook (MamdaSubscription subscription, MamdaBookAtomicListener listener, boolean isRecap)
Method invoked before we start processing the first level in a message.
The book should be cleared when isRecap == true.
Parameters
subscription The MamdaSubscription handle.
listener The listener handling recaps/updates.
isRecap Whether the first update was a recap.
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
onBookAtomicEndBook()
void com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicEndBook (MamdaSubscription subscription, MamdaBookAtomicListener listener)
Method invoked when we stop processing the last level in a message.
We invoke this method after the last entry for the level gets processed. The subscription may be destroyed from this callback.
Parameters
subscription The MamdaSubscription handle.
listener The listener handling recaps/updates.
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
onBookAtomicClear()
void com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicClear (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg)
Method invoked when an order book is cleared.
Parameters
subscription The MamdaSubscription handle.
listener The listener handling recaps/updates.
msg The MamaMsg that triggered this invocation.
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().
onBookAtomicGap()
void com.wombat.mamda.orderbook.MamdaBookAtomicBookHandler.onBookAtomicGap (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg, MamdaBookAtomicGap event)
Method invoked when a gap in orderBook reports is discovered.
Parameters
subscription The MamdaSubscription handle.
listener The listener handling recaps/updates.
msg The MamaMsg that triggered this invocation.
event The gap value object.
Referenced by com.wombat.mamda.orderbook.MamdaBookAtomicListener.onMsg().