OpenMAMDA Java API: com.wombat.mamda.MamdaTradeHandler Interface Reference
com.wombat.mamda.MamdaTradeHandler Interface Reference
MamdaTradeHandler is an interface for applications that want to have an easy way to handle trade updates.
Public Member Functions
void onTradeRecap (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeRecap recap)
Method invoked when the current last-trade information for the security is available.
void onTradeReport (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeReport event, MamdaTradeRecap recap)
Method invoked when a trade is reported.
void onTradeGap (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeGap event, MamdaTradeRecap recap)
Method invoked when a gap in trade reports is discovered.
void onTradeCancelOrError (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeCancelOrError event, MamdaTradeRecap recap)
Method invoked when a trade cancel or error is reported.
void onTradeCorrection (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeCorrection event, MamdaTradeRecap recap)
Method invoked when a trade correction is reported.
void onTradeClosing (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeClosing event, MamdaTradeRecap recap)
Method invoked for a closing report.
Detailed Description
MamdaTradeHandler is an interface for applications that want to have an easy way to handle trade updates.
The interface defines callback methods for different types of trade-related events: trades, errors/cancels, corrections, recaps and closing reports.
Member Function Documentation
onTradeRecap()
void com.wombat.mamda.MamdaTradeHandler.onTradeRecap (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeRecap recap)
Method invoked when the current last-trade information for the security is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
recap Access to the trade fields in the recap update.
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().
onTradeReport()
void com.wombat.mamda.MamdaTradeHandler.onTradeReport (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeReport event, MamdaTradeRecap recap)
Method invoked when a trade is reported.
Parameters
subscription The subscription which received the update.
listener The listener which invoked the callback.
msg The MamaMsg that triggered this invocation.
event Access to the trade data from the update.
recap Access to complete trade data.
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().
onTradeGap()
void com.wombat.mamda.MamdaTradeHandler.onTradeGap (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeGap event, MamdaTradeRecap recap)
Method invoked when a gap in trade reports is discovered.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event Access to details from the trade gap event.
recap Access to complete trade data.
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().
onTradeCancelOrError()
void com.wombat.mamda.MamdaTradeHandler.onTradeCancelOrError (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeCancelOrError event, MamdaTradeRecap recap)
Method invoked when a trade cancel or error is reported.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event Access to the details from the cancel/error event.
recap Access to the complete trade data.
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().
onTradeCorrection()
void com.wombat.mamda.MamdaTradeHandler.onTradeCorrection (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeCorrection event, MamdaTradeRecap recap)
Method invoked when a trade correction is reported.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event Access to the details from the trade correction event.
recap Access to the complete trade data.
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().
onTradeClosing()
void com.wombat.mamda.MamdaTradeHandler.onTradeClosing (MamdaSubscription subscription, MamdaTradeListener listener, MamaMsg msg, MamdaTradeClosing event, MamdaTradeRecap recap)
Method invoked for a closing report.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
event Access to the details from the trade closing event.
recap Access to the complete trade data.
Referenced by com.wombat.mamda.MamdaTradeListener.onMsg().