OpenMAMDA Java API: com.wombat.mamda.MamdaQuoteHandler Interface Reference
com.wombat.mamda.MamdaQuoteHandler Interface Reference
MamdaQuoteHandler is an interface for applications that want to have an easy way to handle quote updates.
Public Member Functions
void onQuoteRecap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteRecap recap)
Method invoked when the current last-quote information for the security is available.
void onQuoteUpdate (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteUpdate event, MamdaQuoteRecap recap)
Method invoked when a quote update arrives.
void onQuoteGap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteGap event, MamdaQuoteRecap recap)
Method invoked when a gap in quote updates is discovered.
void onQuoteClosing (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteClosing event, MamdaQuoteRecap recap)
Method invoked for a quote closing summary.
Detailed Description
MamdaQuoteHandler is an interface for applications that want to have an easy way to handle quote updates.
The interface defines callback methods for different types of quote-related events: quotes and closing-quote updates.
Member Function Documentation
onQuoteRecap()
void com.wombat.mamda.MamdaQuoteHandler.onQuoteRecap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteRecap recap)
Method invoked when the current last-quote information for the security is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The MamdaSubscription handle.
listener The MamdaSubscription handle.
msg The MamaMsg that triggered this invocation.
recap Access to the current value of all fields.
Referenced by com.wombat.mamda.MamdaQuoteListener.onMsg().
onQuoteUpdate()
void com.wombat.mamda.MamdaQuoteHandler.onQuoteUpdate (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteUpdate event, MamdaQuoteRecap recap)
Method invoked when a quote update arrives.
Parameters
subscription The MamdaSubscription handle.
listener The MamdaSubscription handle.
msg The MamaMsg that triggered this invocation.
event The MamdaQuoteUpdate event.
recap Access to the current value of all fields.
Referenced by com.wombat.mamda.MamdaQuoteListener.onMsg().
onQuoteGap()
void com.wombat.mamda.MamdaQuoteHandler.onQuoteGap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteGap event, MamdaQuoteRecap recap)
Method invoked when a gap in quote updates is discovered.
Parameters
subscription The MamdaSubscription handle.
listener The MamdaSubscription handle.
msg The MamaMsg that triggered this invocation.
event The MamdaQuoteGap event.
recap Access to the current value of all fields.
Referenced by com.wombat.mamda.MamdaQuoteListener.onMsg().
onQuoteClosing()
void com.wombat.mamda.MamdaQuoteHandler.onQuoteClosing (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteClosing event, MamdaQuoteRecap recap)
Method invoked for a quote closing summary.
Parameters
subscription The MamdaSubscription handle.
listener The MamdaSubscription handle.
msg The MamaMsg that triggered this invocation.
event The MamdaQuoteClosing event.
recap Access to the current value of all fields.