OpenMAMA C# API: Wombat.MamaInbox Class Reference
Wombat.MamaInbox Class Reference
A class for processing point-to-point messaging
Inherits Wombat.MamaWrapper.
Public Member Functions
MamaInbox ()
Construct an inbox.
void create (MamaTransport transport, MamaQueue queue, MamaInboxCallback callback, object closure)
Creates an inbox and stores at the address specified by the calling client.
void create (MamaTransport transport, MamaQueue queue, MamaInboxCallback callback)
Creates an inbox and stores at the address specified by the calling client.
void create (MamaTransport transport, MamaInboxCallback callback, object closure)
Creates an inbox and stores at the address specified by the calling client.
void destroy ()
A synonym to the MamaWrapper.Dispose method.
object getClosure ()
Returns the user supplied data passed to create.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object.
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
A class for processing point-to-point messaging
Constructor & Destructor Documentation
MamaInbox()
Wombat.MamaInbox.MamaInbox ()
Construct an inbox.
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaInbox.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object.
See also
MamaWrapper.DestroyNativePeer
Implements Wombat.MamaWrapper.
create() [1/3]
void Wombat.MamaInbox.create (MamaTransport transport, MamaQueue queue, MamaInboxCallback callback, object closure)
Creates an inbox and stores at the address specified by the calling client.
Parameters
transport The mamaTransport being used.
queue Optional mamaQueue. Will use default queue if null.
callback A callback interface invoked in response to a p2p message being received or when an error is encountered during p2p messaging.
closure User supplied data
Referenced by Wombat.MamaInbox.create().
create() [2/3]
void Wombat.MamaInbox.create (MamaTransport transport, MamaQueue queue, MamaInboxCallback callback)
Creates an inbox and stores at the address specified by the calling client.
Parameters
transport The mamaTransport being used.
queue Optional mamaQueue. Will use default queue if null.
callback A callback interface invoked in response to a p2p message being received or when an error is encountered during p2p messaging.
References Wombat.MamaInbox.create().
create() [3/3]
void Wombat.MamaInbox.create (MamaTransport transport, MamaInboxCallback callback, object closure)
Creates an inbox and stores at the address specified by the calling client.
Uses a default queue. This functionality is no longer supported.
Parameters
transport The mamaTransport being used.
callback A callback interface invoked in response to a p2p message being received or hen an error is encountered during p2p messaging.
closure User supplied data.
destroy()
void Wombat.MamaInbox.destroy ()
A synonym to the MamaWrapper.Dispose method.
References Wombat.MamaWrapper.Dispose().
getClosure()
object Wombat.MamaInbox.getClosure ()
Returns the user supplied data passed to create.
Returns
The user supplied data passed to create.