OpenMAMA C# API: Wombat.MamaMsg Class Reference
Wombat.MamaMsg Class Reference
Class which encapsulates the messages used in the MAMA infrastructure
Inherits Wombat.MamaWrapper.
Public Member Functions
MamaMsg ()
Create a msg using the default payload.
MamaMsg (mamaPayloadType payloadId)
NOTE: This function has been deprecated in line with the deprecation of the mamaPayloadType enum.
MamaMsg (char payloadId)
Create a msg using the payload specified.
MamaMsg (MamaPayloadBridge payloadBridge)
Create a msg using the payload bridge specified.
MamaMsg (MamaMsg mamaMsgSrc)
Create a deep copy of a message.
void getByteBuffer (ref byte[] byteBuffer, ref int size)
void createFromBuffer (byte[] byteBuffer, int size)
void createForBridgeFromBuffer (byte[] byteBuffer, int size, MamaBridge bridgeImpl)
MamaMsg detach ()
mamaMsgType getType ()
Extract the type
mamaMsgStatus getStatus ()
Return the status
mamaPayloadType getPayloadType ()
void iterateFields (MamaMsgFieldIterator iterator, MamaDictionary dictionary, object closure)
Invoke the specified callback for each field in the message.
void clear ()
Clear a msg.
void destroy ()
Destroy a message and free any resources associated with it.
int getByteSize ()
Get the size of the underlying message in bytes.
void addBool (string name, ushort fid, bool val)
Add a new bool field.
void addChar (string name, ushort fid, char val)
Add a new char field.
void addI8 (string name, ushort fid, sbyte val)
Add a new 8 bit signed int field.
void addU8 (string name, ushort fid, byte val)
Add a new 8 bit unsigned int field.
void addI16 (string name, ushort fid, short val)
Add a new 16 bit signed int field.
void addU16 (string name, ushort fid, ushort val)
Add a new 16 bit unsigned int field.
void addI32 (string name, ushort fid, int val)
Add a new 32 bit unsigned int field.
void addU32 (string name, ushort fid, uint val)
Add a new 32 bit signed int field.
void addI64 (string name, ushort fid, long val)
Add a new I64 field.
void addU64 (string name, ushort fid, ulong val)
Add a new U64 field.
void addF32 (string name, ushort fid, float val)
Add a new float (f32) field.
void addF64 (string name, ushort fid, double val)
Add a new f64 field.
void addString (string name, ushort fid, string val)
Add a string field.
void addOpaque (string name, ushort fid, byte[] val)
Add an opaque field.
void addDateTime (string name, ushort fid, DateTime val)
Add a MAMA date/time field.
void addPrice (string name, ushort fid, MamaPrice val)
Add a MAMA price field.
void addMsg (string name, ushort fid, MamaMsg val)
Add a MamaMsg to the msg
void addVectorBool (string name, ushort fid, bool[] val)
Add an array of booleans to the message.
void addVectorChar (string name, ushort fid, char[] val)
Add an array of characters to the message.
void addVectorI8 (string name, ushort fid, sbyte[]val)
Add an array of signed 8 bit integers to the message.
void addVectorU8 (string name, ushort fid, byte[] val)
Add an array of unsigned 8 bit integers to the message.
void addVectorI16 (string name, ushort fid, short[] val)
Add an array of signed 16 bit integers to the message.
void addVectorU16 (string name, ushort fid, ushort[] val)
Add an array of unsigned 16 bit integers to the message.
void addVectorI32 (string name, ushort fid, int[] val)
Add an array of signed 32 bit integers to the message.
void addVectorU32 (string name, ushort fid, uint[] val)
Add an array of unsigned 32 bit integers to the message.
void addVectorI64 (string name, ushort fid, long[] val)
Add an array of signed 64 bit integers to the message.
void addVectorU64 (string name, ushort fid, ulong[] val)
Add an array of unsigned 64 bit integers to the message.
void addVectorF32 (string name, ushort fid, float[] val)
Add an array of 32 bit floating point numbers to the message.
void addVectorF64 (string name, ushort fid, double[] val)
Add an array of 64 bit floating point numbers to the message.
void addVectorDateTime (string name, ushort fid, DateTime[] val)
Add an array of timestamps to the message.
void updateBool (string name, ushort fid, bool val)
Update the value of an existing bool field.
void updateChar (string name, ushort fid, char val)
Update the value of an existing char field.
void updateI8 (string name, ushort fid, sbyte val)
Update the value of an existing I8 field.
void updateU8 (string name, ushort fid, byte val)
Update the value of an existing U8 field.
void updateI16 (string name, ushort fid, short val)
Update the value of an existing I16 field.
void updateU16 (string name, ushort fid, ushort val)
Update the value of an existing U16 field.
void updateI32 (string name, ushort fid, int val)
Update the value of an existing I32 field.
void updateU32 (string name, ushort fid, uint val)
Update the value of an existing U32 field.
void updateI64 (string name, ushort fid, long val)
Update the value of an existing I64 field.
void updateU64 (string name, ushort fid, ulong val)
Update the value of an existing U64 field.
void updateF32 (string name, ushort fid, float val)
Update the value of an existing float field.
void updateF64 (string name, ushort fid, double val)
Update the value of an existing f64 field.
void updateString (string name, ushort fid, string val)
Update the value of an existing string field.
void updateOpaque (string name, ushort fid, byte[] val)
Update an opaque field.
void updateDateTime (string name, ushort fid, DateTime val)
Update a MAMA date/time field.
void updatePrice (string name, ushort fid, MamaPrice val)
Update a MAMA price field.
void updateVectorBool (string name, ushort fid, bool[] val)
Update an array of booleans.
void updateVectorChar (string name, ushort fid, char[] val)
Update an array of characters.
void updateVectorI8 (string name, ushort fid, sbyte[] val)
Update an array of signed 8 bit integers.
void updateVectorU8 (string name, ushort fid, byte[] val)
Update an array of unsigned 8 bit integers.
void updateVectorI16 (string name, ushort fid, short[] val)
Update an array of signed 16 bit integers.
void updateVectorU16 (string name, ushort fid, ushort[] val)
Update an array of unsigned 16 bit integers.
void updateVectorI32 (string name, ushort fid, int[] val)
Update an array of signed 32 bit integers.
void updateVectorU32 (string name, ushort fid, uint[] val)
Update an array of unsigned 32 bit integers.
void updateVectorI64 (string name, ushort fid, long[] val)
Update an array of signed 64 bit integers.
void updateVectorU64 (string name, ushort fid, ulong[] val)
Update an array of unsigned 64 bit integers.
void updateVectorF32 (string name, ushort fid, float[] val)
Update an array of 32 bit floating point numbers.
void updateVectorF64 (string name, ushort fid, double[] val)
Update an array of 64 bit floating point numbers.
void updateVectorDateTime (string name, ushort fid, DateTime[] val)
Update an array of timestamps.
bool getBool (string name, ushort fid)
Get a bool field.
bool getBool (MamaFieldDescriptor descriptor)
Get a bool field.
bool getBool (string name, ushort fid, bool valueIfMissing)
Get a bool field.
bool getBool (MamaFieldDescriptor descriptor, bool valueIfMissing)
Get a bool field.
char getChar (string name, ushort fid)
Get a char field.
char getChar (MamaFieldDescriptor descriptor)
Get a char field.
char getChar (string name, ushort fid, char valueIfMissing)
Get a char field.
char getChar (MamaFieldDescriptor descriptor, char valueIfMissing)
Get a char field.
sbyte getI8 (string name, ushort fid)
Get a I8, signed 8 bit integer, field.
sbyte getI8 (MamaFieldDescriptor descriptor)
Get a I8, signed 8 bit integer, field.
sbyte getI8 (string name, ushort fid, sbyte valueIfMissing)
Get a I8, signed 8 bit integer, field.
sbyte getI8 (MamaFieldDescriptor descriptor, sbyte valueIfMissing)
Get a I8, signed 8 bit integer, field.
byte getU8 (string name, ushort fid)
Get a U8, unsigned 8 bit integer, field.
byte getU8 (MamaFieldDescriptor descriptor)
Get a U8, unsigned 8 bit integer, field.
byte getU8 (string name, ushort fid, byte valueIfMissing)
Get a U8, unsigned 8 bit integer, field.
byte getU8 (MamaFieldDescriptor descriptor, byte valueIfMissing)
Get a U8, unsigned 8 bit integer, field.
short getI16 (string name, ushort fid)
Get a I16, signed 16 bit integer, field.
short getI16 (MamaFieldDescriptor descriptor)
Get a I16, signed 16 bit integer, field.
short getI16 (string name, ushort fid, short valueIfMissing)
Get a I16, signed 16 bit integer, field.
short getI16 (MamaFieldDescriptor descriptor, short valueIfMissing)
Get a I16, signed 16 bit integer, field.
ushort getU16 (string name, ushort fid)
Get a U16, unsigned 16 bit integer, field.
ushort getU16 (MamaFieldDescriptor descriptor)
Get a U16, unsigned 16 bit integer, field.
ushort getU16 (string name, ushort fid, ushort valueIfMissing)
Get a U16, unsigned 16 bit integer, field.
ushort getU16 (MamaFieldDescriptor descriptor, ushort valueIfMissing)
Get a U16, unsigned 16 bit integer, field.
int getI32 (string name, ushort fid)
Get a I32, signed 32 bit integer, field.
int getI32 (MamaFieldDescriptor descriptor)
Get a I32, signed 32 bit integer, field.
int getI32 (string name, ushort fid, int valueIfMissing)
Get a I32, signed 32 bit integer, field.
int getI32 (MamaFieldDescriptor descriptor, int valueIfMissing)
Get a I32, signed 32 bit integer, field.
uint getU32 (string name, ushort fid)
Get a U32, unsigned 32 bit integer, field.
uint getU32 (MamaFieldDescriptor descriptor)
Get a U32, unsigned 32 bit integer, field.
uint getU32 (string name, ushort fid, uint valueIfMissing)
Get a U32, unsigned 32 bit integer, field.
uint getU32 (MamaFieldDescriptor descriptor, uint valueIfMissing)
Get a U32, unsigned 32 bit integer, field.
long getI64 (string name, ushort fid)
Get a I64, signed 64 bit integer, field.
long getI64 (MamaFieldDescriptor descriptor)
Get a I64, signed 64 bit integer, field.
long getI64 (string name, ushort fid, long valueIfMissing)
Get a I64, signed 64 bit integer, field.
long getI64 (MamaFieldDescriptor descriptor, long valueIfMissing)
Get a I64, signed 64 bit integer, field.
ulong getU64 (string name, ushort fid)
Get a U64, unsigned 64 bit integer, field.
ulong getU64 (MamaFieldDescriptor descriptor)
Get a U64, unsigned 64 bit integer, field.
ulong getU64 (string name, ushort fid, ulong valueIfMissing)
Get a U64, unsigned 64 bit integer, field.
ulong getU64 (MamaFieldDescriptor descriptor, ulong valueIfMissing)
Get a U64, unsigned 64 bit integer, field.
float getF32 (string name, ushort fid)
Get a float (f32) field.
float getF32 (MamaFieldDescriptor descriptor)
Get a float (f32) field.
float getF32 (string name, ushort fid, float valueIfMissing)
Get a float (f32) field.
float getF32 (MamaFieldDescriptor descriptor, float valueIfMissing)
Get a float (f32) field.
double getF64 (string name, ushort fid)
Get a F64 field.
double getF64 (MamaFieldDescriptor descriptor)
Get a F64 field.
double getF64 (string name, ushort fid, double valueIfMissing)
Get a F64 field.
double getF64 (MamaFieldDescriptor descriptor, double valueIfMissing)
Get a F64 field.
string getString (string name, ushort fid)
Get a string field.
bool tryStringAnsi (string name, ushort fid, ref IntPtr result)
bool tryStringAnsi (MamaFieldDescriptor descriptor, ref IntPtr result)
string getString (MamaFieldDescriptor descriptor)
Get a string field.
string getString (string name, ushort fid, string valueIfMissing)
Get a string field.
string getString (MamaFieldDescriptor descriptor, string valueIfMissing)
Get a string field.
byte [] getOpaque (string name, ushort fid)
Get an opaque field.
byte [] getOpaque (MamaFieldDescriptor descriptor)
Get a opaque field.
byte [] getOpaque (string name, ushort fid, byte[] valueIfMissing)
Get a opaque field.
byte [] getOpaque (MamaFieldDescriptor descriptor, byte[] valueIfMissing)
Get a opaque field.
DateTime getDateTime (string name, ushort fid)
Get a MAMA date/time field.
DateTime getDateTime (MamaFieldDescriptor descriptor)
Get a MAMA date/time field.
DateTime getDateTime (string name, ushort fid, DateTime valueIfMissing)
Get a MAMA date/time field.
DateTime getDateTime (MamaFieldDescriptor descriptor, DateTime valueIfMissing)
Get a MAMA date/time field.
MamaPrice getPrice (string name, ushort fid)
Get a MAMA price field.
MamaPrice getPrice (MamaFieldDescriptor descriptor)
Get a MAMA price field.
MamaPrice getPrice (string name, ushort fid, MamaPrice valueIfMissing)
Get a MAMA price field.
MamaPrice getPrice (MamaFieldDescriptor descriptor, MamaPrice valueIfMissing)
Get a MAMA price field.
MamaMsg getMsg (string name, ushort fid)
Get a submessage.
MamaMsg getMsg (MamaFieldDescriptor descriptor)
Get a submessage.
MamaMsg getMsg (string name, ushort fid, MamaMsg valueIfMissing)
Get a submessage.
MamaMsg getMsg (MamaFieldDescriptor descriptor, MamaMsg valueIfMissing)
Get a submessage.
MamaMsgField getField (string name, ushort fid)
Get a MAMA msg field.
MamaMsgField getField (MamaFieldDescriptor descriptor)
Get a MAMA msg field.
MamaMsgField getField (string name, ushort fid, MamaMsgField valueIfMissing)
Get a MAMA msg field.
MamaMsgField getField (MamaFieldDescriptor descriptor, MamaMsgField valueIfMissing)
Get a MAMA msg field.
bool [] getVectorBool (string name, ushort fid)
Get a vector of booleans.
bool [] getVectorBool (MamaFieldDescriptor descriptor)
Get a vector of booleans.
bool [] getVectorBool (string name, ushort fid, bool[] valueIfMissing)
Get a vector of booleans.
bool [] getVectorBool (MamaFieldDescriptor descriptor, bool[] valueIfMissing)
Get a vector of booleans.
char [] getVectorChar (string name, ushort fid)
Get a vector of chars.
char [] getVectorChar (MamaFieldDescriptor descriptor)
Get a vector of chars.
char [] getVectorChar (string name, ushort fid, char[] valueIfMissing)
Get a vector of chars.
char [] getVectorChar (MamaFieldDescriptor descriptor, char[] valueIfMissing)
Get a vector of chars.
sbyte [] getVectorI8 (string name, ushort fid)
Get a vector of signed 8 bit integers.
sbyte [] getVectorI8 (MamaFieldDescriptor descriptor)
Get a vector of signed 8 bit integers.
sbyte [] getVectorI8 (string name, ushort fid, sbyte[] valueIfMissing)
Get a vector of signed 8 bit integers.
sbyte [] getVectorI8 (MamaFieldDescriptor descriptor, sbyte[] valueIfMissing)
Get a vector of signed 8 bit integers.
byte [] getVectorU8 (string name, ushort fid)
Get a vector of unsigned 8 bit integers.
byte [] getVectorU8 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 8 bit integers.
byte [] getVectorU8 (string name, ushort fid, byte[] valueIfMissing)
Get a vector of unsigned 8 bit integers.
byte [] getVectorU8 (MamaFieldDescriptor descriptor, byte[] valueIfMissing)
Get a vector of unsigned 8 bit integers.
short [] getVectorI16 (string name, ushort fid)
Get a vector of signed 16 bit integers.
short [] getVectorI16 (MamaFieldDescriptor descriptor)
Get a vector of signed 16 bit integers.
short [] getVectorI16 (string name, ushort fid, short[] valueIfMissing)
Get a vector of signed 16 bit integers.
short [] getVectorI16 (MamaFieldDescriptor descriptor, short[] valueIfMissing)
Get a vector of signed 16 bit integers.
ushort [] getVectorU16 (string name, ushort fid)
Get a vector of unsigned 16 bit integers.
ushort [] getVectorU16 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 16 bit integers.
ushort [] getVectorU16 (string name, ushort fid, ushort[] valueIfMissing)
Get a vector of unsigned 16 bit integers.
ushort [] getVectorU16 (MamaFieldDescriptor descriptor, ushort[] valueIfMissing)
Get a vector of unsigned 16 bit integers.
int [] getVectorI32 (string name, ushort fid)
Get a vector of signed 32 bit integers.
int [] getVectorI32 (MamaFieldDescriptor descriptor)
Get a vector of signed 32 bit integers.
int [] getVectorI32 (string name, ushort fid, int[] valueIfMissing)
Get a vector of signed 32 bit integers.
int [] getVectorI32 (MamaFieldDescriptor descriptor, int[] valueIfMissing)
Get a vector of signed 32 bit integers.
uint [] getVectorU32 (string name, ushort fid)
Get a vector of unsigned 32 bit integers.
uint [] getVectorU32 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 32 bit integers.
uint [] getVectorU32 (string name, ushort fid, uint[] valueIfMissing)
Get a vector of unsigned 32 bit integers.
uint [] getVectorU32 (MamaFieldDescriptor descriptor, uint[] valueIfMissing)
Get a vector of unsigned 32 bit integers.
long [] getVectorI64 (string name, ushort fid)
Get a vector of signed 64 bit integers.
long [] getVectorI64 (MamaFieldDescriptor descriptor)
Get a vector of signed 64 bit integers.
long [] getVectorI64 (string name, ushort fid, long[] valueIfMissing)
Get a vector of signed 64 bit integers.
long [] getVectorI64 (MamaFieldDescriptor descriptor, long[] valueIfMissing)
Get a vector of signed 64 bit integers.
ulong [] getVectorU64 (string name, ushort fid)
Get a vector of unsigned 64 bit integers.
ulong [] getVectorU64 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 64 bit integers.
ulong [] getVectorU64 (string name, ushort fid, ulong[] valueIfMissing)
Get a vector of unsigned 64 bit integers.
ulong [] getVectorU64 (MamaFieldDescriptor descriptor, ulong[] valueIfMissing)
Get a vector of unsigned 64 bit integers.
float [] getVectorF32 (string name, ushort fid)
Get a vector of 32 bit floating point numbers.
float [] getVectorF32 (MamaFieldDescriptor descriptor)
Get a vector of 32 bit floating point numbers.
float [] getVectorF32 (string name, ushort fid, float[] valueIfMissing)
Get a vector of 32 bit floating point numbers.
float [] getVectorF32 (MamaFieldDescriptor descriptor, float[] valueIfMissing)
Get a vector of 32 bit floating point numbers.
double [] getVectorF64 (string name, ushort fid)
Get a vector of 64 bit floating point numbers.
double [] getVectorF64 (MamaFieldDescriptor descriptor)
Get a vector of 64 bit floating point numbers.
double [] getVectorF64 (string name, ushort fid, double[] valueIfMissing)
Get a vector of 64 bit floating point numbers.
double [] getVectorF64 (MamaFieldDescriptor descriptor, double[] valueIfMissing)
Get a vector of 64 bit floating point numbers.
string [] getVectorString (string name, ushort fid)
Get a vector of strings (char*).
string [] getVectorString (MamaFieldDescriptor descriptor)
Get a vector of strings (char*).
string [] getVectorString (string name, ushort fid, string[] valueIfMissing)
Get a vector of strings (char*).
string [] getVectorString (MamaFieldDescriptor descriptor, string[] valueIfMissing)
Get a vector of strings (char*).
DateTime [] getVectorDateTime (string name, ushort fid)
Get a vector of timestamps.
DateTime [] getVectorDateTime (MamaFieldDescriptor descriptor)
Get a vector of timestamps.
DateTime [] getVectorDateTime (string name, ushort fid, DateTime[] valueIfMissing)
Get a vector of timestamps.
DateTime [] getVectorDateTime (MamaFieldDescriptor descriptor, DateTime[] valueIfMissing)
Get a vector of timestamps.
MamaPrice [] getVectorPrice (string name, ushort fid)
Get a vector of prices.
MamaPrice [] getVectorPrice (MamaFieldDescriptor descriptor)
Get a vector of prices.
MamaPrice [] getVectorPrice (string name, ushort fid, MamaPrice[] valueIfMissing)
Get a vector of prices.
MamaPrice [] getVectorPrice (MamaFieldDescriptor descriptor, MamaPrice[] valueIfMissing)
Get a vector of prices.
MamaMsg [] getVectorMsg (string name, ushort fid)
Get a vector of submessages.
MamaMsg [] getVectorMsg (MamaFieldDescriptor descriptor)
Get a vector of submessages.
MamaMsg [] getVectorMsg (string name, ushort fid, MamaMsg[] valueIfMissing)
Get a vector of submessages.
MamaMsg [] getVectorMsg (MamaFieldDescriptor descriptor, MamaMsg[] valueIfMissing)
Get a vector of submessages.
bool tryBool (string name, ushort fid, ref bool result)
Try to get a bool field.
bool tryBool (MamaFieldDescriptor descriptor, ref bool result)
Try to get a bool field.
bool tryChar (string name, ushort fid, ref char result)
Try to get a char field.
bool tryChar (MamaFieldDescriptor descriptor, ref char result)
Try to get a char field.
bool tryI8 (string name, ushort fid, ref sbyte result)
Try to get a I8, signed 8 bit integer, field.
bool tryI8 (MamaFieldDescriptor descriptor, ref sbyte result)
Try to get a I8, signed 8 bit integer, field.
bool tryU8 (string name, ushort fid, ref byte result)
Try to get a I8, signed 8 bit integer, field.
bool tryU8 (MamaFieldDescriptor descriptor, ref byte result)
Try to get a I8, signed 8 bit integer, field.
bool tryI16 (string name, ushort fid, ref short result)
Try to get a I16, signed 16 bit integer, field.
bool tryI16 (MamaFieldDescriptor descriptor, ref short result)
Try to get a I16, signed 16 bit integer, field.
bool tryU16 (string name, ushort fid, ref ushort result)
Try to get a U16, unsigned 16 bit integer, field.
bool tryU16 (MamaFieldDescriptor descriptor, ref ushort result)
Try to get a U16, unsigned 16 bit integer, field.
bool tryU32 (string name, ushort fid, ref uint result)
Try to get a U32, unsigned 32 bit integer, field.
bool tryU32 (MamaFieldDescriptor descriptor, ref uint result)
Try to get a U32, unsigned 32 bit integer, field.
bool tryI32 (string name, ushort fid, ref int result)
Try to get a I32, signed 32 bit integer, field.
bool tryI32 (MamaFieldDescriptor descriptor, ref int result)
Try to get a I32, signed 32 bit integer, field.
bool tryI64 (string name, ushort fid, ref long result)
<overloads>Try to get a signed 64-bit integer field</overloads>
bool tryI64 (MamaFieldDescriptor descriptor, ref long result)
bool tryU64 (string name, ushort fid, ref ulong result)
Try to get a U64, unsigned 64 bit integer, field.
bool tryU64 (MamaFieldDescriptor descriptor, ref ulong result)
Try to get a U64, unsigned 64 bit integer, field.
bool tryF32 (string name, ushort fid, ref float result)
Try to get a float (f32) field.
bool tryF32 (MamaFieldDescriptor descriptor, ref float result)
Try to get a float (f32) field.
bool tryF64 (string name, ushort fid, ref double result)
Try to get a f64 field.
bool tryF64 (MamaFieldDescriptor descriptor, ref double result)
Try to get a f64 field.
bool tryString (string name, ushort fid, ref string result)
Try to get a string field.
bool tryString (MamaFieldDescriptor descriptor, ref string result)
Try to get a string field.
bool tryOpaque (string name, ushort fid, ref byte[] result)
Try to get an opaque field.
bool tryOpaque (MamaFieldDescriptor descriptor, ref byte[] result)
Try to get an opaque field.
bool tryDateTime (string name, ushort fid, ref DateTime result)
<overloads> Try to get a DateTime object </overloads>
bool tryDateTime (MamaFieldDescriptor descriptor, ref DateTime result)
bool tryPrice (string name, ushort fid, ref MamaPrice result)
Try to get a MAMA price field.
bool tryPrice (string name, ushort fid, MamaPrice result)
bool tryPrice (MamaFieldDescriptor descriptor, ref MamaPrice result)
Try to get a MAMA price field.
bool tryMsg (string name, ushort fid, ref MamaMsg result)
Try to get a submessage.
bool tryMsg (MamaFieldDescriptor descriptor, ref MamaMsg result)
Try to get a submessage.
bool tryVectorBool (string name, ushort fid, ref bool[] result)
Try to get a vector of booleans.
bool tryVectorBool (MamaFieldDescriptor descriptor, ref bool[] result)
Try to get a vector of booleans.
bool tryVectorChar (string name, ushort fid, ref char[] result)
Try to get a vector of chars.
bool tryVectorChar (MamaFieldDescriptor descriptor, ref char[] result)
Try to get a vector of chars.
bool tryVectorI8 (string name, ushort fid, ref sbyte[] result)
Try to get a vector of signed 8 bit integers.
bool tryVectorI8 (MamaFieldDescriptor descriptor, ref sbyte[] result)
Try to get a vector of signed 8 bit integers.
bool tryVectorU8 (string name, ushort fid, ref byte[] result)
Try to get a vector of unsigned 8 bit integers.
bool tryVectorU8 (MamaFieldDescriptor descriptor, ref byte[] result)
Try to get a vector of unsigned 8 bit integers.
bool tryVectorI16 (string name, ushort fid, ref short[] result)
Try to get a vector of signed 16 bit integers.
bool tryVectorI16 (MamaFieldDescriptor descriptor, ref short[] result)
Try to get a vector of signed 16 bit integers.
bool tryVectorU16 (string name, ushort fid, ref ushort[] result)
Try to get a vector of unsigned 16 bit integers.
bool tryVectorU16 (MamaFieldDescriptor descriptor, ref ushort[] result)
Try to get a vector of unsigned 16 bit integers.
bool tryVectorI32 (string name, ushort fid, ref int[] result)
Try to get a vector of signed 32 bit integers.
bool tryVectorI32 (MamaFieldDescriptor descriptor, ref int[] result)
Try to get a vector of signed 32 bit integers.
bool tryVectorU32 (string name, ushort fid, ref uint[] result)
Try to get a vector of unsigned 32 bit integers.
bool tryVectorU32 (MamaFieldDescriptor descriptor, ref uint[] result)
Try to get a vector of unsigned 32 bit integers.
bool tryVectorI64 (string name, ushort fid, ref long[] result)
Try get a vector of signed 64 bit integers.
bool tryVectorI64 (MamaFieldDescriptor descriptor, ref long[] result)
Try get a vector of signed 64 bit integers.
bool tryVectorU64 (string name, ushort fid, ref ulong[] result)
Try to get a vector of unsigned 64 bit integers.
bool tryVectorU64 (MamaFieldDescriptor descriptor, ref ulong[] result)
Try to get a vector of unsigned 64 bit integers.
bool tryVectorF32 (string name, ushort fid, ref float[] result)
Try to get a vector of 32 bit floating point numbers.
bool tryVectorF32 (MamaFieldDescriptor descriptor, ref float[] result)
Try to get a vector of 32 bit floating point numbers.
bool tryVectorF64 (string name, ushort fid, ref double[] result)
Try to get a vector of 64 bit floating point numbers.
bool tryVectorF64 (MamaFieldDescriptor descriptor, ref double[] result)
Try to get a vector of 64 bit floating point numbers.
bool tryVectorString (MamaFieldDescriptor descriptor, ref string[] result)
Try to get a vector of strings (char*).
bool tryVectorDateTime (string name, ushort fid, ref DateTime[] result)
Try to get a vector of timestamps.
bool tryVectorDateTime (MamaFieldDescriptor descriptor, ref DateTime[] result)
Try to get a vector of timestamps.
bool tryVectorPrice (MamaFieldDescriptor descriptor, ref MamaPrice[] result)
Try to get a vector of prices.
bool tryVectorMsg (string name, ushort fid, ref MamaMsg[] result)
<overloads> Try to get a vector of messages </overloads>
bool tryVectorMsg (MamaFieldDescriptor descriptor, ref MamaMsg[] result)
bool tryField (string name, ushort fid, ref MamaMsgField result)
Try to get a MAMA msg field.
bool tryField (MamaFieldDescriptor descriptor, ref MamaMsgField result)
Try to get a MAMA msg field.
bool tryI32 (string name, ushort fid, ref NullableInt result)
<overloads>Try to get a signed 32-bit integer field</overloads>
bool tryI32 (MamaFieldDescriptor descriptor, ref NullableInt result)
bool tryI64 (string name, ushort fid, ref NullableLong result)
<overloads>Try to get a signed 64-bit integer field</overloads>
bool tryI64 (MamaFieldDescriptor descriptor, ref NullableLong result)
int getNumFields ()
Returns the total number of fields in the message.
override string ToString ()
Return a string representation the message.
int getEntitleCode ()
Get the entitle code for this message.
uint getSeqNum ()
Return the sequence
mamaMsgType typeForMsg ()
Extract the type from the supplied message.
string stringForMsg ()
Return the string for this message
string stringForType (mamaMsgType type)
Return the type name.
string stringForStatus (mamaMsgStatus type)
Return the status string
string getFieldAsString (string name, ushort fid)
Return the field value as string
void begin (ref MamaMsgIterator iterator)
void end (ref MamaMsgIterator iterator)
void addVectorString (string name, ushort fid, string[] val)
Add an array of strings (char*) to the message.
void addVectorPrice (string name, ushort fid, MamaPrice[] val)
Add an array of prices to the message.
void addVectorMsg (string name, ushort fid, MamaMsg[] val)
Add an array of nativeHandle objects to the message.
void updateVectorString (string name, ushort fid, string[] val)
Update an array of strings (char*).
void updateVectorPrice (string name, ushort fid, MamaPrice[] val)
Update an array of prices.
void updateVectorMsg (string name, ushort fid, MamaMsg[] val)
Update an array of nativeHandle objects.
bool tryVectorString (string name, ushort fid, ref string[] result)
Try to get a vector of strings (char*).
bool tryVectorPrice (string name, ushort fid, ref MamaPrice[] result)
Try to get a vector of prices.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override void OnDispose ()
override MamaStatus.mamaStatus DestroyNativePeer ()
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
Properties
bool isFromInbox [get]
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
Class which encapsulates the messages used in the MAMA infrastructure
Constructor & Destructor Documentation
MamaMsg() [1/5]
Wombat.MamaMsg.MamaMsg ()
Create a msg using the default payload.
References Wombat.MamaWrapper.nativeHandle.
MamaMsg() [2/5]
Wombat.MamaMsg.MamaMsg (mamaPayloadType payloadId)
NOTE: This function has been deprecated in line with the deprecation of the mamaPayloadType enum.
Create a msg using the payload specified. The payload ID to create the message for
References Wombat.MamaWrapper.nativeHandle.
MamaMsg() [3/5]
Wombat.MamaMsg.MamaMsg (char payloadId)
Create a msg using the payload specified.
Char identifying the payload to create the msg for
References Wombat.MamaWrapper.nativeHandle.
MamaMsg() [4/5]
Wombat.MamaMsg.MamaMsg (MamaPayloadBridge payloadBridge)
Create a msg using the payload bridge specified.
Parameters
payloadBridge The payload bridge to create the message for
References Wombat.MamaWrapper.nativeHandle.
MamaMsg() [5/5]
Wombat.MamaMsg.MamaMsg (MamaMsg mamaMsgSrc)
Create a deep copy of a message.
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
getByteBuffer()
void Wombat.MamaMsg.getByteBuffer (ref byte [] byteBuffer, ref int size)
createFromBuffer()
void Wombat.MamaMsg.createFromBuffer (byte [] byteBuffer, int size)
createForBridgeFromBuffer()
void Wombat.MamaMsg.createForBridgeFromBuffer (byte [] byteBuffer, int size, MamaBridge bridgeImpl)
detach()
MamaMsg Wombat.MamaMsg.detach ()
References Wombat.MamaWrapper.nativeHandle, and Wombat.MamaWrapper.setNativeHandle().
getType()
mamaMsgType Wombat.MamaMsg.getType ()
Extract the type
Returns
getStatus()
mamaMsgStatus Wombat.MamaMsg.getStatus ()
Return the status
Returns
summary> Return the payload type /summary>
References Wombat.MamaFieldDescriptor.getFid(), and Wombat.MamaReservedFields.MsgStatus.
getPayloadType()
mamaPayloadType Wombat.MamaMsg.getPayloadType ()
iterateFields()
void Wombat.MamaMsg.iterateFields (MamaMsgFieldIterator iterator, MamaDictionary dictionary, object closure)
Invoke the specified callback for each field in the message.
Parameters
iterator
dictionary
closure
clear()
void Wombat.MamaMsg.clear ()
Clear a msg.
All fields are removed.
OnDispose()
override void Wombat.MamaMsg.OnDispose () protected virtual
Reimplemented from Wombat.MamaWrapper.
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaMsg.DestroyNativePeer () protected virtual
Returns
Implements Wombat.MamaWrapper.
destroy()
void Wombat.MamaMsg.destroy ()
Destroy a message and free any resources associated with it.
References Wombat.MamaWrapper.Dispose().
getByteSize()
int Wombat.MamaMsg.getByteSize ()
Get the size of the underlying message in bytes.
Only works for tibrvMsg and wombatmsg types.
addBool()
void Wombat.MamaMsg.addBool (string name, ushort fid, bool val)
Add a new bool field.
addChar()
void Wombat.MamaMsg.addChar (string name, ushort fid, char val)
Add a new char field.
addI8()
void Wombat.MamaMsg.addI8 (string name, ushort fid, sbyte val)
Add a new 8 bit signed int field.
addU8()
void Wombat.MamaMsg.addU8 (string name, ushort fid, byte val)
Add a new 8 bit unsigned int field.
addI16()
void Wombat.MamaMsg.addI16 (string name, ushort fid, short val)
Add a new 16 bit signed int field.
addU16()
void Wombat.MamaMsg.addU16 (string name, ushort fid, ushort val)
Add a new 16 bit unsigned int field.
addI32()
void Wombat.MamaMsg.addI32 (string name, ushort fid, int val)
Add a new 32 bit unsigned int field.
addU32()
void Wombat.MamaMsg.addU32 (string name, ushort fid, uint val)
Add a new 32 bit signed int field.
addI64()
void Wombat.MamaMsg.addI64 (string name, ushort fid, long val)
Add a new I64 field.
addU64()
void Wombat.MamaMsg.addU64 (string name, ushort fid, ulong val)
Add a new U64 field.
addF32()
void Wombat.MamaMsg.addF32 (string name, ushort fid, float val)
Add a new float (f32) field.
addF64()
void Wombat.MamaMsg.addF64 (string name, ushort fid, double val)
Add a new f64 field.
addString()
void Wombat.MamaMsg.addString (string name, ushort fid, string val)
Add a string field.
addOpaque()
void Wombat.MamaMsg.addOpaque (string name, ushort fid, byte [] val)
Add an opaque field.
addDateTime()
void Wombat.MamaMsg.addDateTime (string name, ushort fid, DateTime val)
Add a MAMA date/time field.
addPrice()
void Wombat.MamaMsg.addPrice (string name, ushort fid, MamaPrice val)
Add a MAMA price field.
addMsg()
void Wombat.MamaMsg.addMsg (string name, ushort fid, MamaMsg val)
Add a MamaMsg to the msg
addVectorBool()
void Wombat.MamaMsg.addVectorBool (string name, ushort fid, bool [] val)
Add an array of booleans to the message.
addVectorChar()
void Wombat.MamaMsg.addVectorChar (string name, ushort fid, char [] val)
Add an array of characters to the message.
addVectorI8()
void Wombat.MamaMsg.addVectorI8 (string name, ushort fid, sbyte [] val)
Add an array of signed 8 bit integers to the message.
addVectorU8()
void Wombat.MamaMsg.addVectorU8 (string name, ushort fid, byte [] val)
Add an array of unsigned 8 bit integers to the message.
addVectorI16()
void Wombat.MamaMsg.addVectorI16 (string name, ushort fid, short [] val)
Add an array of signed 16 bit integers to the message.
addVectorU16()
void Wombat.MamaMsg.addVectorU16 (string name, ushort fid, ushort [] val)
Add an array of unsigned 16 bit integers to the message.
addVectorI32()
void Wombat.MamaMsg.addVectorI32 (string name, ushort fid, int [] val)
Add an array of signed 32 bit integers to the message.
addVectorU32()
void Wombat.MamaMsg.addVectorU32 (string name, ushort fid, uint [] val)
Add an array of unsigned 32 bit integers to the message.
addVectorI64()
void Wombat.MamaMsg.addVectorI64 (string name, ushort fid, long [] val)
Add an array of signed 64 bit integers to the message.
addVectorU64()
void Wombat.MamaMsg.addVectorU64 (string name, ushort fid, ulong [] val)
Add an array of unsigned 64 bit integers to the message.
addVectorF32()
void Wombat.MamaMsg.addVectorF32 (string name, ushort fid, float [] val)
Add an array of 32 bit floating point numbers to the message.
addVectorF64()
void Wombat.MamaMsg.addVectorF64 (string name, ushort fid, double [] val)
Add an array of 64 bit floating point numbers to the message.
addVectorDateTime()
void Wombat.MamaMsg.addVectorDateTime (string name, ushort fid, DateTime [] val)
Add an array of timestamps to the message.
updateBool()
void Wombat.MamaMsg.updateBool (string name, ushort fid, bool val)
Update the value of an existing bool field.
If the field does not exist it is added.
updateChar()
void Wombat.MamaMsg.updateChar (string name, ushort fid, char val)
Update the value of an existing char field.
If the field does not exist it is added.
updateI8()
void Wombat.MamaMsg.updateI8 (string name, ushort fid, sbyte val)
Update the value of an existing I8 field.
If the field does not exist it is added.
updateU8()
void Wombat.MamaMsg.updateU8 (string name, ushort fid, byte val)
Update the value of an existing U8 field.
If the field does not exist it is added.
updateI16()
void Wombat.MamaMsg.updateI16 (string name, ushort fid, short val)
Update the value of an existing I16 field.
If the field does not exist it is added.
updateU16()
void Wombat.MamaMsg.updateU16 (string name, ushort fid, ushort val)
Update the value of an existing U16 field.
If the field does not exist it is added.
updateI32()
void Wombat.MamaMsg.updateI32 (string name, ushort fid, int val)
Update the value of an existing I32 field.
If the field does not exist it is added.
updateU32()
void Wombat.MamaMsg.updateU32 (string name, ushort fid, uint val)
Update the value of an existing U32 field.
If the field does not exist it is added.
updateI64()
void Wombat.MamaMsg.updateI64 (string name, ushort fid, long val)
Update the value of an existing I64 field.
If the field does not exist it is added.
updateU64()
void Wombat.MamaMsg.updateU64 (string name, ushort fid, ulong val)
Update the value of an existing U64 field.
If the field does not exist it is added.
updateF32()
void Wombat.MamaMsg.updateF32 (string name, ushort fid, float val)
Update the value of an existing float field.
If the field does not exist it is added.
updateF64()
void Wombat.MamaMsg.updateF64 (string name, ushort fid, double val)
Update the value of an existing f64 field.
If the field does not exist it is added.
updateString()
void Wombat.MamaMsg.updateString (string name, ushort fid, string val)
Update the value of an existing string field.
If the field does not exist it is added.
updateOpaque()
void Wombat.MamaMsg.updateOpaque (string name, ushort fid, byte [] val)
Update an opaque field.
updateDateTime()
void Wombat.MamaMsg.updateDateTime (string name, ushort fid, DateTime val)
Update a MAMA date/time field.
updatePrice()
void Wombat.MamaMsg.updatePrice (string name, ushort fid, MamaPrice val)
Update a MAMA price field.
updateVectorBool()
void Wombat.MamaMsg.updateVectorBool (string name, ushort fid, bool [] val)
Update an array of booleans.
updateVectorChar()
void Wombat.MamaMsg.updateVectorChar (string name, ushort fid, char [] val)
Update an array of characters.
updateVectorI8()
void Wombat.MamaMsg.updateVectorI8 (string name, ushort fid, sbyte [] val)
Update an array of signed 8 bit integers.
updateVectorU8()
void Wombat.MamaMsg.updateVectorU8 (string name, ushort fid, byte [] val)
Update an array of unsigned 8 bit integers.
updateVectorI16()
void Wombat.MamaMsg.updateVectorI16 (string name, ushort fid, short [] val)
Update an array of signed 16 bit integers.
updateVectorU16()
void Wombat.MamaMsg.updateVectorU16 (string name, ushort fid, ushort [] val)
Update an array of unsigned 16 bit integers.
updateVectorI32()
void Wombat.MamaMsg.updateVectorI32 (string name, ushort fid, int [] val)
Update an array of signed 32 bit integers.
updateVectorU32()
void Wombat.MamaMsg.updateVectorU32 (string name, ushort fid, uint [] val)
Update an array of unsigned 32 bit integers.
updateVectorI64()
void Wombat.MamaMsg.updateVectorI64 (string name, ushort fid, long [] val)
Update an array of signed 64 bit integers.
updateVectorU64()
void Wombat.MamaMsg.updateVectorU64 (string name, ushort fid, ulong [] val)
Update an array of unsigned 64 bit integers.
updateVectorF32()
void Wombat.MamaMsg.updateVectorF32 (string name, ushort fid, float [] val)
Update an array of 32 bit floating point numbers.
updateVectorF64()
void Wombat.MamaMsg.updateVectorF64 (string name, ushort fid, double [] val)
Update an array of 64 bit floating point numbers.
updateVectorDateTime()
void Wombat.MamaMsg.updateVectorDateTime (string name, ushort fid, DateTime [] val)
Update an array of timestamps.
getBool() [1/4]
bool Wombat.MamaMsg.getBool (string name, ushort fid)
Get a bool field.
getBool() [2/4]
bool Wombat.MamaMsg.getBool (MamaFieldDescriptor descriptor)
Get a bool field.
References Wombat.MamaFieldDescriptor.getFid().
getBool() [3/4]
bool Wombat.MamaMsg.getBool (string name, ushort fid, bool valueIfMissing)
Get a bool field.
getBool() [4/4]
bool Wombat.MamaMsg.getBool (MamaFieldDescriptor descriptor, bool valueIfMissing)
Get a bool field.
References Wombat.MamaFieldDescriptor.getFid().
getChar() [1/4]
char Wombat.MamaMsg.getChar (string name, ushort fid)
Get a char field.
getChar() [2/4]
char Wombat.MamaMsg.getChar (MamaFieldDescriptor descriptor)
Get a char field.
References Wombat.MamaFieldDescriptor.getFid().
getChar() [3/4]
char Wombat.MamaMsg.getChar (string name, ushort fid, char valueIfMissing)
Get a char field.
getChar() [4/4]
char Wombat.MamaMsg.getChar (MamaFieldDescriptor descriptor, char valueIfMissing)
Get a char field.
References Wombat.MamaFieldDescriptor.getFid().
getI8() [1/4]
sbyte Wombat.MamaMsg.getI8 (string name, ushort fid)
Get a I8, signed 8 bit integer, field.
getI8() [2/4]
sbyte Wombat.MamaMsg.getI8 (MamaFieldDescriptor descriptor)
Get a I8, signed 8 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI8() [3/4]
sbyte Wombat.MamaMsg.getI8 (string name, ushort fid, sbyte valueIfMissing)
Get a I8, signed 8 bit integer, field.
getI8() [4/4]
sbyte Wombat.MamaMsg.getI8 (MamaFieldDescriptor descriptor, sbyte valueIfMissing)
Get a I8, signed 8 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU8() [1/4]
byte Wombat.MamaMsg.getU8 (string name, ushort fid)
Get a U8, unsigned 8 bit integer, field.
getU8() [2/4]
byte Wombat.MamaMsg.getU8 (MamaFieldDescriptor descriptor)
Get a U8, unsigned 8 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU8() [3/4]
byte Wombat.MamaMsg.getU8 (string name, ushort fid, byte valueIfMissing)
Get a U8, unsigned 8 bit integer, field.
getU8() [4/4]
byte Wombat.MamaMsg.getU8 (MamaFieldDescriptor descriptor, byte valueIfMissing)
Get a U8, unsigned 8 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI16() [1/4]
short Wombat.MamaMsg.getI16 (string name, ushort fid)
Get a I16, signed 16 bit integer, field.
getI16() [2/4]
short Wombat.MamaMsg.getI16 (MamaFieldDescriptor descriptor)
Get a I16, signed 16 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI16() [3/4]
short Wombat.MamaMsg.getI16 (string name, ushort fid, short valueIfMissing)
Get a I16, signed 16 bit integer, field.
getI16() [4/4]
short Wombat.MamaMsg.getI16 (MamaFieldDescriptor descriptor, short valueIfMissing)
Get a I16, signed 16 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU16() [1/4]
ushort Wombat.MamaMsg.getU16 (string name, ushort fid)
Get a U16, unsigned 16 bit integer, field.
getU16() [2/4]
ushort Wombat.MamaMsg.getU16 (MamaFieldDescriptor descriptor)
Get a U16, unsigned 16 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid(), and Wombat.MamaFieldDescriptor.getName().
getU16() [3/4]
ushort Wombat.MamaMsg.getU16 (string name, ushort fid, ushort valueIfMissing)
Get a U16, unsigned 16 bit integer, field.
getU16() [4/4]
ushort Wombat.MamaMsg.getU16 (MamaFieldDescriptor descriptor, ushort valueIfMissing)
Get a U16, unsigned 16 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI32() [1/4]
int Wombat.MamaMsg.getI32 (string name, ushort fid)
Get a I32, signed 32 bit integer, field.
getI32() [2/4]
int Wombat.MamaMsg.getI32 (MamaFieldDescriptor descriptor)
Get a I32, signed 32 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI32() [3/4]
int Wombat.MamaMsg.getI32 (string name, ushort fid, int valueIfMissing)
Get a I32, signed 32 bit integer, field.
getI32() [4/4]
int Wombat.MamaMsg.getI32 (MamaFieldDescriptor descriptor, int valueIfMissing)
Get a I32, signed 32 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU32() [1/4]
uint Wombat.MamaMsg.getU32 (string name, ushort fid)
Get a U32, unsigned 32 bit integer, field.
getU32() [2/4]
uint Wombat.MamaMsg.getU32 (MamaFieldDescriptor descriptor)
Get a U32, unsigned 32 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU32() [3/4]
uint Wombat.MamaMsg.getU32 (string name, ushort fid, uint valueIfMissing)
Get a U32, unsigned 32 bit integer, field.
getU32() [4/4]
uint Wombat.MamaMsg.getU32 (MamaFieldDescriptor descriptor, uint valueIfMissing)
Get a U32, unsigned 32 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI64() [1/4]
long Wombat.MamaMsg.getI64 (string name, ushort fid)
Get a I64, signed 64 bit integer, field.
getI64() [2/4]
long Wombat.MamaMsg.getI64 (MamaFieldDescriptor descriptor)
Get a I64, signed 64 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getI64() [3/4]
long Wombat.MamaMsg.getI64 (string name, ushort fid, long valueIfMissing)
Get a I64, signed 64 bit integer, field.
getI64() [4/4]
long Wombat.MamaMsg.getI64 (MamaFieldDescriptor descriptor, long valueIfMissing)
Get a I64, signed 64 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU64() [1/4]
ulong Wombat.MamaMsg.getU64 (string name, ushort fid)
Get a U64, unsigned 64 bit integer, field.
getU64() [2/4]
ulong Wombat.MamaMsg.getU64 (MamaFieldDescriptor descriptor)
Get a U64, unsigned 64 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getU64() [3/4]
ulong Wombat.MamaMsg.getU64 (string name, ushort fid, ulong valueIfMissing)
Get a U64, unsigned 64 bit integer, field.
getU64() [4/4]
ulong Wombat.MamaMsg.getU64 (MamaFieldDescriptor descriptor, ulong valueIfMissing)
Get a U64, unsigned 64 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
getF32() [1/4]
float Wombat.MamaMsg.getF32 (string name, ushort fid)
Get a float (f32) field.
getF32() [2/4]
float Wombat.MamaMsg.getF32 (MamaFieldDescriptor descriptor)
Get a float (f32) field.
References Wombat.MamaFieldDescriptor.getFid().
getF32() [3/4]
float Wombat.MamaMsg.getF32 (string name, ushort fid, float valueIfMissing)
Get a float (f32) field.
getF32() [4/4]
float Wombat.MamaMsg.getF32 (MamaFieldDescriptor descriptor, float valueIfMissing)
Get a float (f32) field.
References Wombat.MamaFieldDescriptor.getFid().
getF64() [1/4]
double Wombat.MamaMsg.getF64 (string name, ushort fid)
Get a F64 field.
getF64() [2/4]
double Wombat.MamaMsg.getF64 (MamaFieldDescriptor descriptor)
Get a F64 field.
References Wombat.MamaFieldDescriptor.getFid().
getF64() [3/4]
double Wombat.MamaMsg.getF64 (string name, ushort fid, double valueIfMissing)
Get a F64 field.
getF64() [4/4]
double Wombat.MamaMsg.getF64 (MamaFieldDescriptor descriptor, double valueIfMissing)
Get a F64 field.
References Wombat.MamaFieldDescriptor.getFid().
getString() [1/4]
string Wombat.MamaMsg.getString (string name, ushort fid)
Get a string field.
tryStringAnsi() [1/2]
bool Wombat.MamaMsg.tryStringAnsi (string name, ushort fid, ref IntPtr result)
tryStringAnsi() [2/2]
bool Wombat.MamaMsg.tryStringAnsi (MamaFieldDescriptor descriptor, ref IntPtr result)
References Wombat.MamaFieldDescriptor.getFid().
getString() [2/4]
string Wombat.MamaMsg.getString (MamaFieldDescriptor descriptor)
Get a string field.
References Wombat.MamaFieldDescriptor.getFid().
getString() [3/4]
string Wombat.MamaMsg.getString (string name, ushort fid, string valueIfMissing)
Get a string field.
getString() [4/4]
string Wombat.MamaMsg.getString (MamaFieldDescriptor descriptor, string valueIfMissing)
Get a string field.
References Wombat.MamaFieldDescriptor.getFid().
getOpaque() [1/4]
byte [] Wombat.MamaMsg.getOpaque (string name, ushort fid)
Get an opaque field.
getOpaque() [2/4]
byte [] Wombat.MamaMsg.getOpaque (MamaFieldDescriptor descriptor)
Get a opaque field.
References Wombat.MamaFieldDescriptor.getFid().
getOpaque() [3/4]
byte [] Wombat.MamaMsg.getOpaque (string name, ushort fid, byte [] valueIfMissing)
Get a opaque field.
getOpaque() [4/4]
byte [] Wombat.MamaMsg.getOpaque (MamaFieldDescriptor descriptor, byte [] valueIfMissing)
Get a opaque field.
References Wombat.MamaFieldDescriptor.getFid().
getDateTime() [1/4]
DateTime Wombat.MamaMsg.getDateTime (string name, ushort fid)
Get a MAMA date/time field.
getDateTime() [2/4]
DateTime Wombat.MamaMsg.getDateTime (MamaFieldDescriptor descriptor)
Get a MAMA date/time field.
References Wombat.MamaFieldDescriptor.getFid().
getDateTime() [3/4]
DateTime Wombat.MamaMsg.getDateTime (string name, ushort fid, DateTime valueIfMissing)
Get a MAMA date/time field.
getDateTime() [4/4]
DateTime Wombat.MamaMsg.getDateTime (MamaFieldDescriptor descriptor, DateTime valueIfMissing)
Get a MAMA date/time field.
References Wombat.MamaFieldDescriptor.getFid().
getPrice() [1/4]
MamaPrice Wombat.MamaMsg.getPrice (string name, ushort fid)
Get a MAMA price field.
getPrice() [2/4]
MamaPrice Wombat.MamaMsg.getPrice (MamaFieldDescriptor descriptor)
Get a MAMA price field.
References Wombat.MamaFieldDescriptor.getFid().
getPrice() [3/4]
MamaPrice Wombat.MamaMsg.getPrice (string name, ushort fid, MamaPrice valueIfMissing)
Get a MAMA price field.
getPrice() [4/4]
MamaPrice Wombat.MamaMsg.getPrice (MamaFieldDescriptor descriptor, MamaPrice valueIfMissing)
Get a MAMA price field.
References Wombat.MamaFieldDescriptor.getFid().
getMsg() [1/4]
MamaMsg Wombat.MamaMsg.getMsg (string name, ushort fid)
Get a submessage.
getMsg() [2/4]
MamaMsg Wombat.MamaMsg.getMsg (MamaFieldDescriptor descriptor)
Get a submessage.
References Wombat.MamaFieldDescriptor.getFid().
getMsg() [3/4]
MamaMsg Wombat.MamaMsg.getMsg (string name, ushort fid, MamaMsg valueIfMissing)
Get a submessage.
Parameters
name
fid
valueIfMissing
Returns
getMsg() [4/4]
MamaMsg Wombat.MamaMsg.getMsg (MamaFieldDescriptor descriptor, MamaMsg valueIfMissing)
Get a submessage.
Parameters
descriptor
valueIfMissing
Returns
References Wombat.MamaFieldDescriptor.getFid().
getField() [1/4]
MamaMsgField Wombat.MamaMsg.getField (string name, ushort fid)
Get a MAMA msg field.
The result contains the reusable field object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
getField() [2/4]
MamaMsgField Wombat.MamaMsg.getField (MamaFieldDescriptor descriptor)
Get a MAMA msg field.
The result contains the reusable field object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
References Wombat.MamaFieldDescriptor.getFid(), and Wombat.MamaMsgIterator.getField().
getField() [3/4]
MamaMsgField Wombat.MamaMsg.getField (string name, ushort fid, MamaMsgField valueIfMissing)
Get a MAMA msg field.
The result contains the reusable field object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
getField() [4/4]
MamaMsgField Wombat.MamaMsg.getField (MamaFieldDescriptor descriptor, MamaMsgField valueIfMissing)
Get a MAMA msg field.
The result contains the reusable field object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
References Wombat.MamaFieldDescriptor.getFid(), and Wombat.MamaMsgIterator.getField().
getVectorBool() [1/4]
bool [] Wombat.MamaMsg.getVectorBool (string name, ushort fid)
Get a vector of booleans.
getVectorBool() [2/4]
bool [] Wombat.MamaMsg.getVectorBool (MamaFieldDescriptor descriptor)
Get a vector of booleans.
References Wombat.MamaFieldDescriptor.getFid().
getVectorBool() [3/4]
bool [] Wombat.MamaMsg.getVectorBool (string name, ushort fid, bool [] valueIfMissing)
Get a vector of booleans.
getVectorBool() [4/4]
bool [] Wombat.MamaMsg.getVectorBool (MamaFieldDescriptor descriptor, bool [] valueIfMissing)
Get a vector of booleans.
References Wombat.MamaFieldDescriptor.getFid().
getVectorChar() [1/4]
char [] Wombat.MamaMsg.getVectorChar (string name, ushort fid)
Get a vector of chars.
getVectorChar() [2/4]
char [] Wombat.MamaMsg.getVectorChar (MamaFieldDescriptor descriptor)
Get a vector of chars.
References Wombat.MamaFieldDescriptor.getFid().
getVectorChar() [3/4]
char [] Wombat.MamaMsg.getVectorChar (string name, ushort fid, char [] valueIfMissing)
Get a vector of chars.
getVectorChar() [4/4]
char [] Wombat.MamaMsg.getVectorChar (MamaFieldDescriptor descriptor, char [] valueIfMissing)
Get a vector of chars.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI8() [1/4]
sbyte [] Wombat.MamaMsg.getVectorI8 (string name, ushort fid)
Get a vector of signed 8 bit integers.
getVectorI8() [2/4]
sbyte [] Wombat.MamaMsg.getVectorI8 (MamaFieldDescriptor descriptor)
Get a vector of signed 8 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI8() [3/4]
sbyte [] Wombat.MamaMsg.getVectorI8 (string name, ushort fid, sbyte [] valueIfMissing)
Get a vector of signed 8 bit integers.
getVectorI8() [4/4]
sbyte [] Wombat.MamaMsg.getVectorI8 (MamaFieldDescriptor descriptor, sbyte [] valueIfMissing)
Get a vector of signed 8 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU8() [1/4]
byte [] Wombat.MamaMsg.getVectorU8 (string name, ushort fid)
Get a vector of unsigned 8 bit integers.
getVectorU8() [2/4]
byte [] Wombat.MamaMsg.getVectorU8 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 8 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU8() [3/4]
byte [] Wombat.MamaMsg.getVectorU8 (string name, ushort fid, byte [] valueIfMissing)
Get a vector of unsigned 8 bit integers.
getVectorU8() [4/4]
byte [] Wombat.MamaMsg.getVectorU8 (MamaFieldDescriptor descriptor, byte [] valueIfMissing)
Get a vector of unsigned 8 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI16() [1/4]
short [] Wombat.MamaMsg.getVectorI16 (string name, ushort fid)
Get a vector of signed 16 bit integers.
getVectorI16() [2/4]
short [] Wombat.MamaMsg.getVectorI16 (MamaFieldDescriptor descriptor)
Get a vector of signed 16 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI16() [3/4]
short [] Wombat.MamaMsg.getVectorI16 (string name, ushort fid, short [] valueIfMissing)
Get a vector of signed 16 bit integers.
getVectorI16() [4/4]
short [] Wombat.MamaMsg.getVectorI16 (MamaFieldDescriptor descriptor, short [] valueIfMissing)
Get a vector of signed 16 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU16() [1/4]
ushort [] Wombat.MamaMsg.getVectorU16 (string name, ushort fid)
Get a vector of unsigned 16 bit integers.
getVectorU16() [2/4]
ushort [] Wombat.MamaMsg.getVectorU16 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 16 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU16() [3/4]
ushort [] Wombat.MamaMsg.getVectorU16 (string name, ushort fid, ushort [] valueIfMissing)
Get a vector of unsigned 16 bit integers.
getVectorU16() [4/4]
ushort [] Wombat.MamaMsg.getVectorU16 (MamaFieldDescriptor descriptor, ushort [] valueIfMissing)
Get a vector of unsigned 16 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI32() [1/4]
int [] Wombat.MamaMsg.getVectorI32 (string name, ushort fid)
Get a vector of signed 32 bit integers.
getVectorI32() [2/4]
int [] Wombat.MamaMsg.getVectorI32 (MamaFieldDescriptor descriptor)
Get a vector of signed 32 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI32() [3/4]
int [] Wombat.MamaMsg.getVectorI32 (string name, ushort fid, int [] valueIfMissing)
Get a vector of signed 32 bit integers.
getVectorI32() [4/4]
int [] Wombat.MamaMsg.getVectorI32 (MamaFieldDescriptor descriptor, int [] valueIfMissing)
Get a vector of signed 32 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU32() [1/4]
uint [] Wombat.MamaMsg.getVectorU32 (string name, ushort fid)
Get a vector of unsigned 32 bit integers.
getVectorU32() [2/4]
uint [] Wombat.MamaMsg.getVectorU32 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 32 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU32() [3/4]
uint [] Wombat.MamaMsg.getVectorU32 (string name, ushort fid, uint [] valueIfMissing)
Get a vector of unsigned 32 bit integers.
getVectorU32() [4/4]
uint [] Wombat.MamaMsg.getVectorU32 (MamaFieldDescriptor descriptor, uint [] valueIfMissing)
Get a vector of unsigned 32 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI64() [1/4]
long [] Wombat.MamaMsg.getVectorI64 (string name, ushort fid)
Get a vector of signed 64 bit integers.
getVectorI64() [2/4]
long [] Wombat.MamaMsg.getVectorI64 (MamaFieldDescriptor descriptor)
Get a vector of signed 64 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorI64() [3/4]
long [] Wombat.MamaMsg.getVectorI64 (string name, ushort fid, long [] valueIfMissing)
Get a vector of signed 64 bit integers.
getVectorI64() [4/4]
long [] Wombat.MamaMsg.getVectorI64 (MamaFieldDescriptor descriptor, long [] valueIfMissing)
Get a vector of signed 64 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU64() [1/4]
ulong [] Wombat.MamaMsg.getVectorU64 (string name, ushort fid)
Get a vector of unsigned 64 bit integers.
getVectorU64() [2/4]
ulong [] Wombat.MamaMsg.getVectorU64 (MamaFieldDescriptor descriptor)
Get a vector of unsigned 64 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorU64() [3/4]
ulong [] Wombat.MamaMsg.getVectorU64 (string name, ushort fid, ulong [] valueIfMissing)
Get a vector of unsigned 64 bit integers.
getVectorU64() [4/4]
ulong [] Wombat.MamaMsg.getVectorU64 (MamaFieldDescriptor descriptor, ulong [] valueIfMissing)
Get a vector of unsigned 64 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorF32() [1/4]
float [] Wombat.MamaMsg.getVectorF32 (string name, ushort fid)
Get a vector of 32 bit floating point numbers.
getVectorF32() [2/4]
float [] Wombat.MamaMsg.getVectorF32 (MamaFieldDescriptor descriptor)
Get a vector of 32 bit floating point numbers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorF32() [3/4]
float [] Wombat.MamaMsg.getVectorF32 (string name, ushort fid, float [] valueIfMissing)
Get a vector of 32 bit floating point numbers.
getVectorF32() [4/4]
float [] Wombat.MamaMsg.getVectorF32 (MamaFieldDescriptor descriptor, float [] valueIfMissing)
Get a vector of 32 bit floating point numbers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorF64() [1/4]
double [] Wombat.MamaMsg.getVectorF64 (string name, ushort fid)
Get a vector of 64 bit floating point numbers.
getVectorF64() [2/4]
double [] Wombat.MamaMsg.getVectorF64 (MamaFieldDescriptor descriptor)
Get a vector of 64 bit floating point numbers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorF64() [3/4]
double [] Wombat.MamaMsg.getVectorF64 (string name, ushort fid, double [] valueIfMissing)
Get a vector of 64 bit floating point numbers.
getVectorF64() [4/4]
double [] Wombat.MamaMsg.getVectorF64 (MamaFieldDescriptor descriptor, double [] valueIfMissing)
Get a vector of 64 bit floating point numbers.
References Wombat.MamaFieldDescriptor.getFid().
getVectorString() [1/4]
string [] Wombat.MamaMsg.getVectorString (string name, ushort fid)
Get a vector of strings (char*).
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
Exceptions
MamaException Thrown if the vector could not be found.
getVectorString() [2/4]
string [] Wombat.MamaMsg.getVectorString (MamaFieldDescriptor descriptor)
Get a vector of strings (char*).
References Wombat.MamaFieldDescriptor.getFid().
getVectorString() [3/4]
string [] Wombat.MamaMsg.getVectorString (string name, ushort fid, string [] valueIfMissing)
Get a vector of strings (char*).
getVectorString() [4/4]
string [] Wombat.MamaMsg.getVectorString (MamaFieldDescriptor descriptor, string [] valueIfMissing)
Get a vector of strings (char*).
References Wombat.MamaFieldDescriptor.getFid().
getVectorDateTime() [1/4]
DateTime [] Wombat.MamaMsg.getVectorDateTime (string name, ushort fid)
Get a vector of timestamps.
getVectorDateTime() [2/4]
DateTime [] Wombat.MamaMsg.getVectorDateTime (MamaFieldDescriptor descriptor)
Get a vector of timestamps.
References Wombat.MamaFieldDescriptor.getFid().
getVectorDateTime() [3/4]
DateTime [] Wombat.MamaMsg.getVectorDateTime (string name, ushort fid, DateTime [] valueIfMissing)
Get a vector of timestamps.
getVectorDateTime() [4/4]
DateTime [] Wombat.MamaMsg.getVectorDateTime (MamaFieldDescriptor descriptor, DateTime [] valueIfMissing)
Get a vector of timestamps.
References Wombat.MamaFieldDescriptor.getFid().
getVectorPrice() [1/4]
MamaPrice [] Wombat.MamaMsg.getVectorPrice (string name, ushort fid)
Get a vector of prices.
getVectorPrice() [2/4]
MamaPrice [] Wombat.MamaMsg.getVectorPrice (MamaFieldDescriptor descriptor)
Get a vector of prices.
References Wombat.MamaFieldDescriptor.getFid().
getVectorPrice() [3/4]
MamaPrice [] Wombat.MamaMsg.getVectorPrice (string name, ushort fid, MamaPrice [] valueIfMissing)
Get a vector of prices.
getVectorPrice() [4/4]
MamaPrice [] Wombat.MamaMsg.getVectorPrice (MamaFieldDescriptor descriptor, MamaPrice [] valueIfMissing)
Get a vector of prices.
References Wombat.MamaFieldDescriptor.getFid().
getVectorMsg() [1/4]
MamaMsg [] Wombat.MamaMsg.getVectorMsg (string name, ushort fid)
Get a vector of submessages.
getVectorMsg() [2/4]
MamaMsg [] Wombat.MamaMsg.getVectorMsg (MamaFieldDescriptor descriptor)
Get a vector of submessages.
References Wombat.MamaFieldDescriptor.getFid().
getVectorMsg() [3/4]
MamaMsg [] Wombat.MamaMsg.getVectorMsg (string name, ushort fid, MamaMsg [] valueIfMissing)
Get a vector of submessages.
Parameters
name
fid
valueIfMissing
Returns
getVectorMsg() [4/4]
MamaMsg [] Wombat.MamaMsg.getVectorMsg (MamaFieldDescriptor descriptor, MamaMsg [] valueIfMissing)
Get a vector of submessages.
Parameters
descriptor
valueIfMissing
Returns
References Wombat.MamaFieldDescriptor.getFid().
tryBool() [1/2]
bool Wombat.MamaMsg.tryBool (string name, ushort fid, ref bool result)
Try to get a bool field.
tryBool() [2/2]
bool Wombat.MamaMsg.tryBool (MamaFieldDescriptor descriptor, ref bool result)
Try to get a bool field.
References Wombat.MamaFieldDescriptor.getFid().
tryChar() [1/2]
bool Wombat.MamaMsg.tryChar (string name, ushort fid, ref char result)
Try to get a char field.
tryChar() [2/2]
bool Wombat.MamaMsg.tryChar (MamaFieldDescriptor descriptor, ref char result)
Try to get a char field.
References Wombat.MamaFieldDescriptor.getFid().
tryI8() [1/2]
bool Wombat.MamaMsg.tryI8 (string name, ushort fid, ref sbyte result)
Try to get a I8, signed 8 bit integer, field.
tryI8() [2/2]
bool Wombat.MamaMsg.tryI8 (MamaFieldDescriptor descriptor, ref sbyte result)
Try to get a I8, signed 8 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
tryU8() [1/2]
bool Wombat.MamaMsg.tryU8 (string name, ushort fid, ref byte result)
Try to get a I8, signed 8 bit integer, field.
tryU8() [2/2]
bool Wombat.MamaMsg.tryU8 (MamaFieldDescriptor descriptor, ref byte result)
Try to get a I8, signed 8 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
tryI16() [1/2]
bool Wombat.MamaMsg.tryI16 (string name, ushort fid, ref short result)
Try to get a I16, signed 16 bit integer, field.
tryI16() [2/2]
bool Wombat.MamaMsg.tryI16 (MamaFieldDescriptor descriptor, ref short result)
Try to get a I16, signed 16 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
tryU16() [1/2]
bool Wombat.MamaMsg.tryU16 (string name, ushort fid, ref ushort result)
Try to get a U16, unsigned 16 bit integer, field.
tryU16() [2/2]
bool Wombat.MamaMsg.tryU16 (MamaFieldDescriptor descriptor, ref ushort result)
Try to get a U16, unsigned 16 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
tryU32() [1/2]
bool Wombat.MamaMsg.tryU32 (string name, ushort fid, ref uint result)
Try to get a U32, unsigned 32 bit integer, field.
tryU32() [2/2]
bool Wombat.MamaMsg.tryU32 (MamaFieldDescriptor descriptor, ref uint result)
Try to get a U32, unsigned 32 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
tryI32() [1/4]
bool Wombat.MamaMsg.tryI32 (string name, ushort fid, ref int result)
Try to get a I32, signed 32 bit integer, field.
Parameters
name
fid
result
Returns
tryI32() [2/4]
bool Wombat.MamaMsg.tryI32 (MamaFieldDescriptor descriptor, ref int result)
Try to get a I32, signed 32 bit integer, field.
Parameters
descriptor
result
Returns
References Wombat.MamaFieldDescriptor.getFid().
tryI64() [1/4]
bool Wombat.MamaMsg.tryI64 (string name, ushort fid, ref long result)
<overloads>Try to get a signed 64-bit integer field</overloads>
tryI64() [2/4]
bool Wombat.MamaMsg.tryI64 (MamaFieldDescriptor descriptor, ref long result)
References Wombat.MamaFieldDescriptor.getFid().
tryU64() [1/2]
bool Wombat.MamaMsg.tryU64 (string name, ushort fid, ref ulong result)
Try to get a U64, unsigned 64 bit integer, field.
tryU64() [2/2]
bool Wombat.MamaMsg.tryU64 (MamaFieldDescriptor descriptor, ref ulong result)
Try to get a U64, unsigned 64 bit integer, field.
References Wombat.MamaFieldDescriptor.getFid().
tryF32() [1/2]
bool Wombat.MamaMsg.tryF32 (string name, ushort fid, ref float result)
Try to get a float (f32) field.
tryF32() [2/2]
bool Wombat.MamaMsg.tryF32 (MamaFieldDescriptor descriptor, ref float result)
Try to get a float (f32) field.
References Wombat.MamaFieldDescriptor.getFid().
tryF64() [1/2]
bool Wombat.MamaMsg.tryF64 (string name, ushort fid, ref double result)
Try to get a f64 field.
tryF64() [2/2]
bool Wombat.MamaMsg.tryF64 (MamaFieldDescriptor descriptor, ref double result)
Try to get a f64 field.
References Wombat.MamaFieldDescriptor.getFid().
tryString() [1/2]
bool Wombat.MamaMsg.tryString (string name, ushort fid, ref string result)
Try to get a string field.
tryString() [2/2]
bool Wombat.MamaMsg.tryString (MamaFieldDescriptor descriptor, ref string result)
Try to get a string field.
References Wombat.MamaFieldDescriptor.getFid().
tryOpaque() [1/2]
bool Wombat.MamaMsg.tryOpaque (string name, ushort fid, ref byte [] result)
Try to get an opaque field.
tryOpaque() [2/2]
bool Wombat.MamaMsg.tryOpaque (MamaFieldDescriptor descriptor, ref byte [] result)
Try to get an opaque field.
References Wombat.MamaFieldDescriptor.getFid().
tryDateTime() [1/2]
bool Wombat.MamaMsg.tryDateTime (string name, ushort fid, ref DateTime result)
<overloads> Try to get a DateTime object </overloads>
tryDateTime() [2/2]
bool Wombat.MamaMsg.tryDateTime (MamaFieldDescriptor descriptor, ref DateTime result)
References Wombat.MamaFieldDescriptor.getFid().
tryPrice() [1/3]
bool Wombat.MamaMsg.tryPrice (string name, ushort fid, ref MamaPrice result)
Try to get a MAMA price field.
tryPrice() [2/3]
bool Wombat.MamaMsg.tryPrice (string name, ushort fid, MamaPrice result)
Try to get a MAMA price field.
tryPrice() [3/3]
bool Wombat.MamaMsg.tryPrice (MamaFieldDescriptor descriptor, ref MamaPrice result)
Try to get a MAMA price field.
References Wombat.MamaFieldDescriptor.getFid().
tryMsg() [1/2]
bool Wombat.MamaMsg.tryMsg (string name, ushort fid, ref MamaMsg result)
Try to get a submessage.
tryMsg() [2/2]
bool Wombat.MamaMsg.tryMsg (MamaFieldDescriptor descriptor, ref MamaMsg result)
Try to get a submessage.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorBool() [1/2]
bool Wombat.MamaMsg.tryVectorBool (string name, ushort fid, ref bool [] result)
Try to get a vector of booleans.
tryVectorBool() [2/2]
bool Wombat.MamaMsg.tryVectorBool (MamaFieldDescriptor descriptor, ref bool [] result)
Try to get a vector of booleans.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorChar() [1/2]
bool Wombat.MamaMsg.tryVectorChar (string name, ushort fid, ref char [] result)
Try to get a vector of chars.
tryVectorChar() [2/2]
bool Wombat.MamaMsg.tryVectorChar (MamaFieldDescriptor descriptor, ref char [] result)
Try to get a vector of chars.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorI8() [1/2]
bool Wombat.MamaMsg.tryVectorI8 (string name, ushort fid, ref sbyte [] result)
Try to get a vector of signed 8 bit integers.
tryVectorI8() [2/2]
bool Wombat.MamaMsg.tryVectorI8 (MamaFieldDescriptor descriptor, ref sbyte [] result)
Try to get a vector of signed 8 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorU8() [1/2]
bool Wombat.MamaMsg.tryVectorU8 (string name, ushort fid, ref byte [] result)
Try to get a vector of unsigned 8 bit integers.
tryVectorU8() [2/2]
bool Wombat.MamaMsg.tryVectorU8 (MamaFieldDescriptor descriptor, ref byte [] result)
Try to get a vector of unsigned 8 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorI16() [1/2]
bool Wombat.MamaMsg.tryVectorI16 (string name, ushort fid, ref short [] result)
Try to get a vector of signed 16 bit integers.
tryVectorI16() [2/2]
bool Wombat.MamaMsg.tryVectorI16 (MamaFieldDescriptor descriptor, ref short [] result)
Try to get a vector of signed 16 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorU16() [1/2]
bool Wombat.MamaMsg.tryVectorU16 (string name, ushort fid, ref ushort [] result)
Try to get a vector of unsigned 16 bit integers.
tryVectorU16() [2/2]
bool Wombat.MamaMsg.tryVectorU16 (MamaFieldDescriptor descriptor, ref ushort [] result)
Try to get a vector of unsigned 16 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorI32() [1/2]
bool Wombat.MamaMsg.tryVectorI32 (string name, ushort fid, ref int [] result)
Try to get a vector of signed 32 bit integers.
tryVectorI32() [2/2]
bool Wombat.MamaMsg.tryVectorI32 (MamaFieldDescriptor descriptor, ref int [] result)
Try to get a vector of signed 32 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorU32() [1/2]
bool Wombat.MamaMsg.tryVectorU32 (string name, ushort fid, ref uint [] result)
Try to get a vector of unsigned 32 bit integers.
tryVectorU32() [2/2]
bool Wombat.MamaMsg.tryVectorU32 (MamaFieldDescriptor descriptor, ref uint [] result)
Try to get a vector of unsigned 32 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorI64() [1/2]
bool Wombat.MamaMsg.tryVectorI64 (string name, ushort fid, ref long [] result)
Try get a vector of signed 64 bit integers.
tryVectorI64() [2/2]
bool Wombat.MamaMsg.tryVectorI64 (MamaFieldDescriptor descriptor, ref long [] result)
Try get a vector of signed 64 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorU64() [1/2]
bool Wombat.MamaMsg.tryVectorU64 (string name, ushort fid, ref ulong [] result)
Try to get a vector of unsigned 64 bit integers.
tryVectorU64() [2/2]
bool Wombat.MamaMsg.tryVectorU64 (MamaFieldDescriptor descriptor, ref ulong [] result)
Try to get a vector of unsigned 64 bit integers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorF32() [1/2]
bool Wombat.MamaMsg.tryVectorF32 (string name, ushort fid, ref float [] result)
Try to get a vector of 32 bit floating point numbers.
tryVectorF32() [2/2]
bool Wombat.MamaMsg.tryVectorF32 (MamaFieldDescriptor descriptor, ref float [] result)
Try to get a vector of 32 bit floating point numbers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorF64() [1/2]
bool Wombat.MamaMsg.tryVectorF64 (string name, ushort fid, ref double [] result)
Try to get a vector of 64 bit floating point numbers.
tryVectorF64() [2/2]
bool Wombat.MamaMsg.tryVectorF64 (MamaFieldDescriptor descriptor, ref double [] result)
Try to get a vector of 64 bit floating point numbers.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorString() [1/2]
bool Wombat.MamaMsg.tryVectorString (MamaFieldDescriptor descriptor, ref string [] result)
Try to get a vector of strings (char*).
References Wombat.MamaFieldDescriptor.getFid().
tryVectorDateTime() [1/2]
bool Wombat.MamaMsg.tryVectorDateTime (string name, ushort fid, ref DateTime [] result)
Try to get a vector of timestamps.
tryVectorDateTime() [2/2]
bool Wombat.MamaMsg.tryVectorDateTime (MamaFieldDescriptor descriptor, ref DateTime [] result)
Try to get a vector of timestamps.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorPrice() [1/2]
bool Wombat.MamaMsg.tryVectorPrice (MamaFieldDescriptor descriptor, ref MamaPrice [] result)
Try to get a vector of prices.
References Wombat.MamaFieldDescriptor.getFid().
tryVectorMsg() [1/2]
bool Wombat.MamaMsg.tryVectorMsg (string name, ushort fid, ref MamaMsg [] result)
<overloads> Try to get a vector of messages </overloads>
tryVectorMsg() [2/2]
bool Wombat.MamaMsg.tryVectorMsg (MamaFieldDescriptor descriptor, ref MamaMsg [] result)
References Wombat.MamaFieldDescriptor.getFid().
tryField() [1/2]
bool Wombat.MamaMsg.tryField (string name, ushort fid, ref MamaMsgField result)
Try to get a MAMA msg field.
The result contains the reusable field object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
tryField() [2/2]
bool Wombat.MamaMsg.tryField (MamaFieldDescriptor descriptor, ref MamaMsgField result)
Try to get a MAMA msg field.
The result contains the reusable field object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
References Wombat.MamaFieldDescriptor.getFid().
tryI32() [3/4]
bool Wombat.MamaMsg.tryI32 (string name, ushort fid, ref NullableInt result)
<overloads>Try to get a signed 32-bit integer field</overloads>
tryI32() [4/4]
bool Wombat.MamaMsg.tryI32 (MamaFieldDescriptor descriptor, ref NullableInt result)
References Wombat.MamaFieldDescriptor.getFid().
tryI64() [3/4]
bool Wombat.MamaMsg.tryI64 (string name, ushort fid, ref NullableLong result)
<overloads>Try to get a signed 64-bit integer field</overloads>
tryI64() [4/4]
bool Wombat.MamaMsg.tryI64 (MamaFieldDescriptor descriptor, ref NullableLong result)
References Wombat.MamaFieldDescriptor.getFid(), and Wombat.MamaWrapper.setNativeHandle().
getNumFields()
int Wombat.MamaMsg.getNumFields ()
Returns the total number of fields in the message.
Sub-messages count as a single field.
ToString()
override string Wombat.MamaMsg.ToString ()
Return a string representation the message.
getEntitleCode()
int Wombat.MamaMsg.getEntitleCode ()
Get the entitle code for this message.
The result defaults to 0 (no entitlement) if the field is not present.
getSeqNum()
uint Wombat.MamaMsg.getSeqNum ()
Return the sequence
Returns
typeForMsg()
mamaMsgType Wombat.MamaMsg.typeForMsg ()
Extract the type from the supplied message.
stringForMsg()
string Wombat.MamaMsg.stringForMsg ()
Return the string for this message
stringForType()
string Wombat.MamaMsg.stringForType (mamaMsgType type)
Return the type name.
stringForStatus()
string Wombat.MamaMsg.stringForStatus (mamaMsgStatus type)
Return the status string
getFieldAsString()
string Wombat.MamaMsg.getFieldAsString (string name, ushort fid)
Return the field value as string
begin()
void Wombat.MamaMsg.begin (ref MamaMsgIterator iterator)
end()
void Wombat.MamaMsg.end (ref MamaMsgIterator iterator)
References Wombat.Mama.DllName, and Wombat.MamaWrapper.setNativeHandle().
addVectorString()
void Wombat.MamaMsg.addVectorString (string name, ushort fid, string [] val)
Add an array of strings (char*) to the message.
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
val The array of strings to add.
Exceptions
ArgumentNullException Throw if the string array is null.
ArgumentOutOfRangeException Throw if there are no items in the string array.
addVectorPrice()
void Wombat.MamaMsg.addVectorPrice (string name, ushort fid, MamaPrice [] val)
Add an array of prices to the message.
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
val The array of messages to add.
Exceptions
ArgumentNullException Throw if the message array is null.
ArgumentOutOfRangeException Throw if there are no items in the message array.
addVectorMsg()
void Wombat.MamaMsg.addVectorMsg (string name, ushort fid, MamaMsg [] val)
Add an array of nativeHandle objects to the message.
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
val The array of messages to add.
Exceptions
ArgumentNullException Throw if the message array is null.
ArgumentOutOfRangeException Throw if there are no items in the message array.
References Wombat.MamaWrapper.nativeHandle.
updateVectorString()
void Wombat.MamaMsg.updateVectorString (string name, ushort fid, string [] val)
Update an array of strings (char*).
Parameters
name The field name, can be null or blank if the field Id is supplied.
fid
val The array of strings to add.
Exceptions
ArgumentNullException Throw if the string array is null.
ArgumentOutOfRangeException Throw if there are no items in the string array.
updateVectorPrice()
void Wombat.MamaMsg.updateVectorPrice (string name, ushort fid, MamaPrice [] val)
Update an array of prices.
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
val The array of messages to add.
Exceptions
ArgumentNullException Throw if the message array is null.
ArgumentOutOfRangeException Throw if there are no items in the message array.
updateVectorMsg()
void Wombat.MamaMsg.updateVectorMsg (string name, ushort fid, MamaMsg [] val)
Update an array of nativeHandle objects.
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
val The array of messages to add.
Exceptions
ArgumentNullException Throw if the message array is null.
ArgumentOutOfRangeException Throw if there are no items in the message array.
References Wombat.MamaWrapper.nativeHandle.
tryVectorString() [2/2]
bool Wombat.MamaMsg.tryVectorString (string name, ushort fid, ref string [] result)
Try to get a vector of strings (char*).
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
result To return the array of strings.
Returns
false if the field could not be found. Note that true is returned if an empty array is returned.
tryVectorPrice() [2/2]
bool Wombat.MamaMsg.tryVectorPrice (string name, ushort fid, ref MamaPrice [] result)
Try to get a vector of prices.
Parameters
fid The field id, can be 0 if the name is specified and field names are turned on.
name The field name, can be null or blank if the field Id is supplied.
result To return the array of prices.
Returns
false if the field could not be found. Note that true is returned if an empty array is returned.
Property Documentation
isFromInbox
bool Wombat.MamaMsg.isFromInbox get