OpenMAMA C# API: Wombat.MamaFieldDescriptor Class Reference
Wombat.MamaFieldDescriptor Class Reference
A class that describes a field in a MamaMsg
Inherits Wombat.MamaWrapper.
Public Member Functions
MamaFieldDescriptor (int fid, mamaFieldType type, string name, bool trackModState)
MamaFieldDescriptor (int fid, mamaFieldType type, string name)
void destroy ()
Destroy a MamaFieldDescriptor
string getName ()
Return the human readable name of the field.
int getFid ()
Return the field identifier
mamaFieldType getType ()
Return the data type
string getTypeName ()
Return a human readable string for mamaMsgType
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Properties
bool trackModState [get, set]
Track the modification state
object closure [get, set]
User-supplied data that is associated with the field descriptor
string pubName [get, set]
Publish name for the field
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
A class that describes a field in a MamaMsg
Constructor & Destructor Documentation
MamaFieldDescriptor() [1/2]
Wombat.MamaFieldDescriptor.MamaFieldDescriptor (int fid, mamaFieldType type, string name, bool trackModState)
References Wombat.MamaWrapper.nativeHandle, and Wombat.MamaFieldDescriptor.trackModState.
MamaFieldDescriptor() [2/2]
Wombat.MamaFieldDescriptor.MamaFieldDescriptor (int fid, mamaFieldType type, string name)
Member Function Documentation
destroy()
void Wombat.MamaFieldDescriptor.destroy ()
Destroy a MamaFieldDescriptor
References Wombat.MamaWrapper.Dispose().
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaFieldDescriptor.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object
Implements Wombat.MamaWrapper.
References Wombat.MamaWrapper.nativeHandle.
getName()
string Wombat.MamaFieldDescriptor.getName ()
Return the human readable name of the field.
References Wombat.MamaWrapper.nativeHandle.
Referenced by Wombat.MamaMsg.getU16().
getFid()
int Wombat.MamaFieldDescriptor.getFid ()
Return the field identifier
References Wombat.MamaWrapper.nativeHandle.
Referenced by Wombat.MamaMsg.getBool(), Wombat.MamaMsg.getChar(), Wombat.MamaMsg.getDateTime(), Wombat.MamaMsg.getF32(), Wombat.MamaMsg.getF64(), Wombat.MamaMsg.getField(), Wombat.MamaMsg.getI16(), Wombat.MamaMsg.getI32(), Wombat.MamaMsg.getI64(), Wombat.MamaMsg.getI8(), Wombat.MamaMsg.getMsg(), Wombat.MamaMsg.getOpaque(), Wombat.MamaMsg.getPrice(), Wombat.MamaMsg.getStatus(), Wombat.MamaMsg.getString(), Wombat.MamaMsg.getU16(), Wombat.MamaMsg.getU32(), Wombat.MamaMsg.getU64(), Wombat.MamaMsg.getU8(), Wombat.MamaMsg.getVectorBool(), Wombat.MamaMsg.getVectorChar(), Wombat.MamaMsg.getVectorDateTime(), Wombat.MamaMsg.getVectorF32(), Wombat.MamaMsg.getVectorF64(), Wombat.MamaMsg.getVectorI16(), Wombat.MamaMsg.getVectorI32(), Wombat.MamaMsg.getVectorI64(), Wombat.MamaMsg.getVectorI8(), Wombat.MamaMsg.getVectorMsg(), Wombat.MamaMsg.getVectorPrice(), Wombat.MamaMsg.getVectorString(), Wombat.MamaMsg.getVectorU16(), Wombat.MamaMsg.getVectorU32(), Wombat.MamaMsg.getVectorU64(), Wombat.MamaMsg.getVectorU8(), Wombat.MamaMsg.tryBool(), Wombat.MamaMsg.tryChar(), Wombat.MamaMsg.tryDateTime(), Wombat.MamaMsg.tryF32(), Wombat.MamaMsg.tryF64(), Wombat.MamaMsg.tryField(), Wombat.MamaMsg.tryI16(), Wombat.MamaMsg.tryI32(), Wombat.MamaMsg.tryI64(), Wombat.MamaMsg.tryI8(), Wombat.MamaMsg.tryMsg(), Wombat.MamaMsg.tryOpaque(), Wombat.MamaMsg.tryPrice(), Wombat.MamaMsg.tryString(), Wombat.MamaMsg.tryStringAnsi(), Wombat.MamaMsg.tryU16(), Wombat.MamaMsg.tryU32(), Wombat.MamaMsg.tryU64(), Wombat.MamaMsg.tryU8(), Wombat.MamaMsg.tryVectorBool(), Wombat.MamaMsg.tryVectorChar(), Wombat.MamaMsg.tryVectorDateTime(), Wombat.MamaMsg.tryVectorF32(), Wombat.MamaMsg.tryVectorF64(), Wombat.MamaMsg.tryVectorI16(), Wombat.MamaMsg.tryVectorI32(), Wombat.MamaMsg.tryVectorI64(), Wombat.MamaMsg.tryVectorI8(), Wombat.MamaMsg.tryVectorMsg(), Wombat.MamaMsg.tryVectorPrice(), Wombat.MamaMsg.tryVectorString(), Wombat.MamaMsg.tryVectorU16(), Wombat.MamaMsg.tryVectorU32(), Wombat.MamaMsg.tryVectorU64(), and Wombat.MamaMsg.tryVectorU8().
getType()
mamaFieldType Wombat.MamaFieldDescriptor.getType ()
Return the data type
References Wombat.MamaWrapper.nativeHandle.
getTypeName()
string Wombat.MamaFieldDescriptor.getTypeName ()
Return a human readable string for mamaMsgType
References Wombat.MamaWrapper.nativeHandle, and Wombat.MamaFieldDescriptor.trackModState.
Property Documentation
trackModState
bool Wombat.MamaFieldDescriptor.trackModState get set
Track the modification state
Referenced by Wombat.MamaFieldDescriptor.getTypeName(), and Wombat.MamaFieldDescriptor.MamaFieldDescriptor().
closure
object Wombat.MamaFieldDescriptor.closure get set
User-supplied data that is associated with the field descriptor
pubName
string Wombat.MamaFieldDescriptor.pubName get set
Publish name for the field