OpenMAMA C# API: Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl Class Reference
Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl Class Reference
This impl will perform the work of invoking user supplied callbacks, it is held to ensure that the user can destroy and recreate the parent subscription during the callbacks.
Protected Member Functions
MamaBasicSubscriptionImpl ()
Default constructor for internal use.
Detailed Description
This impl will perform the work of invoking user supplied callbacks, it is held to ensure that the user can destroy and recreate the parent subscription during the callbacks.
Constructor & Destructor Documentation
MamaBasicSubscriptionImpl()
Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl () protected
Default constructor for internal use.
References Wombat.MamaWrapper.nativeHandle, Wombat.MamaBasicSubscriptionCallback.onCreate(), Wombat.MamaBasicSubscriptionCallback.onDestroy(), Wombat.MamaBasicSubscriptionCallback.onError(), Wombat.MamaBasicSubscriptionCallback.onMsg(), Wombat.MamaBasicSubscription.OnSubscriptionCreateDelegate(), Wombat.MamaBasicSubscription.OnSubscriptionDestroyDelegate(), Wombat.MamaBasicSubscription.OnSubscriptionErrorDelegate(), Wombat.MamaBasicSubscription.OnSubscriptionGapDelegate(), Wombat.MamaBasicSubscription.OnSubscriptionMessageDelegate(), Wombat.MamaBasicSubscription.OnSubscriptionQualityDelegate(), Wombat.MamaBasicSubscription.OnSubscriptionRecapRequestDelegate(), and Wombat.MamaWrapper.setNativeHandle().