OpenMAMA C# API: Wombat.MamaIo Class Reference
Wombat.MamaIo Class Reference
I/O handler
Inherits Wombat.MamaWrapper.
Public Member Functions
MamaIo ()
M:Wombat.MamaWrapper.::ctor
void create (MamaQueue queue, MamaIoCallback action, uint descriptor, mamaIoType ioType, object closure)
Create an IO handler.
void create (MamaQueue queue, MamaIoCallback action, uint descriptor, mamaIoType ioType)
create(MamaQueue, MamaIoCallback, uint, mamaIoType, System.Object)
void create (MamaQueue queue, MamaIoCallback action, long descriptor, mamaIoType ioType, object closure)
CLS compliant version of create create(MamaQueue, MamaIoCallback, uint, mamaIoType, System.Object)
void create (MamaQueue queue, MamaIoCallback action, long descriptor, mamaIoType ioType)
CLS compliant version of create create(MamaQueue, MamaIoCallback, uint, mamaIoType, System.Object)
void destroy ()
Destroy the IO.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object.
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Properties
uint descriptor [get]
Get the descriptor.
long descriptorClsCompliant [get]
CLS compliant version of descriptor
object closure [get]
Return the closure for the IO.
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
I/O handler
Constructor & Destructor Documentation
MamaIo()
Wombat.MamaIo.MamaIo ()
M:Wombat.MamaWrapper.::ctor
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaIo.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object.
See also
MamaWrapper.DestroyNativePeer
Implements Wombat.MamaWrapper.
create() [1/4]
void Wombat.MamaIo.create (MamaQueue queue, MamaIoCallback action, uint descriptor, mamaIoType ioType, object closure)
Create an IO handler.
If the underlying infrastructure does not support the requested mamaIoType, create throws MamaException(MAMA_STATUS_UNSUPPORTED_IO_TYPE). For example, RV only supports READ, WRITE, and EXCEPT. LBM supports all types except ERROR
Parameters
queue The event queue for the io events. null specifies the Mama default queue
action The callback to be invoked when an event occurs.
descriptor Wait for IO on this descriptor.
ioType Wait for occurences of this type.
closure The closure that is passed to the callback.
References Wombat.MamaIo.closure.
Referenced by Wombat.MamaIo.create().
create() [2/4]
void Wombat.MamaIo.create (MamaQueue queue, MamaIoCallback action, uint descriptor, mamaIoType ioType)
create(MamaQueue, MamaIoCallback, uint, mamaIoType, System.Object)
References Wombat.MamaIo.create().
create() [3/4]
void Wombat.MamaIo.create (MamaQueue queue, MamaIoCallback action, long descriptor, mamaIoType ioType, object closure)
CLS compliant version of create create(MamaQueue, MamaIoCallback, uint, mamaIoType, System.Object)
References Wombat.MamaIo.create().
create() [4/4]
void Wombat.MamaIo.create (MamaQueue queue, MamaIoCallback action, long descriptor, mamaIoType ioType)
CLS compliant version of create create(MamaQueue, MamaIoCallback, uint, mamaIoType, System.Object)
References Wombat.MamaIo.create(), and Wombat.MamaIo.descriptor.
destroy()
void Wombat.MamaIo.destroy ()
Destroy the IO.
A synonym to the MamaWrapper.Dispose method.
References Wombat.MamaIo.closure, and Wombat.MamaWrapper.Dispose().
Property Documentation
descriptor
uint Wombat.MamaIo.descriptor get
Get the descriptor.
Referenced by Wombat.MamaIo.create().
descriptorClsCompliant
long Wombat.MamaIo.descriptorClsCompliant get
CLS compliant version of descriptor
closure
object Wombat.MamaIo.closure get
Return the closure for the IO.
Referenced by Wombat.MamaIo.create(), and Wombat.MamaIo.destroy().