OpenMAMA C# API: Wombat.MamaTransport Class Reference
Wombat.MamaTransport Class Reference
The underpinning object in any MAMA application
Inherits Wombat.MamaWrapper.
Public Types
enum MamaThrottleInstance { MamaThrottleInstance.MAMA_THROTTLE_DEFAULT = 0, MamaThrottleInstance.MAMA_THROTTLE_INITIAL = 1, MamaThrottleInstance.MAMA_THROTTLE_RECAP = 2 }
Enum to determine to which throttle a call applies.
enum MamaQuality : int {
MamaQuality.MAMA_QUALITY_OK = 0, MamaQuality.MAMA_QUALITY_MAYBE_STALE = 1, MamaQuality.MAMA_QUALITY_STALE = 2, MamaQuality.MAMA_QUALITY_PARTIAL_STALE = 3,
MamaQuality.MAMA_QUALITY_FORCED_STALE = 4, MamaQuality.MAMA_QUALITY_DUPLICATE = 5, MamaQuality.MAMA_QUALITY_UNKNOWN = 99
}
Enum to specify the Quality value supplied by the onQuality callback.
Public Member Functions
MamaTransport ()
Allocate a transport structure.
IntPtr getNativeTransport ()
void create (string name, MamaBridge bridgeImpl)
Create a previously allocated transport.
double getOutboundThrottle (MamaThrottleInstance instance)
Get the outbound throttle rate.
void setOutboundThrottle (MamaThrottleInstance instance, double outboundThrottle)
Set the throttle rate.
void setSymbolMapFunc (MamaSymbolMapCallback callback, object closure)
Set the symbol mapping function for a MamaTransport.
MamaSymbolMapCallback getSymbolMapFunc ()
Return the symbol mapping function for a MamaTransport.
object getSymbolMapFuncClosure ()
Return the symbol mapping function closure for a MamaTransport.
void requestConflation ()
Request conflation for a MamaTransport.
void requestEndConflation ()
Request an end to conflation for a MamaTransport.
void destroy ()
void setTransportCallback (MamaTransportCallback callback)
Set the transport callback.
void setTransportTopicCallback (MamaTransportTopicCallback callback)
Set the transport topic callback.
string getName ()
Get the name of the transport.
void setTransportCallbackQueue (MamaQueue queue)
Set a queue for transport callbacks (transport and topic).
MamaQueue getTransportCallbackQueue ()
Set a queue for transport callbacks (transport and topic).
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override void OnDispose ()
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
Properties
MamaQuality Quality [get]
Accessor methods for the quality associated with a MamaTransport.
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
The underpinning object in any MAMA application
The mamaTransport defines the network protocol level parameters over which MAMA distributes data. Transports effectively provide scope for data identifying the underlying protocols and their values for data delivery. It is an isolated communication channel for data traffic. Transports specify the communication channels to use for making subscriptions and publishing data through the API.
Member Enumeration Documentation
MamaThrottleInstance
enum Wombat.MamaTransport.MamaThrottleInstance strong
Enum to determine to which throttle a call applies.
Currently, the the default throttle, used by the publisher, and the initial value request throttle are the same. Mama sends recap requests on a separate throttle.
Enumerator
MAMA_THROTTLE_DEFAULT
MAMA_THROTTLE_INITIAL
MAMA_THROTTLE_RECAP
MamaQuality
enum Wombat.MamaTransport.MamaQuality : int strong
Enum to specify the Quality value supplied by the onQuality callback.
Enumerator
MAMA_QUALITY_OK
MAMA_QUALITY_MAYBE_STALE
MAMA_QUALITY_STALE
MAMA_QUALITY_PARTIAL_STALE
MAMA_QUALITY_FORCED_STALE
MAMA_QUALITY_DUPLICATE
MAMA_QUALITY_UNKNOWN
Constructor & Destructor Documentation
MamaTransport()
Wombat.MamaTransport.MamaTransport ()
Allocate a transport structure.
You need to call destroy() when the class is no more needed The transport is not created until create() is called. Any transport properties should be set prior to calling create()
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
getNativeTransport()
IntPtr Wombat.MamaTransport.getNativeTransport ()
References Wombat.MamaWrapper.nativeHandle.
create()
void Wombat.MamaTransport.create (string name, MamaBridge bridgeImpl)
Create a previously allocated transport.
Platform specific parameters are read from the properties file mama.properties. The properties file is located in the WOMBAT_PATH directory. The parameters are dependent on the underlying messaging transport. TIBRV transports support the following: mama.tibrv.transport.name.service, mama.tibrv.transport.name.network, and mama.tibrv.transport.name.daemon. These correspond to the parameters for tibrvTransport_Create(). LBM: See the example mama.properties supplied with the release.
Parameters
name
bridgeImpl
References Wombat.MamaWrapper.nativeHandle.
getOutboundThrottle()
double Wombat.MamaTransport.getOutboundThrottle (MamaThrottleInstance instance)
Get the outbound throttle rate.
This the rate at which the transport sends outbound messages to the feed handlers. It is also the rate at which new subscriptions are created. Its purpose is to avoid flooding the network with requests.
References Wombat.MamaWrapper.nativeHandle.
setOutboundThrottle()
void Wombat.MamaTransport.setOutboundThrottle (MamaThrottleInstance instance, double outboundThrottle)
Set the throttle rate.
References Wombat.MamaWrapper.nativeHandle.
setSymbolMapFunc()
void Wombat.MamaTransport.setSymbolMapFunc (MamaSymbolMapCallback callback, object closure)
Set the symbol mapping function for a MamaTransport.
Parameters
callback
closure
References Wombat.MamaWrapper.nativeHandle.
getSymbolMapFunc()
MamaSymbolMapCallback Wombat.MamaTransport.getSymbolMapFunc ()
Return the symbol mapping function for a MamaTransport.
getSymbolMapFuncClosure()
object Wombat.MamaTransport.getSymbolMapFuncClosure ()
Return the symbol mapping function closure for a MamaTransport.
References Wombat.MamaTransport.Quality.
requestConflation()
void Wombat.MamaTransport.requestConflation ()
Request conflation for a MamaTransport.
Currently only available for WMW.
References Wombat.MamaWrapper.nativeHandle.
requestEndConflation()
void Wombat.MamaTransport.requestEndConflation ()
Request an end to conflation for a MamaTransport.
Currently only available for WMW.
References Wombat.MamaWrapper.nativeHandle.
OnDispose()
override void Wombat.MamaTransport.OnDispose () protected virtual
Reimplemented from Wombat.MamaWrapper.
References Wombat.MamaWrapper.nativeHandle, and Wombat.MamaTransport.setTransportCallback().
destroy()
void Wombat.MamaTransport.destroy ()
References Wombat.MamaWrapper.Dispose().
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaTransport.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Returns
MAMA Status code
Implements Wombat.MamaWrapper.
References Wombat.MamaWrapper.nativeHandle.
setTransportCallback()
void Wombat.MamaTransport.setTransportCallback (MamaTransportCallback callback)
Set the transport callback.
It receives advisories when a transport disconnects or reconnects. Passing NULL removes the callback.
Parameters
callback
References Wombat.MamaWrapper.nativeHandle.
Referenced by Wombat.MamaTransport.OnDispose().
setTransportTopicCallback()
void Wombat.MamaTransport.setTransportTopicCallback (MamaTransportTopicCallback callback)
Set the transport topic callback.
It receives advisories when subjects sub or unsub, or when publisher events occur. Passing NULL removes the callback.
Parameters
callback
References Wombat.MamaWrapper.nativeHandle.
getName()
string Wombat.MamaTransport.getName ()
Get the name of the transport.
References Wombat.MamaWrapper.nativeHandle.
setTransportCallbackQueue()
void Wombat.MamaTransport.setTransportCallbackQueue (MamaQueue queue)
Set a queue for transport callbacks (transport and topic).
If this is not set the default queue will be used.
References Wombat.MamaWrapper.nativeHandle.
getTransportCallbackQueue()
MamaQueue Wombat.MamaTransport.getTransportCallbackQueue ()
Set a queue for transport callbacks (transport and topic).
If this is not set the default queue will be used.
References Wombat.Mama.DllName, Wombat.MamaWrapper.nativeHandle, Wombat.MamaTransportCallback.onAcceptConnect(), Wombat.MamaTransportCallback.onAcceptReconnect(), Wombat.MamaTransportCallback.onConnect(), Wombat.MamaTransportCallback.onDisconnect(), Wombat.MamaTransportCallback.onNamingServiceConnect(), Wombat.MamaTransportCallback.onNamingServiceDisconnect(), Wombat.MamaTransportCallback.onPublisherDisconnect(), Wombat.MamaTransportCallback.onQuality(), Wombat.MamaTransportCallback.onReconnect(), Wombat.MamaTransportTopicCallback.onTopicPublishError(), Wombat.MamaTransportTopicCallback.onTopicPublishErrorBadSymbol(), Wombat.MamaTransportTopicCallback.onTopicPublishErrorNotEntitled(), Wombat.MamaTransportTopicCallback.onTopicSubscribe(), Wombat.MamaTransportTopicCallback.onTopicUnsubscribe(), and Wombat.MamaSymbolMapCallback.SymbolMapFunc().
Property Documentation
Quality
MamaQuality Wombat.MamaTransport.Quality get
Accessor methods for the quality associated with a MamaTransport.
Referenced by Wombat.MamaTransport.getSymbolMapFuncClosure().