OpenMAMA C# API: Wombat.MamaBasicSubscription Class Reference
Wombat.MamaBasicSubscription Class Reference
The basic subscription supports publish / subscribe.
Inherits Wombat.MamaWrapper.
Inherited by Wombat.MamaSubscription.
Classes
class MamaBasicSubscriptionImpl
This impl will perform the work of invoking user supplied callbacks, it is held to ensure that the user can destroy and recreate the parent subscription during the callbacks.
struct NativeMethods
Public Member Functions
MamaBasicSubscription ()
Constructor constructs a new basic subscription including creating the underlying native subscription.
void createBasic (MamaTransport transport, MamaQueue queue, MamaBasicSubscriptionCallback callback, string symbol)
This function will create the basic subscription without marketdata semantics.
void createBasic (MamaTransport transport, MamaQueue queue, MamaBasicSubscriptionCallback callback, string symbol, object closure)
This function will create the basic subscription without marketdata semantics.
void deallocate ()
Free the memory for a mamaSubscription which was allocated via a call to constructor.
void destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
void destroyEx ()
Destroy the subscription.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
delegate void OnSubscriptionCreateDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes that native callback function that is invoked whenever the subscription has been created.
delegate void OnSubscriptionDestroyDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes the native function invoked whenever the subscription has been either destroyed or deactivated.
delegate void OnSubscriptionErrorDelegate (IntPtr nativeHandle, int status, IntPtr platformError, string subject, IntPtr closure)
This delegate describes the native function invoked if an error occurs during prior to subscription creation or if the subscription receives a message for an un-entitled subject.
delegate void OnSubscriptionGapDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes the native function invoked when a sequence number gap is detected.
delegate void OnSubscriptionMessageDelegate (IntPtr nativeHandle, IntPtr msg, IntPtr closure, IntPtr itemClosure)
This delegate describes the native function that is invoked whenever a message arrives.
delegate void OnSubscriptionQualityDelegate (IntPtr nativeHandle, int quality, string symbol, short cause, string platforminfo, IntPtr closure)
This delegate describes the native function invoked to indicate a data quality event.
delegate void OnSubscriptionRecapRequestDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes the native function invoked when a recap is requested upon detecting a sequence number gap.
override MamaStatus.mamaStatus DestroyNativePeer ()
This will be called by the base class to de-allocate the native subscription.
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Protected Attributes
object mClosure
The closure passed to the create function.
MamaQueue mQueue
The queue passed to the create function.
MamaTransport mTransport
The transport passed to the create function.
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Static Protected Attributes
static NativeMethods.SubscriptionCallbacks mCallbackDelegates
This structure holds all of the callback delegates, it is initialised in the static constructor.
Properties
mamaSubscriptionState State [get]
This read only property returns the current state of the subscription, this function should be used in preference to the mamaSubscription_isActive or mamaSubscription_isValid functions.
object subscClosure [get]
Read only property returns the closure passed to the create function.
MamaQueue subscQueue [get]
Read only property returns the queue.
string subscSymbol [get]
Read only property returns the symbol for this subscription.
Detailed Description
The basic subscription supports publish / subscribe.
This class can be disposed or the deallocate function called to reduce time during finalization. Note that the deallocate function will attempt to destroy the subscription if this has not already been done whereas dispose will only de-allocate the memory.
Constructor & Destructor Documentation
MamaBasicSubscription()
Wombat.MamaBasicSubscription.MamaBasicSubscription ()
Constructor constructs a new basic subscription including creating the underlying native subscription.
References Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_allocate().
Member Function Documentation
OnSubscriptionCreateDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionCreateDelegate (IntPtr nativeHandle, IntPtr closure) protected
This delegate describes that native callback function that is invoked whenever the subscription has been created.
Parameters
nativeHandle The native subscription.
closure The native closure passed to the create function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
OnSubscriptionDestroyDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionDestroyDelegate (IntPtr nativeHandle, IntPtr closure) protected
This delegate describes the native function invoked whenever the subscription has been either destroyed or deactivated.
Parameters
nativeHandle The native subscription.
closure The native closure passed to the create function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
OnSubscriptionErrorDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionErrorDelegate (IntPtr nativeHandle, int status, IntPtr platformError, string subject, IntPtr closure) protected
This delegate describes the native function invoked if an error occurs during prior to subscription creation or if the subscription receives a message for an un-entitled subject.
If the status is MAMA_MSG_STATUS_NOT_ENTITTLED the subject parameter is the specific unentitled subject. If the subscription subject contains wildcards, the subscription may still receive messages for other entitled subjects. Note wildcard subscriptions are not supported on all platforms.
Parameters
nativeHandle The native subscription.
status The associated error code.
platformError Platform specific error information.
subject The subject for NOT_ENTITLED errors.
closure The native closure passed to the create function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
OnSubscriptionGapDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionGapDelegate (IntPtr nativeHandle, IntPtr closure) protected
This delegate describes the native function invoked when a sequence number gap is detected.
At this point the topic is considered stale and the subscription will not receive further messages until the feed handler satisfies a recap request.
Parameters
nativeHandle The native subscription.
closure The native closure passed to the create function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
OnSubscriptionMessageDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionMessageDelegate (IntPtr nativeHandle, IntPtr msg, IntPtr closure, IntPtr itemClosure) protected
This delegate describes the native function that is invoked whenever a message arrives.
Parameters
nativeHandle The native subscription.
msg The native mama message.
closure The native closure passed to the create function.
itemClosure The item closure for the subscription can be set with setItemClosure, note that setItemClosure is not provided in the C# implementation.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
OnSubscriptionQualityDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionQualityDelegate (IntPtr nativeHandle, int quality, string symbol, short cause, string platforminfo, IntPtr closure) protected
This delegate describes the native function invoked to indicate a data quality event.
Parameters
nativeHandle The native subscription.
quality The new quality.
symbol The symbol.
cause The cause of the data quality event.
platforminfo Info associated with the data quality event.
closure The native closure passed to the create function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
OnSubscriptionRecapRequestDelegate()
delegate void Wombat.MamaBasicSubscription.OnSubscriptionRecapRequestDelegate (IntPtr nativeHandle, IntPtr closure) protected
This delegate describes the native function invoked when a recap is requested upon detecting a sequence number gap.
Parameters
nativeHandle The native subscription.
closure The native closure passed to the create function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaBasicSubscription.DestroyNativePeer () protected virtual
This will be called by the base class to de-allocate the native subscription.
See also
MamaWrapper.DestroyNativePeer
Returns
MAMA Status code.
Implements Wombat.MamaWrapper.
References Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_deallocate().
createBasic() [1/2]
void Wombat.MamaBasicSubscription.createBasic (MamaTransport transport, MamaQueue queue, MamaBasicSubscriptionCallback callback, string symbol)
This function will create the basic subscription without marketdata semantics.
To pass a closure use the overload.
Parameters
transport The MamaTransport.
queue The MamaQueue.
callback Provide callback function implementations to be informed of events on the subscription.
symbol The symbol to subscribe to.
createBasic() [2/2]
void Wombat.MamaBasicSubscription.createBasic (MamaTransport transport, MamaQueue queue, MamaBasicSubscriptionCallback callback, string symbol, object closure)
This function will create the basic subscription without marketdata semantics.
Parameters
transport The MamaTransport.
queue The MamaQueue.
callback Provide callback function implementations to be informed of events on the subscription.
symbol The symbol to subscribe to.
closure The closure that will be passed back with the callback functions.
References Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_createBasic(), and Wombat.MamaBasicSubscription.mCallbackDelegates.
deallocate()
void Wombat.MamaBasicSubscription.deallocate ()
Free the memory for a mamaSubscription which was allocated via a call to constructor.
This function will call destroy() if the subscription has not already been destroyed. Calling this function will reduce time during finalization.
References Wombat.MamaWrapper.Dispose().
destroy()
void Wombat.MamaBasicSubscription.destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
Use destroyEx to destroy the subscription from any thread. Note that the subscription will not be fully destroyed until the onDestroy callback is received.
References Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_destroy().
destroyEx()
void Wombat.MamaBasicSubscription.destroyEx ()
Destroy the subscription.
This function is another option to destroy the resources associated with the subscription It will schedule the destroy() of the subscription on the queue on which it dispatches. This function does not free the memory associated with the subscription. create() can be called again after this function has been called. After the Subscription is effectively destroyed, the OnDestroy callback will be triggered for it.
This function can be called from any thread, as opposed to destroy().
References Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_destroyEx(), and Wombat.MamaBasicSubscription.State.
Member Data Documentation
mClosure
object Wombat.MamaBasicSubscription.mClosure protected
The closure passed to the create function.
This member is declared as protected as there is a public read only property to access it.
mQueue
MamaQueue Wombat.MamaBasicSubscription.mQueue protected
The queue passed to the create function.
This member is declared as protected as there is a public read only property to access it.
mTransport
MamaTransport Wombat.MamaBasicSubscription.mTransport protected
The transport passed to the create function.
This member is declared as protected as there is a public read only property to access it.
mCallbackDelegates
NativeMethods.SubscriptionCallbacks Wombat.MamaBasicSubscription.mCallbackDelegates static protected
This structure holds all of the callback delegates, it is initialised in the static constructor.
Referenced by Wombat.MamaBasicSubscription.createBasic(), and Wombat.MamaSubscription.setup().
Property Documentation
State
mamaSubscriptionState Wombat.MamaBasicSubscription.State get
This read only property returns the current state of the subscription, this function should be used in preference to the mamaSubscription_isActive or mamaSubscription_isValid functions.
function is thread-safe. The state will be one of the mamaSubscriptionState enumeration values.
Referenced by Wombat.MamaBasicSubscription.destroyEx().
subscClosure
object Wombat.MamaBasicSubscription.subscClosure get
Read only property returns the closure passed to the create function.
subscQueue
MamaQueue Wombat.MamaBasicSubscription.subscQueue get
Read only property returns the queue.
subscSymbol
string Wombat.MamaBasicSubscription.subscSymbol get
Read only property returns the symbol for this subscription.