OpenMAMA C# API: Wombat.MamaPublisher Class Reference
Wombat.MamaPublisher Class Reference
The MamaPublisher class publishes messages to basic or market data subscriptions depending on the underlying transport
Inherits Wombat.MamaWrapper.
Public Member Functions
MamaPublisher ()
M:Wombat.MamaWrapper.::ctor
void create (MamaTransport transport, string topic, string source, string root)
Create a mama publisher for the corresponding transport.
void createWithCallbacks (MamaTransport transport, MamaQueue queue, MamaPublisherCallback callback, Object closure, string topic, string source, string root)
Create a mama publisher for the corresponding transport.
void create (MamaTransport transport, string topic, string source)
Create a mama publisher for the corresponding transport.
void create (MamaTransport transport, string topic)
Create a mama publisher for the corresponding transport.
void send (MamaMsg message)
Send a message from the specified publisher.
void sendWithThrottle (MamaMsg message, MamaSendCompleteCallback callback, object closure)
Send a message with the throttle.
void sendFromInbox (MamaInbox inbox, MamaMsg message)
Send a p2p message from the specified inbox using the throttle.
void sendFromInboxWithThrottle (MamaInbox inbox, MamaMsg message, MamaSendCompleteCallback callback, object closure)
Send a p2p message from the specified inbox using the throttle.
void sendReplyToInbox (MamaMsg request, MamaMsg reply)
Send a reply in response to a request to an inbox.
void destroy ()
Destroy the publisher.
MamaTransport getTransport ()
Get the MamaTransport.
string getRoot ()
Get the name of the transport.
string getSource ()
Get the name of the transport.
string getSymbol ()
Get the name of the transport.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void OnDispose ()
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
The MamaPublisher class publishes messages to basic or market data subscriptions depending on the underlying transport
Constructor & Destructor Documentation
MamaPublisher()
Wombat.MamaPublisher.MamaPublisher ()
M:Wombat.MamaWrapper.::ctor
References Wombat.MamaWrapper.nativeHandle.
Referenced by Wombat.MamaPublisher.getSymbol().
Member Function Documentation
Dispose()
override void Wombat.MamaPublisher.Dispose (bool disposing, bool destroyNativeHandle = true) protected virtual
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
Parameters
disposing true if the object is being disposed (false if being finalized)
Reimplemented from Wombat.MamaWrapper.
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaPublisher.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Returns
MAMA Status code
Implements Wombat.MamaWrapper.
create() [1/3]
void Wombat.MamaPublisher.create (MamaTransport transport, string topic, string source, string root)
Create a mama publisher for the corresponding transport.
If the transport is a marketdata transport, as opposed to a "basic" transport, the topic corresponds to the symbol. For a basic transport, the source and root get ignored.
Parameters
transport The transport.
topic Symbol on which to publish.
source The source for market data publishers. (e.g. source.symbol)
root The root for market data publishers. Used internally.
Referenced by Wombat.MamaPublisher.create().
createWithCallbacks()
void Wombat.MamaPublisher.createWithCallbacks (MamaTransport transport, MamaQueue queue, MamaPublisherCallback callback, Object closure, string topic, string source, string root)
Create a mama publisher for the corresponding transport.
If the transport is a marketdata transport, as opposed to a "basic" transport, the topic corresponds to the symbol. For a basic transport, the source and root get ignored.
Parameters
transport The transport.
topic Symbol on which to publish.
source The source for market data publishers. (e.g. source.symbol)
root The root for market data publishers. Used internally.
create() [2/3]
void Wombat.MamaPublisher.create (MamaTransport transport, string topic, string source)
Create a mama publisher for the corresponding transport.
If the transport is a marketdata transport, as opposed to a "basic" transport, the topic corresponds to the symbol. For a basic transport, the source and root get ignored.
Parameters
transport The transport.
topic Symbol on which to publish.
source The source for market data publishers. (e.g. source.symbol)
References Wombat.MamaPublisher.create().
create() [3/3]
void Wombat.MamaPublisher.create (MamaTransport transport, string topic)
Create a mama publisher for the corresponding transport.
If the transport is a marketdata transport, as opposed to a "basic" transport, the topic corresponds to the symbol. For a basic transport, the source and root get ignored.
Parameters
transport The transport.
topic Symbol on which to publish.
References Wombat.MamaPublisher.create().
send()
void Wombat.MamaPublisher.send (MamaMsg message)
Send a message from the specified publisher.
Parameters
message The mamaMsg to send.
sendWithThrottle()
void Wombat.MamaPublisher.sendWithThrottle (MamaMsg message, MamaSendCompleteCallback callback, object closure)
Send a message with the throttle.
The lifecycle of the message sent is controlled by the user of the API. The callback indicates when the API is no longer using the message and can be destroyed/reused by the application.
Parameters
message The mamaMsg to send.
callback Callback invoked once the message has been send on the throttle
closure User supplied data returned in the send complete callback.
sendFromInbox()
void Wombat.MamaPublisher.sendFromInbox (MamaInbox inbox, MamaMsg message)
Send a p2p message from the specified inbox using the throttle.
Parameters
inbox The mamaInbox which will process any response to the sent message.
message The mamaMsg to send.
sendFromInboxWithThrottle()
void Wombat.MamaPublisher.sendFromInboxWithThrottle (MamaInbox inbox, MamaMsg message, MamaSendCompleteCallback callback, object closure)
Send a p2p message from the specified inbox using the throttle.
The lifecycle of the message sent is controlled by the user of the API. The callback indicates when the API is no longer using the message and can be destroyed/reused by the application.
Parameters
inbox The MamaInbox which will process any response to the sent message.
message The MamaMsg to send.
callback The callback which will be invoked when the message is sent from the throttle queue.
closure User supplied data returned when the callback is invoked.
sendReplyToInbox()
void Wombat.MamaPublisher.sendReplyToInbox (MamaMsg request, MamaMsg reply)
Send a reply in response to a request to an inbox.
Parameters
request The MamaMsg to which you are responding.
reply The MamaMsg to be sent as the reply.
destroy()
void Wombat.MamaPublisher.destroy ()
Destroy the publisher.
A synonym to the MamaWrapper.Dispose method.
References Wombat.MamaWrapper.Dispose(), Wombat.MamaSendCompleteCallback.onSendComplete(), and Wombat.MamaWrapper.setNativeHandle().
getTransport()
MamaTransport Wombat.MamaPublisher.getTransport ()
Get the MamaTransport.
The result contains the reusable MamaTransport object of the nativeHandle object. Applications calling this method will receive the same reusable object for repeated calls on same nativeHandle object.
References Wombat.MamaWrapper.setNativeHandle().
getRoot()
string Wombat.MamaPublisher.getRoot ()
Get the name of the transport.
getSource()
string Wombat.MamaPublisher.getSource ()
Get the name of the transport.
getSymbol()
string Wombat.MamaPublisher.getSymbol ()
Get the name of the transport.
References Wombat.Mama.log(), Wombat.MamaPublisher.MamaPublisher(), Wombat.MamaPublisherCallback.onCreate(), Wombat.MamaPublisherCallback.onDestroy(), Wombat.MamaPublisherCallback.onError(), and Wombat.MamaPublisherCallback.onSuccess().