OpenMAMA C# API: Wombat.MamaSource Class Reference
Wombat.MamaSource Class Reference
A MamaSource maintains information about a data source, including the quality of the data coming from that source
Inherits Wombat.MamaWrapper, and Wombat.ISourceManager.
Public Member Functions
MamaSource ()
Constructs and creates a new source object.
void destroy ()
Destroy the source.
void clear ()
Clear the source
MamaSource create (string name)
Implements ISourceManager.create
MamaSource findOrCreate (string name)
Implements ISourceManager.findOrCreate
MamaSource find (string name)
Implements ISourceManager.find
void add (MamaSource source)
Implements ISourceManager.add(MamaSource)
void add (string name, MamaSource source)
Implements ISourceManager.add(System.String, MamaSource)
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Properties
string id [get, set]
Gets or sets the ID of the source
string displayId [get, set]
Gets or sets the display ID of the source
string mappedId [get, set]
Gets or sets the mapped ID of the source The mapped ID is the ID that parent source mManager has mapped this source as.
mamaQuality quality [get, set]
Gets or sets the quality of the source
mamaSourceState state [get, set]
Gets or sets the state of the source
string stateAsString [get]
Get the stringified representation of the source state.
MamaSource parent [get, set]
Gets or sets the parent for the source.
string symbolNamespace [get, set]
Gets or sets the publisher specific source name for this source.
string transportName [get, set]
Gets or sets the name of the MamaTransport on which this describes a valid source of
MamaTransport transport [get, set]
Returns or associates a transport object with the source.
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
A MamaSource maintains information about a data source, including the quality of the data coming from that source
Constructor & Destructor Documentation
MamaSource()
Wombat.MamaSource.MamaSource ()
Constructs and creates a new source object.
See also
M:Wombat.MamaWrapper.::ctor
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaSource.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Returns
MAMA Status code
Implements Wombat.MamaWrapper.
destroy()
void Wombat.MamaSource.destroy ()
Destroy the source.
A synonym to the MamaWrapper.Dispose method.
References Wombat.MamaWrapper.Dispose().
clear()
void Wombat.MamaSource.clear ()
Clear the source
create()
MamaSource Wombat.MamaSource.create (string name)
Implements ISourceManager.create
Implements Wombat.ISourceManager.
References Wombat.MamaSourceManager.create().
findOrCreate()
MamaSource Wombat.MamaSource.findOrCreate (string name)
Implements ISourceManager.findOrCreate
Implements Wombat.ISourceManager.
References Wombat.MamaSourceManager.findOrCreate().
find()
MamaSource Wombat.MamaSource.find (string name)
Implements ISourceManager.find
Implements Wombat.ISourceManager.
References Wombat.MamaSourceManager.find().
add() [1/2]
void Wombat.MamaSource.add (MamaSource source)
Implements ISourceManager.add(MamaSource)
Implements Wombat.ISourceManager.
References Wombat.MamaSourceManager.add().
add() [2/2]
void Wombat.MamaSource.add (string name, MamaSource source)
Implements ISourceManager.add(System.String, MamaSource)
Implements Wombat.ISourceManager.
References Wombat.MamaSourceManager.add(), Wombat.Mama.DllName, Wombat.MamaSource.parent, Wombat.MamaSource.quality, Wombat.MamaSource.state, Wombat.MamaSource.symbolNamespace, Wombat.MamaSource.transport, and Wombat.MamaSource.transportName.
Property Documentation
id
string Wombat.MamaSource.id get set
Gets or sets the ID of the source
displayId
string Wombat.MamaSource.displayId get set
Gets or sets the display ID of the source
mappedId
string Wombat.MamaSource.mappedId get set
Gets or sets the mapped ID of the source The mapped ID is the ID that parent source mManager has mapped this source as.
quality
mamaQuality Wombat.MamaSource.quality get set
Gets or sets the quality of the source
Referenced by Wombat.MamaSource.add().
state
mamaSourceState Wombat.MamaSource.state get set
Gets or sets the state of the source
Referenced by Wombat.MamaSource.add().
stateAsString
string Wombat.MamaSource.stateAsString get
Get the stringified representation of the source state.
parent
MamaSource Wombat.MamaSource.parent get set
Gets or sets the parent for the source.
When the parent is set the source is added to the parent source mManager.
Referenced by Wombat.MamaSource.add().
symbolNamespace
string Wombat.MamaSource.symbolNamespace get set
Gets or sets the publisher specific source name for this source.
E.g. This could be "NASDAQ" for a UTP PAPA publisher.
Referenced by Wombat.MamaSource.add().
transportName
string Wombat.MamaSource.transportName get set
Gets or sets the name of the MamaTransport on which this describes a valid source of
Referenced by Wombat.MamaSource.add().
transport
MamaTransport Wombat.MamaSource.transport get set
Returns or associates a transport object with the source.
Referenced by Wombat.MamaSource.add(), and Wombat.MamaSubscription.setup().