OpenMAMA C# API: Wombat.MamaSubscription Class Reference
Wombat.MamaSubscription Class Reference
Subscription class, derives from a basic subscription.
Inherits Wombat.MamaBasicSubscription.
Public Member Functions
MamaSubscription ()
Allocate memory for a new subscription.
void activate ()
Activate a subscription that has been set up by calling the setup function.
void create (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol)
Set up and activate a subscriber using the throttle queue.
void create (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol, object closure)
Set up and activate a subscriber using the throttle queue.
void createBasic (MamaTransport transport, MamaQueue queue, MamaSubscriptionCallback callback, string symbol)
This function will create the basic subscription without marketdata semantics.
void createBasic (MamaTransport transport, MamaQueue queue, MamaSubscriptionCallback callback, string symbol, object closure)
This function will create the basic subscription without marketdata semantics.
void deactivate ()
Deactivate an active subscription.
int getPreInitialCacheSize ()
Return the initial value cache size.
bool getReceivedInitial ()
Whether an Initial has been received for the specified subscription.
void setPreInitialCacheSize (int cacheSize)
Set the number of messages to cache for each symbol before the initial value arrives.
void setRecoverGaps (bool recover)
If this flag is set then the subscription will attempt to recover from a sequence number gap.
void setRequiresInitial (bool requiresInitial)
Whether an initial value is required for the specified subscription.
void setRetries (int retries)
Set the number of retries when requesting recaps.
void setServiceLevel (mamaServiceLevel svcLevel)
Set the service level without any other options.
void setServiceLevel (mamaServiceLevel svcLevel, int serviceLevelOpt)
Set the service level and an passes an optional service level parameter.
void setSubscriptionType (mamaSubscriptionType type)
Set the subscription type for the subscription being created.
void setTimeout (double timeout)
Set the timeout for this subscription.
void setup (MamaQueue queue, MamaTransport transport, MamaSubscriptionCallback callback, string sourceName, string symbol, object closure)
Set the parameters for a subscription that may be actually activated later.
void setup (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol, object closure)
Set the parameters for a subscription that may be actually activated later.
void setup (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol)
Set the parameters for a subscription that may be actually activated later.
Public Member Functions inherited from Wombat.MamaBasicSubscription
MamaBasicSubscription ()
Constructor constructs a new basic subscription including creating the underlying native subscription.
void createBasic (MamaTransport transport, MamaQueue queue, MamaBasicSubscriptionCallback callback, string symbol)
This function will create the basic subscription without marketdata semantics.
void createBasic (MamaTransport transport, MamaQueue queue, MamaBasicSubscriptionCallback callback, string symbol, object closure)
This function will create the basic subscription without marketdata semantics.
void deallocate ()
Free the memory for a mamaSubscription which was allocated via a call to constructor.
void destroy ()
This function will destroy the subscription, it must be called from the same thread that is processing the queue for the subscription.
void destroyEx ()
Destroy the subscription.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Properties
string subscSource [get]
Read only property returns the subscription source.
Properties inherited from Wombat.MamaBasicSubscription
mamaSubscriptionState State [get]
This read only property returns the current state of the subscription, this function should be used in preference to the mamaSubscription_isActive or mamaSubscription_isValid functions.
object subscClosure [get]
Read only property returns the closure passed to the create function.
MamaQueue subscQueue [get]
Read only property returns the queue.
string subscSymbol [get]
Read only property returns the symbol for this subscription.
Additional Inherited Members
Protected Member Functions inherited from Wombat.MamaBasicSubscription
delegate void OnSubscriptionCreateDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes that native callback function that is invoked whenever the subscription has been created.
delegate void OnSubscriptionDestroyDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes the native function invoked whenever the subscription has been either destroyed or deactivated.
delegate void OnSubscriptionErrorDelegate (IntPtr nativeHandle, int status, IntPtr platformError, string subject, IntPtr closure)
This delegate describes the native function invoked if an error occurs during prior to subscription creation or if the subscription receives a message for an un-entitled subject.
delegate void OnSubscriptionGapDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes the native function invoked when a sequence number gap is detected.
delegate void OnSubscriptionMessageDelegate (IntPtr nativeHandle, IntPtr msg, IntPtr closure, IntPtr itemClosure)
This delegate describes the native function that is invoked whenever a message arrives.
delegate void OnSubscriptionQualityDelegate (IntPtr nativeHandle, int quality, string symbol, short cause, string platforminfo, IntPtr closure)
This delegate describes the native function invoked to indicate a data quality event.
delegate void OnSubscriptionRecapRequestDelegate (IntPtr nativeHandle, IntPtr closure)
This delegate describes the native function invoked when a recap is requested upon detecting a sequence number gap.
override MamaStatus.mamaStatus DestroyNativePeer ()
This will be called by the base class to de-allocate the native subscription.
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Protected Attributes inherited from Wombat.MamaBasicSubscription
object mClosure
The closure passed to the create function.
MamaQueue mQueue
The queue passed to the create function.
MamaTransport mTransport
The transport passed to the create function.
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Static Protected Attributes inherited from Wombat.MamaBasicSubscription
static NativeMethods.SubscriptionCallbacks mCallbackDelegates
This structure holds all of the callback delegates, it is initialised in the static constructor.
Detailed Description
Subscription class, derives from a basic subscription.
Constructor & Destructor Documentation
MamaSubscription()
Wombat.MamaSubscription.MamaSubscription ()
Allocate memory for a new subscription.
The subscription is not actually created until a call to one of the create() functions is made. Memory must be freed using the deallocate()
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
activate()
void Wombat.MamaSubscription.activate ()
Activate a subscription that has been set up by calling the setup function.
Subscription creation actually occurs on the throttle queue. An individual subscription cannot be assumed to be fully created until its onCreate callback has been successfully invoked. The subscription rate can be governed via the MamaTransport.setOutboundThrottle function. Any subscription properties should be set prior to calling this function.
Referenced by Wombat.MamaSubscription.create().
create() [1/2]
void Wombat.MamaSubscription.create (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol)
Set up and activate a subscriber using the throttle queue.
This method is equivalent to calling setup() followed by activate().
Parameters
queue The mama queue.
callback The callback.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol for the listener.
create() [2/2]
void Wombat.MamaSubscription.create (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol, object closure)
Set up and activate a subscriber using the throttle queue.
This method is equivalent to calling setup() followed by activate().
Parameters
queue The mama queue.
callback The callback.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol for the listener.
closure The caller supplied closure.
References Wombat.MamaSubscription.activate(), and Wombat.MamaSubscription.setup().
createBasic() [1/2]
void Wombat.MamaSubscription.createBasic (MamaTransport transport, MamaQueue queue, MamaSubscriptionCallback callback, string symbol)
This function will create the basic subscription without marketdata semantics.
To pass a closure use the overload. This overload provides access to the basic subscription with the MamaSubscriptionCallback rather than the MamaBasicSubscriptionCallback interface. Instantiating the base class directly will provide better performance.
Parameters
transport The MamaTransport.
queue The MamaQueue.
callback Provide callback function implementations to be informed of events on the subscription.
symbol The symbol to subscribe to.
createBasic() [2/2]
void Wombat.MamaSubscription.createBasic (MamaTransport transport, MamaQueue queue, MamaSubscriptionCallback callback, string symbol, object closure)
This function will create the basic subscription without marketdata semantics.
This overload provides access to the basic subscription with the MamaSubscriptionCallback rather than the MamaBasicSubscriptionCallback interface. Instantiating the base class directly will provide better performance.
Parameters
transport The MamaTransport.
queue The MamaQueue.
callback Provide callback function implementations to be informed of events on the subscription.
symbol The symbol to subscribe to.
closure The closure that will be passed back with the callback functions.
deactivate()
void Wombat.MamaSubscription.deactivate ()
Deactivate an active subscription.
The onDestroy callback will be invoked whenever the subscription has been fully deactivated.
getPreInitialCacheSize()
int Wombat.MamaSubscription.getPreInitialCacheSize ()
Return the initial value cache size.
Returns
The cache size.
getReceivedInitial()
bool Wombat.MamaSubscription.getReceivedInitial ()
Whether an Initial has been received for the specified subscription.
Returns true if initial has been received.
Returns
True if an initial has been received for this subscription.
setPreInitialCacheSize()
void Wombat.MamaSubscription.setPreInitialCacheSize (int cacheSize)
Set the number of messages to cache for each symbol before the initial value arrives.
This allows the subscription to recover when the initial value arrives late (after a subsequent trade or quote already arrived). For group subscription, a separate cache is used for each group member. The default is 10.
Parameters
cacheSize The cache size to set.
setRecoverGaps()
void Wombat.MamaSubscription.setRecoverGaps (bool recover)
If this flag is set then the subscription will attempt to recover from a sequence number gap.
Parameters
recover True to attempt recovery.
setRequiresInitial()
void Wombat.MamaSubscription.setRequiresInitial (bool requiresInitial)
Whether an initial value is required for the specified subscription.
This only applies to market data subscriptions and not to basic subscriptions. Default value of true indicating that initial values are required.
Parameters
requiresInitial True if the subscription requires an initial.
setRetries()
void Wombat.MamaSubscription.setRetries (int retries)
Set the number of retries when requesting recaps.
Parameters
retries The number of retries.
setServiceLevel() [1/2]
void Wombat.MamaSubscription.setServiceLevel (mamaServiceLevel svcLevel)
Set the service level without any other options.
This method must be invoked before create().
Parameters
svcLevel The service level to set.
setServiceLevel() [2/2]
void Wombat.MamaSubscription.setServiceLevel (mamaServiceLevel svcLevel, int serviceLevelOpt)
Set the service level and an passes an optional service level parameter.
This method must be invoked before create().
Parameters
svcLevel The service level to set.
serviceLevelOpt The service level options.
setSubscriptionType()
void Wombat.MamaSubscription.setSubscriptionType (mamaSubscriptionType type)
Set the subscription type for the subscription being created.
If not called the subscription type defaults to MAMA_SUBSC_TYPE_NORMAL. See mamaSubscriptionType enum for valid values.
Parameters
type The type to set.
setTimeout()
void Wombat.MamaSubscription.setTimeout (double timeout)
Set the timeout for this subscription.
The timeout is used for requesting recaps.
Parameters
timeout The timeout value in seconds.
setup() [1/3]
void Wombat.MamaSubscription.setup (MamaQueue queue, MamaTransport transport, MamaSubscriptionCallback callback, string sourceName, string symbol, object closure)
Set the parameters for a subscription that may be actually activated later.
Activate the subscription using MamaSubscription.activate().
Parameters
transport The MAMA transport.
queue The MAMA queue.
callback The callback interface.
sourceName The name of the source identifying the publisher for this symbol.
symbol The symbol for the listener.
closure The caller supplied closure.
References Wombat.MamaBasicSubscription.mCallbackDelegates.
Referenced by Wombat.MamaSubscription.create(), and Wombat.MamaSubscription.setup().
setup() [2/3]
void Wombat.MamaSubscription.setup (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol, object closure)
Set the parameters for a subscription that may be actually activated later.
Activate the subscription using MamaSubscription.activate().
Parameters
queue The mama queue.
callback The callback.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol for the listener.
closure The caller supplied closure.
References Wombat.MamaBasicSubscription.mCallbackDelegates, and Wombat.MamaSource.transport.
setup() [3/3]
void Wombat.MamaSubscription.setup (MamaQueue queue, MamaSubscriptionCallback callback, MamaSource source, string symbol)
Set the parameters for a subscription that may be actually activated later.
Activate the subscription using MamaSubscription.activate(). This overload passes a null value for the closure.
Parameters
queue The mama queue.
callback The callback.
source The MamaSource identifying the publisher for this symbol.
symbol The symbol for the listener.
References Wombat.MamaSubscription.setup(), and Wombat.MamaSubscription.subscSource.
Property Documentation
subscSource
string Wombat.MamaSubscription.subscSource get
Read only property returns the subscription source.
Referenced by Wombat.MamaSubscription.setup().