OpenMAMA C# API: Wombat.MamaQueueGroup Class Reference
Wombat.MamaQueueGroup Class Reference
A class for distributing events across multiple queues in a round robin fashion.
Inherits IDisposable.
Public Member Functions
MamaQueueGroup (MamaBridge bridgeImpl, int queueCount)
Construct a queue manager with given number of queues/threads
void destroy ()
Destroy the queue group and destroy all the queues without waiting, this is equivalent to disposing the class.
void destroyWait ()
Destroy the queue group and destroy all the queues waiting on each queue, this is equivalent to disposing the class.
void Dispose ()
Dispose managed and unmanaged resources.
void start ()
Start dispatching on all queues.
void stop ()
Stop dispatching on all queues.
MamaQueue getNextQueue ()
This function will return the next queue since it was called last or the first queue in the group if this is the first time that it has been called.
Detailed Description
A class for distributing events across multiple queues in a round robin fashion.
Constructor & Destructor Documentation
MamaQueueGroup()
Wombat.MamaQueueGroup.MamaQueueGroup (MamaBridge bridgeImpl, int queueCount)
Construct a queue manager with given number of queues/threads
Parameters
bridgeImpl The mama bridge.
queueCount The number of queues in the group.
References Wombat.MamaQueueGroup.Dispose().
Member Function Documentation
destroy()
void Wombat.MamaQueueGroup.destroy ()
Destroy the queue group and destroy all the queues without waiting, this is equivalent to disposing the class.
References Wombat.MamaQueueGroup.Dispose().
destroyWait()
void Wombat.MamaQueueGroup.destroyWait ()
Destroy the queue group and destroy all the queues waiting on each queue, this is equivalent to disposing the class.
Dispose()
void Wombat.MamaQueueGroup.Dispose ()
Dispose managed and unmanaged resources.
This will destroy all the queues without waiting for them to shutdown.
Referenced by Wombat.MamaQueueGroup.destroy(), and Wombat.MamaQueueGroup.MamaQueueGroup().
start()
void Wombat.MamaQueueGroup.start ()
Start dispatching on all queues.
stop()
void Wombat.MamaQueueGroup.stop ()
Stop dispatching on all queues.
getNextQueue()
MamaQueue Wombat.MamaQueueGroup.getNextQueue ()
This function will return the next queue since it was called last or the first queue in the group if this is the first time that it has been called.
Note that when all queues have been returned it will go back to the start of the array.