OpenMAMA C# API: Wombat.MamaSourceManager Class Reference
Wombat.MamaSourceManager Class Reference
A MamaSourceManager maintains information about a set of data sources, including the quality of the data coming from those sources.
Inherits Wombat.MamaWrapper, and Wombat.ISourceManager.
Public Member Functions
MamaSourceManager ()
Constructs and creates a new MamaSourceManager object.
void destroy ()
Destroy the source manager.
MamaSource create (string name)
Implements ISourceManager.create
MamaSource findOrCreate (string name)
Implements ISourceManager.findOrCreate
MamaSource find (string name)
Implements ISourceManager.find
void add (MamaSource source)
Implements ISourceManager.add(MamaSource)
void add (string name, MamaSource source)
Implements ISourceManager.add(System.String, MamaSource)
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object.
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
A MamaSourceManager maintains information about a set of data sources, including the quality of the data coming from those sources.
Constructor & Destructor Documentation
MamaSourceManager()
Wombat.MamaSourceManager.MamaSourceManager ()
Constructs and creates a new MamaSourceManager object.
See also
M:Wombat.MamaWrapper.::ctor
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaSourceManager.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object.
See also
MamaWrapper.DestroyNativePeer
Implements Wombat.MamaWrapper.
destroy()
void Wombat.MamaSourceManager.destroy ()
Destroy the source manager.
A synonym to the MamaWrapper.Dispose method.
References Wombat.MamaWrapper.Dispose().
create()
MamaSource Wombat.MamaSourceManager.create (string name)
Implements ISourceManager.create
Implements Wombat.ISourceManager.
Referenced by Wombat.MamaSource.create().
findOrCreate()
MamaSource Wombat.MamaSourceManager.findOrCreate (string name)
Implements ISourceManager.findOrCreate
Implements Wombat.ISourceManager.
Referenced by Wombat.MamaSource.findOrCreate().
find()
MamaSource Wombat.MamaSourceManager.find (string name)
Implements ISourceManager.find
Implements Wombat.ISourceManager.
Referenced by Wombat.MamaSource.find().
add() [1/2]
void Wombat.MamaSourceManager.add (MamaSource source)
Implements ISourceManager.add(MamaSource)
Implements Wombat.ISourceManager.
Referenced by Wombat.MamaSource.add().
add() [2/2]
void Wombat.MamaSourceManager.add (string name, MamaSource source)
Implements ISourceManager.add(System.String, MamaSource)
Implements Wombat.ISourceManager.
References Wombat.Mama.DllName.