OpenMAMA C# API: Wombat.MamaSourceGroup Class Reference
Wombat.MamaSourceGroup Class Reference
A MamaSourceGroup monitors a set of MamaSources that presumably provide a duplicate set of data.
Inherits Wombat.MamaWrapper, and IEnumerable.
Classes
interface StateChangedRegistration
Encapsulates a registration of a state-change mCallback for a particular source mGroup
Public Member Functions
MamaSourceGroup (string groupName)
Constructs and creates a new source mGroup object.
void destroy ()
Destroy the source.
MamaSource find (string sourceName)
Find a source with the given name in the mGroup.
void add (MamaSource source, uint weight)
Add a mamaSource to the specified mGroup with the specified weighting.
void add (MamaSource source, int weight)
CLS compliant version of add(MamaSource, UInt32)
void add (string sourceName, uint weight, MamaSource source)
Add a mamaSource to the specified mGroup with the specified weighting and string name identifier.
void add (string sourceName, int weight, MamaSource source)
CLS compliant version of add(System.String, UInt32, MamaSource)
void setWeight (string sourceName, uint weight)
Set the weight for an existing mamaSource in the specified mGroup.
void setWeight (string sourceName, int weight)
CLS compliant version of setWeight(System.String, UInt32)
StateChangedRegistration registerStateChangeCallback (MamaSourceStateChangeCallback mCallback)
The mCallback interface registered here will receive a mCallback whenever the state of sources in the mGroup changes.
bool reevaluate ()
Re-evaluate the mGroup by checking all of the relative weights and changing the state of each MamaSource in the mGroup as appropriate.
IEnumerator GetEnumerator ()
Provides an enumerator over the sources in the source mGroup
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object.
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Properties
string name [get]
Return the name string identifier for the specified source mGroup.
uint size [get]
Returns the number of sources in this source mGroup
int sizeClsCompliant [get]
CLS compliant version of size
MamaSource topWeightSource [get]
Return the top weighted source for this source mGroup.
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
A MamaSourceGroup monitors a set of MamaSources that presumably provide a duplicate set of data.
Each member of the mGroup is given a priority and the member with the highest priority is given the state mamaSourceState.MAMA_SOURCE_STATE_OK the other members of the mGroup are given the state mamaSourceState.MAMA_SOURCE_STATE_OFF
Constructor & Destructor Documentation
MamaSourceGroup()
Wombat.MamaSourceGroup.MamaSourceGroup (string groupName)
Constructs and creates a new source mGroup object.
See also
M:Wombat.MamaWrapper.::ctor
Parameters
groupName The string identifier for the source mGroup.
References Wombat.MamaWrapper.nativeHandle.
Member Function Documentation
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaSourceGroup.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object.
See also
MamaWrapper.DestroyNativePeer
Implements Wombat.MamaWrapper.
destroy()
void Wombat.MamaSourceGroup.destroy ()
Destroy the source.
A synonym to the MamaWrapper.Dispose method.
References Wombat.MamaWrapper.Dispose(), and Wombat.MamaSourceGroup.name.
find()
MamaSource Wombat.MamaSourceGroup.find (string sourceName)
Find a source with the given name in the mGroup.
Parameters
sourceName The name identifier for the source being located.
Returns
The source if found, null otherwise
add() [1/4]
void Wombat.MamaSourceGroup.add (MamaSource source, uint weight)
Add a mamaSource to the specified mGroup with the specified weighting.
The source id will be used by the mGroup to uniquely identify the source.
Parameters
source The mamaSource being added to the mamaSourceGroup.
weight The weighing to apply to the source being added.
Referenced by Wombat.MamaSourceGroup.add().
add() [2/4]
void Wombat.MamaSourceGroup.add (MamaSource source, int weight)
CLS compliant version of add(MamaSource, UInt32)
References Wombat.MamaSourceGroup.add().
add() [3/4]
void Wombat.MamaSourceGroup.add (string sourceName, uint weight, MamaSource source)
Add a mamaSource to the specified mGroup with the specified weighting and string name identifier.
Parameters
sourceName The unique identifier for this source in this mGroup.
weight The weighing to apply to the source being added.
source The mamaSource being added to the mamaSourceGroup.
add() [4/4]
void Wombat.MamaSourceGroup.add (string sourceName, int weight, MamaSource source)
CLS compliant version of add(System.String, UInt32, MamaSource)
References Wombat.MamaSourceGroup.add().
setWeight() [1/2]
void Wombat.MamaSourceGroup.setWeight (string sourceName, uint weight)
Set the weight for an existing mamaSource in the specified mGroup.
Parameters
sourceName The name of the source whose weight is being updated.
weight The new weight value for the specified source.
Referenced by Wombat.MamaSourceGroup.setWeight().
setWeight() [2/2]
void Wombat.MamaSourceGroup.setWeight (string sourceName, int weight)
CLS compliant version of setWeight(System.String, UInt32)
References Wombat.MamaSourceGroup.setWeight(), and Wombat.MamaSourceGroup.size.
registerStateChangeCallback()
StateChangedRegistration Wombat.MamaSourceGroup.registerStateChangeCallback (MamaSourceStateChangeCallback mCallback)
The mCallback interface registered here will receive a mCallback whenever the state of sources in the mGroup changes.
Parameters
mCallback The mCallback object
reevaluate()
bool Wombat.MamaSourceGroup.reevaluate ()
Re-evaluate the mGroup by checking all of the relative weights and changing the state of each MamaSource in the mGroup as appropriate.
Returns
Returns true if any states were changed; otherwise false.
References Wombat.MamaSourceGroup.topWeightSource.
GetEnumerator()
IEnumerator Wombat.MamaSourceGroup.GetEnumerator ()
Provides an enumerator over the sources in the source mGroup
Returns
References Wombat.Mama.DllName, Wombat.MamaSourceStateChangeCallback.onStateChanged(), Wombat.MamaSourceGroup.StateChangedRegistration.SourceGroup, Wombat.MamaSourceGroup.StateChangedRegistration.SourceStateChangeCallback, Wombat.MamaSourceGroup.topWeightSource, and Wombat.MamaSourceGroup.StateChangedRegistration.unregister().
Property Documentation
name
string Wombat.MamaSourceGroup.name get
Return the name string identifier for the specified source mGroup.
Referenced by Wombat.MamaSourceGroupManager.add(), and Wombat.MamaSourceGroup.destroy().
size
uint Wombat.MamaSourceGroup.size get
Returns the number of sources in this source mGroup
The size is evaluated every time, so cache it before entering a loop
Referenced by Wombat.MamaSourceGroup.setWeight().
sizeClsCompliant
int Wombat.MamaSourceGroup.sizeClsCompliant get
CLS compliant version of size
topWeightSource
MamaSource Wombat.MamaSourceGroup.topWeightSource get
Return the top weighted source for this source mGroup.
Referenced by Wombat.MamaSourceGroup.GetEnumerator(), and Wombat.MamaSourceGroup.reevaluate().