OpenMAMA C# API: Wombat.MamaFtMember Class Reference
Wombat.MamaFtMember Class Reference
A member of a MAMA fault tolerance group
Inherits Wombat.MamaWrapper.
Inherited by Wombat.MamaBridgeFtMember, and Wombat.MamaMulticastFtMember.
Public Member Functions
MamaFtMember ()
void create ()
Create object.
void setup (MamaQueue queue, MamaFtMemberCallback callback, MamaTransport transport, string groupName, uint weight, double heartbeatInterval, double timeoutInterval, object closure)
void activate ()
Activate the MAMA fault tolerance group member.
void deactivate ()
Deactivate the MAMA fault tolerance group member.
bool isActive ()
Get whether the MAMA fault tolerance member is actively running (not related to its state).
string getGroupName ()
Get the group name to which this MAMA FT member belongs.
uint getWeight ()
Get the fault tolerance weight of the MAMA FT member.
double getHeartbeatInterval ()
Get the fault tolerance heartbeat interval of the MAMA FT member.
double getTimeoutInterval ()
Get the fault tolerance timeout interval of the MAMA FT member.
object getClosure ()
Get the closure argument (provided in the mamaFtMember.create() function) of the MAMA FT member.
void setWeight (uint value)
Set the fault tolerance weight of the MAMA FT member.
void setInstanceId (string id)
Set the instance ID of the MAMA FT member
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Static Public Member Functions
static string mamaFtStateToString (mamaFtState state)
Convert a fault tolerant state to a string
Protected Member Functions
void setupFtType (mamaFtType ftType, MamaQueue queue, MamaFtMemberCallback callback, MamaTransport transport, string groupName, uint weight, double heartbeatInterval, double timeoutInterval, object closure)
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
A member of a MAMA fault tolerance group
Constructor & Destructor Documentation
MamaFtMember()
Wombat.MamaFtMember.MamaFtMember ()
Member Function Documentation
create()
void Wombat.MamaFtMember.create ()
Create object.
This function is typically followed by MamaFtMember.setup and MamaFtMember.activate
References Wombat.MamaWrapper.nativeHandle.
setupFtType()
void Wombat.MamaFtMember.setupFtType (mamaFtType ftType, MamaQueue queue, MamaFtMemberCallback callback, MamaTransport transport, string groupName, uint weight, double heartbeatInterval, double timeoutInterval, object closure) protected
References Wombat.MamaWrapper.nativeHandle.
Referenced by Wombat.MamaFtMember.setup(), Wombat.MamaMulticastFtMember.setup(), and Wombat.MamaBridgeFtMember.setup().
setup()
void Wombat.MamaFtMember.setup (MamaQueue queue, MamaFtMemberCallback callback, MamaTransport transport, string groupName, uint weight, double heartbeatInterval, double timeoutInterval, object closure)
References Wombat.MamaFtMember.setupFtType().
activate()
void Wombat.MamaFtMember.activate ()
Activate the MAMA fault tolerance group member.
References Wombat.MamaWrapper.nativeHandle.
deactivate()
void Wombat.MamaFtMember.deactivate ()
Deactivate the MAMA fault tolerance group member.
References Wombat.MamaWrapper.nativeHandle.
isActive()
bool Wombat.MamaFtMember.isActive ()
Get whether the MAMA fault tolerance member is actively running (not related to its state).
Use mamaFtMember.getState() to determine the actual state of the member.
References Wombat.MamaWrapper.nativeHandle.
getGroupName()
string Wombat.MamaFtMember.getGroupName ()
Get the group name to which this MAMA FT member belongs.
References Wombat.MamaWrapper.nativeHandle.
getWeight()
uint Wombat.MamaFtMember.getWeight ()
Get the fault tolerance weight of the MAMA FT member.
References Wombat.MamaWrapper.nativeHandle.
getHeartbeatInterval()
double Wombat.MamaFtMember.getHeartbeatInterval ()
Get the fault tolerance heartbeat interval of the MAMA FT member.
References Wombat.MamaWrapper.nativeHandle.
getTimeoutInterval()
double Wombat.MamaFtMember.getTimeoutInterval ()
Get the fault tolerance timeout interval of the MAMA FT member.
References Wombat.MamaWrapper.nativeHandle.
getClosure()
object Wombat.MamaFtMember.getClosure ()
Get the closure argument (provided in the mamaFtMember.create() function) of the MAMA FT member.
setWeight()
void Wombat.MamaFtMember.setWeight (uint value)
Set the fault tolerance weight of the MAMA FT member.
The FT weight can be changed dynamically, if desired. The member with the highest weight will become the active member.
References Wombat.MamaWrapper.nativeHandle.
setInstanceId()
void Wombat.MamaFtMember.setInstanceId (string id)
Set the instance ID of the MAMA FT member
The instance ID is used to uniquely identify members of a fault tolerant group. Most applications should allow the MAMA API to automatically set the instance ID and this function would not be called. If not set explicitly before activation, then the instance ID is automatically set according to the following format:
{group-name}.{hex-ip-addr}.{hex-pid}
For example, if the group name is "FOO", the IP address is 192.168.187.9, and the PId is 10777, the default instance ID would be:
FOO.c0a8bb9.2a19
References Wombat.MamaWrapper.nativeHandle.
mamaFtStateToString()
static string Wombat.MamaFtMember.mamaFtStateToString (mamaFtState state) static
Convert a fault tolerant state to a string
Referenced by Wombat.MamaFtMember.DestroyNativePeer().
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaFtMember.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object
See also
MamaWrapper.DestroyNativePeer
Implements Wombat.MamaWrapper.
References Wombat.Mama.DllName, Wombat.MamaFtMember.mamaFtStateToString(), and Wombat.MamaWrapper.nativeHandle.