OpenMAMA C# API: Wombat.MamaDictionary Class Reference
Wombat.MamaDictionary Class Reference
Maps field identifiers (FIDs) to human-readable strings
Inherits Wombat.MamaWrapper.
Public Member Functions
MamaDictionary ()
Default constructor
void create (MamaQueue queue, MamaDictionaryCallback callback, MamaSource source, int retries, double timeout)
Create a data dictionary from a subscription
void create (string filename)
void writeToFile (string filename)
string getFeedName ()
string getFeedHost ()
MamaFieldDescriptor getFieldByName (string fieldName)
Return the descriptor of the field with the specified name.
int getMaxFid ()
Returns the highest field identifier.
int getSize ()
Returns the the number of entries in the dictionary.
MamaFieldDescriptor getFieldByFid (int fid)
Return the field with the specified field FID.
MamaFieldDescriptor getFieldByIndex (int index)
Return the field with the corresponding zero based index.
void buildDictionaryFromMessage (MamaMsg msg)
Recreate a data dictionary from the MamaMsg supplied.
MamaMsg getDictionaryMessage ()
Returns a MamaMsg representing the data dictionary.
Public Member Functions inherited from Wombat.MamaWrapper
void Dispose ()
Destroys the underlying peer object and unbinds the wrapper from it.
void setNativeHandle (IntPtr nHandle)
Sets the native handle of the native peer object.
Protected Member Functions
override MamaStatus.mamaStatus DestroyNativePeer ()
Implements the destruction of the underlying peer object
Protected Member Functions inherited from Wombat.MamaWrapper
MamaWrapper ()
Constructs a new wrapper object but doesn't create it.
MamaWrapper (IntPtr nativeHandle)
Constructs a managed wrapper from an existing native peer.
virtual void Dispose (bool disposing, bool destroyNativeHandle=true)
The actual implementation of Dispose - called by both the Dispose method and the finalizer.
virtual void OnDispose ()
Additional Inherited Members
Protected Attributes inherited from Wombat.MamaWrapper
IntPtr nativeHandle
the handle to the native peer object
Detailed Description
Maps field identifiers (FIDs) to human-readable strings
Any incoming MamaMsg might contain FIDs but no field names. The dictionary allows applications to determine the name associated with a given FID.
Constructor & Destructor Documentation
MamaDictionary()
Wombat.MamaDictionary.MamaDictionary ()
Default constructor
Member Function Documentation
create() [1/2]
void Wombat.MamaDictionary.create (MamaQueue queue, MamaDictionaryCallback callback, MamaSource source, int retries, double timeout)
Create a data dictionary from a subscription
References Wombat.MamaWrapper.nativeHandle.
create() [2/2]
void Wombat.MamaDictionary.create (string filename)
References Wombat.MamaWrapper.nativeHandle.
writeToFile()
void Wombat.MamaDictionary.writeToFile (string filename)
References Wombat.MamaWrapper.nativeHandle.
DestroyNativePeer()
override MamaStatus.mamaStatus Wombat.MamaDictionary.DestroyNativePeer () protected virtual
Implements the destruction of the underlying peer object
Implements Wombat.MamaWrapper.
References Wombat.MamaWrapper.nativeHandle.
getFeedName()
string Wombat.MamaDictionary.getFeedName ()
References Wombat.MamaWrapper.nativeHandle.
getFeedHost()
string Wombat.MamaDictionary.getFeedHost ()
References Wombat.MamaWrapper.nativeHandle.
getFieldByName()
MamaFieldDescriptor Wombat.MamaDictionary.getFieldByName (string fieldName)
Return the descriptor of the field with the specified name.
If there is more than one field with the same name, the one with the lowest field id is returned.
References Wombat.MamaWrapper.nativeHandle.
getMaxFid()
int Wombat.MamaDictionary.getMaxFid ()
Returns the highest field identifier.
References Wombat.MamaWrapper.nativeHandle.
getSize()
int Wombat.MamaDictionary.getSize ()
Returns the the number of entries in the dictionary.
References Wombat.MamaWrapper.nativeHandle.
getFieldByFid()
MamaFieldDescriptor Wombat.MamaDictionary.getFieldByFid (int fid)
Return the field with the specified field FID.
This method is very efficient.
References Wombat.MamaWrapper.nativeHandle.
getFieldByIndex()
MamaFieldDescriptor Wombat.MamaDictionary.getFieldByIndex (int index)
Return the field with the corresponding zero based index.
This method is O (N) with respect to the size of the dictionary.
References Wombat.MamaWrapper.nativeHandle.
buildDictionaryFromMessage()
void Wombat.MamaDictionary.buildDictionaryFromMessage (MamaMsg msg)
Recreate a data dictionary from the MamaMsg supplied.
The MamaMsg is copied and can therefore be deleted after the method has returned.
References Wombat.MamaWrapper.nativeHandle.
getDictionaryMessage()
MamaMsg Wombat.MamaDictionary.getDictionaryMessage ()
Returns a MamaMsg representing the data dictionary.
This message can be published or used to create a new MamaDictionary object. A new MamaMsg is created for each invocation of the method. It is the responsibility of the caller to delete the message when no longer needed.
References Wombat.Mama.DllName, Wombat.MamaWrapper.nativeHandle, Wombat.MamaDictionaryCallback.onComplete(), Wombat.MamaDictionaryCallback.onError(), and Wombat.MamaDictionaryCallback.onTimeout().