OpenMAMA C# API: Wombat.MamaTransportCallback Interface Reference
Wombat.MamaTransportCallback Interface Reference
Callbacks associated with MamaTransports
Public Member Functions
void onDisconnect (MamaTransport transport)
See interface remarks for details
void onReconnect (MamaTransport transport)
See interface remarks for details
void onQuality (MamaTransport transport)
Called when an event occurs which affects data quality
void onConnect (MamaTransport transport)
Called when a subscriber connects to a publisher (Wombat Middleware) or when reconnection to an RV daemon occurs (TIBRV).
void onAcceptConnect (MamaTransport transport)
Called when a publisher accepts a connection from a subscriber (Wombat Middleware).
void onAcceptReconnect (MamaTransport transport)
Called when a publisher accepts a reconnection from a subscriber (Wombat Middleware).
void onPublisherDisconnect (MamaTransport transport)
Called when a subscriber loses connection to a publisher (Wombat Middleware).
void onNamingServiceConnect (MamaTransport transport)
Called on connection to a NSD (Wombat Middleware).
void onNamingServiceDisconnect (MamaTransport transport)
Called on disconnection to a NSD (Wombat Middleware).
Detailed Description
Callbacks associated with MamaTransports
Events that can cause one of the callbacks to be invoked vary according to the underlying middleware. The details are as follows:
All Middleware: MAMA_TRANSPORT_QUALITY is passed when an the underlying transport detects an event that may affect data quality. Depending on the event, MAMA may also mark subscriptions as STALE or MAYBE_STALE.
TIBRV: TIBRV invokes the callback with MAMA_TRANSPORT_DISCONNECT when the transport disconnects from the RV daemon and MAMA_TRANSPORT_RECONNECT when it reestablishes a connection to the daemon.
Wombat Middleware: For Wombat Middleware MAMA distinguishes between connections established from a transport to another transport and connections established by the transport from another transport. In general MAMA applications establish connection from a MAMA transport to a feed handler (publisher); however, they may also accept connections from other MAMA clients. Applications subscribe to topics and publisher messages over all connections. When a transport successfully connects to another transport (ie. a feed handler) the mamaTranpsortCallback receives MAMA_TRANSPORT_CONNECT if the connection succeeds immediately otherwise it receives a MAMA_TRANSPORT_RECONNECT if it subsequently succeeds. Wombat Middlware transports may be configured to retry failed connections. When a conection that a transport establishes to another transport (the publisher by convention) and the connection is lost the mamaTranpsortCallback receives the MAMA_TRANSPORT_PUBLISHER_DISCONNECT event. When a transport accepts a connection from a remote transport (the subscriber by convention) it receives either a MAMA_TRANSPORT_ACCEPT or MAMA_TRANSPORT_ACCEPT_RECONNECT event indicating that the remote client is connecting or reconnecting. When the client disconnects MAMA passes the MAMA_TRANSPORT_DISCONNECT value.
Member Function Documentation
onDisconnect()
void Wombat.MamaTransportCallback.onDisconnect (MamaTransport transport)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onReconnect()
void Wombat.MamaTransportCallback.onReconnect (MamaTransport transport)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onQuality()
void Wombat.MamaTransportCallback.onQuality (MamaTransport transport)
Called when an event occurs which affects data quality
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onConnect()
void Wombat.MamaTransportCallback.onConnect (MamaTransport transport)
Called when a subscriber connects to a publisher (Wombat Middleware) or when reconnection to an RV daemon occurs (TIBRV).
Parameters
transport
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onAcceptConnect()
void Wombat.MamaTransportCallback.onAcceptConnect (MamaTransport transport)
Called when a publisher accepts a connection from a subscriber (Wombat Middleware).
Parameters
transport
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onAcceptReconnect()
void Wombat.MamaTransportCallback.onAcceptReconnect (MamaTransport transport)
Called when a publisher accepts a reconnection from a subscriber (Wombat Middleware).
Parameters
transport
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onPublisherDisconnect()
void Wombat.MamaTransportCallback.onPublisherDisconnect (MamaTransport transport)
Called when a subscriber loses connection to a publisher (Wombat Middleware).
Parameters
transport
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onNamingServiceConnect()
void Wombat.MamaTransportCallback.onNamingServiceConnect (MamaTransport transport)
Called on connection to a NSD (Wombat Middleware).
Parameters
transport
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onNamingServiceDisconnect()
void Wombat.MamaTransportCallback.onNamingServiceDisconnect (MamaTransport transport)
Called on disconnection to a NSD (Wombat Middleware).
Parameters
transport
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().