OpenMAMA C# API: Wombat.MamaPublisherCallback Interface Reference
Wombat.MamaPublisherCallback Interface Reference
Callbacks at the publisher level.
Public Member Functions
void onCreate (MamaPublisher publisher)
See interface remarks for details
void onError (MamaPublisher publisher, MamaStatus.mamaStatus status, string topic)
See interface remarks for details
void onSuccess (MamaPublisher publisher, MamaStatus.mamaStatus status, string topic)
See interface remarks for details
void onDestroy (MamaPublisher publisher)
See interface remarks for details
Detailed Description
Callbacks at the publisher level.
Member Function Documentation
onCreate()
void Wombat.MamaPublisherCallback.onCreate (MamaPublisher publisher)
See interface remarks for details
Referenced by Wombat.MamaPublisher.getSymbol().
onError()
void Wombat.MamaPublisherCallback.onError (MamaPublisher publisher, MamaStatus.mamaStatus status, string topic)
See interface remarks for details
Referenced by Wombat.MamaPublisher.getSymbol().
onSuccess()
void Wombat.MamaPublisherCallback.onSuccess (MamaPublisher publisher, MamaStatus.mamaStatus status, string topic)
See interface remarks for details
Referenced by Wombat.MamaPublisher.getSymbol().
onDestroy()
void Wombat.MamaPublisherCallback.onDestroy (MamaPublisher publisher)
See interface remarks for details
Referenced by Wombat.MamaPublisher.getSymbol().