OpenMAMA C# API: Wombat.MamaTransportTopicCallback Interface Reference
Wombat.MamaTransportTopicCallback Interface Reference
Callbacks at the topic level associated with MamaTransports
Public Member Functions
void onTopicSubscribe (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
void onTopicUnsubscribe (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
void onTopicPublishError (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
void onTopicPublishErrorNotEntitled (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
void onTopicPublishErrorBadSymbol (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
Detailed Description
Callbacks at the topic level associated with MamaTransports
These are topic-specific callbacks from the transport. They are for sub/unsub, and for publisher events.
Member Function Documentation
onTopicSubscribe()
void Wombat.MamaTransportTopicCallback.onTopicSubscribe (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onTopicUnsubscribe()
void Wombat.MamaTransportTopicCallback.onTopicUnsubscribe (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onTopicPublishError()
void Wombat.MamaTransportTopicCallback.onTopicPublishError (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onTopicPublishErrorNotEntitled()
void Wombat.MamaTransportTopicCallback.onTopicPublishErrorNotEntitled (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().
onTopicPublishErrorBadSymbol()
void Wombat.MamaTransportTopicCallback.onTopicPublishErrorBadSymbol (MamaTransport transport, string topic, Object platformInfo)
See interface remarks for details
Referenced by Wombat.MamaTransport.getTransportCallbackQueue().