OpenMAMA C# API: Wombat.MamaBasicSubscriptionCallback Interface Reference
Wombat.MamaBasicSubscriptionCallback Interface Reference
This interface should be implemented by clients wish to create a MAMA Basic subscription, it contains callback functions that will be invoked whenever specific events occur.
Public Member Functions
void onCreate (MamaBasicSubscription subscription)
Called when subscription creation is complete, and before the onMsg() callback is invoked
void onError (MamaBasicSubscription subscription, MamaStatus.mamaStatus status, string subject)
Called when an error has occurred with the subscription
void onMsg (MamaBasicSubscription subscription, MamaMsg message)
Invoked when a message arrives
void onDestroy (MamaBasicSubscription subscription, object closure)
Invoked whenever the basic subscription has been destroyed.
Detailed Description
This interface should be implemented by clients wish to create a MAMA Basic subscription, it contains callback functions that will be invoked whenever specific events occur.
Member Function Documentation
onCreate()
void Wombat.MamaBasicSubscriptionCallback.onCreate (MamaBasicSubscription subscription)
Called when subscription creation is complete, and before the onMsg() callback is invoked
Parameters
subscription The subscription that has been created.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
onError()
void Wombat.MamaBasicSubscriptionCallback.onError (MamaBasicSubscription subscription, MamaStatus.mamaStatus status, string subject)
Called when an error has occurred with the subscription
Parameters
subscription The subscription where the error has been detected.
status The status code associated with the error.
subject The subject for entitlement errors.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
onMsg()
void Wombat.MamaBasicSubscriptionCallback.onMsg (MamaBasicSubscription subscription, MamaMsg message)
Invoked when a message arrives
Parameters
subscription The subscription where the message has arrived.
message The message.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().
onDestroy()
void Wombat.MamaBasicSubscriptionCallback.onDestroy (MamaBasicSubscription subscription, object closure)
Invoked whenever the basic subscription has been destroyed.
The client can have confidence that no further messages will be placed on the queue for this subscription.
Parameters
subscription The basic subscription.
closure The closure provided to the createBasic function.
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscriptionImpl.MamaBasicSubscriptionImpl().