OpenMAMA C# API: Wombat.NullableInt Struct Reference
Wombat.NullableInt Struct Reference
Modelled after Nullable<T> in C# 2.0
Inherits IComparable.
Public Member Functions
NullableInt (int value)
Constructor
int GetValueOrDefault ()
<overloads>Get the value</overloads>
int GetValueOrDefault (int defaultValue)
Get value, or default if value is not defined
override bool Equals (object other)
Test for equality
int CompareTo (object obj)
Compare another object
override int GetHashCode ()
Return the hashcode
override string ToString ()
Stringify the value
Static Public Member Functions
static implicit operator NullableInt (int value)
Conversion from int
static operator int (NullableInt value)
Conversion to int
Properties
bool HasValue [get]
Return TRUE if object has a value
int Value [get, set]
Return the value
Detailed Description
Modelled after Nullable<T> in C# 2.0
Constructor & Destructor Documentation
NullableInt()
Wombat.NullableInt.NullableInt (int value)
Constructor
References Wombat.NullableInt.HasValue.
Referenced by Wombat.NullableInt.CompareTo(), and Wombat.NullableInt.operator NullableInt().
Member Function Documentation
GetValueOrDefault() [1/2]
int Wombat.NullableInt.GetValueOrDefault ()
<overloads>Get the value</overloads>
Get the value
GetValueOrDefault() [2/2]
int Wombat.NullableInt.GetValueOrDefault (int defaultValue)
Get value, or default if value is not defined
Equals()
override bool Wombat.NullableInt.Equals (object other)
Test for equality
Parameters
other Object to compare with
Returns
TRUE if other object is equal to this one, FALSE otherwise
References Wombat.NullableInt.CompareTo().
CompareTo()
int Wombat.NullableInt.CompareTo (object obj)
Compare another object
Parameters
obj Object to compare with
Returns
If both objects are the same, returns zero. If this object has a value but the other object does not, returns +1. If this object does not have a value, but the other object does have a value, returns -1. If both objects have a value, returns an indication of their relative values /returns>
References Wombat.NullableInt.NullableInt().
Referenced by Wombat.NullableInt.Equals().
GetHashCode()
override int Wombat.NullableInt.GetHashCode ()
Return the hashcode
ToString()
override string Wombat.NullableInt.ToString ()
Stringify the value
operator NullableInt()
static implicit Wombat.NullableInt.operator NullableInt (int value) static
Conversion from int
References Wombat.NullableInt.NullableInt().
operator int()
static Wombat.NullableInt.operator int (NullableInt value) explicit static
Conversion to int
References Wombat.NullableInt.Value.
Property Documentation
HasValue
bool Wombat.NullableInt.HasValue get
Return TRUE if object has a value
Referenced by Wombat.NullableInt.NullableInt().
Value
int Wombat.NullableInt.Value get set
Return the value
Referenced by Wombat.NullableInt.operator int().