OpenMAMA C# API: Wombat.NullableBool Struct Reference
Wombat.NullableBool Struct Reference
Modelled after Nullable<T> in C# 2.0
Inherits IComparable.
Public Member Functions
NullableBool (bool value)
Constructor
bool GetValueOrDefault ()
<overloads>Get the value</overloads>
bool GetValueOrDefault (bool defaultValue)
Get value, or default if value is not defined
override bool Equals (object other)
Test for equality
int CompareTo (object obj)
Compare another object
override int GetHashCode ()
Return the hashcode
override string ToString ()
Stringify the value
Static Public Member Functions
static implicit operator NullableBool (bool value)
Conversion from bool
static operator bool (NullableBool value)
Conversion to bool
Properties
bool HasValue [get]
Return TRUE if object has a value
bool Value [get, set]
Return the value
Detailed Description
Modelled after Nullable<T> in C# 2.0
Constructor & Destructor Documentation
NullableBool()
Wombat.NullableBool.NullableBool (bool value)
Constructor
References Wombat.NullableBool.HasValue.
Referenced by Wombat.NullableBool.CompareTo(), and Wombat.NullableBool.operator NullableBool().
Member Function Documentation
GetValueOrDefault() [1/2]
bool Wombat.NullableBool.GetValueOrDefault ()
<overloads>Get the value</overloads>
Get the value
GetValueOrDefault() [2/2]
bool Wombat.NullableBool.GetValueOrDefault (bool defaultValue)
Get value, or default if value is not defined
Equals()
override bool Wombat.NullableBool.Equals (object other)
Test for equality
Parameters
other Object to compare with
Returns
TRUE if other object is equal to this one, FALSE otherwise
References Wombat.NullableBool.CompareTo().
CompareTo()
int Wombat.NullableBool.CompareTo (object obj)
Compare another object
Parameters
obj Object to compare with
Returns
If both objects are the same, returns zero. If this object has a value but the other object does not, returns +1. If this object does not have a value, but the other object does have a value, returns -1. If both objects have a value, returns an indication of their relative values /returns>
References Wombat.NullableBool.NullableBool().
Referenced by Wombat.NullableBool.Equals().
GetHashCode()
override int Wombat.NullableBool.GetHashCode ()
Return the hashcode
ToString()
override string Wombat.NullableBool.ToString ()
Stringify the value
operator NullableBool()
static implicit Wombat.NullableBool.operator NullableBool (bool value) static
Conversion from bool
References Wombat.NullableBool.NullableBool().
operator bool()
static Wombat.NullableBool.operator bool (NullableBool value) explicit static
Conversion to bool
References Wombat.NullableBool.Value.
Property Documentation
HasValue
bool Wombat.NullableBool.HasValue get
Return TRUE if object has a value
Referenced by Wombat.NullableBool.NullableBool().
Value
bool Wombat.NullableBool.Value get set
Return the value
Referenced by Wombat.NullableBool.operator bool().