OpenMAMA C# API: Wombat.MamaBasicSubscription.NativeMethods Struct Reference
Wombat.MamaBasicSubscription.NativeMethods Struct Reference
Classes
struct SubscriptionCallbacks
Public Member Functions
static int mamaSubscription_allocate (ref IntPtr result)
static int mamaSubscription_createBasic (IntPtr nativeHandle, IntPtr transport, IntPtr queue, ref SubscriptionCallbacks callbacks, [MarshalAs(UnmanagedType.LPStr)] string symbol, IntPtr closure)
static int mamaSubscription_deallocate (IntPtr nativeHandle)
static int mamaSubscription_destroy (IntPtr nativeHandle)
static int mamaSubscription_destroyEx (IntPtr nativeHandle)
static int mamaSubscription_getState (IntPtr nativeHandle, ref int state)
static int mamaSubscription_getSubscSymbol (IntPtr subscription, ref IntPtr symbol)
Member Function Documentation
mamaSubscription_allocate()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_allocate (ref IntPtr result)
Referenced by Wombat.MamaBasicSubscription.MamaBasicSubscription().
mamaSubscription_createBasic()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_createBasic (IntPtr nativeHandle, IntPtr transport, IntPtr queue, ref SubscriptionCallbacks callbacks, [MarshalAs(UnmanagedType.LPStr)] string symbol, IntPtr closure)
Referenced by Wombat.MamaBasicSubscription.createBasic().
mamaSubscription_deallocate()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_deallocate (IntPtr nativeHandle)
Referenced by Wombat.MamaBasicSubscription.DestroyNativePeer().
mamaSubscription_destroy()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_destroy (IntPtr nativeHandle)
Referenced by Wombat.MamaBasicSubscription.destroy().
mamaSubscription_destroyEx()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_destroyEx (IntPtr nativeHandle)
Referenced by Wombat.MamaBasicSubscription.destroyEx().
mamaSubscription_getState()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_getState (IntPtr nativeHandle, ref int state)
mamaSubscription_getSubscSymbol()
static int Wombat.MamaBasicSubscription.NativeMethods.mamaSubscription_getSubscSymbol (IntPtr subscription, ref IntPtr symbol)