OpenMAMA C# API: Wombat.NullableLong Struct Reference
Wombat.NullableLong Struct Reference
Modelled after Nullable<T> in C# 2.0
Inherits IComparable.
Public Member Functions
NullableLong (long value)
Constructor
long GetValueOrDefault ()
<overloads>Get the value</overloads>
long GetValueOrDefault (long defaultValue)
Get value, or default if value is not defined
override bool Equals (object other)
Return TRUE if other object is equal to this one
int CompareTo (object obj)
Compare another object.
override int GetHashCode ()
Return the hashcode
override string ToString ()
Stringify the value
Static Public Member Functions
static implicit operator NullableLong (long value)
For implicit type conversions
static operator long (NullableLong value)
For explicit type conversions
Properties
bool HasValue [get]
Return TRUE if object has a value
long Value [get, set]
Return the value
Detailed Description
Modelled after Nullable<T> in C# 2.0
Constructor & Destructor Documentation
NullableLong()
Wombat.NullableLong.NullableLong (long value)
Constructor
References Wombat.NullableLong.HasValue.
Referenced by Wombat.NullableLong.CompareTo(), and Wombat.NullableLong.operator NullableLong().
Member Function Documentation
GetValueOrDefault() [1/2]
long Wombat.NullableLong.GetValueOrDefault ()
<overloads>Get the value</overloads>
Get the value
GetValueOrDefault() [2/2]
long Wombat.NullableLong.GetValueOrDefault (long defaultValue)
Get value, or default if value is not defined
Equals()
override bool Wombat.NullableLong.Equals (object other)
Return TRUE if other object is equal to this one
References Wombat.NullableLong.CompareTo().
CompareTo()
int Wombat.NullableLong.CompareTo (object obj)
Compare another object.
If both objects are the same, then return zero. If this object has a value but the other object does not, return +1 If this object does not have a value, but the other object does have a value, return -1. If both objects have a value, the return value will be an indication of their relative values
References Wombat.NullableLong.NullableLong().
Referenced by Wombat.NullableLong.Equals().
GetHashCode()
override int Wombat.NullableLong.GetHashCode ()
Return the hashcode
ToString()
override string Wombat.NullableLong.ToString ()
Stringify the value
operator NullableLong()
static implicit Wombat.NullableLong.operator NullableLong (long value) static
For implicit type conversions
References Wombat.NullableLong.NullableLong().
operator long()
static Wombat.NullableLong.operator long (NullableLong value) explicit static
For explicit type conversions
References Wombat.NullableLong.Value.
Property Documentation
HasValue
bool Wombat.NullableLong.HasValue get
Return TRUE if object has a value
Referenced by Wombat.NullableLong.NullableLong().
Value
long Wombat.NullableLong.Value get set
Return the value
Referenced by Wombat.NullableLong.operator long().