OpenMAMA C++ API: Wombat::MamaStatus Class Reference
Wombat::MamaStatus Class Reference
#include <MamaStatus.h>
Public Member Functions
virtual ~MamaStatus (void)
MamaStatus (mama_status status)
virtual const char * toString (void) const
mama_status getStatus () const
bool operator== (mama_status const rhs_i)
bool operator== (MamaStatus const rhs_i)
bool operator!= (mama_status const rhs_i)
bool operator!= (MamaStatus const rhs_i)
bool operator< (mama_status const rhs_i)
bool operator< (MamaStatus const rhs_i)
bool operator> (mama_status const rhs_i)
bool operator> (MamaStatus const rhs_i)
bool operator<= (mama_status const rhs_i)
bool operator<= (MamaStatus const rhs_i)
bool operator>= (mama_status const rhs_i)
bool operator>= (MamaStatus const rhs_i)
Constructor & Destructor Documentation
~MamaStatus()
virtual Wombat::MamaStatus::~MamaStatus (void) inline virtual
MamaStatus()
Wombat::MamaStatus::MamaStatus (mama_status status) inline
Member Function Documentation
toString()
virtual const char* Wombat::MamaStatus::toString (void) const virtual
getStatus()
mama_status Wombat::MamaStatus::getStatus () const inline
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
operator==() [1/2]
bool Wombat::MamaStatus::operator== (mama_status const rhs_i) inline
operator==() [2/2]
bool Wombat::MamaStatus::operator== (MamaStatus const rhs_i) inline
References getStatus().
operator!=() [1/2]
bool Wombat::MamaStatus::operator!= (mama_status const rhs_i) inline
operator!=() [2/2]
bool Wombat::MamaStatus::operator!= (MamaStatus const rhs_i) inline
References getStatus().
operator<() [1/2]
bool Wombat::MamaStatus::operator< (mama_status const rhs_i) inline
operator<() [2/2]
bool Wombat::MamaStatus::operator< (MamaStatus const rhs_i) inline
References getStatus().
operator>() [1/2]
bool Wombat::MamaStatus::operator> (mama_status const rhs_i) inline
operator>() [2/2]
bool Wombat::MamaStatus::operator> (MamaStatus const rhs_i) inline
References getStatus().
operator<=() [1/2]
bool Wombat::MamaStatus::operator<= (mama_status const rhs_i) inline
operator<=() [2/2]
bool Wombat::MamaStatus::operator<= (MamaStatus const rhs_i) inline
References getStatus().
operator>=() [1/2]
bool Wombat::MamaStatus::operator>= (mama_status const rhs_i) inline
operator>=() [2/2]
bool Wombat::MamaStatus::operator>= (MamaStatus const rhs_i) inline
References getStatus().