OpenMAMA C++ API: Wombat::MamaFieldCacheFieldBasic< T, fieldType > Class Template Reference
Wombat::MamaFieldCacheFieldBasic< T, fieldType > Class Template Reference
MamaFieldCacheFieldBasic.
#include <MamaFieldCacheFieldTypes.h>
Public Member Functions
virtual ~MamaFieldCacheFieldBasic ()
void set (MamaFieldCacheField &field, const T &value)
Set the field value.
T get (const MamaFieldCacheField &field) const
Return the value of the field.
Public Member Functions inherited from Wombat::MamaFieldCacheFieldBase
virtual ~MamaFieldCacheFieldBase ()
Protected Member Functions
void checkType (const MamaFieldCacheField &field) const
Protected Member Functions inherited from Wombat::MamaFieldCacheFieldBase
MamaFieldCacheFieldBase ()
Detailed Description
template<typename T, mamaFieldType fieldType>
class Wombat::MamaFieldCacheFieldBasic< T, fieldType >
MamaFieldCacheFieldBasic.
Base class for basic single-value types. Allows to set and get the value of the field.
Constructor & Destructor Documentation
~MamaFieldCacheFieldBasic()
template<typename T , mamaFieldType fieldType> virtual Wombat::MamaFieldCacheFieldBasic< T, fieldType >::~MamaFieldCacheFieldBasic () inline virtual
Member Function Documentation
set()
template<typename T , mamaFieldType fieldType> void Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set (MamaFieldCacheField & field, const T & value)
Set the field value.
Parameters
field The field to set the value to.
value The new value of the field.
Referenced by Wombat::setV().
get()
template<typename T , mamaFieldType fieldType> T Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get (const MamaFieldCacheField & field) const
Return the value of the field.
Parameters
field The field to get the value from.
Returns
The value of the field.
Referenced by Wombat::getV().
checkType()
template<typename T , mamaFieldType fieldType> void Wombat::MamaFieldCacheFieldBasic< T, fieldType >::checkType (const MamaFieldCacheField & field) const inline protected
References Wombat::MamaFieldCacheField::getType().