OpenMAMA C++ API: Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType > Class Template Reference
Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType > Class Template Reference
MamaFieldCacheFieldVectorBasic.
#include <MamaFieldCacheFieldTypes.h>
Public Member Functions
void set (MamaFieldCacheField &field, const T *values, mama_size_t size)
Set the field value.
void get (const MamaFieldCacheField &field, const T *&values, mama_size_t &size) const
Return the field values.
const T & get (const MamaFieldCacheField &field, mama_size_t index) const
Return the value of a specific field of a vector field.
Public Member Functions inherited from Wombat::MamaFieldCacheFieldBase
virtual ~MamaFieldCacheFieldBase ()
Protected Member Functions
void checkType (const MamaFieldCacheField &field) const
Protected Member Functions inherited from Wombat::MamaFieldCacheFieldBase
MamaFieldCacheFieldBase ()
Detailed Description
template<typename T, mamaFieldType fieldType>
class Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >
MamaFieldCacheFieldVectorBasic.
Base class for basic vector types. Allows to set and get the value of the field.
Member Function Documentation
set()
template<typename T , mamaFieldType fieldType> void Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::set (MamaFieldCacheField & field, const T * values, mama_size_t size)
Set the field value.
Parameters
field The field to set the values to.
values The new values of the field.
size The number of fields in values.
Referenced by Wombat::setFieldValue().
get() [1/2]
template<typename T , mamaFieldType fieldType> void Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::get (const MamaFieldCacheField & field, const T *& values, mama_size_t & size) const
Return the field values.
Parameters
field The field to get the values from.
values A reference to the values to be returned.
size A reference to the size of the vector to be returned.
Referenced by Wombat::getFieldValue().
get() [2/2]
template<typename T , mamaFieldType fieldType> const T& Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::get (const MamaFieldCacheField & field, mama_size_t index) const
Return the value of a specific field of a vector field.
Parameters
field The field to get the value from.
index The index of the element of the vector to get the value from.
Returns
The value of the field.
checkType()
template<typename T , mamaFieldType fieldType> void Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::checkType (const MamaFieldCacheField & field) const inline protected
References Wombat::MamaFieldCacheField::getType().