OpenMAMA C++ API: Wombat::MamaFieldCacheFieldDateTimeVector Class Reference
Wombat::MamaFieldCacheFieldDateTimeVector Class Reference
MamaFieldCacheField: DateTime vector field.
#include <MamaFieldCacheFieldTypes.h>
Public Member Functions
void set (MamaFieldCacheField &field, const MamaDateTime *values, mama_size_t size)
Set the values of MamDateTime vector field.
void get (const MamaFieldCacheField &field, const MamaDateTime *&values, mama_size_t &size) const
Return the values of a MamaDateTime vector field.
const MamaDateTime * get (const MamaFieldCacheField &field, mama_size_t index) const
Return the value of a specific field of a MamaDateTime vector field.
Public Member Functions inherited from Wombat::MamaFieldCacheFieldBase
virtual ~MamaFieldCacheFieldBase ()
Protected Member Functions
void checkType (const MamaFieldCacheField &field) const
Protected Member Functions inherited from Wombat::MamaFieldCacheFieldBase
MamaFieldCacheFieldBase ()
Protected Member Functions inherited from Wombat::MamaFieldCacheFieldVector< MamaDateTime >
MamaFieldCacheFieldVector ()
~MamaFieldCacheFieldVector ()
void grow (mama_size_t newSize) const
Additional Inherited Members
Protected Attributes inherited from Wombat::MamaFieldCacheFieldVector< MamaDateTime >
MamaDateTime * mValues
mama_size_t mSize
Detailed Description
MamaFieldCacheField: DateTime vector field.
Member Function Documentation
set()
void Wombat::MamaFieldCacheFieldDateTimeVector::set (MamaFieldCacheField & field, const MamaDateTime * values, mama_size_t size)
Set the values of MamDateTime vector field.
Parameters
field The field to set the values to.
values The new values of the field.
size The number of fields in values.
Referenced by Wombat::setFieldValue().
get() [1/2]
void Wombat::MamaFieldCacheFieldDateTimeVector::get (const MamaFieldCacheField & field, const MamaDateTime *& values, mama_size_t & size) const
Return the values of a MamaDateTime vector field.
Parameters
field The field to get the values from.
values A reference to the values to be returned.
size A reference to the size of the vector to be returned.
get() [2/2]
const MamaDateTime* Wombat::MamaFieldCacheFieldDateTimeVector::get (const MamaFieldCacheField & field, mama_size_t index) const
Return the value of a specific field of a MamaDateTime vector field.
Parameters
field The field to get the value from.
index The index of the element of the vector to get the value from.
Returns
The value of the field.
checkType()
void Wombat::MamaFieldCacheFieldDateTimeVector::checkType (const MamaFieldCacheField & field) const inline protected
References Wombat::MamaFieldCacheField::getType(), and Wombat::setFieldValue().