OpenMAMA C++ API: Wombat Namespace Reference
Wombat Namespace Reference
Classes
class Mama
The Mama class provides methods global initialization and manipulating global options.
class MamaBasicSubscription
The MamaBasicSubscription interface represents a subscription to a topic with no market data semantics.
class MamaBasicSubscriptionCallback
The message callback interface for basic subscriptions.
class MamaBasicWildCardSubscription
The MamaBasicWildCardSubscription interface represents a subscription to a topic with no market data semantics.
class MamaBasicWildCardSubscriptionCallback
The message callback interface for basic subscriptions.
class MamaBridgeCallback
Bridge callback.
class MamaBridgeFtMember
class MamaConnection
class MamaDateTime
A date/time representation with additional hints for precision, advanced output formatting and support for time zone conversion (using the MamaTimeZone type).
class MamaDictionary
The MamaDictionary class maps field identifiers (FIDs) to human readable strings.
class MamaDictionaryCallback
The WombatDictionaryCallback receives notification regarding the population of the data dictionary.
class MamaDispatcher
The dispatcher dispatches events from a queue until it is destroyed or MamaQueue->stopDispatch () is called.
class MamaDQPublisher
class MamaDQPublisherManager
class MamaDQPublisherManagerCallback
class MamaEntitlementCallback
Callback object passed to Mama::registerEntitlmentCallbacks().
class MamaFieldCache
The MamaFieldCache class is a collection of unordered MamaFieldCacheField elements.
class MamaFieldCacheField
The MamaFieldCacheField class is used to store the information on the type of a field and its value(s).
class MamaFieldCacheFieldBase
Base type for fields.
class MamaFieldCacheFieldBasic
MamaFieldCacheFieldBasic.
class MamaFieldCacheFieldDateTime
MamaFieldCacheFieldDateTime.
class MamaFieldCacheFieldDateTimeVector
MamaFieldCacheField: DateTime vector field.
class MamaFieldCacheFieldPrice
MamaFieldCacheFieldPrice.
class MamaFieldCacheFieldPriceVector
MamaFieldCacheField: Price vector field.
class MamaFieldCacheFieldString
MamaFieldCacheFieldString.
class MamaFieldCacheFieldStringVector
MamaFieldCacheField: String vector field.
class MamaFieldCacheFieldVector
class MamaFieldCacheFieldVectorBasic
MamaFieldCacheFieldVectorBasic.
class MamaFieldCacheRecord
The MamaFieldCacheRecord class is a collection of unordered MamaFieldCacheField elements.
class MamaFieldDescriptor
The MamaFieldDescriptor class describes a field within a MamaDictionary
class MamaFtMember
class MamaFtMemberCallback
class MamaInbox
Used for sending messages requesting a direct reply.
class MamaInboxCallback
The MamaInboxCallback gets invoked when a message arrives in an inbox or when inbox related errors arise.
class MamaIo
A repeating IO.
class MamaIoCallback
Subclass this to receive IO notifications.
class MamaLogFile
The MamaLogFile class provides a single interface for the configuration and control of Mama logging activity.
class MamaLogFileCallback
Subclass this to receive log notifications.
class MamaMsg
MAMA message representation.
class MamaMsgField
MamaMsg field representation.
class MamaMsgFieldIterator
Callback class for iterating over all fields in a message.
class MamaMsgIterator
Iterator class for mamaMsg.
class MamaMsgQual
The MamaMsgQual class is a wrapper/utility class which provides useful interrogation, comparison and manipulation facilities for the Mama Message Qualifier data field (wMsgQual) which is a "bit-map" used to convey duplicate, delayed and out-of-sequence information about messages.
class MamaMulticastFtMember
class MamaPrice
MamaPrice is a special data type for representing floating point numbers that often require special formatting for display purposes, such as prices.
class MamaPublisher
The publisher class publishes messages to basic or market data subscriptions depending on the underlying transport.
class MamaPublisherCallback
class MamaPublishTopic
class MamaQueue
Queue allows applications to dispatch events in order with multiple threads using a single MamaDispatcher for each queue.
class MamaQueueEnqueueCallback
Callback interface for the MamaQueue::setEnqueueCallback () method.
class MamaQueueEventCallback
Definition of the callback method for when a user added event fires.
class MamaQueueGroup
A simple class for allocating subscriptions amongst multiple queues in a round robin.
class MamaQueueMonitorCallback
Receive callbacks when certain conditions for the MamaQueue are met.
class MamaReservedFields
class MamaSendCompleteCallback
Callback interface for use with the MamaPublisher.sendWithThrottle() and MamaPublisher.sendFromInboxWithThrottle() methods.
class MamaServerConnection
class MamaSource
A MAMA source maintains information about a data source, including the quality of the data coming from that source.
class MamaSourceDerivative
A MamaSourceDerivative provides a reference to a common MamaSource object but can have attributes (such as the quality state) overridden.
class MamaSourceGroup
A MAMA source group monitors a set of MAMA sources that presumably provide a duplicate set of data.
class MamaSourceGroupManager
A MAMA source group manager monitors a set of MAMA source groups.
class MamaSourceManager
A MAMA source manager maintains information about a set of data sources, including the quality of the data coming from those sources.
class MamaSourceStateChangeCallback
Applications can register with MamaSourceGroup to receive state change notifications when the state of sources within the group has changed.
class MamaStartCallback
Callback object passed to Mama::startBackground().
class MamaStat
class MamaStatsCollector
class MamaStatus
class MamaSubscription
The MamaSubscription interface represents a subscription to a topic.
class MamaSubscriptionCallback
The message callback interface.
class MamaSubscriptionIteratorCallback
class MamaSymbolList
MamaSymbolList manages a list of MAMA symbols and related attributes.
class MamaSymbolListFile
MamaSymbolListFile is a file based symbol list with the ability to detect external changes to the file.
class MamaSymbolListIteratorHandler
The MamaSymbolListIteratorHandler interface.
class MamaSymbolListMember
The MamaSymbolListMember class represents the information about the symbol list member.
class MamaSymbolListMembershipHandler
The MamaSymbolListMembershipHandler interface.
class MamaSymbolListResortHandler
The MamaSymbolListResortHandler interface.
class MamaSymbolMap
The MamaSymbolMap class provides the ability for MAMA to do client side symbology mapping.
class MamaSymbolMapFile
MamaSymbolMapFile is a concrete implementation of a symbology map.
class MamaSymbolSource
MamaSymbolSource defines an interface which all SymbolSources should implement in order to provide a mechanism by which objects implementing the "MamaSymbolSourceCallback::onSymbol" can be registered with the source such that they can be notified of new symbols as they arrive.
class MamaSymbolSourceCallback
The MamaSymbolSourceCallback interface.
class MamaSymbolStoreSaveCallback
The MamaSymbolStoreSaveCallback interface.
class MamaTimer
A repeating timer.
class MamaTimerCallback
Subclass this to receive timer notifications.
class MamaTimeZone
A time zone representation to make conversion of timestamps to and from particular time zones more convenient.
class MamaTransport
The MamaTransport class provides market data functionality.
class MamaTransportCallback
Transport callback.
class MamaTransportMap
class MamaTransportTopicEventCallback
TransportTopicEvent callback.
class Type
Typedefs
typedef MamaFieldCacheFieldBasic< char, MAMA_FIELD_TYPE_CHAR > MamaFieldCacheFieldChar
MamaFieldCacheFieldChar.
typedef MamaFieldCacheFieldBasic< mama_bool_t, MAMA_FIELD_TYPE_BOOL > MamaFieldCacheFieldBool
MamaFieldCacheFieldBool.
typedef MamaFieldCacheFieldBasic< mama_i8_t, MAMA_FIELD_TYPE_I8 > MamaFieldCacheFieldI8
MamaFieldCacheFieldI8.
typedef MamaFieldCacheFieldBasic< mama_u8_t, MAMA_FIELD_TYPE_U8 > MamaFieldCacheFieldU8
MamaFieldCacheFieldU8.
typedef MamaFieldCacheFieldBasic< mama_i16_t, MAMA_FIELD_TYPE_I16 > MamaFieldCacheFieldI16
MamaFieldCacheFieldI16.
typedef MamaFieldCacheFieldBasic< mama_u16_t, MAMA_FIELD_TYPE_U16 > MamaFieldCacheFieldU16
MamaFieldCacheFieldU16.
typedef MamaFieldCacheFieldBasic< mama_i32_t, MAMA_FIELD_TYPE_I32 > MamaFieldCacheFieldI32
MamaFieldCacheFieldI32.
typedef MamaFieldCacheFieldBasic< mama_u32_t, MAMA_FIELD_TYPE_U32 > MamaFieldCacheFieldU32
MamaFieldCacheFieldU32.
typedef MamaFieldCacheFieldBasic< mama_i64_t, MAMA_FIELD_TYPE_I64 > MamaFieldCacheFieldI64
MamaFieldCacheFieldI64.
typedef MamaFieldCacheFieldBasic< mama_u64_t, MAMA_FIELD_TYPE_U64 > MamaFieldCacheFieldU64
MamaFieldCacheFieldU64.
typedef MamaFieldCacheFieldBasic< mama_f32_t, MAMA_FIELD_TYPE_F32 > MamaFieldCacheFieldF32
MamaFieldCacheFieldF32.
typedef MamaFieldCacheFieldBasic< mama_f64_t, MAMA_FIELD_TYPE_F64 > MamaFieldCacheFieldF64
MamaFieldCacheFieldF64.
typedef MamaFieldCacheFieldVectorBasic< mama_bool_t, MAMA_FIELD_TYPE_VECTOR_BOOL > MamaFieldCacheFieldBoolVector
MamaFieldCacheFieldBoolVector.
typedef MamaFieldCacheFieldVectorBasic< char, MAMA_FIELD_TYPE_VECTOR_CHAR > MamaFieldCacheFieldCharVector
MamaFieldCacheFieldCharVector.
typedef MamaFieldCacheFieldVectorBasic< mama_i8_t, MAMA_FIELD_TYPE_VECTOR_I8 > MamaFieldCacheFieldI8Vector
MamaFieldCacheFieldI8Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_u8_t, MAMA_FIELD_TYPE_VECTOR_U8 > MamaFieldCacheFieldU8Vector
MamaFieldCacheFieldU8Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_i16_t, MAMA_FIELD_TYPE_VECTOR_I16 > MamaFieldCacheFieldI16Vector
MamaFieldCacheFieldI16Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_u16_t, MAMA_FIELD_TYPE_VECTOR_U16 > MamaFieldCacheFieldU16Vector
MamaFieldCacheFieldU16Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_i32_t, MAMA_FIELD_TYPE_VECTOR_I32 > MamaFieldCacheFieldI32Vector
MamaFieldCacheFieldI32Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_u32_t, MAMA_FIELD_TYPE_VECTOR_U32 > MamaFieldCacheFieldU32Vector
MamaFieldCacheFieldU32Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_i64_t, MAMA_FIELD_TYPE_VECTOR_I64 > MamaFieldCacheFieldI64Vector
MamaFieldCacheFieldI64Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_u64_t, MAMA_FIELD_TYPE_VECTOR_U64 > MamaFieldCacheFieldU64Vector
MamaFieldCacheFieldU64Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_f32_t, MAMA_FIELD_TYPE_VECTOR_F32 > MamaFieldCacheFieldF32Vector
MamaFieldCacheFieldF32Vector.
typedef MamaFieldCacheFieldVectorBasic< mama_f64_t, MAMA_FIELD_TYPE_VECTOR_F64 > MamaFieldCacheFieldF64Vector
MamaFieldCacheFieldF64Vector.
Functions
void setFieldValue (MamaFieldCacheField &field, const char *value)
Helper function to set the value of a String field.
void setFieldValue (MamaFieldCacheField &field, const MamaPrice &value)
Helper function to set the value of a MamaPrice field.
void setFieldValue (MamaFieldCacheField &field, const MamaDateTime &value)
Helper function to set the value of a MamaDateTime field.
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_CHAR > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_BOOL > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_I8 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_U8 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_I16 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_U16 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_I32 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_U32 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_I64 >, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_U64 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_F32 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void setV (Type< MAMA_FIELD_TYPE_F64 > type, MamaFieldCacheField &field, const T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_CHAR > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_BOOL > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_I8 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_U8 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_I16 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_U16 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_I32 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_U32 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_I64 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_U64 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_F32 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void getV (Type< MAMA_FIELD_TYPE_F64 > type, const MamaFieldCacheField &field, T &value)
template<typename T >
void setFieldValue (MamaFieldCacheField &field, const T &value)
Helper function to set the value of a generic single-value field.
void getFieldValue (const MamaFieldCacheField &field, const char *&value)
Helper function to get the value of a string field.
void getFieldValue (const MamaFieldCacheField &field, MamaPrice &value)
Helper function to get the value of a MamaPrice field.
void getFieldValue (const MamaFieldCacheField &field, MamaDateTime &value)
Helper function to get the value of a MamaDateTime field.
template<typename T >
void getFieldValue (const MamaFieldCacheField &field, T &value)
Helper function to get the value of a generic single-value field.
template<typename T >
void setFieldValue (MamaFieldCacheField &field, const T *values, mama_size_t size)
Helper function to set the values of a generic vector field.
void getFieldValue (const MamaFieldCacheField &field, const char **&values, mama_size_t &size)
Helper function to set the values of a string vector field.
void getFieldValue (const MamaFieldCacheField &field, const MamaPrice *&values, mama_size_t &size)
void getFieldValue (const MamaFieldCacheField &field, const mamaDateTime *&values, mama_size_t &size)
template<typename T >
void getFieldValue (const MamaFieldCacheField &field, const T *&values, mama_size_t &size)
Helper function to get the values of a generic vector field.
void mamaFieldCacheFieldFromString (MamaFieldCacheField &field, const std::string &value)
Typedef Documentation
MamaFieldCacheFieldChar
typedef MamaFieldCacheFieldBasic<char, MAMA_FIELD_TYPE_CHAR> Wombat::MamaFieldCacheFieldChar
MamaFieldCacheFieldChar.
Class used to set and get the value of a char single-value MamaFieldCacheField.
MamaFieldCacheFieldBool
typedef MamaFieldCacheFieldBasic<mama_bool_t, MAMA_FIELD_TYPE_BOOL> Wombat::MamaFieldCacheFieldBool
MamaFieldCacheFieldBool.
Class used to set and get the value of a bool single-value MamaFieldCacheField.
MamaFieldCacheFieldI8
typedef MamaFieldCacheFieldBasic<mama_i8_t, MAMA_FIELD_TYPE_I8> Wombat::MamaFieldCacheFieldI8
MamaFieldCacheFieldI8.
Class used to set and get the value of a mama_i8_t single-value MamaFieldCacheField.
MamaFieldCacheFieldU8
typedef MamaFieldCacheFieldBasic<mama_u8_t, MAMA_FIELD_TYPE_U8> Wombat::MamaFieldCacheFieldU8
MamaFieldCacheFieldU8.
Class used to set and get the value of a mama_u8_t single-value MamaFieldCacheField.
MamaFieldCacheFieldI16
typedef MamaFieldCacheFieldBasic<mama_i16_t, MAMA_FIELD_TYPE_I16> Wombat::MamaFieldCacheFieldI16
MamaFieldCacheFieldI16.
Class used to set and get the value of a mama_i16_t single-value MamaFieldCacheField.
MamaFieldCacheFieldU16
typedef MamaFieldCacheFieldBasic<mama_u16_t, MAMA_FIELD_TYPE_U16> Wombat::MamaFieldCacheFieldU16
MamaFieldCacheFieldU16.
Class used to set and get the value of a mama_u16_t single-value MamaFieldCacheField.
MamaFieldCacheFieldI32
typedef MamaFieldCacheFieldBasic<mama_i32_t, MAMA_FIELD_TYPE_I32> Wombat::MamaFieldCacheFieldI32
MamaFieldCacheFieldI32.
Class used to set and get the value of a mama_i32_t single-value MamaFieldCacheField.
MamaFieldCacheFieldU32
typedef MamaFieldCacheFieldBasic<mama_u32_t, MAMA_FIELD_TYPE_U32> Wombat::MamaFieldCacheFieldU32
MamaFieldCacheFieldU32.
Class used to set and get the value of a mama_u32_t single-value MamaFieldCacheField.
MamaFieldCacheFieldI64
typedef MamaFieldCacheFieldBasic<mama_i64_t, MAMA_FIELD_TYPE_I64> Wombat::MamaFieldCacheFieldI64
MamaFieldCacheFieldI64.
Class used to set and get the value of a mama_i64_t single-value MamaFieldCacheField.
MamaFieldCacheFieldU64
typedef MamaFieldCacheFieldBasic<mama_u64_t, MAMA_FIELD_TYPE_U64> Wombat::MamaFieldCacheFieldU64
MamaFieldCacheFieldU64.
Class used to set and get the value of a mama_u64_t single-value MamaFieldCacheField.
MamaFieldCacheFieldF32
typedef MamaFieldCacheFieldBasic<mama_f32_t, MAMA_FIELD_TYPE_F32> Wombat::MamaFieldCacheFieldF32
MamaFieldCacheFieldF32.
Class used to set and get the value of a mama_f32_t single-value MamaFieldCacheField.
MamaFieldCacheFieldF64
typedef MamaFieldCacheFieldBasic<mama_f64_t, MAMA_FIELD_TYPE_F64> Wombat::MamaFieldCacheFieldF64
MamaFieldCacheFieldF64.
Class used to set and get the value of a mama_f64_t single-value MamaFieldCacheField.
MamaFieldCacheFieldBoolVector
typedef MamaFieldCacheFieldVectorBasic<mama_bool_t, MAMA_FIELD_TYPE_VECTOR_BOOL> Wombat::MamaFieldCacheFieldBoolVector
MamaFieldCacheFieldBoolVector.
Class used to set and get the value of a mama_bool_t vector MamaFieldCacheField.
MamaFieldCacheFieldCharVector
typedef MamaFieldCacheFieldVectorBasic<char, MAMA_FIELD_TYPE_VECTOR_CHAR> Wombat::MamaFieldCacheFieldCharVector
MamaFieldCacheFieldCharVector.
Class used to set and get the value of a char vector MamaFieldCacheField.
MamaFieldCacheFieldI8Vector
typedef MamaFieldCacheFieldVectorBasic<mama_i8_t, MAMA_FIELD_TYPE_VECTOR_I8> Wombat::MamaFieldCacheFieldI8Vector
MamaFieldCacheFieldI8Vector.
Class used to set and get the value of a mama_i8_t vector MamaFieldCacheField.
MamaFieldCacheFieldU8Vector
typedef MamaFieldCacheFieldVectorBasic<mama_u8_t, MAMA_FIELD_TYPE_VECTOR_U8> Wombat::MamaFieldCacheFieldU8Vector
MamaFieldCacheFieldU8Vector.
Class used to set and get the value of a mama_u8_t vector MamaFieldCacheField.
MamaFieldCacheFieldI16Vector
typedef MamaFieldCacheFieldVectorBasic<mama_i16_t, MAMA_FIELD_TYPE_VECTOR_I16> Wombat::MamaFieldCacheFieldI16Vector
MamaFieldCacheFieldI16Vector.
Class used to set and get the value of a mama_i16_t vector MamaFieldCacheField.
MamaFieldCacheFieldU16Vector
typedef MamaFieldCacheFieldVectorBasic<mama_u16_t, MAMA_FIELD_TYPE_VECTOR_U16> Wombat::MamaFieldCacheFieldU16Vector
MamaFieldCacheFieldU16Vector.
Class used to set and get the value of a mama_u16_t vector MamaFieldCacheField.
MamaFieldCacheFieldI32Vector
typedef MamaFieldCacheFieldVectorBasic<mama_i32_t, MAMA_FIELD_TYPE_VECTOR_I32> Wombat::MamaFieldCacheFieldI32Vector
MamaFieldCacheFieldI32Vector.
Class used to set and get the value of a mama_i32_t vector MamaFieldCacheField.
MamaFieldCacheFieldU32Vector
typedef MamaFieldCacheFieldVectorBasic<mama_u32_t, MAMA_FIELD_TYPE_VECTOR_U32> Wombat::MamaFieldCacheFieldU32Vector
MamaFieldCacheFieldU32Vector.
Class used to set and get the value of a mama_u32_t vector MamaFieldCacheField.
MamaFieldCacheFieldI64Vector
typedef MamaFieldCacheFieldVectorBasic<mama_i64_t, MAMA_FIELD_TYPE_VECTOR_I64> Wombat::MamaFieldCacheFieldI64Vector
MamaFieldCacheFieldI64Vector.
Class used to set and get the value of a mama_i64_t vector MamaFieldCacheField.
MamaFieldCacheFieldU64Vector
typedef MamaFieldCacheFieldVectorBasic<mama_u64_t, MAMA_FIELD_TYPE_VECTOR_U64> Wombat::MamaFieldCacheFieldU64Vector
MamaFieldCacheFieldU64Vector.
Class used to set and get the value of a mama_u64_t vector MamaFieldCacheField.
MamaFieldCacheFieldF32Vector
typedef MamaFieldCacheFieldVectorBasic<mama_f32_t, MAMA_FIELD_TYPE_VECTOR_F32> Wombat::MamaFieldCacheFieldF32Vector
MamaFieldCacheFieldF32Vector.
Class used to set and get the value of a mama_f32_t vector MamaFieldCacheField.
MamaFieldCacheFieldF64Vector
typedef MamaFieldCacheFieldVectorBasic<mama_f64_t, MAMA_FIELD_TYPE_VECTOR_F64> Wombat::MamaFieldCacheFieldF64Vector
MamaFieldCacheFieldF64Vector.
Class used to set and get the value of a mama_f64_t vector MamaFieldCacheField.
Function Documentation
setFieldValue() [1/5]
void Wombat::setFieldValue (MamaFieldCacheField & field, const char * value)
Helper function to set the value of a String field.
Parameters
field The field to set the value to.
value The value to set.
Referenced by Wombat::MamaFieldCacheFieldDateTimeVector::checkType().
setFieldValue() [2/5]
void Wombat::setFieldValue (MamaFieldCacheField & field, const MamaPrice & value)
Helper function to set the value of a MamaPrice field.
Parameters
field The field to set the value to.
value The value to set.
setFieldValue() [3/5]
void Wombat::setFieldValue (MamaFieldCacheField & field, const MamaDateTime & value)
Helper function to set the value of a MamaDateTime field.
Parameters
field The field to set the value to.
value The value to set.
setV() [1/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_CHAR > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
Referenced by setFieldValue().
setV() [2/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_BOOL > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [3/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_I8 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [4/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_U8 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [5/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_I16 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [6/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_U16 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [7/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_I32 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [8/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_U32 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [9/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_I64 > , MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [10/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_U64 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [11/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_F32 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
setV() [12/12]
template<typename T > void Wombat::setV (Type< MAMA_FIELD_TYPE_F64 > type, MamaFieldCacheField & field, const T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::set().
getV() [1/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_CHAR > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
Referenced by getFieldValue().
getV() [2/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_BOOL > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [3/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_I8 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [4/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_U8 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [5/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_I16 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [6/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_U16 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [7/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_I32 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [8/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_U32 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [9/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_I64 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [10/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_U64 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [11/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_F32 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
getV() [12/12]
template<typename T > void Wombat::getV (Type< MAMA_FIELD_TYPE_F64 > type, const MamaFieldCacheField & field, T & value)
References Wombat::MamaFieldCacheFieldBasic< T, fieldType >::get().
setFieldValue() [4/5]
template<typename T > void Wombat::setFieldValue (MamaFieldCacheField & field, const T & value)
Helper function to set the value of a generic single-value field.
Parameters
field The field to set the value to.
value The value to set.
References getFieldValue(), Wombat::MamaFieldCacheField::getType(), and setV().
getFieldValue() [1/8]
void Wombat::getFieldValue (const MamaFieldCacheField & field, const char *& value)
Helper function to get the value of a string field.
Parameters
field The field to get the value from.
value The value to return.
Referenced by setFieldValue().
getFieldValue() [2/8]
void Wombat::getFieldValue (const MamaFieldCacheField & field, MamaPrice & value)
Helper function to get the value of a MamaPrice field.
Parameters
field The field to get the value from.
value The value to return.
getFieldValue() [3/8]
void Wombat::getFieldValue (const MamaFieldCacheField & field, MamaDateTime & value)
Helper function to get the value of a MamaDateTime field.
Parameters
field The field to get the value from.
value The value to return.
getFieldValue() [4/8]
template<typename T > void Wombat::getFieldValue (const MamaFieldCacheField & field, T & value)
Helper function to get the value of a generic single-value field.
Parameters
field The field to get the value from.
value The value to return.
References Wombat::MamaFieldCacheField::getType(), and getV().
setFieldValue() [5/5]
template<typename T > void Wombat::setFieldValue (MamaFieldCacheField & field, const T * values, mama_size_t size)
Helper function to set the values of a generic vector field.
Parameters
field The field to set the values to.
values The values to set.
size The number of values in the field.
References getFieldValue(), Wombat::MamaFieldCacheField::getType(), Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::set(), Wombat::MamaFieldCacheFieldStringVector::set(), Wombat::MamaFieldCacheFieldPriceVector::set(), and Wombat::MamaFieldCacheFieldDateTimeVector::set().
getFieldValue() [5/8]
void Wombat::getFieldValue (const MamaFieldCacheField & field, const char **& values, mama_size_t & size)
Helper function to set the values of a string vector field.
Parameters
field The field to set the values to.
values The values to set.
size The number of values in the field.
getFieldValue() [6/8]
void Wombat::getFieldValue (const MamaFieldCacheField & field, const MamaPrice *& values, mama_size_t & size)
getFieldValue() [7/8]
void Wombat::getFieldValue (const MamaFieldCacheField & field, const mamaDateTime *& values, mama_size_t & size)
getFieldValue() [8/8]
template<typename T > void Wombat::getFieldValue (const MamaFieldCacheField & field, const T *& values, mama_size_t & size)
Helper function to get the values of a generic vector field.
Parameters
field The field to get the values from.
values The values to return.
size The number of values in the field.
References Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::get(), Wombat::MamaFieldCacheField::getType(), and mamaFieldCacheFieldFromString().
mamaFieldCacheFieldFromString()
void Wombat::mamaFieldCacheFieldFromString (MamaFieldCacheField & field, const std::string & value)
Referenced by getFieldValue().