OpenMAMDA C++ API: MamdaOrderBookDepthFilter Class Reference
MamdaOrderBookDepthFilter Class Reference
#include <MamdaOrderBookDepthFilter.h>
Public Member Functions
MamdaOrderBookDepthFilter (MamdaOrderBookListener &parent, size_t depth)
virtual ~MamdaOrderBookDepthFilter ()
virtual void addHandler (MamdaOrderBookHandler *handler)
Add a specialized order book handler.
virtual void removeHandlers ()
Remove the reference of handlers from the internal list.
virtual const MamdaOrderBook * getOrderBook () const
Return the filtered orderbook.
virtual const MamdaOrderBook * getFullOrderBook () const
Return the full depth orderbook.
virtual void onMsg (MamdaSubscription *subscription, const MamaMsg &msg, short msgType)
virtual void onBookRecap (MamdaSubscription *subscription, MamdaOrderBookListener &listener, const MamaMsg *msg, const MamdaOrderBookComplexDelta *delta, const MamdaOrderBookRecap &event, const MamdaOrderBook &book)
virtual void onBookDelta (MamdaSubscription *subscription, MamdaOrderBookListener &listener, const MamaMsg *msg, const MamdaOrderBookSimpleDelta &event, const MamdaOrderBook &book)
virtual void onBookComplexDelta (MamdaSubscription *subscription, MamdaOrderBookListener &listener, const MamaMsg *msg, const MamdaOrderBookComplexDelta &event, const MamdaOrderBook &book)
virtual void onBookClear (MamdaSubscription *subscription, MamdaOrderBookListener &listener, const MamaMsg *msg, const MamdaOrderBookClear &event, const MamdaOrderBook &book)
virtual void onBookGap (MamdaSubscription *subscription, MamdaOrderBookListener &listener, const MamaMsg *msg, const MamdaOrderBookGap &event, const MamdaOrderBook &book)
Constructor & Destructor Documentation
MamdaOrderBookDepthFilter()
MamdaOrderBookDepthFilter::MamdaOrderBookDepthFilter (MamdaOrderBookListener & parent, size_t depth)
~MamdaOrderBookDepthFilter()
virtual MamdaOrderBookDepthFilter::~MamdaOrderBookDepthFilter () virtual
Member Function Documentation
addHandler()
virtual void MamdaOrderBookDepthFilter::addHandler (MamdaOrderBookHandler * handler) virtual
Add a specialized order book handler.
Currently, only one handler can (and must) be registered.
Parameters
handler The hadler registered to receive order book update callbacks.
removeHandlers()
virtual void MamdaOrderBookDepthFilter::removeHandlers () virtual
Remove the reference of handlers from the internal list.
Memory is not freed.
getOrderBook()
virtual const MamdaOrderBook* MamdaOrderBookDepthFilter::getOrderBook () const virtual
Return the filtered orderbook.
getFullOrderBook()
virtual const MamdaOrderBook* MamdaOrderBookDepthFilter::getFullOrderBook () const virtual
Return the full depth orderbook.
onMsg()
virtual void MamdaOrderBookDepthFilter::onMsg (MamdaSubscription * subscription, const MamaMsg & msg, short msgType) inline virtual
References onBookClear(), onBookComplexDelta(), onBookDelta(), onBookGap(), and onBookRecap().
onBookRecap()
virtual void MamdaOrderBookDepthFilter::onBookRecap (MamdaSubscription * subscription, MamdaOrderBookListener & listener, const MamaMsg * msg, const MamdaOrderBookComplexDelta * delta, const MamdaOrderBookRecap & event, const MamdaOrderBook & book) virtual
Referenced by onMsg().
onBookDelta()
virtual void MamdaOrderBookDepthFilter::onBookDelta (MamdaSubscription * subscription, MamdaOrderBookListener & listener, const MamaMsg * msg, const MamdaOrderBookSimpleDelta & event, const MamdaOrderBook & book) virtual
Referenced by onMsg().
onBookComplexDelta()
virtual void MamdaOrderBookDepthFilter::onBookComplexDelta (MamdaSubscription * subscription, MamdaOrderBookListener & listener, const MamaMsg * msg, const MamdaOrderBookComplexDelta & event, const MamdaOrderBook & book) virtual
Referenced by onMsg().
onBookClear()
virtual void MamdaOrderBookDepthFilter::onBookClear (MamdaSubscription * subscription, MamdaOrderBookListener & listener, const MamaMsg * msg, const MamdaOrderBookClear & event, const MamdaOrderBook & book) virtual
Referenced by onMsg().
onBookGap()
virtual void MamdaOrderBookDepthFilter::onBookGap (MamdaSubscription * subscription, MamdaOrderBookListener & listener, const MamaMsg * msg, const MamdaOrderBookGap & event, const MamdaOrderBook & book) virtual
Referenced by onMsg().