OpenMAMDA C# API: Wombat.MamdaOrderBookChecker Class Reference
Wombat.MamdaOrderBookChecker Class Reference
TODOC:
Public Member Functions
MamdaOrderBookChecker (MamaTransport transport, MamaQueue queue, MamdaOrderBookCheckerHandler handler, string source, string symbol, double intervalSeconds)
MamdaOrderBookChecker (MamdaSubscription realTimeSubsc, MamdaOrderBookListener realTimeListener, MamdaOrderBookCheckerHandler handler, double intervalSeconds)
long getSuccessCount ()
long getInconclusiveCount ()
long getFailureCount ()
void checkSnapShotNow ()
Detailed Description
TODOC:
Constructor & Destructor Documentation
MamdaOrderBookChecker() [1/2]
Wombat.MamdaOrderBookChecker.MamdaOrderBookChecker (MamaTransport transport, MamaQueue queue, MamdaOrderBookCheckerHandler handler, string source, string symbol, double intervalSeconds)
Parameters
transport
queue
handler
source
symbol
intervalSeconds
References Wombat.MamdaSubscription.addMsgListener(), Wombat.MamdaSubscription.create(), and Wombat.MamdaSubscription.setType().
MamdaOrderBookChecker() [2/2]
Wombat.MamdaOrderBookChecker.MamdaOrderBookChecker (MamdaSubscription realTimeSubsc, MamdaOrderBookListener realTimeListener, MamdaOrderBookCheckerHandler handler, double intervalSeconds)
Parameters
realTimeSubsc
realTimeListener
handler
intervalSeconds
Member Function Documentation
getSuccessCount()
long Wombat.MamdaOrderBookChecker.getSuccessCount ()
Returns
getInconclusiveCount()
long Wombat.MamdaOrderBookChecker.getInconclusiveCount ()
Returns
getFailureCount()
long Wombat.MamdaOrderBookChecker.getFailureCount ()
Returns
References Wombat.MamdaOrderBookListener.addHandler(), and Wombat.MamdaSubscription.addMsgListener().
checkSnapShotNow()
void Wombat.MamdaOrderBookChecker.checkSnapShotNow ()
References Wombat.MamdaOrderBookCheckType.APPLY_DELTA, Wombat.MamdaOrderBook.assertEqual(), Wombat.MamdaOrderBookListener.clear(), Wombat.MamdaSubscription.create(), Wombat.MamdaSubscription.deactivate(), Wombat.MamdaOrderBookRecap.getFullOrderBook(), Wombat.MamdaOrderBookListener.getFullOrderBook(), Wombat.MamdaSubscription.getQueue(), Wombat.MamdaOrderBookListener.getSeqNum(), Wombat.MamdaSubscription.getSource(), Wombat.MamdaSubscription.getSymbol(), Wombat.MamdaSubscription.getTransport(), Wombat.MamdaOrderBookCheckerHandler.onFailure(), Wombat.MamdaOrderBookCheckerHandler.onInconclusive(), Wombat.MamdaOrderBookCheckerHandler.onSuccess(), Wombat.MamdaSubscription.setServiceLevel(), Wombat.MamdaSubscription.setType(), and Wombat.MamdaOrderBookCheckType.SNAPSHOT.