OpenMAMDA C# API: Wombat.MamdaQuoteListener Class Reference
Wombat.MamdaQuoteListener Class Reference
MamdaQuoteListener is a class that specializes in handling quote updates.
Inherits Wombat.MamdaMsgListener, Wombat.MamdaQuoteRecap, Wombat.MamdaQuoteUpdate, Wombat.MamdaQuoteGap, and Wombat.MamdaQuoteClosing.
Public Member Functions
MamdaQuoteListener ()
Create a specialized quote listener.
void addHandler (MamdaQuoteHandler handler)
Add a specialized quote handler.
string getSymbol ()
Symbol.
string getPartId ()
Participant ID.
DateTime getSrcTime ()
Returns the source time.
DateTime getActivityTime ()
DateTime getLineTime ()
Line time.
DateTime getSendTime ()
Send time.
string getPubId ()
MamaPrice getBidPrice ()
Get the closing bid price.
long getBidSize ()
Get the closing bid size.
long getBidDepth ()
string getBidPartId ()
Get the closing bid participant identifier.
MamaPrice getBidClosePrice ()
DateTime getBidCloseDate ()
MamaPrice getBidPrevClosePrice ()
DateTime getBidPrevCloseDate ()
MamaPrice getBidHigh ()
MamaPrice getBidLow ()
MamaPrice getAskPrice ()
Get the closing ask price.
long getAskSize ()
Get the closing ask size.
long getAskDepth ()
string getAskPartId ()
Get the closing ask participant identifier.
MamaPrice getAskClosePrice ()
DateTime getAskCloseDate ()
MamaPrice getAskPrevClosePrice ()
DateTime getAskPrevCloseDate ()
MamaPrice getAskHigh ()
MamaPrice getAskLow ()
MamaPrice getQuoteMidPrice ()
Get the quote mid price.
string getQuoteQual ()
Get the normalized quote qualifier.
string getQuoteQualNative ()
MamdaQuoteUpdate.getQuoteQualNative()
char getShortSaleBidTick ()
MamdaQuoteUpdate.getShortSaleBidTick()
char getShortSaleCircuitBreaker ()
MamdaQuoteUpdate.getShortSaleCircuitBreaker()
long getQuoteCount ()
Get the quote count.
long getEventSeqNum ()
DateTime getEventTime ()
DateTime getQuoteDate ()
long getBeginGapSeqNum ()
The starting sequence number of detected missing quotes based on the quote count.
long getEndGapSeqNum ()
The end sequence number of detected missing quotes based on the quote count.
DateTime getAskTime ()
DateTime getBidTime ()
string getAskIndicator ()
string getBidIndicator ()
long getAskUpdateCount ()
long getBidUpdateCount ()
double getAskYield ()
double getBidYield ()
MamdaFieldState getSymbolFieldState ()
Returns the field state.
MamdaFieldState getPartIdFieldState ()
Returns the field state.
MamdaFieldState getSrcTimeFieldState ()
Returns the field state.
MamdaFieldState getActivityTimeFieldState ()
Returns the field state.
MamdaFieldState getLineTimeFieldState ()
Returns the field state.
MamdaFieldState getSendTimeFieldState ()
Returns the field state.
MamdaFieldState getPubIdFieldState ()
MamdaFieldState getBidPriceFieldState ()
Get the field state
MamdaFieldState getBidSizeFieldState ()
Get the field state
MamdaFieldState getBidDepthFieldState ()
MamdaFieldState getBidPartIdFieldState ()
Get the field state
MamdaFieldState getBidClosePriceFieldState ()
MamdaFieldState getBidCloseDateFieldState ()
MamdaFieldState getBidPrevClosePriceFieldState ()
MamdaFieldState getBidPrevCloseDateFieldState ()
MamdaFieldState getBidHighFieldState ()
MamdaFieldState getBidLowFieldState ()
MamdaFieldState getAskPriceFieldState ()
Get the field state
MamdaFieldState getAskSizeFieldState ()
Get the field state
MamdaFieldState getAskDepthFieldState ()
MamdaFieldState getAskPartIdFieldState ()
Get the field state
MamdaFieldState getAskClosePriceFieldState ()
MamdaFieldState getAskCloseDateFieldState ()
MamdaFieldState getAskPrevClosePriceFieldState ()
MamdaFieldState getAskPrevCloseDateFieldState ()
MamdaFieldState getAskHighFieldState ()
MamdaFieldState getAskLowFieldState ()
MamdaFieldState getQuoteQualFieldState ()
Get the field state
MamdaFieldState getQuoteQualNativeFieldState ()
Get the field state
MamdaFieldState getShortSaleBidTickFieldState ()
Get the field state
MamdaFieldState getShortSaleCircuitBreakerFieldState ()
Get the field state
MamdaFieldState getQuoteCountFieldState ()
Get the field state
MamdaFieldState getEventSeqNumFieldState ()
Returns the field state.
MamdaFieldState getEventTimeFieldState ()
Returns the field state.
MamdaFieldState getQuoteDateFieldState ()
MamdaFieldState getBeginGapSeqNumFieldState ()
Get the field state
MamdaFieldState getEndGapSeqNumFieldState ()
Get the field state
MamdaFieldState getAskTimeFieldState ()
MamdaFieldState getBidTimeFieldState ()
MamdaFieldState getAskIndicatorFieldState ()
MamdaFieldState getBidIndicatorFieldState ()
MamdaFieldState getAskUpdateCountFieldState ()
MamdaFieldState getBidUpdateCountFieldState ()
MamdaFieldState getAskYieldFieldState ()
MamdaFieldState getBidYieldFieldState ()
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
void populateRecap (MamdaConcreteQuoteRecap recap)
Detailed Description
MamdaQuoteListener is a class that specializes in handling quote updates.
Developers provide their own implementation of the MamdaQuoteHandler interface and will be delivered notifications for quotes and quote closing prices. An obvious application for this MAMDA class is any kind of quote tick capture application.
Note: The MamdaQuoteListener class caches quote-related field values. Among other reasons, caching of these fields makes it possible to provide complete quote-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaQuoteListener()
Wombat.MamdaQuoteListener.MamdaQuoteListener ()
Create a specialized quote listener.
This listener handles quote updates, quote recaps, and quote gap notifications.
Member Function Documentation
addHandler()
void Wombat.MamdaQuoteListener.addHandler (MamdaQuoteHandler handler)
Add a specialized quote handler.
Currently, only one handler can (and must) be registered.
Parameters
handler
Referenced by Wombat.MamdaOptionUnderlying.addQuoteHandler(), and Wombat.MamdaOptionContract.addQuoteHandler().
getSymbol()
string Wombat.MamdaQuoteListener.getSymbol ()
Symbol.
This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements Wombat.MamdaBasicRecap.
getPartId()
string Wombat.MamdaQuoteListener.getPartId ()
Participant ID.
This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements Wombat.MamdaBasicRecap.
getSrcTime()
DateTime Wombat.MamdaQuoteListener.getSrcTime ()
Returns the source time.
Returns
Source time. Typically, the exchange generated feed
time stamp. This is often the same as the "event time",
because many feeds do not distinguish between the actual event
time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getActivityTime()
DateTime Wombat.MamdaQuoteListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements Wombat.MamdaBasicEvent.
getLineTime()
DateTime Wombat.MamdaQuoteListener.getLineTime ()
Line time.
A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements Wombat.MamdaBasicRecap.
getSendTime()
DateTime Wombat.MamdaQuoteListener.getSendTime ()
Send time.
A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware). See MAMA API: MamaDateTime::currentTime()).
Implements Wombat.MamdaBasicRecap.
getPubId()
string Wombat.MamdaQuoteListener.getPubId ()
getBidPrice()
MamaPrice Wombat.MamdaQuoteListener.getBidPrice ()
Get the closing bid price.
Returns
Today's closing bid price, after the market has closed and the stock has traded today.
Implements Wombat.MamdaQuoteClosing.
Referenced by Wombat.MamdaOptionChain.getAtTheMoney().
getBidSize()
long Wombat.MamdaQuoteListener.getBidSize ()
Get the closing bid size.
Returns
Today's closing bid size, after the market has closed and the stock has traded today.
Implements Wombat.MamdaQuoteClosing.
getBidDepth()
long Wombat.MamdaQuoteListener.getBidDepth ()
getBidPartId()
string Wombat.MamdaQuoteListener.getBidPartId ()
Get the closing bid participant identifier.
Returns
Today's closing bid participant identifier, after the market has closed and the stock has traded today.
Implements Wombat.MamdaQuoteClosing.
getBidClosePrice()
MamaPrice Wombat.MamdaQuoteListener.getBidClosePrice ()
getBidCloseDate()
DateTime Wombat.MamdaQuoteListener.getBidCloseDate ()
getBidPrevClosePrice()
MamaPrice Wombat.MamdaQuoteListener.getBidPrevClosePrice ()
getBidPrevCloseDate()
DateTime Wombat.MamdaQuoteListener.getBidPrevCloseDate ()
getBidHigh()
MamaPrice Wombat.MamdaQuoteListener.getBidHigh ()
getBidLow()
MamaPrice Wombat.MamdaQuoteListener.getBidLow ()
getAskPrice()
MamaPrice Wombat.MamdaQuoteListener.getAskPrice ()
Get the closing ask price.
Returns
Today's closing ask price, after the market has closed and the stock has traded today.
Implements Wombat.MamdaQuoteClosing.
Referenced by Wombat.MamdaOptionChain.getAtTheMoney().
getAskSize()
long Wombat.MamdaQuoteListener.getAskSize ()
Get the closing ask size.
Returns
Today's closing ask size, after the market has closed and the stock has traded today.
Implements Wombat.MamdaQuoteClosing.
getAskDepth()
long Wombat.MamdaQuoteListener.getAskDepth ()
getAskPartId()
string Wombat.MamdaQuoteListener.getAskPartId ()
Get the closing ask participant identifier.
Returns
Today's closing ask participant identifier, after the market has closed and the stock has traded today.
Implements Wombat.MamdaQuoteClosing.
getAskClosePrice()
MamaPrice Wombat.MamdaQuoteListener.getAskClosePrice ()
getAskCloseDate()
DateTime Wombat.MamdaQuoteListener.getAskCloseDate ()
getAskPrevClosePrice()
MamaPrice Wombat.MamdaQuoteListener.getAskPrevClosePrice ()
getAskPrevCloseDate()
DateTime Wombat.MamdaQuoteListener.getAskPrevCloseDate ()
getAskHigh()
MamaPrice Wombat.MamdaQuoteListener.getAskHigh ()
getAskLow()
MamaPrice Wombat.MamdaQuoteListener.getAskLow ()
getQuoteMidPrice()
MamaPrice Wombat.MamdaQuoteListener.getQuoteMidPrice ()
Get the quote mid price.
Returns
The mid price of the current quote. Usually, this is the average of the bid and ask prices, but some exchanges provide this field explicitly.
Implements Wombat.MamdaQuoteRecap.
getQuoteQual()
string Wombat.MamdaQuoteListener.getQuoteQual ()
Get the normalized quote qualifier.
Returns
A normalized set of qualifiers for the last quote for the security. This field may contain multiple string values, separated by the colon(:) character. MamdaQuoteUpdate.getQuoteQual
Implements Wombat.MamdaQuoteRecap.
getQuoteQualNative()
string Wombat.MamdaQuoteListener.getQuoteQualNative ()
MamdaQuoteUpdate.getQuoteQualNative()
Returns
Implements Wombat.MamdaQuoteRecap.
getShortSaleBidTick()
char Wombat.MamdaQuoteListener.getShortSaleBidTick ()
MamdaQuoteUpdate.getShortSaleBidTick()
Returns
Implements Wombat.MamdaQuoteRecap.
getShortSaleCircuitBreaker()
char Wombat.MamdaQuoteListener.getShortSaleCircuitBreaker ()
MamdaQuoteUpdate.getShortSaleCircuitBreaker()
Returns
Implements Wombat.MamdaQuoteRecap.
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getQuoteCount()
long Wombat.MamdaQuoteListener.getQuoteCount ()
Get the quote count.
Returns
The number of quotes generated for this security during the current trading session.
Implements Wombat.MamdaQuoteRecap.
getEventSeqNum()
long Wombat.MamdaQuoteListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements Wombat.MamdaBasicEvent.
getEventTime()
DateTime Wombat.MamdaQuoteListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getQuoteDate()
DateTime Wombat.MamdaQuoteListener.getQuoteDate ()
Implements Wombat.MamdaQuoteRecap.
getBeginGapSeqNum()
long Wombat.MamdaQuoteListener.getBeginGapSeqNum ()
The starting sequence number of detected missing quotes based on the quote count.
Returns
Implements Wombat.MamdaQuoteGap.
getEndGapSeqNum()
long Wombat.MamdaQuoteListener.getEndGapSeqNum ()
The end sequence number of detected missing quotes based on the quote count.
Returns
Implements Wombat.MamdaQuoteGap.
getAskTime()
DateTime Wombat.MamdaQuoteListener.getAskTime ()
Implements Wombat.MamdaQuoteRecap.
getBidTime()
DateTime Wombat.MamdaQuoteListener.getBidTime ()
Implements Wombat.MamdaQuoteRecap.
getAskIndicator()
string Wombat.MamdaQuoteListener.getAskIndicator ()
Implements Wombat.MamdaQuoteRecap.
getBidIndicator()
string Wombat.MamdaQuoteListener.getBidIndicator ()
Implements Wombat.MamdaQuoteRecap.
getAskUpdateCount()
long Wombat.MamdaQuoteListener.getAskUpdateCount ()
Implements Wombat.MamdaQuoteRecap.
getBidUpdateCount()
long Wombat.MamdaQuoteListener.getBidUpdateCount ()
Implements Wombat.MamdaQuoteRecap.
getAskYield()
double Wombat.MamdaQuoteListener.getAskYield ()
Implements Wombat.MamdaQuoteRecap.
getBidYield()
double Wombat.MamdaQuoteListener.getBidYield ()
Implements Wombat.MamdaQuoteRecap.
getSymbolFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getSymbolFieldState ()
Returns the field state.
Returns
Symbol Field State
Implements Wombat.MamdaBasicRecap.
getPartIdFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getPartIdFieldState ()
Returns the field state.
Returns
Participant ID Field State
Implements Wombat.MamdaBasicRecap.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getSrcTimeFieldState ()
Returns the field state.
Returns
Source time Field State
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getActivityTimeFieldState ()
Returns the field state.
Returns
Activity time Field State
Implements Wombat.MamdaBasicEvent.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getLineTimeFieldState ()
Returns the field state.
Returns
Line Time Field State
Implements Wombat.MamdaBasicRecap.
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getSendTimeFieldState ()
Returns the field state.
Returns
Send time Field State
Implements Wombat.MamdaBasicRecap.
getPubIdFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getPubIdFieldState ()
getBidPriceFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteClosing.
getBidSizeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidSizeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteClosing.
getBidDepthFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidDepthFieldState ()
getBidPartIdFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidPartIdFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteClosing.
getBidClosePriceFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidClosePriceFieldState ()
getBidCloseDateFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidCloseDateFieldState ()
getBidPrevClosePriceFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidPrevClosePriceFieldState ()
getBidPrevCloseDateFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidPrevCloseDateFieldState ()
getBidHighFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidHighFieldState ()
getBidLowFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidLowFieldState ()
getAskPriceFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteClosing.
getAskSizeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskSizeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteClosing.
getAskDepthFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskDepthFieldState ()
getAskPartIdFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskPartIdFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteClosing.
getAskClosePriceFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskClosePriceFieldState ()
getAskCloseDateFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskCloseDateFieldState ()
getAskPrevClosePriceFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskPrevClosePriceFieldState ()
getAskPrevCloseDateFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskPrevCloseDateFieldState ()
getAskHighFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskHighFieldState ()
getAskLowFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskLowFieldState ()
getQuoteQualFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getQuoteQualFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteRecap.
getQuoteQualNativeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getQuoteQualNativeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteRecap.
getShortSaleBidTickFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getShortSaleBidTickFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteRecap.
getShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getShortSaleCircuitBreakerFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteRecap.
getQuoteCountFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getQuoteCountFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteRecap.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getEventSeqNumFieldState ()
Returns the field state.
Returns
Source sequence number Field State
Implements Wombat.MamdaBasicEvent.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getEventTimeFieldState ()
Returns the field state.
Returns
Event Time Field State
Implements Wombat.MamdaBasicEvent.
getQuoteDateFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getQuoteDateFieldState ()
Implements Wombat.MamdaQuoteRecap.
getBeginGapSeqNumFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBeginGapSeqNumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteGap.
getEndGapSeqNumFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getEndGapSeqNumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaQuoteGap.
getAskTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskTimeFieldState ()
Implements Wombat.MamdaQuoteRecap.
getBidTimeFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidTimeFieldState ()
Implements Wombat.MamdaQuoteRecap.
getAskIndicatorFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskIndicatorFieldState ()
Implements Wombat.MamdaQuoteRecap.
getBidIndicatorFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidIndicatorFieldState ()
Implements Wombat.MamdaQuoteRecap.
getAskUpdateCountFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskUpdateCountFieldState ()
Implements Wombat.MamdaQuoteRecap.
getBidUpdateCountFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidUpdateCountFieldState ()
Implements Wombat.MamdaQuoteRecap.
getAskYieldFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getAskYieldFieldState ()
Implements Wombat.MamdaQuoteRecap.
getBidYieldFieldState()
MamdaFieldState Wombat.MamdaQuoteListener.getBidYieldFieldState ()
Implements Wombat.MamdaQuoteRecap.
onMsg()
void Wombat.MamdaQuoteListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Parameters
subscription The MamdaSubscription to which this listener was registered.
msg The MamaMsg received by the underlying MAMA API and which resulted in this callback being invoked.
msgType The message type. e.g. INITIAL, RECAP, UPDATE etc.
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaQuoteFields.isSet().
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
populateRecap()
void Wombat.MamdaQuoteListener.populateRecap (MamdaConcreteQuoteRecap recap)
References Wombat.MamdaQuoteFields.ACTIVITY_TIME, Wombat.MamdaQuoteFields.ASK_CLOSE_DATE, Wombat.MamdaQuoteFields.ASK_CLOSE_PRICE, Wombat.MamdaQuoteFields.ASK_DEPTH, Wombat.MamdaQuoteFields.ASK_HIGH, Wombat.MamdaQuoteFields.ASK_INDICATOR, Wombat.MamdaQuoteFields.ASK_LOW, Wombat.MamdaQuoteFields.ASK_PART_ID, Wombat.MamdaQuoteFields.ASK_PREV_CLOSE_DATE, Wombat.MamdaQuoteFields.ASK_PREV_CLOSE_PRICE, Wombat.MamdaQuoteFields.ASK_PRICE, Wombat.MamdaQuoteFields.ASK_SIZE, Wombat.MamdaQuoteFields.ASK_TIME, Wombat.MamdaQuoteFields.ASK_UPDATE_COUNT, Wombat.MamdaQuoteFields.ASK_YIELD, Wombat.MamdaQuoteFields.BID_CLOSE_DATE, Wombat.MamdaQuoteFields.BID_CLOSE_PRICE, Wombat.MamdaQuoteFields.BID_DEPTH, Wombat.MamdaQuoteFields.BID_HIGH, Wombat.MamdaQuoteFields.BID_INDICATOR, Wombat.MamdaQuoteFields.BID_LOW, Wombat.MamdaQuoteFields.BID_PART_ID, Wombat.MamdaQuoteFields.BID_PREV_CLOSE_DATE, Wombat.MamdaQuoteFields.BID_PREV_CLOSE_PRICE, Wombat.MamdaQuoteFields.BID_PRICE, Wombat.MamdaQuoteFields.BID_SIZE, Wombat.MamdaQuoteFields.BID_TICK, Wombat.MamdaQuoteFields.BID_TIME, Wombat.MamdaQuoteFields.BID_UPDATE_COUNT, Wombat.MamdaQuoteFields.BID_YIELD, Wombat.MamdaQuoteFields.CONFLATE_COUNT, Wombat.MamdaQuoteFields.getMaxFid(), Wombat.MamdaQuoteListener.getShortSaleCircuitBreaker(), Wombat.MamdaQuoteFields.ISSUE_SYMBOL, Wombat.MamdaQuoteFields.LINE_TIME, Wombat.MamdaQuoteHandler.onQuoteGap(), Wombat.MamdaQuoteHandler.onQuoteRecap(), Wombat.MamdaQuoteHandler.onQuoteUpdate(), Wombat.MamdaQuoteFields.PART_ID, Wombat.MamdaQuoteFields.PUB_ID, Wombat.MamdaQuoteFields.QUOTE_COUNT, Wombat.MamdaQuoteFields.QUOTE_DATE, Wombat.MamdaQuoteFields.QUOTE_QUAL, Wombat.MamdaQuoteFields.QUOTE_QUAL_NATIVE, Wombat.MamdaQuoteFields.QUOTE_SEQ_NUM, Wombat.MamdaQuoteFields.QUOTE_TIME, Wombat.MamdaQuoteFields.SEND_TIME, Wombat.MamdaConcreteQuoteRecap.setActivityTime(), Wombat.MamdaConcreteQuoteRecap.setAskCloseDate(), Wombat.MamdaConcreteQuoteRecap.setAskClosePrice(), Wombat.MamdaConcreteQuoteRecap.setAskDepth(), Wombat.MamdaConcreteQuoteRecap.setAskHigh(), Wombat.MamdaConcreteQuoteRecap.setAskIndicator(), Wombat.MamdaConcreteQuoteRecap.setAskLow(), Wombat.MamdaConcreteQuoteRecap.setAskPartId(), Wombat.MamdaConcreteQuoteRecap.setAskPrevCloseDate(), Wombat.MamdaConcreteQuoteRecap.setAskPrevClosePrice(), Wombat.MamdaConcreteQuoteRecap.setAskPrice(), Wombat.MamdaConcreteQuoteRecap.setAskSize(), Wombat.MamdaConcreteQuoteRecap.setAskTime(), Wombat.MamdaConcreteQuoteRecap.setAskUpdateCount(), Wombat.MamdaConcreteQuoteRecap.setAskYield(), Wombat.MamdaConcreteQuoteRecap.setBidCloseDate(), Wombat.MamdaConcreteQuoteRecap.setBidClosePrice(), Wombat.MamdaConcreteQuoteRecap.setBidDepth(), Wombat.MamdaConcreteQuoteRecap.setBidHigh(), Wombat.MamdaConcreteQuoteRecap.setBidIndicator(), Wombat.MamdaConcreteQuoteRecap.setBidLow(), Wombat.MamdaConcreteQuoteRecap.setBidPartId(), Wombat.MamdaConcreteQuoteRecap.setBidPrevCloseDate(), Wombat.MamdaConcreteQuoteRecap.setBidPrevClosePrice(), Wombat.MamdaConcreteQuoteRecap.setBidPrice(), Wombat.MamdaConcreteQuoteRecap.setBidSize(), Wombat.MamdaConcreteQuoteRecap.setBidTime(), Wombat.MamdaConcreteQuoteRecap.setBidUpdateCount(), Wombat.MamdaConcreteQuoteRecap.setBidYield(), Wombat.MamdaConcreteQuoteRecap.setEventSeqNum(), Wombat.MamdaConcreteQuoteRecap.setEventTime(), Wombat.MamdaConcreteQuoteRecap.setLineTime(), Wombat.MamdaConcreteQuoteRecap.setPartId(), Wombat.MamdaConcreteQuoteRecap.setPubId(), Wombat.MamdaConcreteQuoteRecap.setQuoteCount(), Wombat.MamdaConcreteQuoteRecap.setQuoteDate(), Wombat.MamdaConcreteQuoteRecap.setQuoteMidPrice(), Wombat.MamdaConcreteQuoteRecap.setQuoteQual(), Wombat.MamdaConcreteQuoteRecap.setQuoteQualNative(), Wombat.MamdaConcreteQuoteRecap.setSendTime(), Wombat.MamdaConcreteQuoteRecap.setShortSaleBidTick(), Wombat.MamdaConcreteQuoteRecap.setShortSaleCircuitBreaker(), Wombat.MamdaConcreteQuoteRecap.setSrcTime(), Wombat.MamdaConcreteQuoteRecap.setSymbol(), Wombat.MamdaQuoteFields.SHORT_SALE_BID_TICK, Wombat.MamdaQuoteFields.SHORT_SALE_CIRCUIT_BREAKER, Wombat.MamdaQuoteFields.SRC_TIME, and Wombat.MamdaQuoteFields.SYMBOL.