OpenMAMDA C# API: Wombat.MamdaOptionExpirationDateSet Class Reference
Wombat.MamdaOptionExpirationDateSet Class Reference
A class that represents a set of expiration dates, each of which contains a set of strike prices (MamdaOptionStrikeSet), each of which contains a set of option contracts (MamdaOptionContractSet), each of which contains exchange-specific contracts.
Inherits Wombat.Containers.TreeMap.
Public Member Functions
MamdaOptionExpirationDateSet ()
MamdaOptionExpirationDateSet (MamdaOptionExpirationDateSet copy)
MamdaOptionExpirationDateSet getExpirationsBefore (DateTime date)
MamdaOptionExpirationDateSet getExpirations (int numExpirations)
String toString ()
override string ToString ()
Public Member Functions inherited from Wombat.Containers.TreeMap
TreeMap ()
TreeMap (Comparator c)
TreeMap (Map m)
TreeMap (SortedMap m)
Comparator comparator ()
SortedMap subMap (object fromKey, object toKey)
SortedMap headMap (object toKey)
SortedMap tailMap (object fromKey)
object firstKey ()
object lastKey ()
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
object Clone ()
Protected Member Functions
MamdaOptionExpirationDateSet (SortedMap map)
Detailed Description
A class that represents a set of expiration dates, each of which contains a set of strike prices (MamdaOptionStrikeSet), each of which contains a set of option contracts (MamdaOptionContractSet), each of which contains exchange-specific contracts.
To access a set of strike prices for a given expiration date, use the get method (inherited from TreeMap).
Constructor & Destructor Documentation
MamdaOptionExpirationDateSet() [1/3]
Wombat.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet ()
Referenced by Wombat.MamdaOptionExpirationDateSet.getExpirations(), and Wombat.MamdaOptionExpirationDateSet.getExpirationsBefore().
MamdaOptionExpirationDateSet() [2/3]
Wombat.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet (MamdaOptionExpirationDateSet copy)
MamdaOptionExpirationDateSet() [3/3]
Wombat.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet (SortedMap map) protected
Member Function Documentation
getExpirationsBefore()
MamdaOptionExpirationDateSet Wombat.MamdaOptionExpirationDateSet.getExpirationsBefore (DateTime date)
References Wombat.Containers.TreeMap.headMap(), and Wombat.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet().
Referenced by Wombat.MamdaOptionExpirationDateSet.getExpirations(), and Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
getExpirations()
MamdaOptionExpirationDateSet Wombat.MamdaOptionExpirationDateSet.getExpirations (int numExpirations)
References Wombat.MamdaOptionExpirationDateSet.getExpirationsBefore(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), Wombat.Containers.TreeMap.keySet(), Wombat.MamdaOptionExpirationDateSet.MamdaOptionExpirationDateSet(), and Wombat.Containers.Iterator.next().
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
toString()
String Wombat.MamdaOptionExpirationDateSet.toString ()
References Wombat.Containers.TreeMap.entrySet(), Wombat.SimpleDateFormat.Format(), Wombat.Containers.MapEntry.getKey(), Wombat.Containers.MapEntry.getValue(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
Referenced by Wombat.MamdaOptionExpirationDateSet.ToString().
ToString()
override string Wombat.MamdaOptionExpirationDateSet.ToString ()
References Wombat.Containers.Map.entrySet(), Wombat.Containers.MapEntry.getKey(), Wombat.Containers.MapEntry.getValue(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), Wombat.Containers.Iterator.next(), Wombat.Containers.TreeMap.put(), and Wombat.MamdaOptionExpirationDateSet.toString().