OpenMAMDA C# API: Wombat.MamdaOptionChainView Class Reference
Wombat.MamdaOptionChainView Class Reference
A class that represents a "view" of a subset of an option chain.
Inherits Wombat.MamdaOptionChainHandler.
Public Member Functions
MamdaOptionChainView (MamdaOptionChain chain)
Create a view on the given option chain.
string getSymbol ()
Return the symbol for the option chain.
void setAtTheMoneyType (MamdaOptionAtTheMoneyCompareType atTheMoneyType)
Set how the underlying price ("at the money") is determined MamdaOptionAtTheMoneyCompareType
void setStrikeRangePercent (double percentMargin)
Set the range of strike prices to be included in the view by percentage variation from the underlying price.
void setStrikeRangeNumber (int number)
Set the number of strike prices to be included in the view.
void setExpirationRangeDays (int expirationDays)
Set the range of expiration dates to be included in the view by the maximum number of days until expiration.
void setNumberOfExpirations (int numExpirations)
Set the number of expiration dates to be included in the view.
void setJitterMargin (double percentMargin)
Set a "jitter margin" to avoid having the range jump between different strike prices when the underlying price hovers right on the edge of a range boundary.
bool isVisible (MamdaOptionContract contract)
Return whether an option contract falls within this view's parameters.
Iterator expirationIterator ()
Return an Iterator over the set of expiration dates within the view.
void onOptionChainRecap (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionChain chain)
Handler option chain recaps and initial values.
void onOptionContractCreate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionContract contract, MamdaOptionChain chain)
Handler for option chain structural updates.
void onOptionSeriesUpdate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionSeriesUpdate updateEvent, MamdaOptionChain chain)
Handler for option chain structural updates.
Detailed Description
A class that represents a "view" of a subset of an option chain.
The view can be restricted to a percentage or number of strike prices around "the money" as well as to a maximum number of days into the future. The view will be adjusted to include strike prices within the range as the underlying price moves. This means that the range of strike prices will change over time. In order to avoid a "jitter" in the range of strike prices when the underlying price hovers right on the edge of a range boundary, the class also provides a "jitter margin" as some percentage of the underyling price (default is 0.5%).
Constructor & Destructor Documentation
MamdaOptionChainView()
Wombat.MamdaOptionChainView.MamdaOptionChainView (MamdaOptionChain chain)
Create a view on the given option chain.
Multiple views are supported on any given option chain.
Parameters
chain
Member Function Documentation
getSymbol()
string Wombat.MamdaOptionChainView.getSymbol ()
Return the symbol for the option chain.
Returns
References Wombat.MamdaOptionChain.getSymbol().
setAtTheMoneyType()
void Wombat.MamdaOptionChainView.setAtTheMoneyType (MamdaOptionAtTheMoneyCompareType atTheMoneyType)
Set how the underlying price ("at the money") is determined MamdaOptionAtTheMoneyCompareType
Parameters
atTheMoneyType
setStrikeRangePercent()
void Wombat.MamdaOptionChainView.setStrikeRangePercent (double percentMargin)
Set the range of strike prices to be included in the view by percentage variation from the underlying price.
The range of strike prices in the view will vary as the underlying varies. The "jitter margin" avoids switching between ranges too often.
Parameters
percentMargin
setStrikeRangeNumber()
void Wombat.MamdaOptionChainView.setStrikeRangeNumber (int number)
Set the number of strike prices to be included in the view.
The "jitter margin" avoids switching between ranges too often.
Parameters
number
setExpirationRangeDays()
void Wombat.MamdaOptionChainView.setExpirationRangeDays (int expirationDays)
Set the range of expiration dates to be included in the view by the maximum number of days until expiration.
Note: a non-zero range overrides a specific number of expirations set by setNumberOfExpirations().
Parameters
expirationDays
setNumberOfExpirations()
void Wombat.MamdaOptionChainView.setNumberOfExpirations (int numExpirations)
Set the number of expiration dates to be included in the view.
Note: a non-zero range (set by setExpirationRangeDays()) overrides a specific number of expirations.
Parameters
numExpirations
setJitterMargin()
void Wombat.MamdaOptionChainView.setJitterMargin (double percentMargin)
Set a "jitter margin" to avoid having the range jump between different strike prices when the underlying price hovers right on the edge of a range boundary.
The underlying is allowed to fluctuate within the jitter margin without the range being reset. When the underlying moves beyond the jitter margin, the range is reset.
Parameters
percentMargin
isVisible()
bool Wombat.MamdaOptionChainView.isVisible (MamdaOptionContract contract)
Return whether an option contract falls within this view's parameters.
Parameters
contract
Returns
References Wombat.MamdaOptionContract.getExpireDate(), and Wombat.MamdaOptionContract.getStrikePrice().
expirationIterator()
Iterator Wombat.MamdaOptionChainView.expirationIterator ()
Return an Iterator over the set of expiration dates within the view.
Each Iterator represents a MamdaOptionExpirationStrikes object.
Returns
References Wombat.Containers.Iterable.iterator(), and Wombat.Containers.TreeMap.values().
onOptionChainRecap()
void Wombat.MamdaOptionChainView.onOptionChainRecap (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionChain chain)
Handler option chain recaps and initial values.
Parameters
subscription
listener
msg
chain
Implements Wombat.MamdaOptionChainHandler.
onOptionContractCreate()
void Wombat.MamdaOptionChainView.onOptionContractCreate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionContract contract, MamdaOptionChain chain)
Handler for option chain structural updates.
Parameters
subscription
listener
msg
contract
chain
Implements Wombat.MamdaOptionChainHandler.
onOptionSeriesUpdate()
void Wombat.MamdaOptionChainView.onOptionSeriesUpdate (MamdaSubscription subscription, MamdaOptionChainListener listener, MamaMsg msg, MamdaOptionSeriesUpdate updateEvent, MamdaOptionChain chain)
Handler for option chain structural updates.
Parameters
subscription
listener
msg
updateEvent
chain
Implements Wombat.MamdaOptionChainHandler.
References Wombat.Containers.SortedSet.first(), Wombat.Containers.TreeMap.firstKey(), Wombat.MamdaOptionChain.getAllExpirations(), Wombat.MamdaOptionExpirationDateSet.getExpirations(), Wombat.MamdaOptionExpirationDateSet.getExpirationsBefore(), Wombat.MamdaOptionChain.getStrikesWithinPercent(), Wombat.MamdaOptionChain.getStrikesWithinRangeSize(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), Wombat.Containers.SortedSet.last(), Wombat.Containers.TreeMap.lastKey(), Wombat.Containers.Iterator.next(), Wombat.Containers.Collection.size(), Wombat.Containers.TreeMap.size(), Wombat.MamdaOptionExpirationStrikes.trimStrikes(), and Wombat.Containers.TreeMap.values().