OpenMAMDA C# API: Wombat.Containers.RedBlackTree Class Reference
Wombat.Containers.RedBlackTree Class Reference
Inherits Wombat.Containers.SortedMap.
Classes
class Node
Public Member Functions
RedBlackTree ()
RedBlackTree (Comparator comparator)
Comparator comparator ()
SortedMap subMap (object fromKey, object toKey)
SortedMap headMap (object toKey)
SortedMap tailMap (object fromKey)
object firstKey ()
object lastKey ()
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
Constructor & Destructor Documentation
RedBlackTree() [1/2]
Wombat.Containers.RedBlackTree.RedBlackTree ()
RedBlackTree() [2/2]
Wombat.Containers.RedBlackTree.RedBlackTree (Comparator comparator)
Member Function Documentation
comparator()
Comparator Wombat.Containers.RedBlackTree.comparator ()
Implements Wombat.Containers.SortedMap.
subMap()
SortedMap Wombat.Containers.RedBlackTree.subMap (object fromKey, object toKey)
Implements Wombat.Containers.SortedMap.
headMap()
SortedMap Wombat.Containers.RedBlackTree.headMap (object toKey)
Implements Wombat.Containers.SortedMap.
tailMap()
SortedMap Wombat.Containers.RedBlackTree.tailMap (object fromKey)
Implements Wombat.Containers.SortedMap.
firstKey()
object Wombat.Containers.RedBlackTree.firstKey ()
Implements Wombat.Containers.SortedMap.
lastKey()
object Wombat.Containers.RedBlackTree.lastKey ()
Implements Wombat.Containers.SortedMap.
size()
int Wombat.Containers.RedBlackTree.size ()
Implements Wombat.Containers.Map.
Referenced by Wombat.Containers.RedBlackTree.entrySet().
isEmpty()
bool Wombat.Containers.RedBlackTree.isEmpty ()
Implements Wombat.Containers.Map.
containsKey()
bool Wombat.Containers.RedBlackTree.containsKey (object key)
Implements Wombat.Containers.Map.
containsValue()
bool Wombat.Containers.RedBlackTree.containsValue (object value)
Implements Wombat.Containers.Map.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
valueOf()
object Wombat.Containers.RedBlackTree.valueOf (object key)
Implements Wombat.Containers.Map.
put()
object Wombat.Containers.RedBlackTree.put (object key, object value)
Implements Wombat.Containers.Map.
remove()
object Wombat.Containers.RedBlackTree.remove (object key)
Implements Wombat.Containers.Map.
putAll()
void Wombat.Containers.RedBlackTree.putAll (Map m)
Implements Wombat.Containers.Map.
References Wombat.Containers.Map.entrySet(), Wombat.Containers.MapEntry.getKey(), Wombat.Containers.MapEntry.getValue(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
clear()
void Wombat.Containers.RedBlackTree.clear ()
Implements Wombat.Containers.Map.
keySet()
Set Wombat.Containers.RedBlackTree.keySet ()
Implements Wombat.Containers.Map.
values()
Collection Wombat.Containers.RedBlackTree.values ()
Implements Wombat.Containers.Map.
entrySet()
Set Wombat.Containers.RedBlackTree.entrySet ()
Implements Wombat.Containers.Map.
References Wombat.Containers.ArrayListCollection.add(), Wombat.Containers.Comparator.compare(), Wombat.Containers.Map.entrySet(), Wombat.Containers.MapEntry.getKey(), Wombat.Containers.MapEntry.getValue(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), Wombat.Containers.Iterator.next(), Wombat.Containers.Iterator.remove(), and Wombat.Containers.RedBlackTree.size().