OpenMAMDA C# API: Wombat.MamdaTradeListener Class Reference
Wombat.MamdaTradeListener Class Reference
MamdaTradeListener is a class that specializes in handling trade updates.
Inherits Wombat.MamdaMsgListener, Wombat.MamdaTradeRecap, Wombat.MamdaTradeReport, Wombat.MamdaTradeGap, Wombat.MamdaTradeCancelOrError, Wombat.MamdaTradeCorrection, and Wombat.MamdaTradeClosing.
Classes
class MamdaTradeCache
class TradeLineTime
class TradeSendTime
interface TradeUpdate
Public Member Functions
MamdaTradeListener ()
Create a specialized trade listener.
void addHandler (MamdaTradeHandler handler)
Add a specialized trade handler.
String getSymbol ()
String getPartId ()
MamdaBasicEvent.getPartId()
DateTime getSrcTime ()
MamdaBasicEvent.getSrcTime()
DateTime getActivityTime ()
MamdaBasicEvent.getActivityTime()
DateTime getLineTime ()
MamdaBasicEvent.getLineTime()
DateTime getSendTime ()
MamdaBasicEvent.getSendTime()
String getPubId ()
MamdaBasicEvent.getPubId()
long getEventSeqNum ()
MamdaBasicEvent.getEventSeqNum()
DateTime getEventTime ()
MamdaBasicEvent.getEventTime()
MamaPrice getLastPrice ()
MamdaTradeRecap.getLastPrice()
long getLastVolume ()
MamdaTradeRecap.getLastVolume()
String getLastPartId ()
MamdaTradeRecap.getLastPartId()
String getTradeId ()
MamdaTradeReport.getTradeId()
String getOrigTradeId ()
MamdaTradeCancelOrError.getOrigTradeId()
String getCorrTradeId ()
MamdaTradeCorrection.getCorrTradeId()
DateTime getLastTime ()
MamdaTradeRecap.getLastTime()
MamaPrice getIrregPrice ()
MamdaTradeRecap.getIrregPrice()
long getIrregVolume ()
MamdaTradeRecap.getIrregVolume()
String getIrregPartId ()
MamdaTradeRecap.getIrregPartId()
DateTime getIrregTime ()
MamdaTradeRecap.getIrregTime()
DateTime getTradeDate ()
MamdaTradeRecap.getLastTime()
long getAccVolume ()
MamdaTradeRecap.getAccVolume()
long getOffExAccVolume ()
MamdaTradeRecap.getOffExAccVolume()
long getOnExAccVolume ()
MamdaTradeRecap.getOnExAccVolume()
MamaPrice getNetChange ()
MamdaTradeRecap.getNetChange()
double getPctChange ()
MamdaTradeRecap.getPctChange()
String getTradeDirection ()
MamdaTradeRecap.getTradeDirection()
string getSide ()
MamdaTradeRecap.getSide()
MamaPrice getOpenPrice ()
MamdaTradeRecap.getOpenPrice()
MamaPrice getHighPrice ()
MamdaTradeRecap.getHighPrice()
MamaPrice getLowPrice ()
MamdaTradeRecap.getLowPrice()
MamaPrice getClosePrice ()
MamdaTradeRecap.getClosePrice()
MamaPrice getPrevClosePrice ()
MamdaTradeRecap.getPrevClosePrice()
DateTime getPrevCloseDate ()
MamdaTradeRecap.getPrevCloseDate()
MamaPrice getAdjPrevClose ()
MamdaTradeRecap.getAdjPrevClose()
long getBlockCount ()
MamdaTradeRecap.getBlockCount()
long getBlockVolume ()
MamdaTradeRecap.getBlockVolume()
double getVwap ()
MamdaTradeRecap.getVwap()
double getOffExVwap ()
MamdaTradeRecap.getOffExVwap()
double getOnExVwap ()
MamdaTradeRecap.getOnExVwap()
double getTotalValue ()
MamdaTradeRecap.getTotalValue()
double getOffExTotalValue ()
MamdaTradeRecap.getOffExTotalValue()
double getOnExTotalValue ()
MamdaTradeRecap.getOnExTotalValue()
double getStdDev ()
MamdaTradeRecap.getStdDev()
double getStdDevSum ()
MamdaTradeRecap.getStdDevSum()
double getStdDevSumSquares ()
MamdaTradeRecap.getStdDevSumSquares()
long getOrderId ()
MamdaTradeRecap.getOrderId
MamaPrice getSettlePrice ()
MamdaTradeRecap.getSettlePrice()
DateTime getSettleDate ()
MamdaTradeRecap.getSettleDate()
char getShortSaleCircuitBreaker ()
Returns the ShortSaleCircuitBreaker
char getOrigShortSaleCircuitBreaker ()
Returns the ShortSaleCircuitBreaker
char getCorrShortSaleCircuitBreaker ()
Get the ShortSaleCircuitBreaker.
MamaPrice getTradePrice ()
MamdaTradeReport.getTradePrice()
long getTradeVolume ()
MamdaTradeReport.getTradeVolume()
String getTradePartId ()
MamdaTradeReport.getTradePartId()
String getTradeQual ()
MamdaTradeReport.getTradeQual()
String getTradeQualNativeStr ()
MamdaTradeReport.getTradeQualNativeStr()
String getTradeCondition ()
MamdaTradeReport.getTradeCondition()
long getTradeSellersSaleDays ()
MamdaTradeReport.getTradeSellersSaleDays()
char getTradeStopStock ()
MamdaTradeReport.getTradeStopStock()
String getTradeExecVenue ()
MamdaTradeRecap.getTradeExecVenue()
MamaPrice getOffExchangeTradePrice ()
MamdaTradeRecap.getOffExchangeTradePrice()
MamaPrice getOnExchangeTradePrice ()
MamdaTradeRecap.getOnExchangeTradePrice()
long getTradeCount ()
MamdaTradeRecap.getTradeCount()
string getTradeUnits ()
MamdaTradeRecap.getTradeUnits()
long getLastSeqNum ()
MamdaTradeRecap.getLastSeqNum()
long getHighSeqNum ()
MamdaTradeRecap.getHighSeqNum()
long getLowSeqNum ()
MamdaTradeRecap.getLowSeqNum()
long getTotalVolumeSeqNum ()
MamdaTradeRecap.getTotalVolumeSeqNum()
string getCurrencyCode ()
MamdaTradeRecap.getCurrencyCode()
bool getIsIrregular ()
MamdaTradeReport.getIsIrregular()
long getBeginGapSeqNum ()
MamdaTradeGap.getBeginGapSeqNum()
long getEndGapSeqNum ()
MamdaTradeGap.getEndGapSeqNum()
bool getIsCancel ()
MamdaTradeCancelOrError.getIsCancel()
long getOrigSeqNum ()
MamdaTradeCancelOrError.getOrigSeqNum()
double getOrigPrice ()
MamdaTradeCancelOrError.getOrigPrice()
long getOrigVolume ()
MamdaTradeCancelOrError.getOrigVolume()
String getOrigPartId ()
MamdaTradeCancelOrError.getOrigPartId()
String getOrigQual ()
MamdaTradeCancelOrError.getOrigQual()
String getOrigQualNative ()
MamdaTradeCancelOrError.getOrigQualNative()
String getOrigCondition ()
MamdaTradeCancelOrError.getOrigCondition()
long getOrigSellersSaleDays ()
MamdaTradeCancelOrError.getOrigSellersSaleDays()
char getOrigStopStock ()
MamdaTradeCancelOrError.getOrigStopStock()
double getCorrPrice ()
MamdaTradeCorrection.getCorrPrice()
long getCorrVolume ()
MamdaTradeCorrection.getCorrVolume()
String getCorrPartId ()
MamdaTradeCorrection.getCorrPartId()
String getCorrQual ()
MamdaTradeCorrection.getCorrQual()
String getCorrQualNative ()
MamdaTradeCorrection.getCorrQualNative()
String getCorrCondition ()
MamdaTradeCorrection.getCorrCondition()
long getCorrSellersSaleDays ()
MamdaTradeCorrection.getCorrSellersSaleDays()
char getCorrStopStock ()
MamdaTradeCorrection.getCorrStopStock()
bool getIsIndicative ()
MamdaTradeClosing.getIsIndicative()
MamdaFieldState getSymbolFieldState ()
MamdaFieldState getPartIdFieldState ()
MamdaBasicEvent.getPartIdFieldState()
MamdaFieldState getSrcTimeFieldState ()
MamdaBasicEvent.getSrcTimeFieldState()
MamdaFieldState getActivityTimeFieldState ()
MamdaBasicEvent.getActivityTimeFieldState()
MamdaFieldState getLineTimeFieldState ()
MamdaBasicEvent.getLineTimeFieldState()
MamdaFieldState getSendTimeFieldState ()
MamdaBasicEvent.getSendTimeFieldState()
MamdaFieldState getPubIdFieldState ()
MamdaBasicEvent.getPubIdFieldState()
MamdaFieldState getEventSeqNumFieldState ()
MamdaBasicEvent.getEventSeqNumFieldState()
MamdaFieldState getEventTimeFieldState ()
MamdaBasicEvent.getEventTimeFieldState()
MamdaFieldState getLastPriceFieldState ()
MamdaTradeRecap.getLastPriceFieldState()
MamdaFieldState getLastVolumeFieldState ()
MamdaTradeRecap.getLastVolumeFieldState()
MamdaFieldState getLastPartIdFieldState ()
MamdaTradeRecap.getLastPartIdFieldState()
MamdaFieldState getTradeIdFieldState ()
MamdaTradeReport.getTradeIdFieldState()
MamdaFieldState getOrigTradeIdFieldState ()
MamdaTradeCancelOrError.getOrigTradeIdFieldState()
MamdaFieldState getCorrTradeIdFieldState ()
MamdaTradeCorrection.getCorrTradeIdFieldState()
MamdaFieldState getLastTimeFieldState ()
MamdaTradeRecap.getLastTimeFieldState()
MamdaFieldState getIrregPriceFieldState ()
MamdaTradeRecap.getIrregPriceFieldState()
MamdaFieldState getIrregVolumeFieldState ()
MamdaTradeRecap.getIrregVolumeFieldState()
MamdaFieldState getIrregPartIdFieldState ()
MamdaTradeRecap.getIrregPartIdFieldState()
MamdaFieldState getIrregTimeFieldState ()
MamdaTradeRecap.getIrregTimeFieldState()
MamdaFieldState getTradeDateFieldState ()
MamdaTradeRecap.getLastTimeFieldState()
MamdaFieldState getAccVolumeFieldState ()
MamdaTradeRecap.getAccVolumeFieldState()
MamdaFieldState getOffExAccVolumeFieldState ()
MamdaTradeRecap.getOffExAccVolumeFieldState()
MamdaFieldState getOnExAccVolumeFieldState ()
MamdaTradeRecap.getOnExAccVolumeFieldState()
MamdaFieldState getNetChangeFieldState ()
MamdaTradeRecap.getNetChangeFieldState()
MamdaFieldState getPctChangeFieldState ()
MamdaTradeRecap.getPctChangeFieldState()
MamdaFieldState getTradeDirectionFieldState ()
MamdaTradeRecap.getTradeDirectionFieldState()
MamdaFieldState getSideFieldState ()
MamdaTradeRecap.getSideFieldState()
MamdaFieldState getOpenPriceFieldState ()
MamdaTradeRecap.getOpenPriceFieldState()
MamdaFieldState getHighPriceFieldState ()
MamdaTradeRecap.getHighPriceFieldState()
MamdaFieldState getLowPriceFieldState ()
MamdaTradeRecap.getLowPriceFieldState()
MamdaFieldState getClosePriceFieldState ()
MamdaTradeRecap.getClosePriceFieldState()
MamdaFieldState getPrevClosePriceFieldState ()
MamdaTradeRecap.getPrevClosePriceFieldState()
MamdaFieldState getPrevCloseDateFieldState ()
MamdaTradeRecap.getPrevCloseDateFieldState()
MamdaFieldState getAdjPrevCloseFieldState ()
MamdaTradeRecap.getAdjPrevCloseFieldState()
MamdaFieldState getBlockCountFieldState ()
MamdaTradeRecap.getBlockCountFieldState()
MamdaFieldState getBlockVolumeFieldState ()
MamdaTradeRecap.getBlockVolumeFieldState()
MamdaFieldState getVwapFieldState ()
MamdaTradeRecap.getVwapFieldState()
MamdaFieldState getOffExVwapFieldState ()
MamdaTradeRecap.getOffExVwapFieldState()
MamdaFieldState getOnExVwapFieldState ()
MamdaTradeRecap.getOnExVwapFieldState()
MamdaFieldState getTotalValueFieldState ()
MamdaTradeRecap.getTotalValueFieldState()
MamdaFieldState getOffExTotalValueFieldState ()
MamdaTradeRecap.getOffExTotalValueFieldState()
MamdaFieldState getOnExTotalValueFieldState ()
MamdaTradeRecap.getOnExTotalValueFieldState()
MamdaFieldState getStdDevFieldState ()
MamdaTradeRecap.getStdDevFieldState()
MamdaFieldState getStdDevSumFieldState ()
MamdaTradeRecap.getStdDevSumFieldState()
MamdaFieldState getStdDevSumSquaresFieldState ()
MamdaTradeRecap.getStdDevSumSquaresFieldState()
MamdaFieldState getOrderIdFieldState ()
MamdaTradeRecap.getOrderId
MamdaFieldState getSettlePriceFieldState ()
MamdaTradeRecap.getSettlePriceFieldState()
MamdaFieldState getSettleDateFieldState ()
MamdaTradeRecap.getSettleDateFieldState()
MamdaFieldState getShortSaleCircuitBreakerFieldState ()
Returns the FieldState, always MODIFIED
MamdaFieldState getOrigShortSaleCircuitBreakerFieldState ()
Returns the FieldState, always MODIFIED
MamdaFieldState getCorrShortSaleCircuitBreakerFieldState ()
Get the field state
MamdaFieldState getTradePriceFieldState ()
MamdaTradeReport.getTradePriceFieldState()
MamdaFieldState getTradeVolumeFieldState ()
MamdaTradeReport.getTradeVolumeFieldState()
MamdaFieldState getTradePartIdFieldState ()
MamdaTradeReport.getTradePartIdFieldState()
MamdaFieldState getTradeQualFieldState ()
MamdaTradeReport.getTradeQualFieldState()
MamdaFieldState getTradeQualNativeStrFieldState ()
MamdaTradeReport.getTradeQualNativeStrFieldState()
MamdaFieldState getTradeConditionFieldState ()
MamdaTradeReport.getTradeConditionFieldState()
MamdaFieldState getTradeSellersSaleDaysFieldState ()
MamdaTradeReport.getTradeSellersSaleDaysFieldState()
MamdaFieldState getTradeStopStockFieldState ()
MamdaTradeReport.getTradeStopStockFieldState()
MamdaFieldState getTradeExecVenueFieldState ()
MamdaTradeRecap.getTradeExecVenueFieldState()
MamdaFieldState getOffExchangeTradePriceFieldState ()
MamdaTradeRecap.getOffExchangeTradePriceFieldState()
MamdaFieldState getOnExchangeTradePriceFieldState ()
MamdaTradeRecap.getOnExchangeTradePriceFieldState()
MamdaFieldState getTradeCountFieldState ()
MamdaTradeRecap.getTradeCountFieldState()
MamdaFieldState getTradeUnitsFieldState ()
MamdaTradeRecap.getTradeUnitsFieldState()
MamdaFieldState getLastSeqNumFieldState ()
MamdaTradeRecap.getLastSeqNumFieldState()
MamdaFieldState getHighSeqNumFieldState ()
MamdaTradeRecap.getHighSeqNumFieldState()
MamdaFieldState getLowSeqNumFieldState ()
MamdaTradeRecap.getLowSeqNum()
MamdaFieldState getTotalVolumeSeqNumFieldState ()
MamdaTradeRecap.getTotalVolumeSeqNumFieldState()
MamdaFieldState getCurrencyCodeFieldState ()
MamdaTradeRecap.getCurrencyCodeFieldState()
MamdaFieldState getIsIrregularFieldState ()
MamdaTradeReport.getIsIrregularFieldState()
MamdaFieldState getBeginGapSeqNumFieldState ()
MamdaTradeGap.getBeginGapSeqNumFieldState()
MamdaFieldState getEndGapSeqNumFieldState ()
MamdaTradeGap.getEndGapSeqNumFieldState()
MamdaFieldState getOrigSeqNumFieldState ()
MamdaTradeCancelOrError.getOrigSeqNumFieldState()
MamdaFieldState getOrigPriceFieldState ()
MamdaTradeCancelOrError.getOrigPriceFieldState()
MamdaFieldState getOrigVolumeFieldState ()
MamdaTradeCancelOrError.getOrigVolumeFieldState()
MamdaFieldState getOrigPartIdFieldState ()
MamdaTradeCancelOrError.getOrigPartIdFieldState()
MamdaFieldState getOrigQualFieldState ()
MamdaTradeCancelOrError.getOrigQualFieldState()
MamdaFieldState getOrigQualNativeFieldState ()
MamdaTradeCancelOrError.getOrigQualNativeFieldState()
MamdaFieldState getOrigConditionFieldState ()
MamdaTradeCancelOrError.getOrigConditionFieldState()
MamdaFieldState getOrigSellersSaleDaysFieldState ()
MamdaTradeCancelOrError.getOrigSellersSaleDaysFieldState()
MamdaFieldState getOrigStopStockFieldState ()
MamdaTradeCancelOrError.getOrigStopStockFieldState()
MamdaFieldState getCorrPriceFieldState ()
MamdaTradeCorrection.getCorrPriceFieldState()
MamdaFieldState getCorrVolumeFieldState ()
MamdaTradeCorrection.getCorrVolumeFieldState()
MamdaFieldState getCorrPartIdFieldState ()
MamdaTradeCorrection.getCorrPartIdFieldState()
MamdaFieldState getCorrQualFieldState ()
MamdaTradeCorrection.getCorrQualFieldState()
MamdaFieldState getCorrQualNativeFieldState ()
MamdaTradeCorrection.getCorrQualNativeFieldState()
MamdaFieldState getCorrConditionFieldState ()
MamdaTradeCorrection.getCorrConditionFieldState()
MamdaFieldState getCorrSellersSaleDaysFieldState ()
MamdaTradeCorrection.getCorrSellersSaleDaysFieldState()
MamdaFieldState getCorrStopStockFieldState ()
MamdaTradeCorrection.getCorrStopStockFieldState()
MamdaFieldState getIsIndicativeFieldState ()
MamdaTradeClosing.getIsIndicativeFieldState()
void populateRecap (MamdaConcreteTradeRecap recap)
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Detailed Description
MamdaTradeListener is a class that specializes in handling trade updates.
Developers provide their own implementation of the MamdaTradeHandler interface and will be delivered notifications for trades, trade cancels/error/corrections, and trade closing prices. An obvious application for this MAMDA class is any kind of trade tick capture application.
Note: The MamdaTradeListener class caches trade-related field values. Among other reasons, caching of these fields makes it possible to provide complete trade-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaTradeListener()
Wombat.MamdaTradeListener.MamdaTradeListener ()
Create a specialized trade listener.
This listener handles trade reports, trade recaps, trade errors/cancels, trade corrections, and trade gap notifications.
Member Function Documentation
addHandler()
void Wombat.MamdaTradeListener.addHandler (MamdaTradeHandler handler)
Add a specialized trade handler.
Currently, only one handler can (and must) be registered.
Parameters
handler
Referenced by Wombat.MamdaOptionUnderlying.addTradeHandler(), and Wombat.MamdaOptionContract.addTradeHandler().
getSymbol()
String Wombat.MamdaTradeListener.getSymbol ()
getPartId()
String Wombat.MamdaTradeListener.getPartId ()
MamdaBasicEvent.getPartId()
getSrcTime()
DateTime Wombat.MamdaTradeListener.getSrcTime ()
MamdaBasicEvent.getSrcTime()
Implements Wombat.MamdaBasicEvent.
getActivityTime()
DateTime Wombat.MamdaTradeListener.getActivityTime ()
MamdaBasicEvent.getActivityTime()
Implements Wombat.MamdaBasicEvent.
getLineTime()
DateTime Wombat.MamdaTradeListener.getLineTime ()
MamdaBasicEvent.getLineTime()
getSendTime()
DateTime Wombat.MamdaTradeListener.getSendTime ()
MamdaBasicEvent.getSendTime()
getPubId()
String Wombat.MamdaTradeListener.getPubId ()
MamdaBasicEvent.getPubId()
getEventSeqNum()
long Wombat.MamdaTradeListener.getEventSeqNum ()
MamdaBasicEvent.getEventSeqNum()
Implements Wombat.MamdaBasicEvent.
getEventTime()
DateTime Wombat.MamdaTradeListener.getEventTime ()
MamdaBasicEvent.getEventTime()
Implements Wombat.MamdaBasicEvent.
getLastPrice()
MamaPrice Wombat.MamdaTradeListener.getLastPrice ()
MamdaTradeRecap.getLastPrice()
Implements Wombat.MamdaTradeRecap.
Referenced by Wombat.MamdaOptionChain.getAtTheMoney().
getLastVolume()
long Wombat.MamdaTradeListener.getLastVolume ()
MamdaTradeRecap.getLastVolume()
Implements Wombat.MamdaTradeRecap.
getLastPartId()
String Wombat.MamdaTradeListener.getLastPartId ()
MamdaTradeRecap.getLastPartId()
Implements Wombat.MamdaTradeRecap.
getTradeId()
String Wombat.MamdaTradeListener.getTradeId ()
MamdaTradeReport.getTradeId()
Implements Wombat.MamdaTradeReport.
getOrigTradeId()
String Wombat.MamdaTradeListener.getOrigTradeId ()
MamdaTradeCancelOrError.getOrigTradeId()
Implements Wombat.MamdaTradeCancelOrError.
getCorrTradeId()
String Wombat.MamdaTradeListener.getCorrTradeId ()
MamdaTradeCorrection.getCorrTradeId()
Implements Wombat.MamdaTradeCorrection.
getLastTime()
DateTime Wombat.MamdaTradeListener.getLastTime ()
MamdaTradeRecap.getLastTime()
Implements Wombat.MamdaTradeRecap.
getIrregPrice()
MamaPrice Wombat.MamdaTradeListener.getIrregPrice ()
MamdaTradeRecap.getIrregPrice()
Implements Wombat.MamdaTradeRecap.
getIrregVolume()
long Wombat.MamdaTradeListener.getIrregVolume ()
MamdaTradeRecap.getIrregVolume()
Implements Wombat.MamdaTradeRecap.
getIrregPartId()
String Wombat.MamdaTradeListener.getIrregPartId ()
MamdaTradeRecap.getIrregPartId()
Implements Wombat.MamdaTradeRecap.
getIrregTime()
DateTime Wombat.MamdaTradeListener.getIrregTime ()
MamdaTradeRecap.getIrregTime()
Implements Wombat.MamdaTradeRecap.
getTradeDate()
DateTime Wombat.MamdaTradeListener.getTradeDate ()
MamdaTradeRecap.getLastTime()
Implements Wombat.MamdaTradeRecap.
getAccVolume()
long Wombat.MamdaTradeListener.getAccVolume ()
MamdaTradeRecap.getAccVolume()
Implements Wombat.MamdaTradeRecap.
getOffExAccVolume()
long Wombat.MamdaTradeListener.getOffExAccVolume ()
MamdaTradeRecap.getOffExAccVolume()
Implements Wombat.MamdaTradeRecap.
getOnExAccVolume()
long Wombat.MamdaTradeListener.getOnExAccVolume ()
MamdaTradeRecap.getOnExAccVolume()
Implements Wombat.MamdaTradeRecap.
getNetChange()
MamaPrice Wombat.MamdaTradeListener.getNetChange ()
MamdaTradeRecap.getNetChange()
Implements Wombat.MamdaTradeRecap.
getPctChange()
double Wombat.MamdaTradeListener.getPctChange ()
MamdaTradeRecap.getPctChange()
Implements Wombat.MamdaTradeRecap.
getTradeDirection()
String Wombat.MamdaTradeListener.getTradeDirection ()
MamdaTradeRecap.getTradeDirection()
Implements Wombat.MamdaTradeRecap.
getSide()
string Wombat.MamdaTradeListener.getSide ()
MamdaTradeRecap.getSide()
Implements Wombat.MamdaTradeRecap.
getOpenPrice()
MamaPrice Wombat.MamdaTradeListener.getOpenPrice ()
MamdaTradeRecap.getOpenPrice()
Implements Wombat.MamdaTradeRecap.
getHighPrice()
MamaPrice Wombat.MamdaTradeListener.getHighPrice ()
MamdaTradeRecap.getHighPrice()
Implements Wombat.MamdaTradeRecap.
getLowPrice()
MamaPrice Wombat.MamdaTradeListener.getLowPrice ()
MamdaTradeRecap.getLowPrice()
Implements Wombat.MamdaTradeRecap.
getClosePrice()
MamaPrice Wombat.MamdaTradeListener.getClosePrice ()
MamdaTradeRecap.getClosePrice()
Implements Wombat.MamdaTradeClosing.
getPrevClosePrice()
MamaPrice Wombat.MamdaTradeListener.getPrevClosePrice ()
MamdaTradeRecap.getPrevClosePrice()
Implements Wombat.MamdaTradeRecap.
getPrevCloseDate()
DateTime Wombat.MamdaTradeListener.getPrevCloseDate ()
MamdaTradeRecap.getPrevCloseDate()
Implements Wombat.MamdaTradeRecap.
getAdjPrevClose()
MamaPrice Wombat.MamdaTradeListener.getAdjPrevClose ()
MamdaTradeRecap.getAdjPrevClose()
Implements Wombat.MamdaTradeRecap.
getBlockCount()
long Wombat.MamdaTradeListener.getBlockCount ()
MamdaTradeRecap.getBlockCount()
Implements Wombat.MamdaTradeRecap.
getBlockVolume()
long Wombat.MamdaTradeListener.getBlockVolume ()
MamdaTradeRecap.getBlockVolume()
Implements Wombat.MamdaTradeRecap.
getVwap()
double Wombat.MamdaTradeListener.getVwap ()
MamdaTradeRecap.getVwap()
Implements Wombat.MamdaTradeRecap.
getOffExVwap()
double Wombat.MamdaTradeListener.getOffExVwap ()
MamdaTradeRecap.getOffExVwap()
Implements Wombat.MamdaTradeRecap.
getOnExVwap()
double Wombat.MamdaTradeListener.getOnExVwap ()
MamdaTradeRecap.getOnExVwap()
Implements Wombat.MamdaTradeRecap.
getTotalValue()
double Wombat.MamdaTradeListener.getTotalValue ()
MamdaTradeRecap.getTotalValue()
Implements Wombat.MamdaTradeRecap.
getOffExTotalValue()
double Wombat.MamdaTradeListener.getOffExTotalValue ()
MamdaTradeRecap.getOffExTotalValue()
Implements Wombat.MamdaTradeRecap.
getOnExTotalValue()
double Wombat.MamdaTradeListener.getOnExTotalValue ()
MamdaTradeRecap.getOnExTotalValue()
Implements Wombat.MamdaTradeRecap.
getStdDev()
double Wombat.MamdaTradeListener.getStdDev ()
MamdaTradeRecap.getStdDev()
Implements Wombat.MamdaTradeRecap.
getStdDevSum()
double Wombat.MamdaTradeListener.getStdDevSum ()
MamdaTradeRecap.getStdDevSum()
Implements Wombat.MamdaTradeRecap.
getStdDevSumSquares()
double Wombat.MamdaTradeListener.getStdDevSumSquares ()
MamdaTradeRecap.getStdDevSumSquares()
Implements Wombat.MamdaTradeRecap.
getOrderId()
long Wombat.MamdaTradeListener.getOrderId ()
MamdaTradeRecap.getOrderId
Implements Wombat.MamdaTradeRecap.
getSettlePrice()
MamaPrice Wombat.MamdaTradeListener.getSettlePrice ()
MamdaTradeRecap.getSettlePrice()
Implements Wombat.MamdaTradeRecap.
getSettleDate()
DateTime Wombat.MamdaTradeListener.getSettleDate ()
MamdaTradeRecap.getSettleDate()
Implements Wombat.MamdaTradeRecap.
getShortSaleCircuitBreaker()
char Wombat.MamdaTradeListener.getShortSaleCircuitBreaker ()
Returns the ShortSaleCircuitBreaker
Returns
Implements Wombat.MamdaTradeRecap.
getOrigShortSaleCircuitBreaker()
char Wombat.MamdaTradeListener.getOrigShortSaleCircuitBreaker ()
Returns the ShortSaleCircuitBreaker
Returns
Implements Wombat.MamdaTradeCancelOrError.
getCorrShortSaleCircuitBreaker()
char Wombat.MamdaTradeListener.getCorrShortSaleCircuitBreaker ()
Get the ShortSaleCircuitBreaker.
MamdaTradeReport.getCorrShortSaleCircuitBreaker()
Returns
Implements Wombat.MamdaTradeCorrection.
getTradePrice()
MamaPrice Wombat.MamdaTradeListener.getTradePrice ()
MamdaTradeReport.getTradePrice()
Implements Wombat.MamdaTradeReport.
getTradeVolume()
long Wombat.MamdaTradeListener.getTradeVolume ()
MamdaTradeReport.getTradeVolume()
Implements Wombat.MamdaTradeReport.
getTradePartId()
String Wombat.MamdaTradeListener.getTradePartId ()
MamdaTradeReport.getTradePartId()
Implements Wombat.MamdaTradeReport.
getTradeQual()
String Wombat.MamdaTradeListener.getTradeQual ()
MamdaTradeReport.getTradeQual()
Implements Wombat.MamdaTradeReport.
getTradeQualNativeStr()
String Wombat.MamdaTradeListener.getTradeQualNativeStr ()
MamdaTradeReport.getTradeQualNativeStr()
Implements Wombat.MamdaTradeReport.
getTradeCondition()
String Wombat.MamdaTradeListener.getTradeCondition ()
MamdaTradeReport.getTradeCondition()
Implements Wombat.MamdaTradeReport.
getTradeSellersSaleDays()
long Wombat.MamdaTradeListener.getTradeSellersSaleDays ()
MamdaTradeReport.getTradeSellersSaleDays()
Implements Wombat.MamdaTradeReport.
getTradeStopStock()
char Wombat.MamdaTradeListener.getTradeStopStock ()
MamdaTradeReport.getTradeStopStock()
Implements Wombat.MamdaTradeReport.
getTradeExecVenue()
String Wombat.MamdaTradeListener.getTradeExecVenue ()
MamdaTradeRecap.getTradeExecVenue()
Implements Wombat.MamdaTradeRecap.
getOffExchangeTradePrice()
MamaPrice Wombat.MamdaTradeListener.getOffExchangeTradePrice ()
MamdaTradeRecap.getOffExchangeTradePrice()
Implements Wombat.MamdaTradeRecap.
getOnExchangeTradePrice()
MamaPrice Wombat.MamdaTradeListener.getOnExchangeTradePrice ()
MamdaTradeRecap.getOnExchangeTradePrice()
Implements Wombat.MamdaTradeRecap.
getTradeCount()
long Wombat.MamdaTradeListener.getTradeCount ()
MamdaTradeRecap.getTradeCount()
Implements Wombat.MamdaTradeRecap.
getTradeUnits()
string Wombat.MamdaTradeListener.getTradeUnits ()
MamdaTradeRecap.getTradeUnits()
Implements Wombat.MamdaTradeRecap.
getLastSeqNum()
long Wombat.MamdaTradeListener.getLastSeqNum ()
MamdaTradeRecap.getLastSeqNum()
Implements Wombat.MamdaTradeRecap.
getHighSeqNum()
long Wombat.MamdaTradeListener.getHighSeqNum ()
MamdaTradeRecap.getHighSeqNum()
Implements Wombat.MamdaTradeRecap.
getLowSeqNum()
long Wombat.MamdaTradeListener.getLowSeqNum ()
MamdaTradeRecap.getLowSeqNum()
Implements Wombat.MamdaTradeRecap.
getTotalVolumeSeqNum()
long Wombat.MamdaTradeListener.getTotalVolumeSeqNum ()
MamdaTradeRecap.getTotalVolumeSeqNum()
Implements Wombat.MamdaTradeRecap.
getCurrencyCode()
string Wombat.MamdaTradeListener.getCurrencyCode ()
MamdaTradeRecap.getCurrencyCode()
Implements Wombat.MamdaTradeRecap.
getIsIrregular()
bool Wombat.MamdaTradeListener.getIsIrregular ()
MamdaTradeReport.getIsIrregular()
Implements Wombat.MamdaTradeReport.
getBeginGapSeqNum()
long Wombat.MamdaTradeListener.getBeginGapSeqNum ()
MamdaTradeGap.getBeginGapSeqNum()
Implements Wombat.MamdaTradeGap.
getEndGapSeqNum()
long Wombat.MamdaTradeListener.getEndGapSeqNum ()
MamdaTradeGap.getEndGapSeqNum()
Implements Wombat.MamdaTradeGap.
getIsCancel()
bool Wombat.MamdaTradeListener.getIsCancel ()
MamdaTradeCancelOrError.getIsCancel()
Implements Wombat.MamdaTradeCancelOrError.
getOrigSeqNum()
long Wombat.MamdaTradeListener.getOrigSeqNum ()
MamdaTradeCancelOrError.getOrigSeqNum()
Implements Wombat.MamdaTradeCancelOrError.
getOrigPrice()
double Wombat.MamdaTradeListener.getOrigPrice ()
MamdaTradeCancelOrError.getOrigPrice()
Implements Wombat.MamdaTradeCancelOrError.
getOrigVolume()
long Wombat.MamdaTradeListener.getOrigVolume ()
MamdaTradeCancelOrError.getOrigVolume()
Implements Wombat.MamdaTradeCancelOrError.
getOrigPartId()
String Wombat.MamdaTradeListener.getOrigPartId ()
MamdaTradeCancelOrError.getOrigPartId()
Implements Wombat.MamdaTradeCancelOrError.
getOrigQual()
String Wombat.MamdaTradeListener.getOrigQual ()
MamdaTradeCancelOrError.getOrigQual()
Implements Wombat.MamdaTradeCancelOrError.
getOrigQualNative()
String Wombat.MamdaTradeListener.getOrigQualNative ()
MamdaTradeCancelOrError.getOrigQualNative()
Implements Wombat.MamdaTradeCancelOrError.
getOrigCondition()
String Wombat.MamdaTradeListener.getOrigCondition ()
MamdaTradeCancelOrError.getOrigCondition()
Implements Wombat.MamdaTradeCancelOrError.
getOrigSellersSaleDays()
long Wombat.MamdaTradeListener.getOrigSellersSaleDays ()
MamdaTradeCancelOrError.getOrigSellersSaleDays()
Implements Wombat.MamdaTradeCancelOrError.
getOrigStopStock()
char Wombat.MamdaTradeListener.getOrigStopStock ()
MamdaTradeCancelOrError.getOrigStopStock()
Implements Wombat.MamdaTradeCancelOrError.
getCorrPrice()
double Wombat.MamdaTradeListener.getCorrPrice ()
MamdaTradeCorrection.getCorrPrice()
Implements Wombat.MamdaTradeCorrection.
getCorrVolume()
long Wombat.MamdaTradeListener.getCorrVolume ()
MamdaTradeCorrection.getCorrVolume()
Implements Wombat.MamdaTradeCorrection.
getCorrPartId()
String Wombat.MamdaTradeListener.getCorrPartId ()
MamdaTradeCorrection.getCorrPartId()
Implements Wombat.MamdaTradeCorrection.
getCorrQual()
String Wombat.MamdaTradeListener.getCorrQual ()
MamdaTradeCorrection.getCorrQual()
Implements Wombat.MamdaTradeCorrection.
getCorrQualNative()
String Wombat.MamdaTradeListener.getCorrQualNative ()
MamdaTradeCorrection.getCorrQualNative()
Implements Wombat.MamdaTradeCorrection.
getCorrCondition()
String Wombat.MamdaTradeListener.getCorrCondition ()
MamdaTradeCorrection.getCorrCondition()
Implements Wombat.MamdaTradeCorrection.
getCorrSellersSaleDays()
long Wombat.MamdaTradeListener.getCorrSellersSaleDays ()
MamdaTradeCorrection.getCorrSellersSaleDays()
Implements Wombat.MamdaTradeCorrection.
getCorrStopStock()
char Wombat.MamdaTradeListener.getCorrStopStock ()
MamdaTradeCorrection.getCorrStopStock()
Implements Wombat.MamdaTradeCorrection.
getIsIndicative()
bool Wombat.MamdaTradeListener.getIsIndicative ()
MamdaTradeClosing.getIsIndicative()
Implements Wombat.MamdaTradeClosing.
getSymbolFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getSymbolFieldState ()
getPartIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getPartIdFieldState ()
MamdaBasicEvent.getPartIdFieldState()
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getSrcTimeFieldState ()
MamdaBasicEvent.getSrcTimeFieldState()
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getActivityTimeFieldState ()
MamdaBasicEvent.getActivityTimeFieldState()
Implements Wombat.MamdaBasicEvent.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLineTimeFieldState ()
MamdaBasicEvent.getLineTimeFieldState()
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getSendTimeFieldState ()
MamdaBasicEvent.getSendTimeFieldState()
getPubIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getPubIdFieldState ()
MamdaBasicEvent.getPubIdFieldState()
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getEventSeqNumFieldState ()
MamdaBasicEvent.getEventSeqNumFieldState()
Implements Wombat.MamdaBasicEvent.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getEventTimeFieldState ()
MamdaBasicEvent.getEventTimeFieldState()
Implements Wombat.MamdaBasicEvent.
getLastPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLastPriceFieldState ()
MamdaTradeRecap.getLastPriceFieldState()
Implements Wombat.MamdaTradeRecap.
getLastVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLastVolumeFieldState ()
MamdaTradeRecap.getLastVolumeFieldState()
Implements Wombat.MamdaTradeRecap.
getLastPartIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLastPartIdFieldState ()
MamdaTradeRecap.getLastPartIdFieldState()
Implements Wombat.MamdaTradeRecap.
getTradeIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeIdFieldState ()
MamdaTradeReport.getTradeIdFieldState()
Implements Wombat.MamdaTradeReport.
getOrigTradeIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigTradeIdFieldState ()
MamdaTradeCancelOrError.getOrigTradeIdFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getCorrTradeIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrTradeIdFieldState ()
MamdaTradeCorrection.getCorrTradeIdFieldState()
Implements Wombat.MamdaTradeCorrection.
getLastTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLastTimeFieldState ()
MamdaTradeRecap.getLastTimeFieldState()
Implements Wombat.MamdaTradeRecap.
getIrregPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getIrregPriceFieldState ()
MamdaTradeRecap.getIrregPriceFieldState()
Implements Wombat.MamdaTradeRecap.
getIrregVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getIrregVolumeFieldState ()
MamdaTradeRecap.getIrregVolumeFieldState()
Implements Wombat.MamdaTradeRecap.
getIrregPartIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getIrregPartIdFieldState ()
MamdaTradeRecap.getIrregPartIdFieldState()
Implements Wombat.MamdaTradeRecap.
getIrregTimeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getIrregTimeFieldState ()
MamdaTradeRecap.getIrregTimeFieldState()
Implements Wombat.MamdaTradeRecap.
getTradeDateFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeDateFieldState ()
MamdaTradeRecap.getLastTimeFieldState()
Implements Wombat.MamdaTradeRecap.
getAccVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getAccVolumeFieldState ()
MamdaTradeRecap.getAccVolumeFieldState()
Implements Wombat.MamdaTradeRecap.
getOffExAccVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOffExAccVolumeFieldState ()
MamdaTradeRecap.getOffExAccVolumeFieldState()
Implements Wombat.MamdaTradeRecap.
getOnExAccVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOnExAccVolumeFieldState ()
MamdaTradeRecap.getOnExAccVolumeFieldState()
Implements Wombat.MamdaTradeRecap.
getNetChangeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getNetChangeFieldState ()
MamdaTradeRecap.getNetChangeFieldState()
Implements Wombat.MamdaTradeRecap.
getPctChangeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getPctChangeFieldState ()
MamdaTradeRecap.getPctChangeFieldState()
Implements Wombat.MamdaTradeRecap.
getTradeDirectionFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeDirectionFieldState ()
MamdaTradeRecap.getTradeDirectionFieldState()
Implements Wombat.MamdaTradeRecap.
getSideFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getSideFieldState ()
MamdaTradeRecap.getSideFieldState()
Implements Wombat.MamdaTradeRecap.
getOpenPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOpenPriceFieldState ()
MamdaTradeRecap.getOpenPriceFieldState()
Implements Wombat.MamdaTradeRecap.
getHighPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getHighPriceFieldState ()
MamdaTradeRecap.getHighPriceFieldState()
Implements Wombat.MamdaTradeRecap.
getLowPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLowPriceFieldState ()
MamdaTradeRecap.getLowPriceFieldState()
Implements Wombat.MamdaTradeRecap.
getClosePriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getClosePriceFieldState ()
MamdaTradeRecap.getClosePriceFieldState()
Implements Wombat.MamdaTradeClosing.
getPrevClosePriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getPrevClosePriceFieldState ()
MamdaTradeRecap.getPrevClosePriceFieldState()
Implements Wombat.MamdaTradeRecap.
getPrevCloseDateFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getPrevCloseDateFieldState ()
MamdaTradeRecap.getPrevCloseDateFieldState()
Implements Wombat.MamdaTradeRecap.
getAdjPrevCloseFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getAdjPrevCloseFieldState ()
MamdaTradeRecap.getAdjPrevCloseFieldState()
Implements Wombat.MamdaTradeRecap.
getBlockCountFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getBlockCountFieldState ()
MamdaTradeRecap.getBlockCountFieldState()
Implements Wombat.MamdaTradeRecap.
getBlockVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getBlockVolumeFieldState ()
MamdaTradeRecap.getBlockVolumeFieldState()
Implements Wombat.MamdaTradeRecap.
getVwapFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getVwapFieldState ()
MamdaTradeRecap.getVwapFieldState()
Implements Wombat.MamdaTradeRecap.
getOffExVwapFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOffExVwapFieldState ()
MamdaTradeRecap.getOffExVwapFieldState()
Implements Wombat.MamdaTradeRecap.
getOnExVwapFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOnExVwapFieldState ()
MamdaTradeRecap.getOnExVwapFieldState()
Implements Wombat.MamdaTradeRecap.
getTotalValueFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTotalValueFieldState ()
MamdaTradeRecap.getTotalValueFieldState()
Implements Wombat.MamdaTradeRecap.
getOffExTotalValueFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOffExTotalValueFieldState ()
MamdaTradeRecap.getOffExTotalValueFieldState()
Implements Wombat.MamdaTradeRecap.
getOnExTotalValueFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOnExTotalValueFieldState ()
MamdaTradeRecap.getOnExTotalValueFieldState()
Implements Wombat.MamdaTradeRecap.
getStdDevFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getStdDevFieldState ()
MamdaTradeRecap.getStdDevFieldState()
Implements Wombat.MamdaTradeRecap.
getStdDevSumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getStdDevSumFieldState ()
MamdaTradeRecap.getStdDevSumFieldState()
Implements Wombat.MamdaTradeRecap.
getStdDevSumSquaresFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getStdDevSumSquaresFieldState ()
MamdaTradeRecap.getStdDevSumSquaresFieldState()
Implements Wombat.MamdaTradeRecap.
getOrderIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrderIdFieldState ()
MamdaTradeRecap.getOrderId
Implements Wombat.MamdaTradeRecap.
getSettlePriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getSettlePriceFieldState ()
MamdaTradeRecap.getSettlePriceFieldState()
Implements Wombat.MamdaTradeRecap.
getSettleDateFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getSettleDateFieldState ()
MamdaTradeRecap.getSettleDateFieldState()
Implements Wombat.MamdaTradeRecap.
getShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getShortSaleCircuitBreakerFieldState ()
Returns the FieldState, always MODIFIED
Returns
Implements Wombat.MamdaTradeRecap.
getOrigShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigShortSaleCircuitBreakerFieldState ()
Returns the FieldState, always MODIFIED
Returns
Implements Wombat.MamdaTradeCancelOrError.
getCorrShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrShortSaleCircuitBreakerFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeCorrection.
getTradePriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradePriceFieldState ()
MamdaTradeReport.getTradePriceFieldState()
Implements Wombat.MamdaTradeReport.
getTradeVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeVolumeFieldState ()
MamdaTradeReport.getTradeVolumeFieldState()
Implements Wombat.MamdaTradeReport.
getTradePartIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradePartIdFieldState ()
MamdaTradeReport.getTradePartIdFieldState()
Implements Wombat.MamdaTradeReport.
getTradeQualFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeQualFieldState ()
MamdaTradeReport.getTradeQualFieldState()
Implements Wombat.MamdaTradeReport.
getTradeQualNativeStrFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeQualNativeStrFieldState ()
MamdaTradeReport.getTradeQualNativeStrFieldState()
Implements Wombat.MamdaTradeReport.
getTradeConditionFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeConditionFieldState ()
MamdaTradeReport.getTradeConditionFieldState()
Implements Wombat.MamdaTradeReport.
getTradeSellersSaleDaysFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeSellersSaleDaysFieldState ()
MamdaTradeReport.getTradeSellersSaleDaysFieldState()
Implements Wombat.MamdaTradeReport.
getTradeStopStockFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeStopStockFieldState ()
MamdaTradeReport.getTradeStopStockFieldState()
Implements Wombat.MamdaTradeReport.
getTradeExecVenueFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeExecVenueFieldState ()
MamdaTradeRecap.getTradeExecVenueFieldState()
Implements Wombat.MamdaTradeRecap.
getOffExchangeTradePriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOffExchangeTradePriceFieldState ()
MamdaTradeRecap.getOffExchangeTradePriceFieldState()
Implements Wombat.MamdaTradeRecap.
getOnExchangeTradePriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOnExchangeTradePriceFieldState ()
MamdaTradeRecap.getOnExchangeTradePriceFieldState()
Implements Wombat.MamdaTradeRecap.
getTradeCountFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeCountFieldState ()
MamdaTradeRecap.getTradeCountFieldState()
Implements Wombat.MamdaTradeRecap.
getTradeUnitsFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTradeUnitsFieldState ()
MamdaTradeRecap.getTradeUnitsFieldState()
Implements Wombat.MamdaTradeRecap.
getLastSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLastSeqNumFieldState ()
MamdaTradeRecap.getLastSeqNumFieldState()
Implements Wombat.MamdaTradeRecap.
getHighSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getHighSeqNumFieldState ()
MamdaTradeRecap.getHighSeqNumFieldState()
Implements Wombat.MamdaTradeRecap.
getLowSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getLowSeqNumFieldState ()
MamdaTradeRecap.getLowSeqNum()
Implements Wombat.MamdaTradeRecap.
getTotalVolumeSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getTotalVolumeSeqNumFieldState ()
MamdaTradeRecap.getTotalVolumeSeqNumFieldState()
Implements Wombat.MamdaTradeRecap.
getCurrencyCodeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCurrencyCodeFieldState ()
MamdaTradeRecap.getCurrencyCodeFieldState()
Implements Wombat.MamdaTradeRecap.
getIsIrregularFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getIsIrregularFieldState ()
MamdaTradeReport.getIsIrregularFieldState()
Implements Wombat.MamdaTradeReport.
getBeginGapSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getBeginGapSeqNumFieldState ()
MamdaTradeGap.getBeginGapSeqNumFieldState()
Implements Wombat.MamdaTradeGap.
getEndGapSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getEndGapSeqNumFieldState ()
MamdaTradeGap.getEndGapSeqNumFieldState()
Implements Wombat.MamdaTradeGap.
getOrigSeqNumFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigSeqNumFieldState ()
MamdaTradeCancelOrError.getOrigSeqNumFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigPriceFieldState ()
MamdaTradeCancelOrError.getOrigPriceFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigVolumeFieldState ()
MamdaTradeCancelOrError.getOrigVolumeFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigPartIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigPartIdFieldState ()
MamdaTradeCancelOrError.getOrigPartIdFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigQualFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigQualFieldState ()
MamdaTradeCancelOrError.getOrigQualFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigQualNativeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigQualNativeFieldState ()
MamdaTradeCancelOrError.getOrigQualNativeFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigConditionFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigConditionFieldState ()
MamdaTradeCancelOrError.getOrigConditionFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigSellersSaleDaysFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigSellersSaleDaysFieldState ()
MamdaTradeCancelOrError.getOrigSellersSaleDaysFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getOrigStopStockFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getOrigStopStockFieldState ()
MamdaTradeCancelOrError.getOrigStopStockFieldState()
Implements Wombat.MamdaTradeCancelOrError.
getCorrPriceFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrPriceFieldState ()
MamdaTradeCorrection.getCorrPriceFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrVolumeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrVolumeFieldState ()
MamdaTradeCorrection.getCorrVolumeFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrPartIdFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrPartIdFieldState ()
MamdaTradeCorrection.getCorrPartIdFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrQualFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrQualFieldState ()
MamdaTradeCorrection.getCorrQualFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrQualNativeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrQualNativeFieldState ()
MamdaTradeCorrection.getCorrQualNativeFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrConditionFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrConditionFieldState ()
MamdaTradeCorrection.getCorrConditionFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrSellersSaleDaysFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrSellersSaleDaysFieldState ()
MamdaTradeCorrection.getCorrSellersSaleDaysFieldState()
Implements Wombat.MamdaTradeCorrection.
getCorrStopStockFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getCorrStopStockFieldState ()
MamdaTradeCorrection.getCorrStopStockFieldState()
Implements Wombat.MamdaTradeCorrection.
getIsIndicativeFieldState()
MamdaFieldState Wombat.MamdaTradeListener.getIsIndicativeFieldState ()
MamdaTradeClosing.getIsIndicativeFieldState()
Implements Wombat.MamdaTradeClosing.
populateRecap()
void Wombat.MamdaTradeListener.populateRecap (MamdaConcreteTradeRecap recap)
Parameters
recap
References Wombat.MamdaConcreteTradeRecap.setAccVolume(), Wombat.MamdaConcreteTradeRecap.setActTime(), Wombat.MamdaConcreteTradeRecap.setAdjPrevClose(), Wombat.MamdaConcreteTradeRecap.setBlockCount(), Wombat.MamdaConcreteTradeRecap.setBlockVolume(), Wombat.MamdaConcreteTradeRecap.setCancelTime(), Wombat.MamdaConcreteTradeRecap.setClosePrice(), Wombat.MamdaConcreteTradeRecap.setCorrCondStr(), Wombat.MamdaConcreteTradeRecap.setCorrPartId(), Wombat.MamdaConcreteTradeRecap.setCorrPrice(), Wombat.MamdaConcreteTradeRecap.setCorrQualNativeStr(), Wombat.MamdaConcreteTradeRecap.setCorrQualStr(), Wombat.MamdaConcreteTradeRecap.setCorrSellersSaleDays(), Wombat.MamdaConcreteTradeRecap.setCorrStopStockInd(), Wombat.MamdaConcreteTradeRecap.setCorrTradeId(), Wombat.MamdaConcreteTradeRecap.setCorrVolume(), Wombat.MamdaConcreteTradeRecap.setCurrencyCode(), Wombat.MamdaConcreteTradeRecap.setEventSeqNum(), Wombat.MamdaConcreteTradeRecap.setEventTime(), Wombat.MamdaConcreteTradeRecap.setHighPrice(), Wombat.MamdaConcreteTradeRecap.setHighSeqNum(), Wombat.MamdaConcreteTradeRecap.setIrregPartId(), Wombat.MamdaConcreteTradeRecap.setIrregPrice(), Wombat.MamdaConcreteTradeRecap.setIrregTime(), Wombat.MamdaConcreteTradeRecap.setIrregVolume(), Wombat.MamdaConcreteTradeRecap.setIsCancel(), Wombat.MamdaConcreteTradeRecap.setIsIrregular(), Wombat.MamdaConcreteTradeRecap.setLastPartId(), Wombat.MamdaConcreteTradeRecap.setLastPrice(), Wombat.MamdaConcreteTradeRecap.setLastSeqNum(), Wombat.MamdaConcreteTradeRecap.setLastTime(), Wombat.MamdaConcreteTradeRecap.setLastVolume(), Wombat.MamdaConcreteTradeRecap.setLineTime(), Wombat.MamdaConcreteTradeRecap.setLowPrice(), Wombat.MamdaConcreteTradeRecap.setLowSeqNum(), Wombat.MamdaConcreteTradeRecap.setNetChange(), Wombat.MamdaConcreteTradeRecap.setOffExAccVolume(), Wombat.MamdaConcreteTradeRecap.setOffExchangeTradePrice(), Wombat.MamdaConcreteTradeRecap.setOffExTotalValue(), Wombat.MamdaConcreteTradeRecap.setOffExVwap(), Wombat.MamdaConcreteTradeRecap.setOnExAccVolume(), Wombat.MamdaConcreteTradeRecap.setOnExchangeTradePrice(), Wombat.MamdaConcreteTradeRecap.setOnExTotalValue(), Wombat.MamdaConcreteTradeRecap.setOnExVwap(), Wombat.MamdaConcreteTradeRecap.setOpenPrice(), Wombat.MamdaConcreteTradeRecap.setOrderId(), Wombat.MamdaConcreteTradeRecap.setOrigCondStr(), Wombat.MamdaConcreteTradeRecap.setOrigPartId(), Wombat.MamdaConcreteTradeRecap.setOrigPrice(), Wombat.MamdaConcreteTradeRecap.setOrigQualNativeStr(), Wombat.MamdaConcreteTradeRecap.setOrigQualStr(), Wombat.MamdaConcreteTradeRecap.setOrigSellersSaleDays(), Wombat.MamdaConcreteTradeRecap.setOrigSeqNum(), Wombat.MamdaConcreteTradeRecap.setOrigStopStockInd(), Wombat.MamdaConcreteTradeRecap.setOrigTradeId(), Wombat.MamdaConcreteTradeRecap.setOrigVolume(), Wombat.MamdaConcreteTradeRecap.setPartId(), Wombat.MamdaConcreteTradeRecap.setPctChange(), Wombat.MamdaConcreteTradeRecap.setPrevCloseDate(), Wombat.MamdaConcreteTradeRecap.setPrevClosePrice(), Wombat.MamdaConcreteTradeRecap.setPubId(), Wombat.MamdaConcreteTradeRecap.setSellersSaleDays(), Wombat.MamdaConcreteTradeRecap.setSendTime(), Wombat.MamdaConcreteTradeRecap.setSettleDate(), Wombat.MamdaConcreteTradeRecap.setSettlePrice(), Wombat.MamdaConcreteTradeRecap.setSide(), Wombat.MamdaConcreteTradeRecap.setSrcTime(), Wombat.MamdaConcreteTradeRecap.setStdDev(), Wombat.MamdaConcreteTradeRecap.setStdDevSum(), Wombat.MamdaConcreteTradeRecap.setStdDevSumSquares(), Wombat.MamdaConcreteTradeRecap.setStopStockInd(), Wombat.MamdaConcreteTradeRecap.setSymbol(), Wombat.MamdaConcreteTradeRecap.setTotalValue(), Wombat.MamdaConcreteTradeRecap.setTotalVolumeSeqNum(), Wombat.MamdaConcreteTradeRecap.setTradeCondStr(), Wombat.MamdaConcreteTradeRecap.setTradeCount(), Wombat.MamdaConcreteTradeRecap.setTradeDate(), Wombat.MamdaConcreteTradeRecap.setTradeDirection(), Wombat.MamdaConcreteTradeRecap.setTradeExecVenue(), Wombat.MamdaConcreteTradeRecap.setTradeId(), Wombat.MamdaConcreteTradeRecap.setTradePartId(), Wombat.MamdaConcreteTradeRecap.setTradePrice(), Wombat.MamdaConcreteTradeRecap.setTradeQualNativeStr(), Wombat.MamdaConcreteTradeRecap.setTradeQualStr(), Wombat.MamdaConcreteTradeRecap.setTradeUnits(), Wombat.MamdaConcreteTradeRecap.setTradeVolume(), and Wombat.MamdaConcreteTradeRecap.setVwap().
onMsg()
void Wombat.MamdaTradeListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Parameters
subscription
msg
msgType
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaTradeFields.isSet(), Wombat.MamdaTradeHandler.onTradeCancelOrError(), Wombat.MamdaTradeHandler.onTradeClosing(), Wombat.MamdaTradeHandler.onTradeCorrection(), Wombat.MamdaTradeHandler.onTradeGap(), Wombat.MamdaTradeHandler.onTradeRecap(), and Wombat.MamdaTradeHandler.onTradeReport().
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().