OpenMAMDA C# API: Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache Class Reference
Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache Class Reference
Public Attributes
DateTime mSrcTime = DateTime.MinValue
DateTime mActTime = DateTime.MinValue
long mEventSeqNum
DateTime mEventTime = DateTime.MinValue
long mSecStatus
long mSecStatusQual
string mSecStatusStr
string mSecStatusQualStr
string mSecStatusOrigStr
char mShortSaleCircuitBreaker
string mReason
DateTime mLuldTime = DateTime.MinValue
char mLuldIndicator
MamaPrice mLuldHighLimit = new MamaPrice ()
MamaPrice mLuldLowLimit = new MamaPrice ()
MamdaFieldState mSrcTimeFieldState = new MamdaFieldState()
MamdaFieldState mActTimeFieldState = new MamdaFieldState()
MamdaFieldState mEventSeqNumFieldState = new MamdaFieldState()
MamdaFieldState mEventTimeFieldState = new MamdaFieldState()
MamdaFieldState mSecStatusFieldState = new MamdaFieldState()
MamdaFieldState mSecStatusQualFieldState = new MamdaFieldState()
MamdaFieldState mSecStatusStrFieldState = new MamdaFieldState()
MamdaFieldState mSecStatusQualStrFieldState = new MamdaFieldState()
MamdaFieldState mSecStatusOrigStrFieldState = new MamdaFieldState()
MamdaFieldState mShortSaleCircuitBreakerFieldState = new MamdaFieldState()
MamdaFieldState mReasonFieldState = new MamdaFieldState()
MamdaFieldState mLuldTimeFieldState = new MamdaFieldState()
MamdaFieldState mLuldIndicatorFieldState = new MamdaFieldState()
MamdaFieldState mLuldHighLimitFieldState = new MamdaFieldState()
MamdaFieldState mLuldLowLimitFieldState = new MamdaFieldState()
Member Data Documentation
mSrcTime
DateTime Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTime = DateTime.MinValue
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getSrcTime(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mActTime
DateTime Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTime = DateTime.MinValue
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getActivityTime(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mEventSeqNum
long Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNum
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getEventSeqNum(), and Wombat.MamdaSecurityStatusListener.getFieldAsString().
mEventTime
DateTime Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTime = DateTime.MinValue
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getEventTime(), and Wombat.MamdaSecurityStatusListener.getFieldAsString().
mSecStatus
long Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatus
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mSecStatusQual
long Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQual
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mSecStatusStr
string Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getSecurityStatus(), Wombat.MamdaSecurityStatusListener.getSecurityStatusEnum(), Wombat.MamdaSecurityStatusListener.getSecurityStatusStr(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mSecStatusQualStr
string Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getSecurityStatusOrigStr(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifier(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierEnum(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierStr(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mSecStatusOrigStr
string Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStr
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), and Wombat.MamdaSecurityStatusListener.getFieldAsString().
mShortSaleCircuitBreaker
char Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreaker
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getShortSaleCircuitBreaker(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mReason
string Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReason
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getReason(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mLuldTime
DateTime Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTime = DateTime.MinValue
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldTime(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mLuldIndicator
char Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicator
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldIndicator(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mLuldHighLimit
MamaPrice Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimit = new MamaPrice ()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldHighLimit(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mLuldLowLimit
MamaPrice Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimit = new MamaPrice ()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldLowLimit(), and Wombat.MamdaSecurityStatusListener.populateRecap().
mSrcTimeFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getSrcTimeFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mActTimeFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getActivityTimeFieldState(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), and Wombat.MamdaSecurityStatusListener.onMsg().
mEventSeqNumFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNumFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getEventSeqNumFieldState(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), and Wombat.MamdaSecurityStatusListener.onMsg().
mEventTimeFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getEventTimeFieldState(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), and Wombat.MamdaSecurityStatusListener.onMsg().
mSecStatusFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), and Wombat.MamdaSecurityStatusListener.onMsg().
mSecStatusQualFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), and Wombat.MamdaSecurityStatusListener.onMsg().
mSecStatusStrFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getSecurityStatusEnumFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusStrFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mSecStatusQualStrFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getSecurityStatusOrigStrFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierEnumFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierStrFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mSecStatusOrigStrFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStrFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), and Wombat.MamdaSecurityStatusListener.onMsg().
mShortSaleCircuitBreakerFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreakerFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getShortSaleCircuitBreakerFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mReasonFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReasonFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getReasonFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mLuldTimeFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldTimeFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mLuldIndicatorFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicatorFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldIndicatorFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mLuldHighLimitFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimitFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldHighLimitFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().
mLuldLowLimitFieldState
MamdaFieldState Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimitFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaSecurityStatusListener.clearCache(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldLowLimitFieldState(), and Wombat.MamdaSecurityStatusListener.onMsg().