OpenMAMDA C# API: Wombat.MamdaOrderImbalanceType Class Reference
Wombat.MamdaOrderImbalanceType Class Reference
Public Member Functions
int getValue ()
Returns the integer value for the type.
string toString ()
Returns the string name for the enumerated type.
override string ToString ()
override int GetHashCode ()
bool equals (MamdaOrderImbalanceType imbDataType)
Compare the two types for equality.
override bool Equals (object obj)
Static Public Member Functions
static MamdaOrderImbalanceType enumObjectForValue (int value)
Return an instance of a MamdaOrderImbalanceType corresponding to the specified integer value.
static String valueToString (int value)
Utility method for mapping type integer values to corresponding string values.
static int stringToValue (String type)
static bool isMamdaOrderImbalanceType (int value)
static bool isMamdaImbalanceOrder (int value)
static bool operator== (MamdaOrderImbalanceType left, MamdaOrderImbalanceType right)
static bool operator!= (MamdaOrderImbalanceType left, MamdaOrderImbalanceType right)
Public Attributes
const int MARKET_IMBALANCE_BUY_VALUE = 16
MARKET_IMBALANCE_BUY.
const int MARKET_IMBALANCE_SELL_VALUE =17
MARKET_IMBALANCE_SELL.
const int NO_MARKET_IMBALANCE_VALUE = 18
NO_MARKET_IMBALANCE.
const int MOC_IMBALANCE_BUY_VALUE = 19
MOC_IMBALANCE_BUY.
const int MOC_IMBALANCE_SELL_VALUE = 20
MOC_IMBALANCE_SELL.
const int NO_MOC_IMBALANCE_VALUE = 21
NO_MOC_IMBALANCE.
const int ORDER_IMB_VALUE = 22
ORDER_IMB.
const int ORDER_INF_VALUE = 23
ORDER_INF.
const int ORDER_IMBALANCE_BUY_VALUE = 24
ORDER_IMBALANCE_BUY_VALUE.
const int ORDER_IMBALANCE_SELL_VALUE = 25
ORDER_IMBALANCE_SELL_VALUE.
const int NO_ORDER_IMBALANCE_VALUE = 26
NO_ORDER_IMBALANCE.
const int UNKNOWN = -99
UKNOWN.
Static Public Attributes
static readonly MamdaOrderImbalanceType MARKET_IMBALANCE_BUY
static readonly MamdaOrderImbalanceType MARKET_IMBALANCE_SELL
static readonly MamdaOrderImbalanceType NO_MARKET_IMBALANCE
static readonly MamdaOrderImbalanceType MOC_IMBALANCE_BUY
static readonly MamdaOrderImbalanceType MOC_IMBALANCE_SELL
static readonly MamdaOrderImbalanceType NO_MOC_IMBALANCE
static readonly MamdaOrderImbalanceType ORDER_IMB
static readonly MamdaOrderImbalanceType ORDER_INF
static readonly MamdaOrderImbalanceType ORDER_IMBALANCE_BUY
static readonly MamdaOrderImbalanceType ORDER_IMBALANCE_SELL
static readonly MamdaOrderImbalanceType NO_ORDER_IMBALANCE
static readonly MamdaOrderImbalanceType TYPE_UNKNOWN
Detailed Description
Member Function Documentation
getValue()
int Wombat.MamdaOrderImbalanceType.getValue ()
Returns the integer value for the type.
This value can be used in switch statements against the public XXX_VALUE static members of the class.
Returns
The integer type.
toString()
string Wombat.MamdaOrderImbalanceType.toString ()
Returns the string name for the enumerated type.
Returns
Name for the type.
Referenced by Wombat.MamdaOrderImbalanceType.ToString().
ToString()
override string Wombat.MamdaOrderImbalanceType.ToString ()
References Wombat.MamdaOrderImbalanceType.toString().
GetHashCode()
override int Wombat.MamdaOrderImbalanceType.GetHashCode ()
enumObjectForValue()
static MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.enumObjectForValue (int value) static
Return an instance of a MamdaOrderImbalanceType corresponding to the specified integer value.
Returns null if the integer value is not recognised.
Parameters
value Int value for a MamdaOrderImbalanceType
Returns
Instance of a MamdaOrderImbalanceType if a mapping exists.
References Wombat.MamdaOrderImbalanceType.MARKET_IMBALANCE_BUY, Wombat.MamdaOrderImbalanceType.MARKET_IMBALANCE_SELL, Wombat.MamdaOrderImbalanceType.MOC_IMBALANCE_BUY, Wombat.MamdaOrderImbalanceType.MOC_IMBALANCE_SELL, Wombat.MamdaOrderImbalanceType.NO_MARKET_IMBALANCE, Wombat.MamdaOrderImbalanceType.NO_MOC_IMBALANCE, Wombat.MamdaOrderImbalanceType.NO_ORDER_IMBALANCE, Wombat.MamdaOrderImbalanceType.ORDER_IMB, Wombat.MamdaOrderImbalanceType.ORDER_IMBALANCE_BUY, Wombat.MamdaOrderImbalanceType.ORDER_IMBALANCE_SELL, and Wombat.MamdaOrderImbalanceType.ORDER_INF.
valueToString()
static String Wombat.MamdaOrderImbalanceType.valueToString (int value) static
Utility method for mapping type integer values to corresponding string values.
Returns "UNKNOWN" if the int type value is not recognised.
Parameters
value The int value for a MamdaOrderImbalanceType
Returns
The string name value of the specified MamdaOrderImbalanceType value.
stringToValue()
static int Wombat.MamdaOrderImbalanceType.stringToValue (String type) static
References Wombat.MamdaOrderImbalanceType.UNKNOWN.
Referenced by Wombat.MamdaOrderImbalanceListener.onMsg().
isMamdaOrderImbalanceType()
static bool Wombat.MamdaOrderImbalanceType.isMamdaOrderImbalanceType (int value) static
Referenced by Wombat.MamdaOrderImbalanceListener.onMsg().
isMamdaImbalanceOrder()
static bool Wombat.MamdaOrderImbalanceType.isMamdaImbalanceOrder (int value) static
Referenced by Wombat.MamdaOrderImbalanceListener.onMsg().
equals()
bool Wombat.MamdaOrderImbalanceType.equals (MamdaOrderImbalanceType imbDataType)
Compare the two types for equality.
Returns true if the integer value of both types is equal. Otherwise returns false.
Parameters
imbDataType The object to check equality against.
Returns
Whether the two objects are equal.
Referenced by Wombat.MamdaOrderImbalanceType.Equals(), and Wombat.MamdaOrderImbalanceType.operator==().
Equals()
override bool Wombat.MamdaOrderImbalanceType.Equals (object obj)
References Wombat.MamdaOrderImbalanceType.equals().
operator==()
static bool Wombat.MamdaOrderImbalanceType.operator== (MamdaOrderImbalanceType left, MamdaOrderImbalanceType right) static
References Wombat.MamdaOrderImbalanceType.equals().
operator!=()
static bool Wombat.MamdaOrderImbalanceType.operator!= (MamdaOrderImbalanceType left, MamdaOrderImbalanceType right) static
Member Data Documentation
MARKET_IMBALANCE_BUY_VALUE
const int Wombat.MamdaOrderImbalanceType.MARKET_IMBALANCE_BUY_VALUE = 16
MARKET_IMBALANCE_BUY.
MARKET_IMBALANCE_BUY
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.MARKET_IMBALANCE_BUY static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(MARKET_IMBALANCE_BUY_VALUE), MARKET_IMBALANCE_BUY_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
MARKET_IMBALANCE_SELL_VALUE
const int Wombat.MamdaOrderImbalanceType.MARKET_IMBALANCE_SELL_VALUE =17
MARKET_IMBALANCE_SELL.
MARKET_IMBALANCE_SELL
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.MARKET_IMBALANCE_SELL static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(MARKET_IMBALANCE_SELL_VALUE), MARKET_IMBALANCE_SELL_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
NO_MARKET_IMBALANCE_VALUE
const int Wombat.MamdaOrderImbalanceType.NO_MARKET_IMBALANCE_VALUE = 18
NO_MARKET_IMBALANCE.
NO_MARKET_IMBALANCE
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.NO_MARKET_IMBALANCE static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(NO_MARKET_IMBALANCE_VALUE), NO_MARKET_IMBALANCE_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
MOC_IMBALANCE_BUY_VALUE
const int Wombat.MamdaOrderImbalanceType.MOC_IMBALANCE_BUY_VALUE = 19
MOC_IMBALANCE_BUY.
MOC_IMBALANCE_BUY
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.MOC_IMBALANCE_BUY static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(MOC_IMBALANCE_BUY_VALUE), MOC_IMBALANCE_BUY_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
MOC_IMBALANCE_SELL_VALUE
const int Wombat.MamdaOrderImbalanceType.MOC_IMBALANCE_SELL_VALUE = 20
MOC_IMBALANCE_SELL.
MOC_IMBALANCE_SELL
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.MOC_IMBALANCE_SELL static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(MOC_IMBALANCE_SELL_VALUE), MOC_IMBALANCE_SELL_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
NO_MOC_IMBALANCE_VALUE
const int Wombat.MamdaOrderImbalanceType.NO_MOC_IMBALANCE_VALUE = 21
NO_MOC_IMBALANCE.
NO_MOC_IMBALANCE
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.NO_MOC_IMBALANCE static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(NO_MOC_IMBALANCE_VALUE), NO_MOC_IMBALANCE_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
ORDER_IMB_VALUE
const int Wombat.MamdaOrderImbalanceType.ORDER_IMB_VALUE = 22
ORDER_IMB.
ORDER_IMB
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.ORDER_IMB static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(ORDER_IMB_VALUE), ORDER_IMB_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
ORDER_INF_VALUE
const int Wombat.MamdaOrderImbalanceType.ORDER_INF_VALUE = 23
ORDER_INF.
ORDER_INF
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.ORDER_INF static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(ORDER_INF_VALUE), ORDER_INF_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
ORDER_IMBALANCE_BUY_VALUE
const int Wombat.MamdaOrderImbalanceType.ORDER_IMBALANCE_BUY_VALUE = 24
ORDER_IMBALANCE_BUY_VALUE.
ORDER_IMBALANCE_BUY
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.ORDER_IMBALANCE_BUY static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(ORDER_IMBALANCE_BUY_VALUE), ORDER_IMBALANCE_BUY_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
ORDER_IMBALANCE_SELL_VALUE
const int Wombat.MamdaOrderImbalanceType.ORDER_IMBALANCE_SELL_VALUE = 25
ORDER_IMBALANCE_SELL_VALUE.
ORDER_IMBALANCE_SELL
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.ORDER_IMBALANCE_SELL static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(ORDER_IMBALANCE_SELL_VALUE), ORDER_IMBALANCE_SELL_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
NO_ORDER_IMBALANCE_VALUE
const int Wombat.MamdaOrderImbalanceType.NO_ORDER_IMBALANCE_VALUE = 26
NO_ORDER_IMBALANCE.
NO_ORDER_IMBALANCE
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.NO_ORDER_IMBALANCE static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(NO_ORDER_IMBALANCE_VALUE), NO_ORDER_IMBALANCE_VALUE)
Referenced by Wombat.MamdaOrderImbalanceType.enumObjectForValue().
UNKNOWN
const int Wombat.MamdaOrderImbalanceType.UNKNOWN = -99
UKNOWN.
Referenced by Wombat.MamdaOrderImbalanceType.stringToValue().
TYPE_UNKNOWN
readonly MamdaOrderImbalanceType Wombat.MamdaOrderImbalanceType.TYPE_UNKNOWN static
Initial value:
=
            new MamdaOrderImbalanceType(valueToString(UNKNOWN), UNKNOWN)