OpenMAMDA C# API: Wombat.MamdaAuctionListener Class Reference
Wombat.MamdaAuctionListener Class Reference
MamdaAuctionListener is a class that specializes in handling Auction updates.
Inherits Wombat.MamdaMsgListener, Wombat.MamdaAuctionRecap, and Wombat.MamdaAuctionUpdate.
Public Member Functions
MamdaAuctionListener ()
Create a specialized Auction listener.
void addHandler (MamdaAuctionHandler handler)
Add a specialized Auction handler.
string getSymbol ()
Symbol.
string getPartId ()
Participant ID.
DateTime getSrcTime ()
Returns the source time.
DateTime getActivityTime ()
DateTime getLineTime ()
Line time.
DateTime getSendTime ()
Send time.
DateTime getEventTime ()
long getEventSeqNum ()
MamaPrice getUncrossPrice ()
Get the uncross price.
double getUncrossVolume ()
Get the uncross Volume.
long getUncrossPriceInd ()
Get the uncross price indicator.
MamdaFieldState getSymbolFieldState ()
Returns the field state.
MamdaFieldState getPartIdFieldState ()
Returns the field state.
MamdaFieldState getSrcTimeFieldState ()
Returns the field state.
MamdaFieldState getActivityTimeFieldState ()
Returns the field state.
MamdaFieldState getLineTimeFieldState ()
Returns the field state.
MamdaFieldState getSendTimeFieldState ()
Returns the field state.
MamdaFieldState getEventTimeFieldState ()
Returns the field state.
MamdaFieldState getEventSeqNumFieldState ()
Returns the field state.
MamdaFieldState getUncrossPriceFieldState ()
Get the field state
MamdaFieldState getUncrossVolumeFieldState ()
Get the field state
MamdaFieldState getUncrossPriceIndFieldState ()
Get the field state
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
string getFieldAsString (MamaMsgField field)
Detailed Description
MamdaAuctionListener is a class that specializes in handling Auction updates.
Developers provide their own implementation of the MamdaAuctionHandler interface and will be delivered notifications for Auctions and Auction closing prices. An obvious application for this MAMDA class is any kind of Auction tick capture application.
Note: The MamdaAuctionListener class caches Auction-related field values. Among other reasons, caching of these fields makes it possible to provide complete Auction-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaAuctionListener()
Wombat.MamdaAuctionListener.MamdaAuctionListener ()
Create a specialized Auction listener.
This listener handles Auction updates, quote recaps, and Auction gap notifications.
Member Function Documentation
addHandler()
void Wombat.MamdaAuctionListener.addHandler (MamdaAuctionHandler handler)
Add a specialized Auction handler.
Currently, only one handler can (and must) be registered.
Parameters
handler
getSymbol()
string Wombat.MamdaAuctionListener.getSymbol ()
Symbol.
This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements Wombat.MamdaBasicRecap.
getPartId()
string Wombat.MamdaAuctionListener.getPartId ()
Participant ID.
This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements Wombat.MamdaBasicRecap.
getSrcTime()
DateTime Wombat.MamdaAuctionListener.getSrcTime ()
Returns the source time.
Returns
Source time. Typically, the exchange generated feed
time stamp. This is often the same as the "event time",
because many feeds do not distinguish between the actual event
time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getActivityTime()
DateTime Wombat.MamdaAuctionListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements Wombat.MamdaBasicEvent.
getLineTime()
DateTime Wombat.MamdaAuctionListener.getLineTime ()
Line time.
A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements Wombat.MamdaBasicRecap.
getSendTime()
DateTime Wombat.MamdaAuctionListener.getSendTime ()
Send time.
A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware). See MAMA API: MamaDateTime::currentTime()).
Implements Wombat.MamdaBasicRecap.
getEventTime()
DateTime Wombat.MamdaAuctionListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getEventSeqNum()
long Wombat.MamdaAuctionListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements Wombat.MamdaBasicEvent.
getUncrossPrice()
MamaPrice Wombat.MamdaAuctionListener.getUncrossPrice ()
Get the uncross price.
Returns
Indicative or firm auction price.
Implements Wombat.MamdaAuctionRecap.
getUncrossVolume()
double Wombat.MamdaAuctionListener.getUncrossVolume ()
Get the uncross Volume.
Returns
Indicative Volume or the volume turned over in the auction
Implements Wombat.MamdaAuctionRecap.
getUncrossPriceInd()
long Wombat.MamdaAuctionListener.getUncrossPriceInd ()
Get the uncross price indicator.
Returns
The uncross price ind - indicates whether the price and volume is indicative of the current state of the auction or whether its the firm auction price and volume
Implements Wombat.MamdaAuctionRecap.
References Wombat.MamdaUncrossPriceInd.mamdaAuctionPriceIndFromString().
getSymbolFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getSymbolFieldState ()
Returns the field state.
Returns
Symbol Field State
Implements Wombat.MamdaBasicRecap.
getPartIdFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getPartIdFieldState ()
Returns the field state.
Returns
Participant ID Field State
Implements Wombat.MamdaBasicRecap.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getSrcTimeFieldState ()
Returns the field state.
Returns
Source time Field State
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getActivityTimeFieldState ()
Returns the field state.
Returns
Activity time Field State
Implements Wombat.MamdaBasicEvent.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getLineTimeFieldState ()
Returns the field state.
Returns
Line Time Field State
Implements Wombat.MamdaBasicRecap.
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getSendTimeFieldState ()
Returns the field state.
Returns
Send time Field State
Implements Wombat.MamdaBasicRecap.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getEventTimeFieldState ()
Returns the field state.
Returns
Event Time Field State
Implements Wombat.MamdaBasicEvent.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getEventSeqNumFieldState ()
Returns the field state.
Returns
Source sequence number Field State
Implements Wombat.MamdaBasicEvent.
getUncrossPriceFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getUncrossPriceFieldState ()
Get the field state
Returns
Field state
Implements Wombat.MamdaAuctionRecap.
getUncrossVolumeFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getUncrossVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaAuctionRecap.
getUncrossPriceIndFieldState()
MamdaFieldState Wombat.MamdaAuctionListener.getUncrossPriceIndFieldState ()
Get the field state
Returns
Field state
Implements Wombat.MamdaAuctionRecap.
onMsg()
void Wombat.MamdaAuctionListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Parameters
subscription The MamdaSubscription to which this listener was registered.
msg The MamaMsg received by the underlying MAMA API and which resulted in this callback being invoked.
msgType The message type. e.g. INITIAL, RECAP, UPDATE etc.
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaAuctionFields.isSet().
getFieldAsString()
string Wombat.MamdaAuctionListener.getFieldAsString (MamaMsgField field)
References Wombat.MamdaCommonFields.ACTIVITY_TIME, Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaAuctionFields.getMaxFid(), Wombat.MamdaCommonFields.ISSUE_SYMBOL, Wombat.MamdaCommonFields.LINE_TIME, Wombat.MamdaAuctionHandler.onAuctionRecap(), Wombat.MamdaAuctionHandler.onAuctionUpdate(), Wombat.MamdaCommonFields.PART_ID, Wombat.MamdaCommonFields.SEND_TIME, Wombat.MamdaCommonFields.SRC_TIME, Wombat.MamdaCommonFields.SYMBOL, Wombat.MamdaAuctionFields.UNCROSS_PRICE, Wombat.MamdaAuctionFields.UNCROSS_PRICE_IND, and Wombat.MamdaAuctionFields.UNCROSS_VOLUME.
Referenced by Wombat.MamdaAuctionListener.getFieldAsString().