OpenMAMDA C# API: Wombat.Containers.ArrayListCollection Class Reference
Wombat.Containers.ArrayListCollection Class Reference
Inherits Wombat.Containers.Collection.
Public Member Functions
ArrayListCollection ()
virtual int size ()
virtual bool isEmpty ()
virtual bool contains (object o)
virtual object [] toArray ()
virtual bool add (object o)
virtual bool remove (object o)
virtual bool containsAll (Collection c)
virtual bool addAll (Collection c)
virtual bool removeAll (Collection c)
virtual bool retainAll (Collection c)
virtual void clear ()
Iterator iterator ()
Constructor & Destructor Documentation
ArrayListCollection()
Wombat.Containers.ArrayListCollection.ArrayListCollection ()
Member Function Documentation
size()
virtual int Wombat.Containers.ArrayListCollection.size () virtual
Implements Wombat.Containers.Collection.
isEmpty()
virtual bool Wombat.Containers.ArrayListCollection.isEmpty () virtual
Implements Wombat.Containers.Collection.
contains()
virtual bool Wombat.Containers.ArrayListCollection.contains (object o) virtual
Implements Wombat.Containers.Collection.
toArray()
virtual object [] Wombat.Containers.ArrayListCollection.toArray () virtual
Implements Wombat.Containers.Collection.
add()
virtual bool Wombat.Containers.ArrayListCollection.add (object o) virtual
Implements Wombat.Containers.Collection.
Referenced by Wombat.Containers.RedBlackTree.entrySet().
remove()
virtual bool Wombat.Containers.ArrayListCollection.remove (object o) virtual
Implements Wombat.Containers.Collection.
containsAll()
virtual bool Wombat.Containers.ArrayListCollection.containsAll (Collection c) virtual
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
addAll()
virtual bool Wombat.Containers.ArrayListCollection.addAll (Collection c) virtual
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
removeAll()
virtual bool Wombat.Containers.ArrayListCollection.removeAll (Collection c) virtual
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
retainAll()
virtual bool Wombat.Containers.ArrayListCollection.retainAll (Collection c) virtual
Implements Wombat.Containers.Collection.
clear()
virtual void Wombat.Containers.ArrayListCollection.clear () virtual
Implements Wombat.Containers.Collection.
iterator()
Iterator Wombat.Containers.ArrayListCollection.iterator ()
Implements Wombat.Containers.Iterable.