OpenMAMDA C# API: Wombat.Containers.TreeMap Class Reference
Wombat.Containers.TreeMap Class Reference
Inherits Wombat.Containers.SortedMap, and ICloneable.
Inherited by Wombat.MamdaOptionExpirationDateSet, and Wombat.MamdaOptionExpirationStrikes.
Public Member Functions
TreeMap ()
TreeMap (Comparator c)
TreeMap (Map m)
TreeMap (SortedMap m)
Comparator comparator ()
SortedMap subMap (object fromKey, object toKey)
SortedMap headMap (object toKey)
SortedMap tailMap (object fromKey)
object firstKey ()
object lastKey ()
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
object Clone ()
Constructor & Destructor Documentation
TreeMap() [1/4]
Wombat.Containers.TreeMap.TreeMap ()
Referenced by Wombat.MamdaOptionExpirationStrikes.trimStrikes().
TreeMap() [2/4]
Wombat.Containers.TreeMap.TreeMap (Comparator c)
TreeMap() [3/4]
Wombat.Containers.TreeMap.TreeMap (Map m)
TreeMap() [4/4]
Wombat.Containers.TreeMap.TreeMap (SortedMap m)
Member Function Documentation
comparator()
Comparator Wombat.Containers.TreeMap.comparator ()
Implements Wombat.Containers.SortedMap.
subMap()
SortedMap Wombat.Containers.TreeMap.subMap (object fromKey, object toKey)
Implements Wombat.Containers.SortedMap.
References Wombat.Containers.SortedMap.subMap().
Referenced by Wombat.MamdaOptionExpirationStrikes.trimStrikes().
headMap()
SortedMap Wombat.Containers.TreeMap.headMap (object toKey)
Implements Wombat.Containers.SortedMap.
References Wombat.Containers.SortedMap.headMap().
Referenced by Wombat.MamdaOptionExpirationDateSet.getExpirationsBefore().
tailMap()
SortedMap Wombat.Containers.TreeMap.tailMap (object fromKey)
Implements Wombat.Containers.SortedMap.
References Wombat.Containers.SortedMap.tailMap().
firstKey()
object Wombat.Containers.TreeMap.firstKey ()
Implements Wombat.Containers.SortedMap.
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
lastKey()
object Wombat.Containers.TreeMap.lastKey ()
Implements Wombat.Containers.SortedMap.
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
size()
int Wombat.Containers.TreeMap.size ()
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
isEmpty()
bool Wombat.Containers.TreeMap.isEmpty ()
Implements Wombat.Containers.Map.
containsKey()
bool Wombat.Containers.TreeMap.containsKey (object key)
Implements Wombat.Containers.Map.
containsValue()
bool Wombat.Containers.TreeMap.containsValue (object value)
Implements Wombat.Containers.Map.
valueOf()
object Wombat.Containers.TreeMap.valueOf (object key)
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionChain.addContract(), and Wombat.MamdaOptionContractSet.getExchangeContract().
put()
object Wombat.Containers.TreeMap.put (object key, object value)
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionChain.addContract(), Wombat.MamdaOptionContractSet.setExchangeContract(), and Wombat.MamdaOptionExpirationDateSet.ToString().
remove()
object Wombat.Containers.TreeMap.remove (object key)
Implements Wombat.Containers.Map.
putAll()
void Wombat.Containers.TreeMap.putAll (Map m)
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionExpirationStrikes.trimStrikes().
clear()
void Wombat.Containers.TreeMap.clear ()
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionExpirationStrikes.trimStrikes().
keySet()
Set Wombat.Containers.TreeMap.keySet ()
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionContractSet.getExchanges(), and Wombat.MamdaOptionExpirationDateSet.getExpirations().
values()
Collection Wombat.Containers.TreeMap.values ()
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionChainView.expirationIterator(), Wombat.MamdaOptionContractSet.getExchangeContracts(), and Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
entrySet()
Set Wombat.Containers.TreeMap.entrySet ()
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionExpirationDateSet.toString().
Clone()
object Wombat.Containers.TreeMap.Clone ()