OpenMAMDA C# API: Wombat.MamdaSubscription Class Reference
Wombat.MamdaSubscription Class Reference
A MamdaSubscription is used to register interest in a particular symbol and source.
Inherits Wombat.MamdaResourceContainer.
Public Member Functions
MamdaSubscription ()
Default constructor.
void create (MamaTransport transport, MamaQueue queue, string source, string symbol, object closure)
Create and activate a subscription.
void setSource (string source)
Set the data source name.
void setSymbol (string symbol)
Set the symbol.
void setTransport (MamaTransport transport)
Set the MAMA transport.
void setQueue (MamaQueue queue)
Set the MAMA queue.
void setType (mamaSubscriptionType type)
Set the subscrption type.
void setServiceLevel (mamaServiceLevel serviceLevel, int serviceLevelOpt)
Set the MAMA service level.
void setRequireInitial (bool require)
Set whether an initial value is required.
void setTimeout (double timeout)
Set the timeout (in seconds) for this subscription.
void setRetries (int retries)
Set the retries for this subscription.
void setClosure (Object closure)
Set the closure.
void addMsgListener (MamdaMsgListener listener)
Add a listener for regular messages.
ArrayList getMsgListeners ()
get a listener for regular messages.
void addStaleListener (MamdaStaleListener listener)
Add a listener for changes in stale status.
void addErrorListener (MamdaErrorListener listener)
Add a listener for error events.
void activate ()
Activate the subscription.
void deactivate ()
Deactivate the subscription.
void requestRecap ()
Force a recap request to be sent for this subscription.
string getSource ()
double getTimout ()
int getRetries ()
string getSymbol ()
MamaQueue getQueue ()
MamaTransport getTransport ()
Object getClosure ()
Get the additional object passed as the closure to the create() method.
MamaSubscription getMamaSubscription ()
Public Member Functions inherited from Wombat.MamdaResourceContainer
void Dispose ()
Destroys the resources
Additional Inherited Members
Protected Member Functions inherited from Wombat.MamdaResourceContainer
MamdaResourceContainer ()
void AddResource (IDisposable resource)
Detailed Description
A MamdaSubscription is used to register interest in a particular symbol and source.
A MamaTransport is required to actually activate the subscription.
Multiple listeners can be added to the MamdaSubscription. In this way, an application can make use of more than one of the specialized value added MAMDA listeners, such as MamdaTradeListener and MamdaQuoteListener.
Constructor & Destructor Documentation
MamdaSubscription()
Wombat.MamdaSubscription.MamdaSubscription ()
Default constructor.
The subscription is not created until either create() or activate() is called.
Member Function Documentation
create()
void Wombat.MamdaSubscription.create (MamaTransport transport, MamaQueue queue, string source, string symbol, object closure)
Create and activate a subscription.
Any properties for the subscription should be set prior to calling this method.
Parameters
transport
queue
source
symbol
closure
References Wombat.MamdaSubscription.activate(), Wombat.MamdaSubscription.setClosure(), Wombat.MamdaSubscription.setQueue(), Wombat.MamdaSubscription.setSource(), Wombat.MamdaSubscription.setSymbol(), and Wombat.MamdaSubscription.setTransport().
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow(), and Wombat.MamdaOrderBookChecker.MamdaOrderBookChecker().
setSource()
void Wombat.MamdaSubscription.setSource (string source)
Set the data source name.
Do this before calling activate().
Parameters
source
Referenced by Wombat.MamdaSubscription.create().
setSymbol()
void Wombat.MamdaSubscription.setSymbol (string symbol)
Set the symbol.
Do this before calling activate().
Parameters
symbol
Referenced by Wombat.MamdaSubscription.create().
setTransport()
void Wombat.MamdaSubscription.setTransport (MamaTransport transport)
Set the MAMA transport.
Do this before calling activate().
Parameters
transport
Referenced by Wombat.MamdaSubscription.create().
setQueue()
void Wombat.MamdaSubscription.setQueue (MamaQueue queue)
Set the MAMA queue.
Do this before calling activate().
Parameters
queue
Referenced by Wombat.MamdaSubscription.create().
setType()
void Wombat.MamdaSubscription.setType (mamaSubscriptionType type)
Set the subscrption type.
Do this before calling activate() Default is mamaSubscriptionType.MAMA_SUBSC_TYPE_NORMAL
Parameters
type
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow(), and Wombat.MamdaOrderBookChecker.MamdaOrderBookChecker().
setServiceLevel()
void Wombat.MamdaSubscription.setServiceLevel (mamaServiceLevel serviceLevel, int serviceLevelOpt)
Set the MAMA service level.
In the future, certain service levels may have an optional argument (e.g., an interval for conflated data). Do this before calling activate(). Default value is MamaServiceLevel.MAMA_SERVICE_LEVEL_REAL_TIME and 0
Parameters
serviceLevel
serviceLevelOpt
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
setRequireInitial()
void Wombat.MamdaSubscription.setRequireInitial (bool require)
Set whether an initial value is required.
Do this before calling activate(). Default is true
Parameters
require
setTimeout()
void Wombat.MamdaSubscription.setTimeout (double timeout)
Set the timeout (in seconds) for this subscription.
Do this before calling activate(). Default is 10 seconds.
Parameters
timeout
setRetries()
void Wombat.MamdaSubscription.setRetries (int retries)
Set the retries for this subscription.
Do this before calling activate(). Default is 10 seconds.
Parameters
timeout
setClosure()
void Wombat.MamdaSubscription.setClosure (Object closure)
Set the closure.
Do this before calling activate().
Parameters
closure
Referenced by Wombat.MamdaSubscription.create().
addMsgListener()
void Wombat.MamdaSubscription.addMsgListener (MamdaMsgListener listener)
Add a listener for regular messages.
Parameters
listener
Referenced by Wombat.MamdaOrderBookChecker.getFailureCount(), and Wombat.MamdaOrderBookChecker.MamdaOrderBookChecker().
getMsgListeners()
ArrayList Wombat.MamdaSubscription.getMsgListeners ()
get a listener for regular messages.
Parameters
listener
addStaleListener()
void Wombat.MamdaSubscription.addStaleListener (MamdaStaleListener listener)
Add a listener for changes in stale status.
Parameters
listener
addErrorListener()
void Wombat.MamdaSubscription.addErrorListener (MamdaErrorListener listener)
Add a listener for error events.
Parameters
listener
activate()
void Wombat.MamdaSubscription.activate ()
Activate the subscription.
Until this method is invoked, no updates will be received.
Referenced by Wombat.MamdaSubscription.create().
deactivate()
void Wombat.MamdaSubscription.deactivate ()
Deactivate the subscription.
No more updates will be received for this subscription (unless activate() is invoked again).
This function must be called from the same thread dispatching on the associated event queue unless both the default queue and dispatch queue are not actively dispatching.
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
requestRecap()
void Wombat.MamdaSubscription.requestRecap ()
Force a recap request to be sent for this subscription.
Note: there is still a possibility that the feed handler will reject such recap requests (based on configurable feature(s) of a feed handler).
getSource()
string Wombat.MamdaSubscription.getSource ()
Returns
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
getTimout()
double Wombat.MamdaSubscription.getTimout ()
Returns
getRetries()
int Wombat.MamdaSubscription.getRetries ()
Returns
getSymbol()
string Wombat.MamdaSubscription.getSymbol ()
Returns
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow(), and Wombat.MamdaOrderBookListener.onMsg().
getQueue()
MamaQueue Wombat.MamdaSubscription.getQueue ()
Returns
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
getTransport()
MamaTransport Wombat.MamdaSubscription.getTransport ()
Returns
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
getClosure()
Object Wombat.MamdaSubscription.getClosure ()
Get the additional object passed as the closure to the create() method.
Returns
getMamaSubscription()
MamaSubscription Wombat.MamdaSubscription.getMamaSubscription ()
References Wombat.MamdaErrorListener.onError(), Wombat.MamdaMsgListener.onMsg(), Wombat.MamdaStaleListener.onStale(), and Wombat.MamdaErrorCodes.stringForMamdaError().