OpenMAMDA C# API: Wombat.MamdaOptionContractSet Class Reference
Wombat.MamdaOptionContractSet Class Reference
A class that represents a set of option contracts at a given strike price.
Public Member Functions
MamdaOptionContractSet ()
void setBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer.
void setWombatBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer, as calculated by Wombat.
void setExchangeContract (string exchange, MamdaOptionContract contract)
Set the contract for the particular exchange.
MamdaOptionContract getBboContract ()
Return the contract for the best bid and offer.
MamdaOptionContract getWombatBboContract ()
Return the contract for the best bid and offer, as calculated by Wombat.
MamdaOptionContract getExchangeContract (string exchange)
Return the contract for the particular exchange.
Collection getExchangeContracts ()
Return the set of individual regional exchange option contracts.
Set getExchanges ()
Return the set of individual regional exchange identifiers The type of object in the set is a instance of String.
Detailed Description
A class that represents a set of option contracts at a given strike price.
Constructor & Destructor Documentation
MamdaOptionContractSet()
Wombat.MamdaOptionContractSet.MamdaOptionContractSet ()
Member Function Documentation
setBboContract()
void Wombat.MamdaOptionContractSet.setBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer.
Parameters
contract
Referenced by Wombat.MamdaOptionChain.addContract().
setWombatBboContract()
void Wombat.MamdaOptionContractSet.setWombatBboContract (MamdaOptionContract contract)
Set the contract for the best bid and offer, as calculated by Wombat.
Parameters
contract
Referenced by Wombat.MamdaOptionChain.addContract().
setExchangeContract()
void Wombat.MamdaOptionContractSet.setExchangeContract (string exchange, MamdaOptionContract contract)
Set the contract for the particular exchange.
Parameters
exchange
contract
References Wombat.Containers.TreeMap.put().
Referenced by Wombat.MamdaOptionChain.addContract().
getBboContract()
MamdaOptionContract Wombat.MamdaOptionContractSet.getBboContract ()
Return the contract for the best bid and offer.
Returns
getWombatBboContract()
MamdaOptionContract Wombat.MamdaOptionContractSet.getWombatBboContract ()
Return the contract for the best bid and offer, as calculated by Wombat.
Returns
getExchangeContract()
MamdaOptionContract Wombat.MamdaOptionContractSet.getExchangeContract (string exchange)
Return the contract for the particular exchange.
Parameters
exchange
Returns
References Wombat.Containers.TreeMap.valueOf().
getExchangeContracts()
Collection Wombat.MamdaOptionContractSet.getExchangeContracts ()
Return the set of individual regional exchange option contracts.
The type of object in the set is a instance of MamdaOptionContract.
Returns
References Wombat.Containers.TreeMap.values().
getExchanges()
Set Wombat.MamdaOptionContractSet.getExchanges ()
Return the set of individual regional exchange identifiers The type of object in the set is a instance of String.
Returns
References Wombat.Containers.TreeMap.keySet().