OpenMAMDA C# API: Wombat.MamdaOrderBook Class Reference
Wombat.MamdaOrderBook Class Reference
MamdaOrderBook is a class that provides order book functionality, including iterators over price levels and entries within price levels.
Public Member Functions
MamdaOrderBook ()
Construct a new order book object.
void clear ()
Clear all levels from the order book.
void setSymbol (string symbol)
String getSymbol ()
void setBookTime (DateTime time)
DateTime getBookTime ()
void addLevel (MamdaOrderBookPriceLevel level)
Add a price level to the order book.
void updateLevel (MamdaOrderBookPriceLevel level)
Update an existing level in the order book.
void deleteLevel (MamdaOrderBookPriceLevel level)
Delete an existing price level from the book.
void apply (MamdaOrderBook deltaBook)
Apply a delta to this (presumably) full book.
void copy (MamdaOrderBook book)
Make a shallow copy of a book.
void deepCopy (MamdaOrderBook book)
Make a deep copy of a book.
void setAsDeltaDeleted (MamdaOrderBook bookToDelete)
Set this order book to be a delta that would, when applied, delete all of the fields in the bookToDelete.
void setAsDeltaDifference (MamdaOrderBook lhs, MamdaOrderBook rhs)
Set this order book to be a delta that would, when applied, be the difference between to other books.
long getTotalNumLevels ()
Get the total number of price levels (both sides of order book).
void assertEqual (MamdaOrderBook rhs)
Order book equality verification.
IEnumerable getBidLevels ()
Allows an application to iterate over all the bid side price levels in the order book.
IEnumerable getAskLevels ()
Allows an application to iterate over all the ask side price levels in the order book.
void setIsConsistent (bool isConsistent)
Set whether the order book is in a consistent or an an inconsistent state.
bool getIsConsistent ()
Get whether the order book is in a consistent or an an inconsistent state.
void dump ()
Dump the order book to standard output.
void dump (Stream stream)
Dumps the order book to the specified stream
void dump (TextWriter writer)
Dumps the order book using the specified TextWriter instance
Static Public Member Functions
static void setStrictChecking (bool strict)
Enforce strict checking of order book modifications (at the expense of some performance).
Detailed Description
MamdaOrderBook is a class that provides order book functionality, including iterators over price levels and entries within price levels.
Constructor & Destructor Documentation
MamdaOrderBook()
Wombat.MamdaOrderBook.MamdaOrderBook ()
Construct a new order book object.
Contains no price levels upon construction.
Member Function Documentation
clear()
void Wombat.MamdaOrderBook.clear ()
Clear all levels from the order book.
Clears both the bid and ask side levels from the order book.
Referenced by Wombat.MamdaOrderBook.copy(), Wombat.MamdaOrderBook.deepCopy(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBook.setAsDeltaDifference().
setSymbol()
void Wombat.MamdaOrderBook.setSymbol (string symbol)
Parameters
symbol The order book subscription symbol.
Referenced by Wombat.MamdaOrderBookListener.getBookSnapshot(), Wombat.MamdaOrderBookListener.getDeepBookSnapshot(), and Wombat.MamdaOrderBookListener.onMsg().
getSymbol()
String Wombat.MamdaOrderBook.getSymbol ()
Returns
The order book subscription symbol.
Referenced by Wombat.MamdaOrderBookListener.getBookSnapshot(), and Wombat.MamdaOrderBookListener.getDeepBookSnapshot().
setBookTime()
void Wombat.MamdaOrderBook.setBookTime (DateTime time)
Parameters
symbol The order book subscription symbol.
Referenced by Wombat.MamdaOrderBookListener.onMsg().
getBookTime()
DateTime Wombat.MamdaOrderBook.getBookTime ()
Returns
The order book subscription symbol.
Referenced by Wombat.MamdaOrderBookListener.onMsg().
addLevel()
void Wombat.MamdaOrderBook.addLevel (MamdaOrderBookPriceLevel level)
Add a price level to the order book.
Parameters
level The price level to add to the book.
References Wombat.MamdaOrderBookPriceLevel.getSide().
Referenced by Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBook.setStrictChecking().
updateLevel()
void Wombat.MamdaOrderBook.updateLevel (MamdaOrderBookPriceLevel level)
Update an existing level in the order book.
Parameters
level The price level to update.
References Wombat.MamdaOrderBookPriceLevel.getSide().
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
deleteLevel()
void Wombat.MamdaOrderBook.deleteLevel (MamdaOrderBookPriceLevel level)
Delete an existing price level from the book.
Parameters
level The price level in the book to delete.
References Wombat.MamdaOrderBookPriceLevel.getSide().
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
apply()
void Wombat.MamdaOrderBook.apply (MamdaOrderBook deltaBook)
Apply a delta to this (presumably) full book.
Parameters
deltaBook The delta to apply to the order book.
References Wombat.MamdaOrderBook.getAskLevels(), and Wombat.MamdaOrderBook.getBidLevels().
Referenced by Wombat.MamdaOrderBook.copy(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBook.setStrictChecking().
copy()
void Wombat.MamdaOrderBook.copy (MamdaOrderBook book)
Make a shallow copy of a book.
Parameters
book The order book to copy.
References Wombat.MamdaOrderBook.apply(), and Wombat.MamdaOrderBook.clear().
Referenced by Wombat.MamdaOrderBookListener.getBookSnapshot(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBook.setAsDeltaDeleted().
deepCopy()
void Wombat.MamdaOrderBook.deepCopy (MamdaOrderBook book)
Make a deep copy of a book.
Parameters
book The order book to copy.
References Wombat.MamdaOrderBook.clear(), Wombat.MamdaOrderBook.getAskLevels(), and Wombat.MamdaOrderBook.getBidLevels().
Referenced by Wombat.MamdaOrderBookListener.getDeepBookSnapshot(), and Wombat.MamdaOrderBook.setStrictChecking().
setAsDeltaDeleted()
void Wombat.MamdaOrderBook.setAsDeltaDeleted (MamdaOrderBook bookToDelete)
Set this order book to be a delta that would, when applied, delete all of the fields in the bookToDelete.
Parameters
bookToDelete The book to be deleted.
References Wombat.MamdaOrderBook.copy().
Referenced by Wombat.MamdaOrderBookListener.onMsg().
setAsDeltaDifference()
void Wombat.MamdaOrderBook.setAsDeltaDifference (MamdaOrderBook lhs, MamdaOrderBook rhs)
Set this order book to be a delta that would, when applied, be the difference between to other books.
Parameters
lhs An order book.
rhs An order book.
References Wombat.MamdaOrderBook.clear().
Referenced by Wombat.MamdaOrderBookListener.onMsg().
getTotalNumLevels()
long Wombat.MamdaOrderBook.getTotalNumLevels ()
Get the total number of price levels (both sides of order book).
Returns
The total number of level in the order book.
assertEqual()
void Wombat.MamdaOrderBook.assertEqual (MamdaOrderBook rhs)
Order book equality verification.
A MamdaOrderBookException is thrown if the books are not equal, along with the reason for the inequality.
Parameters
rhs The order book to compare to the current book.
Exceptions
MamdaOrderBookException Throws MamdaOrderBookException if the two books are not equal.
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow(), and Wombat.MamdaOrderBook.setStrictChecking().
getBidLevels()
IEnumerable Wombat.MamdaOrderBook.getBidLevels ()
Allows an application to iterate over all the bid side price levels in the order book.
Returns
IEnumerable for the bid side price levels in the order book - the elements are of type MamdaOrderBookPriceLevel
Referenced by Wombat.MamdaOrderBook.apply(), and Wombat.MamdaOrderBook.deepCopy().
getAskLevels()
IEnumerable Wombat.MamdaOrderBook.getAskLevels ()
Allows an application to iterate over all the ask side price levels in the order book.
Returns
IEnumerable for the ask side price levels in the order book - the elements are of type MamdaOrderBookPriceLevel
Referenced by Wombat.MamdaOrderBook.apply(), and Wombat.MamdaOrderBook.deepCopy().
setIsConsistent()
void Wombat.MamdaOrderBook.setIsConsistent (bool isConsistent)
Set whether the order book is in a consistent or an an inconsistent state.
Parameters
isConsistent Whether the book is consistent.
Referenced by Wombat.MamdaOrderBookListener.getBookSnapshot(), Wombat.MamdaOrderBookListener.getDeepBookSnapshot(), and Wombat.MamdaOrderBookListener.onMsg().
getIsConsistent()
bool Wombat.MamdaOrderBook.getIsConsistent ()
Get whether the order book is in a consistent or an an inconsistent state.
The orderbook will be marked as inconsistent if a gap is detected by the Listener. The book will be marked consistent again once a full recap for the book has been obtained from the feed.
Returns
Whether the book is in a consistent state.
Referenced by Wombat.MamdaOrderBookListener.getBookSnapshot(), Wombat.MamdaOrderBookListener.getDeepBookSnapshot(), and Wombat.MamdaOrderBookListener.onMsg().
dump() [1/3]
void Wombat.MamdaOrderBook.dump ()
Dump the order book to standard output.
Referenced by Wombat.MamdaOrderBook.dump(), and Wombat.MamdaOrderBook.setStrictChecking().
dump() [2/3]
void Wombat.MamdaOrderBook.dump (Stream stream)
Dumps the order book to the specified stream
Parameters
stream The stream on which the order book will be dumped
References Wombat.MamdaOrderBook.dump().
dump() [3/3]
void Wombat.MamdaOrderBook.dump (TextWriter writer)
Dumps the order book using the specified TextWriter instance
Parameters
writer
References Wombat.MamdaOrderBook.dump().
setStrictChecking()
static void Wombat.MamdaOrderBook.setStrictChecking (bool strict) static
Enforce strict checking of order book modifications (at the expense of some performance).
This setting is passed on to the MamdaOrderBookPriceLevel and MamdaOrderBookEntry classes.
Parameters
strict
References Wombat.MamdaOrderBook.addLevel(), Wombat.MamdaOrderBook.apply(), Wombat.MamdaOrderBook.assertEqual(), Wombat.MamdaOrderBookPriceLevel.assertEqual(), Wombat.MamdaOrderBookPriceLevel.copy(), Wombat.MamdaOrderBook.deepCopy(), Wombat.MamdaOrderBook.deleteLevel(), Wombat.MamdaOrderBook.dump(), Wombat.MamdaOrderBookEntry.getAction(), Wombat.MamdaOrderBookPriceLevel.getAction(), Wombat.MamdaOrderBookEntry.getId(), Wombat.MamdaOrderBookPriceLevel.getNumEntries(), Wombat.MamdaOrderBookPriceLevel.getPrice(), Wombat.MamdaOrderBookPriceLevel.getSide(), Wombat.MamdaOrderBookEntry.getSize(), Wombat.MamdaOrderBookPriceLevel.getSize(), Wombat.MamdaOrderBookEntry.getTime(), Wombat.MamdaOrderBookPriceLevel.getTime(), Wombat.MamdaOrderBookEntry.hasTime(), Wombat.MamdaOrderBookPriceLevel.hasTime(), Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookPriceLevel.setAsDifference(), Wombat.MamdaOrderBookEntry.setStrictChecking(), Wombat.MamdaOrderBookPriceLevel.setStrictChecking(), and Wombat.MamdaOrderBook.updateLevel().