OpenMAMDA C# API: Wombat.MamdaOrderBookListener Class Reference
Wombat.MamdaOrderBookListener Class Reference
MamdaOrderBookListener is a class that specializes in handling order book updates.
Inherits Wombat.MamdaMsgListener, Wombat.MamdaOrderBookRecap, Wombat.MamdaOrderBookDelta, and Wombat.MamdaOrderBookGap.
Public Member Functions
MamdaOrderBookListener ()
Create an order book listener using internally created data structures for the full and delta order books.
MamdaOrderBookListener (MamdaOrderBook fullBook, MamdaOrderBook deltaBook)
Create an order book listener using user-provided data structures for the full and delta order books.
void addHandler (MamdaOrderBookHandler handler)
Add a specialized order book handler.
void addIgnoreEntryId (string id)
(Future) Add an entry ID to ignore.
void removeIgnoreEntryId (string id)
(Future) Remove an entry ID to ignore.
void clear ()
Clear all cached data fields.
DateTime getSrcTime ()
DateTime getActivityTime ()
long getEventSeqNum ()
DateTime getEventTime ()
MamdaFieldState getSymbolFieldState ()
MamdaFieldState getPartIdFieldState ()
MamdaFieldState getSrcTimeFieldState ()
Returns the field state.
MamdaFieldState getActivityTimeFieldState ()
Returns the field state.
MamdaFieldState getLineTimeFieldState ()
MamdaFieldState getSendTimeFieldState ()
MamdaFieldState getEventSeqNumFieldState ()
Returns the field state.
MamdaFieldState getEventTimeFieldState ()
Returns the field state.
MamdaOrderBook getFullOrderBook ()
MamdaOrderBook getDeltaOrderBook ()
long getBeginGapSeqNum ()
long getEndGapSeqNum ()
long getSeqNum ()
MamdaOrderBook getBookSnapshot ()
Returns a shallow copy of the underlying order book.
MamdaOrderBook getDeepBookSnapshot ()
Returns a deep copy of the underlying order book.
void setUpdateInconsistentBook (bool update)
Whether to handle or ignore updates sent for an inconsistent book.
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Detailed Description
MamdaOrderBookListener is a class that specializes in handling order book updates.
Developers provide their own implementation of the MamdaOrderBookHandler interface and will be delivered notifications for order book recaps and deltas. Notifications for order book deltas include the delta itself as well as the full order book with deltas applied. An obvious application for this MAMDA class is any kind of program trading application that looks at depth of book.
Note: The MamdaOrderBookListener class caches the order book. Among other reasons, caching of these fields makes it possible to provide complete trade-related callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaOrderBookListener() [1/2]
Wombat.MamdaOrderBookListener.MamdaOrderBookListener ()
Create an order book listener using internally created data structures for the full and delta order books.
MamdaOrderBookListener() [2/2]
Wombat.MamdaOrderBookListener.MamdaOrderBookListener (MamdaOrderBook fullBook, MamdaOrderBook deltaBook)
Create an order book listener using user-provided data structures for the full and delta order books.
It is an error for the deltaBook to be NULL. If the fullBook is NULL, then there will be no cached order book (and therefore nothing to apply the delta order books to); this may be useful in some circumstances.
Parameters
fullBook
deltaBook
Member Function Documentation
addHandler()
void Wombat.MamdaOrderBookListener.addHandler (MamdaOrderBookHandler handler)
Add a specialized order book handler.
Currently, only one handler can (and must) be registered.
Parameters
handler
Referenced by Wombat.MamdaOrderBookChecker.getFailureCount().
addIgnoreEntryId()
void Wombat.MamdaOrderBookListener.addIgnoreEntryId (string id)
(Future) Add an entry ID to ignore.
This only makes sense when the entry type is participant ID (as opposed to order ID). All order book updates for this entry ID will be ignored.
Parameters
id
removeIgnoreEntryId()
void Wombat.MamdaOrderBookListener.removeIgnoreEntryId (string id)
(Future) Remove an entry ID to ignore.
See addIgnoreEntryId.
Parameters
id
clear()
void Wombat.MamdaOrderBookListener.clear ()
Clear all cached data fields.
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
getSrcTime()
DateTime Wombat.MamdaOrderBookListener.getSrcTime ()
Returns
Implements Wombat.MamdaBasicEvent.
getActivityTime()
DateTime Wombat.MamdaOrderBookListener.getActivityTime ()
Returns
Implements Wombat.MamdaBasicEvent.
getEventSeqNum()
long Wombat.MamdaOrderBookListener.getEventSeqNum ()
Returns
Implements Wombat.MamdaBasicEvent.
getEventTime()
DateTime Wombat.MamdaOrderBookListener.getEventTime ()
Returns
Implements Wombat.MamdaBasicEvent.
getSymbolFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getSymbolFieldState ()
getPartIdFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getPartIdFieldState ()
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getSrcTimeFieldState ()
Returns the field state.
Returns
Source time Field State
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getActivityTimeFieldState ()
Returns the field state.
Returns
Activity time Field State
Implements Wombat.MamdaBasicEvent.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getLineTimeFieldState ()
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getSendTimeFieldState ()
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getEventSeqNumFieldState ()
Returns the field state.
Returns
Source sequence number Field State
Implements Wombat.MamdaBasicEvent.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaOrderBookListener.getEventTimeFieldState ()
Returns the field state.
Returns
Event Time Field State
Implements Wombat.MamdaBasicEvent.
getFullOrderBook()
MamdaOrderBook Wombat.MamdaOrderBookListener.getFullOrderBook ()
Returns
Implements Wombat.MamdaOrderBookRecap.
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
getDeltaOrderBook()
MamdaOrderBook Wombat.MamdaOrderBookListener.getDeltaOrderBook ()
Returns
Implements Wombat.MamdaOrderBookDelta.
getBeginGapSeqNum()
long Wombat.MamdaOrderBookListener.getBeginGapSeqNum ()
Returns
Implements Wombat.MamdaOrderBookGap.
getEndGapSeqNum()
long Wombat.MamdaOrderBookListener.getEndGapSeqNum ()
Returns
Implements Wombat.MamdaOrderBookGap.
getSeqNum()
long Wombat.MamdaOrderBookListener.getSeqNum ()
Returns
Referenced by Wombat.MamdaOrderBookChecker.checkSnapShotNow().
getBookSnapshot()
MamdaOrderBook Wombat.MamdaOrderBookListener.getBookSnapshot ()
Returns a shallow copy of the underlying order book.
As such this method should not be called from a separate thread. The recommended use of this method is to use a timer on the same queue as data for this book is being dispatched and grab the snapshot at regular intervals.
Returns
A snapshot of the current Order Book
References Wombat.MamdaOrderBook.copy(), Wombat.MamdaOrderBook.getIsConsistent(), Wombat.MamdaOrderBook.getSymbol(), Wombat.MamdaOrderBook.setIsConsistent(), and Wombat.MamdaOrderBook.setSymbol().
getDeepBookSnapshot()
MamdaOrderBook Wombat.MamdaOrderBookListener.getDeepBookSnapshot ()
Returns a deep copy of the underlying order book.
Returns
A deep snapshot of the current Order Book
References Wombat.MamdaOrderBook.deepCopy(), Wombat.MamdaOrderBook.getIsConsistent(), Wombat.MamdaOrderBook.getSymbol(), Wombat.MamdaOrderBook.setIsConsistent(), and Wombat.MamdaOrderBook.setSymbol().
setUpdateInconsistentBook()
void Wombat.MamdaOrderBookListener.setUpdateInconsistentBook (bool update)
Whether to handle or ignore updates sent for an inconsistent book.
A book may be in an inconsistent state if there has been a gap on the sequence of update (delta) messages. Default is to not update (and wait for a recap).
Parameters
update
onMsg()
void Wombat.MamdaOrderBookListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Parameters
subscription
msg
msgType
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaOrderBookFields.ACTIVITY_TIME, Wombat.MamdaOrderBookPriceLevel.addEntry(), Wombat.MamdaOrderBook.addLevel(), Wombat.MamdaOrderBook.apply(), Wombat.MamdaOrderBookFields.BOOK_TIME, Wombat.MamdaOrderBook.clear(), Wombat.MamdaOrderBook.copy(), Wombat.MamdaOrderBookFields.ENTRY_ACTION, Wombat.MamdaOrderBookFields.ENTRY_ID, Wombat.MamdaOrderBookFields.ENTRY_SIZE, Wombat.MamdaOrderBookFields.ENTRY_TIME, Wombat.MamdaOrderBook.getBookTime(), Wombat.MamdaOrderBookFields.getHasVectorFields(), Wombat.MamdaOrderBook.getIsConsistent(), Wombat.MamdaSubscription.getSymbol(), Wombat.MamdaOrderBookPriceLevel.getTime(), Wombat.MamdaOrderBookFields.isSet(), Wombat.MamdaOrderBookFields.NUM_LEVELS, Wombat.MamdaOrderBookHandler.onBookClear(), Wombat.MamdaOrderBookHandler.onBookDelta(), Wombat.MamdaOrderBookHandler.onBookGap(), Wombat.MamdaOrderBookHandler.onBookRecap(), Wombat.MamdaOrderBookFields.PL_ACTION, Wombat.MamdaOrderBookFields.PL_ENTRIES, Wombat.MamdaOrderBookFields.PL_ENTRY, Wombat.MamdaOrderBookFields.PL_NUM_ATTACH, Wombat.MamdaOrderBookFields.PL_NUM_ENTRIES, Wombat.MamdaOrderBookFields.PL_PRICE, Wombat.MamdaOrderBookFields.PL_SIDE, Wombat.MamdaOrderBookFields.PL_SIZE, Wombat.MamdaOrderBookFields.PL_SIZE_CHANGE, Wombat.MamdaOrderBookFields.PL_TIME, Wombat.MamdaOrderBookFields.PRICE_LEVEL, Wombat.MamdaOrderBookFields.PRICE_LEVELS, Wombat.MamdaOrderBookFields.SEQNUM, Wombat.MamdaOrderBookEntry.setAction(), Wombat.MamdaOrderBookPriceLevel.setAction(), Wombat.MamdaOrderBook.setAsDeltaDeleted(), Wombat.MamdaOrderBook.setAsDeltaDifference(), Wombat.MamdaOrderBook.setBookTime(), Wombat.MamdaOrderBookEntry.setId(), Wombat.MamdaOrderBook.setIsConsistent(), Wombat.MamdaOrderBookPriceLevel.setNumEntries(), Wombat.MamdaOrderBookPriceLevel.setPrice(), Wombat.MamdaOrderBookPriceLevel.setSide(), Wombat.MamdaOrderBookEntry.setSize(), Wombat.MamdaOrderBookPriceLevel.setSize(), Wombat.MamdaOrderBookPriceLevel.setSizeChange(), Wombat.MamdaOrderBook.setSymbol(), Wombat.MamdaOrderBookEntry.setTime(), Wombat.MamdaOrderBookPriceLevel.setTime(), and Wombat.MamdaOrderBookFields.SRC_TIME.