OpenMAMDA C# API: Wombat.MamdaFundamentalListener Class Reference
Wombat.MamdaFundamentalListener Class Reference
MamdaFundamentalListener is a class that specializes in handling fundamental equity pricing/analysis attributes, indicators and ratios.
Inherits Wombat.MamdaMsgListener, and Wombat.MamdaFundamentals.
Public Member Functions
MamdaFundamentalListener ()
Create a specialized fundamental field listener.
void addHandler (MamdaFundamentalHandler handler)
Add a specialized fundamentals handler.
DateTime getSrcTime ()
DateTime getActivityTime ()
string getCorporateActionType ()
Corporate Action Type.
double getDividendPrice ()
Dividend price.
string getDividendFrequency ()
Frequency of the dividend payments.
string getDividendExDate ()
The date on or after which a security is traded without a previously declared dividend or distribution.
string getDividendPayDate ()
Date on which corporate action distribution will be paid or effective.
string getDividendRecordDate ()
This is the date on which all shareholders are considered a "holder of record" and ensured the right of a dividend or distribution.
string getDividendCurrency ()
Currency of dividend.
long getSharesOut ()
Shares outstanding.
long getSharesFloat ()
The number of shares of a security that are outstanding and available for trading by the public.
long getSharesAuthorized ()
Authorized shares.
double getEarningsPerShare ()
Earnings per share, including common stock, preferred stock, unexercised stock options, unexercised warrants, and some convertible debt.
double getVolatility ()
The relative rate at which the price of a security moves up and down.
double getPriceEarningsRatio ()
The most common measure of how expensive a stock is.
double getYield ()
Yield, for cash instruments where prices are published
string getMarketSegmentNative ()
Feed-specific market segment code in native feed format.
string getMarketSectorNative ()
Feed-specific market sector code in native feed format.
string getMarketSegment ()
Market subgroup.
string getMarketSector ()
A distinct subset of a market, society, industry, or economy, whose components share similar characteristics
double getHistoricalVolatility ()
Volatility estimated from historical data
double getRiskFreeRate ()
Theoretical interest rate at which an investment may earn interest without incurring any risk
MamdaFieldState getSrcTimeFieldState ()
MamdaFieldState getActivityTimeFieldState ()
MamdaFieldState getCorporateActionTypeFieldState ()
Field State
MamdaFieldState getDividendPriceFieldState ()
Field State
MamdaFieldState getDividendFrequencyFieldState ()
Field State
MamdaFieldState getDividendExDateFieldState ()
Field State
MamdaFieldState getDividendPayDateFieldState ()
Field State
MamdaFieldState getDividendRecordDateFieldState ()
Field State
MamdaFieldState getDividendCurrencyFieldState ()
Field State
MamdaFieldState getSharesOutFieldState ()
Field State
MamdaFieldState getSharesFloatFieldState ()
Field State
MamdaFieldState getSharesAuthorizedFieldState ()
Field State
MamdaFieldState getEarningsPerShareFieldState ()
Field State
MamdaFieldState getVolatilityFieldState ()
Field State
MamdaFieldState getPriceEarningsRatioFieldState ()
Field State
MamdaFieldState getYieldFieldState ()
Field State
MamdaFieldState getMarketSegmentNativeFieldState ()
Field State
MamdaFieldState getMarketSectorNativeFieldState ()
Field State
MamdaFieldState getMarketSegmentFieldState ()
Field State
MamdaFieldState getMarketSectorFieldState ()
Field State
MamdaFieldState getHistoricalVolatilityFieldState ()
Field State
MamdaFieldState getRiskFreeRateFieldState ()
Field State
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
string getFieldAsString (MamaMsgField field)
Detailed Description
MamdaFundamentalListener is a class that specializes in handling fundamental equity pricing/analysis attributes, indicators and ratios.
Developers provide their own implementation of the MamdaFundamentalHandler interface and will be delivered notifications for updates in the fundamental data. An obvious application for this MAMDA class is any kind of pricing analysis application.
Note: The MamdaFundamentalListener class caches equity pricing/analysis attributes, indicators and ratios. Among other reasons, caching of these fields makes it possible to provide complete fundamental callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaFundamentalListener()
Wombat.MamdaFundamentalListener.MamdaFundamentalListener ()
Create a specialized fundamental field listener.
Member Function Documentation
addHandler()
void Wombat.MamdaFundamentalListener.addHandler (MamdaFundamentalHandler handler)
Add a specialized fundamentals handler.
Parameters
handler
Referenced by Wombat.MamdaOptionContract.addFundamentalHandler().
getSrcTime()
DateTime Wombat.MamdaFundamentalListener.getSrcTime ()
getActivityTime()
DateTime Wombat.MamdaFundamentalListener.getActivityTime ()
getCorporateActionType()
string Wombat.MamdaFundamentalListener.getCorporateActionType ()
Corporate Action Type.
Returns
Implements Wombat.MamdaFundamentals.
getDividendPrice()
double Wombat.MamdaFundamentalListener.getDividendPrice ()
Dividend price.
Returns
Implements Wombat.MamdaFundamentals.
getDividendFrequency()
string Wombat.MamdaFundamentalListener.getDividendFrequency ()
Frequency of the dividend payments.
: No dividend payments are made.
1M : Monthly
3M : Quarterly
6M : Semi-Annually
1Y : Annually
SP : Payment frequency is special.
NA : Irregular payment frequency.
ER : Invalid dividend frequency period.
Returns
Implements Wombat.MamdaFundamentals.
getDividendExDate()
string Wombat.MamdaFundamentalListener.getDividendExDate ()
The date on or after which a security is traded without a previously declared dividend or distribution.
Returns
Implements Wombat.MamdaFundamentals.
getDividendPayDate()
string Wombat.MamdaFundamentalListener.getDividendPayDate ()
Date on which corporate action distribution will be paid or effective.
Returns
Implements Wombat.MamdaFundamentals.
getDividendRecordDate()
string Wombat.MamdaFundamentalListener.getDividendRecordDate ()
This is the date on which all shareholders are considered a "holder of record" and ensured the right of a dividend or distribution.
Returns
Implements Wombat.MamdaFundamentals.
getDividendCurrency()
string Wombat.MamdaFundamentalListener.getDividendCurrency ()
Currency of dividend.
Returns
Implements Wombat.MamdaFundamentals.
getSharesOut()
long Wombat.MamdaFundamentalListener.getSharesOut ()
Shares outstanding.
The number of authorized shares in a company that are held by investors, including employees and executives of that company. (Un-issued shares and treasury shares are not included in this figure).
Returns
Implements Wombat.MamdaFundamentals.
getSharesFloat()
long Wombat.MamdaFundamentalListener.getSharesFloat ()
The number of shares of a security that are outstanding and available for trading by the public.
Returns
Implements Wombat.MamdaFundamentals.
getSharesAuthorized()
long Wombat.MamdaFundamentalListener.getSharesAuthorized ()
Authorized shares.
The number of shares that a corporation is permitted to issue.
Returns
Implements Wombat.MamdaFundamentals.
getEarningsPerShare()
double Wombat.MamdaFundamentalListener.getEarningsPerShare ()
Earnings per share, including common stock, preferred stock, unexercised stock options, unexercised warrants, and some convertible debt.
In companies with a large amount of convertibles, warrants and stock options, diluted earnings per share are usually a more accurate measure of the company's real earning power than earnings per share.
Returns
Implements Wombat.MamdaFundamentals.
getVolatility()
double Wombat.MamdaFundamentalListener.getVolatility ()
The relative rate at which the price of a security moves up and down.
Returns
Implements Wombat.MamdaFundamentals.
getPriceEarningsRatio()
double Wombat.MamdaFundamentalListener.getPriceEarningsRatio ()
The most common measure of how expensive a stock is.
The P/E ratio is equal to a stock's market capitalization divided by its after-tax earnings over a 12-month period, usually the trailing period but occasionally the current or forward period.
Returns
Implements Wombat.MamdaFundamentals.
getYield()
double Wombat.MamdaFundamentalListener.getYield ()
Yield, for cash instruments where prices are published
Returns
Implements Wombat.MamdaFundamentals.
getMarketSegmentNative()
string Wombat.MamdaFundamentalListener.getMarketSegmentNative ()
Feed-specific market segment code in native feed format.
Returns
Implements Wombat.MamdaFundamentals.
getMarketSectorNative()
string Wombat.MamdaFundamentalListener.getMarketSectorNative ()
Feed-specific market sector code in native feed format.
Returns
Implements Wombat.MamdaFundamentals.
getMarketSegment()
string Wombat.MamdaFundamentalListener.getMarketSegment ()
Market subgroup.
Returns
Implements Wombat.MamdaFundamentals.
getMarketSector()
string Wombat.MamdaFundamentalListener.getMarketSector ()
A distinct subset of a market, society, industry, or economy, whose components share similar characteristics
Returns
Implements Wombat.MamdaFundamentals.
getHistoricalVolatility()
double Wombat.MamdaFundamentalListener.getHistoricalVolatility ()
Volatility estimated from historical data
Returns
Implements Wombat.MamdaFundamentals.
getRiskFreeRate()
double Wombat.MamdaFundamentalListener.getRiskFreeRate ()
Theoretical interest rate at which an investment may earn interest without incurring any risk
Returns
Implements Wombat.MamdaFundamentals.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getSrcTimeFieldState ()
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getActivityTimeFieldState ()
getCorporateActionTypeFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getCorporateActionTypeFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getDividendPriceFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getDividendPriceFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getDividendFrequencyFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getDividendFrequencyFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getDividendExDateFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getDividendExDateFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getDividendPayDateFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getDividendPayDateFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getDividendRecordDateFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getDividendRecordDateFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getDividendCurrencyFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getDividendCurrencyFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getSharesOutFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getSharesOutFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getSharesFloatFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getSharesFloatFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getSharesAuthorizedFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getSharesAuthorizedFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getEarningsPerShareFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getEarningsPerShareFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getVolatilityFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getVolatilityFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getPriceEarningsRatioFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getPriceEarningsRatioFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getYieldFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getYieldFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getMarketSegmentNativeFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getMarketSegmentNativeFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getMarketSectorNativeFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getMarketSectorNativeFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getMarketSegmentFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getMarketSegmentFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getMarketSectorFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getMarketSectorFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getHistoricalVolatilityFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getHistoricalVolatilityFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
getRiskFreeRateFieldState()
MamdaFieldState Wombat.MamdaFundamentalListener.getRiskFreeRateFieldState ()
Field State
Returns
Implements Wombat.MamdaFundamentals.
onMsg()
void Wombat.MamdaFundamentalListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Parameters
subscription
msg
msgType
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaFundamentalFields.ACTIVITY_TIME, Wombat.MamdaFundamentalFields.CORP_ACT_TYPE, Wombat.MamdaFundamentalFields.DIVIDEND_CURRENCY, Wombat.MamdaFundamentalFields.DIVIDEND_EX_DATE, Wombat.MamdaFundamentalFields.DIVIDEND_FREQ, Wombat.MamdaFundamentalFields.DIVIDEND_PAY_DATE, Wombat.MamdaFundamentalFields.DIVIDEND_PRICE, Wombat.MamdaFundamentalFields.DIVIDEND_REC_DATE, Wombat.MamdaFundamentalFields.EARN_PER_SHARE, Wombat.MamdaFundamentalListener.getFieldAsString(), Wombat.MamdaFundamentalFields.HIST_VOLATILITY, Wombat.MamdaFundamentalFields.isSet(), Wombat.MamdaFundamentalFields.MRKT_SECT_NATIVE, Wombat.MamdaFundamentalFields.MRKT_SECTOR, Wombat.MamdaFundamentalFields.MRKT_SEGM_NATIVE, Wombat.MamdaFundamentalFields.MRKT_SEGMENT, Wombat.MamdaFundamentalHandler.onFundamentals(), Wombat.MamdaFundamentalFields.PRICE_EARN_RATIO, Wombat.MamdaFundamentalFields.RISK_FREE_RATE, Wombat.MamdaFundamentalFields.SHARES_AUTH, Wombat.MamdaFundamentalFields.SHARES_FLOAT, Wombat.MamdaFundamentalFields.SHARES_OUT, Wombat.MamdaFundamentalFields.SRC_TIME, Wombat.MamdaFundamentalFields.VOLATILITY, and Wombat.MamdaFundamentalFields.YIELD.
getFieldAsString()
string Wombat.MamdaFundamentalListener.getFieldAsString (MamaMsgField field)
Referenced by Wombat.MamdaFundamentalListener.onMsg().