OpenMAMDA C# API: Wombat.MamdaOptionExpirationStrikes Class Reference
Wombat.MamdaOptionExpirationStrikes Class Reference
A class that represents a set of strike prices at a particlar expiration date.
Inherits Wombat.Containers.TreeMap.
Public Member Functions
MamdaOptionExpirationStrikes ()
MamdaOptionExpirationStrikes (MamdaOptionExpirationStrikes copy)
void trimStrikes (SortedSet strikeSet)
Trim the current set of strike prices to the given set.
Public Member Functions inherited from Wombat.Containers.TreeMap
TreeMap ()
TreeMap (Comparator c)
TreeMap (Map m)
TreeMap (SortedMap m)
Comparator comparator ()
SortedMap subMap (object fromKey, object toKey)
SortedMap headMap (object toKey)
SortedMap tailMap (object fromKey)
object firstKey ()
object lastKey ()
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
object Clone ()
Detailed Description
A class that represents a set of strike prices at a particlar expiration date.
Each strike price of which contains a set of option contracts, each of which contains exchange-specific contracts. To access a contract set for a given strike price, use the get method (inherited from TreeMap).
Constructor & Destructor Documentation
MamdaOptionExpirationStrikes() [1/2]
Wombat.MamdaOptionExpirationStrikes.MamdaOptionExpirationStrikes ()
MamdaOptionExpirationStrikes() [2/2]
Wombat.MamdaOptionExpirationStrikes.MamdaOptionExpirationStrikes (MamdaOptionExpirationStrikes copy)
Member Function Documentation
trimStrikes()
void Wombat.MamdaOptionExpirationStrikes.trimStrikes (SortedSet strikeSet)
Trim the current set of strike prices to the given set.
Parameters
strikeSet
References Wombat.Containers.TreeMap.clear(), Wombat.Containers.SortedSet.first(), Wombat.Containers.SortedSet.last(), Wombat.Containers.TreeMap.putAll(), Wombat.Containers.TreeMap.subMap(), and Wombat.Containers.TreeMap.TreeMap().
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().