OpenMAMDA C# API: Wombat.Containers.TreeSet Class Reference
Wombat.Containers.TreeSet Class Reference
Inherits Wombat.Containers.SortedSet, and ICloneable.
Public Member Functions
TreeSet ()
TreeSet (Comparator c)
TreeSet (Collection c)
TreeSet (SortedSet s)
Comparator comparator ()
SortedSet subSet (object from, object to)
SortedSet headSet (object to)
SortedSet tailSet (object from)
object first ()
object last ()
int size ()
bool isEmpty ()
bool contains (object o)
object [] toArray ()
bool add (object o)
bool remove (object o)
bool containsAll (Collection c)
bool addAll (Collection c)
bool removeAll (Collection c)
bool retainAll (Collection c)
void clear ()
Iterator iterator ()
object Clone ()
Creates a deep clone of this TreeSet
Constructor & Destructor Documentation
TreeSet() [1/4]
Wombat.Containers.TreeSet.TreeSet ()
TreeSet() [2/4]
Wombat.Containers.TreeSet.TreeSet (Comparator c)
TreeSet() [3/4]
Wombat.Containers.TreeSet.TreeSet (Collection c)
TreeSet() [4/4]
Wombat.Containers.TreeSet.TreeSet (SortedSet s)
Member Function Documentation
comparator()
Comparator Wombat.Containers.TreeSet.comparator ()
Implements Wombat.Containers.SortedSet.
subSet()
SortedSet Wombat.Containers.TreeSet.subSet (object from, object to)
Implements Wombat.Containers.SortedSet.
Referenced by Wombat.MamdaOptionChain.getStrikesWithinPercent(), and Wombat.MamdaOptionChain.getStrikesWithinRangeSize().
headSet()
SortedSet Wombat.Containers.TreeSet.headSet (object to)
Implements Wombat.Containers.SortedSet.
tailSet()
SortedSet Wombat.Containers.TreeSet.tailSet (object from)
Implements Wombat.Containers.SortedSet.
first()
object Wombat.Containers.TreeSet.first ()
Implements Wombat.Containers.SortedSet.
last()
object Wombat.Containers.TreeSet.last ()
Implements Wombat.Containers.SortedSet.
size()
int Wombat.Containers.TreeSet.size ()
Implements Wombat.Containers.Collection.
isEmpty()
bool Wombat.Containers.TreeSet.isEmpty ()
Implements Wombat.Containers.Collection.
contains()
bool Wombat.Containers.TreeSet.contains (object o)
Implements Wombat.Containers.Collection.
toArray()
object [] Wombat.Containers.TreeSet.toArray ()
Implements Wombat.Containers.Collection.
add()
bool Wombat.Containers.TreeSet.add (object o)
Implements Wombat.Containers.Collection.
Referenced by Wombat.MamdaOptionChain.addContract().
remove()
bool Wombat.Containers.TreeSet.remove (object o)
Implements Wombat.Containers.Collection.
containsAll()
bool Wombat.Containers.TreeSet.containsAll (Collection c)
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
addAll()
bool Wombat.Containers.TreeSet.addAll (Collection c)
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
removeAll()
bool Wombat.Containers.TreeSet.removeAll (Collection c)
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
retainAll()
bool Wombat.Containers.TreeSet.retainAll (Collection c)
Implements Wombat.Containers.Collection.
References Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
clear()
void Wombat.Containers.TreeSet.clear ()
Implements Wombat.Containers.Collection.
iterator()
Iterator Wombat.Containers.TreeSet.iterator ()
Implements Wombat.Containers.Iterable.
Referenced by Wombat.MamdaOptionChain.callIterator(), Wombat.MamdaOptionChain.dump(), Wombat.MamdaOptionChain.getStrikesWithinRangeSize(), and Wombat.MamdaOptionChain.putIterator().
Clone()
object Wombat.Containers.TreeSet.Clone ()
Creates a deep clone of this TreeSet
Returns