OpenMAMDA C# API: Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache Class Reference
Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache Class Reference
Public Attributes
MamaPrice mHighIndicationPrice = new MamaPrice()
MamaPrice mLowIndicationPrice = new MamaPrice()
MamaPrice mIndicationPrice = new MamaPrice()
long mBuyVolume
long mSellVolume
long mMatchVolume
String mSecurityStatusQual
MamaPrice mInsideMatchPrice = new MamaPrice()
MamaPrice mFarClearingPrice = new MamaPrice()
MamaPrice mNearClearingPrice = new MamaPrice()
char mNoClearingPrice
char mPriceVarInd
char mCrossType
DateTime mEventTime = DateTime.MinValue
long mEventSeqNum
DateTime mSrcTime = DateTime.MinValue
DateTime mActTime = DateTime.MinValue
int mMsgType
String mIssueSymbol = null
String mPartId = null
String mSymbol = null
int mSeqNum
String mSecurityStatusOrig = null
DateTime mSecurityStatusTime = DateTime.MinValue
DateTime mAuctionTime = DateTime.MinValue
DateTime mLineTime = DateTime.MinValue
DateTime mSendTime = DateTime.MinValue
MamdaFieldState mHighIndicationPriceFieldState = new MamdaFieldState()
MamdaFieldState mLowIndicationPriceFieldState = new MamdaFieldState()
MamdaFieldState mIndicationPriceFieldState = new MamdaFieldState()
MamdaFieldState mBuyVolumeFieldState = new MamdaFieldState()
MamdaFieldState mSellVolumeFieldState = new MamdaFieldState()
MamdaFieldState mMatchVolumeFieldState = new MamdaFieldState()
MamdaFieldState mSecurityStatusQualFieldState = new MamdaFieldState()
MamdaFieldState mInsideMatchPriceFieldState = new MamdaFieldState()
MamdaFieldState mFarClearingPriceFieldState = new MamdaFieldState()
MamdaFieldState mNearClearingPriceFieldState = new MamdaFieldState()
MamdaFieldState mNoClearingPriceFieldState = new MamdaFieldState()
MamdaFieldState mPriceVarIndFieldState = new MamdaFieldState()
MamdaFieldState mCrossTypeFieldState = new MamdaFieldState()
MamdaFieldState mEventTimeFieldState = new MamdaFieldState()
MamdaFieldState mEventSeqNumFieldState = new MamdaFieldState()
MamdaFieldState mSrcTimeFieldState = new MamdaFieldState()
MamdaFieldState mActTimeFieldState = new MamdaFieldState()
MamdaFieldState mMsgTypeFieldState = new MamdaFieldState()
MamdaFieldState mIssueSymbolFieldState = new MamdaFieldState()
MamdaFieldState mPartIdFieldState = new MamdaFieldState()
MamdaFieldState mSymbolFieldState = new MamdaFieldState()
MamdaFieldState mSeqNumFieldState = new MamdaFieldState()
MamdaFieldState mSecurityStatusOrigFieldState = new MamdaFieldState()
MamdaFieldState mSecurityStatusTimeFieldState = new MamdaFieldState()
MamdaFieldState mAuctionTimeFieldState = new MamdaFieldState()
MamdaFieldState mLineTimeFieldState = new MamdaFieldState()
MamdaFieldState mSendTimeFieldState = new MamdaFieldState()
Member Data Documentation
mHighIndicationPrice
MamaPrice Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPrice = new MamaPrice()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getHighIndicationPrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mLowIndicationPrice
MamaPrice Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPrice = new MamaPrice()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getLowIndicationPrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mIndicationPrice
MamaPrice Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPrice = new MamaPrice()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getImbalancePrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mBuyVolume
long Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolume
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getBuyVolume(), Wombat.MamdaOrderImbalanceListener.getImbalanceSide(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSellVolume
long Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolume
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getImbalanceSide(), Wombat.MamdaOrderImbalanceListener.getSellVolume(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mMatchVolume
long Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolume
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getMatchVolume(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSecurityStatusQual
String Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQual
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getImbalanceState(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mInsideMatchPrice
MamaPrice Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPrice = new MamaPrice()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getMatchPrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mFarClearingPrice
MamaPrice Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPrice = new MamaPrice()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getFarClearingPrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mNearClearingPrice
MamaPrice Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPrice = new MamaPrice()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getNearClearingPrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mNoClearingPrice
char Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPrice
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getNoClearingPrice(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mPriceVarInd
char Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarInd
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getPriceVarInd(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mCrossType
char Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossType
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getCrossType(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mEventTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getEventTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mEventSeqNum
long Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNum
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getEventSeqNum(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSrcTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSrcTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mActTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getActivityTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mMsgType
int Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgType
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getMsgType(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mIssueSymbol
String Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbol = null
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getIssueSymbol(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mPartId
String Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartId = null
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getPartId(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSymbol
String Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbol = null
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSymbol(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSeqNum
int Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNum
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSeqNum(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSecurityStatusOrig
String Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrig = null
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusOrig(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSecurityStatusTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mAuctionTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getAuctionTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mLineTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getLineTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mSendTime
DateTime Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTime = DateTime.MinValue
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSendTime(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().
mHighIndicationPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getHighIndicationPriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mLowIndicationPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getLowIndicationPriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mIndicationPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getImbalancePriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mBuyVolumeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolumeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getBuyVolumeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSellVolumeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolumeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSellVolumeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mMatchVolumeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolumeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getMatchVolumeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSecurityStatusQualFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQualFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getImbalanceStateFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mInsideMatchPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getMatchPriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mFarClearingPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getFarClearingPriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mNearClearingPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getNearClearingPriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mNoClearingPriceFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPriceFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getNoClearingPriceFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mPriceVarIndFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarIndFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getPriceVarIndFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mCrossTypeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossTypeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getCrossTypeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mEventTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getEventTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mEventSeqNumFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNumFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getEventSeqNumFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSrcTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSrcTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mActTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getActivityTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mMsgTypeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgTypeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getMsgTypeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mIssueSymbolFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbolFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getIssueSymbolFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mPartIdFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartIdFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getPartIdFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSymbolFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbolFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSymbolFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSeqNumFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNumFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSeqNumFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSecurityStatusOrigFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrigFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusOrigFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSecurityStatusTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mAuctionTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getAuctionTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mLineTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getLineTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().
mSendTimeFieldState
MamdaFieldState Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTimeFieldState = new MamdaFieldState()
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceListener.getSendTimeFieldState(), and Wombat.MamdaOrderImbalanceListener.onMsg().