OpenMAMDA C# API: Wombat.MamdaOrderImbalanceListener Class Reference
Wombat.MamdaOrderImbalanceListener Class Reference
A MamdaOrderImbalanceListener is class that specializes in handling imbalance order updates.
Inherits Wombat.MamdaMsgListener, Wombat.MamdaBasicEvent, Wombat.MamdaBasicRecap, and Wombat.MamdaOrderImbalanceRecap.
Classes
class MamdaOrderImbalanceCache
Public Member Functions
MamdaOrderImbalanceListener ()
void addHandler (MamdaOrderImbalanceHandler handler)
Registers handler interested in receiving update and recap events.
MamaPrice getHighIndicationPrice ()
Returns the high indication price of the imbalance order.
MamaPrice getLowIndicationPrice ()
Returns the low indication price of the imbalance order.
MamaPrice getImbalancePrice ()
Returns the indication price for the imbalance order.
long getBuyVolume ()
Returns the buy volume of the imbalance order
long getSellVolume ()
Returns the sell volume of the imbalance order
long getMatchVolume ()
Returns the match volume of the imbalance order
String getImbalanceState ()
Returns the order imbalance state
MamaPrice getMatchPrice ()
Returns the match price for the imbalance order.
MamaPrice getFarClearingPrice ()
Returns the far clearing price for the imbalance order.
MamaPrice getNearClearingPrice ()
Returns the near clearing price for the imbalance order.
char getNoClearingPrice ()
Returns the no clearing price for the imbalance order.
char getPriceVarInd ()
char getCrossType ()
Returns the imbalance cross type
DateTime getEventTime ()
MamdaBasicEvent.getEventTime
long getEventSeqNum ()
MamdaBasicEvent.getEventSeqNum
DateTime getActivityTime ()
MamdaBasicEvent.getActivityTime
DateTime getSrcTime ()
MamdaBasicEvent.getSrcTime
DateTime getLineTime ()
MamdaBasicEvent.getLineTime
DateTime getSendTime ()
MamdaBasicEvent.getSendTime
int getMsgType ()
String getIssueSymbol ()
String getSymbol ()
String getPartId ()
int getSeqNum ()
String getSecurityStatusOrig ()
DateTime getSecurityStatusTime ()
DateTime getAuctionTime ()
MamdaFieldState getHighIndicationPriceFieldState ()
Returns the high indication price field state
MamdaFieldState getLowIndicationPriceFieldState ()
Returns the low indication price field state
MamdaFieldState getImbalancePriceFieldState ()
Returns the indication price field state
MamdaFieldState getBuyVolumeFieldState ()
Returns the buy volume field state of the imbalance order
MamdaFieldState getSellVolumeFieldState ()
Returns the sell volume field state of the imbalance order
MamdaFieldState getMatchVolumeFieldState ()
Returns the match volume field state of the imbalance order
MamdaFieldState getImbalanceStateFieldState ()
Returns the order imbalance state field state
MamdaFieldState getMatchPriceFieldState ()
Returns the match price field state for the imbalance order.
MamdaFieldState getFarClearingPriceFieldState ()
Returns the far clearing price field state for the imbalance order.
MamdaFieldState getNearClearingPriceFieldState ()
Returns the near clearing price field state for the imbalance order.
MamdaFieldState getNoClearingPriceFieldState ()
Returns the no clearing price field state for the imbalance order.
MamdaFieldState getPriceVarIndFieldState ()
MamdaFieldState getCrossTypeFieldState ()
Returns the imbalance cross type field state
MamdaFieldState getEventTimeFieldState ()
MamdaBasicEvent.getEventTimeFieldState
MamdaFieldState getEventSeqNumFieldState ()
MamdaBasicEvent.getEventSeqNumFieldState
MamdaFieldState getActivityTimeFieldState ()
MamdaBasicEvent.getActivityTimeFieldState
MamdaFieldState getSrcTimeFieldState ()
MamdaBasicEvent.getSrcTimeFieldState
MamdaFieldState getLineTimeFieldState ()
MamdaBasicEvent.getLineTimeFieldState
MamdaFieldState getSendTimeFieldState ()
MamdaBasicEvent.getSendTimeFieldState
MamdaFieldState getMsgTypeFieldState ()
MamdaFieldState getIssueSymbolFieldState ()
MamdaFieldState getSymbolFieldState ()
MamdaFieldState getPartIdFieldState ()
MamdaFieldState getSeqNumFieldState ()
MamdaFieldState getSecurityStatusOrigFieldState ()
MamdaFieldState getSecurityStatusTimeFieldState ()
MamdaFieldState getAuctionTimeFieldState ()
void populateRecap (MamdaConcreteOrderImbalanceRecap recap)
Resets the recap object to cached values.
MamdaOrderImbalanceSide getImbalanceSide ()
Returns the imbalance side of the imbalance order.
long getImbalanceVolume ()
Returns the imbalance volume, which is either the sell or buy volume
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Static Protected Member Functions
static void clearCache (MamdaOrderImbalanceCache cache)
Clears all cached data by reseting to default values.
Protected Attributes
readonly MamdaOrderImbalanceCache mOrderImbalanceCache
Detailed Description
A MamdaOrderImbalanceListener is class that specializes in handling imbalance order updates.
An imbalance order occurs when too many orders of a particular type - either buy, sell or limit - for listed securities and not enough of the other, matching orders are received by an exchange. Developers provide their own implementation of the MamdaOrderImbalanceHandler interface and will be delivered notifications for imbalance updates.
Constructor & Destructor Documentation
MamdaOrderImbalanceListener()
Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceListener ()
References Wombat.MamdaOrderImbalanceListener.clearCache(), and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
Member Function Documentation
addHandler()
void Wombat.MamdaOrderImbalanceListener.addHandler (MamdaOrderImbalanceHandler handler)
Registers handler interested in receiving update and recap events.
Parameters
handler the handler to be registered.
getHighIndicationPrice()
MamaPrice Wombat.MamdaOrderImbalanceListener.getHighIndicationPrice ()
Returns the high indication price of the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getLowIndicationPrice()
MamaPrice Wombat.MamdaOrderImbalanceListener.getLowIndicationPrice ()
Returns the low indication price of the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getImbalancePrice()
MamaPrice Wombat.MamdaOrderImbalanceListener.getImbalancePrice ()
Returns the indication price for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getBuyVolume()
long Wombat.MamdaOrderImbalanceListener.getBuyVolume ()
Returns the buy volume of the imbalance order
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolume, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
Referenced by Wombat.MamdaOrderImbalanceListener.getImbalanceVolume().
getSellVolume()
long Wombat.MamdaOrderImbalanceListener.getSellVolume ()
Returns the sell volume of the imbalance order
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolume.
Referenced by Wombat.MamdaOrderImbalanceListener.getImbalanceVolume().
getMatchVolume()
long Wombat.MamdaOrderImbalanceListener.getMatchVolume ()
Returns the match volume of the imbalance order
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolume, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getImbalanceState()
String Wombat.MamdaOrderImbalanceListener.getImbalanceState ()
Returns the order imbalance state
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQual.
getMatchPrice()
MamaPrice Wombat.MamdaOrderImbalanceListener.getMatchPrice ()
Returns the match price for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getFarClearingPrice()
MamaPrice Wombat.MamdaOrderImbalanceListener.getFarClearingPrice ()
Returns the far clearing price for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getNearClearingPrice()
MamaPrice Wombat.MamdaOrderImbalanceListener.getNearClearingPrice ()
Returns the near clearing price for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getNoClearingPrice()
char Wombat.MamdaOrderImbalanceListener.getNoClearingPrice ()
Returns the no clearing price for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPrice, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getPriceVarInd()
char Wombat.MamdaOrderImbalanceListener.getPriceVarInd ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarInd.
getCrossType()
char Wombat.MamdaOrderImbalanceListener.getCrossType ()
Returns the imbalance cross type
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossType, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getEventTime()
DateTime Wombat.MamdaOrderImbalanceListener.getEventTime ()
MamdaBasicEvent.getEventTime
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTime, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getEventSeqNum()
long Wombat.MamdaOrderImbalanceListener.getEventSeqNum ()
MamdaBasicEvent.getEventSeqNum
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNum, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getActivityTime()
DateTime Wombat.MamdaOrderImbalanceListener.getActivityTime ()
MamdaBasicEvent.getActivityTime
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTime, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSrcTime()
DateTime Wombat.MamdaOrderImbalanceListener.getSrcTime ()
MamdaBasicEvent.getSrcTime
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTime.
getLineTime()
DateTime Wombat.MamdaOrderImbalanceListener.getLineTime ()
MamdaBasicEvent.getLineTime
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTime, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSendTime()
DateTime Wombat.MamdaOrderImbalanceListener.getSendTime ()
MamdaBasicEvent.getSendTime
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTime.
getMsgType()
int Wombat.MamdaOrderImbalanceListener.getMsgType ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgType, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getIssueSymbol()
String Wombat.MamdaOrderImbalanceListener.getIssueSymbol ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbol, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSymbol()
String Wombat.MamdaOrderImbalanceListener.getSymbol ()
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbol.
getPartId()
String Wombat.MamdaOrderImbalanceListener.getPartId ()
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartId.
getSeqNum()
int Wombat.MamdaOrderImbalanceListener.getSeqNum ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNum.
getSecurityStatusOrig()
String Wombat.MamdaOrderImbalanceListener.getSecurityStatusOrig ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrig.
getSecurityStatusTime()
DateTime Wombat.MamdaOrderImbalanceListener.getSecurityStatusTime ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTime.
getAuctionTime()
DateTime Wombat.MamdaOrderImbalanceListener.getAuctionTime ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTime, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getHighIndicationPriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getHighIndicationPriceFieldState ()
Returns the high indication price field state
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getLowIndicationPriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getLowIndicationPriceFieldState ()
Returns the low indication price field state
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getImbalancePriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getImbalancePriceFieldState ()
Returns the indication price field state
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getBuyVolumeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getBuyVolumeFieldState ()
Returns the buy volume field state of the imbalance order
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolumeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSellVolumeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSellVolumeFieldState ()
Returns the sell volume field state of the imbalance order
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolumeFieldState.
getMatchVolumeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getMatchVolumeFieldState ()
Returns the match volume field state of the imbalance order
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolumeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getImbalanceStateFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getImbalanceStateFieldState ()
Returns the order imbalance state field state
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQualFieldState.
getMatchPriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getMatchPriceFieldState ()
Returns the match price field state for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getFarClearingPriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getFarClearingPriceFieldState ()
Returns the far clearing price field state for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getNearClearingPriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getNearClearingPriceFieldState ()
Returns the near clearing price field state for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getNoClearingPriceFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getNoClearingPriceFieldState ()
Returns the no clearing price field state for the imbalance order.
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPriceFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getPriceVarIndFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getPriceVarIndFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarIndFieldState.
getCrossTypeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getCrossTypeFieldState ()
Returns the imbalance cross type field state
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossTypeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getEventTimeFieldState ()
MamdaBasicEvent.getEventTimeFieldState
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTimeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getEventSeqNumFieldState ()
MamdaBasicEvent.getEventSeqNumFieldState
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNumFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getActivityTimeFieldState ()
MamdaBasicEvent.getActivityTimeFieldState
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTimeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSrcTimeFieldState ()
MamdaBasicEvent.getSrcTimeFieldState
Returns
Implements Wombat.MamdaBasicEvent.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTimeFieldState.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getLineTimeFieldState ()
MamdaBasicEvent.getLineTimeFieldState
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTimeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSendTimeFieldState ()
MamdaBasicEvent.getSendTimeFieldState
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTimeFieldState.
getMsgTypeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getMsgTypeFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgTypeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getIssueSymbolFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getIssueSymbolFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbolFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
getSymbolFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSymbolFieldState ()
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbolFieldState.
getPartIdFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getPartIdFieldState ()
Returns
Implements Wombat.MamdaBasicRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartIdFieldState.
getSeqNumFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSeqNumFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNumFieldState.
getSecurityStatusOrigFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSecurityStatusOrigFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrigFieldState.
getSecurityStatusTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getSecurityStatusTimeFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTimeFieldState.
getAuctionTimeFieldState()
MamdaFieldState Wombat.MamdaOrderImbalanceListener.getAuctionTimeFieldState ()
Returns
Implements Wombat.MamdaOrderImbalanceRecap.
References Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTimeFieldState, and Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache.
populateRecap()
void Wombat.MamdaOrderImbalanceListener.populateRecap (MamdaConcreteOrderImbalanceRecap recap)
Resets the recap object to cached values.
Parameters
recap
References Wombat.MamdaConcreteOrderImbalanceRecap.clear(), Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossType, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNum, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbol, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgType, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPrice, Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartId, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarInd, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrig, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQual, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNum, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbol, Wombat.MamdaConcreteOrderImbalanceRecap.setActivityTime(), Wombat.MamdaConcreteOrderImbalanceRecap.setAuctionTime(), Wombat.MamdaConcreteOrderImbalanceRecap.setBuyVolume(), Wombat.MamdaConcreteOrderImbalanceRecap.setCrossType(), Wombat.MamdaConcreteOrderImbalanceRecap.setEventSeqNum(), Wombat.MamdaConcreteOrderImbalanceRecap.setEventTime(), Wombat.MamdaConcreteOrderImbalanceRecap.setFarClearingPrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setHighIndicationPrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setImbalancePrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setImbalanceState(), Wombat.MamdaConcreteOrderImbalanceRecap.setIssueSymbol(), Wombat.MamdaConcreteOrderImbalanceRecap.setLineTime(), Wombat.MamdaConcreteOrderImbalanceRecap.setLowIndicationPrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setMatchPrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setMatchVolume(), Wombat.MamdaConcreteOrderImbalanceRecap.setMsgType(), Wombat.MamdaConcreteOrderImbalanceRecap.setNearClearingPrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setNoClearingPrice(), Wombat.MamdaConcreteOrderImbalanceRecap.setPartId(), Wombat.MamdaConcreteOrderImbalanceRecap.setPriceVarInd(), Wombat.MamdaConcreteOrderImbalanceRecap.setSecurityStatusOrig(), Wombat.MamdaConcreteOrderImbalanceRecap.setSecurityStatusTime(), Wombat.MamdaConcreteOrderImbalanceRecap.setSellVolume(), Wombat.MamdaConcreteOrderImbalanceRecap.setSendTime(), Wombat.MamdaConcreteOrderImbalanceRecap.setSeqNum(), Wombat.MamdaConcreteOrderImbalanceRecap.setSrcTime(), and Wombat.MamdaConcreteOrderImbalanceRecap.setSymbol().
getImbalanceSide()
MamdaOrderImbalanceSide Wombat.MamdaOrderImbalanceListener.getImbalanceSide ()
Returns the imbalance side of the imbalance order.
This is determined by the Buy and Sell volumes.
Returns
References Wombat.MamdaOrderImbalanceSide.ASK_SIDE, Wombat.MamdaOrderImbalanceSide.BID_SIDE, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolume, Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolume.
Referenced by Wombat.MamdaOrderImbalanceListener.getImbalanceVolume().
getImbalanceVolume()
long Wombat.MamdaOrderImbalanceListener.getImbalanceVolume ()
Returns the imbalance volume, which is either the sell or buy volume
Returns
References Wombat.MamdaOrderImbalanceSide.BID_SIDE, Wombat.MamdaOrderImbalanceListener.getBuyVolume(), Wombat.MamdaOrderImbalanceListener.getImbalanceSide(), and Wombat.MamdaOrderImbalanceListener.getSellVolume().
onMsg()
void Wombat.MamdaOrderImbalanceListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaOrderImbalanceFields.ACTIVITY_TIME, Wombat.MamdaOrderImbalanceFields.AUCTION_TIME, Wombat.MamdaOrderImbalanceFields.BUY_VOLUME, Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceFields.CROSS_TYPE, Wombat.MamdaOrderImbalanceFields.FAR_CLEARING_PRICE, Wombat.MamdaOrderImbalanceFields.getMaxFid(), Wombat.MamdaOrderImbalanceFields.HIGH_INDICATION_PRICE, Wombat.MamdaOrderImbalanceFields.INDICATION_PRICE, Wombat.MamdaOrderImbalanceFields.INSIDE_MATCH_PRICE, Wombat.MamdaOrderImbalanceType.isMamdaImbalanceOrder(), Wombat.MamdaOrderImbalanceType.isMamdaOrderImbalanceType(), Wombat.MamdaOrderImbalanceFields.isSet(), Wombat.MamdaOrderImbalanceFields.ISSUE_SYMBOL, Wombat.MamdaOrderImbalanceFields.LINE_TIME, Wombat.MamdaOrderImbalanceFields.LOW_INDICATION_PRICE, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTimeFieldState, Wombat.MamdaOrderImbalanceFields.MATCH_VOLUME, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolumeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossType, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossTypeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNum, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNumFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbol, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbolFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolumeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgType, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgTypeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPriceFieldState, Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartId, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartIdFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarInd, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarIndFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrig, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrigFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQual, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQualFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolumeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNum, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNumFieldState, Wombat.MamdaOrderImbalanceFields.MSG_TYPE, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbol, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbolFieldState, Wombat.MamdaOrderImbalanceFields.NEAR_CLEARING_PRICE, Wombat.MamdaOrderImbalanceFields.NO_CLEARING_PRICE, Wombat.MamdaOrderImbalanceHandler.onNoOrderImbalance(), Wombat.MamdaOrderImbalanceHandler.onOrderImbalance(), Wombat.MamdaOrderImbalanceHandler.onOrderImbalanceRecap(), Wombat.MamdaOrderImbalanceFields.PART_ID, Wombat.MamdaOrderImbalanceFields.PRICE_VAR_IND, Wombat.MamdaOrderImbalanceFields.SECURITY_STATUS_ORIG, Wombat.MamdaOrderImbalanceFields.SECURITY_STATUS_QUAL, Wombat.MamdaOrderImbalanceFields.SECURITY_STATUS_TIME, Wombat.MamdaOrderImbalanceFields.SELL_VOLUME, Wombat.MamdaOrderImbalanceFields.SEND_TIME, Wombat.MamdaOrderImbalanceFields.SEQ_NUM, Wombat.MamdaOrderImbalanceFields.SRC_TIME, Wombat.MamdaOrderImbalanceType.stringToValue(), and Wombat.MamdaOrderImbalanceFields.SYMBOL.
clearCache()
static void Wombat.MamdaOrderImbalanceListener.clearCache (MamdaOrderImbalanceCache cache) static protected
Clears all cached data by reseting to default values.
Parameters
cache The imbalance order cache to clear.
References Wombat.MamdaOrderImbalanceSide.ASK_SIDE, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mActTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mAuctionTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mBuyVolumeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossType, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mCrossTypeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNum, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventSeqNumFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mEventTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mFarClearingPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mHighIndicationPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIndicationPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mInsideMatchPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbol, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mIssueSymbolFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLineTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mLowIndicationPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMatchVolumeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgType, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mMsgTypeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNearClearingPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPrice, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mNoClearingPriceFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartId, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPartIdFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarInd, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mPriceVarIndFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrig, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusOrigFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQual, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusQualFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSecurityStatusTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolume, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSellVolumeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSendTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNum, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSeqNumFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTime, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSrcTimeFieldState, Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbol, and Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceCache.mSymbolFieldState.
Referenced by Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceListener(), and Wombat.MamdaOrderImbalanceListener.onMsg().
Member Data Documentation
mOrderImbalanceCache
readonly MamdaOrderImbalanceCache Wombat.MamdaOrderImbalanceListener.mOrderImbalanceCache protected
Initial value:
=
            new MamdaOrderImbalanceCache ()
Referenced by Wombat.MamdaOrderImbalanceListener.getActivityTime(), Wombat.MamdaOrderImbalanceListener.getActivityTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getAuctionTime(), Wombat.MamdaOrderImbalanceListener.getAuctionTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getBuyVolume(), Wombat.MamdaOrderImbalanceListener.getBuyVolumeFieldState(), Wombat.MamdaOrderImbalanceListener.getCrossType(), Wombat.MamdaOrderImbalanceListener.getCrossTypeFieldState(), Wombat.MamdaOrderImbalanceListener.getEventSeqNum(), Wombat.MamdaOrderImbalanceListener.getEventSeqNumFieldState(), Wombat.MamdaOrderImbalanceListener.getEventTime(), Wombat.MamdaOrderImbalanceListener.getEventTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getFarClearingPrice(), Wombat.MamdaOrderImbalanceListener.getFarClearingPriceFieldState(), Wombat.MamdaOrderImbalanceListener.getHighIndicationPrice(), Wombat.MamdaOrderImbalanceListener.getHighIndicationPriceFieldState(), Wombat.MamdaOrderImbalanceListener.getImbalancePrice(), Wombat.MamdaOrderImbalanceListener.getImbalancePriceFieldState(), Wombat.MamdaOrderImbalanceListener.getImbalanceSide(), Wombat.MamdaOrderImbalanceListener.getImbalanceState(), Wombat.MamdaOrderImbalanceListener.getImbalanceStateFieldState(), Wombat.MamdaOrderImbalanceListener.getIssueSymbol(), Wombat.MamdaOrderImbalanceListener.getIssueSymbolFieldState(), Wombat.MamdaOrderImbalanceListener.getLineTime(), Wombat.MamdaOrderImbalanceListener.getLineTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getLowIndicationPrice(), Wombat.MamdaOrderImbalanceListener.getLowIndicationPriceFieldState(), Wombat.MamdaOrderImbalanceListener.getMatchPrice(), Wombat.MamdaOrderImbalanceListener.getMatchPriceFieldState(), Wombat.MamdaOrderImbalanceListener.getMatchVolume(), Wombat.MamdaOrderImbalanceListener.getMatchVolumeFieldState(), Wombat.MamdaOrderImbalanceListener.getMsgType(), Wombat.MamdaOrderImbalanceListener.getMsgTypeFieldState(), Wombat.MamdaOrderImbalanceListener.getNearClearingPrice(), Wombat.MamdaOrderImbalanceListener.getNearClearingPriceFieldState(), Wombat.MamdaOrderImbalanceListener.getNoClearingPrice(), Wombat.MamdaOrderImbalanceListener.getNoClearingPriceFieldState(), Wombat.MamdaOrderImbalanceListener.getPartId(), Wombat.MamdaOrderImbalanceListener.getPartIdFieldState(), Wombat.MamdaOrderImbalanceListener.getPriceVarInd(), Wombat.MamdaOrderImbalanceListener.getPriceVarIndFieldState(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusOrig(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusOrigFieldState(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusTime(), Wombat.MamdaOrderImbalanceListener.getSecurityStatusTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getSellVolume(), Wombat.MamdaOrderImbalanceListener.getSellVolumeFieldState(), Wombat.MamdaOrderImbalanceListener.getSendTime(), Wombat.MamdaOrderImbalanceListener.getSendTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getSeqNum(), Wombat.MamdaOrderImbalanceListener.getSeqNumFieldState(), Wombat.MamdaOrderImbalanceListener.getSrcTime(), Wombat.MamdaOrderImbalanceListener.getSrcTimeFieldState(), Wombat.MamdaOrderImbalanceListener.getSymbol(), Wombat.MamdaOrderImbalanceListener.getSymbolFieldState(), Wombat.MamdaOrderImbalanceListener.MamdaOrderImbalanceListener(), Wombat.MamdaOrderImbalanceListener.onMsg(), and Wombat.MamdaOrderImbalanceListener.populateRecap().