OpenMAMDA C# API: Wombat.MamdaSecurityStatusListener Class Reference
Wombat.MamdaSecurityStatusListener Class Reference
MamdaSecurityStatusListener is a class that specializes in handling security status updates.
Inherits Wombat.MamdaMsgListener, Wombat.MamdaSecurityStatusRecap, and Wombat.MamdaSecurityStatusUpdate.
Classes
class MamdaSecurityStatusCache
Public Member Functions
MamdaSecurityStatusListener ()
Create a specialized trade listener.
void addHandler (MamdaSecurityStatusHandler handler)
Add a specialized trade handler.
void populateRecap (MamdaConcreteSecurityStatusRecap recap)
DateTime getSrcTime ()
DateTime getActivityTime ()
long getEventSeqNum ()
DateTime getEventTime ()
long getSecurityStatus ()
MamdaSecurityStatusUpdate.getSecurityStatus()
long getSecurityStatusQualifier ()
MamdaSecurityStatusUpdate.getSecurityStatus()
MamdaSecurityStatus.mamdaSecurityStatus getSecurityStatusEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusEnum()
MamdaSecurityStatusQual.mamdaSecurityStatusQual getSecurityStatusQualifierEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifierEnum()
string getSecurityStatusStr ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
char getShortSaleCircuitBreaker ()
MamdaSecurityStatusUpdate.getShortSaleCircuitBreaker()
string getSecurityStatusQualifierStr ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
string getSecurityStatusOrigStr ()
Return the native security status qualifier
string getReason ()
MamdaSecurityStatusUpdate.getReason()
DateTime getLuldTime ()
MamdaSecurityStatusUpdate.getLuldTime()
char getLuldIndicator ()
MamdaSecurityStatusUpdate.getLuldIndicator()
MamaPrice getLuldHighLimit ()
MamdaSecurityStatusUpdate.getLuldHighLimit()
MamaPrice getLuldLowLimit ()
MamdaSecurityStatusUpdate.getLuldLowLimit()
MamdaFieldState getSrcTimeFieldState ()
MamdaFieldState getActivityTimeFieldState ()
MamdaFieldState getEventSeqNumFieldState ()
MamdaFieldState getEventTimeFieldState ()
MamdaFieldState getSecurityStatusFieldState ()
Get the field state
MamdaFieldState getSecurityStatusQualifierFieldState ()
Get the field state
MamdaFieldState getShortSaleCircuitBreakerFieldState ()
MamdaSecurityStatusUpdate.getShortSaleCircuitBreakerFieldState()
MamdaFieldState getSecurityStatusEnumFieldState ()
Get the field state
MamdaFieldState getSecurityStatusQualifierEnumFieldState ()
Get the field state
MamdaFieldState getSecurityStatusStrFieldState ()
Get the field state
MamdaFieldState getSecurityStatusQualifierStrFieldState ()
Get the field state
MamdaFieldState getSecurityStatusOrigStrFieldState ()
Get the field state
MamdaFieldState getReasonFieldState ()
Get the field state
MamdaFieldState getLuldTimeFieldState ()
Get the field state
MamdaFieldState getLuldIndicatorFieldState ()
Get the field state
MamdaFieldState getLuldHighLimitFieldState ()
Get the field state
MamdaFieldState getLuldLowLimitFieldState ()
Get the field state
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
string getFieldAsString (MamaMsgField field)
Static Protected Member Functions
static void clearCache (MamdaSecurityStatusCache cache)
Protected Attributes
readonly MamdaSecurityStatusCache mSecurityStatusCache = new MamdaSecurityStatusCache()
Detailed Description
MamdaSecurityStatusListener is a class that specializes in handling security status updates.
Developers provide their own implementation of the MamdaSecurityStatusHandler interface and will be delivered notifications for security status updates.
Note: The MamdaSecurityStatusListener class caches some field values. Among other reasons, caching of these fields makes it possible to provide complete certain callbacks, even when the publisher (e.g., feed handler) is only publishing deltas containing modified fields.
Constructor & Destructor Documentation
MamdaSecurityStatusListener()
Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusListener ()
Create a specialized trade listener.
This listener handles trade reports, trade recaps, trade errors/cancels, trade corrections, and trade gap notifications.
References Wombat.MamdaSecurityStatusListener.clearCache(), and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
Member Function Documentation
addHandler()
void Wombat.MamdaSecurityStatusListener.addHandler (MamdaSecurityStatusHandler handler)
Add a specialized trade handler.
Currently, only one handler can (and must) be registered.
clearCache()
static void Wombat.MamdaSecurityStatusListener.clearCache (MamdaSecurityStatusCache cache) static protected
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNum, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNumFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimit, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimitFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicator, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicatorFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimit, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimitFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReason, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReasonFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatus, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQual, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreaker, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreakerFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTime, and Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTimeFieldState.
Referenced by Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusListener().
populateRecap()
void Wombat.MamdaSecurityStatusListener.populateRecap (MamdaConcreteSecurityStatusRecap recap)
References Wombat.MamdaConcreteSecurityStatusRecap.clear(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimit, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicator, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimit, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReason, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatus, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQual, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr, Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreaker, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTime, Wombat.MamdaConcreteSecurityStatusRecap.setActivityTime(), Wombat.MamdaConcreteSecurityStatusRecap.setLuldHighLimit(), Wombat.MamdaConcreteSecurityStatusRecap.setLuldIndicator(), Wombat.MamdaConcreteSecurityStatusRecap.setLuldLowLimit(), Wombat.MamdaConcreteSecurityStatusRecap.setLuldTime(), Wombat.MamdaConcreteSecurityStatusRecap.setReason(), Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatus(), Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusQualifier(), Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusQualifierStr(), Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusStr(), Wombat.MamdaConcreteSecurityStatusRecap.setShortSaleCircuitBreaker(), and Wombat.MamdaConcreteSecurityStatusRecap.setSrcTime().
getSrcTime()
DateTime Wombat.MamdaSecurityStatusListener.getSrcTime ()
References Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, and Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTime.
getActivityTime()
DateTime Wombat.MamdaSecurityStatusListener.getActivityTime ()
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTime, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getEventSeqNum()
long Wombat.MamdaSecurityStatusListener.getEventSeqNum ()
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNum, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getEventTime()
DateTime Wombat.MamdaSecurityStatusListener.getEventTime ()
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTime, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatus()
long Wombat.MamdaSecurityStatusListener.getSecurityStatus ()
MamdaSecurityStatusUpdate.getSecurityStatus()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatus.mamdaSecurityStatusFromString(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusQualifier()
long Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifier ()
MamdaSecurityStatusUpdate.getSecurityStatus()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusQual.mamdaSecurityStatusQualFromString(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusEnum()
MamdaSecurityStatus.mamdaSecurityStatus Wombat.MamdaSecurityStatusListener.getSecurityStatusEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusEnum()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatus.mamdaSecurityStatusFromString(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusQualifierEnum()
MamdaSecurityStatusQual.mamdaSecurityStatusQual Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifierEnum()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusQual.mamdaSecurityStatusQualFromString(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusStr()
string Wombat.MamdaSecurityStatusListener.getSecurityStatusStr ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getShortSaleCircuitBreaker()
char Wombat.MamdaSecurityStatusListener.getShortSaleCircuitBreaker ()
MamdaSecurityStatusUpdate.getShortSaleCircuitBreaker()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, and Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreaker.
getSecurityStatusQualifierStr()
string Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierStr ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusOrigStr()
string Wombat.MamdaSecurityStatusListener.getSecurityStatusOrigStr ()
Return the native security status qualifier
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getReason()
string Wombat.MamdaSecurityStatusListener.getReason ()
MamdaSecurityStatusUpdate.getReason()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReason, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldTime()
DateTime Wombat.MamdaSecurityStatusListener.getLuldTime ()
MamdaSecurityStatusUpdate.getLuldTime()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTime, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldIndicator()
char Wombat.MamdaSecurityStatusListener.getLuldIndicator ()
MamdaSecurityStatusUpdate.getLuldIndicator()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicator, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldHighLimit()
MamaPrice Wombat.MamdaSecurityStatusListener.getLuldHighLimit ()
MamdaSecurityStatusUpdate.getLuldHighLimit()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimit, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldLowLimit()
MamaPrice Wombat.MamdaSecurityStatusListener.getLuldLowLimit ()
MamdaSecurityStatusUpdate.getLuldLowLimit()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimit, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSrcTimeFieldState ()
References Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, and Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTimeFieldState.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getActivityTimeFieldState ()
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTimeFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getEventSeqNumFieldState ()
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNumFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getEventTimeFieldState ()
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTimeFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusQualifierFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getShortSaleCircuitBreakerFieldState ()
MamdaSecurityStatusUpdate.getShortSaleCircuitBreakerFieldState()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, and Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreakerFieldState.
getSecurityStatusEnumFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusEnumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusQualifierEnumFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierEnumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusStrFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusStrFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusQualifierStrFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierStrFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getSecurityStatusOrigStrFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getSecurityStatusOrigStrFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getReasonFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getReasonFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReasonFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldTimeFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getLuldTimeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTimeFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldIndicatorFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getLuldIndicatorFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicatorFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldHighLimitFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getLuldHighLimitFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimitFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
getLuldLowLimitFieldState()
MamdaFieldState Wombat.MamdaSecurityStatusListener.getLuldLowLimitFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaSecurityStatusRecap.
References Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimitFieldState, and Wombat.MamdaSecurityStatusListener.mSecurityStatusCache.
onMsg()
void Wombat.MamdaSecurityStatusListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaSecurityStatusFields.ACTIVITY_TIME, Wombat.MamdaSecurityStatusFields.getMaxFid(), Wombat.MamdaSecurityStatusFields.LULDHIGHLIMIT, Wombat.MamdaSecurityStatusFields.LULDINDICATOR, Wombat.MamdaSecurityStatusFields.LULDLOWLIMIT, Wombat.MamdaSecurityStatusFields.LULDTIME, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNumFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimitFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicatorFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimitFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReasonFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState, Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreakerFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTimeFieldState, Wombat.MamdaSecurityStatusHandler.onSecurityStatusRecap(), Wombat.MamdaSecurityStatusHandler.onSecurityStatusUpdate(), Wombat.MamdaSecurityStatusFields.REASON, Wombat.MamdaSecurityStatusFields.SECURITY_STATUS, Wombat.MamdaSecurityStatusFields.SECURITY_STATUS_ORIG, Wombat.MamdaSecurityStatusFields.SECURITY_STATUS_QUAL, Wombat.MamdaSecurityStatusFields.SECURITY_STATUS_TIME, Wombat.MamdaSecurityStatusFields.SEQNUM, Wombat.MamdaSecurityStatusFields.SHORT_SALE_CIRCUIT_BREAKER, and Wombat.MamdaSecurityStatusFields.SRC_TIME.
getFieldAsString()
string Wombat.MamdaSecurityStatusListener.getFieldAsString (MamaMsgField field)
References Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mActTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNum, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventSeqNumFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mEventTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimit, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldHighLimitFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicator, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldIndicatorFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimit, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldLowLimitFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTime, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mLuldTimeFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReason, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mReasonFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusOrigStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusQualStrFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStr, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSecStatusStrFieldState, Wombat.MamdaSecurityStatusListener.mSecurityStatusCache, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreaker, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mShortSaleCircuitBreakerFieldState, Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTime, and Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusCache.mSrcTimeFieldState.
Referenced by Wombat.MamdaSecurityStatusListener.getFieldAsString().
Member Data Documentation
mSecurityStatusCache
readonly MamdaSecurityStatusCache Wombat.MamdaSecurityStatusListener.mSecurityStatusCache = new MamdaSecurityStatusCache() protected
Referenced by Wombat.MamdaSecurityStatusListener.getActivityTime(), Wombat.MamdaSecurityStatusListener.getActivityTimeFieldState(), Wombat.MamdaSecurityStatusListener.getEventSeqNum(), Wombat.MamdaSecurityStatusListener.getEventSeqNumFieldState(), Wombat.MamdaSecurityStatusListener.getEventTime(), Wombat.MamdaSecurityStatusListener.getEventTimeFieldState(), Wombat.MamdaSecurityStatusListener.getFieldAsString(), Wombat.MamdaSecurityStatusListener.getLuldHighLimit(), Wombat.MamdaSecurityStatusListener.getLuldHighLimitFieldState(), Wombat.MamdaSecurityStatusListener.getLuldIndicator(), Wombat.MamdaSecurityStatusListener.getLuldIndicatorFieldState(), Wombat.MamdaSecurityStatusListener.getLuldLowLimit(), Wombat.MamdaSecurityStatusListener.getLuldLowLimitFieldState(), Wombat.MamdaSecurityStatusListener.getLuldTime(), Wombat.MamdaSecurityStatusListener.getLuldTimeFieldState(), Wombat.MamdaSecurityStatusListener.getReason(), Wombat.MamdaSecurityStatusListener.getReasonFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatus(), Wombat.MamdaSecurityStatusListener.getSecurityStatusEnum(), Wombat.MamdaSecurityStatusListener.getSecurityStatusEnumFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusOrigStr(), Wombat.MamdaSecurityStatusListener.getSecurityStatusOrigStrFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifier(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierEnum(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierEnumFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierStr(), Wombat.MamdaSecurityStatusListener.getSecurityStatusQualifierStrFieldState(), Wombat.MamdaSecurityStatusListener.getSecurityStatusStr(), Wombat.MamdaSecurityStatusListener.getSecurityStatusStrFieldState(), Wombat.MamdaSecurityStatusListener.getShortSaleCircuitBreaker(), Wombat.MamdaSecurityStatusListener.getShortSaleCircuitBreakerFieldState(), Wombat.MamdaSecurityStatusListener.getSrcTime(), Wombat.MamdaSecurityStatusListener.getSrcTimeFieldState(), Wombat.MamdaSecurityStatusListener.MamdaSecurityStatusListener(), Wombat.MamdaSecurityStatusListener.onMsg(), and Wombat.MamdaSecurityStatusListener.populateRecap().