OpenMAMDA C# API: Wombat.MamdaOptionStrikeSet Class Reference
Wombat.MamdaOptionStrikeSet Class Reference
A class that represents the call and put contract sets at a given strike price.
Public Member Functions
MamdaOptionStrikeSet (DateTime expireDate, double strikePrice)
MamdaOptionContractSet getCallSet ()
Return a set of call option contracts at a given strike price.
MamdaOptionContractSet getPutSet ()
Return a set of put option contracts at a given strike price.
DateTime getExpireDate ()
Return the expiration date for the contracts at the given strike price.
string getExpireDateStr ()
Return the expiration date as a string for the contracts at the given strike price.
double getStrikePrice ()
Return the strike price.
Detailed Description
A class that represents the call and put contract sets at a given strike price.
Constructor & Destructor Documentation
MamdaOptionStrikeSet()
Wombat.MamdaOptionStrikeSet.MamdaOptionStrikeSet (DateTime expireDate, double strikePrice)
Member Function Documentation
getCallSet()
MamdaOptionContractSet Wombat.MamdaOptionStrikeSet.getCallSet ()
Return a set of call option contracts at a given strike price.
Returns
Set of call contracts at the given strike price.
Referenced by Wombat.MamdaOptionChain.addContract().
getPutSet()
MamdaOptionContractSet Wombat.MamdaOptionStrikeSet.getPutSet ()
Return a set of put option contracts at a given strike price.
Returns
MamdaOptionContractSet Set of put contracts at the given strike price.
Referenced by Wombat.MamdaOptionChain.addContract().
getExpireDate()
DateTime Wombat.MamdaOptionStrikeSet.getExpireDate ()
Return the expiration date for the contracts at the given strike price.
Returns
The expiration date.
getExpireDateStr()
string Wombat.MamdaOptionStrikeSet.getExpireDateStr ()
Return the expiration date as a string for the contracts at the given strike price.
Returns
The expiration date.
References Wombat.SimpleDateFormat.Format().
getStrikePrice()
double Wombat.MamdaOptionStrikeSet.getStrikePrice ()
Return the strike price.
Returns
The strike price.