OpenMAMDA C# API: Wombat.MamdaMultiSecurityManager Class Reference
Wombat.MamdaMultiSecurityManager Class Reference
MamdaMultiSecurityManager is a class that manages updates on a group symbol which provides a single subscription to multiple different securities.
Inherits Wombat.MamdaMsgListener.
Public Member Functions
MamdaMultiSecurityManager (string symbol)
Only constructor for the class.
void addHandler (MamdaMultiSecurityHandler handler)
Add a specialized handler for notifications about new securities.
void addListener (MamdaMsgListener listener, string symbol)
Add a specialized message listener (e.g.
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of the MamdaMsgListener Interface.
Detailed Description
MamdaMultiSecurityManager is a class that manages updates on a group symbol which provides a single subscription to multiple different securities.
Developers are notified of each element available for the group and can choose which elements they wish to provide handling for (e.g. based on wildcards).
Specialized Listeners can be added to the MamdaMultiSecurityManager in response to the callbacks on the MamdaMultiSecurityHandler being invoked. Alternatively, the Listeners can be added up front if the participants are known in advance.
Constructor & Destructor Documentation
MamdaMultiSecurityManager()
Wombat.MamdaMultiSecurityManager.MamdaMultiSecurityManager (string symbol)
Only constructor for the class.
No default available.
Parameters
symbol The group symbol for which the corresponding subscription was created.
Member Function Documentation
addHandler()
void Wombat.MamdaMultiSecurityManager.addHandler (MamdaMultiSecurityHandler handler)
Add a specialized handler for notifications about new securities.
Parameters
handler Concrete instance of the MamdaMultiSecurityHandler interface
addListener()
void Wombat.MamdaMultiSecurityManager.addListener (MamdaMsgListener listener, string symbol)
Add a specialized message listener (e.g.
a MamdaQuoteListener, MamdaTradeListener, etc.) for a security.
Multiple listeners for each security can be added.
Parameters
listener Concrete instance of the MamdaMsgListener interface.
symbol The symbol for the instrument.
References Wombat.Add, and Wombat.Containers.Map.valueOf().
onMsg()
void Wombat.MamdaMultiSecurityManager.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of the MamdaMsgListener Interface.
Parameters
subscription
msg
msgType
Implements Wombat.MamdaMsgListener.
References Wombat.Containers.Map.containsKey(), Wombat.MamdaCommonFields.ISSUE_SYMBOL, Wombat.MamdaMsgListener.onMsg(), Wombat.MamdaMultiSecurityHandler.onSecurityCreate(), Wombat.Containers.Map.put(), and Wombat.Containers.Map.valueOf().