OpenMAMDA C# API: Wombat.MamdaOptionChainListener Class Reference
Wombat.MamdaOptionChainListener Class Reference
MamdaOptionChainListener is a class that specializes in handling and managing option chain updates.
Inherits Wombat.MamdaMsgListener, and Wombat.MamdaOptionSeriesUpdate.
Public Member Functions
MamdaOptionChainListener (string underlyingSymbol)
Create a specialized option chain listener.
MamdaOptionChainListener (MamdaOptionChain chain)
Create a specialized option chain listener.
void addHandler (MamdaOptionChainHandler handler)
Add a specialized option chain handler.
MamdaOptionChain getOptionChain ()
Return the option chain associated with this listener.
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
DateTime getSrcTime ()
Returns the source time.
DateTime getActivityTime ()
long getEventSeqNum ()
DateTime getEventTime ()
MamdaOptionContract getOptionContract ()
Get the option contract to which the most recent event applies.
MamdaOptionAction getOptionAction ()
Get the most recent action.
MamdaFieldState getSrcTimeFieldState ()
Returns the field state.
MamdaFieldState getActivityTimeFieldState ()
Returns the field state.
MamdaFieldState getEventSeqNumFieldState ()
Returns the field state.
MamdaFieldState getEventTimeFieldState ()
Returns the field state.
MamdaFieldState getOptionContractFieldState ()
MamdaFieldState getOptionActionFieldState ()
string getFieldAsString (MamaMsgField field)
Detailed Description
MamdaOptionChainListener is a class that specializes in handling and managing option chain updates.
Developers provide their own implementation of the MamdaOptionChainHandler interface and will be delivered notifications for various types of options-related events.
Constructor & Destructor Documentation
MamdaOptionChainListener() [1/2]
Wombat.MamdaOptionChainListener.MamdaOptionChainListener (string underlyingSymbol)
Create a specialized option chain listener.
This listener handles option chain updates.
Parameters
underlyingSymbol
MamdaOptionChainListener() [2/2]
Wombat.MamdaOptionChainListener.MamdaOptionChainListener (MamdaOptionChain chain)
Create a specialized option chain listener.
This listener handles option chain updates.
Parameters
chain
Member Function Documentation
addHandler()
void Wombat.MamdaOptionChainListener.addHandler (MamdaOptionChainHandler handler)
Add a specialized option chain handler.
Parameters
handler
getOptionChain()
MamdaOptionChain Wombat.MamdaOptionChainListener.getOptionChain ()
Return the option chain associated with this listener.
Returns
onMsg()
void Wombat.MamdaOptionChainListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of MamdaListener interface.
Parameters
subscription
msg
msgType
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaOptionFields.isSet(), and Wombat.MamdaOptionChainHandler.onOptionChainRecap().
getSrcTime()
DateTime Wombat.MamdaOptionChainListener.getSrcTime ()
Returns the source time.
Returns
Source time. Typically, the exchange generated feed
time stamp. This is often the same as the "event time",
because many feeds do not distinguish between the actual event
time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getActivityTime()
DateTime Wombat.MamdaOptionChainListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements Wombat.MamdaBasicEvent.
getEventSeqNum()
long Wombat.MamdaOptionChainListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements Wombat.MamdaBasicEvent.
getEventTime()
DateTime Wombat.MamdaOptionChainListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getOptionContract()
MamdaOptionContract Wombat.MamdaOptionChainListener.getOptionContract ()
Get the option contract to which the most recent event applies.
Returns
The option contract to which the most recent event applies. If the contract is new, it will have already been added to the chain. If it is being removed, it will have already been removed from the chain.
Implements Wombat.MamdaOptionSeriesUpdate.
getOptionAction()
MamdaOptionAction Wombat.MamdaOptionChainListener.getOptionAction ()
Get the most recent action.
Returns
The action related to the last series update message.
Implements Wombat.MamdaOptionSeriesUpdate.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaOptionChainListener.getSrcTimeFieldState ()
Returns the field state.
Returns
Source time Field State
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaOptionChainListener.getActivityTimeFieldState ()
Returns the field state.
Returns
Activity time Field State
Implements Wombat.MamdaBasicEvent.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaOptionChainListener.getEventSeqNumFieldState ()
Returns the field state.
Returns
Source sequence number Field State
Implements Wombat.MamdaBasicEvent.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaOptionChainListener.getEventTimeFieldState ()
Returns the field state.
Returns
Event Time Field State
Implements Wombat.MamdaBasicEvent.
getOptionContractFieldState()
MamdaFieldState Wombat.MamdaOptionChainListener.getOptionContractFieldState ()
getOptionActionFieldState()
MamdaFieldState Wombat.MamdaOptionChainListener.getOptionActionFieldState ()
References Wombat.MamdaOptionChain.addContract(), Wombat.MamdaOptionFields.CONTRACT_SYMBOL, Wombat.MamdaOptionFields.EXERCISE_STYLE, Wombat.MamdaOptionFields.EXPIRATION_DATE, Wombat.MamdaOptionChain.getContract(), Wombat.MamdaOptionChainListener.getFieldAsString(), Wombat.MamdaOptionContract.getQuoteListener(), Wombat.MamdaOptionContract.getTradeListener(), Wombat.MamdaQuoteListener.onMsg(), Wombat.MamdaTradeListener.onMsg(), Wombat.MamdaOptionChainHandler.onOptionContractCreate(), Wombat.MamdaOptionFields.OPEN_INTEREST, Wombat.SimpleDateFormat.Parse(), Wombat.MamdaOptionFields.PUT_CALL, Wombat.MamdaOptionContract.setExerciseStyle(), Wombat.MamdaOptionContract.setOpenInterest(), and Wombat.MamdaOptionFields.STRIKE_PRICE.
getFieldAsString()
string Wombat.MamdaOptionChainListener.getFieldAsString (MamaMsgField field)
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().