OpenMAMDA C# API: Wombat.MamdaConcreteOrderImbalanceRecap Class Reference
Wombat.MamdaConcreteOrderImbalanceRecap Class Reference
Public Member Functions
MamdaConcreteOrderImbalanceRecap ()
void clear ()
Clear the recap data
DateTime getActivityTime ()
MamdaBasicRecap.getActivityTime
MamdaFieldState getActivityTimeFieldState ()
MamdaBasicRecap.getActivityTimeFieldState
void setActivityTime (DateTime actTime)
DateTime getLineTime ()
MamdaBasicRecap.getLineTime
MamdaFieldState getLineTimeFieldState ()
void setLineTime (DateTime lineTime)
DateTime getSendTime ()
MamdaBasicRecap.getActivityTime
MamdaFieldState getSendTimeFieldState ()
void setSendTime (DateTime sendTime)
DateTime getAuctionTime ()
MamdaFieldState getAuctionTimeFieldState ()
MamdaBasicRecap.FieldState
void setAuctionTime (DateTime auctionTime)
long getBuyVolume ()
MamdaFieldState getBuyVolumeFieldState ()
void setBuyVolume (long buyVolume)
char getCrossType ()
MamdaFieldState getCrossTypeFieldState ()
void setCrossType (char crossType)
long getEventSeqNum ()
MamdaFieldState getEventSeqNumFieldState ()
void setEventSeqNum (long eventSeqNum)
DateTime getEventTime ()
MamdaFieldState getEventTimeFieldState ()
void setEventTime (DateTime eventTime)
MamaPrice getFarClearingPrice ()
MamdaFieldState getFarClearingPriceFieldState ()
void setFarClearingPrice (MamaPrice farClearingPrice)
MamaPrice getHighIndicationPrice ()
MamdaFieldState getHighIndicationPriceFieldState ()
void setHighIndicationPrice (MamaPrice highIndicationPrice)
MamaPrice getImbalancePrice ()
MamdaFieldState getImbalancePriceFieldState ()
void setImbalancePrice (MamaPrice indicationPrice)
MamaPrice getMatchPrice ()
MamdaFieldState getMatchPriceFieldState ()
void setMatchPrice (MamaPrice insideMatchPrice)
string getIssueSymbol ()
MamdaFieldState getIssueSymbolFieldState ()
void setIssueSymbol (String issueSymbol)
string getSymbol ()
MamdaFieldState getSymbolFieldState ()
void setSymbol (String symbol)
MamaPrice getLowIndicationPrice ()
MamdaFieldState getLowIndicationPriceFieldState ()
void setLowIndicationPrice (MamaPrice lowIndicationPrice)
long getMatchVolume ()
MamdaFieldState getMatchVolumeFieldState ()
void setMatchVolume (long matchVolume)
int getMsgType ()
MamdaFieldState getMsgTypeFieldState ()
void setMsgType (int msgType)
MamaPrice getNearClearingPrice ()
MamdaFieldState getNearClearingPriceFieldState ()
void setNearClearingPrice (MamaPrice nearClearingPrice)
char getNoClearingPrice ()
MamdaFieldState getNoClearingPriceFieldState ()
void setNoClearingPrice (char noClearingPrice)
string getPartId ()
MamdaFieldState getPartIdFieldState ()
void setPartId (String partId)
char getPriceVarInd ()
MamdaFieldState getPriceVarIndFieldState ()
void setPriceVarInd (char priceVarInd)
String getSecurityStatusOrig ()
MamdaFieldState getSecurityStatusOrigFieldState ()
void setSecurityStatusOrig (string securityStatusOrig)
string getImbalanceState ()
MamdaFieldState getImbalanceStateFieldState ()
void setImbalanceState (string securityStatusQual)
DateTime getSecurityStatusTime ()
MamdaFieldState getSecurityStatusTimeFieldState ()
void setSecurityStatusTime (DateTime securityStatusTime)
long getSellVolume ()
MamdaFieldState getSellVolumeFieldState ()
void setSellVolume (long sellVolume)
int getSeqNum ()
MamdaFieldState getSeqNumFieldState ()
void setSeqNum (int seqNum)
DateTime getSrcTime ()
MamdaFieldState getSrcTimeFieldState ()
void setSrcTime (DateTime srcTime)
Detailed Description
Constructor & Destructor Documentation
MamdaConcreteOrderImbalanceRecap()
Wombat.MamdaConcreteOrderImbalanceRecap.MamdaConcreteOrderImbalanceRecap ()
Member Function Documentation
clear()
void Wombat.MamdaConcreteOrderImbalanceRecap.clear ()
Clear the recap data
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getActivityTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getActivityTime ()
MamdaBasicRecap.getActivityTime
Returns
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getActivityTimeFieldState ()
MamdaBasicRecap.getActivityTimeFieldState
Returns
setActivityTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setActivityTime (DateTime actTime)
Parameters
actTime
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getLineTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getLineTime ()
MamdaBasicRecap.getLineTime
Returns
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getLineTimeFieldState ()
Returns
setLineTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setLineTime (DateTime lineTime)
Parameters
actTime
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSendTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getSendTime ()
MamdaBasicRecap.getActivityTime
Returns
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSendTimeFieldState ()
Returns
setSendTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSendTime (DateTime sendTime)
Parameters
actTime
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getAuctionTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getAuctionTime ()
Returns
getAuctionTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getAuctionTimeFieldState ()
MamdaBasicRecap.FieldState
Returns
setAuctionTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setAuctionTime (DateTime auctionTime)
Parameters
auctionTime
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getBuyVolume()
long Wombat.MamdaConcreteOrderImbalanceRecap.getBuyVolume ()
Returns
getBuyVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getBuyVolumeFieldState ()
Returns
setBuyVolume()
void Wombat.MamdaConcreteOrderImbalanceRecap.setBuyVolume (long buyVolume)
Parameters
buyVolume
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getCrossType()
char Wombat.MamdaConcreteOrderImbalanceRecap.getCrossType ()
Returns
getCrossTypeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getCrossTypeFieldState ()
Returns
setCrossType()
void Wombat.MamdaConcreteOrderImbalanceRecap.setCrossType (char crossType)
Parameters
crossType
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getEventSeqNum()
long Wombat.MamdaConcreteOrderImbalanceRecap.getEventSeqNum ()
Returns
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getEventSeqNumFieldState ()
Returns
setEventSeqNum()
void Wombat.MamdaConcreteOrderImbalanceRecap.setEventSeqNum (long eventSeqNum)
Parameters
eventSeqNum
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getEventTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getEventTime ()
Returns
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getEventTimeFieldState ()
Returns
setEventTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setEventTime (DateTime eventTime)
Parameters
eventTime
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getFarClearingPrice()
MamaPrice Wombat.MamdaConcreteOrderImbalanceRecap.getFarClearingPrice ()
Returns
getFarClearingPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getFarClearingPriceFieldState ()
Returns
setFarClearingPrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setFarClearingPrice (MamaPrice farClearingPrice)
Parameters
farClearingPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getHighIndicationPrice()
MamaPrice Wombat.MamdaConcreteOrderImbalanceRecap.getHighIndicationPrice ()
Returns
getHighIndicationPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getHighIndicationPriceFieldState ()
Returns
setHighIndicationPrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setHighIndicationPrice (MamaPrice highIndicationPrice)
Parameters
highIndicationPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getImbalancePrice()
MamaPrice Wombat.MamdaConcreteOrderImbalanceRecap.getImbalancePrice ()
Returns
getImbalancePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getImbalancePriceFieldState ()
Returns
setImbalancePrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setImbalancePrice (MamaPrice indicationPrice)
Parameters
indicationPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getMatchPrice()
MamaPrice Wombat.MamdaConcreteOrderImbalanceRecap.getMatchPrice ()
Returns
getMatchPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getMatchPriceFieldState ()
Returns
setMatchPrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setMatchPrice (MamaPrice insideMatchPrice)
Parameters
insideMatchPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getIssueSymbol()
string Wombat.MamdaConcreteOrderImbalanceRecap.getIssueSymbol ()
Returns
getIssueSymbolFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getIssueSymbolFieldState ()
Returns
setIssueSymbol()
void Wombat.MamdaConcreteOrderImbalanceRecap.setIssueSymbol (String issueSymbol)
Parameters
issueSymbol
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSymbol()
string Wombat.MamdaConcreteOrderImbalanceRecap.getSymbol ()
Returns
getSymbolFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSymbolFieldState ()
Returns
setSymbol()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSymbol (String symbol)
Parameters
issueSymbol
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getLowIndicationPrice()
MamaPrice Wombat.MamdaConcreteOrderImbalanceRecap.getLowIndicationPrice ()
Returns
getLowIndicationPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getLowIndicationPriceFieldState ()
Returns
setLowIndicationPrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setLowIndicationPrice (MamaPrice lowIndicationPrice)
Parameters
lowIndicationPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getMatchVolume()
long Wombat.MamdaConcreteOrderImbalanceRecap.getMatchVolume ()
Returns
getMatchVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getMatchVolumeFieldState ()
Returns
setMatchVolume()
void Wombat.MamdaConcreteOrderImbalanceRecap.setMatchVolume (long matchVolume)
Parameters
matchVolume
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getMsgType()
int Wombat.MamdaConcreteOrderImbalanceRecap.getMsgType ()
Returns
getMsgTypeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getMsgTypeFieldState ()
Returns
setMsgType()
void Wombat.MamdaConcreteOrderImbalanceRecap.setMsgType (int msgType)
Parameters
msgType
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getNearClearingPrice()
MamaPrice Wombat.MamdaConcreteOrderImbalanceRecap.getNearClearingPrice ()
Returns
getNearClearingPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getNearClearingPriceFieldState ()
Returns
setNearClearingPrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setNearClearingPrice (MamaPrice nearClearingPrice)
Parameters
nearClearingPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getNoClearingPrice()
char Wombat.MamdaConcreteOrderImbalanceRecap.getNoClearingPrice ()
Returns
getNoClearingPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getNoClearingPriceFieldState ()
Returns
setNoClearingPrice()
void Wombat.MamdaConcreteOrderImbalanceRecap.setNoClearingPrice (char noClearingPrice)
Parameters
noClearingPrice
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getPartId()
string Wombat.MamdaConcreteOrderImbalanceRecap.getPartId ()
Returns
getPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getPartIdFieldState ()
Returns
setPartId()
void Wombat.MamdaConcreteOrderImbalanceRecap.setPartId (String partId)
Parameters
partId
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getPriceVarInd()
char Wombat.MamdaConcreteOrderImbalanceRecap.getPriceVarInd ()
Returns
getPriceVarIndFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getPriceVarIndFieldState ()
Returns
setPriceVarInd()
void Wombat.MamdaConcreteOrderImbalanceRecap.setPriceVarInd (char priceVarInd)
Parameters
priceVarInd
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSecurityStatusOrig()
String Wombat.MamdaConcreteOrderImbalanceRecap.getSecurityStatusOrig ()
Returns
getSecurityStatusOrigFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSecurityStatusOrigFieldState ()
Returns
setSecurityStatusOrig()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSecurityStatusOrig (string securityStatusOrig)
Parameters
securityStatusOrig
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getImbalanceState()
string Wombat.MamdaConcreteOrderImbalanceRecap.getImbalanceState ()
Returns
getImbalanceStateFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getImbalanceStateFieldState ()
Returns
setImbalanceState()
void Wombat.MamdaConcreteOrderImbalanceRecap.setImbalanceState (string securityStatusQual)
Parameters
securityStatusQual
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSecurityStatusTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getSecurityStatusTime ()
Returns
getSecurityStatusTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSecurityStatusTimeFieldState ()
Returns
setSecurityStatusTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSecurityStatusTime (DateTime securityStatusTime)
Parameters
securityStatusTime
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSellVolume()
long Wombat.MamdaConcreteOrderImbalanceRecap.getSellVolume ()
Returns
getSellVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSellVolumeFieldState ()
Returns
setSellVolume()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSellVolume (long sellVolume)
Parameters
sellVolume
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSeqNum()
int Wombat.MamdaConcreteOrderImbalanceRecap.getSeqNum ()
Returns
getSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSeqNumFieldState ()
Returns
setSeqNum()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSeqNum (int seqNum)
Parameters
seqNum
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().
getSrcTime()
DateTime Wombat.MamdaConcreteOrderImbalanceRecap.getSrcTime ()
Returns
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteOrderImbalanceRecap.getSrcTimeFieldState ()
Returns
setSrcTime()
void Wombat.MamdaConcreteOrderImbalanceRecap.setSrcTime (DateTime srcTime)
Parameters
srcTime the datetime to set.
Referenced by Wombat.MamdaOrderImbalanceListener.populateRecap().