OpenMAMDA C# API: Wombat.MamdaOrderBookEntry Class Reference
Wombat.MamdaOrderBookEntry Class Reference
MamdaOrderBookEntry is a class that provides/implements order book functionality.
Public Types
enum Actions : sbyte { Actions.Add = (sbyte)'A', Actions.Update = (sbyte)'U', Actions.Delete = (sbyte)'D', Actions.Unknown = (sbyte)'Z' }
An enumeration for book entry actions.
Public Member Functions
MamdaOrderBookEntry ()
MamdaOrderBookEntry (MamdaOrderBookEntry copy)
Copy an order book entry object which is a deep copy of the original.
void copy (MamdaOrderBookEntry copy)
Copy an order book entry object which is an exact and deep copy of the original.
void setId (string id)
void setSize (long size)
void setAction (Actions action)
void setTime (DateTime time)
void setDetails (MamdaOrderBookEntry copy)
string getId ()
If supported, Order book entry ID (order ID, participant ID, etc.)
long getSize ()
The size of the order entry.
Actions getAction ()
Whether to ADD, UPDATE or DELETE the entry.
DateTime getTime ()
Time of order book entry update.
bool hasTime ()
Returns whether the time part of this entry was set to a valid date
void assertEqual (MamdaOrderBookEntry rhs)
Order book entry equality verification.
bool equalId (string id)
Whether the id of the entry is equal to the id passed to the method.
Static Public Member Functions
static void setStrictChecking (bool strict)
Enforce strict checking of order book modifications (at the expense of some performance).
Detailed Description
MamdaOrderBookEntry is a class that provides/implements order book functionality.
Member Enumeration Documentation
Actions
enum Wombat.MamdaOrderBookEntry.Actions : sbyte strong
An enumeration for book entry actions.
Price level actions differ from entry actions because, for example, a price level message with Actions.Add may consist of entries with Actions.Add, Actions.Update or Actions.Delete.
Enumerator
Add
A new entry.
Update
An updated entry.
Delete
A deleted entry.
Unknown
Unknown action (error).
Constructor & Destructor Documentation
MamdaOrderBookEntry() [1/2]
Wombat.MamdaOrderBookEntry.MamdaOrderBookEntry ()
MamdaOrderBookEntry() [2/2]
Wombat.MamdaOrderBookEntry.MamdaOrderBookEntry (MamdaOrderBookEntry copy)
Copy an order book entry object which is a deep copy of the original.
Parameters
copy The MamdaOrderBookEntry to copy.
References Wombat.MamdaOrderBookEntry.copy().
Member Function Documentation
copy()
void Wombat.MamdaOrderBookEntry.copy (MamdaOrderBookEntry copy)
Copy an order book entry object which is an exact and deep copy of the original.
Parameters
copy The MamdaOrderBookEntry to deep copy.
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), and Wombat.MamdaOrderBookEntry.MamdaOrderBookEntry().
setId()
void Wombat.MamdaOrderBookEntry.setId (string id)
Parameters
id
Referenced by Wombat.MamdaOrderBookListener.onMsg().
setSize()
void Wombat.MamdaOrderBookEntry.setSize (long size)
Parameters
size
Referenced by Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), and Wombat.MamdaOrderBookListener.onMsg().
setAction()
void Wombat.MamdaOrderBookEntry.setAction (Actions action)
Parameters
action
Referenced by Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
setTime()
void Wombat.MamdaOrderBookEntry.setTime (DateTime time)
Parameters
time
Referenced by Wombat.MamdaOrderBookListener.onMsg().
setDetails()
void Wombat.MamdaOrderBookEntry.setDetails (MamdaOrderBookEntry copy)
Parameters
copy
Referenced by Wombat.MamdaOrderBookPriceLevel.updateEntry().
getId()
string Wombat.MamdaOrderBookEntry.getId ()
If supported, Order book entry ID (order ID, participant ID, etc.)
Returns
Referenced by Wombat.MamdaOrderBookPriceLevel.checkNotExist(), Wombat.MamdaOrderBookPriceLevel.removeEntry(), Wombat.MamdaOrderBookPriceLevel.setAsDifference(), Wombat.MamdaOrderBook.setStrictChecking(), and Wombat.MamdaOrderBookPriceLevel.updateEntry().
getSize()
long Wombat.MamdaOrderBookEntry.getSize ()
The size of the order entry.
Returns
Referenced by Wombat.MamdaOrderBookPriceLevel.setAsDifference(), and Wombat.MamdaOrderBook.setStrictChecking().
getAction()
Actions Wombat.MamdaOrderBookEntry.getAction ()
Whether to ADD, UPDATE or DELETE the entry.
Returns
The action.
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
getTime()
DateTime Wombat.MamdaOrderBookEntry.getTime ()
Time of order book entry update.
Returns
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
hasTime()
bool Wombat.MamdaOrderBookEntry.hasTime ()
Returns whether the time part of this entry was set to a valid date
Returns
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
assertEqual()
void Wombat.MamdaOrderBookEntry.assertEqual (MamdaOrderBookEntry rhs)
Order book entry equality verification.
A MamdaOrderBookException is thrown if the entries within a price level are not equal, along with the reason for the inequality.
Parameters
rhs
Exceptions
MamdaOrderBookException MamdaOrderBookException
Referenced by Wombat.MamdaOrderBookPriceLevel.assertEqual().
equalId()
bool Wombat.MamdaOrderBookEntry.equalId (string id)
Whether the id of the entry is equal to the id passed to the method.
Parameters
id The id to compare to the order entry id.
Returns
Whether the id is the same as the order id.
Referenced by Wombat.MamdaOrderBookPriceLevel.checkNotExist(), Wombat.MamdaOrderBookPriceLevel.removeEntry(), and Wombat.MamdaOrderBookPriceLevel.updateEntry().
setStrictChecking()
static void Wombat.MamdaOrderBookEntry.setStrictChecking (bool strict) static
Enforce strict checking of order book modifications (at the expense of some performance).
This setting is automatically updated by MamdaOrderBook.setStrictChecking().
Parameters
strict
Referenced by Wombat.MamdaOrderBook.setStrictChecking().