OpenMAMDA C# API: Wombat.MamdaFields Class Reference
Wombat.MamdaFields Class Reference
Common base class for all the MamdaXXXFields classes.
Inherited by Wombat.MamdaAuctionFields, Wombat.MamdaCommonFields, Wombat.MamdaFundamentalFields, Wombat.MamdaOptionFields, Wombat.MamdaOrderBookFields, Wombat.MamdaOrderImbalanceFields, Wombat.MamdaQuoteFields, Wombat.MamdaSecurityStatusFields, and Wombat.MamdaTradeFields.
Static Protected Member Functions
static string lookupFieldName (NameValueCollection properties, string defaultFieldName)
Detailed Description
Common base class for all the MamdaXXXFields classes.
Each of the subclasses maintains a cache of relevant MamaFieldDescriptors obtained from the MamaDictionary using the fields standard name. If the dictionary is being published with non standard field name mappings users can pass a NameValueCollection object to the corresponding setDictionary() method which contains field mappings.
Each mapping should have the following format:
mamda.field.<common field name>=<mapped field name> e.g.
mamda.field.wTradePrice=mMappedTradePrice where mMappedTradePrice is the name of the field under which the trade price is being published by the feedhandlers and which is being published by the dictionary to describe the trade price field.
Member Function Documentation
lookupFieldName()
static string Wombat.MamdaFields.lookupFieldName (NameValueCollection properties, string defaultFieldName) static protected
Parameters
properties
defaultFieldName
Returns
Referenced by Wombat.MamdaOrderImbalanceFields.setDictionary(), Wombat.MamdaOptionFields.setDictionary(), Wombat.MamdaSecurityStatusFields.setDictionary(), Wombat.MamdaFundamentalFields.setDictionary(), Wombat.MamdaAuctionFields.setDictionary(), Wombat.MamdaQuoteFields.setDictionary(), Wombat.MamdaOrderBookFields.setDictionary(), Wombat.MamdaTradeFields.setDictionary(), and Wombat.MamdaCommonFields.setDictionary().