OpenMAMDA C# API: Wombat.MamdaConcreteTradeRecap Class Reference
Wombat.MamdaConcreteTradeRecap Class Reference
Inherits Wombat.MamdaTradeRecap.
Public Member Functions
MamdaConcreteTradeRecap ()
void clear ()
Clear the recap data
string getSymbol ()
MamdaFieldState getSymbolFieldState ()
void setSymbol (string symbol)
string getPartId ()
MamdaFieldState getPartIdFieldState ()
void setPartId (string partId)
long getAccVolume ()
Total volume of shares traded in a security at the time it is disseminated.
MamdaFieldState getAccVolumeFieldState ()
Get the field state
void setAccVolume (long accVolume)
void setAccVolume (double accVolume)
long getOffExAccVolume ()
Total volume of shares traded off exchange in a security at the time it is disseminated.
MamdaFieldState getOffExAccVolumeFieldState ()
Get the field state
void setOffExAccVolume (long offExAccVolume)
void setOffExAccVolume (double offExAccVolume)
long getOnExAccVolume ()
Total volume of shares traded on exchange in a security at the time it is disseminated.
MamdaFieldState getOnExAccVolumeFieldState ()
Get the field state
void setOnExAccVolume (long onExAccVolume)
void setOnExAccVolume (double onExAccVolume)
DateTime getActivityTime ()
MamdaFieldState getActivityTimeFieldState ()
Returns the field state.
void setActTime (DateTime actTime)
DateTime getLineTime ()
MamdaFieldState getLineTimeFieldState ()
void setLineTime (DateTime lineTime)
DateTime getSendTime ()
MamdaFieldState getSendTimeFieldState ()
void setSendTime (DateTime sendTime)
string getPubId ()
MamdaFieldState getPubIdFieldState ()
void setPubId (string pubId)
long getBlockCount ()
The number of block trades (at least 10,000 shares) today.
MamdaFieldState getBlockCountFieldState ()
Get the field state
void setBlockCount (long blockCount)
long getBlockVolume ()
Total volume of block trades today.
MamdaFieldState getBlockVolumeFieldState ()
Get the field state
void setBlockVolume (long blockVolume)
void setBlockVolume (double blockVolume)
MamaPrice getClosePrice ()
Today's closing price.
MamdaFieldState getClosePriceFieldState ()
Get the field state
void setClosePrice (MamaPrice closePrice)
string getCorrCondStr ()
MamdaFieldState getCorrCondStrFieldState ()
void setCorrCondStr (string corrCondStr)
string getCorrPartId ()
MamdaFieldState getCorrPartIdFieldState ()
void setCorrPartId (string corrPartId)
MamaPrice getCorrPrice ()
MamdaFieldState getCorrPriceFieldState ()
void setCorrPrice (MamaPrice corrPrice)
string getCorrQualStr ()
MamdaFieldState getCorrQualStrFieldState ()
void setCorrQualStr (string corrQualStr)
string getCorrQualNativeStr ()
MamdaFieldState getCorrQualNativeStrFieldState ()
void setCorrQualNativeStr (string corrQualNativeStr)
long getCorrSellersSaleDays ()
MamdaFieldState getCorrSellersSaleDaysFieldState ()
void setCorrSellersSaleDays (long corrSellersSaleDays)
char getCorrStopStockInd ()
MamdaFieldState getCorrStopStockIndFieldState ()
void setCorrStopStockInd (char corrStopStockInd)
DateTime getCancelTime ()
MamdaFieldState getCancelTimeFieldState ()
void setCancelTime (DateTime cancelTime)
long getCorrVolume ()
MamdaFieldState getCorrVolumeFieldState ()
void setCorrVolume (long corrVolume)
void setCorrVolume (double corrVolume)
long getEventSeqNum ()
MamdaFieldState getEventSeqNumFieldState ()
Returns the field state.
void setEventSeqNum (long eventSeqNum)
DateTime getEventTime ()
MamdaFieldState getEventTimeFieldState ()
Returns the field state.
void setEventTime (DateTime eventTime)
MamaPrice getHighPrice ()
Highest price paid for security during the trading day.
MamdaFieldState getHighPriceFieldState ()
Get the field state
void setHighPrice (MamaPrice highPrice)
string getLastPartId ()
Trade participant ID.
string getTradeId ()
string getCorrTradeId ()
string getOrigTradeId ()
MamdaFieldState getLastPartIdFieldState ()
Get the field state
MamdaFieldState getTradeIdFieldState ()
MamdaFieldState getOrigTradeIdFieldState ()
MamdaFieldState getCorrTradeIdFieldState ()
void setLastPartId (string lastPartId)
void setTradeId (string tradeId)
void setOrigTradeId (string origTradeId)
void setCorrTradeId (string corrTradeId)
MamaPrice getLastPrice ()
Monetary value of an individual share of the security at the time of the trade.
MamdaFieldState getLastPriceFieldState ()
Get the field state
void setLastPrice (MamaPrice lastPrice)
DateTime getLastTime ()
Time corresponding to the last trade, as reported by the feed The exact time of the trade may not be available, since rules governing trade reporting allow for a trades to be reported within a specified time limit.
MamdaFieldState getLastTimeFieldState ()
Get the field state
void setLastTime (DateTime lastTime)
DateTime getTradeDate ()
MamdaFieldState getTradeDateFieldState ()
Get the field state
void setTradeDate (DateTime tradeDate)
MamaPrice getIrregPrice ()
Monetary value of an individual share of the security at the time of the last irregular trade.
MamdaFieldState getIrregPriceFieldState ()
Get the field state
void setIrregPrice (MamaPrice irregPrice)
long getIrregVolume ()
Number of shares traded in a single transaction for an individual security.
MamdaFieldState getIrregVolumeFieldState ()
Get the field state
void setIrregVolume (long irregVolume)
void setIrregVolume (double irregVolume)
string getIrregPartId ()
Trade participant ID for the last irregular trade.
MamdaFieldState getIrregPartIdFieldState ()
Get the field state
void setIrregPartId (string irregPartId)
DateTime getIrregTime ()
Time corresponding to the last irregular trade, as reported by the feed The exact time of the trade may not be available, since rules governing trade reporting allow for a trades to be reported within a specified time limit.
MamdaFieldState getIrregTimeFieldState ()
Get the field state
void setIrregTime (DateTime irregTime)
long getLastVolume ()
Number of shares traded in a single transaction for an individual security.
MamdaFieldState getLastVolumeFieldState ()
Get the field state
void setLastVolume (long lastVolume)
void setLastVolume (double lastVolume)
MamaPrice getLowPrice ()
Lowest price paid for security during the trading day.
MamdaFieldState getLowPriceFieldState ()
Get the field state
void setLowPrice (MamaPrice lowPrice)
MamaPrice getNetChange ()
Get the change in price compared with the previous closing price
MamdaFieldState getNetChangeFieldState ()
Get the field state
void setNetChange (MamaPrice netChange)
MamaPrice getOpenPrice ()
The price of the first qualifying trade in the security during the current trading day.
MamdaFieldState getOpenPriceFieldState ()
Get the field state
void setOpenPrice (MamaPrice openPrice)
string getOrigCondStr ()
MamdaFieldState getOrigCondStrFieldState ()
void setOrigCondStr (string origCondStr)
string getOrigPartId ()
MamdaFieldState getOrigPartIdFieldState ()
void setOrigPartId (string origPartId)
MamaPrice getOrigPrice ()
MamdaFieldState getOrigPriceFieldState ()
void setOrigPrice (MamaPrice origPrice)
string getOrigQualStr ()
MamdaFieldState getOrigQualStrFieldState ()
void setOrigQualStr (string origQualStr)
string getOrigQualNativeStr ()
MamdaFieldState getOrigQualNativeStrFieldState ()
void setOrigQualNativeStr (string origQualNativeStr)
long getOrigSellersSaleDays ()
MamdaFieldState getOrigSellersSaleDaysFieldState ()
void setOrigSellersSaleDays (long origSellersSaleDays)
char getOrigStopStockInd ()
MamdaFieldState getOrigStopStockIndFieldState ()
void setOrigStopStockInd (char origStopStockInd)
long getOrigSeqNum ()
MamdaFieldState getOrigSeqNumFieldState ()
void setOrigSeqNum (long origSeqNum)
long getOrigVolume ()
MamdaFieldState getOrigVolumeFieldState ()
void setOrigVolume (long origVolume)
void setOrigVolume (double origVolume)
double getPctChange ()
Change in price as a percentage.
MamdaFieldState getPctChangeFieldState ()
Get the field state
void setPctChange (double pctChange)
DateTime getPrevCloseDate ()
Date corresponding to PrevClosePrice.
MamdaFieldState getPrevCloseDateFieldState ()
Get the field state
void setPrevCloseDate (DateTime prevCloseDate)
MamaPrice getAdjPrevClose ()
The previous close price adjusted by corporate actions, such as dividends and stock splits on the ex-date.
MamdaFieldState getAdjPrevCloseFieldState ()
Get the field state
void setAdjPrevClose (MamaPrice adjPrevClose)
MamaPrice getPrevClosePrice ()
The last qualifying trade price on the previous trading day.
MamdaFieldState getPrevClosePriceFieldState ()
Get the field state
void setPrevClosePrice (MamaPrice prevClosePrice)
long getSellersSaleDays ()
MamdaFieldState getSellersSaleDaysFieldState ()
void setSellersSaleDays (long sellersSaleDays)
char getStopStockInd ()
MamdaFieldState getStopStockIndFieldState ()
void setStopStockInd (char stopStockInd)
DateTime getSrcTime ()
Returns the source time.
MamdaFieldState getSrcTimeFieldState ()
Returns the field state.
void setSrcTime (DateTime srcTime)
double getStdDev ()
Standard deviation of last trade price of a security at the time it is disseminated.
MamdaFieldState getStdDevFieldState ()
Get the field state
void setStdDev (double stdDev)
double getStdDevSum ()
MamdaFieldState getStdDevSumFieldState ()
Get the field state
void setStdDevSum (double stdDevSum)
double getStdDevSumSquares ()
MamdaFieldState getStdDevSumSquaresFieldState ()
Get the field state
void setStdDevSumSquares (double stdDevSumSquares)
long getOrderId ()
Get the order id, if available.
MamdaFieldState getOrderIdFieldState ()
Get the field state
void setOrderId (long orderId)
MamaPrice getSettlePrice ()
Future's / Options settlement price.
MamdaFieldState getSettlePriceFieldState ()
Get the field state
void setSettlePrice (MamaPrice settlePrice)
DateTime getSettleDate ()
Date corresponding to SettlePrice.
MamdaFieldState getSettleDateFieldState ()
Get the field state
void setSettleDate (DateTime settleDate)
char getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
MamdaFieldState getShortSaleCircuitBreakerFieldState ()
Returns the FieldState, always MODIFIED.
void setShortSaleCircuitBreaker (char shortSaleCircuitBreaker)
Set the shortSaleCircuitBreaker
double getTotalValue ()
Total value of all shares traded in a security at the time it is disseminated.
MamdaFieldState getTotalValueFieldState ()
Get the field state
void setTotalValue (double totalValue)
double getOffExTotalValue ()
Total value of all shares traded off exchange in a security at the time it is disseminated.
MamdaFieldState getOffExTotalValueFieldState ()
Get the field state
void setOffExTotalValue (double offExTotalValue)
double getOnExTotalValue ()
Total value of all shares traded on exchange in a security at the time it is disseminated.
MamdaFieldState getOnExTotalValueFieldState ()
Get the field state
void setOnExTotalValue (double onExTotalValue)
string getTradeCondStr ()
MamdaFieldState getTradeCondStrFieldState ()
void setTradeCondStr (string tradeCondStr)
long getTradeCount ()
The number of trades today.
MamdaFieldState getTradeCountFieldState ()
Get the field state
void setTradeCount (long tradeCount)
string getTradeUnits ()
MamdaFieldState getTradeUnitsFieldState ()
Get the field state
void setTradeUnits (string tradeUnits)
long getLastSeqNum ()
MamdaFieldState getLastSeqNumFieldState ()
Get the field state
void setLastSeqNum (long lastSeqNum)
long getHighSeqNum ()
MamdaFieldState getHighSeqNumFieldState ()
Get the field state
void setHighSeqNum (long highSeqNum)
long getLowSeqNum ()
MamdaFieldState getLowSeqNumFieldState ()
Get the field state
void setLowSeqNum (long lowSeqNum)
long getTotalVolumeSeqNum ()
MamdaFieldState getTotalVolumeSeqNumFieldState ()
Get the field state
void setTotalVolumeSeqNum (long totalVolumeSeqNum)
string getCurrencyCode ()
MamdaFieldState getCurrencyCodeFieldState ()
Get the field state
void setCurrencyCode (string currencyCode)
string getTradeDirection ()
Trade tick direction.
MamdaFieldState getTradeDirectionFieldState ()
Get the field state
void setTradeDirection (string tradeDirection)
string getSide ()
Returns the Aggressor side or TradeSide
MamdaFieldState getSideFieldState ()
Get the field state
void setSide (string tradeSide)
string getTradePartId ()
MamdaFieldState getTradePartIdFieldState ()
void setTradePartId (string tradePartId)
MamaPrice getTradePrice ()
MamdaFieldState getTradePriceFieldState ()
void setTradePrice (MamaPrice tradePrice)
string getTradeQualStr ()
MamdaFieldState getTradeQualStrFieldState ()
void setTradeQualStr (string tradeQualStr)
string getTradeQualNativeStr ()
MamdaFieldState getTradeQualNativeStrFieldState ()
void setTradeQualNativeStr (string tradeQualNativeStr)
long getTradeVolume ()
MamdaFieldState getTradeVolumeFieldState ()
void setTradeVolume (long tradeVolume)
void setTradeVolume (double tradeVolume)
double getVwap ()
Volume-weighted average price of a security at the time it is disseminated.
MamdaFieldState getVwapFieldState ()
Get the field state
void setVwap (double vwap)
double getOffExVwap ()
Volume-weighted average off exchange price of a security at the time it is disseminated.
MamdaFieldState getOffExVwapFieldState ()
Get the field state
void setOffExVwap (double offExVwap)
double getOnExVwap ()
Volume-weighted average on exchange price of a security at the time it is disseminated.
MamdaFieldState getOnExVwapFieldState ()
Get the field state
void setOnExVwap (double onExVwap)
bool IsIrregular ()
void setIsIrregular (bool isIrregular)
bool IsCancel ()
void setIsCancel (bool isCancel)
string getTradeExecVenue ()
Trade execution venue.
MamdaFieldState getTradeExecVenueFieldState ()
Get the field state
void setTradeExecVenue (string tradeExecVenue)
MamaPrice getOffExchangeTradePrice ()
Monetary value of an individual off exchange share of the security at the time of the trade.
MamdaFieldState getOffExchangeTradePriceFieldState ()
Get the field state
void setOffExchangeTradePrice (MamaPrice offExTradePrice)
MamaPrice getOnExchangeTradePrice ()
Monetary value of an individual off exchange share of the security at the time of the trade.
MamdaFieldState getOnExchangeTradePriceFieldState ()
Get the field state
void setOnExchangeTradePrice (MamaPrice onExTradePrice)
Detailed Description
Constructor & Destructor Documentation
MamdaConcreteTradeRecap()
Wombat.MamdaConcreteTradeRecap.MamdaConcreteTradeRecap ()
Member Function Documentation
clear()
void Wombat.MamdaConcreteTradeRecap.clear ()
Clear the recap data
getSymbol()
string Wombat.MamdaConcreteTradeRecap.getSymbol ()
getSymbolFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSymbolFieldState ()
setSymbol()
void Wombat.MamdaConcreteTradeRecap.setSymbol (string symbol)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getPartId()
string Wombat.MamdaConcreteTradeRecap.getPartId ()
getPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getPartIdFieldState ()
setPartId()
void Wombat.MamdaConcreteTradeRecap.setPartId (string partId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getAccVolume()
long Wombat.MamdaConcreteTradeRecap.getAccVolume ()
Total volume of shares traded in a security at the time it is disseminated.
Returns
Implements Wombat.MamdaTradeRecap.
getAccVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getAccVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setAccVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setAccVolume (long accVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setAccVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setAccVolume (double accVolume)
getOffExAccVolume()
long Wombat.MamdaConcreteTradeRecap.getOffExAccVolume ()
Total volume of shares traded off exchange in a security at the time it is disseminated.
Returns
Implements Wombat.MamdaTradeRecap.
getOffExAccVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOffExAccVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOffExAccVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setOffExAccVolume (long offExAccVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setOffExAccVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setOffExAccVolume (double offExAccVolume)
getOnExAccVolume()
long Wombat.MamdaConcreteTradeRecap.getOnExAccVolume ()
Total volume of shares traded on exchange in a security at the time it is disseminated.
Returns
Implements Wombat.MamdaTradeRecap.
getOnExAccVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOnExAccVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOnExAccVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setOnExAccVolume (long onExAccVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setOnExAccVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setOnExAccVolume (double onExAccVolume)
getActivityTime()
DateTime Wombat.MamdaConcreteTradeRecap.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getActivityTimeFieldState ()
Returns the field state.
Returns
Activity time Field State
Implements Wombat.MamdaBasicEvent.
setActTime()
void Wombat.MamdaConcreteTradeRecap.setActTime (DateTime actTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLineTime()
DateTime Wombat.MamdaConcreteTradeRecap.getLineTime ()
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLineTimeFieldState ()
setLineTime()
void Wombat.MamdaConcreteTradeRecap.setLineTime (DateTime lineTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getSendTime()
DateTime Wombat.MamdaConcreteTradeRecap.getSendTime ()
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSendTimeFieldState ()
setSendTime()
void Wombat.MamdaConcreteTradeRecap.setSendTime (DateTime sendTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getPubId()
string Wombat.MamdaConcreteTradeRecap.getPubId ()
getPubIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getPubIdFieldState ()
setPubId()
void Wombat.MamdaConcreteTradeRecap.setPubId (string pubId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getBlockCount()
long Wombat.MamdaConcreteTradeRecap.getBlockCount ()
The number of block trades (at least 10,000 shares) today.
Returns
Implements Wombat.MamdaTradeRecap.
getBlockCountFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getBlockCountFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setBlockCount()
void Wombat.MamdaConcreteTradeRecap.setBlockCount (long blockCount)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getBlockVolume()
long Wombat.MamdaConcreteTradeRecap.getBlockVolume ()
Total volume of block trades today.
Returns
Implements Wombat.MamdaTradeRecap.
getBlockVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getBlockVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setBlockVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setBlockVolume (long blockVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setBlockVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setBlockVolume (double blockVolume)
getClosePrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getClosePrice ()
Today's closing price.
The closing price field is populated when official closing prices are sent by the feed after the session close.
Returns
Implements Wombat.MamdaTradeRecap.
getClosePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getClosePriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setClosePrice()
void Wombat.MamdaConcreteTradeRecap.setClosePrice (MamaPrice closePrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrCondStr()
string Wombat.MamdaConcreteTradeRecap.getCorrCondStr ()
getCorrCondStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrCondStrFieldState ()
setCorrCondStr()
void Wombat.MamdaConcreteTradeRecap.setCorrCondStr (string corrCondStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrPartId()
string Wombat.MamdaConcreteTradeRecap.getCorrPartId ()
getCorrPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrPartIdFieldState ()
setCorrPartId()
void Wombat.MamdaConcreteTradeRecap.setCorrPartId (string corrPartId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getCorrPrice ()
getCorrPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrPriceFieldState ()
setCorrPrice()
void Wombat.MamdaConcreteTradeRecap.setCorrPrice (MamaPrice corrPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrQualStr()
string Wombat.MamdaConcreteTradeRecap.getCorrQualStr ()
getCorrQualStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrQualStrFieldState ()
setCorrQualStr()
void Wombat.MamdaConcreteTradeRecap.setCorrQualStr (string corrQualStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrQualNativeStr()
string Wombat.MamdaConcreteTradeRecap.getCorrQualNativeStr ()
getCorrQualNativeStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrQualNativeStrFieldState ()
setCorrQualNativeStr()
void Wombat.MamdaConcreteTradeRecap.setCorrQualNativeStr (string corrQualNativeStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrSellersSaleDays()
long Wombat.MamdaConcreteTradeRecap.getCorrSellersSaleDays ()
getCorrSellersSaleDaysFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrSellersSaleDaysFieldState ()
setCorrSellersSaleDays()
void Wombat.MamdaConcreteTradeRecap.setCorrSellersSaleDays (long corrSellersSaleDays)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrStopStockInd()
char Wombat.MamdaConcreteTradeRecap.getCorrStopStockInd ()
getCorrStopStockIndFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrStopStockIndFieldState ()
setCorrStopStockInd()
void Wombat.MamdaConcreteTradeRecap.setCorrStopStockInd (char corrStopStockInd)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCancelTime()
DateTime Wombat.MamdaConcreteTradeRecap.getCancelTime ()
getCancelTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCancelTimeFieldState ()
setCancelTime()
void Wombat.MamdaConcreteTradeRecap.setCancelTime (DateTime cancelTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCorrVolume()
long Wombat.MamdaConcreteTradeRecap.getCorrVolume ()
getCorrVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrVolumeFieldState ()
setCorrVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setCorrVolume (long corrVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setCorrVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setCorrVolume (double corrVolume)
getEventSeqNum()
long Wombat.MamdaConcreteTradeRecap.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements Wombat.MamdaBasicEvent.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getEventSeqNumFieldState ()
Returns the field state.
Returns
Source sequence number Field State
Implements Wombat.MamdaBasicEvent.
setEventSeqNum()
void Wombat.MamdaConcreteTradeRecap.setEventSeqNum (long eventSeqNum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getEventTime()
DateTime Wombat.MamdaConcreteTradeRecap.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getEventTimeFieldState ()
Returns the field state.
Returns
Event Time Field State
Implements Wombat.MamdaBasicEvent.
setEventTime()
void Wombat.MamdaConcreteTradeRecap.setEventTime (DateTime eventTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getHighPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getHighPrice ()
Highest price paid for security during the trading day.
Returns
Implements Wombat.MamdaTradeRecap.
getHighPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getHighPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setHighPrice()
void Wombat.MamdaConcreteTradeRecap.setHighPrice (MamaPrice highPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLastPartId()
string Wombat.MamdaConcreteTradeRecap.getLastPartId ()
Trade participant ID.
This is typically an exchange ID, sometimes a market maker ID.
Returns
Implements Wombat.MamdaTradeRecap.
getTradeId()
string Wombat.MamdaConcreteTradeRecap.getTradeId ()
getCorrTradeId()
string Wombat.MamdaConcreteTradeRecap.getCorrTradeId ()
getOrigTradeId()
string Wombat.MamdaConcreteTradeRecap.getOrigTradeId ()
getLastPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLastPartIdFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
getTradeIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeIdFieldState ()
getOrigTradeIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigTradeIdFieldState ()
getCorrTradeIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCorrTradeIdFieldState ()
setLastPartId()
void Wombat.MamdaConcreteTradeRecap.setLastPartId (string lastPartId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setTradeId()
void Wombat.MamdaConcreteTradeRecap.setTradeId (string tradeId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setOrigTradeId()
void Wombat.MamdaConcreteTradeRecap.setOrigTradeId (string origTradeId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setCorrTradeId()
void Wombat.MamdaConcreteTradeRecap.setCorrTradeId (string corrTradeId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLastPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getLastPrice ()
Monetary value of an individual share of the security at the time of the trade.
Returns
Implements Wombat.MamdaTradeRecap.
getLastPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLastPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setLastPrice()
void Wombat.MamdaConcreteTradeRecap.setLastPrice (MamaPrice lastPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLastTime()
DateTime Wombat.MamdaConcreteTradeRecap.getLastTime ()
Time corresponding to the last trade, as reported by the feed The exact time of the trade may not be available, since rules governing trade reporting allow for a trades to be reported within a specified time limit.
Returns
Implements Wombat.MamdaTradeRecap.
getLastTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLastTimeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setLastTime()
void Wombat.MamdaConcreteTradeRecap.setLastTime (DateTime lastTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeDate()
DateTime Wombat.MamdaConcreteTradeRecap.getTradeDate ()
Implements Wombat.MamdaTradeRecap.
getTradeDateFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeDateFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTradeDate()
void Wombat.MamdaConcreteTradeRecap.setTradeDate (DateTime tradeDate)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getIrregPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getIrregPrice ()
Monetary value of an individual share of the security at the time of the last irregular trade.
Returns
Implements Wombat.MamdaTradeRecap.
getIrregPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getIrregPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setIrregPrice()
void Wombat.MamdaConcreteTradeRecap.setIrregPrice (MamaPrice irregPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getIrregVolume()
long Wombat.MamdaConcreteTradeRecap.getIrregVolume ()
Number of shares traded in a single transaction for an individual security.
Returns
Implements Wombat.MamdaTradeRecap.
getIrregVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getIrregVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setIrregVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setIrregVolume (long irregVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setIrregVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setIrregVolume (double irregVolume)
getIrregPartId()
string Wombat.MamdaConcreteTradeRecap.getIrregPartId ()
Trade participant ID for the last irregular trade.
This is typically an exchange ID, sometimes a market maker ID.
Returns
Implements Wombat.MamdaTradeRecap.
getIrregPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getIrregPartIdFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setIrregPartId()
void Wombat.MamdaConcreteTradeRecap.setIrregPartId (string irregPartId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getIrregTime()
DateTime Wombat.MamdaConcreteTradeRecap.getIrregTime ()
Time corresponding to the last irregular trade, as reported by the feed The exact time of the trade may not be available, since rules governing trade reporting allow for a trades to be reported within a specified time limit.
Returns
Implements Wombat.MamdaTradeRecap.
getIrregTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getIrregTimeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setIrregTime()
void Wombat.MamdaConcreteTradeRecap.setIrregTime (DateTime irregTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLastVolume()
long Wombat.MamdaConcreteTradeRecap.getLastVolume ()
Number of shares traded in a single transaction for an individual security.
Returns
Implements Wombat.MamdaTradeRecap.
getLastVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLastVolumeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setLastVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setLastVolume (long lastVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setLastVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setLastVolume (double lastVolume)
getLowPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getLowPrice ()
Lowest price paid for security during the trading day.
Returns
Implements Wombat.MamdaTradeRecap.
getLowPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLowPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setLowPrice()
void Wombat.MamdaConcreteTradeRecap.setLowPrice (MamaPrice lowPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getNetChange()
MamaPrice Wombat.MamdaConcreteTradeRecap.getNetChange ()
Get the change in price compared with the previous closing price
Returns
Change in price compared with the previous closing price (i.e. previous closing price - trade price).
Implements Wombat.MamdaTradeRecap.
getNetChangeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getNetChangeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setNetChange()
void Wombat.MamdaConcreteTradeRecap.setNetChange (MamaPrice netChange)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOpenPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getOpenPrice ()
The price of the first qualifying trade in the security during the current trading day.
Returns
Implements Wombat.MamdaTradeRecap.
getOpenPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOpenPriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOpenPrice()
void Wombat.MamdaConcreteTradeRecap.setOpenPrice (MamaPrice openPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigCondStr()
string Wombat.MamdaConcreteTradeRecap.getOrigCondStr ()
getOrigCondStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigCondStrFieldState ()
setOrigCondStr()
void Wombat.MamdaConcreteTradeRecap.setOrigCondStr (string origCondStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigPartId()
string Wombat.MamdaConcreteTradeRecap.getOrigPartId ()
getOrigPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigPartIdFieldState ()
setOrigPartId()
void Wombat.MamdaConcreteTradeRecap.setOrigPartId (string origPartId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigPrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getOrigPrice ()
getOrigPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigPriceFieldState ()
setOrigPrice()
void Wombat.MamdaConcreteTradeRecap.setOrigPrice (MamaPrice origPrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigQualStr()
string Wombat.MamdaConcreteTradeRecap.getOrigQualStr ()
getOrigQualStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigQualStrFieldState ()
setOrigQualStr()
void Wombat.MamdaConcreteTradeRecap.setOrigQualStr (string origQualStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigQualNativeStr()
string Wombat.MamdaConcreteTradeRecap.getOrigQualNativeStr ()
getOrigQualNativeStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigQualNativeStrFieldState ()
setOrigQualNativeStr()
void Wombat.MamdaConcreteTradeRecap.setOrigQualNativeStr (string origQualNativeStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigSellersSaleDays()
long Wombat.MamdaConcreteTradeRecap.getOrigSellersSaleDays ()
getOrigSellersSaleDaysFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigSellersSaleDaysFieldState ()
setOrigSellersSaleDays()
void Wombat.MamdaConcreteTradeRecap.setOrigSellersSaleDays (long origSellersSaleDays)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigStopStockInd()
char Wombat.MamdaConcreteTradeRecap.getOrigStopStockInd ()
getOrigStopStockIndFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigStopStockIndFieldState ()
setOrigStopStockInd()
void Wombat.MamdaConcreteTradeRecap.setOrigStopStockInd (char origStopStockInd)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigSeqNum()
long Wombat.MamdaConcreteTradeRecap.getOrigSeqNum ()
getOrigSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigSeqNumFieldState ()
setOrigSeqNum()
void Wombat.MamdaConcreteTradeRecap.setOrigSeqNum (long origSeqNum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrigVolume()
long Wombat.MamdaConcreteTradeRecap.getOrigVolume ()
getOrigVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrigVolumeFieldState ()
setOrigVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setOrigVolume (long origVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setOrigVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setOrigVolume (double origVolume)
getPctChange()
double Wombat.MamdaConcreteTradeRecap.getPctChange ()
Change in price as a percentage.
Returns
Implements Wombat.MamdaTradeRecap.
getPctChangeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getPctChangeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setPctChange()
void Wombat.MamdaConcreteTradeRecap.setPctChange (double pctChange)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getPrevCloseDate()
DateTime Wombat.MamdaConcreteTradeRecap.getPrevCloseDate ()
Date corresponding to PrevClosePrice.
getPrevClosePrice()
Returns
Implements Wombat.MamdaTradeRecap.
getPrevCloseDateFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getPrevCloseDateFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setPrevCloseDate()
void Wombat.MamdaConcreteTradeRecap.setPrevCloseDate (DateTime prevCloseDate)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getAdjPrevClose()
MamaPrice Wombat.MamdaConcreteTradeRecap.getAdjPrevClose ()
The previous close price adjusted by corporate actions, such as dividends and stock splits on the ex-date.
getPrevClosePrice()
Returns
The adjusted previous closing price.
Implements Wombat.MamdaTradeRecap.
getAdjPrevCloseFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getAdjPrevCloseFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setAdjPrevClose()
void Wombat.MamdaConcreteTradeRecap.setAdjPrevClose (MamaPrice adjPrevClose)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getPrevClosePrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getPrevClosePrice ()
The last qualifying trade price on the previous trading day.
This field may be copied from the close price field during the morning "roll" of records in the feedhandler, or it may be obtained from a secondary source, or it may be explicitly sent by the feed prior to the opening of trading for the current day.
Returns
Implements Wombat.MamdaTradeRecap.
getPrevClosePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getPrevClosePriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setPrevClosePrice()
void Wombat.MamdaConcreteTradeRecap.setPrevClosePrice (MamaPrice prevClosePrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getSellersSaleDays()
long Wombat.MamdaConcreteTradeRecap.getSellersSaleDays ()
getSellersSaleDaysFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSellersSaleDaysFieldState ()
setSellersSaleDays()
void Wombat.MamdaConcreteTradeRecap.setSellersSaleDays (long sellersSaleDays)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getStopStockInd()
char Wombat.MamdaConcreteTradeRecap.getStopStockInd ()
getStopStockIndFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getStopStockIndFieldState ()
setStopStockInd()
void Wombat.MamdaConcreteTradeRecap.setStopStockInd (char stopStockInd)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getSrcTime()
DateTime Wombat.MamdaConcreteTradeRecap.getSrcTime ()
Returns the source time.
Returns
Source time. Typically, the exchange generated feed
time stamp. This is often the same as the "event time",
because many feeds do not distinguish between the actual event
time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSrcTimeFieldState ()
Returns the field state.
Returns
Source time Field State
Implements Wombat.MamdaBasicEvent.
setSrcTime()
void Wombat.MamdaConcreteTradeRecap.setSrcTime (DateTime srcTime)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getStdDev()
double Wombat.MamdaConcreteTradeRecap.getStdDev ()
Standard deviation of last trade price of a security at the time it is disseminated.
Returns
Implements Wombat.MamdaTradeRecap.
getStdDevFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getStdDevFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setStdDev()
void Wombat.MamdaConcreteTradeRecap.setStdDev (double stdDev)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getStdDevSum()
double Wombat.MamdaConcreteTradeRecap.getStdDevSum ()
Implements Wombat.MamdaTradeRecap.
getStdDevSumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getStdDevSumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setStdDevSum()
void Wombat.MamdaConcreteTradeRecap.setStdDevSum (double stdDevSum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getStdDevSumSquares()
double Wombat.MamdaConcreteTradeRecap.getStdDevSumSquares ()
Implements Wombat.MamdaTradeRecap.
getStdDevSumSquaresFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getStdDevSumSquaresFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setStdDevSumSquares()
void Wombat.MamdaConcreteTradeRecap.setStdDevSumSquares (double stdDevSumSquares)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOrderId()
long Wombat.MamdaConcreteTradeRecap.getOrderId ()
Get the order id, if available.
Returns
The trade message unique order id number (if available).
Implements Wombat.MamdaTradeRecap.
getOrderIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOrderIdFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOrderId()
void Wombat.MamdaConcreteTradeRecap.setOrderId (long orderId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getSettlePrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getSettlePrice ()
Future's / Options settlement price.
Returns
Implements Wombat.MamdaTradeRecap.
getSettlePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSettlePriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setSettlePrice()
void Wombat.MamdaConcreteTradeRecap.setSettlePrice (MamaPrice settlePrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getSettleDate()
DateTime Wombat.MamdaConcreteTradeRecap.getSettleDate ()
Date corresponding to SettlePrice.
getSettlePrice()
Returns
Implements Wombat.MamdaTradeRecap.
getSettleDateFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSettleDateFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setSettleDate()
void Wombat.MamdaConcreteTradeRecap.setSettleDate (DateTime settleDate)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getShortSaleCircuitBreaker()
char Wombat.MamdaConcreteTradeRecap.getShortSaleCircuitBreaker ()
getShortSaleCircuitBreaker Returns the ShortSaleCircuitBreaker
Returns
the ShortSaleCircuitBreaker
Implements Wombat.MamdaTradeRecap.
getShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getShortSaleCircuitBreakerFieldState ()
Returns the FieldState, always MODIFIED.
Returns
the FieldState
Implements Wombat.MamdaTradeRecap.
setShortSaleCircuitBreaker()
void Wombat.MamdaConcreteTradeRecap.setShortSaleCircuitBreaker (char shortSaleCircuitBreaker)
Set the shortSaleCircuitBreaker
Parameters
shortSaleCircuitBreaker
getTotalValue()
double Wombat.MamdaConcreteTradeRecap.getTotalValue ()
Total value of all shares traded in a security at the time it is disseminated.
Calculated by the sum of multiplying the trade price by trade volume for each qualifying trade.
Returns
Implements Wombat.MamdaTradeRecap.
getTotalValueFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTotalValueFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTotalValue()
void Wombat.MamdaConcreteTradeRecap.setTotalValue (double totalValue)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOffExTotalValue()
double Wombat.MamdaConcreteTradeRecap.getOffExTotalValue ()
Total value of all shares traded off exchange in a security at the time it is disseminated.
Calculated by the sum of multiplying the trade price by trade volume for each qualifying trade.
Returns
Implements Wombat.MamdaTradeRecap.
getOffExTotalValueFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOffExTotalValueFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOffExTotalValue()
void Wombat.MamdaConcreteTradeRecap.setOffExTotalValue (double offExTotalValue)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOnExTotalValue()
double Wombat.MamdaConcreteTradeRecap.getOnExTotalValue ()
Total value of all shares traded on exchange in a security at the time it is disseminated.
Calculated by the sum of multiplying the trade price by trade volume for each qualifying trade.
Returns
Implements Wombat.MamdaTradeRecap.
getOnExTotalValueFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOnExTotalValueFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOnExTotalValue()
void Wombat.MamdaConcreteTradeRecap.setOnExTotalValue (double onExTotalValue)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeCondStr()
string Wombat.MamdaConcreteTradeRecap.getTradeCondStr ()
getTradeCondStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeCondStrFieldState ()
setTradeCondStr()
void Wombat.MamdaConcreteTradeRecap.setTradeCondStr (string tradeCondStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeCount()
long Wombat.MamdaConcreteTradeRecap.getTradeCount ()
The number of trades today.
Returns
Implements Wombat.MamdaTradeRecap.
getTradeCountFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeCountFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTradeCount()
void Wombat.MamdaConcreteTradeRecap.setTradeCount (long tradeCount)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeUnits()
string Wombat.MamdaConcreteTradeRecap.getTradeUnits ()
Implements Wombat.MamdaTradeRecap.
getTradeUnitsFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeUnitsFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTradeUnits()
void Wombat.MamdaConcreteTradeRecap.setTradeUnits (string tradeUnits)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLastSeqNum()
long Wombat.MamdaConcreteTradeRecap.getLastSeqNum ()
Implements Wombat.MamdaTradeRecap.
getLastSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLastSeqNumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setLastSeqNum()
void Wombat.MamdaConcreteTradeRecap.setLastSeqNum (long lastSeqNum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getHighSeqNum()
long Wombat.MamdaConcreteTradeRecap.getHighSeqNum ()
Implements Wombat.MamdaTradeRecap.
getHighSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getHighSeqNumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setHighSeqNum()
void Wombat.MamdaConcreteTradeRecap.setHighSeqNum (long highSeqNum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getLowSeqNum()
long Wombat.MamdaConcreteTradeRecap.getLowSeqNum ()
Implements Wombat.MamdaTradeRecap.
getLowSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getLowSeqNumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setLowSeqNum()
void Wombat.MamdaConcreteTradeRecap.setLowSeqNum (long lowSeqNum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTotalVolumeSeqNum()
long Wombat.MamdaConcreteTradeRecap.getTotalVolumeSeqNum ()
Implements Wombat.MamdaTradeRecap.
getTotalVolumeSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTotalVolumeSeqNumFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTotalVolumeSeqNum()
void Wombat.MamdaConcreteTradeRecap.setTotalVolumeSeqNum (long totalVolumeSeqNum)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getCurrencyCode()
string Wombat.MamdaConcreteTradeRecap.getCurrencyCode ()
Implements Wombat.MamdaTradeRecap.
getCurrencyCodeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getCurrencyCodeFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setCurrencyCode()
void Wombat.MamdaConcreteTradeRecap.setCurrencyCode (string currencyCode)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeDirection()
string Wombat.MamdaConcreteTradeRecap.getTradeDirection ()
Trade tick direction.
0 : No direction is currently known/available.
: Up tick.
: Down tick. 0+ : Unchanged; Previous move was up tick. 0- : Unchanged; Previous move was down tick. NA : Not applicable. (If it is meaningful to have such a value for some exchanges.)
Returns
Implements Wombat.MamdaTradeRecap.
getTradeDirectionFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeDirectionFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTradeDirection()
void Wombat.MamdaConcreteTradeRecap.setTradeDirection (string tradeDirection)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getSide()
string Wombat.MamdaConcreteTradeRecap.getSide ()
Returns the Aggressor side or TradeSide
AggressorSide: 0 : No AggressorSide is currently known/available. 1 or B : Buy 2 or S : Sell
TradeSide: TRADE_SIDE_UNKNOWN TRADE_SIDE_BUY TRADE_SIDE_SELL
Returns
Implements Wombat.MamdaTradeRecap.
getSideFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getSideFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setSide()
void Wombat.MamdaConcreteTradeRecap.setSide (string tradeSide)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradePartId()
string Wombat.MamdaConcreteTradeRecap.getTradePartId ()
getTradePartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradePartIdFieldState ()
setTradePartId()
void Wombat.MamdaConcreteTradeRecap.setTradePartId (string tradePartId)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradePrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getTradePrice ()
getTradePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradePriceFieldState ()
setTradePrice()
void Wombat.MamdaConcreteTradeRecap.setTradePrice (MamaPrice tradePrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeQualStr()
string Wombat.MamdaConcreteTradeRecap.getTradeQualStr ()
getTradeQualStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeQualStrFieldState ()
setTradeQualStr()
void Wombat.MamdaConcreteTradeRecap.setTradeQualStr (string tradeQualStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeQualNativeStr()
string Wombat.MamdaConcreteTradeRecap.getTradeQualNativeStr ()
getTradeQualNativeStrFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeQualNativeStrFieldState ()
setTradeQualNativeStr()
void Wombat.MamdaConcreteTradeRecap.setTradeQualNativeStr (string tradeQualNativeStr)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeVolume()
long Wombat.MamdaConcreteTradeRecap.getTradeVolume ()
getTradeVolumeFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeVolumeFieldState ()
setTradeVolume() [1/2]
void Wombat.MamdaConcreteTradeRecap.setTradeVolume (long tradeVolume)
Referenced by Wombat.MamdaTradeListener.populateRecap().
setTradeVolume() [2/2]
void Wombat.MamdaConcreteTradeRecap.setTradeVolume (double tradeVolume)
getVwap()
double Wombat.MamdaConcreteTradeRecap.getVwap ()
Volume-weighted average price of a security at the time it is disseminated.
Equivalent to dividing total value by total volume.
Returns
Implements Wombat.MamdaTradeRecap.
getVwapFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getVwapFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setVwap()
void Wombat.MamdaConcreteTradeRecap.setVwap (double vwap)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOffExVwap()
double Wombat.MamdaConcreteTradeRecap.getOffExVwap ()
Volume-weighted average off exchange price of a security at the time it is disseminated.
Equivalent to dividing total value by total volume.
Returns
Implements Wombat.MamdaTradeRecap.
getOffExVwapFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOffExVwapFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOffExVwap()
void Wombat.MamdaConcreteTradeRecap.setOffExVwap (double offExVwap)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOnExVwap()
double Wombat.MamdaConcreteTradeRecap.getOnExVwap ()
Volume-weighted average on exchange price of a security at the time it is disseminated.
Equivalent to dividing total value by total volume.
Returns
Implements Wombat.MamdaTradeRecap.
getOnExVwapFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOnExVwapFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOnExVwap()
void Wombat.MamdaConcreteTradeRecap.setOnExVwap (double onExVwap)
Referenced by Wombat.MamdaTradeListener.populateRecap().
IsIrregular()
bool Wombat.MamdaConcreteTradeRecap.IsIrregular ()
setIsIrregular()
void Wombat.MamdaConcreteTradeRecap.setIsIrregular (bool isIrregular)
Referenced by Wombat.MamdaTradeListener.populateRecap().
IsCancel()
bool Wombat.MamdaConcreteTradeRecap.IsCancel ()
setIsCancel()
void Wombat.MamdaConcreteTradeRecap.setIsCancel (bool isCancel)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getTradeExecVenue()
string Wombat.MamdaConcreteTradeRecap.getTradeExecVenue ()
Trade execution venue.
Unknown OnExchange OnExchangeOffBook OffExchange
Returns
Implements Wombat.MamdaTradeRecap.
getTradeExecVenueFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getTradeExecVenueFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setTradeExecVenue()
void Wombat.MamdaConcreteTradeRecap.setTradeExecVenue (string tradeExecVenue)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOffExchangeTradePrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getOffExchangeTradePrice ()
Monetary value of an individual off exchange share of the security at the time of the trade.
Returns
Implements Wombat.MamdaTradeRecap.
getOffExchangeTradePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOffExchangeTradePriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOffExchangeTradePrice()
void Wombat.MamdaConcreteTradeRecap.setOffExchangeTradePrice (MamaPrice offExTradePrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().
getOnExchangeTradePrice()
MamaPrice Wombat.MamdaConcreteTradeRecap.getOnExchangeTradePrice ()
Monetary value of an individual off exchange share of the security at the time of the trade.
Returns
Implements Wombat.MamdaTradeRecap.
getOnExchangeTradePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteTradeRecap.getOnExchangeTradePriceFieldState ()
Get the field state
Returns
Field State
Implements Wombat.MamdaTradeRecap.
setOnExchangeTradePrice()
void Wombat.MamdaConcreteTradeRecap.setOnExchangeTradePrice (MamaPrice onExTradePrice)
Referenced by Wombat.MamdaTradeListener.populateRecap().