OpenMAMDA C# API: Wombat.MamdaOptionChain Class Reference
Wombat.MamdaOptionChain Class Reference
MamdaOptionChain is a specialized class to represent market data option chains.
Public Member Functions
MamdaOptionChain (string symbol)
MamdaOptionChain Constructor.
void setSymbol (string symbol)
Set the underlying symbol for the option chain.
string getSymbol ()
Get the underlying symbol for the option chain.
void setUnderlyingQuoteListener (MamdaQuoteListener quoteListener)
Set the underlying quote listener information.
void setUnderlyingTradeListener (MamdaTradeListener tradeListener)
Set the underlying trade listener information.
MamdaQuoteListener getUnderlyingQuoteListener ()
Make the underlying quote listener available externally.
MamdaTradeListener getUnderlyingTradeListener ()
Make the underlying trade listener available externally.
MamdaOptionContract getContract (String contractSymbol)
Find an option contract by OPRA symbol.
SortedSet getExchanges ()
Return the superset of regional exchange identifiers for any option in this chain.
SortedSet getStrikePrices ()
Return the superset of strike prices for this chain.
void addContract (string contractSymbol, MamdaOptionContract contract)
Add an option contract.
void removeContract (string contractSymbol)
Remove an option contract.
double getAtTheMoney (MamdaOptionAtTheMoneyCompareType compareType)
Get the price of the option underlying.
bool getIsPriceWithinPercentOfMoney (double price, double percentage, MamdaOptionAtTheMoneyCompareType compareType)
Return whether the price is within a % of the money.
SortedSet getStrikesWithinPercent (double percentage, MamdaOptionAtTheMoneyCompareType compareType)
Determine the set of strike prices that are included in a given percentage range of the underlying price.
SortedSet getStrikesWithinRangeSize (int rangeLength, MamdaOptionAtTheMoneyCompareType compareType)
Determine the set of strike prices that are included in a given fixed size range of strikes surrounding the underlying price.
Iterator callIterator ()
Return an iterator over all call option contracts.
Iterator putIterator ()
Return an iterator over all put option contracts.
MamdaOptionExpirationDateSet getAllExpirations ()
Return a set of MamdaOptionExpirationDateSet.
void dump ()
Print the contents of the chain to standard out.
Detailed Description
MamdaOptionChain is a specialized class to represent market data option chains.
The class has capabilities to store the current state of an entire option chain, or a subset of the chain.
Constructor & Destructor Documentation
MamdaOptionChain()
Wombat.MamdaOptionChain.MamdaOptionChain (string symbol)
MamdaOptionChain Constructor.
Parameters
symbol The underlying symbol.
References Wombat.MamdaOptionChain.setSymbol().
Member Function Documentation
setSymbol()
void Wombat.MamdaOptionChain.setSymbol (string symbol)
Set the underlying symbol for the option chain.
Parameters
symbol The underlying symbol.
Referenced by Wombat.MamdaOptionChain.MamdaOptionChain().
getSymbol()
string Wombat.MamdaOptionChain.getSymbol ()
Get the underlying symbol for the option chain.
Returns
The underlying symbol for the option chain.
Referenced by Wombat.MamdaOptionChainView.getSymbol().
setUnderlyingQuoteListener()
void Wombat.MamdaOptionChain.setUnderlyingQuoteListener (MamdaQuoteListener quoteListener)
Set the underlying quote listener information.
MamdaOptionChain does not use this class itself, but related classes might (e.g., MamdaOptionChainView).
Parameters
quoteListener The quote listener for the chain.
setUnderlyingTradeListener()
void Wombat.MamdaOptionChain.setUnderlyingTradeListener (MamdaTradeListener tradeListener)
Set the underlying trade listener information.
MamdaOptionChain uses this class to implement the atTheMoney() method. Related classes might (e.g., MamdaOptionChainView) use it for other reasons.
Parameters
tradeListener The trade listener for the chain.
getUnderlyingQuoteListener()
MamdaQuoteListener Wombat.MamdaOptionChain.getUnderlyingQuoteListener ()
Make the underlying quote listener available externally.
Returns
The quote listener for the chain.
getUnderlyingTradeListener()
MamdaTradeListener Wombat.MamdaOptionChain.getUnderlyingTradeListener ()
Make the underlying trade listener available externally.
Returns
The trade listener for the chain.
getContract()
MamdaOptionContract Wombat.MamdaOptionChain.getContract (String contractSymbol)
Find an option contract by OPRA symbol.
Parameters
contractSymbol
Returns
MamdaOptionContract The contract object representing the option.
References Wombat.Containers.HashMap.valueOf().
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
getExchanges()
SortedSet Wombat.MamdaOptionChain.getExchanges ()
Return the superset of regional exchange identifiers for any option in this chain.
Each element in the set is a String object.
Returns
Set of regional exchange identifiers.
getStrikePrices()
SortedSet Wombat.MamdaOptionChain.getStrikePrices ()
Return the superset of strike prices for this chain.
Each element in the set is a Double object.
Returns
Set of strike prices for the chain.
addContract()
void Wombat.MamdaOptionChain.addContract (string contractSymbol, MamdaOptionContract contract)
Add an option contract.
This method would not normally be invoked by a user application. Rather, MamdaOptionChainListener would be most likely to call this method.
Parameters
contractSymbol The option instrument symbol.
contract The Mamda option contract representation.
References Wombat.Containers.TreeSet.add(), Wombat.MamdaOptionStrikeSet.getCallSet(), Wombat.MamdaOptionContract.getExchange(), Wombat.MamdaOptionContract.getExpireDate(), Wombat.MamdaOptionContract.getPutCall(), Wombat.MamdaOptionStrikeSet.getPutSet(), Wombat.MamdaOptionContract.getStrikePrice(), Wombat.MamdaOptionExchangeUtils.isBbo(), Wombat.MamdaOptionExchangeUtils.isWombatBbo(), Wombat.Containers.HashMap.put(), Wombat.Containers.TreeMap.put(), Wombat.MamdaOptionContractSet.setBboContract(), Wombat.MamdaOptionContractSet.setExchangeContract(), Wombat.MamdaOptionContractSet.setWombatBboContract(), and Wombat.Containers.TreeMap.valueOf().
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
removeContract()
void Wombat.MamdaOptionChain.removeContract (string contractSymbol)
Remove an option contract.
This method would not normally be invoked by a user application. Rather, MamdaOptionChainListener would be most likely to call this method.
Parameters
contractSymbol
getAtTheMoney()
double Wombat.MamdaOptionChain.getAtTheMoney (MamdaOptionAtTheMoneyCompareType compareType)
Get the price of the option underlying.
Determine the underlying price ("at the money"), based on the mode of calculation.
Parameters
compareType The mode of calculation (MamdaOptionAtTheMoneyCompareType)
Returns
The price of the underlying.
References Wombat.MamdaQuoteListener.getAskPrice(), Wombat.MamdaQuoteListener.getBidPrice(), and Wombat.MamdaTradeListener.getLastPrice().
Referenced by Wombat.MamdaOptionChain.getIsPriceWithinPercentOfMoney(), Wombat.MamdaOptionChain.getStrikesWithinPercent(), and Wombat.MamdaOptionChain.getStrikesWithinRangeSize().
getIsPriceWithinPercentOfMoney()
bool Wombat.MamdaOptionChain.getIsPriceWithinPercentOfMoney (double price, double percentage, MamdaOptionAtTheMoneyCompareType compareType)
Return whether the price is within a % of the money.
Determine whether some price (e.g. a strike price) is within a given percentage range of the underlying (at the money) price.
Parameters
price The strike price to check.
percentage What % to check the strike price against.
compareType What price we are checking against (see MamdaOptionAtTheMoneyCompareType)
Returns
Whether the price is within % of the money.
References Wombat.MamdaOptionChain.getAtTheMoney().
getStrikesWithinPercent()
SortedSet Wombat.MamdaOptionChain.getStrikesWithinPercent (double percentage, MamdaOptionAtTheMoneyCompareType compareType)
Determine the set of strike prices that are included in a given percentage range of the underlying price.
If there are no strikes within the percentage range, then both strike prices are set to zero. MamdaOptionAtTheMoneyCompareType
Parameters
percentage The percentage range of the underlying price.
compareType Which underlying price to compare to.
Returns
Set of strike prices.
References Wombat.MamdaOptionChain.getAtTheMoney(), and Wombat.Containers.TreeSet.subSet().
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
getStrikesWithinRangeSize()
SortedSet Wombat.MamdaOptionChain.getStrikesWithinRangeSize (int rangeLength, MamdaOptionAtTheMoneyCompareType compareType)
Determine the set of strike prices that are included in a given fixed size range of strikes surrounding the underlying price.
If rangeLen is odd, then the strike price nearest to the underlying price is treated as a higher strike price. If rangeLen is even and the underlying price is exactly equal to a strike price, then that strike price is treated as a higher strike price. MamdaOptionAtTheMoneyCompareType
Parameters
rangeLength Number of strike prices to include in result.
compareType What underlying price to use as a comparator.
Returns
Resulting set of strike prices.
References Wombat.Containers.SortedSet.first(), Wombat.MamdaOptionChain.getAtTheMoney(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.TreeSet.iterator(), Wombat.Containers.Iterator.next(), and Wombat.Containers.TreeSet.subSet().
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
callIterator()
Iterator Wombat.MamdaOptionChain.callIterator ()
Return an iterator over all call option contracts.
The type of object that Iterator.next() returns is MamdaOptionContract.
Returns
The iterator of call options.
References Wombat.Containers.TreeSet.iterator().
putIterator()
Iterator Wombat.MamdaOptionChain.putIterator ()
Return an iterator over all put option contracts.
The type of object that Iterator.next() returns is MamdaOptionContract.
Returns
References Wombat.Containers.TreeSet.iterator().
getAllExpirations()
MamdaOptionExpirationDateSet Wombat.MamdaOptionChain.getAllExpirations ()
Return a set of MamdaOptionExpirationDateSet.
Returns
Set of expiration dates.
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate().
dump()
void Wombat.MamdaOptionChain.dump ()
Print the contents of the chain to standard out.
References Wombat.MamdaOptionContract.getExchange(), Wombat.MamdaOptionContract.getExpireDate(), Wombat.MamdaOptionContract.getStrikePrice(), Wombat.MamdaOptionContract.getSymbol(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.TreeSet.iterator(), and Wombat.Containers.Iterator.next().