OpenMAMDA C# API: Wombat.MamdaBookAtomicListener Class Reference
Wombat.MamdaBookAtomicListener Class Reference
Inherits Wombat.MamdaMsgListener, Wombat.MamdaBookAtomicLevel, Wombat.MamdaBookAtomicLevelEntry, and Wombat.MamdaBookAtomicGap.
Public Member Functions
void addBookHandler (MamdaBookAtomicBookHandler handler)
void addLevelHandler (MamdaBookAtomicLevelHandler handler)
void addLevelEntryHandler (MamdaBookAtomicLevelEntryHandler handler)
string getSymbol ()
Symbol.
string getPartId ()
Participant ID.
DateTime getSrcTime ()
Returns the source time.
DateTime getActivityTime ()
DateTime getLineTime ()
Line time.
DateTime getSendTime ()
Send time.
long getEventSeqNum ()
DateTime getEventTime ()
MamdaFieldState getSymbolFieldState ()
Returns the field state.
MamdaFieldState getPartIdFieldState ()
Returns the field state.
MamdaFieldState getSrcTimeFieldState ()
Returns the field state.
MamdaFieldState getActivityTimeFieldState ()
Returns the field state.
MamdaFieldState getLineTimeFieldState ()
Returns the field state.
MamdaFieldState getSendTimeFieldState ()
Returns the field state.
MamdaFieldState getEventSeqNumFieldState ()
Returns the field state.
MamdaFieldState getEventTimeFieldState ()
Returns the field state.
long getPriceLevelNumLevels ()
Return the number of price levels in the order book update.
long getPriceLevelNum ()
Return at which position this level is within an update containing a number of levels.
double getPriceLevelPrice ()
Return the price for this price level.
MamaPrice getPriceLevelMamaPrice ()
Return the Mamaprice for this price level.
double getPriceLevelSize ()
Return the number of order entries comprising this price level.
long getPriceLevelSizeChange ()
Aggregate size at current price level.
char getPriceLevelAction ()
The action to apply to the orderbook for this price level.
char getPriceLevelSide ()
Side of book at current price level.
DateTime getPriceLevelTime ()
Time of order book price level.
double getPriceLevelNumEntries ()
Number of order book entries at current price level.
long getPriceLevelActNumEntries ()
??
char getPriceLevelEntryAction ()
Order book entry action to apply to the full order book.
IntPtr getPriceLevelEntryIdIntPtr ()
string getPriceLevelEntryId ()
Order book entry Id.
long getPriceLevelEntrySize ()
Return the order book entry size.
DateTime getPriceLevelEntryTime ()
Return the time of order book entry update.
long getBeginGapSeqNum ()
Beginning sequence number in a detected gap event.<>
long getEndGapSeqNum ()
Ending sequence number in a detected gap event.<>
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Member Function Documentation
addBookHandler()
void Wombat.MamdaBookAtomicListener.addBookHandler (MamdaBookAtomicBookHandler handler)
addLevelHandler()
void Wombat.MamdaBookAtomicListener.addLevelHandler (MamdaBookAtomicLevelHandler handler)
addLevelEntryHandler()
void Wombat.MamdaBookAtomicListener.addLevelEntryHandler (MamdaBookAtomicLevelEntryHandler handler)
getSymbol()
string Wombat.MamdaBookAtomicListener.getSymbol ()
Symbol.
This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements Wombat.MamdaBasicRecap.
getPartId()
string Wombat.MamdaBookAtomicListener.getPartId ()
Participant ID.
This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements Wombat.MamdaBasicRecap.
getSrcTime()
DateTime Wombat.MamdaBookAtomicListener.getSrcTime ()
Returns the source time.
Returns
Source time. Typically, the exchange generated feed
time stamp. This is often the same as the "event time",
because many feeds do not distinguish between the actual event
time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getActivityTime()
DateTime Wombat.MamdaBookAtomicListener.getActivityTime ()
Returns
Activity time. A feed handler generated time stamp representing when the data item was last updated.
Implements Wombat.MamdaBasicEvent.
getLineTime()
DateTime Wombat.MamdaBookAtomicListener.getLineTime ()
Line time.
A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements Wombat.MamdaBasicRecap.
getSendTime()
DateTime Wombat.MamdaBookAtomicListener.getSendTime ()
Send time.
A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware). See MAMA API: MamaDateTime::currentTime()).
Implements Wombat.MamdaBasicRecap.
getEventSeqNum()
long Wombat.MamdaBookAtomicListener.getEventSeqNum ()
Returns
Source sequence number. The exchange generated sequence number.
Implements Wombat.MamdaBasicEvent.
getEventTime()
DateTime Wombat.MamdaBookAtomicListener.getEventTime ()
Returns
Event time. Typically, when the event actually occurred. This is often the same as the "source time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements Wombat.MamdaBasicEvent.
getSymbolFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getSymbolFieldState ()
Returns the field state.
Returns
Symbol Field State
Implements Wombat.MamdaBasicRecap.
getPartIdFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getPartIdFieldState ()
Returns the field state.
Returns
Participant ID Field State
Implements Wombat.MamdaBasicRecap.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getSrcTimeFieldState ()
Returns the field state.
Returns
Source time Field State
Implements Wombat.MamdaBasicEvent.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getActivityTimeFieldState ()
Returns the field state.
Returns
Activity time Field State
Implements Wombat.MamdaBasicEvent.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getLineTimeFieldState ()
Returns the field state.
Returns
Line Time Field State
Implements Wombat.MamdaBasicRecap.
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getSendTimeFieldState ()
Returns the field state.
Returns
Send time Field State
Implements Wombat.MamdaBasicRecap.
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getEventSeqNumFieldState ()
Returns the field state.
Returns
Source sequence number Field State
Implements Wombat.MamdaBasicEvent.
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaBookAtomicListener.getEventTimeFieldState ()
Returns the field state.
Returns
Event Time Field State
Implements Wombat.MamdaBasicEvent.
getPriceLevelNumLevels()
long Wombat.MamdaBookAtomicListener.getPriceLevelNumLevels ()
Return the number of price levels in the order book update.
Returns
The number of price levels.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelNum()
long Wombat.MamdaBookAtomicListener.getPriceLevelNum ()
Return at which position this level is within an update containing a number of levels.
(i.e. level m of n levels in the update)
returns>The position of this level in the update received.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelPrice()
double Wombat.MamdaBookAtomicListener.getPriceLevelPrice ()
Return the price for this price level.
Returns
The price level price.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelMamaPrice()
MamaPrice Wombat.MamdaBookAtomicListener.getPriceLevelMamaPrice ()
Return the Mamaprice for this price level.
Returns
The price level Mama price.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelSize()
double Wombat.MamdaBookAtomicListener.getPriceLevelSize ()
Return the number of order entries comprising this price level.
Returns
The number of entries in this price level.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelSizeChange()
long Wombat.MamdaBookAtomicListener.getPriceLevelSizeChange ()
Aggregate size at current price level.
Returns
The aggregate size at the current price level.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelAction()
char Wombat.MamdaBookAtomicListener.getPriceLevelAction ()
The action to apply to the orderbook for this price level.
Can have a value of: A : Add a new price level U : Update an existing price level D : Delete an existing price level C : Closing information for price level (often treat the same as Update).
Returns
The price level action.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelSide()
char Wombat.MamdaBookAtomicListener.getPriceLevelSide ()
Side of book at current price level.
B : Bid side. Same as 'buy' side. A : Ask side. Same as 'sell' side.
Returns
The price level side.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelTime()
DateTime Wombat.MamdaBookAtomicListener.getPriceLevelTime ()
Time of order book price level.
Returns
The time of the orderbook price level.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelNumEntries()
double Wombat.MamdaBookAtomicListener.getPriceLevelNumEntries ()
Number of order book entries at current price level.
Returns
The number of entries at the current price level.
Implements Wombat.MamdaBookAtomicLevel.
getPriceLevelActNumEntries()
long Wombat.MamdaBookAtomicListener.getPriceLevelActNumEntries ()
??
Implements Wombat.MamdaBookAtomicLevelEntry.
getPriceLevelEntryAction()
char Wombat.MamdaBookAtomicListener.getPriceLevelEntryAction ()
Order book entry action to apply to the full order book.
A : Add entry to the price level. U : Update existing entry in the price level. D : Delete existing entry from the price level.
Returns
The orderbook entry action.
Implements Wombat.MamdaBookAtomicLevelEntry.
getPriceLevelEntryIdIntPtr()
IntPtr Wombat.MamdaBookAtomicListener.getPriceLevelEntryIdIntPtr ()
getPriceLevelEntryId()
string Wombat.MamdaBookAtomicListener.getPriceLevelEntryId ()
Order book entry Id.
(order ID, participant ID, etc.)
Returns
The entry id
Implements Wombat.MamdaBookAtomicLevelEntry.
getPriceLevelEntrySize()
long Wombat.MamdaBookAtomicListener.getPriceLevelEntrySize ()
Return the order book entry size.
Returns
Order book entry size
Implements Wombat.MamdaBookAtomicLevelEntry.
getPriceLevelEntryTime()
DateTime Wombat.MamdaBookAtomicListener.getPriceLevelEntryTime ()
Return the time of order book entry update.
Returns
Time of order book entry update.
Implements Wombat.MamdaBookAtomicLevelEntry.
getBeginGapSeqNum()
long Wombat.MamdaBookAtomicListener.getBeginGapSeqNum ()
Beginning sequence number in a detected gap event.<>
Implements Wombat.MamdaBookAtomicGap.
getEndGapSeqNum()
long Wombat.MamdaBookAtomicListener.getEndGapSeqNum ()
Ending sequence number in a detected gap event.<>
Implements Wombat.MamdaBookAtomicGap.
onMsg()
void Wombat.MamdaBookAtomicListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Parameters
subscription The MamdaSubscription to which this listener was registered.
msg The MamaMsg received by the underlying MAMA API and which resulted in this callback being invoked.
msgType The message type. e.g. INITIAL, RECAP, UPDATE etc.
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaOrderBookFields.ACTIVITY_TIME, Wombat.MamdaOrderBookFields.BOOK_TIME, Wombat.MamdaOrderBookFields.ENTRY_ACTION, Wombat.MamdaOrderBookFields.ENTRY_ID, Wombat.MamdaOrderBookFields.ENTRY_SIZE, Wombat.MamdaOrderBookFields.ENTRY_TIME, Wombat.MamdaOrderBookFields.getHasVectorFields(), Wombat.MamdaOrderBookFields.getNumEntryFields(), Wombat.MamdaOrderBookFields.getNumLevelFields(), Wombat.MamdaOrderBookFields.isSet(), Wombat.MamdaOrderBookFields.LINE_TIME, Wombat.MamdaOrderBookFields.NUM_LEVELS, Wombat.MamdaBookAtomicBookHandler.onBookAtomicBeginBook(), Wombat.MamdaBookAtomicBookHandler.onBookAtomicClear(), Wombat.MamdaBookAtomicBookHandler.onBookAtomicEndBook(), Wombat.MamdaBookAtomicBookHandler.onBookAtomicGap(), Wombat.MamdaBookAtomicLevelHandler.onBookAtomicLevelDelta(), Wombat.MamdaBookAtomicLevelEntryHandler.onBookAtomicLevelEntryDelta(), Wombat.MamdaBookAtomicLevelEntryHandler.onBookAtomicLevelEntryRecap(), Wombat.MamdaBookAtomicLevelHandler.onBookAtomicLevelRecap(), Wombat.MamdaOrderBookFields.PART_ID, Wombat.MamdaOrderBookFields.PL_ACTION, Wombat.MamdaOrderBookFields.PL_ENTRIES, Wombat.MamdaOrderBookFields.PL_ENTRY, Wombat.MamdaOrderBookFields.PL_NUM_ATTACH, Wombat.MamdaOrderBookFields.PL_NUM_ENTRIES, Wombat.MamdaOrderBookFields.PL_PRICE, Wombat.MamdaOrderBookFields.PL_SIDE, Wombat.MamdaOrderBookFields.PL_SIZE, Wombat.MamdaOrderBookFields.PL_SIZE_CHANGE, Wombat.MamdaOrderBookFields.PL_TIME, Wombat.MamdaOrderBookFields.PRICE_LEVEL, Wombat.MamdaOrderBookFields.PRICE_LEVELS, Wombat.MamdaOrderBookFields.SRC_TIME, and Wombat.MamdaCommonFields.SYMBOL.