OpenMAMDA C# API: Wombat.MamdaOrderBookPriceLevel Class Reference
Wombat.MamdaOrderBookPriceLevel Class Reference
Inherits IEnumerable.
Public Types
enum Actions : sbyte { Actions.Add = (sbyte)'A', Actions.Update = (sbyte)'U', Actions.Delete = (sbyte)'D', Actions.Unknown = (sbyte)'Z' }
An enumeration for book price level actions.
enum Sides : sbyte { Sides.Bid = (sbyte)'B', Sides.Ask = (sbyte)'A', Sides.Unknown = (sbyte)'U' }
Public Member Functions
MamdaOrderBookPriceLevel ()
Default constructor.
MamdaOrderBookPriceLevel (MamdaOrderBookPriceLevel copy)
Construct a price level object which is a shallow copy of the original.
void copy (MamdaOrderBookPriceLevel copy)
Copy a price level object which is an exact and deep copy of the original.
void setPrice (MamaPrice price)
void setSize (long size)
void setSizeChange (long size)
void setNumEntries (int numEntries)
void setSide (Sides side)
void setAction (Actions action)
void setTime (DateTime time)
void setDetails (MamdaOrderBookPriceLevel level)
Take the details from
void addEntry (MamdaOrderBookEntry entry)
Add a new order book entry to the price level.
void updateEntry (MamdaOrderBookEntry entry)
Update the details of an existing entry in the level.
void removeEntry (MamdaOrderBookEntry entry)
Remove an order book entry from the price level.
IEnumerator GetEnumerator ()
Returns a
void checkNotExist (MamdaOrderBookEntry entry)
If the provided order book entry exists in the price level a
void markAllDeleted ()
Mark everything in this price level as deleted, including entries.
void setAsDifference (MamdaOrderBookPriceLevel lhs, MamdaOrderBookPriceLevel rhs)
MamaPrice getPrice ()
Return the price for this level.
long getSize ()
Return the total size (across all entries) for this level.
long getSizeChange ()
Return the size change for this (presumably delta) level.
int getNumEntries ()
Return the actual number of entries for this level.
Sides getSide ()
Return the side (bid/ask) of the book for this level.
Actions getAction ()
Return the action for this price level.
bool hasTime ()
DateTime getTime ()
Return the time stamp for when the price level was last updated.
void assertEqual (MamdaOrderBookPriceLevel rhs)
Order book price level equality verification.
Static Public Member Functions
static void setStrictChecking (bool strict)
Enforce strict checking of order book modifications (at the expense of some performance).
Detailed Description
Member Enumeration Documentation
Actions
enum Wombat.MamdaOrderBookPriceLevel.Actions : sbyte strong
An enumeration for book price level actions.
Price level actions differ from entry actions because, for example, a price level message with Actions.Add may consist of entries with Actions.Add, Actions.Update or Actions.Delete.
Enumerator
Add
A new price level
Update
Updated price level.
Delete
Deleted price level.
Unknown
Unknown action (error).
Sides
enum Wombat.MamdaOrderBookPriceLevel.Sides : sbyte strong
Enumerator
Bid
Bid (buy) side.
Ask
Ask (sell) side.
Unknown
Unknown side (error).
Constructor & Destructor Documentation
MamdaOrderBookPriceLevel() [1/2]
Wombat.MamdaOrderBookPriceLevel.MamdaOrderBookPriceLevel ()
Default constructor.
MamdaOrderBookPriceLevel() [2/2]
Wombat.MamdaOrderBookPriceLevel.MamdaOrderBookPriceLevel (MamdaOrderBookPriceLevel copy)
Construct a price level object which is a shallow copy of the original.
Parameters
copy The MamdaOrderBookPriceLevel to copy.
Member Function Documentation
copy()
void Wombat.MamdaOrderBookPriceLevel.copy (MamdaOrderBookPriceLevel copy)
Copy a price level object which is an exact and deep copy of the original.
Parameters
copy The MamdaOrderBookPriceLevel to copy.
References Wombat.MamdaOrderBookEntry.copy(), Wombat.MamdaOrderBookPriceLevel.setAction(), Wombat.MamdaOrderBookPriceLevel.setNumEntries(), Wombat.MamdaOrderBookPriceLevel.setPrice(), Wombat.MamdaOrderBookPriceLevel.setSide(), Wombat.MamdaOrderBookPriceLevel.setSize(), Wombat.MamdaOrderBookPriceLevel.setSizeChange(), and Wombat.MamdaOrderBookPriceLevel.setTime().
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
setPrice()
void Wombat.MamdaOrderBookPriceLevel.setPrice (MamaPrice price)
Parameters
price
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), and Wombat.MamdaOrderBookListener.onMsg().
setSize()
void Wombat.MamdaOrderBookPriceLevel.setSize (long size)
Parameters
size
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
setSizeChange()
void Wombat.MamdaOrderBookPriceLevel.setSizeChange (long size)
Parameters
size
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
setNumEntries()
void Wombat.MamdaOrderBookPriceLevel.setNumEntries (int numEntries)
Parameters
numEntries
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
setSide()
void Wombat.MamdaOrderBookPriceLevel.setSide (Sides side)
Parameters
side
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
setAction()
void Wombat.MamdaOrderBookPriceLevel.setAction (Actions action)
Parameters
action
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
setTime()
void Wombat.MamdaOrderBookPriceLevel.setTime (DateTime time)
Parameters
time
Referenced by Wombat.MamdaOrderBookPriceLevel.copy(), and Wombat.MamdaOrderBookListener.onMsg().
setDetails()
void Wombat.MamdaOrderBookPriceLevel.setDetails (MamdaOrderBookPriceLevel level)
Take the details from
levelcode> and apply them to this level This does not update entries within the level, only information pertaining to the level itself. It is intended that this method should not be used externally to the API.
Parameters
level The price level object from which the details are being obtained.
addEntry()
void Wombat.MamdaOrderBookPriceLevel.addEntry (MamdaOrderBookEntry entry)
Add a new order book entry to the price level.
Parameters
entry The new entry to be added to the level.
References Wombat.MamdaOrderBookPriceLevel.checkNotExist().
Referenced by Wombat.MamdaOrderBookListener.onMsg(), and Wombat.MamdaOrderBookPriceLevel.setAsDifference().
updateEntry()
void Wombat.MamdaOrderBookPriceLevel.updateEntry (MamdaOrderBookEntry entry)
Update the details of an existing entry in the level.
Parameters
entry An instance of
MamdaOrderBookEntry
with the new details for the entry in the level.
References Wombat.MamdaOrderBookEntry.equalId(), Wombat.MamdaOrderBookEntry.getId(), and Wombat.MamdaOrderBookEntry.setDetails().
Referenced by Wombat.MamdaOrderBookPriceLevel.setAsDifference().
removeEntry()
void Wombat.MamdaOrderBookPriceLevel.removeEntry (MamdaOrderBookEntry entry)
Remove an order book entry from the price level.
MamdaOrderBookEntry
Parameters
entry The entry which is to be removed from the price level.
References Wombat.MamdaOrderBookEntry.equalId(), and Wombat.MamdaOrderBookEntry.getId().
GetEnumerator()
IEnumerator Wombat.MamdaOrderBookPriceLevel.GetEnumerator ()
Returns a
System.Collections.IEnumerator for all entries within this level. Price Level entries are represented by the MamdaOrderBookEntry class.
Returns
The enumerator for the price level entries
checkNotExist()
void Wombat.MamdaOrderBookPriceLevel.checkNotExist (MamdaOrderBookEntry entry)
If the provided order book entry exists in the price level a
MamdaOrderBookException exception is thrown. Otherwise the method simply returns.
Parameters
entry The entry whose presence in the level is being determined.
Exceptions
MamdaOrderBookException Throws MamdaOrderBookException if the entry is found in the price
References Wombat.MamdaOrderBookEntry.equalId(), and Wombat.MamdaOrderBookEntry.getId().
Referenced by Wombat.MamdaOrderBookPriceLevel.addEntry().
markAllDeleted()
void Wombat.MamdaOrderBookPriceLevel.markAllDeleted ()
Mark everything in this price level as deleted, including entries.
References Wombat.MamdaOrderBookPriceLevel.getSize(), Wombat.MamdaOrderBookEntry.setAction(), Wombat.MamdaOrderBookPriceLevel.setAction(), Wombat.MamdaOrderBookPriceLevel.setNumEntries(), Wombat.MamdaOrderBookEntry.setSize(), Wombat.MamdaOrderBookPriceLevel.setSize(), and Wombat.MamdaOrderBookPriceLevel.setSizeChange().
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
setAsDifference()
void Wombat.MamdaOrderBookPriceLevel.setAsDifference (MamdaOrderBookPriceLevel lhs, MamdaOrderBookPriceLevel rhs)
Parameters
lhs
rhs
References Wombat.MamdaOrderBookPriceLevel.addEntry(), Wombat.MamdaOrderBookEntry.getId(), Wombat.MamdaOrderBookPriceLevel.getNumEntries(), Wombat.MamdaOrderBookPriceLevel.getPrice(), Wombat.MamdaOrderBookPriceLevel.getSide(), Wombat.MamdaOrderBookEntry.getSize(), Wombat.MamdaOrderBookPriceLevel.getSize(), Wombat.MamdaOrderBookPriceLevel.getTime(), Wombat.MamdaOrderBookEntry.setAction(), Wombat.MamdaOrderBookPriceLevel.setAction(), Wombat.MamdaOrderBookPriceLevel.setNumEntries(), Wombat.MamdaOrderBookPriceLevel.setSide(), Wombat.MamdaOrderBookPriceLevel.setSize(), Wombat.MamdaOrderBookPriceLevel.setSizeChange(), and Wombat.MamdaOrderBookPriceLevel.updateEntry().
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
getPrice()
MamaPrice Wombat.MamdaOrderBookPriceLevel.getPrice ()
Return the price for this level.
Returns
The price for this level.
Referenced by Wombat.MamdaOrderBookPriceLevel.setAsDifference(), and Wombat.MamdaOrderBook.setStrictChecking().
getSize()
long Wombat.MamdaOrderBookPriceLevel.getSize ()
Return the total size (across all entries) for this level.
Returns
The total size for this level.
Referenced by Wombat.MamdaOrderBookPriceLevel.markAllDeleted(), Wombat.MamdaOrderBookPriceLevel.setAsDifference(), and Wombat.MamdaOrderBook.setStrictChecking().
getSizeChange()
long Wombat.MamdaOrderBookPriceLevel.getSizeChange ()
Return the size change for this (presumably delta) level.
This attribute is only of interest for delta order books. For full order books, this field will be equal to the size of the price level.
Returns
The changed size for this level.
getNumEntries()
int Wombat.MamdaOrderBookPriceLevel.getNumEntries ()
Return the actual number of entries for this level.
The actual number of entries may not equate to the number of entries that can be iterated over if: (a) the feed does not provide the actual entries, or (b) the price level is just a delta.
Returns
The actual number of entries for this level.
Referenced by Wombat.MamdaOrderBookPriceLevel.setAsDifference(), and Wombat.MamdaOrderBook.setStrictChecking().
getSide()
Sides Wombat.MamdaOrderBookPriceLevel.getSide ()
Return the side (bid/ask) of the book for this level.
Returns
The side of the book for this level.
Referenced by Wombat.MamdaOrderBook.addLevel(), Wombat.MamdaOrderBook.deleteLevel(), Wombat.MamdaOrderBookPriceLevel.setAsDifference(), Wombat.MamdaOrderBook.setStrictChecking(), and Wombat.MamdaOrderBook.updateLevel().
getAction()
Actions Wombat.MamdaOrderBookPriceLevel.getAction ()
Return the action for this price level.
All price levels for a full book are marked with mActionADD.
Returns
The action for this level.
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
hasTime()
bool Wombat.MamdaOrderBookPriceLevel.hasTime ()
Returns
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
getTime()
DateTime Wombat.MamdaOrderBookPriceLevel.getTime ()
Return the time stamp for when the price level was last updated.
Returns
The time stamp for when the price level was last updated.
Referenced by Wombat.MamdaOrderBookListener.onMsg(), Wombat.MamdaOrderBookPriceLevel.setAsDifference(), and Wombat.MamdaOrderBook.setStrictChecking().
assertEqual()
void Wombat.MamdaOrderBookPriceLevel.assertEqual (MamdaOrderBookPriceLevel rhs)
Order book price level equality verification.
A is thrown if the price levels are not equal, along with the reason for the inequality.
Parameters
rhs
Exceptions
MamdaOrderBookException MamdaOrderBookException is thrown if the price levels are
References Wombat.MamdaOrderBookEntry.assertEqual().
Referenced by Wombat.MamdaOrderBook.setStrictChecking().
setStrictChecking()
static void Wombat.MamdaOrderBookPriceLevel.setStrictChecking (bool strict) static
Enforce strict checking of order book modifications (at the expense of some performance).
This setting is automatically updated by MamdaOrderBook.setStrictChecking().
Parameters
strict
Referenced by Wombat.MamdaOrderBook.setStrictChecking().