OpenMAMDA C# API: Wombat.SimpleDateFormat Class Reference
Wombat.SimpleDateFormat Class Reference
Wraps a date formatting settings
Public Member Functions
SimpleDateFormat (string format)
Creates a date format, using the specified date/time format, and an invariant culture
See also
System.DateTime.ToString(System.String)
SimpleDateFormat (string format, IFormatProvider formatProvider)
Creates a date format, using the specified date/time format and culture (format provider)
See also
System.DateTime.ToString(System.String, System.Globalization.IFormatProvider)
string Format (DateTime dateTime)
DateTime Parse (string dateTimeString)
Static Public Member Functions
static string Format (DateTime dateTime, string format, IFormatProvider formatProvider)
static DateTime Parse (string dateTimeString, string format, IFormatProvider formatProvider)
Properties
string FormatString [get]
IFormatProvider FormatProvider [get]
Detailed Description
Wraps a date formatting settings
Constructor & Destructor Documentation
SimpleDateFormat() [1/2]
Wombat.SimpleDateFormat.SimpleDateFormat (string format)
Creates a date format, using the specified date/time format, and an invariant culture
See also
System.DateTime.ToString(System.String)
SimpleDateFormat() [2/2]
Wombat.SimpleDateFormat.SimpleDateFormat (string format, IFormatProvider formatProvider)
Creates a date format, using the specified date/time format and culture (format provider)
See also
System.DateTime.ToString(System.String, System.Globalization.IFormatProvider)
References Wombat.SimpleDateFormat.FormatString.
Member Function Documentation
Format() [1/2]
string Wombat.SimpleDateFormat.Format (DateTime dateTime)
Referenced by Wombat.MamdaOptionStrikeSet.getExpireDateStr(), Wombat.MamdaOptionContract.getExpireDateStr(), and Wombat.MamdaOptionExpirationDateSet.toString().
Format() [2/2]
static string Wombat.SimpleDateFormat.Format (DateTime dateTime, string format, IFormatProvider formatProvider) static
Parse() [1/2]
DateTime Wombat.SimpleDateFormat.Parse (string dateTimeString)
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
Parse() [2/2]
static DateTime Wombat.SimpleDateFormat.Parse (string dateTimeString, string format, IFormatProvider formatProvider) static
Property Documentation
FormatString
string Wombat.SimpleDateFormat.FormatString get
Referenced by Wombat.SimpleDateFormat.SimpleDateFormat().
FormatProvider
IFormatProvider Wombat.SimpleDateFormat.FormatProvider get