OpenMAMDA C# API: Wombat.MamdaOptionContract Class Reference
Wombat.MamdaOptionContract Class Reference
A class that represents a single option contract.
Public Types
enum PutOrCall : byte { PutOrCall.Unknown = (byte)'Z', PutOrCall.Call = (byte)'C', PutOrCall.Put = (byte)'P' }
enum ExerciseStyle : byte { ExerciseStyle.Unknown = (byte)'Z', ExerciseStyle.American = (byte)'A', ExerciseStyle.European = (byte)'E', ExerciseStyle.Capped = (byte)'C' }
Public Member Functions
MamdaOptionContract (string symbol, string exchange, DateTime expireDate, double strikePrice, PutOrCall putCall)
Constructor from expiration date, strike price, and put/call indicator.
void setOpenInterest (long openInterest)
Set the open interest size.
void setExerciseStyle (ExerciseStyle exerciseStyle)
Set the exercise style.
string getSymbol ()
Return the OPRA contract symbol.
string getExchange ()
Return the exchange.
DateTime getExpireDate ()
Return the expiration date.
string getExpireDateStr ()
Return the expiration date as a commonly formatted string (MMyy).
double getStrikePrice ()
Return the strike price.
PutOrCall getPutCall ()
Return the put/call indicator.
long getOpenInterest ()
Return the open interest.
ExerciseStyle getExerciseStyle ()
Return the exercise style.
void addTradeHandler (MamdaTradeHandler handler)
Add a MamdaTradeHandler for handling trade updates to this option contract.
void addQuoteHandler (MamdaQuoteHandler handler)
Add a MamdaQuoteHandler for handling quote updates to this option contract.
void addFundamentalHandler (MamdaFundamentalHandler handler)
Add a MamdaFundamentalHandler for handling fundamental updates to this option contract.
void setCustomObject (object obj)
Add a custom object to this option contract.
MamdaTradeRecap getTradeInfo ()
Return the current trade fields.
MamdaQuoteRecap getQuoteInfo ()
Return the current quote fields.
MamdaFundamentals getFundamentalsInfo ()
Return the current fundamental fields.
object getCustomObject ()
Return the custom object.
MamdaTradeListener getTradeListener ()
Return the trade listener.
MamdaQuoteListener getQuoteListener ()
Return the current quote listener.
MamdaFundamentalListener getFundamentalListener ()
Return the current fundamental listener.
void setInView (bool inView)
Set whether this contract is in the "view" within the option chain.
bool getInView ()
Return whether this contract is in the "view" within the option chain.
Detailed Description
A class that represents a single option contract.
Instances of this object are typically created by the MamdaOptionChainListener. Applications may attach a custom object to each instance of MamdaOptionContract.
Note: User applications can be notified of creation of MamdaOptionContract instances via the MamdaOptionChainListener.onOptionContractCreate() method.
Member Enumeration Documentation
PutOrCall
enum Wombat.MamdaOptionContract.PutOrCall : byte strong
Enumerator
Unknown
Call
Put
ExerciseStyle
enum Wombat.MamdaOptionContract.ExerciseStyle : byte strong
Enumerator
Unknown
American
European
Capped
Constructor & Destructor Documentation
MamdaOptionContract()
Wombat.MamdaOptionContract.MamdaOptionContract (string symbol, string exchange, DateTime expireDate, double strikePrice, PutOrCall putCall)
Constructor from expiration date, strike price, and put/call indicator.
Parameters
symbol
exchange
expireDate
strikePrice
putCall
Member Function Documentation
setOpenInterest()
void Wombat.MamdaOptionContract.setOpenInterest (long openInterest)
Set the open interest size.
Parameters
openInterest
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
setExerciseStyle()
void Wombat.MamdaOptionContract.setExerciseStyle (ExerciseStyle exerciseStyle)
Set the exercise style.
Parameters
exerciseStyle
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
getSymbol()
string Wombat.MamdaOptionContract.getSymbol ()
Return the OPRA contract symbol.
Returns
Referenced by Wombat.MamdaOptionChain.dump().
getExchange()
string Wombat.MamdaOptionContract.getExchange ()
Return the exchange.
Returns
Referenced by Wombat.MamdaOptionChain.addContract(), and Wombat.MamdaOptionChain.dump().
getExpireDate()
DateTime Wombat.MamdaOptionContract.getExpireDate ()
Return the expiration date.
Returns
Referenced by Wombat.MamdaOptionChain.addContract(), Wombat.MamdaOptionChain.dump(), and Wombat.MamdaOptionChainView.isVisible().
getExpireDateStr()
string Wombat.MamdaOptionContract.getExpireDateStr ()
Return the expiration date as a commonly formatted string (MMyy).
Returns
References Wombat.SimpleDateFormat.Format().
getStrikePrice()
double Wombat.MamdaOptionContract.getStrikePrice ()
Return the strike price.
Returns
Referenced by Wombat.MamdaOptionChain.addContract(), Wombat.MamdaOptionChain.dump(), and Wombat.MamdaOptionChainView.isVisible().
getPutCall()
PutOrCall Wombat.MamdaOptionContract.getPutCall ()
Return the put/call indicator.
Returns
Referenced by Wombat.MamdaOptionChain.addContract().
getOpenInterest()
long Wombat.MamdaOptionContract.getOpenInterest ()
Return the open interest.
Returns
getExerciseStyle()
ExerciseStyle Wombat.MamdaOptionContract.getExerciseStyle ()
Return the exercise style.
Returns
addTradeHandler()
void Wombat.MamdaOptionContract.addTradeHandler (MamdaTradeHandler handler)
Add a MamdaTradeHandler for handling trade updates to this option contract.
Parameters
handler
References Wombat.MamdaTradeListener.addHandler().
addQuoteHandler()
void Wombat.MamdaOptionContract.addQuoteHandler (MamdaQuoteHandler handler)
Add a MamdaQuoteHandler for handling quote updates to this option contract.
Parameters
handler
References Wombat.MamdaQuoteListener.addHandler().
addFundamentalHandler()
void Wombat.MamdaOptionContract.addFundamentalHandler (MamdaFundamentalHandler handler)
Add a MamdaFundamentalHandler for handling fundamental updates to this option contract.
Parameters
handler
References Wombat.MamdaFundamentalListener.addHandler().
setCustomObject()
void Wombat.MamdaOptionContract.setCustomObject (object obj)
Add a custom object to this option contract.
Such an object might contain customer per-contract data.
Parameters
obj
getTradeInfo()
MamdaTradeRecap Wombat.MamdaOptionContract.getTradeInfo ()
Return the current trade fields.
Returns
getQuoteInfo()
MamdaQuoteRecap Wombat.MamdaOptionContract.getQuoteInfo ()
Return the current quote fields.
Returns
getFundamentalsInfo()
MamdaFundamentals Wombat.MamdaOptionContract.getFundamentalsInfo ()
Return the current fundamental fields.
Returns
getCustomObject()
object Wombat.MamdaOptionContract.getCustomObject ()
Return the custom object.
Returns
getTradeListener()
MamdaTradeListener Wombat.MamdaOptionContract.getTradeListener ()
Return the trade listener.
Returns
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
getQuoteListener()
MamdaQuoteListener Wombat.MamdaOptionContract.getQuoteListener ()
Return the current quote listener.
Returns
Referenced by Wombat.MamdaOptionChainListener.getOptionActionFieldState().
getFundamentalListener()
MamdaFundamentalListener Wombat.MamdaOptionContract.getFundamentalListener ()
Return the current fundamental listener.
Returns
setInView()
void Wombat.MamdaOptionContract.setInView (bool inView)
Set whether this contract is in the "view" within the option chain.
MamdaOptionChain
Parameters
inView
getInView()
bool Wombat.MamdaOptionContract.getInView ()
Return whether this contract is in the "view" within the option chain.
MamdaOptionChain
Returns