OpenMAMDA C# API: Wombat.Containers.HashMap Class Reference
Wombat.Containers.HashMap Class Reference
Inherits Wombat.Containers.Map, and ICloneable.
Public Member Functions
HashMap (int initialCapacity, float loadFactor)
HashMap (int initialCapacity)
HashMap ()
HashMap (HashMap m)
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
object Clone ()
Creates a deep copy of this HashMap instance
Constructor & Destructor Documentation
HashMap() [1/4]
Wombat.Containers.HashMap.HashMap (int initialCapacity, float loadFactor)
HashMap() [2/4]
Wombat.Containers.HashMap.HashMap (int initialCapacity)
HashMap() [3/4]
Wombat.Containers.HashMap.HashMap ()
HashMap() [4/4]
Wombat.Containers.HashMap.HashMap (HashMap m)
Member Function Documentation
size()
int Wombat.Containers.HashMap.size ()
Implements Wombat.Containers.Map.
isEmpty()
bool Wombat.Containers.HashMap.isEmpty ()
Implements Wombat.Containers.Map.
containsKey()
bool Wombat.Containers.HashMap.containsKey (object key)
Implements Wombat.Containers.Map.
containsValue()
bool Wombat.Containers.HashMap.containsValue (object value)
Implements Wombat.Containers.Map.
valueOf()
object Wombat.Containers.HashMap.valueOf (object key)
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionChain.getContract().
put()
object Wombat.Containers.HashMap.put (object key, object value)
Implements Wombat.Containers.Map.
Referenced by Wombat.MamdaOptionChain.addContract().
remove()
object Wombat.Containers.HashMap.remove (object key)
Implements Wombat.Containers.Map.
putAll()
void Wombat.Containers.HashMap.putAll (Map m)
Implements Wombat.Containers.Map.
References Wombat.Containers.Map.entrySet(), Wombat.Containers.MapEntry.getKey(), Wombat.Containers.MapEntry.getValue(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
clear()
void Wombat.Containers.HashMap.clear ()
Implements Wombat.Containers.Map.
keySet()
Set Wombat.Containers.HashMap.keySet ()
Implements Wombat.Containers.Map.
values()
Collection Wombat.Containers.HashMap.values ()
Implements Wombat.Containers.Map.
entrySet()
Set Wombat.Containers.HashMap.entrySet ()
Implements Wombat.Containers.Map.
References Wombat.Containers.MapEntry.getKey(), Wombat.Containers.MapEntry.getValue(), Wombat.Containers.Iterator.hasNext(), Wombat.Containers.Iterable.iterator(), and Wombat.Containers.Iterator.next().
Clone()
object Wombat.Containers.HashMap.Clone ()
Creates a deep copy of this HashMap instance
Returns