OpenMAMDA C# API: Wombat.MamdaCommonFields Class Reference
Wombat.MamdaCommonFields Class Reference
Maintains a cache of common update field descriptors.
Inherits Wombat.MamdaFields.
Static Public Member Functions
static void setDictionary (MamaDictionary dictionary, NameValueCollection properties)
Set the dictionary for common update fields.
static bool isSet ()
static void reset ()
Static Public Attributes
static MamaFieldDescriptor SYMBOL = null
static MamaFieldDescriptor ISSUE_SYMBOL = null
static MamaFieldDescriptor INDEX_SYMBOL = null
static MamaFieldDescriptor PART_ID = null
static MamaFieldDescriptor SEQ_NUM = null
static MamaFieldDescriptor SRC_TIME = null
static MamaFieldDescriptor LINE_TIME = null
static MamaFieldDescriptor ACTIVITY_TIME = null
static MamaFieldDescriptor SEND_TIME = null
static MamaFieldDescriptor PUB_ID = null
static MamaFieldDescriptor MSG_QUAL = null
static MamaFieldDescriptor MSG_SEQ_NUM = null
static MamaFieldDescriptor MSG_NUM = null
static MamaFieldDescriptor MSG_TOTAL = null
static MamaFieldDescriptor SENDER_ID = null
Additional Inherited Members
Static Protected Member Functions inherited from Wombat.MamdaFields
static string lookupFieldName (NameValueCollection properties, string defaultFieldName)
Detailed Description
Maintains a cache of common update field descriptors.
Member Function Documentation
setDictionary()
static void Wombat.MamdaCommonFields.setDictionary (MamaDictionary dictionary, NameValueCollection properties) static
Set the dictionary for common update fields.
Maintains a cache of MamaFieldDescriptors for common update related fields. The properties parameter allows users of the API to map the common dictionary names to something else if they are beig published under different names.
Parameters
dictionary A reference to a valid MamaDictionary
properties A NameValueCollection object containing field mappings. (See MamdaFields for more information)
References Wombat.MamdaCommonFields.ACTIVITY_TIME, Wombat.MamdaCommonFields.INDEX_SYMBOL, Wombat.MamdaCommonFields.ISSUE_SYMBOL, Wombat.MamdaCommonFields.LINE_TIME, Wombat.MamdaFields.lookupFieldName(), Wombat.MamdaCommonFields.MSG_QUAL, Wombat.MamdaCommonFields.PART_ID, Wombat.MamdaCommonFields.PUB_ID, Wombat.MamdaCommonFields.SEQ_NUM, Wombat.MamdaCommonFields.SRC_TIME, and Wombat.MamdaCommonFields.SYMBOL.
Referenced by Wombat.MamdaOrderBookFields.setDictionary().
isSet()
static bool Wombat.MamdaCommonFields.isSet () static
Referenced by Wombat.MamdaAuctionFields.reset(), Wombat.MamdaOptionFields.reset(), Wombat.MamdaSecurityStatusFields.reset(), Wombat.MamdaFundamentalFields.reset(), Wombat.MamdaOrderImbalanceFields.reset(), Wombat.MamdaQuoteFields.reset(), Wombat.MamdaOrderBookFields.reset(), and Wombat.MamdaTradeFields.reset().
reset()
static void Wombat.MamdaCommonFields.reset () static
References Wombat.MamdaCommonFields.ACTIVITY_TIME, Wombat.MamdaCommonFields.INDEX_SYMBOL, Wombat.MamdaCommonFields.LINE_TIME, Wombat.MamdaCommonFields.MSG_NUM, Wombat.MamdaCommonFields.MSG_QUAL, Wombat.MamdaCommonFields.MSG_SEQ_NUM, Wombat.MamdaCommonFields.MSG_TOTAL, Wombat.MamdaCommonFields.PART_ID, Wombat.MamdaCommonFields.PUB_ID, Wombat.MamdaCommonFields.SEND_TIME, Wombat.MamdaCommonFields.SENDER_ID, Wombat.MamdaCommonFields.SEQ_NUM, and Wombat.MamdaCommonFields.SRC_TIME.
Referenced by Wombat.MamdaAuctionFields.reset(), Wombat.MamdaOptionFields.reset(), Wombat.MamdaSecurityStatusFields.reset(), Wombat.MamdaFundamentalFields.reset(), Wombat.MamdaOrderImbalanceFields.reset(), Wombat.MamdaQuoteFields.reset(), Wombat.MamdaOrderBookFields.reset(), and Wombat.MamdaTradeFields.reset().
Member Data Documentation
SYMBOL
MamaFieldDescriptor Wombat.MamdaCommonFields.SYMBOL = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaMultiParticipantManager.onMsg(), Wombat.MamdaBookAtomicListener.onMsg(), and Wombat.MamdaCommonFields.setDictionary().
ISSUE_SYMBOL
MamaFieldDescriptor Wombat.MamdaCommonFields.ISSUE_SYMBOL = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaMultiSecurityManager.onMsg(), Wombat.MamdaMultiParticipantManager.onMsg(), and Wombat.MamdaCommonFields.setDictionary().
INDEX_SYMBOL
MamaFieldDescriptor Wombat.MamdaCommonFields.INDEX_SYMBOL = null static
Referenced by Wombat.MamdaMultiParticipantManager.onMsg(), Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
PART_ID
MamaFieldDescriptor Wombat.MamdaCommonFields.PART_ID = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaMultiParticipantManager.onMsg(), Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
SEQ_NUM
MamaFieldDescriptor Wombat.MamdaCommonFields.SEQ_NUM = null static
Referenced by Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
SRC_TIME
MamaFieldDescriptor Wombat.MamdaCommonFields.SRC_TIME = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
LINE_TIME
MamaFieldDescriptor Wombat.MamdaCommonFields.LINE_TIME = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
ACTIVITY_TIME
MamaFieldDescriptor Wombat.MamdaCommonFields.ACTIVITY_TIME = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
SEND_TIME
MamaFieldDescriptor Wombat.MamdaCommonFields.SEND_TIME = null static
Referenced by Wombat.MamdaAuctionListener.getFieldAsString(), and Wombat.MamdaCommonFields.reset().
PUB_ID
MamaFieldDescriptor Wombat.MamdaCommonFields.PUB_ID = null static
Referenced by Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
MSG_QUAL
MamaFieldDescriptor Wombat.MamdaCommonFields.MSG_QUAL = null static
Referenced by Wombat.MamdaCommonFields.reset(), and Wombat.MamdaCommonFields.setDictionary().
MSG_SEQ_NUM
MamaFieldDescriptor Wombat.MamdaCommonFields.MSG_SEQ_NUM = null static
Referenced by Wombat.MamdaCommonFields.reset().
MSG_NUM
MamaFieldDescriptor Wombat.MamdaCommonFields.MSG_NUM = null static
Referenced by Wombat.MamdaCommonFields.reset().
MSG_TOTAL
MamaFieldDescriptor Wombat.MamdaCommonFields.MSG_TOTAL = null static
Referenced by Wombat.MamdaCommonFields.reset().
SENDER_ID
MamaFieldDescriptor Wombat.MamdaCommonFields.SENDER_ID = null static
Referenced by Wombat.MamdaCommonFields.reset().