OpenMAMDA C# API: Wombat.MamdaConcreteSecurityStatusRecap Class Reference
Wombat.MamdaConcreteSecurityStatusRecap Class Reference
Inherits Wombat.MamdaSecurityStatusRecap.
Public Member Functions
void clear ()
Clear the recap data
long getSecurityStatus ()
Returns the security status MamdaSecurityStatusUpdate.getSecurityStatus()
MamdaFieldState getSecurityStatusFieldState ()
Returns Field State, always MODIFIED
void setSecurityStatus (long securityStatus)
Set the security status MamdaSecurityStatusUpdate.getSecurityStatus()
long getSecurityStatusQualifier ()
Returns the security MamdaSecurityStatusUpdate.getSecurityStatus()
MamdaFieldState getSecurityStatusQualifierFieldState ()
Returns Field State, always MODIFIED
void setSecurityStatusQualifier (long secQualifier)
MamdaSecurityStatusUpdate.getSecurityStatus()
MamdaSecurityStatus.mamdaSecurityStatus getSecurityStatusEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusEnum()
MamdaFieldState getSecurityStatusEnumFieldState ()
Returns Field State, always MODIFIED
void setSecurityStatusEnum (MamdaSecurityStatus.mamdaSecurityStatus secStatus)
MamdaSecurityStatusUpdate.getSecurityStatusEnum()
MamdaSecurityStatusQual.mamdaSecurityStatusQual getSecurityStatusQualifierEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifierEnum()
MamdaFieldState getSecurityStatusQualifierEnumFieldState ()
Returns Field State, always MODIFIED
void setSecurityStatusQualifierEnum (MamdaSecurityStatusQual.mamdaSecurityStatusQual secStatusQual)
MamdaSecurityStatusUpdate.getSecurityStatusQualifierEnum()
string getSecurityStatusStr ()
Returns the security status string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
MamdaFieldState getSecurityStatusStrFieldState ()
Returns Field State, always MODIFIED
char getShortSaleCircuitBreaker ()
Returns the short sale CircuitBreaker MamdaSecurityStatusUpdate.getShortSaleCircuitBreaker()
void setShortSaleCircuitBreaker (char shortSaleCircuitBreaker)
Set the short sale Circuit Breaker.
MamdaFieldState getShortSaleCircuitBreakerFieldState ()
Returns Field State, always MODIFIED
string getSecurityStatusOrigStr ()
Return the native security status qualifier
MamdaFieldState getSecurityStatusOrigStrFieldState ()
Returns Field State, always MODIFIED
void setSecurityStatusOrigStr (string securityStatusOrigStr)
void setSecurityStatusStr (string securityStatusStr)
Set the security status string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
string getSecurityStatusQualifierStr ()
Returns the security status qualifier string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
MamdaFieldState getSecurityStatusQualifierStrFieldState ()
Returns Field State, always MODIFIED
void setSecurityStatusQualifierStr (String securityStatusQualifierStr)
Set the security status qualifier string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
string getReason ()
MamdaSecurityStatusUpdate.getReason()
MamdaFieldState getReasonFieldState ()
Returns Field State, always MODIFIED
void setReason (string reason)
DateTime getActivityTime ()
MamdaBasicRecap.getActivityTime
MamdaFieldState getActivityTimeFieldState ()
Returns Field State, always MODIFIED
void setActivityTime (DateTime actTime)
void setSrcTime (DateTime srcTime)
DateTime getSrcTime ()
MamdaFieldState getSrcTimeFieldState ()
Returns Field State, always MODIFIED
DateTime getLuldTime ()
MamdaSecurityStatusUpdate.getLuldTime()
MamdaFieldState getLuldTimeFieldState ()
Returns Field State, always MODIFIED
char getLuldIndicator ()
Returns the security status Luld Indicator
MamdaFieldState getLuldIndicatorFieldState ()
Returns Field State, always MODIFIED
MamaPrice getLuldHighLimit ()
MamdaSecurityStatusUpdate.getLuldHighLimit()
MamdaFieldState getLuldHighLimitFieldState ()
Returns Field State, always MODIFIED
MamaPrice getLuldLowLimit ()
MamdaSecurityStatusUpdate.getLuldLowLimit()
MamdaFieldState getLuldLowLimitFieldState ()
Returns Field State, always MODIFIED
void setLuldTime (DateTime luldTime)
Set the Limit Up Limit Down Time
void setLuldIndicator (char luldIndicator)
Set the Limit Up Limit Down Indicator
void setLuldHighLimit (MamaPrice luldHighLimit)
Set the Limit Up Limit Down High Limit
void setLuldLowLimit (MamaPrice luldLowLimit)
Set the Limit Up Limit Down Low Limit
Member Function Documentation
clear()
void Wombat.MamdaConcreteSecurityStatusRecap.clear ()
Clear the recap data
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getSecurityStatus()
long Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatus ()
Returns the security status MamdaSecurityStatusUpdate.getSecurityStatus()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setSecurityStatus()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatus (long securityStatus)
Set the security status MamdaSecurityStatusUpdate.getSecurityStatus()
Parameters
securityStatus
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getSecurityStatusQualifier()
long Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusQualifier ()
Returns the security MamdaSecurityStatusUpdate.getSecurityStatus()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusQualifierFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusQualifierFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setSecurityStatusQualifier()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusQualifier (long secQualifier)
MamdaSecurityStatusUpdate.getSecurityStatus()
Parameters
secQualifier
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getSecurityStatusEnum()
MamdaSecurityStatus.mamdaSecurityStatus Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusEnum()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusEnumFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusEnumFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setSecurityStatusEnum()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusEnum (MamdaSecurityStatus.mamdaSecurityStatus secStatus)
MamdaSecurityStatusUpdate.getSecurityStatusEnum()
<returns
getSecurityStatusQualifierEnum()
MamdaSecurityStatusQual.mamdaSecurityStatusQual Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusQualifierEnum ()
MamdaSecurityStatusUpdate.getSecurityStatusQualifierEnum()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusQualifierEnumFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusQualifierEnumFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setSecurityStatusQualifierEnum()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusQualifierEnum (MamdaSecurityStatusQual.mamdaSecurityStatusQual secStatusQual)
MamdaSecurityStatusUpdate.getSecurityStatusQualifierEnum()
Parameters
secStatusQual
getSecurityStatusStr()
string Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusStr ()
Returns the security status string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusStrFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusStrFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
getShortSaleCircuitBreaker()
char Wombat.MamdaConcreteSecurityStatusRecap.getShortSaleCircuitBreaker ()
Returns the short sale CircuitBreaker MamdaSecurityStatusUpdate.getShortSaleCircuitBreaker()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
setShortSaleCircuitBreaker()
void Wombat.MamdaConcreteSecurityStatusRecap.setShortSaleCircuitBreaker (char shortSaleCircuitBreaker)
Set the short sale Circuit Breaker.
MamdaSecurityStatusUpdate.getShortSaleCircuitBreakerFieldState()
Parameters
shortSaleCircuitBreaker
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getShortSaleCircuitBreakerFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusOrigStr()
string Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusOrigStr ()
Return the native security status qualifier
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusOrigStrFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusOrigStrFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setSecurityStatusOrigStr()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusOrigStr (string securityStatusOrigStr)
setSecurityStatusStr()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusStr (string securityStatusStr)
Set the security status string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
Parameters
securityStatusStr
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getSecurityStatusQualifierStr()
string Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusQualifierStr ()
Returns the security status qualifier string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getSecurityStatusQualifierStrFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSecurityStatusQualifierStrFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setSecurityStatusQualifierStr()
void Wombat.MamdaConcreteSecurityStatusRecap.setSecurityStatusQualifierStr (String securityStatusQualifierStr)
Set the security status qualifier string MamdaSecurityStatusUpdate.getSecurityStatusQualifier()
Parameters
securityStatusQualifierStr
summary> Returns the security status reason MamdaSecurityStatusRecap.getReason()
Returns
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getReason()
string Wombat.MamdaConcreteSecurityStatusRecap.getReason ()
MamdaSecurityStatusUpdate.getReason()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getReasonFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getReasonFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
summary> Set the security status reason MamdaSecurityStatusRecap.getReason()
Parameters
reason
Implements Wombat.MamdaSecurityStatusRecap.
setReason()
void Wombat.MamdaConcreteSecurityStatusRecap.setReason (string reason)
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getActivityTime()
DateTime Wombat.MamdaConcreteSecurityStatusRecap.getActivityTime ()
MamdaBasicRecap.getActivityTime
Returns
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getActivityTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setActivityTime()
void Wombat.MamdaConcreteSecurityStatusRecap.setActivityTime (DateTime actTime)
Parameters
actTime
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
setSrcTime()
void Wombat.MamdaConcreteSecurityStatusRecap.setSrcTime (DateTime srcTime)
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
getSrcTime()
DateTime Wombat.MamdaConcreteSecurityStatusRecap.getSrcTime ()
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getSrcTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
summary> Returns the security status Luld Time
Returns
getLuldTime()
DateTime Wombat.MamdaConcreteSecurityStatusRecap.getLuldTime ()
MamdaSecurityStatusUpdate.getLuldTime()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getLuldTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getLuldTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
summary>
Implements Wombat.MamdaSecurityStatusRecap.
getLuldIndicator()
char Wombat.MamdaConcreteSecurityStatusRecap.getLuldIndicator ()
Returns the security status Luld Indicator
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getLuldIndicatorFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getLuldIndicatorFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
summary> Returns the security status Luld High Limit
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getLuldHighLimit()
MamaPrice Wombat.MamdaConcreteSecurityStatusRecap.getLuldHighLimit ()
MamdaSecurityStatusUpdate.getLuldHighLimit()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getLuldHighLimitFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getLuldHighLimitFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
summary> Returns the security status Luld LowLimit
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getLuldLowLimit()
MamaPrice Wombat.MamdaConcreteSecurityStatusRecap.getLuldLowLimit ()
MamdaSecurityStatusUpdate.getLuldLowLimit()
Returns
Implements Wombat.MamdaSecurityStatusRecap.
getLuldLowLimitFieldState()
MamdaFieldState Wombat.MamdaConcreteSecurityStatusRecap.getLuldLowLimitFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaSecurityStatusRecap.
setLuldTime()
void Wombat.MamdaConcreteSecurityStatusRecap.setLuldTime (DateTime luldTime)
Set the Limit Up Limit Down Time
Parameters
LuldTime
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
setLuldIndicator()
void Wombat.MamdaConcreteSecurityStatusRecap.setLuldIndicator (char luldIndicator)
Set the Limit Up Limit Down Indicator
Parameters
LuldIndicator
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
setLuldHighLimit()
void Wombat.MamdaConcreteSecurityStatusRecap.setLuldHighLimit (MamaPrice luldHighLimit)
Set the Limit Up Limit Down High Limit
Parameters
LuldHighLimit
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().
setLuldLowLimit()
void Wombat.MamdaConcreteSecurityStatusRecap.setLuldLowLimit (MamaPrice luldLowLimit)
Set the Limit Up Limit Down Low Limit
Parameters
LuldHighLimit
Referenced by Wombat.MamdaSecurityStatusListener.populateRecap().