OpenMAMDA C# API: Wombat.MamdaConcreteQuoteRecap Class Reference
Wombat.MamdaConcreteQuoteRecap Class Reference
Inherits Wombat.MamdaQuoteRecap.
Public Member Functions
MamdaConcreteQuoteRecap ()
void clear ()
Clear the recap data
void setSymbol (string symbol)
string getSymbol ()
Symbol.
MamdaFieldState getSymbolFieldState ()
Returns Field State, always MODIFIED
void setPartId (string partId)
string getPartId ()
Participant ID.
MamdaFieldState getPartIdFieldState ()
Returns Field State, always MODIFIED
void setSrcTime (DateTime srcTime)
DateTime getSrcTime ()
Source time.
MamdaFieldState getSrcTimeFieldState ()
Returns Field State, always MODIFIED
void setActivityTime (DateTime activityTime)
DateTime getActivityTime ()
Activity time.
MamdaFieldState getActivityTimeFieldState ()
Returns Field State, always MODIFIED
void setLineTime (DateTime lineTime)
DateTime getLineTime ()
Line time.
MamdaFieldState getLineTimeFieldState ()
Returns Field State, always MODIFIED
void setSendTime (DateTime sendTime)
DateTime getSendTime ()
Send time.
MamdaFieldState getSendTimeFieldState ()
Returns Field State, always MODIFIED
void setPubId (string pubId)
string getPubId ()
MamdaFieldState getPubIdFieldState ()
Returns Field State, always MODIFIED
void setBidPrice (MamaPrice bidPrice)
MamaPrice getBidPrice ()
Get the bid price.
MamdaFieldState getBidPriceFieldState ()
Returns Field State, always MODIFIED
void setBidSize (long bidSize)
long getBidSize ()
Get the bid size.
MamdaFieldState getBidSizeFieldState ()
Returns Field State, always MODIFIED
void setBidSize (double bidSize)
void setBidDepth (double bidDepth)
double getBidDepth ()
MamdaFieldState getBidDepthFieldState ()
Returns Field State, always MODIFIED
void setBidPartId (string partId)
string getBidPartId ()
Get the bid participant identifier.
MamdaFieldState getBidPartIdFieldState ()
Returns Field State, always MODIFIED
void setBidClosePrice (MamaPrice bidClosePrice)
MamaPrice getBidClosePrice ()
MamdaFieldState getBidClosePriceFieldState ()
Returns Field State, always MODIFIED
void setBidCloseDate (DateTime bidCloseDate)
DateTime getBidCloseDate ()
MamdaFieldState getBidCloseDateFieldState ()
Returns Field State, always MODIFIED
void setBidPrevClosePrice (MamaPrice bidPrevClosePrice)
MamaPrice getBidPrevClosePrice ()
MamdaFieldState getBidPrevClosePriceFieldState ()
Returns Field State, always MODIFIED
void setBidPrevCloseDate (DateTime bidPrevCloseDate)
DateTime getBidPrevCloseDate ()
MamdaFieldState getBidPrevCloseDateFieldState ()
Returns Field State, always MODIFIED
void setBidHigh (MamaPrice bidHigh)
MamaPrice getBidHigh ()
MamdaFieldState getBidHighFieldState ()
Returns Field State, always MODIFIED
void setBidLow (MamaPrice bidLow)
MamaPrice getBidLow ()
MamdaFieldState FieldState ()
Returns Field State, always MODIFIED
void setAskPrice (MamaPrice askPrice)
MamaPrice getAskPrice ()
Get the ask price.
MamdaFieldState getAskPriceFieldState ()
Returns Field State, always MODIFIED
void setQuoteMidPrice (MamaPrice midPrice)
MamaPrice getQuoteMidPrice ()
Get the quote mid price.
MamdaFieldState getQuoteMidPriceFieldState ()
Returns Field State, always MODIFIED
void setAskSize (long askSize)
long getAskSize ()
Get the ask size.
MamdaFieldState getAskSizeFieldState ()
Returns Field State, always MODIFIED
void setAskSize (double askSize)
void setAskDepth (double askDepth)
double getAskDepth ()
void setAskPartId (string askPartId)
string getAskPartId ()
Get the ask participant identifier.
MamdaFieldState getAskPartIdFieldState ()
Returns Field State, always MODIFIED
void setAskClosePrice (MamaPrice askClosePrice)
MamaPrice getAskClosePrice ()
MamdaFieldState getAskClosePriceFieldState ()
Returns Field State, always MODIFIED
void setAskCloseDate (DateTime askCloseDate)
DateTime getAskCloseDate ()
MamdaFieldState getAskCloseDateFieldState ()
Returns Field State, always MODIFIED
void setAskPrevClosePrice (MamaPrice askPrevClosePrice)
MamaPrice getAskPrevClosePrice ()
MamdaFieldState getAskPrevClosePriceFieldState ()
Returns Field State, always MODIFIED
void setAskPrevCloseDate (DateTime askPrevCloseDate)
DateTime getAskPrevCloseDate ()
MamdaFieldState getAskPrevCloseDateFieldState ()
Returns Field State, always MODIFIED
void setAskHigh (MamaPrice askHigh)
MamaPrice getAskHigh ()
MamdaFieldState getAskHighFieldState ()
Returns Field State, always MODIFIED
void setAskLow (MamaPrice askLow)
MamaPrice getAskLow ()
MamdaFieldState getAskLowFieldState ()
Returns Field State, always MODIFIED
void setEventSeqNum (long eventSeqNum)
long getEventSeqNum ()
MamdaFieldState getEventSeqNumFieldState ()
Returns Field State, always MODIFIED
void setEventTime (DateTime eventTime)
DateTime getEventTime ()
MamdaFieldState getEventTimeFieldState ()
Returns Field State, always MODIFIED
void setQuoteDate (DateTime quoteDate)
DateTime getQuoteDate ()
MamdaFieldState getQuoteDateFieldState ()
Returns Field State, always MODIFIED
void setQuoteQual (string quoteQualStr)
string getQuoteQual ()
Get the normalized quote qualifier.
MamdaFieldState getQuoteQualFieldState ()
Returns Field State, always MODIFIED
void setQuoteQualNative (string quoteQualNative)
string getQuoteQualNative ()
MamdaQuoteUpdate.getQuoteQualNative()
MamdaFieldState getQuoteQualNativeFieldState ()
Returns Field State, always MODIFIED
void setTmpQuoteCount (long quoteCount)
long getTmpQuoteCount ()
MamdaFieldState getTmpQuoteCountFieldState ()
Returns Field State, always MODIFIED
void setQuoteCount (long quoteCount)
long getQuoteCount ()
Get the quote count.
MamdaFieldState getQuoteCountFieldState ()
Returns Field State, always MODIFIED
char getShortSaleBidTick ()
MamdaQuoteUpdate.getShortSaleBidTick()
MamdaFieldState getShortSaleBidTickFieldState ()
Returns Field State, always MODIFIED
void setShortSaleBidTick (char shortSaleBidTick)
char getShortSaleCircuitBreaker ()
MamdaQuoteUpdate.getShortSaleCircuitBreaker()
MamdaFieldState getShortSaleCircuitBreakerFieldState ()
Returns Field State, always MODIFIED
void setShortSaleCircuitBreaker (char shortSaleCircuitBreaker)
void setAskTime (DateTime askTime)
void setBidTime (DateTime bidTime)
void setAskIndicator (string askIndicator)
void setBidIndicator (string bidIndicator)
void setAskUpdateCount (long askUpdateCount)
void setBidUpdateCount (long bidUpdateCount)
void setAskYield (double askYield)
void setBidYield (double bidYield)
DateTime getAskTime ()
MamdaFieldState getAskTimeFieldState ()
Returns Field State, always MODIFIED
DateTime getBidTime ()
MamdaFieldState getBidTimeFieldState ()
Returns Field State, always MODIFIED
string getAskIndicator ()
MamdaFieldState getAskIndicatorFieldState ()
Returns Field State, always MODIFIED
string getBidIndicator ()
MamdaFieldState getBidIndicatorFieldState ()
Returns Field State, always MODIFIED
long getAskUpdateCount ()
MamdaFieldState getAskUpdateCountFieldState ()
Returns Field State, always MODIFIED
long getBidUpdateCount ()
MamdaFieldState getBidUpdateCountFieldState ()
Returns Field State, always MODIFIED
double getAskYield ()
MamdaFieldState getAskYieldFieldState ()
Returns Field State, always MODIFIED
double getBidYield ()
MamdaFieldState getBidYieldFieldState ()
Returns Field State, always MODIFIED
Detailed Description
Constructor & Destructor Documentation
MamdaConcreteQuoteRecap()
Wombat.MamdaConcreteQuoteRecap.MamdaConcreteQuoteRecap ()
Member Function Documentation
clear()
void Wombat.MamdaConcreteQuoteRecap.clear ()
Clear the recap data
setSymbol()
void Wombat.MamdaConcreteQuoteRecap.setSymbol (string symbol)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getSymbol()
string Wombat.MamdaConcreteQuoteRecap.getSymbol ()
Symbol.
This is the "well-known" symbol for the security, including any symbology mapping performed by the publisher.
Implements Wombat.MamdaBasicRecap.
getSymbolFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getSymbolFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaBasicRecap.
setPartId()
void Wombat.MamdaConcreteQuoteRecap.setPartId (string partId)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getPartId()
string Wombat.MamdaConcreteQuoteRecap.getPartId ()
Participant ID.
This may be an exchange identifier, a market maker ID, etc., or NULL (if this is not related to any specific participant).
Implements Wombat.MamdaBasicRecap.
getPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getPartIdFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaBasicRecap.
setSrcTime()
void Wombat.MamdaConcreteQuoteRecap.setSrcTime (DateTime srcTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getSrcTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getSrcTime ()
Source time.
Typically, the exchange generated feed time stamp. This is often the same as the "event time", because many feeds do not distinguish between the actual event time and when the exchange sent the message.
Implements Wombat.MamdaBasicRecap.
getSrcTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getSrcTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaBasicRecap.
setActivityTime()
void Wombat.MamdaConcreteQuoteRecap.setActivityTime (DateTime activityTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getActivityTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getActivityTime ()
Activity time.
A feed handler generated time stamp representing when the data item was last updated.
Returns
Implements Wombat.MamdaBasicRecap.
getActivityTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getActivityTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaBasicRecap.
setLineTime()
void Wombat.MamdaConcreteQuoteRecap.setLineTime (DateTime lineTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getLineTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getLineTime ()
Line time.
A feed handler (or similar publisher) time stamp representing the time that such publisher received the update message pertaining to the event. If clocks are properly synchronized and the source time (see above) is accurate enough, then the difference between the source time and line time is the latency between the data source and the feed handler.
Implements Wombat.MamdaBasicRecap.
getLineTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getLineTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaBasicRecap.
setSendTime()
void Wombat.MamdaConcreteQuoteRecap.setSendTime (DateTime sendTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getSendTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getSendTime ()
Send time.
A feed handler (or similar publisher) time stamp representing the time that such publisher sent the current message. The difference between the line time and send time is the latency within the feed handler itself. Also, if clocks are properly synchronized then the difference between the send time and current time is the latency within the market data distribution framework (i.e. MAMA and the underlying middleware). See MAMA API: MamaDateTime::currentTime()).
Implements Wombat.MamdaBasicRecap.
getSendTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getSendTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaBasicRecap.
setPubId()
void Wombat.MamdaConcreteQuoteRecap.setPubId (string pubId)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getPubId()
string Wombat.MamdaConcreteQuoteRecap.getPubId ()
getPubIdFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getPubIdFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidPrice()
void Wombat.MamdaConcreteQuoteRecap.setBidPrice (MamaPrice bidPrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidPrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getBidPrice ()
Get the bid price.
Returns
Bid price. The highest price that the representative party/group is willing to pay to buy the security. For most feeds, this size is represented in round lots.
Implements Wombat.MamdaQuoteRecap.
getBidPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidPriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setBidSize() [1/2]
void Wombat.MamdaConcreteQuoteRecap.setBidSize (long bidSize)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidSize()
long Wombat.MamdaConcreteQuoteRecap.getBidSize ()
Get the bid size.
Returns
Total share size available for the current bid price.
Implements Wombat.MamdaQuoteRecap.
getBidSizeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidSizeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setBidSize() [2/2]
void Wombat.MamdaConcreteQuoteRecap.setBidSize (double bidSize)
setBidDepth()
void Wombat.MamdaConcreteQuoteRecap.setBidDepth (double bidDepth)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidDepth()
double Wombat.MamdaConcreteQuoteRecap.getBidDepth ()
getBidDepthFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidDepthFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidPartId()
void Wombat.MamdaConcreteQuoteRecap.setBidPartId (string partId)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidPartId()
string Wombat.MamdaConcreteQuoteRecap.getBidPartId ()
Get the bid participant identifier.
Returns
The identifier of the market participant (e.g. exchange or market maker) contributing the bid price field.
Implements Wombat.MamdaQuoteRecap.
getBidPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidPartIdFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setBidClosePrice()
void Wombat.MamdaConcreteQuoteRecap.setBidClosePrice (MamaPrice bidClosePrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidClosePrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getBidClosePrice ()
getBidClosePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidClosePriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidCloseDate()
void Wombat.MamdaConcreteQuoteRecap.setBidCloseDate (DateTime bidCloseDate)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidCloseDate()
DateTime Wombat.MamdaConcreteQuoteRecap.getBidCloseDate ()
getBidCloseDateFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidCloseDateFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidPrevClosePrice()
void Wombat.MamdaConcreteQuoteRecap.setBidPrevClosePrice (MamaPrice bidPrevClosePrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidPrevClosePrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getBidPrevClosePrice ()
getBidPrevClosePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidPrevClosePriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidPrevCloseDate()
void Wombat.MamdaConcreteQuoteRecap.setBidPrevCloseDate (DateTime bidPrevCloseDate)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidPrevCloseDate()
DateTime Wombat.MamdaConcreteQuoteRecap.getBidPrevCloseDate ()
getBidPrevCloseDateFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidPrevCloseDateFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidHigh()
void Wombat.MamdaConcreteQuoteRecap.setBidHigh (MamaPrice bidHigh)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidHigh()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getBidHigh ()
getBidHighFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidHighFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setBidLow()
void Wombat.MamdaConcreteQuoteRecap.setBidLow (MamaPrice bidLow)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getBidLow()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getBidLow ()
FieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.FieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskPrice()
void Wombat.MamdaConcreteQuoteRecap.setAskPrice (MamaPrice askPrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskPrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getAskPrice ()
Get the ask price.
Returns
Ask price. The lowest price that the representative party/group is willing to take to sell the security. For most feeds, this size is represented in round lots.
Implements Wombat.MamdaQuoteRecap.
getAskPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskPriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setQuoteMidPrice()
void Wombat.MamdaConcreteQuoteRecap.setQuoteMidPrice (MamaPrice midPrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getQuoteMidPrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getQuoteMidPrice ()
Get the quote mid price.
Returns
The mid price of the current quote. Usually, this is the average of the bid and ask prices, but some exchanges provide this field explicitly.
Implements Wombat.MamdaQuoteRecap.
getQuoteMidPriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getQuoteMidPriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskSize() [1/2]
void Wombat.MamdaConcreteQuoteRecap.setAskSize (long askSize)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskSize()
long Wombat.MamdaConcreteQuoteRecap.getAskSize ()
Get the ask size.
Returns
Total share size available for the current ask price.
Note: many feeds provide this size in terms of round lots. Wombat may change the behavior of this in the future to represent the exact number of shares.
Implements Wombat.MamdaQuoteRecap.
getAskSizeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskSizeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setAskSize() [2/2]
void Wombat.MamdaConcreteQuoteRecap.setAskSize (double askSize)
setAskDepth()
void Wombat.MamdaConcreteQuoteRecap.setAskDepth (double askDepth)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskDepth()
double Wombat.MamdaConcreteQuoteRecap.getAskDepth ()
setAskPartId()
void Wombat.MamdaConcreteQuoteRecap.setAskPartId (string askPartId)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskPartId()
string Wombat.MamdaConcreteQuoteRecap.getAskPartId ()
Get the ask participant identifier.
Returns
The identifier of the market participant (e.g. exchange or market maker) contributing the ask price field.
Implements Wombat.MamdaQuoteRecap.
getAskPartIdFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskPartIdFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setAskClosePrice()
void Wombat.MamdaConcreteQuoteRecap.setAskClosePrice (MamaPrice askClosePrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskClosePrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getAskClosePrice ()
getAskClosePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskClosePriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskCloseDate()
void Wombat.MamdaConcreteQuoteRecap.setAskCloseDate (DateTime askCloseDate)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskCloseDate()
DateTime Wombat.MamdaConcreteQuoteRecap.getAskCloseDate ()
getAskCloseDateFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskCloseDateFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskPrevClosePrice()
void Wombat.MamdaConcreteQuoteRecap.setAskPrevClosePrice (MamaPrice askPrevClosePrice)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskPrevClosePrice()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getAskPrevClosePrice ()
getAskPrevClosePriceFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskPrevClosePriceFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskPrevCloseDate()
void Wombat.MamdaConcreteQuoteRecap.setAskPrevCloseDate (DateTime askPrevCloseDate)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskPrevCloseDate()
DateTime Wombat.MamdaConcreteQuoteRecap.getAskPrevCloseDate ()
getAskPrevCloseDateFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskPrevCloseDateFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskHigh()
void Wombat.MamdaConcreteQuoteRecap.setAskHigh (MamaPrice askHigh)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskHigh()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getAskHigh ()
getAskHighFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskHighFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setAskLow()
void Wombat.MamdaConcreteQuoteRecap.setAskLow (MamaPrice askLow)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskLow()
MamaPrice Wombat.MamdaConcreteQuoteRecap.getAskLow ()
getAskLowFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskLowFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setEventSeqNum()
void Wombat.MamdaConcreteQuoteRecap.setEventSeqNum (long eventSeqNum)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getEventSeqNum()
long Wombat.MamdaConcreteQuoteRecap.getEventSeqNum ()
getEventSeqNumFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getEventSeqNumFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setEventTime()
void Wombat.MamdaConcreteQuoteRecap.setEventTime (DateTime eventTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getEventTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getEventTime ()
getEventTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getEventTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setQuoteDate()
void Wombat.MamdaConcreteQuoteRecap.setQuoteDate (DateTime quoteDate)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getQuoteDate()
DateTime Wombat.MamdaConcreteQuoteRecap.getQuoteDate ()
Implements Wombat.MamdaQuoteRecap.
getQuoteDateFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getQuoteDateFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setQuoteQual()
void Wombat.MamdaConcreteQuoteRecap.setQuoteQual (string quoteQualStr)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getQuoteQual()
string Wombat.MamdaConcreteQuoteRecap.getQuoteQual ()
Get the normalized quote qualifier.
Returns
A normalized set of qualifiers for the last quote for the security. This field may contain multiple string values, separated by the colon(:) character. MamdaQuoteUpdate.getQuoteQual
Implements Wombat.MamdaQuoteRecap.
getQuoteQualFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getQuoteQualFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setQuoteQualNative()
void Wombat.MamdaConcreteQuoteRecap.setQuoteQualNative (string quoteQualNative)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getQuoteQualNative()
string Wombat.MamdaConcreteQuoteRecap.getQuoteQualNative ()
MamdaQuoteUpdate.getQuoteQualNative()
Returns
Implements Wombat.MamdaQuoteRecap.
getQuoteQualNativeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getQuoteQualNativeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setTmpQuoteCount()
void Wombat.MamdaConcreteQuoteRecap.setTmpQuoteCount (long quoteCount)
getTmpQuoteCount()
long Wombat.MamdaConcreteQuoteRecap.getTmpQuoteCount ()
getTmpQuoteCountFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getTmpQuoteCountFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
setQuoteCount()
void Wombat.MamdaConcreteQuoteRecap.setQuoteCount (long quoteCount)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getQuoteCount()
long Wombat.MamdaConcreteQuoteRecap.getQuoteCount ()
Get the quote count.
Returns
The number of quotes generated for this security during the current trading session.
Implements Wombat.MamdaQuoteRecap.
getQuoteCountFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getQuoteCountFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getShortSaleBidTick()
char Wombat.MamdaConcreteQuoteRecap.getShortSaleBidTick ()
MamdaQuoteUpdate.getShortSaleBidTick()
Returns
Implements Wombat.MamdaQuoteRecap.
getShortSaleBidTickFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getShortSaleBidTickFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setShortSaleBidTick()
void Wombat.MamdaConcreteQuoteRecap.setShortSaleBidTick (char shortSaleBidTick)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getShortSaleCircuitBreaker()
char Wombat.MamdaConcreteQuoteRecap.getShortSaleCircuitBreaker ()
MamdaQuoteUpdate.getShortSaleCircuitBreaker()
Returns
Implements Wombat.MamdaQuoteRecap.
getShortSaleCircuitBreakerFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getShortSaleCircuitBreakerFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
setShortSaleCircuitBreaker()
void Wombat.MamdaConcreteQuoteRecap.setShortSaleCircuitBreaker (char shortSaleCircuitBreaker)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setAskTime()
void Wombat.MamdaConcreteQuoteRecap.setAskTime (DateTime askTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setBidTime()
void Wombat.MamdaConcreteQuoteRecap.setBidTime (DateTime bidTime)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setAskIndicator()
void Wombat.MamdaConcreteQuoteRecap.setAskIndicator (string askIndicator)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setBidIndicator()
void Wombat.MamdaConcreteQuoteRecap.setBidIndicator (string bidIndicator)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setAskUpdateCount()
void Wombat.MamdaConcreteQuoteRecap.setAskUpdateCount (long askUpdateCount)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setBidUpdateCount()
void Wombat.MamdaConcreteQuoteRecap.setBidUpdateCount (long bidUpdateCount)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setAskYield()
void Wombat.MamdaConcreteQuoteRecap.setAskYield (double askYield)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
setBidYield()
void Wombat.MamdaConcreteQuoteRecap.setBidYield (double bidYield)
Referenced by Wombat.MamdaQuoteListener.populateRecap().
getAskTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getAskTime ()
Implements Wombat.MamdaQuoteRecap.
getAskTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getBidTime()
DateTime Wombat.MamdaConcreteQuoteRecap.getBidTime ()
Implements Wombat.MamdaQuoteRecap.
getBidTimeFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidTimeFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getAskIndicator()
string Wombat.MamdaConcreteQuoteRecap.getAskIndicator ()
Implements Wombat.MamdaQuoteRecap.
getAskIndicatorFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskIndicatorFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getBidIndicator()
string Wombat.MamdaConcreteQuoteRecap.getBidIndicator ()
Implements Wombat.MamdaQuoteRecap.
getBidIndicatorFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidIndicatorFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getAskUpdateCount()
long Wombat.MamdaConcreteQuoteRecap.getAskUpdateCount ()
Implements Wombat.MamdaQuoteRecap.
getAskUpdateCountFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskUpdateCountFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getBidUpdateCount()
long Wombat.MamdaConcreteQuoteRecap.getBidUpdateCount ()
Implements Wombat.MamdaQuoteRecap.
getBidUpdateCountFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidUpdateCountFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getAskYield()
double Wombat.MamdaConcreteQuoteRecap.getAskYield ()
Implements Wombat.MamdaQuoteRecap.
getAskYieldFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getAskYieldFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.
getBidYield()
double Wombat.MamdaConcreteQuoteRecap.getBidYield ()
Implements Wombat.MamdaQuoteRecap.
getBidYieldFieldState()
MamdaFieldState Wombat.MamdaConcreteQuoteRecap.getBidYieldFieldState ()
Returns Field State, always MODIFIED
Returns
Field State MODIFIED
Implements Wombat.MamdaQuoteRecap.