OpenMAMDA C# API: Wombat.MamdaOrderImbalanceSide Class Reference
Wombat.MamdaOrderImbalanceSide Class Reference
Public Member Functions
override string ToString ()
Returns the string name for the enumerated type.
string toString ()
Returns the string name for the enumerated type.
int getValue ()
Returns the integer value for the type.
bool equals (MamdaOrderImbalanceSide imbalanceSide)
Compare the two types for equality.
override bool Equals (object obj)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (MamdaOrderImbalanceSide left, MamdaOrderImbalanceSide right)
static bool operator!= (MamdaOrderImbalanceSide left, MamdaOrderImbalanceSide right)
static String valueToString (int value)
Utility method for mapping type integer values to corresponding string values.
static MamdaOrderImbalanceSide enumObjectForValue (int value)
Return an instance of a MamdaOrderImbalanceSide corresponding to the specified integer value.
Public Attributes
const int BID_SIDE_VALUE = 0
BID_SIDE_IMBALANCE.
const int ASK_SIDE_VALUE = 1
ASK_SIDE_IMBALANCE.
const int NO_IMBALANCE_VALUE = 2
NO_IMBALANCE.
Static Public Attributes
static readonly MamdaOrderImbalanceSide BID_SIDE
static readonly MamdaOrderImbalanceSide ASK_SIDE
static readonly MamdaOrderImbalanceSide NO_IMBALANCE_SIDE
Detailed Description
Member Function Documentation
ToString()
override string Wombat.MamdaOrderImbalanceSide.ToString ()
Returns the string name for the enumerated type.
Returns
Name for the type.
Referenced by Wombat.MamdaOrderImbalanceSide.toString().
toString()
string Wombat.MamdaOrderImbalanceSide.toString ()
Returns the string name for the enumerated type.
Returns
Name for the type.
References Wombat.MamdaOrderImbalanceSide.ToString().
getValue()
int Wombat.MamdaOrderImbalanceSide.getValue ()
Returns the integer value for the type.
This value can be used in switch statements against the public XXX_VALUE const members of the class.
Returns
The integer type.
equals()
bool Wombat.MamdaOrderImbalanceSide.equals (MamdaOrderImbalanceSide imbalanceSide)
Compare the two types for equality.
Parameters
imbalanceSide The object to check equality against.
Returns
Returns true if the integer value of both types is equal. Otherwise returns false.
Referenced by Wombat.MamdaOrderImbalanceSide.Equals(), and Wombat.MamdaOrderImbalanceSide.operator==().
Equals()
override bool Wombat.MamdaOrderImbalanceSide.Equals (object obj)
References Wombat.MamdaOrderImbalanceSide.equals().
GetHashCode()
override int Wombat.MamdaOrderImbalanceSide.GetHashCode ()
operator==()
static bool Wombat.MamdaOrderImbalanceSide.operator== (MamdaOrderImbalanceSide left, MamdaOrderImbalanceSide right) static
References Wombat.MamdaOrderImbalanceSide.equals().
operator!=()
static bool Wombat.MamdaOrderImbalanceSide.operator!= (MamdaOrderImbalanceSide left, MamdaOrderImbalanceSide right) static
valueToString()
static String Wombat.MamdaOrderImbalanceSide.valueToString (int value) static
Utility method for mapping type integer values to corresponding string values.
Returns "UNKNOWN" is the int type value is not recognised.
Parameters
value The int value for a MamdaOrderImbalanceSide
Returns
The string name value of the specified MamdaOrderImbalanceSide integer value
enumObjectForValue()
static MamdaOrderImbalanceSide Wombat.MamdaOrderImbalanceSide.enumObjectForValue (int value) static
Return an instance of a MamdaOrderImbalanceSide corresponding to the specified integer value.
Returns null if the integer value is not recognised.
Parameters
value Int value for a MamdaOrderImbalanceSide
Returns
Instance of a MamdaOrderImbalanceSide if a mapping exists.
References Wombat.MamdaOrderImbalanceSide.ASK_SIDE, Wombat.MamdaOrderImbalanceSide.BID_SIDE, and Wombat.MamdaOrderImbalanceSide.NO_IMBALANCE_SIDE.
Member Data Documentation
BID_SIDE_VALUE
const int Wombat.MamdaOrderImbalanceSide.BID_SIDE_VALUE = 0
BID_SIDE_IMBALANCE.
BID_SIDE
readonly MamdaOrderImbalanceSide Wombat.MamdaOrderImbalanceSide.BID_SIDE static
Initial value:
=
            new MamdaOrderImbalanceSide(valueToString(BID_SIDE_VALUE), BID_SIDE_VALUE)
Referenced by Wombat.MamdaOrderImbalanceSide.enumObjectForValue(), Wombat.MamdaOrderImbalanceListener.getImbalanceSide(), and Wombat.MamdaOrderImbalanceListener.getImbalanceVolume().
ASK_SIDE_VALUE
const int Wombat.MamdaOrderImbalanceSide.ASK_SIDE_VALUE = 1
ASK_SIDE_IMBALANCE.
ASK_SIDE
readonly MamdaOrderImbalanceSide Wombat.MamdaOrderImbalanceSide.ASK_SIDE static
Initial value:
=
            new MamdaOrderImbalanceSide(valueToString(ASK_SIDE_VALUE), ASK_SIDE_VALUE)
Referenced by Wombat.MamdaOrderImbalanceListener.clearCache(), Wombat.MamdaOrderImbalanceSide.enumObjectForValue(), and Wombat.MamdaOrderImbalanceListener.getImbalanceSide().
NO_IMBALANCE_VALUE
const int Wombat.MamdaOrderImbalanceSide.NO_IMBALANCE_VALUE = 2
NO_IMBALANCE.
NO_IMBALANCE_SIDE
readonly MamdaOrderImbalanceSide Wombat.MamdaOrderImbalanceSide.NO_IMBALANCE_SIDE static
Initial value:
=
            new MamdaOrderImbalanceSide(valueToString(NO_IMBALANCE_VALUE), NO_IMBALANCE_VALUE)
Referenced by Wombat.MamdaOrderImbalanceSide.enumObjectForValue().