OpenMAMDA C# API: Wombat.MamdaMultiParticipantManager Class Reference
Wombat.MamdaMultiParticipantManager Class Reference
MamdaMultiParticipantManager is a class that manages updates on a consolidated basis for securities that may be traded on multiple exchanges and which may have a national best bid and offer.
Inherits Wombat.MamdaMsgListener.
Public Member Functions
MamdaMultiParticipantManager (string symbol)
Only constructor for the class.
void addHandler (MamdaMultiParticipantHandler handler)
Add a specialized handler for notifications about the multi-participant security.
void addConsolidatedListener (MamdaMsgListener listener)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for the consolidated data.
void addParticipantListener (MamdaMsgListener listener, string partId)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for a participant.
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of the MamdaMsgListener Interface.
Detailed Description
MamdaMultiParticipantManager is a class that manages updates on a consolidated basis for securities that may be traded on multiple exchanges and which may have a national best bid and offer.
Developers are notified of each element available for the consolidated security, including the national best bid and offer, and each regional exchange (Market Maker). Developers can pick and choose which elements they wish to provide handling for (e.g., BBO-only, certain regional exchanges, etc.).
Specialized Listeners can be added to the MamdaMultiParticipantManager in response to the callbacks on the MamdaMultiParticipantHandler being invoked. Alternatively, the Listeners can be added up front if the participants are known in advance.
Note: the
MamdaMultiParticipantManager
can also be used for securities that are not traded on multiple exchanges.
Constructor & Destructor Documentation
MamdaMultiParticipantManager()
Wombat.MamdaMultiParticipantManager.MamdaMultiParticipantManager (string symbol)
Only constructor for the class.
No default available.
Parameters
symbol The group symbol for which the corresponding subscription was created.
Member Function Documentation
addHandler()
void Wombat.MamdaMultiParticipantManager.addHandler (MamdaMultiParticipantHandler handler)
Add a specialized handler for notifications about the multi-participant security.
Parameters
handler Concrete instance of the MamdaMultiParticipantHandler interface.
addConsolidatedListener()
void Wombat.MamdaMultiParticipantManager.addConsolidatedListener (MamdaMsgListener listener)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for the consolidated data.
Multiple listeners can be added.
Parameters
listener Concrete instance of the MamdaMsgListener interface.
addParticipantListener()
void Wombat.MamdaMultiParticipantManager.addParticipantListener (MamdaMsgListener listener, string partId)
Add a specialized message listener (e.g., a MamdaQuoteListener, MamdaTradeListener, etc.) for a participant.
Multiple listeners for each participant can be added.
Parameters
listener Concrete instance of the MamdaMsgListener interface.
partId The participant id for the instrument.
onMsg()
void Wombat.MamdaMultiParticipantManager.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Implementation of the MamdaMsgListener Interface.
Parameters
subscription
msg
msgType
Implements Wombat.MamdaMsgListener.
References Wombat.MamdaCommonFields.INDEX_SYMBOL, Wombat.MamdaCommonFields.ISSUE_SYMBOL, Wombat.MamdaMultiParticipantHandler.onConsolidatedCreate(), Wombat.MamdaMsgListener.onMsg(), Wombat.MamdaMultiParticipantHandler.onParticipantCreate(), Wombat.MamdaCommonFields.PART_ID, Wombat.Containers.Map.put(), Wombat.MamdaCommonFields.SYMBOL, and Wombat.Containers.Map.valueOf().