OpenMAMDA C# API: Wombat.MamdaBookAtomicBookHandler Interface Reference
Wombat.MamdaBookAtomicBookHandler Interface Reference
MamdaBookAtomicBookHandler is an interface for applications that need to know when a MamdaBookAtomicListener finishes processing a single book update.
Public Member Functions
void onBookAtomicBeginBook (MamdaSubscription subscription, MamdaBookAtomicListener listener, bool isRecap)
Method invoked before we start processing the first level in a message.
void onBookAtomicEndBook (MamdaSubscription subscription, MamdaBookAtomicListener listener)
summary> Method invoked when an order book is cleared.
void onBookAtomicClear (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg)
summary> Method invoked when a gap in orderBook reports is discovered.
void onBookAtomicGap (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg, MamdaBookAtomicGap gapEvent)
Detailed Description
MamdaBookAtomicBookHandler is an interface for applications that need to know when a MamdaBookAtomicListener finishes processing a single book update.
This may be useful for applications that wish to destroy the subscription from a callback as the subscription can only be destroyed after the message processing is complete. Furthermore, it allows applications to determine when to clear the book when a recap arrives.
Member Function Documentation
onBookAtomicBeginBook()
void Wombat.MamdaBookAtomicBookHandler.onBookAtomicBeginBook (MamdaSubscription subscription, MamdaBookAtomicListener listener, bool isRecap)
Method invoked before we start processing the first level in a message.
The book should be cleared when isRecap == true.
param name = "subscription">
//The MamdaSubscription handle. param name = "listener">
//The listener handling the recap. param name = "isRecap">
//Whether the first update was a recap. summary> Method invoked when we stop processing the last level in a message. We invoke this method after the last entry for the level gets processed. The subscription may be destroyed from this callback.
param name = "subscription">
//The MamdaSubscription handle. param name = "listener">
//The listener handling the recap. param name = "isRecap">
//Whether the first update was a recap.
Referenced by Wombat.MamdaBookAtomicListener.onMsg().
onBookAtomicEndBook()
void Wombat.MamdaBookAtomicBookHandler.onBookAtomicEndBook (MamdaSubscription subscription, MamdaBookAtomicListener listener)
summary> Method invoked when an order book is cleared.
param name = "subscription">
//The MamdaSubscription handle. param name = "listener">
//The listener handling the recap. param name = "msg">
//The MamaMsg that triggered this invocation.
Referenced by Wombat.MamdaBookAtomicListener.onMsg().
onBookAtomicClear()
void Wombat.MamdaBookAtomicBookHandler.onBookAtomicClear (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg)
summary> Method invoked when a gap in orderBook reports is discovered.
param name = "subscription">
//The MamdaSubscription handle. param name = "listener">
//The listener handling the recap. param name = "msg">
//The MamaMsg that triggered this invocation. param name = "gapEvent">
//The gap value object.
Referenced by Wombat.MamdaBookAtomicListener.onMsg().
onBookAtomicGap()
void Wombat.MamdaBookAtomicBookHandler.onBookAtomicGap (MamdaSubscription subscription, MamdaBookAtomicListener listener, MamaMsg msg, MamdaBookAtomicGap gapEvent)
Referenced by Wombat.MamdaBookAtomicListener.onMsg().