OpenMAMDA C# API: Wombat.MamdaOrderImbalanceHandler Interface Reference
Wombat.MamdaOrderImbalanceHandler Interface Reference
MamdaOrderImbalanceHandler is an interface for applications that want to have an easy way to handle order imbalance updates.
Public Member Functions
void onOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, MamaMsg msg)
Method invoked when a order imbalance is reported.
void onNoOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, MamaMsg msg)
Method invoked when a no order imbalance is reported.
void onOrderImbalanceRecap (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, MamaMsg msg)
Method invoked when the current order imbalance information is available.
Detailed Description
MamdaOrderImbalanceHandler is an interface for applications that want to have an easy way to handle order imbalance updates.
The interface defines callback methods for different types of order-imbalance events:
Member Function Documentation
onOrderImbalance()
void Wombat.MamdaOrderImbalanceHandler.onOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, MamaMsg msg)
Method invoked when a order imbalance is reported.
Parameters
subscription The subscription which received this update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
Referenced by Wombat.MamdaOrderImbalanceListener.onMsg().
onNoOrderImbalance()
void Wombat.MamdaOrderImbalanceHandler.onNoOrderImbalance (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, MamaMsg msg)
Method invoked when a no order imbalance is reported.
Parameters
subscription The subscription which received this update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
Referenced by Wombat.MamdaOrderImbalanceListener.onMsg().
onOrderImbalanceRecap()
void Wombat.MamdaOrderImbalanceHandler.onOrderImbalanceRecap (MamdaSubscription subscription, MamdaOrderImbalanceListener listener, MamaMsg msg)
Method invoked when the current order imbalance information is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The subscription which received this update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
Referenced by Wombat.MamdaOrderImbalanceListener.onMsg().