OpenMAMDA C# API: Wombat.MamdaOrderBookHandler Interface Reference
Wombat.MamdaOrderBookHandler Interface Reference
Process updates on the order book.
Public Member Functions
void onBookRecap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookDelta delta, MamdaOrderBookRecap fullBook)
Method invoked when an updated full order book image is available.
void onBookDelta (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookDelta delta, MamdaOrderBookRecap fullBook)
Method invoked when a regular update for an order book is available.
void onBookClear (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookDelta delta, MamdaOrderBookRecap fullBook)
Method invoked when an order book is cleared.
void onBookGap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookGap gapEvent, MamdaOrderBookRecap fullBook)
Method invoked when a gap in order book updates is discovered.
Detailed Description
Process updates on the order book.
Concrete instances of this interface are passed to the MamdaOrderBookListener in order for an application to receive callbacks on order book update events.
Member Function Documentation
onBookRecap()
void Wombat.MamdaOrderBookHandler.onBookRecap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookDelta delta, MamdaOrderBookRecap fullBook)
Method invoked when an updated full order book image is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
delta The order book delata generated from the update.
fullBook The full order book
Referenced by Wombat.MamdaOrderBookListener.onMsg().
onBookDelta()
void Wombat.MamdaOrderBookHandler.onBookDelta (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookDelta delta, MamdaOrderBookRecap fullBook)
Method invoked when a regular update for an order book is available.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
delta The order book delata generated from the update.
fullBook The full order book
Referenced by Wombat.MamdaOrderBookListener.onMsg().
onBookClear()
void Wombat.MamdaOrderBookHandler.onBookClear (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookDelta delta, MamdaOrderBookRecap fullBook)
Method invoked when an order book is cleared.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
delta The order book delata generated from the update.
fullBook The full order book
Referenced by Wombat.MamdaOrderBookListener.onMsg().
onBookGap()
void Wombat.MamdaOrderBookHandler.onBookGap (MamdaSubscription subscription, MamdaOrderBookListener listener, MamaMsg msg, MamdaOrderBookGap gapEvent, MamdaOrderBookRecap fullBook)
Method invoked when a gap in order book updates is discovered.
Parameters
subscription The subscription which received the update.
listener The listener which invoked this callback.
msg The MamaMsg that triggered this invocation.
gapEvent Access to details on the order book gap event.
fullBook The full order book
Referenced by Wombat.MamdaOrderBookListener.onMsg().