OpenMAMDA C# API: Wombat.Containers.Map Interface Reference
Wombat.Containers.Map Interface Reference
Inherited by Wombat.Containers.HashMap, and Wombat.Containers.SortedMap.
Public Member Functions
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
Member Function Documentation
size()
int Wombat.Containers.Map.size ()
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
isEmpty()
bool Wombat.Containers.Map.isEmpty ()
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
containsKey()
bool Wombat.Containers.Map.containsKey (object key)
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
Referenced by Wombat.MamdaMultiSecurityManager.onMsg().
containsValue()
bool Wombat.Containers.Map.containsValue (object value)
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
valueOf()
object Wombat.Containers.Map.valueOf (object key)
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
Referenced by Wombat.MamdaMultiSecurityManager.addListener(), Wombat.MamdaMultiSecurityManager.onMsg(), and Wombat.MamdaMultiParticipantManager.onMsg().
put()
object Wombat.Containers.Map.put (object key, object value)
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
Referenced by Wombat.MamdaMultiSecurityManager.onMsg(), and Wombat.MamdaMultiParticipantManager.onMsg().
remove()
object Wombat.Containers.Map.remove (object key)
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
putAll()
void Wombat.Containers.Map.putAll (Map m)
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
clear()
void Wombat.Containers.Map.clear ()
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
keySet()
Set Wombat.Containers.Map.keySet ()
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
values()
Collection Wombat.Containers.Map.values ()
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
entrySet()
Set Wombat.Containers.Map.entrySet ()
Implemented in Wombat.Containers.RedBlackTree, Wombat.Containers.TreeMap, and Wombat.Containers.HashMap.
Referenced by Wombat.Containers.RedBlackTree.entrySet(), Wombat.Containers.HashMap.putAll(), Wombat.Containers.RedBlackTree.putAll(), and Wombat.MamdaOptionExpirationDateSet.ToString().