OpenMAMDA C# API: Wombat.MamdaMsgListener Interface Reference
Wombat.MamdaMsgListener Interface Reference
MamdaMsgListener defines an interface for handling normal messages for a MamdaSubscription.
Inherited by Wombat.MamdaAuctionListener, Wombat.MamdaBookAtomicListener, Wombat.MamdaFundamentalListener, Wombat.MamdaMultiParticipantManager, Wombat.MamdaMultiSecurityManager, Wombat.MamdaOptionChainListener, Wombat.MamdaOrderBookListener, Wombat.MamdaOrderImbalanceListener, Wombat.MamdaQuoteListener, Wombat.MamdaSecurityStatusListener, and Wombat.MamdaTradeListener.
Public Member Functions
void onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Detailed Description
MamdaMsgListener defines an interface for handling normal messages for a MamdaSubscription.
Member Function Documentation
onMsg()
void Wombat.MamdaMsgListener.onMsg (MamdaSubscription subscription, MamaMsg msg, mamaMsgType msgType)
Invoked for each message received for the subscription to which the Listener is registered.
Parameters
subscription The MamdaSubscription to which this listener was registered.
msg The MamaMsg received by the underlying MAMA API and which resulted in this callback being invoked.
msgType The message type. e.g. INITIAL, RECAP, UPDATE etc.
Implemented in Wombat.MamdaTradeListener, Wombat.MamdaQuoteListener, Wombat.MamdaOrderImbalanceListener, Wombat.MamdaSecurityStatusListener, Wombat.MamdaOrderBookListener, Wombat.MamdaFundamentalListener, Wombat.MamdaBookAtomicListener, Wombat.MamdaAuctionListener, Wombat.MamdaMultiParticipantManager, Wombat.MamdaMultiSecurityManager, and Wombat.MamdaOptionChainListener.
Referenced by Wombat.MamdaSubscription.getMamaSubscription(), Wombat.MamdaMultiSecurityManager.onMsg(), and Wombat.MamdaMultiParticipantManager.onMsg().