OpenMAMDA C# API: Wombat.Containers.SortedMap Interface Reference
Wombat.Containers.SortedMap Interface Reference
Inherits Wombat.Containers.Map.
Inherited by Wombat.Containers.RedBlackTree, and Wombat.Containers.TreeMap.
Public Member Functions
Comparator comparator ()
SortedMap subMap (object from, object to)
SortedMap headMap (object toKey)
SortedMap tailMap (object fromKey)
object firstKey ()
object lastKey ()
Public Member Functions inherited from Wombat.Containers.Map
int size ()
bool isEmpty ()
bool containsKey (object key)
bool containsValue (object value)
object valueOf (object key)
object put (object key, object value)
object remove (object key)
void putAll (Map m)
void clear ()
Set keySet ()
Collection values ()
Set entrySet ()
Member Function Documentation
comparator()
Comparator Wombat.Containers.SortedMap.comparator ()
Implemented in Wombat.Containers.TreeMap, and Wombat.Containers.RedBlackTree.
subMap()
SortedMap Wombat.Containers.SortedMap.subMap (object from, object to)
Implemented in Wombat.Containers.TreeMap, and Wombat.Containers.RedBlackTree.
Referenced by Wombat.Containers.TreeMap.subMap().
headMap()
SortedMap Wombat.Containers.SortedMap.headMap (object toKey)
Implemented in Wombat.Containers.TreeMap, and Wombat.Containers.RedBlackTree.
Referenced by Wombat.Containers.TreeMap.headMap().
tailMap()
SortedMap Wombat.Containers.SortedMap.tailMap (object fromKey)
Implemented in Wombat.Containers.TreeMap, and Wombat.Containers.RedBlackTree.
Referenced by Wombat.Containers.TreeMap.tailMap().
firstKey()
object Wombat.Containers.SortedMap.firstKey ()
Implemented in Wombat.Containers.TreeMap, and Wombat.Containers.RedBlackTree.
lastKey()
object Wombat.Containers.SortedMap.lastKey ()
Implemented in Wombat.Containers.RedBlackTree, and Wombat.Containers.TreeMap.