OpenMAMDA C# API: Wombat.MamdaQuoteHandler Interface Reference
Wombat.MamdaQuoteHandler Interface Reference
MamdaQuoteHandler is an interface for applications that want to have an easy way to handle quote updates.
Public Member Functions
void onQuoteRecap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteRecap recap)
Method invoked when the current last-quote information for the security is available.
void onQuoteUpdate (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteUpdate update, MamdaQuoteRecap recap)
Method invoked when a quote update arrives.
void onQuoteGap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteGap gap, MamdaQuoteRecap recap)
Method invoked when a gap in quote updates is discovered.
void onQuoteClosing (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteClosing closingEvent, MamdaQuoteRecap recap)
Method invoked for a quote closing summary.
Detailed Description
MamdaQuoteHandler is an interface for applications that want to have an easy way to handle quote updates.
The interface defines callback methods for different types of quote-related events: quotes and closing-quote updates.
Member Function Documentation
onQuoteRecap()
void Wombat.MamdaQuoteHandler.onQuoteRecap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteRecap recap)
Method invoked when the current last-quote information for the security is available.
The reason for the invocation may be any of the following:
Initial image.
Recap update (e.g., after server fault tolerant event or data quality event.)
After stale status removed.
Parameters
subscription The MamdaSubscription reference.
listener The MamdaQuoteListener reference.
msg The MamaMsg that triggered this invocation.
recap Access to the current value of all fields.
Referenced by Wombat.MamdaQuoteListener.populateRecap().
onQuoteUpdate()
void Wombat.MamdaQuoteHandler.onQuoteUpdate (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteUpdate update, MamdaQuoteRecap recap)
Method invoked when a quote update arrives.
Parameters
subscription The MamdaSubscription reference.
listener The MamdaQuoteListener reference.
msg The MamaMsg that triggered this invocation.
update The MamdaQuoteUpdate event.
recap Access to the current value of all fields.
Referenced by Wombat.MamdaQuoteListener.populateRecap().
onQuoteGap()
void Wombat.MamdaQuoteHandler.onQuoteGap (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteGap gap, MamdaQuoteRecap recap)
Method invoked when a gap in quote updates is discovered.
Parameters
subscription The MamdaSubscription reference.
listener The MamdaQuoteListener reference.
msg The MamaMsg that triggered this invocation.
gap The MamdaQuoteGap event.
recap Access to the current value of all fields.
Referenced by Wombat.MamdaQuoteListener.populateRecap().
onQuoteClosing()
void Wombat.MamdaQuoteHandler.onQuoteClosing (MamdaSubscription subscription, MamdaQuoteListener listener, MamaMsg msg, MamdaQuoteClosing closingEvent, MamdaQuoteRecap recap)
Method invoked for a quote closing summary.
Parameters
subscription The MamdaSubscription reference.
listener The MamdaQuoteListener reference.
msg The MamaMsg that triggered this invocation.
closingEvent The MamdaQuoteClosing event.
recap Access to the current value of all fields.