OpenMAMDA C# API: Wombat.Containers.Iterator Interface Reference
Wombat.Containers.Iterator Interface Reference
Inherited by Wombat.Containers.ReadonlyIteratorOverEnumerator.
Public Member Functions
bool hasNext ()
object next ()
void remove ()
Member Function Documentation
hasNext()
bool Wombat.Containers.Iterator.hasNext ()
Implemented in Wombat.Containers.ReadonlyIteratorOverEnumerator.
Referenced by Wombat.Containers.ArrayListCollection.addAll(), Wombat.Containers.TreeSet.addAll(), Wombat.Containers.ArrayListCollection.containsAll(), Wombat.Containers.TreeSet.containsAll(), Wombat.Containers.RedBlackTree.containsValue(), Wombat.MamdaOptionChain.dump(), Wombat.Containers.HashMap.entrySet(), Wombat.Containers.RedBlackTree.entrySet(), Wombat.MamdaOptionExpirationDateSet.getExpirations(), Wombat.MamdaOptionChain.getStrikesWithinRangeSize(), Wombat.MamdaOptionChainView.onOptionSeriesUpdate(), Wombat.Containers.HashMap.putAll(), Wombat.Containers.RedBlackTree.putAll(), Wombat.Containers.ArrayListCollection.removeAll(), Wombat.Containers.TreeSet.removeAll(), Wombat.Containers.TreeSet.retainAll(), Wombat.MamdaOptionExpirationDateSet.toString(), and Wombat.MamdaOptionExpirationDateSet.ToString().
next()
object Wombat.Containers.Iterator.next ()
Implemented in Wombat.Containers.ReadonlyIteratorOverEnumerator.
Referenced by Wombat.Containers.ArrayListCollection.addAll(), Wombat.Containers.TreeSet.addAll(), Wombat.Containers.ArrayListCollection.containsAll(), Wombat.Containers.TreeSet.containsAll(), Wombat.Containers.RedBlackTree.containsValue(), Wombat.MamdaOptionChain.dump(), Wombat.Containers.HashMap.entrySet(), Wombat.Containers.RedBlackTree.entrySet(), Wombat.MamdaOptionExpirationDateSet.getExpirations(), Wombat.MamdaOptionChain.getStrikesWithinRangeSize(), Wombat.MamdaOptionChainView.onOptionSeriesUpdate(), Wombat.Containers.HashMap.putAll(), Wombat.Containers.RedBlackTree.putAll(), Wombat.Containers.ArrayListCollection.removeAll(), Wombat.Containers.TreeSet.removeAll(), Wombat.Containers.TreeSet.retainAll(), Wombat.MamdaOptionExpirationDateSet.toString(), and Wombat.MamdaOptionExpirationDateSet.ToString().
remove()
void Wombat.Containers.Iterator.remove ()
Implemented in Wombat.Containers.ReadonlyIteratorOverEnumerator.
Referenced by Wombat.Containers.RedBlackTree.entrySet().