OpenMAMDA C# API: Wombat.Containers.MapEntry Interface Reference
Wombat.Containers.MapEntry Interface Reference
Inherited by Wombat.Containers.RedBlackTree.Node.
Public Member Functions
object getKey ()
object getValue ()
object setValue (object value)
Member Function Documentation
getKey()
object Wombat.Containers.MapEntry.getKey ()
Referenced by Wombat.Containers.HashMap.entrySet(), Wombat.Containers.RedBlackTree.entrySet(), Wombat.Containers.HashMap.putAll(), Wombat.Containers.RedBlackTree.putAll(), Wombat.MamdaOptionExpirationDateSet.toString(), and Wombat.MamdaOptionExpirationDateSet.ToString().
getValue()
object Wombat.Containers.MapEntry.getValue ()
Referenced by Wombat.Containers.HashMap.entrySet(), Wombat.Containers.RedBlackTree.entrySet(), Wombat.Containers.HashMap.putAll(), Wombat.Containers.RedBlackTree.putAll(), Wombat.MamdaOptionExpirationDateSet.toString(), and Wombat.MamdaOptionExpirationDateSet.ToString().
setValue()
object Wombat.Containers.MapEntry.setValue (object value)