OpenMAMDA C# API: Wombat.Containers.SortedSet Interface Reference
Wombat.Containers.SortedSet Interface Reference
Inherits Wombat.Containers.Set.
Inherited by Wombat.Containers.TreeSet.
Public Member Functions
Comparator comparator ()
SortedSet subSet (object from, object to)
SortedSet headSet (object to)
SortedSet tailSet (object from)
object first ()
object last ()
Public Member Functions inherited from Wombat.Containers.Collection
int size ()
bool isEmpty ()
bool contains (object o)
object [] toArray ()
bool add (object o)
bool remove (object o)
bool containsAll (Collection c)
bool addAll (Collection c)
bool removeAll (Collection c)
bool retainAll (Collection c)
void clear ()
Public Member Functions inherited from Wombat.Containers.Iterable
Iterator iterator ()
Member Function Documentation
comparator()
Comparator Wombat.Containers.SortedSet.comparator ()
Implemented in Wombat.Containers.TreeSet.
subSet()
SortedSet Wombat.Containers.SortedSet.subSet (object from, object to)
Implemented in Wombat.Containers.TreeSet.
headSet()
SortedSet Wombat.Containers.SortedSet.headSet (object to)
Implemented in Wombat.Containers.TreeSet.
tailSet()
SortedSet Wombat.Containers.SortedSet.tailSet (object from)
Implemented in Wombat.Containers.TreeSet.
first()
object Wombat.Containers.SortedSet.first ()
Implemented in Wombat.Containers.TreeSet.
Referenced by Wombat.MamdaOptionChain.getStrikesWithinRangeSize(), Wombat.MamdaOptionChainView.onOptionSeriesUpdate(), and Wombat.MamdaOptionExpirationStrikes.trimStrikes().
last()
object Wombat.Containers.SortedSet.last ()
Implemented in Wombat.Containers.TreeSet.
Referenced by Wombat.MamdaOptionChainView.onOptionSeriesUpdate(), and Wombat.MamdaOptionExpirationStrikes.trimStrikes().