OpenMAMDA C# API: Wombat.Containers.Iterable Interface Reference
Wombat.Containers.Iterable Interface Reference
Inherited by Wombat.Containers.Collection.
Public Member Functions
Iterator iterator ()
Member Function Documentation
iterator()
Iterator Wombat.Containers.Iterable.iterator ()
Implemented in Wombat.Containers.TreeSet, and Wombat.Containers.ArrayListCollection.
Referenced by Wombat.Containers.ArrayListCollection.addAll(), Wombat.Containers.TreeSet.addAll(), Wombat.Containers.ArrayListCollection.containsAll(), Wombat.Containers.TreeSet.containsAll(), Wombat.Containers.RedBlackTree.containsValue(), Wombat.Containers.HashMap.entrySet(), Wombat.Containers.RedBlackTree.entrySet(), Wombat.MamdaOptionChainView.expirationIterator(), Wombat.MamdaOptionExpirationDateSet.getExpirations(), Wombat.MamdaOptionChainView.onOptionSeriesUpdate(), Wombat.Containers.HashMap.putAll(), Wombat.Containers.RedBlackTree.putAll(), Wombat.Containers.ArrayListCollection.removeAll(), Wombat.Containers.TreeSet.removeAll(), Wombat.Containers.TreeSet.retainAll(), Wombat.MamdaOptionExpirationDateSet.toString(), and Wombat.MamdaOptionExpirationDateSet.ToString().